### ISSUE TITLE
[web] Add action: "Duplicate" Space

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10016]
# Description

## User Stories

* > As a user I want a context menu option to duplicate a space so that I don't need to do copy & paste for the content and manual recreation for the space info.

## Value
- foster usage of spaces
- improve usability
- enhance productivity

## Acceptance Criteria
- Add new Context Menu Option "Duplicate" (`folders-line`)
- Option is available for Spaces (each: single or multiple)
- Action requires permission to create new spaces + read-permission on the to be duplicated space
- position: below "Rename"
- after clicking on "duplicate", the selected space gets duplicated with a space title like we do it on "keep both" in conflict resolution (i.e. duplicate of "Mars Mission" becomes "Mars Mission (1)")
- duplicate space title, subtitle, description, image and file/folder content, i.e. all metadata and data, but:
  - do not re-invite the space members of the original space
  - do not create link shares like in the original space
  - do not re-create metadata on files (like tags or shares), i.e. do a webdav copy operation
- duplication is not available in the admin-settings app. only in the project spaces overview and inside the root of a space.
- technical detail: use `loadingService` for the requests because the operation might take long...

## Organizational
**Please track times**

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

## Visuals
![screenshot_001865](https://github.com/owncloud/web/assets/26610733/8f7b93f4-0b39-487e-a7e6-f5d9a0996b35)

**Comment by dschmidt** [comment]
What exactly is duplicating a space? All members and content copied as well?

**Comment by JanAckermann** [comment]
I don't think that's possible, I guess same as with copy paste (that means just raw content, no meta data).

**Comment by kulmann** [comment]
Updated issue description. We need everything but members/shares. So basically the space skeleton (title, subtitle, description, image) and the content (files & folders).

**Comment by kulmann** [comment]
Regarding the icon, see https://github.com/owncloud/web/issues/9898#issuecomment-1819568896 ff for discussion.
