### ISSUE TITLE
[web] Add option to zoom in and out

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10017]
# Description

## User Stories

* > As a user who needs to adapt the size of the ui elements, I want an obvious option to zoom the ui so that I can adapt the ui size to my needs.

## Value

- accessibility

## Acceptance Criteria
- Add 2 new icons to the top right to in- or decrease the ui zoom (next to the right of the theme switcher)
- klick on zoom in zooms to:
  - 110%
  - 125%
  - 133%
  - 140%
  - 150%
  - 175%
  - 200%
- klick on zoom out zooms to:
  - 90%
  - 80%
  - 75%
  - 67%
  - 50%
  - 33%
  - 25%
- use `feedback-line` as feedback icon
- needs to be configurable on/off, by default off
- hint: try out how this behaves in app provider apps. not a blocker if it doesn't do anything there.
- Bonus: Maginfier-Icons should be used in the image viewer as well

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

### expected
![screenshot_001976](https://github.com/owncloud/web/assets/26610733/776341dd-dc76-4a1a-8451-7bf530869e6e)

### Alternative (dismissed idea)

![screenshot_001975](https://github.com/owncloud/web/assets/26610733/fb7d0318-005d-4ddf-a94e-cf49d6475db7)

**Comment by dschmidt** [comment]
Is that really something other applications do? 

To me that's a browser feature and nothing the application should handle. But we can make sure different browser zoom levels work fine

**Comment by tbsbdr** [comment]
yes, feels wired as we use our keyboard shortcuts to zoom in and out on a regular basis. 
I assume if you walk into a classroom and say: "zoom in", not many users will manage to do that, most will struggle. I'd like to give it a try because we got feedback, that eg. long filenames (>40 chars) are truncated for some users. I observed that many users open their browsers in windowed mode (not using the whole screen space), often 14'' Laptops screens and Windows usually adds a zoom of +125 or +150% which leads to really few space left for the Web UI elements. on the other side eg. CERN told us they run the web ui on wide screen in really high resolutions. so we are trying to squaring the circle. I think we have a good default since the last sizing improvements; still I'd like to be accessible for those who struggle using a pc. let's try

**Comment by JanAckermann** [comment]
I don't see that often, just in some very old applications, to me that feels clumsy and spams the UI. 
Not a fan 😢

**Comment by kulmann** [comment]
@tbsbdr are you fine to make this configurable with default off? We mainly want to try it for schools...
And later on maybe also a good candidate for the user preferences...

**Comment by lookacat** [comment]
@tbsbdr the only possibility to zoom the whole body is via the css zoom attribute on the body. E.g setting it to 1.5. Unfortunately this breaks the entire layout of the application (e.g. right click menu very displaced, two scrollbars when enough files)
We could adjust the font size which would not affect the whole layout (you can try that out via your browser settings). Should we go this way or do nothing. Maybe an alternative would be to give the user some kind of hint on how to use the browser zoom via keyboard (like google drive does it with ctrl+c ctrl+v)

**Comment by lookacat** [comment]
Closed because this will result in more issues than it resolves (there is no way to access the browsers zoom and every other way will create bugs)
This will resolve it:
https://github.com/owncloud/web/issues/10036
