### ISSUE TITLE
[web] Disable App Banner

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10015]
## Issue Description
The app banner is not in shape for a public release. It would need further improvements, which we can't schedule right now, as the priority for the feature is too low.
- detection for when to show the app banner does not work reliably, see https://github.com/owncloud/web/issues/9139#issuecomment-1779810169
- install link for users who don't have the app installed is missing, see https://github.com/owncloud/web/issues/9139#issuecomment-1779819629

**Please track times**

## Requirement / acceptance criterion
- Don't show the app banner if the `appBanner` key is missing or empty in the theme.json.
- adjust in dev docs how to enable/disable the feature

**Comment by tbsbdr** [comment]
cc @michaelstingl

**Comment by michaelstingl** [comment]
@tbsbdr aren't current config options sufficient? Isn't there an option to disable it?

- https://github.com/owncloud/web/issues/9836
- https://github.com/owncloud/web/pull/9872

**Comment by tbsbdr** [comment]
naa, there is no option to disable it 😢

**Comment by JanAckermann** [comment]
We could add an option alternatively?

**Comment by michaelstingl** [comment]
Yes, config option please, and keep it enabled on our [continuous deployments](https://owncloud.dev/ocis/deployment/continuous_deployment/). This way, the teams can continue iterate on it and improve.

**Comment by JanAckermann** [comment]
Let's discuss this in spring planning today

**Comment by kulmann** [comment]
Thanks for feedback, I updated the issue description accordingly. We need to decide if we want to put disabling the app banner into the config.json where we would usually do something like that or into the theme.json where all the app banner info lives.
