### ISSUE TITLE
UX - upload progress

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#1001]
On Thursday I met with @wuenschedesign and we discussed the upload progress. At the moment it's displayed in a dropdown which is accessed by clicking on progress circle next to the "new" button.

![image](https://user-images.githubusercontent.com/25989331/56579611-ef114480-65d0-11e9-9833-53bda5a939bb.png)

![image](https://user-images.githubusercontent.com/25989331/56579614-f1739e80-65d0-11e9-82fa-d17f4f7f124e.png)

This can be confusing for the user since there is basically no way for him to know that there is that dropdown. There are also a few other issues. After a file is uploaded it disappears from that dropdown without any notification that the file was uploaded. Which can confuse the user when he has a lot of files and doesn't see the file in the list. Also, there is at the moment no interaction with the file while it's being uploaded. User can't stop the upload.

Andreas tried to come up with some prototypes to fix these issues and this is what he managed to do so far.

![image](https://user-images.githubusercontent.com/25989331/56580139-30562400-65d2-11e9-8a62-74f472659f7f.png)

Here you can see that one option could be to display the file in the list already when it's being uploaded. At the same time, there would be implemented upload manager that would become visible once the upload would begin. In that manager, you would have the option to filter files by their status so you don't need to scroll down and look for them.

![image](https://user-images.githubusercontent.com/25989331/56580355-a8244e80-65d2-11e9-80a1-88fe84e3c1cb.png)

With this upload manager, we'd like to introduce also a few new actions that the user can do after the start of the upload.

- Cancel the upload
- Pause the upload
- In case of an already existing file either rename the file or cancel the file

It would be great to get also your thought on this topic.

**Comment by DeepDiver1975** [comment]
>     * In case of an already existing file either rename the file or cancel the file

FYI: The current UX is based on box.net - via the new menu only new files can be uploaded. For uploading a new version of a file we will introduce another option when selecting a file ... or something like that ...

**Comment by DeepDiver1975** [comment]
- showing the upload progress in the file list is nice - but please keep in mind that there are multiple pages of files - you will never see all files in progress in one screen. So this can only be nice eye candy. We need some central (non blocking) way of displaying operations progress.

Please note that this is not only about upload - also delete, copy and move are longer running operations which have a progress and need to be displayed to the user in the 'upload manager'

Furthermore not all operations are pauseable/stoppable ...

Remaining execution time cannot be predicted - generally speaking ...

**Comment by DeepDiver1975** [comment]
Next step should be some rapid prototyping - we need to schedule time for this ....

**Comment by pmaier1** [comment]
Yes, as discussed, this looks pretty nice and should not only be used for uploads but for general file operations that take time and/or are queued. So this would maybe rather be a 'file operation manager' or so. 

- General question: Is this thought as an overlay or using the regular files view?
- Pausing an upload is nice but I would regard it as optional
- File name collisions should be handled via versioning (upload) or should be prevented https://github.com/owncloud/enterprise/pull/3297

> After a file is uploaded it disappears from that dropdown without any notification that the file was uploaded. Which can confuse the user when he has a lot of files and doesn't see the file in the list. 

- Keeping a history for the time of the session or similar might make sense for that users can verify whether operations were successful or not and related issues.

> Also, there is at the moment no interaction with the file while it's being uploaded. User can't stop the upload.

- It must at least be possible to stop a whole upload process. Removing single files from the queue maybe becomes too complicated.

**Comment by pascalwengerter** [comment]
Closing this since the `web-app-files` has received a major overhaul early this year and the upload progress is prominently visible now. 

Pausing/resuming/cancelling uploads should live in a dedicated ticket which can be added as necessary (if it doesn't exist yet) and presumably need (some) backend implementations too
