### ISSUE TITLE
Not all the archive files have appropriate icons

### ISSUE THREAD

**Issue by 2403905** [owncloud/web#10031]
## Describe the bug
The files tar.gz and tar.bz2 don't have the appropriate icon in a UI

## Steps to reproduce
1. Create the archive files `tar cfvj archive.tar.bz2 file.txt`, `tar cfzv archive.tar.gz file.txt`
2. Upload the files to the personal space

## Expected behavior
The archive files have appropriate icons

## Actual behavior
The archive files have the default icons

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>

<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

## Additional context
<img width="602" alt="Screenshot 2023-11-21-1" src="https://github.com/owncloud/web/assets/11679989/5b6dc16f-5a0b-48b3-b383-7c223ff2d6be">

**Comment by pascalwengerter** [comment]
Happy to work on this, what's the definition of done? CC @tbsbdr https://en.wikipedia.org/wiki/List_of_archive_formats lists quite a lot of possible endings, some of which may be pretty exotic? I could all of them (like in https://github.com/owncloud/web/issues/9966) or a reduced list

**Comment by kulmann** [comment]
> Happy to work on this, what's the definition of done? CC @tbsbdr https://en.wikipedia.org/wiki/List_of_archive_formats lists quite a lot of possible endings, some of which may be pretty exotic? I could all of them (like in #9966) or a reduced list

Please only add the two from the issue description, `.tar.gz` and `.tar.bz2`. If we don't have `.7z` then please add that as well. I still consider these 3 mainstream formats. Should be good for now.
