### ISSUE TITLE
Foldername gets converted to integer

### ISSUE THREAD

**Issue by lookacat** [owncloud/web#10035]
## Describe the bug
Foldername gets converted to integer, super edge case but it may be interesting to find out why

## Steps to reproduce
1. Create a folder with a name like "333333333334444444444"
2. The folder name results in an integer e.g.  "3.3333343434343433e+36" in the files list and the sidebar panel

## Expected behavior
The folder name should be a string

## Actual behavior
The folder name gets somehow converted to int

**Comment by jacob-nv** [comment]
@lookacat Unable to reproduce. Is it still and issue? Could you send video showing how to reproduce?
