### ISSUE TITLE
Failed at pnpm install

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#10044]
`pnpm-lock.yaml` is not up to date with packages/web-app-files/package.json. So fails in pnpm install.

Build:
https://drone.owncloud.com/owncloud/web/40557/4/2

**Comment by saw-jan** [comment]
might be due to the changes in `owncloudci/nodejs:18` image

**Comment by saw-jan** [comment]
I see two options here:
1. use `pnpm install --no-frozen-lockfile` in the drone config
2. update the lock file and merge the PR (also bump commit to ocis stable branch) 

CC @ScharfViktor

**Comment by JammingBen** [comment]
> update the lock file and merge the PR (also bump commit to ocis stable branch)

In that case we should probably also update the pnpm version in the `package.json` on the `stable-7.1` branch, like we've done in https://github.com/owncloud/web/pull/9823.

**Comment by ScharfViktor** [comment]
so we're going the second way + update pnpm + update playwrigth https://github.com/owncloud/web/pull/9937 if it possible

**Comment by SwikritiT** [comment]
fixed with the merge of https://github.com/owncloud/web/pull/10051
