### ISSUE TITLE
Password input actions won't be disabled when the input is

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10084]
## Describe the bug
When disabling a password text input, the field itself will be disabled but the actions inside are still clickable.

## Steps to reproduce
1. Disable a password text input via `:disabled="true"`

## Expected behavior
The buttons are greyed out like the input and can't be clicked.

## Actual behavior
The buttons are not greyed out and can still be clicked.

<img width="439" alt="image" src="https://github.com/owncloud/web/assets/50302941/08fd99fc-34e1-40e7-9541-00e799c3491d">

**Comment by lookacat** [comment]
We've decided to not display the buttons at all if the input is disabled.
