### ISSUE TITLE
Space quota is not being duplicated

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#10123]
ocis 5.0.0-alpha.3+62afc6e9b
web 8.0.0-alpha.11

Steps: 
- create space `s1` 
- increase the quota to 10 GB and upload more than 1 GB of data into the space.
- try to duplicate the space

Actual: 
first request POST `https://host.docker.internal:9200/graph/v1.0/drives` creates space with 1Gb default quota so not all data is copied to new space

<img width="1736" alt="image" src="https://github.com/owncloud/web/assets/84779829/8a59889a-4eaa-46a2-9a9e-61b7c66487c6">

Expected: web copies space with same quota (10Gb in my case)
`body: {"name":"s2 (1)","description":"try to duplicate me","quota":{"total":value}}: `

**Comment by JammingBen** [comment]
Whoever is taking action here: we need to check if a quota can be passed to `createDrive`. If not, we need to update the drive's quota manually in such case.

**Comment by JammingBen** [comment]
@jacob-nv Could you please have a look here? `useSpaceActionsDuplicate` is the relevant action for this.

**Comment by JanAckermann** [comment]
@jacob-nv sorry I already started with that :(
