### ISSUE TITLE
Appswitcher: Harmonize Default App Icon Style

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10121]
## Steps to reproduce
1. Click on the Apps Menu
2. App Icon style is not harmonized

![screenshot_002125](https://github.com/owncloud/web/assets/26610733/a25286c6-c20a-4277-ab5b-3a1da02ff07a)

## Expected behavior
- the style should be harmonized with the ui - unsure if its the `color` or the `skeuomorphic` effect 
- As Microsoft demonstrates, the icons can be colorful but need some kind of alignment

![screenshot_002126](https://github.com/owncloud/web/assets/26610733/08a9f8b2-b509-454a-8afa-f13d68829c46)

## Actual behavior
- The current icon style is quite outstanding and thus does not feel like it belongs to the rest of the ui

**Comment by tbsbdr** [comment]
@lookacat can you relate to what I describe? Its about style - maybe you can help with fingertip feel

**Comment by JanAckermann** [comment]
My feeling is that the icons just don't look good currently 🤔

**Comment by tbsbdr** [comment]
yeah same, but why? what needs to change?

**Comment by JanAckermann** [comment]
@tbsbdr In a perfect world we would have a designer creating nice buttons with colors all of the same palette. Like you see in your example and get probably rid of the blue background 😮‍💨

**Comment by JanAckermann** [comment]
I also feel that we could profit from a different orientation instead of a list view. 

Like that ![image](https://github.com/owncloud/web/assets/26169327/01f843ee-53a8-4e78-8802-9288f05763ec)

**Comment by kulmann** [comment]
> I also feel that we could profit from a different orientation instead of a list view.
> 
> Like that ![image](https://private-user-images.githubusercontent.com/26169327/290083316-01f843ee-53a8-4e78-8802-9288f05763ec.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTU2MTIsIm5iZiI6MTcwMjQ1NTMxMiwicGF0aCI6Ii8yNjE2OTMyNy8yOTAwODMzMTYtMDFmODQzZWUtNTNhOC00ZTc4LTg4MDItOTI4OGYwNTc2M2VjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwODE1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjhlNmNiNGE3OGVkNjk5YjUxY2Y0ZjUwNGEwZjNjODRlMmFmZTEwZWNkZmRiZDQ5NTNlYjU3OWNiYmZhNGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JXX8ZJhfo3RYw7jNMPkMwSoJE6fX_e8LJG87esED74g)

@lookacat already tried that before, but we found out that the space for the label below the icon is **very** limited then and decided against it.

**Comment by lookacat** [comment]
yep i agree the colors are not great, in darkmode it seems fine but in light mode they are off. Also we should never have icons with almost the same color that looks weird too.

**Comment by lookacat** [comment]
I also think the active background is too dark and prominent

**Comment by lookacat** [comment]
![Screenshot (13)](https://github.com/owncloud/web/assets/786551/7e6fd115-45b0-4cf5-982a-211375ba36ed)
![Screenshot (14)](https://github.com/owncloud/web/assets/786551/513b141f-ef6f-4d5f-9112-ed6704cbc69e)

@tbsbdr how about this?

**Comment by tbsbdr** [comment]
yes, I think that's better than before
