### ISSUE TITLE
[Feature]: Support to work with .dwb (Draw.io Drawingboard) file in integrated draw.io app

### ISSUE THREAD

**Issue by inferno-umar** [owncloud/web#10140]

**Comment by dschmidt** [comment]
Is this just another file type that draw.io supports? So do we just need to add it to the list of supported extensions and we're done?

**Comment by inferno-umar** [comment]
Where to add that config?

**Comment by JanAckermann** [comment]
@inferno-umar i checked out the current version of drawio.com tried to export existent projects to dwb which is not possible and open multiple dwb files from this source:

http://justsolve.archiveteam.org/wiki/DWB
https://github.com/tribula-mel/high_freq_alt/
Unfortunately I get errors or unreadable files. 

I also can't find any information about `drawio drawboading` could you hand over some resources?

**Comment by inferno-umar** [comment]
Well I researched it further, .dwb files are supported by draw.io(embedded in NextCloud) which was our former platform, but .dwb files aren't supported by draw.io Desktop or Web version.

Seems Nextcloud has implemented handling .dwb files with draw.io in some mysterious way, but the NextCloud's draw.io .dwb features still work in oCIS' draw.io app, just the format .dwb is not supported instead .drawio format is supported, which isn't big deal for us.
