### ISSUE TITLE
[docs] Theming dev docs outdated

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#10146]
## Describe the bug
Theming dev docs are outdated since https://github.com/owncloud/web/pull/9698 has been merged.

## Steps to reproduce
1. Visit https://owncloud.dev/clients/web/theming/
2. Try to follow the docs for building themes

## Expected behavior
Instructions for building themes are correct.

## Actual behavior
Nothing works anymore. Be confused.

**Comment by JammingBen** [comment]
Note that there is also https://github.com/owncloud/docs-ocis/issues/678 to keep track of the changes on our official doc page. We also need to communicate the changes there so Martin can update the docs accordingly.
