### ISSUE TITLE
"Failed to create link" when password is forbidden

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#10142]
## Describe the bug

UX is not great

## Steps to reproduce
1. configure a password policy and forbid a certain password like "tooeasy"
2. create a link and use password "tooeasy"

## Expected behavior

User get's a message that this password is not allowed

I assume that's possible because the ocs request returns:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
   <meta>
      <status>error</status>
      <statuscode>400</statuscode>
      <message>Unfortunately, your password is commonly used. please pick a harder-to-guess password for your safety</message>
   </meta>
</ocs>
```

## Actual behavior

![image](https://github.com/owncloud/web/assets/34452982/41a4266a-9d5e-443a-b9bc-d4ed08e1c5ef)

## Setup

ownCloud Web UI 8.0.0-alpha.13
Infinite Scale 5.0.0-alpha.6

**Comment by kulmann** [comment]
Please add the default role to the `steps to reproduce`
