### ISSUE TITLE
webUrl of virtual/shares leads to an empty page

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#10141]
## Describe the bug
when navigating with the browser to the `webUrl` provided by `/graph/v1.0/me/drives` for `"virtual/shares"` it only an empty page is shown

## Steps to reproduce
1. query  `/graph/v1.0/me/drives`
2. navigate to the `webUrl` given for  `"virtual/shares"`

## Expected behavior
some useful information shown, maybe the shared with me page

## Actual behavior
![grafik](https://github.com/owncloud/web/assets/2425577/ca6f59f3-31ec-46b2-915f-c28419c8bc84)

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
PROXY_ENABLE_BASIC_AUTH=true OCIS_INSECURE=true PROXY_HTTP_ADDR=0.0.0.0:9200 OCIS_URL=https://host.docker.internal:9200 PROXY_TRANSPORT_TLS_KEY=./ocis.pem PROXY_TRANSPORT_TLS_CERT=./ocis.crt ./ocis/bin/ocis server
```

</p>
</details>

**Comment by kulmann** [comment]
Could you please provide the full browser url in the issue text?

**Comment by individual-it** [comment]
`https://host.docker.internal:9200/f/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668`

**Comment by kulmann** [comment]
Ok, thank you. Then this is basically the same issue as https://github.com/owncloud/web/issues/9867 with the difference that #9867 had the share jail id triplet, while this issue has the 2-segment id only.
