### ISSUE TITLE
No file extension given on new file creation

### ISSUE THREAD

**Issue by nicholas-wilson-au** [owncloud/web#10170]
Go to [infinite.owncloud.com](https://infinite.owncloud.com/) and turn off show file extensions. Then create a new excel, word or plain text file. For me, no extension is defaulted so it creates a file with no file extension. I expect it should still give a file extension to a new file.

**Comment by nicholas-wilson-au** [comment]
@JanAckermann and @kulmann Here is the issue.

**Comment by kulmann** [comment]
Thanks for the bug report @nicholas-wilson-au 

@JanAckermann fixed it via https://github.com/owncloud/web/pull/10169 - next step: needs a release.
