### ISSUE TITLE
Groups created through keycloak is not available in oCIS

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/web#10171]
## Describe the bug
When a group is created in keycloak, the created group is not available in oCIS. Due to which actions like, `sharing to group`, `adding user to group`, `deleting users from group` is not possible.

## Steps to reproduce
1. Create a group through keycloak
2. Check the created group in oCIS

## Expected behavior
Created group should be available in oCIS.

## Actual behavior
The created group is not available in oCIS.

### Group created in keycloak
![image](https://github.com/owncloud/web/assets/83579989/daa885ff-6e74-4e70-b156-38918a5bf9bf)

### No groups available in oCIS
![image](https://github.com/owncloud/web/assets/83579989/09691768-e3f3-4c42-8d28-ba5d843adcb1)

## Setup
idp: keycloak

**Comment by saw-jan** [comment]
^
CC @wkloucek

**Comment by wkloucek** [comment]
That's currently not supported. Probably it is also a backend feature from what I know.

**Comment by JanAckermann** [comment]
We only fetch groups via graph, if they are not provided, we are not able to display them

**Comment by rhafer** [comment]
We have a feature request for that already: https://github.com/owncloud/ocis/issues/5538
