### ISSUE TITLE
Move Theme switcher to Account Settings Page

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10181]
## Improvement proposal
- Move theme switcher drop to account settings
- Remove theme icon from top bar to declutter top bar as it has now the new sidebar toggle button 
- Bonus: Provide an Auto-Option (default) to adjust the dark/light theme to system setting

![image](https://github.com/owncloud/web/assets/26610733/e83a0a90-e7d8-477f-9edd-9020ab6a5415)

**Comment by JanAckermann** [comment]
We will allow anon users (public link) to access a minimal version of the preferences.
