### ISSUE TITLE
Impossible to override metadata_url

### ISSUE THREAD

**Issue by mtb-xt** [owncloud/web#10184]
## Describe the bug
It seems that currently it is impossible to override WEB_OIDC_METADATA_URL. Even when it's defined, wrong variable is passed to oidc-client-ts.

If we look here - https://github.com/authts/oidc-client-ts/blob/main/src/OidcClientSettings.ts#L32 - we can see that the library you guys are using for OIDC, expects the `metadataUrl` option. 
But if we look at your types - https://github.com/owncloud/web/blob/2b3fe6a5e7f5682eea023d9aac2c665071a15ead/packages/web-pkg/src/configuration/types.ts#L58  - you are calling it `metadata_url`. So even if I override this setting (and it appears in /config.json) - the web app still tries the default path, which is different for me, because I use Authentik.

Looks like it was broken during the refactoring in this commit here - https://github.com/owncloud/web/commit/434a622b6d77d4c3040a973fd08535f0e2d97e7d  - before this, you also called it metadataUrl.

## Steps to reproduce
1. Use Authentik for OIDC
2. Configure env variable - WEB_OIDC_METADATA_URL to try to override the URL.
3. Check that config.json includes the correct metadata_url
4. web app still uses the default url.

See screenshots 
![image](https://github.com/owncloud/web/assets/11381295/48422c77-165b-4a41-9f79-f15522c26cba)
![image](https://github.com/owncloud/web/assets/11381295/a8165d35-1967-4359-83c5-d87df32f8708)

## Setup
Installed from helm chart, 

<details>
<p>

```console
~ $ env | grep WEB_OIDC
WEB_OIDC_METADATA_URL=https://authentik.<redacted>.one/application/o/ocis-web/.well-known/openid-configuration
WEB_OIDC_CLIENT_ID=<redacted>
WEB_OIDC_AUTHORITY=https://authentik.<redacted>.one
~ $ env | grep WEB_UI
WEB_UI_CONFIG_SERVER=https://ocis.<redacted>.one
WEB_UI_THEME_SERVER=https://ocis.<redacted>.one
```

</p>
</details>

**Comment by kulmann** [comment]
@mtb-xt thank you for the bug report. Please note that despite this issue being closed, it will take some more time to bring web to ocis and helm charts. Please expect this to be available some time next week.
