### ISSUE TITLE
Translations with pGettext won't be translated

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/web#10216]
## Describe the bug
We use pGettext in some of our code (similar to gettext, but adds a context for the po/pot files). Obvious there is something wrong in the i18n chain as the strings won't be translated. 

## Steps to reproduce
1. open web 
2. change language to german
3. right click on a file
4. Copy action shows Copy instead of Kopieren

## Actual behavior
A clear and concise description of what happened.

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by dschmidt** [comment]
Maybe it's finally time to switch over to the vue3-gettext extractor...
