### ISSUE TITLE
translation-sync failing for zh-Hans

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#10217]
## Describe the bug
https://drone.owncloud.com/owncloud/translation-sync/3135/40/7
`Error: ENOENT: no such file or directory, open '../../web-pkg/l10n/locale/zh-Hans/LC_MESSAGES/app.po'`

The nightly translation-sync job is failing with the above message.

## Steps to reproduce
Re-run translation-sync in drone - it fails again.

## Expected behavior
Translations are automatically synced from Transifex.

## Actual behavior
translation-sync fails.

## Setup
N/A

**Comment by kulmann** [comment]
Thanks for opening the issue. I'll try to get the transifex cli setup locally today to fix it...

**Comment by kulmann** [comment]
Fixed via https://github.com/owncloud/web/pull/10218
