### ISSUE TITLE
Convert remaining JS unit tests to TS

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10250]
We have a few unit tests left in the design system that still need to be converted to TypeScript. After doing that we probably can (and should) remove the `babel-jest` dependency.

**Comment by JammingBen** [comment]
It seems that the remaining JS tests are for the ODS docs... let's wait for https://github.com/owncloud/web/pull/10243 and then decide what to do with them. Maybe we can remove them, I'm not sure how valuable they actually are.

**Comment by dschmidt** [comment]
Yeah, unit tests for the docs seems a bit pointless, I would love e2e tests on the built artifacts tho
