### ISSUE TITLE
Share with expiration date. User cannot create next share without expiration date(previously established)

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#10273]
Imagine that a user wants to share a resource with multiple users with and without an expiration date, he: 
- opens shares sidebar
- creates share with expiration date to `user1`
- tries to create share without expiration date to `user2`

Actual: it's not possible to create next shares without expiration date. 
work around: user can create next share with expiration date and after that delete expiration date. Or reopen sidebar panel

https://github.com/owncloud/web/assets/84779829/d61d03e3-a77f-4a25-bb63-0c4ab4c46947

Expected: we can change the role. I would suggest being able to delete expiration date,
<img width="463" alt="Screenshot 2024-01-03 at 16 22 55" src="https://github.com/owncloud/web/assets/84779829/2cabb82a-a743-4a47-9004-3315f0ffc9c9">

**Comment by kulmann** [comment]
Good finding! That should be fixed for the upcoming `8.0.0` release, so a PR with target `stable-8.0` is needed. Fix should be an additional item in the drop down `Remove expiration date`, like we already have it on existing shares that currently hold an expiration date.

**Comment by kulmann** [comment]
@jacob-nv is this something you could take over quickly?

**Comment by jacob-nv** [comment]
@kulmann No problem

**Comment by jacob-nv** [comment]
@kulmann There's by default way to remove expiration date.
![image](https://github.com/owncloud/web/assets/138569835/8b3a64c2-0e02-4b74-bd64-d2135b5515ca)
Only issue is that it breaks after "share". This can be fixed just by setting expirationDate to null after submit.

**Comment by kulmann** [comment]
Sounds good 👍

**Comment by kulmann** [comment]
Was fixed via https://github.com/owncloud/web/pull/10294
