### ISSUE TITLE
[Spaces] Tiles view not shown as grid

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/web#10299]
## Describe the bug

![CleanShot 2024-01-05 at 16 01 57](https://github.com/owncloud/web/assets/214010/9eeb4df4-023e-4d73-b67f-bfc73e6c46ff)

## Expected behavior

Should look like here:
- https://github.com/owncloud/web/issues/10040

## Actual behavior

Tiles are listed in only one column

## Setup

https://ocis.ocis-traefik.latest.owncloud.works/files/spaces/projects?tiles-size=2&files-spaces-projects-view-mode=resource-tiles&items-per-page=100&sort-dir=asc&sort-by=name

```
[Log]  ownCloud Web UI 8.0.0-rc.1  (index.html-MZztZoFM.mjs, line 1)
[Log]  Infinite Scale 5.1.0-prealpha+c46db2b7c Community  (index.html-MZztZoFM.mjs, line 1)
```

@tbsbdr @kulmann

**Comment by kulmann** [comment]
Congrats, you're the first to notice this in a time span of 2 weeks. 🙈 Thank you for reporting it!

@JammingBen already found this and fixed it in https://github.com/owncloud/web/pull/10261 
But it's not yet in ocis... will arrive there next week.

**Comment by kulmann** [comment]
> I only searched for issues, not the PR's…

Which is legit! Usually we have issues for bugs. In this case we thought `tiny one, let's just quickly fix it and be done with it`... should have created an issue anyways.
