### ISSUE TITLE
Remove checks for space and share jail support

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10298]
The code base has many places where we check if the server supports spaces and/or share jail. We needed this until recently because Web still supported oC10, which has none of these, however, with the dropped support and the only supported server being oCIS we can (and should) remove those checks.

Before this can happen in Web, oCIS first needs to remove the option to control these 2 things via config/env var.

**Comment by Lymah123** [comment]
Hi @JammingBen , can I work on the issue?

**Comment by kulmann** [comment]
> Hi @JammingBen , can I work on the issue?

Status is `Blocked`, so it's not actionable. Sorry ;-)

**Comment by Lymah123** [comment]
> > Hi @JammingBen , can I work on the issue?
> 
> Status is `Blocked`, so it's not actionable. Sorry ;-)

Alright. Thanks for the prompt response.

**Comment by JanAckermann** [comment]
Fixed via:
- https://github.com/owncloud/web/pull/10437
- https://github.com/owncloud/web/pull/10436
