### ISSUE TITLE
Remove icon mapping injection

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10305]
Currently, the icon mapping is being injected because the `ResourceIcon.vue` component was living in the ODS in the past and it was the most convenient way to retrieve runtime data there (see https://github.com/owncloud/web/blob/master/packages/web-runtime/src/container/bootstrap.ts#L274).

However, since the component is now living in `web-pkg`, there is no need to inject it anymore. Instead the component should query that information from the runtime / a composable / whatever.

**Comment by jacob-nv** [comment]
@JammingBen I don't see really why change it, applications are required to build the icon maps. This happens at the start. Provide and Inject seem like appropriate tools to pass down this data. I don't see much alternative to how to build this data once and provide them to components outside of pinia storage. I might be missing something

**Comment by JammingBen** [comment]
Ahh okay, seems like I misunderstood it. Then we'll leave it as it is, thank you for digging though!
