### ISSUE TITLE
Shortcut. No error message when opening a shortcut to a deleted resource

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#10315]
ocis: 5.1.0-prealpha+465c9e3c20
web: 8.0.0-rc.1

when user opens shortcut for unshared resource or resource from disabled/deleted space he gets `PROPFIND 404` but doesn't get any message on web 

Steps: 
- create project space `s1` 
- in the personal space create shortcut to space `s1`
- disable `s1`
- try to open shortcut

Expected: to provide an error message like:
 <img width="448" alt="image" src="https://github.com/owncloud/web/assets/84779829/9363a354-e61b-4e50-b0d6-d9ec61f1bcdf">
 

Actual: no message that resource not found. Only just a blank screen
<img width="1437" alt="Screenshot 2024-01-09 at 22 23 34" src="https://github.com/owncloud/web/assets/84779829/ff503fad-e11c-4bf4-a009-17ee835468e7">

2. Case with hidden shares: 
- `admin` shares `file.txt` to `katherine`
- `katherine` creates shortcut for `file.txt` in personal space
- `katherine` hides `file.txt`
- `katherine` opens shortcut

Expect: not sure here. should we open text editor? or it works as expected

Actual: opened shares jail page 

https://github.com/owncloud/web/assets/84779829/e0e09090-e4f7-40b7-96af-b9ab35e01212

**Comment by JammingBen** [comment]
Case 1 is definitely valid. Since we have the fileId we could do a PROPFIND with that id to check if the user has access to the resource before redirecting them via private link.

Case 2 is a known issue currently. Hidden shares should (and will) be accessible in the future, but we need to implement sharing NG first.

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/web/pull/10321
