### ISSUE TITLE
User Settings not scroll able

### ISSUE THREAD

**Issue by dj4oC** [owncloud/web#10313]
## Describe the bug
If I use a small screen, I cannot reach the lower settings on the account page screen, since I cannot scroll the screen vertically.

Tested with Web 8.0

<img width="592" alt="image" src="https://github.com/owncloud/web/assets/50302941/44283f8b-8cb0-4505-a86f-0498d6044abf">

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/web/pull/10318
