### ISSUE TITLE
String rename: Search "In here", "Everywhere"

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10339]
Let's please rename the scope filter in search bar:

- ~In here~ -> Current folder
- ~Everywhere~ -> All files

Background
- "In here" and "Everywhere" were not well-received because it made testusers think and and they described it as unexpected wording.

**Comment by JanAckermann** [comment]
Again :D ?

**Comment by tbsbdr** [comment]
♻️ yes
