### ISSUE TITLE
Show post-processing info in versions sidebar panel

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10348]
## Is your feature request related to a problem? Please describe.
A file version can be in a processing state just like a normal file, which means a user can't do anything with such version until it has been processed by the server. Currently, the versions panel does not show if a version is post-processing or not. This can lead to the user trying to perform actions with a version which will fail eventually.

## Describe the solution you'd like
The versions sidebar panel should show if a version is currently in a post-processing state. Actions should be disabled or hidden.

@tbsbdr Do you have an idea on how to implement that UX-wise?

Issue originated from https://github.com/owncloud/enterprise/issues/6151#issuecomment-1893972187.

**Comment by kulmann** [comment]
> ## Describe the solution you'd like
> The versions sidebar panel should show if a version is currently in a post-processing state. Actions should be disabled or hidden.

I guess that's the point in time where we should add the current version to the versions list. At the moment the versions list only shows the other versions, never the current version.

**Comment by tbsbdr** [comment]
I'd use the same pattern as we display postprocessing in the fileslist: apply a kind of disabled-style to the affected version, actions are not clickable because they are disabled.

<img alt="image" src="https://github.com/owncloud/web/assets/26610733/1cab8b3b-3c0f-4ad9-994f-89729da8dfdb">

**Comment by kulmann** [comment]
It shouldn't be possible to open the right sidebar at all for a file that is currently in postprocessing. Closing
