### ISSUE TITLE
Update docker compose for `app-provider`

### ISSUE THREAD

**Issue by SagarGi** [owncloud/web#10359]
### Description
Some changes has been made in CI regarding running the app-provider e2e tests which is different than that of docker.

TODO:
- [x] update the docker compose for app-provider tests according to CI https://github.com/owncloud/web/pull/10360

**Comment by SagarGi** [comment]
May be do not merge this issue until this things get resolved: https://github.com/owncloud/web/issues/10351 with this PR: https://github.com/owncloud/web/pull/10357

**Comment by saw-jan** [comment]
@SagarGi should we close it now?

**Comment by SagarGi** [comment]
The update has been merged. https://github.com/owncloud/web/pull/10360 so closing this issue:
