### ISSUE TITLE
Parent link in upload info does not work for share root folders

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10369]
## Steps to reproduce
1. As `einstein`, share a folder `folder` with write permissions with `admin`
2. As `admin`, go to your shares and open that folder
3. Upload a resource
4. Go to some other page, e.g. your personal space
5. Click on "Show details" on the upload info (bottom right side) and then go to the parent folder `folder`

## Expected behavior
You are being redirected to the folder correctly.

## Actual behavior
The redirect is broken, it shows "Resource not found".

Note that the fix for this needed to target `stable-8.0`.

**Comment by jacob-nv** [comment]
@JammingBen Getting different type of error. Anything uploaded by admin or einstein from admin point of view into shared folder by

**Comment by jacob-nv** [comment]
@JammingBen Getting different type of error. Anything uploaded by Admin or Einstein from Admin point of view into shared folder by Einstein won't even show the "Shared via" and console logs PROPFIND 403 error
(Shared with edit permissions)

**Comment by JammingBen** [comment]
> @JammingBen Getting different type of error. Anything uploaded by Admin or Einstein from Admin point of view into shared folder by Einstein won't even show the "Shared via" and console logs PROPFIND 403 error (Shared with edit permissions)

Could you maybe post a video or exact steps of what you are doing? Uploading works fine for me, it's just the parent folder that is buggy.

**Comment by jacob-nv** [comment]
@JammingBen 
Running OCIS_IMAGE=owncloud/ocis:5.0.0-rc.1
Login as Admin, Login as Einstein

Einstein: 
- Create folder with name folder
- Click on context menu, Click on Share
- Search for Admin, switch from Can view to Can edit, submit

Admin: 
- Go to shares, see the shared folder, open folder
- Upload testing png I have prepared
- Click context menu for file, Detail
![image](https://github.com/owncloud/web/assets/138569835/04734dbb-6089-42db-924b-0df053576af4)
(Try to refresh page, repeat last step, same error)

Einstein:
- Check the shared folder, file uploaded, context menu, detail, see the /folder path (click, everything works fine)
- Upload new file

Admin:
- Check the uploaded file, context menu, details, same error

**Comment by JammingBen** [comment]
> Click context menu for file, Detail

Ahh now I get it. The error occours when opening the right sidebar, that's another bug. I'll create a ticket for it.

For this issue you don't need to open the sidebar though. It's about the parent folder link ("for admin") in this overlay on the bottom right:

<img width="381" alt="image" src="https://github.com/owncloud/web/assets/50302941/dd7d3710-e48c-4104-a8a7-bf0631892745">

**Comment by JammingBen** [comment]
Seems to be fixed meanwhile, hence closing.
