### ISSUE TITLE
Clicking the oC logo on public links causes weird issues

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10371]
## Steps to reproduce
1. Make sure you are running a stack with external apps such as OnlyOffice or Collabora
2. Create a public link for a folder that includes a `docx` file
3. Open the link in an incognito window
4. Click on the oC logo a few times
5. Right click the docx file to open the context menu

## Expected behavior
Clicking the oC logo always reloads the current link. Right clicking the file shows the context menu and its entries as expected.

## Actual behavior
Sometimes the page dies when trying to reload, giving an error `Cannot read properties of null (reading 'canCreate')`. Reloads that are successful on the other hand cause duplicated entries for external apps in the context menu:

<img width="290" alt="image" src="https://github.com/owncloud/web/assets/50302941/d6628003-1aea-4878-82d9-f7edf8e077d9">

The error only exists on master, not on `stable-8.0`.

**Comment by JanAckermann** [comment]
Introduced via https://github.com/owncloud/web/pull/10207
