### ISSUE TITLE
Provide a simple way to add an extension

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10386]
# Description

## User Stories

* > As an admin I want a simple way to add web extension so that I can customise the web ui to my needs.

## Acceptance Criteria
- tbd

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by kulmann** [comment]
This is done already. See https://owncloud.dev/services/web/#web-apps for details and http://github.com/owncloud/awesome-ocis for apps
