### ISSUE TITLE
[QA] Backport e2e tests to stable-8.0

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#10457]
Recently, we have added or extended some e2e test scenarios to the master branch. We want to have them in stable-8.0 as well.
So try to backport ui test changes to the stable-8 and see how well it works out. Some changes might not cope with the stable-8 branch.

CC @ScharfViktor

**Comment by S-Panta** [comment]
PR to be backported. Some of these PR have development code attached, so direct cherry-picking is difficult. 
 - [ ] Deleting resharing feature [https://github.com/owncloud/web/pull/10392 
 - [ ] open file through Collabora [ https://github.com/owncloud/web/pull/10420
 - [ ] Toast editor [https://github.com/owncloud/web/pull/10390
 - [ ] remove share status in favour of syncEnabled [https://github.com/owncloud/web/pull/10421 
 - [ ] Deleted acceptance tests [ https://github.com/owncloud/web/pull/10267
 - [ ] remove share access details tests [ https://github.com/owncloud/web/pull/10427
 - [ ] move upload file exceeding quota test to e2e https://github.com/owncloud/web/pull/10428
 - [ ]  delete multiple resources from trashbin https://github.com/owncloud/web/pull/10449
 - [ ] Removed scenario related to folder upload from old web UI test https://github.com/owncloud/web/pull/10480
 - [ ] eceive two shares with same name https://github.com/owncloud/web/pull/10488

**Comment by saw-jan** [comment]
Closing as test PRs have been ported to stable-8
