### ISSUE TITLE
Access token expiry causes failed uploads on OCIS test server

### ISSUE THREAD

**Issue by prohtex** [owncloud/web#10474]
I've been scratching my head over token expiry errors that cause failed uploads on OCIS documented on owncloud/ocis#8368 and owncloud/ocis#8372. Today I reproduced these errors on OCIS continuous deployment test server.

I obviously don't have access to those logs, but screenshots are below.

Steps to reproduce:

1. Log into OCIS test server: https://ocis.ocis-wopi.latest.owncloud.works admin/admin
2. Create a new space
3. Upload a directory containing large flies to the new space
4. Upload fails with unknown error. Observe console errors caused by token expiry

![Screenshot 2024-02-10 at 2 42 39 PM](https://github.com/owncloud/ocis/assets/12946938/af5907b9-a581-45bd-91cd-d9e4a9153f02)

**Comment by tbsbdr** [comment]
All I can say is that uploads must continue in "background" tabs; assessing as p2 as uploading is essential for us. as mentioned by you, @kulmann solving this issue via web worker might be heavy lifting, so a effort estimation / reasearch beforehand should happen before we go in.

**Comment by prohtex** [comment]
> **Could you please try the following?**
> 
> 1. Start a long running upload (e.g. like in your reproducer)
> 2. Open the network tab in the dev tools, so that network requests get recorded
> 3. Grab a coffee or click around in the ownCloud browser tab. Make sure to not put the browser or the tab into hibernation.

Hi @kulmann, I am glad the issue was found! I can confirm that taking further actions keeps the tab active and the upload going. This also explains why the point at which the upload failed was rather inconsistent (as I was taking various actions with the browser, and not always keeping it in the background). I can also confirm that setting IDP_ID_TOKEN_EXPIRATION mitigates the issue; I had mistakenly tried to set the value in the .env file previously and it was not taking effect.

Our use case is for photo retouching, and so we are frequently sending massive files over the web client. A big part of why we wanted to migrate to OCIS was to improve reliability sending large files this way; we often encounter timeouts and broken uploads with OC10. I am assuming sites like DropBox and Wetransfer use Web Workers for their uploads.

For the meantime, we will likely deploy more than one instance of OCIS so we can continue to test, and to keep one with a very long token timeout for these purposes. It doesn't appear possible to get the WOPI deployment working without Docker so we will continue to use the Ubuntu VM. I can always test anything in a fresh Ubuntu VM or on macOS.

Thanks again to the team of dedicated individuals working to make OCIS an incredible product. I'm a PHP developer so can't contribute much in the way of code, but am happy to do whatever I can to help.

**Comment by prohtex** [comment]
After further testing, I am noticing some quirks: #10492

**Comment by appiekap653** [comment]
I am receiving the same error, but then when trying to upload using the android client, rclone and web.
I don't think this has something to do with browsers throttling tabs, rclone and android client doesn't have tabs...

I have also set the access tokens to expire after 24 hours in my external idp. using authentik.
I doubt that the access token expired error message is referring to the token from the idp, I think it is referring to some internal used access token.

**Comment by JammingBen** [comment]
> I am receiving the same error, but then when trying to upload using the android client, rclone and web.
> I don't think this has something to do with browsers throttling tabs, rclone and android client doesn't have tabs...

It sounds like a different error then. We have a similar issue open in the server repo, which makes more sense if you're experiencing these problems with other clients as well. Maybe related? https://github.com/owncloud/ocis/issues/8372

Either way, there are definitely issues with tab throttling. https://github.com/owncloud/web/pull/10955 addresses those.
