### ISSUE TITLE
Login user page stays in loop  when it's disabled by the admin 

### ISSUE THREAD

**Issue by S-Panta** [owncloud/web#10472]
## Describe the bug
When a user is disabled by the `admin` and if the user isn't logged out, the browser stays in the loop when trying to access it next time, and no login is possible. 

## Steps to reproduce
1. Login with any test user
2. Open incognito and login with admin and disable that user
3. The user get logs out.

## Expected behavior
It should be possible to log in to the URL again on that session

## Actual behavior
The login page is stuck and it stays in the loop with the message `Authentication failed`. The browser console reads as ` getUser: user not found in storage`.

![image](https://github.com/owncloud/ocis/assets/64484313/753d1769-4faa-43bd-9963-13ee6f641a8c)

**Comment by JammingBen** [comment]
I suppose this is the same issue as https://github.com/owncloud/web/issues/4677. The supposed fix https://github.com/owncloud/web/pull/10165 has other drawbacks the last time I tested, so it needs a re-visit.

**Comment by S-Panta** [comment]
It looks similar though this is for disabled user.

**Comment by JammingBen** [comment]
> It looks similar though this is for disabled user.

Yes. I think I didn't make myself clear enough 😄 What I meant was that the underlying technical issue with the IDP lib is (probably) the same, meaning fixing it will resolve both issues.

**Comment by S-Panta** [comment]
Closing this issue in favor of https://github.com/owncloud/web/issues/4677
