### ISSUE TITLE
Ctrl+S key listener in text editor / AppWrapper fires on Ctrl+Shift+S as well

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#10477]
## Describe the bug
The key listener we have in the AppWrapper is not an exact match on the keys 😨 

## Steps to reproduce
1. Open up your Firefox
2. Create a markdown file from within the files app (opens in text-editor app)
3. Write some content (optional)
4. Try to make a screenshot of your awesome content with Ctrl+Shift+S

## Expected behavior
Firefox keyboard shortcut for making screenshots works as expected.

## Actual behavior
Firefox keyboard shortcut for making screenshots doesn't work.

## Additional context
The key binding which is supposed to save the content via `Ctrl+S` is defined in https://github.com/owncloud/web/blob/1674c8e17da2c0385d5b0bfed2696dad864949b0/packages/web-pkg/src/components/AppTemplates/AppWrapper.vue#L407

Unfortunately this fires for e.g. `Ctrl+Shift+S` as well. We somehow need to make this an exact match for the pressed keys....

**Comment by kulmann** [comment]
CC @TheOneRing - thanks for reporting this! 👍

**Comment by kulmann** [comment]
@jacob-nv could you look into this?

**Comment by AlexAndBear** [comment]
Taking over for now

**Comment by AlexAndBear** [comment]
Unassigned for now, need to work on other sprint tasks first

**Comment by pascalwengerter** [comment]
@AlexAndBear did you have any findings while working on this?

**Comment by AlexAndBear** [comment]
@pascalwengerter no, if you want you can take it over

**Comment by pascalwengerter** [comment]
> @pascalwengerter no, if you want you can take it over

I've added a suggestion on how to fix it, but it seems a bit klunky tbh
