### ISSUE TITLE
Authenticated user cannot download file via public link share

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/web#10473]
## Describe the bug
When a user tries to download a file inside a folder whose public link is shared, the download fails with with status code `401 Unauthorized`.

## Steps to reproduce
As user `Admin`
1. Create a folder `test-folder`
2. Upload a file `test-file.txt` inside `test-folder`
3. Create a public link share of `test-folder`

As user `einstein`
1. Open the public link shared by `admin`
2. try to download the file `test-file.txt`

## Expected behavior
The file should be successfully downloaded.

## Actual behavior
The download fails with status code `401`.

[Screencast from 02-13-2024 05:12:03 PM.webm](https://github.com/owncloud/web/assets/83579989/fc95bc5c-0c21-4353-b239-5b91da08574a)

## Setup
 ownCloud Web UI 8.0.0-rc.2
Infinite Scale 5.1.0-prealpha+01d40c278

**Comment by saw-jan** [comment]
1. anonymous user can do the following to download drom public link: (works :heavy_check_mark:)
    ```
    curl "https://localhost:9200/remote.php/dav/public-files/CfcZNdrwEftaRng/test-file.txt" \
    -u public:<link-pass> -vk
    ```
    `public` doesn't have effect but I put it there to indicate public user

2. authenticated user: (`401` :exclamation:)
    ```
    curl "https://localhost:9200/remote.php/dav/public-files/CfcZNdrwEftaRng/test-file.txt" \
    -u demo:demo -vk
    ```
    I wonder if that is supposed to work or not


CC @ScharfViktor @kulmann

**Comment by ScharfViktor** [comment]
it's not reproduced on:
`ocis 5.1.0-prealpha+c3d895445`
`web 8.0.0-rc.4`

maybe it was already fixed? I'm trying to find where

**Comment by saw-jan** [comment]
> it's not reproduced on: `ocis 5.1.0-prealpha+c3d895445` `web 8.0.0-rc.4`
> 
> maybe it was already fixed? I'm trying to find where

the issue is in the master branch.
```
ownCloud Web UI 8.0.0-rc.2
Infinite Scale 5.1.0-prealpha+01d40c278
```

**Comment by ScharfViktor** [comment]
we have test for public https://github.com/owncloud/web/blob/master/tests/e2e/cucumber/features/smoke/shares/link.feature#L70-L72

I'll expand the suite for the athenticated user

**Comment by ScharfViktor** [comment]
I'm not sure. Maybe it has something to do with: https://github.com/owncloud/ocis/pull/8385/files related?

**Comment by PrajwolAmatya** [comment]
Fixed in https://github.com/owncloud/web/pull/10494. So, closing this issue.
