### ISSUE TITLE
Shared resource is not available in the Shares for sharee

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/web#10484]
## Describe the bug
With latest web `ownCloud Web UI 8.0.0-rc.2`, when a resource is shared to a user, then the shared resource is not available in the Shares page of the sharee.

## Steps to reproduce
1. User `Admin` creates a folder `test-folder`
2. `Admin` shares folder `test-folder` with user `Einstein`
3. `Einstein` navigates to the Shares page.

## Expected behavior
`test-folder` should be available in the Shares for user `Eisntein`.

## Actual behavior
`test-folder` is not available in the Shares for user `Einstein`. User Einstein gets the notification and proper response is available from `sharedWithMe` endpoint but the folder `test-folder` is not available as seen in the following screenshot.

### Screenshot
![Screenshot from 2024-02-15 09-56-33](https://github.com/owncloud/web/assets/83579989/20178433-9b22-4105-b581-71cc402b8aa7)

## Setup
ownCloud Web UI 8.0.0-rc.2
Infinite Scale 5.1.0-prealpha+01d40c278 Community

**Comment by kulmann** [comment]
That's the current version in `master`, not `8.0.0-rc.2`. We should probably have a version number like `8.1.0-prealpha` in place, like ocis does it...

However, that's fallout from the switch to sharing ng. We'll need to wait for a backend fix.

**Comment by saw-jan** [comment]
works fine with these versions (`web-master-latest`, `ocis-master-latest`)
@PrajwolAmatya Maybe the ocis wasn't up-to-date?
```bash
ownCloud Web UI 8.0.0-rc.2 (master-git)
Infinite Scale 5.1.0-prealpha+4fafefd69 Community 
```

**Comment by PrajwolAmatya** [comment]
> works fine with these versions (`web-master-latest`, `ocis-master-latest`) @PrajwolAmatya Maybe the ocis wasn't up-to-date?
> 
> ```shell
> ownCloud Web UI 8.0.0-rc.2 (master-git)
> Infinite Scale 5.1.0-prealpha+4fafefd69 Community 
> ```
> 
> I see `shared` property in the above provided screenshot. The `shared` property was removed in the ocis and web was also changed accordingly. That means the web was updated but not the ocis.

Thanks. It worked now. Closing this issue. :+1:
