### ISSUE TITLE
OCIS Web doesn't warn a user about closing a window with an active upload

### ISSUE THREAD

**Issue by prohtex** [owncloud/web#10500]
## Describe the bug
OCIS Web doesn't warn a user about closing a window with an active upload

## Steps to reproduce
1. Begin upload
2. Close Window

## Expected behavior
When user closes a browser window with an active upload, an error warns the user about the active upload.

## Actual behavior
Window is closed and upload fails

## Setup
OCIS latest with Safari browser

**Comment by dschmidt** [comment]
c.f.

https://github.com/owncloud/web/blob/9444050be78871817ea84fe85935c6fa47cc2446/packages/web-pkg/src/components/AppTemplates/AppWrapper.vue#L151-L163

**Comment by kulmann** [comment]
@jacob-nv maybe something for you?

**Comment by AlexAndBear** [comment]
@kulmann @jacob-nv sorry, I was already on it
