### ISSUE TITLE
Show Basic Activities

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10506]
# Description

## User Stories

* > As a user I want to see who made which changes to files, so that I can track modifications.
* > As a user I want to see who accessed files, so that I can track access.

## Value
- improve collaboration
- provide transparency

## Acceptance Criteria
- new sidebar panel "Activity"
  - The panel activity shows the following events, newest events on top
  - Events are shown recursively
    - Name of the person who caused the event
    - The amount of events in the right sidebar is limited to XX
 - Event types (applicable to files, folders or spaces)
   - Added
   - Deleted
   - Edited
   - Moved
   - Renamed
   - Shared

  - Click on one of the listed file navigates to the respective resource
  - Seeing Activities depends on a permission (enabled by default)
  - batch events are grouped

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
## Visuals
**exmaple**
![screenshot_002384](https://github.com/owncloud/web/assets/26610733/0d8fcfcb-7f67-4975-9fc4-c864dbf8ae83)

@tbsbdr add scribbles

**Comment by JammingBen** [comment]
@tbsbdr Can we close this now that it's implemented?
