### ISSUE TITLE
Modals can overlay the logged out page

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#10502]
## Steps to reproduce
open a modal, be logged out because of session timeout

## Expected behavior
Modal is closed and the logged out page is visible and accessible

## Actual behavior
Modal is not closed and prevents access to the underlying page

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by AlexAndBear** [comment]
@dschmidt what would be your technically advise to solve this ? Iterating trough modal elements and call a close method during logout or whatever page will be rendered

**Comment by pascalwengerter** [comment]
> @dschmidt what would be your technically advise to solve this ? Iterating trough modal elements and call a close method during logout or whatever page will be rendered

I've faced a similar issue with wanting to remove the "UploadInfo" popup on the FilesDrop page, my way was adding a property to the route `meta` and then dynamically modifying the global `App.vue`
