### ISSUE TITLE
Image viewer doesn't respect aspect ratio

### ISSUE THREAD

**Issue by prohtex** [owncloud/web#10511]
## Describe the bug
The oCIS image viewer allows you to preview supported image files, but when the images are opened in the web, the aspect ratio is not maintained.

## Steps to reproduce
1. Upload an image
2. Open in oCIS web
3. Observe aspect ratio

## Expected behavior
Image displayed properly

## Actual behavior
Image displayed with incorrect aspect

## Additional context
Probably a simple CSS fix.

<img width="1175" alt="Screenshot 2024-02-24 at 10 34 45 PM" src="https://github.com/owncloud/web/assets/12946938/0c4617f2-369a-4bdc-8309-7a6cc7110130">

**Comment by AlexAndBear** [comment]
Might be fixed on master already,  need to check

**Comment by kulmann** [comment]
Has been fixed for ocis `v5.0.0`. The thumbnail service now has a new nocrop option, which the `preview` app is utilizing. See https://github.com/owncloud/ocis/issues/5179 for details.
Since this required an enhancement for the thumbnail service we can't bring it in ocis `v4.0.x`, i.e. won't fix for ocis `v4.0.x`, sorry.

**Comment by prohtex** [comment]
@kulmann can we re-open this? I think there was some confusion about the issue in question, which is still present in 9.0.0. The behavior can be observed here. It might be limited to webkit/safari (and indeed is probably related to how Safari handles the transform) as I cannot reproduce in Firefox:
https://ocis.ocis-wopi.latest.owncloud.works/preview/personal/admin/cover.jpg?fileId=f6d67da8-f09d-4c36-ae78-ec1bcc07dd77%243fa1879e-fbd7-4d60-a78c-5867602b2562%21c5a07b6e-b41b-4ba5-b401-546a4f49c5d8&contextRouteName=files-spaces-generic&contextRouteParams.driveAliasAndItem=personal%2Fadmin&contextRouteQuery.fileId=f6d67da8-f09d-4c36-ae78-ec1bcc07dd77%243fa1879e-fbd7-4d60-a78c-5867602b2562%213fa1879e-fbd7-4d60-a78c-5867602b2562
![Screenshot 2024-06-18 at 3 24 39 AM](https://github.com/owncloud/web/assets/12946938/4466b80e-7024-4251-b504-570cda6faea5)

![Screenshot 2024-06-18 at 3 24 49 AM](https://github.com/owncloud/web/assets/12946938/fb820e48-86b9-4731-af22-b99fe9a60138)
![Screenshot 2024-06-18 at 3 25 09 AM](https://github.com/owncloud/web/assets/12946938/91d1f5ae-431e-407c-8604-31ee479b6702)

**Comment by AlexAndBear** [comment]
> Probably a simple CSS fix.

It was indeed, but trial and error was a nightmare 😸 

Thanks for the detailed error description

**Comment by kulmann** [comment]
thank you for digging into it @AlexAndBear :-)

@prohtex don't know if you heard about the rolling releases. If not, see https://owncloud.dev/ocis/release_roadmap/#release-types - gist is, that we now release an `ocis-rolling` artifact after each sprint (= every 3 weeks on Monday or Tuesday). This fix will be part of the next rolling release (ocis `6.2.0`). Don't know about your production environment, if it allows for `rolling` then you'll have the fix in about 2 weeks. If not, you'll need to wait for November 🙈
