### ISSUE TITLE
hidden state of resources in `Shared with me` won't persist after reload/traverse back to `Shared with me`

### ISSUE THREAD

**Issue by nabim777** [owncloud/web#10542]
## Describe the bug
The hidden resources in the `shared with me` page will unhide when the page is reloaded or traversed back from elsewhere.

## Steps to reproduce
1. As an `admin`, create a folder as "New Folder"
2. As an `admin`, shares folder with `einstein`
3. As a user `einstein`, hide the folder `New Folder` in the `share` space
4. Then reload the pages or simply go back and forth from another space

## Expected behavior
The folder `New Folder` expected to be in the `hidden shares` list
![image](https://github.com/owncloud/web/assets/61624650/5e2f1e5a-f546-4769-bf27-8fe4af8691aa)

## Actual behavior
The folder `New Folder` comes in  `shares` list
![image](https://github.com/owncloud/web/assets/61624650/bbfcb247-e736-46c2-9667-b10294454c94)

## Test environment set up
 `ownCloud Web UI 9.0.0-alpha.1` 
 `Infinite Scale 5.1.0-prealpha+fa57da865 Community` 

## Screen record Video

[Screencast from 03-05-2024 01:12:43 PM.webm](https://github.com/owncloud/web/assets/61624650/335fb6a3-b63e-4910-9813-bc20feea510e)

**Comment by kulmann** [comment]
> Are you sure you're running Web version `8.0.0-rc.2`? I can reproduce the error on current master (version `9.0.0-alpha.1`), however not on `8.0.0-rc.2`.
> 
> 
> 
> Could you please also check if Web is doing a request to `.../graph/v1beta1/me/drive/sharedWithMe` on the "Shares" page?

It was on master. It just didn't have the 9.0.0-alpha.1 version, yet.

**Comment by nabim777** [comment]
> Are you sure you're running Web version `8.0.0-rc.2`? I can reproduce the error on current master (version `9.0.0-alpha.1`), however not on `8.0.0-rc.2`.
> 
> Could you please also check if Web is doing a request to `.../graph/v1beta1/me/drive/sharedWithMe` on the "Shares" page?

When I made this issue there was version `8.0.0-rc.2`. It was later changed in `9.0.0-alpha.1`  when this [PR](https://github.com/owncloud/web/pull/10512/files) was merged. 

Yes @JammingBen Web is doing a request to `.../graph/v1beta1/me/drive/sharedWithMe` on the "Shares" page
But
While hiding the resources web is doing requests to `..ocs/v2.php/apps/files_sharing/api/v1/shares/pending`
