### ISSUE TITLE
[CI] Implementing Dynamic ocis build from Latest Commit 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#10559]
## Description
Changes made to the share-with-me API response in the ocis, led to failures on ocis-php-sdk that went unnoticed until the ocis commit id was updated. This resulted in a prolonged blockage of the SDK. To prevent such incidents on the web, one solution was to run ocis with the latest commit id.

Currently, the ocis commit id is specified in the .drone.env file for reference. This commit id is utilized to cache ocis. 
In nightly builds we can build ocis with latest commit id. To fetch latest commit id we write script 

## Advantages:
- Early detection of any breaking changes in ocis.
- Identification of critical issues in advance, enabling mitigation and avoiding last-minute panic.

## Disadvantage
- Continuous Integration (CI) may remain red for an extended period until a fix is merged.
- Dynamic failures may occur, such as a bug emerging on Monday's last commit and a different failure on Tuesday's last commit.

**Comment by amrita-shrestha** [comment]
cc @phil-davis @individual-it @ScharfViktor @micbar

**Comment by individual-it** [comment]
I like the idea, we would not block PRs because of some change in the ocis repo, but we will know of issues early

**Comment by kulmann** [comment]
Awesome idea! 🚀 

Please keep in mind that the respective ocis branch name must be respected. E.g. for web `stable-8.0` the ocis branch `stable-5.0` from the `.drone.env` needs to be used to determine the most recent commit id.

**Comment by nabim777** [comment]
done in  #10661 and #10625
