### ISSUE TITLE
Disabled password policy has no effect in web ui

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#10560]
## Describe the bug
When the password policy is disabled in ocis (`OCIS_PASSWORD_POLICY_DISABLED=true`) the web ui is still enforcing a non-empty password.

## Steps to reproduce
1. Disable password policy by setting env var `OCIS_PASSWORD_POLICY_DISABLED=true`
2. Try to create a public link

## Expected behavior
No password needed

## Actual behavior
I'm forced to enter at least one character. Policy in the web ui shows that the rule `Must not be empty` is not fulfilled (see screenshot).

## Screenshot
<img width="506" alt="Screenshot 2024-03-07 at 11 27 51" src="https://github.com/owncloud/web/assets/3532843/b07a7181-20dc-4158-9502-ba8d56359ed4">

## Setup
self built ocis from HEAD of `stable-5.0` ocis branch (= web `v8.0.0-rc.6` / HEAD of `stable-8.0` in web)

## Target branch
Please fix on web `stable-8.0` and forward port to `master`. Not a release blocker, but we want it included in a web `v8.0.1`.

**Comment by AlexAndBear** [comment]
Let's check if the capabilities are correct set first before making web adjustments

**Comment by kulmann** [comment]
<img width="218" alt="Screenshot 2024-03-07 at 14 06 59" src="https://github.com/owncloud/web/assets/3532843/84920a4f-770c-4a28-a72f-3d24f186c250">

looks correct to me

**Comment by AlexAndBear** [comment]
Ehm another question, are we sure that the password is still not enforced in your case? 

Because for this case,I implemented this default passwordMustNotBeEmpty role

**Comment by kulmann** [comment]
Elevated to p2 and release blocking

**Comment by kulmann** [comment]
> I think the problem is that the max length is still set. That's why the check says a password is needed

Max length being set should never enforce the password 🤔

**Comment by kulmann** [comment]
You're right. Password enforcement capability must be disabled as well. When I do that there's an underlying backend issue, tracked here: https://github.com/owncloud/ocis/issues/8604
Closing here since this seems to be a misunderstanding in the first place and then a backend only issue.
