### ISSUE TITLE
[Performance] File selection is extremely slow

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#10578]
## Describe the bug
Selecting files should be instant, especially in the tiles view it's super slow.

## Steps to reproduce
1. Upload 500 photos into one folder
2. Switch to tiles view
3. Try to select files (-> selected = checkbox is ticked)

## Expected behavior
Clicking a resource instantly selects it.

## Actual behavior
With 500 tiles it takes multiple seconds to select a resource on my machine.

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by AlexAndBear** [comment]
Good news 🥳 

A combination of:
- https://github.com/owncloud/web/pull/11508
- https://github.com/owncloud/web/pull/11631

fixes the issue:

https://github.com/user-attachments/assets/90090fb2-e15b-4695-8d01-c2528c4faaee
