### ISSUE TITLE
Incoming notifications don't render properly when notifications open

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10602]
## Describe the bug
Incoming notifications do not display properly when having the notifications opened.

## Steps to reproduce
1. Open 2 browser tabs, one being logged in as "admin", one as "einstein"
2. As "einstein", open the notifications and leave them open
3. As "admin", invite "einstein" to a space

## Expected behavior
The notification doesn't get rendered properly for "einstein":

![image](https://github.com/owncloud/web/assets/50302941/e5ec7cf4-3be3-4090-98a0-ce180d11e83a)

## Actual behavior
The notification gets rendered properly for "einstein".

**Comment by kulmann** [comment]
@JammingBen is this relevant for `stable-8.0`?

**Comment by JammingBen** [comment]
> @JammingBen is this relevant for `stable-8.0`?

I mean it's not critical IMO, but yes, the error also happens on `stable-8.0`.

**Comment by kulmann** [comment]
Ok 👍 then for whoever works on this: please fix with PR to `stable-8.0` and then we can do a forward port to `master`.

**Comment by AlexAndBear** [comment]
Was not able to fix this on stable-8.0 since the code differs too much, and I am not quite sure about changing the whole file for a patch release and an issue that is p4
