### ISSUE TITLE
click on .sb3 files leads to error message `wopi: neither edit nor view app url found`

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10605]
## Steps to reproduce
1. Login on https://ocis.ocis-web.latest.owncloud.works/
2. upload  [Scratch-Project.sb3 (43 KB)](https://infinite.owncloud.com/s/BPlxIonLtkWwQEh) file (.sb3 extensions is used in _Scratch_ https://scratch.mit.edu/ , the mime type `application/zip` )
3. click on `Scratch-Project.sb3` in the web ui
4. error shows up: "wopi: neither edit nor view app url found"

Note: this behaviour happens also if you use any other plain sb3 file, generated via `touch sb3test.sb3`

## Expected behavior
- standard action "Download" should be triggered

## Actual behavior
- error shows up: "wopi: neither edit nor view app url found"

## Screenie
![screenshot_002475](https://github.com/owncloud/web/assets/26610733/a8d11b2c-6681-4b78-8d09-bce7b1976488)

**Comment by AlexAndBear** [comment]
Let's see if this is a web issue or a (mis)configuration on the OCIS side

**Comment by kulmann** [comment]
The mime type that oCIS announces via the `PROPFIND` response is `application/octet-stream`. The app provider is configured as follows for that mimetype:
```
{
    "mime_type": "application/octet-stream",
    "app_providers": [
        {
            "name": "Collabora",
            "icon": "https://collabora.owncloud.com/favicon.ico"
        },
        {
            "name": "OnlyOffice",
            "icon": "https://onlyoffice.owncloud.com/web-apps/apps/documenteditor/main/resources/img/favicon.ico"
        },
        {
            "name": "Office365",
            "icon": "https://res.cdn.office.net/officehub/images/content/images/favicon-8f211ea639.ico"
        }
    ]
}
```

So this is not a web issue but a misconfiguration of the app provider, like @AlexAndBear assumed.

**Comment by kulmann** [comment]
@micbar since this repo doesn't list the `application/octet-stream` mime type in the app provider config, I assume that this is part of some default config for the app provider. Can you give me a pointer?

**Comment by AlexAndBear** [comment]
Fixed via https://github.com/cs3org/reva/pull/4693
