### ISSUE TITLE
Closing a file editor blanks out the "Shares" navigation item

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10615]
## Describe the bug
Closing a file editor such as the preview app or the pdf viewer in your personal space will make the "Shares" navigation item to go blank.

## Steps to reproduce
1. Upload a PDF file to your personal space
2. Open it with the PDF viewer
3. Close it again

## Expected behavior
Left navigation is as it was before opening the file.

## Actual behavior
The "Shares" navigation item goes blank. It's still there, but the font changed to white (as if it was active), hence you can't see it anymore.

<img width="222" alt="image" src="https://github.com/owncloud/web/assets/50302941/adb3a67d-9f1e-4aef-b95b-9dce89ea4c00">

The issue exists on current master, not on `stable-8.0` though.

**Comment by kulmann** [comment]
Ah, thanks for the reproducer! I noticed the state as well, but didn't find out how I got there.
