### ISSUE TITLE
Running oCIS Web in a pinned browser tab is sub-optimal

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/web#10623]
## Describe the bug
I am pinning often used website in browser tabs in FF.
As soon as a session in oCIS web expires the 'Log in again' button opens up a new tab.
The pinned tab is basically unusable now.

This can be quite annoying .....

**Comment by AlexAndBear** [comment]
Also not able to reproduce

**Comment by DeepDiver1975** [comment]
Never happened to me again. 🤷
