### ISSUE TITLE
[Embed mode] Disable opening files via editors

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10635]
A question that came up yesterday: should the embed mode allow opening files via editors? IMO it misses the point of the embed mode a bit, since its purpose is basically to transfer files to/from a third party app, and not to work in files. Hence I'd suggest disabling it.

@kulmann @tbsbdr Opinions?

**Comment by kulmann** [comment]
Same opinion.

**Comment by tbsbdr** [comment]
Same opinion.

**Comment by kulmann** [comment]
I'll label this as a p3  bug. IMO worth disabling in the `stable-8.0` branch so that it gets included in the next ocis patch release.

**Comment by JammingBen** [comment]
I stumbled upon a question while implementing: what should actually happen, if you click e.g. a text file in embed mode? Should it trigger the download action like usually, if there is no editor found, or should it be un-clickable at all?
