### ISSUE TITLE
Use server-side space template logic

### ISSUE THREAD

**Issue by kobergj** [owncloud/web#10644]
Currently when creating a space, the webclient will fire several requests:
- `POST` to create the drive
- `MKCOL` to create the `.space` folder
- `PROPFIND` to find the id of the `.space` folder
- `PUT` to upload the `readme.md`
- `PROPFIND` to find the id of the `readme.md`
- `PATCH` to patch the drive with the special id of the `readme.md`

Since https://github.com/owncloud/ocis/pull/8558 the server is able to do all this work for the client(s)

The improved requests would look like this:
- `POST` to create the drive, add the parameter "template=default"

This will create the drive, the `.space` folder, the `readme.md` and a default space image.

A benefit of this approach is that other clients can reuse this logic when they want to create spaces. This will lead to a consistent behaviour between all clients.

**Comment by tbsbdr** [comment]
@kobergj can you add a user story or is it tech dept?

**Comment by kobergj** [comment]
I would say it is technical debt. That is why added that label. But maybe webbies don't agree?

**Comment by JammingBen** [comment]
I agree that it's a technical debt 👍 There is no direct value for an end-user, however, much so for us devs.

**Comment by kulmann** [comment]
While I don't see it coming at the moment that other clients will allow users to create spaces, this is an awesome improvement for the web client alone. Agreeing that it's technical debt, but it also improves server load (less requests is always a good thing). Nice 💪

**Comment by AlexAndBear** [comment]
Wonderful 😍 we need to check how we can set the template when the space already exists. (Somebody could have remove the .space folder)

**Comment by AlexAndBear** [comment]
Fixed via https://github.com/owncloud/web/pull/10656
