### ISSUE TITLE
App bootstrap fails if system is set to dark and there is no dark theme

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#10657]
## Describe the bug
Given an ownCloud instance with only a light theme fails in app bootstrap if the operating system is set to dark mode.
(also happens the other way around, only a dark theme but system is set to light mode)

## Steps to reproduce
1. Set up an ownCloud which only has a light theme
2. Set your operating system to dark mode
3. Visit your ownCloud instance in a private browser tab

## Expected behavior
The ownCloud page you tried to open loads like it should, rendered with the only available theme.

## Actual behavior
`Missing or invalid config` page is shown

## Additional context
Happens on `stable-8.0` (I didn't test if it also happens on `master`).
This is the line where it fails:
https://github.com/owncloud/web/blob/4155b81726b7760ad59b7025fbc9ec05166b80f3/packages/web-pkg/src/composables/piniaStores/theme.ts#L107

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/web/pull/10659.
