### ISSUE TITLE
unable to disable PASSWORD_POLICY

### ISSUE THREAD

**Issue by fschade** [owncloud/web#10672]
## Describe the bug
using the PASSWORD_POLICY env has no impact in web.

## Steps to reproduce
1. OCIS_PASSWORD_POLICY_DISABLED=true
2. open sidebar in web.
3. open shares panel.
4. click `Add Link` in the `Share via link` section.
5. click `Copy link` in the opened modal
6. PW is marked as required

## Expected behavior
1. OCIS_PASSWORD_POLICY_DISABLED=true
2. open sidebar in web.
3. open shares panel.
4. click `Add Link` in the `Share via link` section.
5. click `Copy link` in the opened modal
6. PW is not marked as required and the modal closes while the created link is copied to the users clipboard

## Actual behavior
PW is marked as required (modal) no matter if OCIS_PASSWORD_POLICY_DISABLED is set.

**Comment by fschade** [comment]
looks like ocis sets the `...files_sharing.enforced` bool only and web uses:

`...files_sharing.enforced_for.read_only`
`...files_sharing.enforced_for.read_write`
`...files_sharing.enforced_for.read_write_delete`
`...files_sharing.enforced_for.upload_only`

we need to clarify:
* is it needed to be able to set each of those individually as a conf value aka. env?
* can ocis disable all 4 values if the admin sets `FRONTEND_PASSWORD_POLICY_DISABLED=true` or `SHARING_PASSWORD_POLICY_DISABLED=true` or `OCIS_PASSWORD_POLICY_DISABLED=true`

cc. @tbsbdr

**Comment by kulmann** [comment]
I actually reported that in the ocis repo a few days ago. Could you find the issue for me and link it here?

**Comment by kulmann** [comment]
Gist: there is another env var for disabling password enforcement. I find this super confusing. Feels like config is way too granular in a lot of cases and lacks easy docs.

**Comment by JammingBen** [comment]
> I actually reported that in the ocis repo a few days ago. Could you find the issue for me and link it here?

Here is the ocis issue (at least I think so): https://github.com/owncloud/ocis/issues/8607

I agree, we should rethink all these configs and decide for one simple way to handle this.

**Comment by AlexAndBear** [comment]
Every dev stumble over this 😅

**Comment by AlexAndBear** [comment]
Oh, I am closing this, since this is by far not a web issue and we have it tracked in the ocis repo
