### ISSUE TITLE
8.1: cannot get OpenID connect to work, documentation not really helpful

### ISSUE THREAD

**Issue by jouvin** [owncloud/web#10691]
## Steps to reproduce
1. Untar web.tar.gz in the document root of a Nginx virtual host (where `.mjs` was added as an `application/javascript` mime type)
2. config.json built by using [config.json.sample-ocsi](https://github.com/owncloud/web/blob/master/config/config.json.sample-ocis) as a reference
3. With a browser connection to the webui URL

## Expected behavior

A page asking to login, redirecting to the configured OIDC issuer

## Actual behavior

A blue screen with the following error in the Javascript console:

```
Uncaught (in promise) Error: Only the Authorization Code flow (with PKCE) is supported
    at JXe.createSigninRequest (vendor-Qpw5q4IY.mjs:56:67932)
    at dr._signinStart (vendor-Qpw5q4IY.mjs:56:91054)
    at dr.signinRedirect (vendor-Qpw5q4IY.mjs:56:86353)
```

## Setup

Nothing more was done in terms of configuration that what is described above. Not necessarily expecting Webui to work properly but I was hopting at least the get the authentication starting/working. The surprising thing is that, according to the OIDC issuer admins, there is no request from the webui server made to the issuer... (but I cannot check myself, I am not an admin of the issuer).

My `config.json`is:

```
{
  "server": "https://reva-meso.ijclab.in2p3.fr",
  "theme": "https://reva-meso-webui.ijclab.in2p3.fr/themes/owncloud/theme.json",
  "openIdConnect": {
    "metadata_url": "https://sso.universite-paris-saclay.fr/cas/oidc/.well-known/openid-configuration",
    "authority": "https://sso.universite-paris-saclay.fr/cas/oidc",
    "client_id": "secret",
    "client_secret": "very secret",    # Config example provided for OCIS has no parameter for the client secret, I guess it was this one
    "response_type": "no-cors",     # set to no-cors as recommended in the Javascript console after an error
    "scope": "openid profile email"
  },
  "apps": [
    "files",
    "preview",
    "pdf-viewer",
    "search",
    "text-editor",
    "draw-io",
    "external",
    "admin-settings",
    "epub-reader"
  ],
  "options": {
    "previewFileMimeTypes": [
      "image/gif",
      "image/png",
      "image/jpeg",
      "text/plain",
      "image/tiff",
      "image/bmp",
      "image/x-ms-bmp"
    ],
    "upload": {
      "xhr": {
        "timeout": 60000
      }
    },
    "contextHelpersReadMore": true
  }
}
```

## Context

The url to reach webui is `https://reva-meso-webui.ijclab.in2p3.fr` and as said webui is installed in the document root of this virtual host.

**Comment by kulmann** [comment]
@jouvin your `openid-configuration` lists:

```json
  "response_types_supported": [
    "code",
    "token",
    "id_token",
    "id_token token",
    "device_code"
  ]
```

There is no `no-cors` response type among those.
Could you explain the error you saw when you had `code` as `response_type` in your config.json?


One more thing: Your config looks like you would like to run the web ui against a standalone reva, not ocis. Is that correct? In that case please use web from the `stable-8.0` branch or a `8.0.x` released version. And you can remove the `epub-reader` app from your `config.json`, because that's not available in web `8.0.x`.

**Comment by jouvin** [comment]
@kulmann thanks. Yes I want to use the Reva 1.x branch rather than OCIS. And I use webui 8.1.

You are right that the issuer doesn't seem to provide no-cors and the javascript code suggested me to use code instead. But after doing it I get the error mentioned in the issue and the issuer admins told me that they don't see any request coming in... Is there a way to enable some debugging code to get more details about what webui is trying to do.

Also am I wrong to think that you need to provide a client secret with code flow?

**Comment by kulmann** [comment]
> @kulmann thanks. Yes I want to use the Reva 1.x branch rather than OCIS. And I use webui 8.1.

There is no webui 8.1, only `8.0` and `master` (master is currently set to `9.0.0-alpha`). I guess it's 8.0 then. :-)


> You are right that the issuer doesn't seem to provide no-cors and the javascript code suggested me to use code instead. But after doing it I get the error mentioned in the issue and the issuer admins told me that they don't see any request coming 
in... Is there a way to enable some debugging code to get more details about what webui is trying to do.

That's weird... the `oidc-client-ts` lib can be instructed to use a different log level. We hardcoded it to `INFO` in the `stable-8.0` branch and to `WARN` in `master`. It's not configurable, you need to change the value and build the web ui with `pnpm install && pnpm build`. This is the line we're talking about:
https://github.com/owncloud/web/blob/a3f3f9f2d6f5103d949ba7e65e0625cd0e8e6daa/packages/web-runtime/src/services/auth/userManager.ts#L102

> Also am I wrong to think that you need to provide a client secret with code flow?

The lib we're using for oidc handling (https://github.com/authts/oidc-client-ts) defaults to using the `PKCE` extension for the `code` auth flow. Only if you explicitly disable `PKCE` you need the `clientSecret`.

**Comment by jouvin** [comment]
@kulmann thanks again for all these detailed information. Should I need to specify  a secret, what is the name of the parameter to use in the yaml config file? `client_secret`? `ClientSecret`?

And about the version, sorry for the typo, I took `8.0.1`.

**Comment by kulmann** [comment]
Sure, always happy to help!

For the `config.json` we're expecting the var name to be `client_secret`. Not sure where `yaml` is involved for you for the web config, but if it's really yaml, then it might be a different var name.

**Comment by jouvin** [comment]
@kulmann I apologize for the mistake again, `json` not `yaml` ... Doing too many things in // ! 

I made a step forward: after a discussion with the OIDC issuer admins, they agreed that they add an ACL to access the authentication endpoint (issuer url) that was too restrictive... They fix it and now the authentication against the issuer works but is not accepted by webui because of a missing CORS header. Checking the configuration they did to add this header, they put a regex on the `Origin` header domain name and I guess this header is set by webui to something that is different from the web server (virtual host) name. Is there a way to control what is the value this header is defined to? Or what is the value it is set to?

**Comment by jouvin** [comment]
I made progress and the remaining problems are with the Reva server configuration, not with webui. So the issue can be closed. Thanks again for the help.

**Comment by kulmann** [comment]
Glad that I was able to help a bit. 👍🏻 don't hesitate to open new issues if anything else comes up!
