### ISSUE TITLE
Trigger chat notification for stable branch 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#10692]
## Describe 
web stable branch nightly doesn't throw notifications on Rocket Chat. `chat-notifications` doesn't triggered for stable branch.

- master branch nightly build (chat-notifications)
![Screenshot from 2024-04-02 12-48-56](https://github.com/owncloud/web/assets/54478846/9289e694-13ed-48a8-81a5-3ede98aacd45)

- stable branch nightly build (chat-notifications missing)
 
![Screenshot from 2024-04-02 12-49-05](https://github.com/owncloud/web/assets/54478846/b6f1917d-dfc5-4c8f-81b7-0f420d636e58)

**Comment by nabim777** [comment]
This PR #10693 fixes this issue so closing this issue
