### ISSUE TITLE
[a11y] 9.2.1.1 Usable without mouse

### ISSUE THREAD

**Issue by tschiebel** [owncloud/web#10730]
audit: https://infinite.owncloud.com/s/PnaAukHGGsLnrMM

https://bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-9-2-1-1-ohne-maus-nutzbar

### Personal 

- [ ] During the test, it was not possible to activate the checkboxes correctly with the keyboard
unless you had previously focused on a checkbox with the mouse.

### Shares

- [ ] See commentary on Personal.

**Comment by pascalwengerter** [comment]
Seems to be a problem inside `ResourceTable.vue`, since it works fine on `ResourceTiles.vue` (so the OcCheckbox component shouldn't be at fault)

**Comment by tbsbdr** [comment]
still reproducible
