### ISSUE TITLE
[a11y] 9.2.5.3 Visible labeling part of the accessible name

### ISSUE THREAD

**Issue by tschiebel** [owncloud/web#10736]
audit: https://infinite.owncloud.com/s/PnaAukHGGsLnrMM

https://bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-9-2-5-3-sichtbare-beschriftung-teil-des-zugaenglichen-namens

### Personal

- [ ] In the "Keywords" area, the combo box element has a visual text
"Adding or editing keywords", but this does not appear in the accessible name of the
element, as it is overwritten by the use of the "aria-label" attribute.
attribute.
![image](https://github.com/owncloud/web/assets/132444655/67d96349-fc95-4499-8df2-9f38e8fbe9b6)

### Spaces 

- [ ] In the "Quota for Space 8A - Change art" dialog, the visible label of the "Quota" field is changed by using the
Quota" field is overwritten by using the "aria-label" attribute "Search for option".
is overwritten.

### Account

- [ ] The visible label of the "Language" field is overwritten by the use of the "aria-label"
attribute "Search for option".

**Comment by pascalwengerter** [comment]
Looks like the `OcSelect.vue` default aria-label of "Search for an option" is problematic. Let's add a prop to pass a label to the component, then?

**Comment by AlexAndBear** [comment]
Let's check if we really want to integrate the fork, I created a issue on vue-select repo, which was about set the aria-label, this has been fixed in the meantime 

https://github.com/sagalbot/vue-select/pull/1765
