### ISSUE TITLE
[QA] increase test coverage for WOPI service

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/web#10750]
# Description
Previously e2e test for office suites (onlyoffice, collabora) with  WOIP service was limited to only manual testing (smoke testing) before releases. We do have e2e tests for office suits in which we only create and open files, but now we can extend and automate those manual testing and run on CI.

- [x] when file is shared with a user @anon-pradip 
     - [x] https://github.com/owncloud/web/pull/10958
1. share a file as viewer with a user
2. open the file as a sharee
3. sharee tries to edit the file
4. shares edits the file 
5. sharee sees the content updating in real time
6. sharer shares with edit permission
7. sharee edits the document
8. sharer sees the content updating in real time
9. sharer changes the permission back to viewer https://github.com/owncloud/ocis/issues/8060
10. sharee tries to edit the file

- [x] when file is shared with an anonymous user @anon-pradip
     - [x] https://github.com/owncloud/web/pull/10892
     - [x] https://github.com/owncloud/web/pull/10908
1. Alice creats a public link
2. Anonymous oopen the file
3. Anonymous tries to edit the file
4. Alice edits the file 
5. Anonymous sees the content updating in real time
6. Alice shares with edit permission
7. Anonymous edits the document
8. Alice sees the content updating in real time
9. Alice changes the permission back to viewer https://github.com/owncloud/ocis/issues/8060
10. Anonymous tries to edit the file

**Comment by saw-jan** [comment]
Also, consider https://github.com/owncloud/ocis/issues/8691

**Comment by saw-jan** [comment]
I am closing this as done

CC @ScharfViktor @anon-pradip @nirajacharya2
