### ISSUE TITLE
Delete Resharing from the code base

### ISSUE THREAD

**Issue by micbar** [owncloud/web#10771]
resharing feature is not supported anymore: https://github.com/owncloud/docs-ocis/pull/739/files#diff-04cd79e526c8a7f0162d8fc5bc5fa8c501fe9e5899024268837c05a74349b26cR148-R149

- [x] make all api and ui tests happy https://github.com/owncloud/ocis/pull/8704
- [x] create negative tests when we verify that a resharing is not possible `tests/acceptance/features/apiReshare/resharing.feature`
- [x] delete all resharing unit tests. here were commented tests https://github.com/owncloud/ocis/pull/8704/files#diff-8b57150852b437d73b32911784f40991ab7f0d8f94468201c405ee3e7a5686feR735-R764 and https://github.com/owncloud/ocis/pull/8704/files#diff-af2466555f3858dc080336a3201445475fc162a82a0592d214f930b1ebdfa534R354-R375
- [x] deleting re-sharpening from the code base
- [x] delete all envs related re-sharing like `OCIS_ENABLE_RESHARING`
- [x] remove resharing from reva https://github.com/cs3org/reva/pull/4606
- [x] default web client with `resharing=false`

### Web

- [ ] Check that there are no leftover tests or test-steps that include resharing
- [ ] Remove the resharing capability

cc @kobergj @saw-jan

**Comment by JammingBen** [comment]
We already removed all the functionality regarding resharing. The only remaining things I can think of are:

* Check that there are no leftover tests or test-steps that include resharing
* Remove the resharing capability (what's the status on the server side here?)

Am I missing something?

**Comment by micbar** [comment]
Then we can close it :-)

**Comment by JammingBen** [comment]
Okay, then let's leave it open for the remaining two tasks, I'll add them to the list above.

There is one thing not checked: `default web client with resharing=false`, does it need work on the server side?

**Comment by kulmann** [comment]
Web doesn't need the resharing capability anymore then, but it needs to stay server side as long as other clients rely on it. Needs to be checked.

**Comment by kobergj** [comment]
> Remove the resharing capability (what's the status on the server side here?)

We couldn't remove it as web defaulted to `true`, we also need to check with other clients what their default is.

> There is one thing not checked: default web client with resharing=false, does it need work on the server side?

Don't understand. The server doesn't know any more what resharing is.

**Comment by JammingBen** [comment]
> > There is one thing not checked: default web client with resharing=false, does it need work on the server side?
> 
> Don't understand. The server doesn't know any more what resharing is.

Me neither 😄 I guess it can be checked then since both the Web client and the server don't know anything about resharing anymore.

**Comment by kobergj** [comment]
Since there is nothing to any more I close this. Feel free to reopen if you feel you still need this ticket

**Comment by JammingBen** [comment]
Let's keep the issue open so we keep track on the 2 remaining tasks in Web.
