### ISSUE TITLE
Not possible to find user by email on web

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#10783]
5.1.0-prealpha+f0089bc1cc
9.0.0-alpha.4

Steps: 
- try to find use by email: full email - `marie@example.org`, trimmed email - `marie@ex`

Expected: it's possible to find users by email

Actual: The backend returns a result, but we don't see the found user on the web

https://github.com/owncloud/web/assets/84779829/059163b4-6198-46ef-9624-dde1dcf5919c

**Comment by JammingBen** [comment]
We need to check if the server is capable of doing this. AFAIK filters are only allowed for admin users, which is why we're using the basic `search` property for searching users by display name. Not sure if this allows searching other user fields.

**Comment by ScharfViktor** [comment]
> Viktor checked, apparently we can use the filter for non-admins as well.

<img width="1318" alt="image" src="https://github.com/owncloud/web/assets/84779829/e12a4af8-1cb6-4526-84ca-5d0088a3448e">
