### ISSUE TITLE
Context menu is empty for not selected tiles

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10793]
## Describe the bug
The file action context menu is empty for not selected tiles.

## Steps to reproduce
1. Upload a file
2. Switch to tiles mode
3. Open the context menu without selecting the file before

## Expected behavior
The context menu shows all relevant file actions.

## Actual behavior
The context menu is empty.

<img width="432" alt="image" src="https://github.com/owncloud/web/assets/50302941/052b86ae-df70-42ef-ae7e-4ad510b31d11">

Issue exists on master, not on `stable-8.0`.

**Comment by kulmann** [comment]
Underlying issue is that the click on the three dots button doesn't select the file/folder in tiles view. In list view it does.
