### ISSUE TITLE
[web] Show Activities (text only)

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10800]
# Description
## User Stories

* > As a user I want to see who made which changes to files, so that I can track modifications.

* >  As a user I want to see who accessed files, so that I can track access.

## Value
- improve collaboration
- provide transparency

## Acceptance Criteria
- new sidebar panel "Activity"
- The panel activity shows the following events, newest events on top
- the amount of activities is limited to 1.000 items
- Events shown are recursive (from all containing subfolders etc.)
- Name of the person who caused the event
- Event types (applicable to files, folders or spaces). text only representation for the first iteration.
  - Added --> "24.12.2024 21:39 Albert Einstein added `new file.txt` to `Ideas`"
  - Deleted --> "24.12.2024 21:39 Albert Einstein deleted `new file.txt` from `Ideas`"
  - Unauthenticated download --> "24.12.2024 21:39 new file.txt was downloaded via Link-for-Albert"
  - Unauthenticated added --> "24.12.2024 21:39 new file.txt was added via Link-for-Albert"
  - Edited --> "24.12.2024 21:39 Albert Einstein edited `new file.txt` in `Ideas`"
  - Moved --> "24.12.2024 21:39 Albert Einstein moved `new file.txt` to `Ideas`"
  - Renamed --> "24.12.2024 21:39 Albert Einstein renamed `new file.txt` to `Idea.txt`"
  - Shared
    - --> "24.12.2024 21:39 Albert Einstein shared `new file.txt` with `Marie Curie, Maurice Moss, Class 7a`"
    - --> "24.12.2024 21:39 Albert Einstein removed `Marie Curie, Maurice Moss, Class 7a` from `new file.txt`"

    - --> "24.12.2024 21:39 Albert Einstein added `Marie Curie, Maurice Moss, Class 7a` as member of `Marketing`"
    - --> "24.12.2024 21:39 Albert Einstein removed `Marie Curie, Maurice Moss, Class 7a` from `Marketing`"

     - --> "24.12.2024 21:39 Albert Einstein shared `new file.txt` via link
     - --> "24.12.2024 21:39 Albert Einstein removed link from `new file.txt`

- Seeing Activities depends on a permission (enabled by default)
  - if the permission is not given, the activity panel is not shown at all
if there are no activities yet, show "No activities available"
- show a notice on bottom of the activity "Showing max. 1.000 activities." (should be a reasonable value so that the user gets a result within somewhat 4 seconds)

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

## Visuals

![screenshot_002568](https://github.com/owncloud/web/assets/26610733/402ef7c2-e73d-44fc-b29b-3f6c90c16e78)

**Comment by tbsbdr** [comment]
- icon: pulse
![screenshot_002690](https://github.com/owncloud/web/assets/26610733/2bd4db4c-29ff-440f-ba1a-e5d6441f1617)
- wording: checked onedrive, dropbox and google drive: all call it "**Activity**" so singular might be the right way. But if you want to call it in plural, I won't veto.

**Comment by AlexAndBear** [comment]
Thank you @tbsbdr can you also provide me a mockup when no activities have been recorded ?
