### ISSUE TITLE
Link creation modal not scrollable

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#10814]
## Describe the bug
If the browser height is small I'm not able to click on the button for creating submitting the link creation modal.

## Steps to reproduce
1. Have a small browser height
2. Create a file
3. Click on the "copy link" quick action in the file list
4. Type in a password so that the (rather lengthy) password rules appear

## Expected behavior
The controls of the modal (Cancel and Submit buttons) are always visible

## Actual behavior
The controls of the modal are not in the visible area anymore

## Screenshot
<img width="1156" alt="Screenshot 2024-04-22 at 22 41 59" src="https://github.com/owncloud/web/assets/3532843/8924b0db-7bfa-46e2-bbb7-41fefd17d663">

## Additional context
Please fix on `stable-8.0`.

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/10816.
