### ISSUE TITLE
Closing editors on password protected links with auth context

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10828]
## Describe the bug
Closing file editors on password protected links with auth context (though without having actual access to the resource) renders an empty file list.

## Steps to reproduce
1. As "admin", create a folder and upload a PDF file into the folder
2. Create a password protected public link for that folder
3. As "einstein", open that link and enter the password
4. Open the PDF file
5. Close it again

## Expected behavior
The file list containing the PDF file is being displayed after the file has been closed.

## Actual behavior
The file list is empty after the file has been closed.

Issue exists on current master, needs checking if `stable-8.0` is affected as well.

**Comment by AlexAndBear** [comment]
Little technical design. It looks like the currentFolder is not set, after closing the viewer/editor

**Comment by JammingBen** [comment]
Seems to be fixed meanwhile, couldn't reproduce on master and on stable-8.0.
