### ISSUE TITLE
User-member gets sse event as created new file when space description or space image updated

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#10833]
Version	5.1.0-prealpha+78ba48378
Web client version	9.0.0-alpha.5

Steps: 
- admin adds member to the space
- member opens space
- admin changes: 
<img width="229" alt="Screenshot 2024-04-25 at 10 32 14" src="https://github.com/owncloud/web/assets/84779829/125541e5-4861-4a12-b551-a69dca8b7752">

Expected: members sees that: space image/description is updated

Actual:  member gets sse event - correct. member see that new file `readme.md` or `image/emoji.png` is created

https://github.com/owncloud/web/assets/84779829/59b4bdff-fa9b-4f2f-8017-93bec528f317

cc @AlexAndBear

**Comment by AlexAndBear** [comment]
Currently not implemented, I don't know if planned

**Comment by AlexAndBear** [comment]
Closed because this is planned in 

https://github.com/owncloud/web/issues/10648
