### ISSUE TITLE
User can accidentally share parent folder

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#10918]
`Version | 5.1.0-prealpha+0ac03d8a8`
`web 9.0.0-alpha.5`

Steps: 
- create folders `mainFolder/subfolder` 
- go inside the mainFolder
- open share dialog and before creating share and link -> make right click 
- create share or link of the `subfolder`

Actual: user accidentally share parent folder. Yes, right sidebar has title `mainFolder` but the user may not notice it

Expect: Right-clicking does not switch the sidebar to the parent folder. don't confuse the user 😀

**Comment by kulmann** [comment]
Fixed via https://github.com/owncloud/web/pull/10936
