### ISSUE TITLE
App menu items can't be clicked in text editor

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10930]
## Describe the bug
Items in the app menu on the top left can't be clicked because the editor seems to prevent that.

## Steps to reproduce
1. Open a text file in the text editor
2. Open the app menu on the top left
3. Click one of the items at the bottom

## Expected behavior
The item can be clicked.

## Actual behavior
I cannot, the click always targets the editor.

<img width="528" alt="image" src="https://github.com/owncloud/web/assets/50302941/4296585e-3cfd-4e4e-953e-1444fc0dc5bf">

**Comment by AlexAndBear** [comment]
Yikes 😰 assigned
