### ISSUE TITLE
Space doesn't get updated after navigating into another space

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10941]
## Describe the bug
The current space doesn't get updated after navigation into another space, e.g. via search result or the upload info box.

## Steps to reproduce
1. Create a project space
2. Go to your personal space and create a folder "New folder"
3. Search for the project space
4. Navigate to the project space by clicking it in the search results
5. Try creating a folder "New folder"

## Expected behavior
"New folder" is being created in the project space.

## Actual behavior
"New folder" is not being created. The server responds with a conflict because the space has not been updated and Web is trying to create "New folder" in the personal space.

This error affects a whole bunch of actions like creating folders, uploading resources, pasting resources etc.

**Comment by kulmann** [comment]
Fixed via https://github.com/owncloud/web/pull/10943
