### ISSUE TITLE
[QA][e2e-test] use graph endpoint to do the share in API steps

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#10949]
We have these new graph endpoints to the the resource/drive share.
- drive: https://owncloud.dev/libre-graph-api/#/drives.root
- resource: https://owncloud.dev/libre-graph-api/#/drives.permissions

Since ocs sharing will be removed soon, let's move on to use the graph endpoint to do the share via API in the e2e tests.

Open task:
- [x] do the share via graph endpoint (SharingNG) @ishabaral https://github.com/owncloud/web/pull/11003
  - [x] add members to space
  - [x] share resources of the personal space
  - [x] share resources of the project space
- [x] create a public link (SharingNG) @ishabaral https://github.com/owncloud/web/pull/11075
     some scenario has webUI steps which can be changed into API like 
   - ~[ ] officeSuites,feature~ not required
   - [x] languageChange.feature
   - [x] rename.feature
   - [x] shortcut.feature
- [x] remove ocs sharing helpers https://github.com/owncloud/web/blob/78b6d4ad7ef36f174fa96b5393732f0f714872ef/tests/e2e/support/api/share/share.ts#L35-L67

**Comment by saw-jan** [comment]
assigned to @ishabaral

**Comment by ishabaral** [comment]
completed
