### ISSUE TITLE
Getting a file sharing link requires a password

### ISSUE THREAD

**Issue by abatie** [owncloud/web#10967]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Click on Copy Link for a file, select "anyone with link can view", then click on Copy Link. It refuses to generate one without a password. There is a closed case for this behave *9 years* ago that said it would be fixed, but this is in a brand new instance I just installed.

### Expected behavior

It should generate a link without requiring a password

### Steps to reproduce the issue

Steps give above

### Screenshots

![password-required](https://github.com/owncloud/client/assets/5952476/fdda3898-d613-49ec-bc93-858fd150e51e)

### Logs

I don't think a log is relevant

### Client version number

Using web interface from "docker pull" today - it doesn't show a version

### Server information

"docker pull" today - it doesn't show a version; on Ubuntu 22.04.4 LTS

**Comment by JammingBen** [comment]
This is the default behaviour in oCIS, however, you can change this by setting `OCIS_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD` to `false` for your oCIS instance.

**Comment by abatie** [comment]
OK, thanks!

**Comment by abatie** [comment]
OK, that seems to be an environment variable, but I'm running ocis as a docker container and there doesn't seem to be any way to set it - the documentation all assumes you have access to everything. When I start a shell in the container, all the directories are empty. The Admin Settings in the web interface have pretty much nothing to set.

**Comment by JammingBen** [comment]
You can set env variables for your Docker containers like this: https://docs.docker.com/compose/environment-variables/set-environment-variables/ (or https://docs.docker.com/reference/cli/docker/container/run/#env if you're not using docker compose).

**Comment by kulmann** [comment]
@abatie in addition to what @JammingBen said/linked, are you running the docker container yourself or is someone else running it for you? In other words, are you allowed to set env variables for the docker container and restart it, or can you only get access to the running docker container?

**Comment by abatie** [comment]
On 5/28/24 11:38 PM, Benedikt Kulmann wrote:
> @abatie <https://github.com/abatie> in addition to what @JammingBen 
> <https://github.com/JammingBen> said/linked, are you running the docker 
> container yourself or is someone else running it for you? In other 
> words, are you allowed to set env variables for the docker container and 
> restart it, or can you only get access to the running docker container?

It's mine, and setting the environment variable fixed the problem, 
thanks (a closer look at the docker run startup command showed that some 
other env was getting set with -e option, so I just added one more to 
the list)

**Comment by kulmann** [comment]
Cool, glad that this worked out. Please do reach out if you have more questions or issues 🙂
