### ISSUE TITLE
Search user autocomplete and create link broke in 9.0.0-alpha.4

### ISSUE THREAD

**Issue by pascuflow** [owncloud/web#10984]
## Describe the bug
Whenever I try to create a link for a file, Chrome logs show `TypeError: Cannot read properties of undefined (reading '@libre.graph.displayName'`

Also, the search bar under Share With People no longer autocompletes.

**Comment by JammingBen** [comment]
I think this has been fixed already via https://github.com/owncloud/web/pull/10738. Could you try with the newer Web version `9.0.0-alpha.5` (bundled together with latest oCIS master) or `9.0.0-alpha.6`?

**Comment by pascuflow** [comment]
Ok, it works with Ocis 5.0.5 and 9.0.0-alpha.6, but now my custom theme is not loaded:

 ```
 invalid theme. Using default theme. ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "common",
      "shareRoles"
    ],
    "message": "Required"
  }
]
```

and anytime I navigate by clicking on the left sidebar nothing loads, the spinner it stuck.

`Cannot read properties of undefined (reading 'trim')`

**Comment by pascuflow** [comment]
I'll revert back to 9.0.0-alpha-3 for now.
