### ISSUE TITLE
e2e - SecureView tests

### ISSUE THREAD

**Issue by AlexAndBear** [owncloud/web#10985]
See:
https://github.com/owncloud/web/issues/10765

Things to test in secure view share:
- File opens with Collabora 
- Download not possible (in shared with me page and inside the share)
- Copy and paste not possible (in shared with me page and inside the share)
- Sharing not possible
- Previews/Thumbnails not displayed

**Comment by saw-jan** [comment]
Some were added in https://github.com/owncloud/web/pull/10944 but skipped here https://github.com/owncloud/web/pull/10946/commits/67c948d87d25be095789b661e164a357735dd878
Reason: https://github.com/owncloud/web/pull/10946#issuecomment-2125103076

**Comment by ScharfViktor** [comment]
https://github.com/owncloud/web/pull/11236 https://github.com/owncloud/web/pull/11203
