### ISSUE TITLE
Uncaught console error in web

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11011]
how to find error see here: https://github.com/owncloud/web/pull/10993#issue-2333240779
see all fails here: https://drone.owncloud.com/owncloud/web/44914

<details>
<summary>  ##  TypeError: Cannot read properties of undefined (reading 'storageId') </summary>
```

- `user1` creates `f1/file.txt`
- `user1` shares `f1` with edit role
- `user2` renames `file.txt` 

Result: `user1` gets error `Cannot read properties of undefined (reading 'storageId')`
</details>
<details>
<summary>  ##  "TypeError: Cannot read properties of undefined (reading 'split')" </summary>

run test `tests/e2e/cucumber/features/spaces/participantManagement.feature:3`

</details>
<details>
<summary>  ##  "TypeError: cancel" </summary>

run test `tests/e2e/cucumber/features/shares/link.feature:312`
- `user1` creates `f1/file.txt`
- `user1` create link to `f1` with edit role
- `public` opens link
-  `user1` changes password of link
- `public` refresh page

Result: `public` gets error `Uncaught (in promise) cancel`
</details>
<details>
<summary>  ##  "TypeError: Cannot read properties of null (reading 'getTabs')" </summary>

run test `tests/e2e/cucumber/features/app-provider/officeSuites.feature:17`

**Comment by AlexAndBear** [comment]
I decided to give it a P2 since this will enhance our automated testing and should be quite relevant for rolling releases

**Comment by JammingBen** [comment]
`Uncaught (in promise) cancel` looks like an error you get when canceling a task. There are situations where we do this intentionally, so it might be sufficient to wrap this in a `try { ... } catch (e) { }` block.

**Comment by AlexAndBear** [comment]
> `Uncaught (in promise) cancel` looks like an error you get when canceling a task. There are situations where we do this intentionally, so it might be sufficient to wrap this in a `try { ... } catch (e) { }` block.

Hm I can't find anything that cancel or cancelAll should throw an error in the docs 🤔

**Comment by AlexAndBear** [comment]
@ScharfViktor 
"TypeError: Cannot read properties of null (reading 'getTabs')"
run test tests/e2e/cucumber/features/app-provider/officeSuites.feature:17"

that is an issue in collabora, unfortantly we can't fix this. I would propose to not fail on external app errors maybe ?

**Comment by ScharfViktor** [comment]
> that is an issue in collabora, unfortantly we can't fix this. I would propose to not fail on external app errors maybe ?

yes, we may to not fail tests when `suite == "oCIS-app-provider"`
