### ISSUE TITLE
[web] Show a constant loading spinner during initial page load

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#11041]
The initial page load currently is quite messy when it comes to loading spinners.

First the JS chunks are being loaded (we can't show anything during that). Then some loading spinner pops up, but only for a short moment before the page goes completely blank again. Then the blue background appears. Then a loading spinner appears again and the application gets painted eventually.

I guess it will be quite hard to display a constant loading spinner all the time, but I'm still pretty sure we can provide a better UX than what we currently have.

@kulmann @tbsbdr What do you think, let's tackle that in the future?

**Comment by tbsbdr** [comment]
Yes, please. What does it cost?

**Comment by JammingBen** [comment]
Hard to say, could be 1pd, maximum 3pd I'd guess.
