### ISSUE TITLE
File/Folder count in Details panel for current folder

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#11056]
# Description

## User Stories

* > As a user with high file count in one folder, I want to see at a glance how many files/folders the current folder contains so that I don't have to scroll the file list to the bottom, where the footer displays that exact information.

## Value
Easy UX

## Acceptance Criteria
- in Details panel, show file/folder count above the `Size` if available
  - show a total count and additionally a detailed count (files / folders / hidden) like in the footer
  - only show for folders and space roots
  - only show for current folder/space root, not for items in the file list, because:
  - afaik this information is only available in a file listing (propfind with depth=1), not in a search response or on the children of a propfind

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by tbsbdr** [comment]
like that?
![screenshot_002778](https://github.com/owncloud/web/assets/26610733/6f91bf17-7ffc-4fd1-bd02-0c55dadd1ce8)

**Comment by kulmann** [comment]
Yes, that would be cool. Having it in the `Size` field as additional information if available is a good idea 👍 

For completeness, when you also have hidden items it would read as follows:

`1.5 MB, 7 items (4 files including 1 hidden, 3 folders including 2 hidden)`
