### ISSUE TITLE
Shortcuts with no protocol prefix

### ISSUE THREAD

**Issue by jesmrec** [owncloud/web#11063]
## Describe the bug

Web client creates shortcuts without protocol prefix (if not typed by the user), that leads to unexpected behaviours in other clients that expects the URL inside the shortcuts with http/https. Mobile clients can not open URLs in a browser if the URL has no http/https protocol 

## Steps to reproduce

1.  New > Shortcut
2. Add URL without protocol prefix, like `owncloud.com`
3. Open shortcut in iOS client

## Expected behavior

iOS client opens correctly the shortcut

## Actual behavior

iOS can't open because the URL lacks of protocol

Actually, every client behaves in a different way:

- Web: doesn't add protocol in creation phase
- iOS: add protocol in creation phase
- Android: initially, add protocol in creation phase (this is still under QA)

As this unofficial format guide: https://www.lyberty.com/encyc/articles/tech/dot_url_format_-_an_unofficial_guide.html

```
URL

The URL field is self-explanatory. It’s the address location of the page to load. It should be a fully qualifying URL with the format protocol://server/page. A URL file is not restricted to the HTTP protocol. In general, at least, whatever that can be saved as a favorite is a valid URL.
```

So, my suggestion is:

- If user types the protocol in the URL, everything OK ✅ 
- If not, adding `https://` as default in creation phase

Open to discussion with @felix-schwarz @Aitorbp @JuancaG05 @TheOneRing

**Comment by kulmann** [comment]
Fix for this should land in `stable-8.0` and `master`. A patch release of v8.0 makes sense.

**Comment by kulmann** [comment]
I agree with the default behaviour of adding `https://` if the user didn't provide a protocol. 👍

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/11076.
