### ISSUE TITLE
Editors with `save` action (AppWrapper) don't use renewed token, 401 on save

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#11062]
## Describe the bug
When I keep an editor open until after a token renewal has happened, attempting to save my work results in a `401`. Apparently the renewed token is not being used, but the old expired one.

## Steps to reproduce
1. Create an `.md` file with out text editor app
2. Write some content
3. Wait until you see a `token` request in the network tab (= token renewal, happens every 5 minutes by default)
4. Click `Save` in the app top bar

## Expected behavior
Document gets saved.

## Actual behavior
Document doesn't get saved. I see an error toast, but if I ignore that (and the warning about the dirty state when leaving the page) my work is lost.

## Additional context
Needs fixing in current `master` and in `stable-8.0`.
@JammingBen and me already looked into this and think that the underlying issue is, that the `webdav` client gets destructured from the `clientService` and that the headers loose their reactivity with that.

**Comment by jnweiger** [comment]
Tested this with web-7.0.3 on oc10.15.0-rc.1 -- seems unaffected.

**Comment by AlexAndBear** [comment]
> Tested this with web-7.0.3 on oc10.15.0-rc.1 -- seems unaffected.

? oc10 + web 7 that's not really up 2 date, I don't think it makes sense to put effort into that outdated versions
