### ISSUE TITLE
download in editor context menu downloads last saved state (what about dirty state?)

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#11072]
# Description
For downloads from within an editor it could be perceived as a bug, that the last server side known state is downloaded while changes to the open document don't appear in the download. We should save the document before downloading it.

## User Stories

* > As a user who currently edits a markdown file, I want changes to my document being saved before downloading it, so that I don't accidentally have an "old" state of the document on my local disk.

## Value
UX

## Acceptance Criteria
- if a document is in a dirty state (we already detect that in the AppWrapper... is the solution sufficient?!):
  - auto-save the file
  - wait until auto-save is finished
  - download the file
- technical detail: since we only track the dirty state within the AppWrapper, we should wrap the handler of the download action with the check if the document is in a dirty state and trigger the auto-save from there.

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by tbsbdr** [comment]
I'd keep it simple and save implicitly before download. if the save is unwanted, the user can still go back in versions.
lets keep it simple, no risk no fun, quod licet Iovi, non licet bovi.

**Comment by kulmann** [comment]
> if the save is unwanted, the user can still go back in versions.

... well, that's not true for share receivers, because versions are not exposed in shares. ;-) But anyway, fine by me. I'll change the acceptance criteria accordingly.

**Comment by tbsbdr** [comment]
ok, lets try. if accidents happen, we can adjust it and add a safety net dialog.
