### ISSUE TITLE
Possible `$ngettext` problem

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#11088]
## Steps to reproduce
1. Switch language to German and start creating a link share for a file/folder
2. Shut down backend while on "create link" modal, add password and click "create"
3. See only partially translated error popup

<img width="443" alt="Screenshot 2024-06-24 at 14 19 58" src="https://github.com/owncloud/web/assets/16822008/e101235e-6c67-4ba2-b345-c1f4491b95a4">

## Expected behavior
Fully translated error popup

## Actual behavior
Only partially translated error popup via https://github.com/owncloud/web/blob/226058908e4c669c675f7f57d55f687b78104ed3/packages/web-pkg/src/composables/actions/files/useFileActionsCreateLink.ts#L74

**Comment by JammingBen** [comment]
Can't reproduce this 🤔 

<img width="414" alt="image" src="https://github.com/owncloud/web/assets/50302941/2e32fe7e-4b7e-4855-ba11-6967c2f37c19">

Which version are you on? Is `Failed to create link` present in one of the `translation.json` files?

**Comment by pascalwengerter** [comment]
Rebased my branch, can't reproduce anymore myself 🥴 sorry for the noise
