### ISSUE TITLE
Initial page loading spinner never hides in some scenarios

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#11083]
## Describe the bug
The initial page loading spinner never hides in scenarios where we don't load all apps. This is due to the fact that the spinner only gets removed via a callback after all apps have been loaded.

## Steps to reproduce
1. Go to https://host.docker.internal:9200/access-denied
2. Enjoy the endless loading state

## Expected behavior
The loading spinner eventually disappears.

## Actual behavior
It stay forever on such pages.

This is a regression from https://github.com/owncloud/web/pull/11054.

**Comment by kulmann** [comment]
I can't reproduce it with current master 🙈  neither mit `vite` nor with a production `build`.

**Comment by JammingBen** [comment]
Now I can't either... but it's a timing issue. The loading spinner appears after 0.5 seconds. Meaning if the page loads faster than that, everything is fine. But if it's slower, then the loading spinner will appear and never go away.
