### ISSUE TITLE
always download archives as "zip" 

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#11080]
# Description

## User Stories

* > As a user who only can unzip zip files, I want to download archives as zip so that I can unzip the archive.

## Value

- maximize compatibility

## Acceptance Criteria

- always download archives as .zip (no more .tar or alike)

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by tbsbdr** [comment]
fyi @individual-it

**Comment by AlexAndBear** [comment]
Hell yes, this is kinda important, we can't expect ppl having tar tools lying around

**Comment by AlexAndBear** [comment]
blocked by https://github.com/owncloud/ocis/issues/9399

**Comment by AlexAndBear** [comment]
Fixed via: https://github.com/cs3org/reva/pull/4766

no web code update is necessary
