### ISSUE TITLE
Closing an editor with a dirty state does not remove the beforeunload listener

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#11092]
## Describe the bug
As per title. That means after the editor has been closed, reloading the page still shows the browser popup asking the user if they want to leave the page.

## Steps to reproduce
1. Open some text document with the text-editor app
2. Change something, don't save
3. Hit the "back"-button in your browser
4. Hit any button in the modal, doesn't matter
5. In the files list, try reloading the page

## Expected behavior
The page gets reloaded.

## Actual behavior
The browser is asking the user if they want to leave the page.

**Comment by kulmann** [comment]
Closed via https://github.com/owncloud/web/pull/11094
