### ISSUE TITLE
FR: Show detailed information about a share

### ISSUE THREAD

**Issue by AlexAndBear** [owncloud/web#11101]
As a user I want to know what I can do within a share (permissions). Especially if I am navigating in a secure view share

**Comment by kulmann** [comment]
As far as I can see the backend doesn't expose this information, right? If that's correct, could you create an ocis issue for this? If it does I can take care of the web story.

**Comment by AlexAndBear** [comment]
I think this information is in the GraphSharePermissions that are accessible trough sharing Ng ? Or am I wrong ?

**Comment by JammingBen** [comment]
The `.../permissions` endpoint for a resource returns all the graph permissions the user is allowed to share the resource with. You want to have that information for an existing share though, right?

I guess you can always query the permission that holds all necessary information. Or maybe the DAV permissions are sufficient? They should indicate what the user is allowed to do and what not.

**Comment by AlexAndBear** [comment]
> The `.../permissions` endpoint for a resource returns all the graph permissions the user is allowed to share the resource with. You want to have that information for an existing share though, right?
> 
> I guess you can always query the permission that holds all necessary information. Or maybe the DAV permissions are sufficient? They should indicate what the user is allowed to do and what not.

Yep about existing share. From what I remember of my implementation for secure view. The graph permissions are already persisted in the shared resource object

**Comment by JammingBen** [comment]
> The graph permissions are already persisted in the shared resource object

Correct 👍 The terminology is a bit confusing here: a "share" in our terms is a "permission" in Graph terms. A "permission" in our terms is an "action" in Graph terms.

Still, the DAV permissions give away all necessary information, no? They are a bit more "digestable" than the Graph permissions.

**Comment by kulmann** [comment]
> They are a bit more "digestable" than the Graph permissions.

That's a sad thing to say about a new API 😢

**Comment by JammingBen** [comment]
Hmm not sure if I would agree. From a UI perspective - yes, definitely! But from a server perspective, having them so granular might actually be a good thing. IMO they are just not designed to be visualized in some UI.
