### ISSUE TITLE
Disallow managing the users via an ocis admin menu when using an external IDP

### ISSUE THREAD

**Issue by 2403905** [owncloud/web#11119]
## Describe the bug
When the ocis installation is using an external IDP like keycloak we have disalow the user menegment actions in an ocis admin menu  that can confuse an admin and lead to inconsistent data.
There are two cases: rename user and create a new user.

## Steps to reproduce
1. Login as `moss` and logout
2. login as an `admin` -> open `admin-settings/users` -> rename `moss` to `mossNew`
3. Try to login as `mossNew`
4. After `admin` logout and login agen he can see two records `moss` and `mossNew` 

## Expected behavior
You logged in as `mossNew`.
Only `mossNew` exists.

## Actual behavior
Login is failed.
There are two rows in an ocis user setings `moss` and `mossNew`  

## Setup
ocis 5.0.5  ocis_keycloak/docker-compose.yml
 
<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by kulmann** [comment]
Did you check https://owncloud.dev/services/frontend/#define-read-only-attributes ?

**Comment by AlexAndBear** [comment]
We have the OCIS_LDAP_SERVER_WRITE_ENABLED env variable, according to docs setting it to false, it will result in:
- disable the create user button
- disable the delete user button
- disable editing the user attributes

See **https://owncloud.dev/services/frontend/**

So from my POV everything is working nice but hard to understand (docs related)

**Comment by 2403905** [comment]
Thank you. It looks like a misconfiguration of the deployment example.
