### ISSUE TITLE
Change Icon of "Actions" Sidebar Panel

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#11111]
## Proposal
I propose to change the "Actions" Icon. The current icon relates also to a "Presentation" wich does not fit here.
Proposing the icon: `play-circle-line` https://remixicon.com/icon/play-circle-line

## Current Status
![screenshot_002828](https://github.com/owncloud/web/assets/26610733/08655633-ff33-4eaa-81aa-5fe778f7a367)

## Proposal visual
![screenshot_002827](https://github.com/owncloud/web/assets/26610733/1e4cd51e-4300-4cb4-938c-c97e2a38fe52)

**Comment by AlexAndBear** [comment]
Do we have alternatives? Ihmo this looks kinda old-school and ugly 🙈

**Comment by pascalwengerter** [comment]
I think the proposed change is definitely an improvement. Looking at https://owncloud.design/#/Design%20Tokens/IconList it is really tough coming up with an alternative suggestion...

**Comment by tbsbdr** [comment]
Its the best i could find. Btw same as gh actions. Do you have something more suitable in mind?
