### ISSUE TITLE
Run the skipped app provider e2e tests

### ISSUE THREAD

**Issue by SagarGi** [owncloud/web#11116]
### Description
We had a failure for the app provider e2e tests https://github.com/owncloud/web/issues/11108 which was introduced by the PR https://github.com/owncloud/web/pull/11103 .  The fix was made with the PR https://github.com/owncloud/web/pull/11113 but at the mean time we have skipped the app provider e2e tests because it is failing with issue https://github.com/owncloud/web/pull/11115#issuecomment-2197142841. 
 #10435 

Refer to this link for more information.
https://github.com/owncloud/web/issues/11108
https://github.com/owncloud/web/pull/11115

#### TODO
- [ ] unskip all the skipped app provider test (investigate)
- [ ] adjust the test code if necessary.

**Comment by S-Panta** [comment]
Creating a file(word or only office)  via API opens a dialogue box that wants to select the text option.

**Comment by S-Panta** [comment]
Working on this issue is possible if this is fixed https://github.com/owncloud/web/issues/11129
