### ISSUE TITLE
[Web] Consistent + Improve Link Permission Dialog

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#11122]
# Description

Since the introduction of the link permission dialog, we have a non-consistent ux for setting link permissions. Plus: the current dialog provides quite a lot visual infos upfront which should be put into a better hierarchy so that users are not overwhelmed.
This is a proposal to align the link permission dialog triggered from the filelist or the right sidebar. Tradeoff: drop consistency of people and link permission dropmenus as the link permission options got too extensive.

## User Stories

* > As a user I want a consistent link permission dialog so that it does not make me wonder.

## Value
- improve link permission dialog
- improved usability
- enhanced learnability
- reduced cognitive load
- error reduction
- efficiency in development

## Acceptance Criteria

- Link Sharing dialog can be opened from:
  - Click on Quickaction "Copy Link"
  - Context menu (right click/3-dots) "Copy Link"
  - Click on Right sidebar > Sharing > Share via Link > [Link Permission]
  - Click on Right sidebar > Sharing > Share via Link > Create Link (quick link)
  - Click on Right sidebar > Sharing > Share via Link > Add link
- **Dialog**
- If defaultlinkpersmissions=0, then use private link instead of "internal" role.
  - shows current (initially: default) link role
  - new button "Options", click on Options shows radio selection
    - People with existing access (=copies private link)
    - Anyone (+ world-Icon), if selected, show
      - password field (if enforced via policy)
      - drop menu as currently is in the "share via link" section, except ~invited ppl~ (we are dropping the "Internal" role from the UI):
        - Can view
        - Can upload
        - Can edit
        - Secret File Drop

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

## Release Note
We have unified the link sharing dialog to simplify the sharing process. This update brings improved usability, enhanced learnability, reduced cognitive load, and error reduction, making it easier and more intuitive to share links. Enjoy a consistent sharing process!

## Visual and Flow
![image](https://github.com/owncloud/web/assets/26610733/0f2206f0-0317-4cbb-a64d-b724b43b60f2)

**Comment by AlexAndBear** [comment]
🤩

**Comment by tbsbdr** [comment]
on hold, first step: https://github.com/owncloud/web/issues/11204 then lets iterate
