### ISSUE TITLE
[Secure View] If no secure view app is present, default action is "hide share"

### ISSUE THREAD

**Issue by micbar** [owncloud/web#11138]
## Steps to reproduce
1. Create  File which cannot be viewed in Collabora
2. Share with "Secure Viewer" with Alice
3. As "Alice", log in and browse to the received shares
4. Click on the Shared File

## Expected behavior
If no app is available, nothing should happen

## Actual behavior
The share disappears from the UI because the default action is "hide share"

## Setup
docker compose ocis_full with default configuration

**Comment by micbar** [comment]
@tbsbdr @kulmann @JammingBen 

Would be nice to get this into the next rolling on monday.

**Comment by JammingBen** [comment]
I'll check it, was about to grab a new issue anyway.
