### ISSUE TITLE
Parent folder tooltip partially hidden behind other elements

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#11135]
## Describe the bug
The parent folder tooltip is partially hidden behind other elements.

## Steps to reproduce
1. Delete a file
2. Navigate to the trash bin where the file is located
3. Hover over the parent folder link

## Expected behavior
The tooltip should be visible above other elements.

## Actual behavior
The tooltip is partially hidden. Maybe a regression from https://github.com/owncloud/web/pull/11087?

<img width="249" alt="image" src="https://github.com/owncloud/web/assets/50302941/86c2eb73-5add-4680-b90c-28e5edde88d5">

**Comment by pascalwengerter** [comment]
Urgh, having caused that I'll take a look

**Comment by pascalwengerter** [comment]
I think I found the culprint, but the result doesn't really spark joy - do we really need to provide the hover with path prefix on the resource as well as the hover on the parent name underneath?

<img width="517" alt="Screenshot 2024-07-04 at 12 33 50" src="https://github.com/owncloud/web/assets/16822008/d509586c-ef2b-4829-94ba-eb580d216b41">

**Comment by kulmann** [comment]
The tooltip on the file name is only really relevant if the file name gets truncated in the list. But afaik we can't know that and because of that we just always show the tooltip on the file name.
