### ISSUE TITLE
File with a space is replaced with + on downloading

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11169]
Version	6.1.0
Web client version	9.1.0
MacOs 14.4.1 

Steps: 
- create file `new file.odt` (with space)
- download file

Expected: file is downloaded as `new file.odt`

Actual: file is downloaded as `new+file.odt`
![Screenshot 2024-07-10 at 09 32 41](https://github.com/owncloud/web/assets/84779829/b601a847-f3b3-4671-b212-eb8920ec016f)

**Comment by JammingBen** [comment]
Might be a fallout from https://github.com/cs3org/reva/pull/4748 😬

**Comment by ScharfViktor** [comment]
@JammingBen please adapt the e2e download.feature when you fix this bug as https://github.com/owncloud/web/compare/downloadFileWithSpace?expand=1

We could have found this degradation if we had a test for it, but we didn't.

![Screenshot 2024-07-10 at 10 11 08](https://github.com/owncloud/web/assets/84779829/c232d604-bb09-41de-a4c6-70b56685dba6)

**Comment by ScharfViktor** [comment]
wile with `?` `:` `*` `|` `\` `;` `<>`-> changed as `_`
![image](https://github.com/owncloud/web/assets/84779829/f1f028f7-7264-43a0-997a-afd4cde9ba30)

**Comment by kulmann** [comment]
> > file with `?` `:` `*` `|` `\` `;` `<>`-> changed as `_`
> 
> This "issue" is not new though, and I'm not sure if there is anything we can do about it. The `content-disposition` header is being encoded correctly, so this seems to be a browser thing. @kulmann How do you feel about this, acceptable?

That's acceptable. As long as blanks work correctly again. 👍

**Comment by JammingBen** [comment]
Fixed via the current oCIS rolling release.

See https://github.com/owncloud/web/pull/11187 for the e2e test adjustment.
