### ISSUE TITLE
numerical tags causes serious problem!

### ISSUE THREAD

**Issue by nazarifard** [owncloud/web#11193]
if user add number as a tag to one folder, the folder will be missed entirely!
for example; adding 1234 as a tag will cause the resource disappear totally.

**Comment by nazarifard** [comment]
> Awesome. You loose your complete personal space if you add numerical tags to a resource. Works also in project spaces. Needs a fix asap.

I fixed the issue independently, However first part is also fixed by @AlexAndBear 
But I think it's a It is the tip of the iceberg, likely at least all property of DavPropertyMapping should be double checked.

**Comment by nazarifard** [comment]
Hi @AlexAndBear 
I sent a new PR to fix the issue, but seemingly there is a issue in TestFunctions and my PR is blocked. Can you review the source and or Unit Test functions. I tested locally and my codes is working fine without any issue.

https://github.com/owncloud/web/pull/11197

**Comment by AlexAndBear** [comment]
@nazarifard Thank you very much, let me just adjust the chaneglog and merge it.
