### ISSUE TITLE
Add e2e test for adding numerical tags on a resource

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/web#11195]
### Description
When a tag is added on a resource and the page is reloaded then the resource gets lost and oCIS stops working.
Related issue mentioned here: https://github.com/owncloud/web/issues/11193

We do have test cases for adding tags on a resource but not the numerical tags.
- [ ] Add e2e for adding numerical tags, e.g. `1234`, to a resource. `tests/e2e/cucumber/features/smoke/tags.feature`

**Comment by kulmann** [comment]
Please don't create an e2e test for this. Should only be a unit test on the resource building.

**Comment by PrajwolAmatya** [comment]
> Please don't create an e2e test for this. Should only be a unit test on the resource building.
> 
> Reason: we agreed to not test edge cases in e2e tests anymore. Only happy path tests.

Yes, sure. I will close this issue. :+1:
