### ISSUE TITLE
Shared file details contains not clear Shared via path 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11208]
web 6.1.0+0b8559f91
ocis 9.1.0

Steps: 

- `user1` creates `folder/file.png` 
- `user1` shares `folder` to `user2` 
- `user2` opens `folder` and see details of the `file.png`

Expected: `Shared via` `/f1`

Actual: `Shared via`:` /`
<img width="2132" alt="Screenshot 2024-07-17 at 16 10 35" src="https://github.com/user-attachments/assets/32728474-6a54-4ee1-a8b2-24c122cfea25">

- `user2` clicks by `/`

Actual: he stays in the `folder`. it's not clear where he's supposed to go.

https://github.com/user-attachments/assets/3ee827dc-c9bb-4e9f-9292-ff921ec9f292

**Comment by JammingBen** [comment]
The "Shared via" indicator doesn't make sense in this context, hence we should remove it in shared spaces.
