### ISSUE TITLE
Resource table doesn't show Tag column. is there any setting or configuration to show the Tag column?

### ISSUE THREAD

**Issue by nazarifard** [owncloud/web#11200]
![image](https://github.com/user-attachments/assets/06287d17-6ab1-4463-a822-4adc088a4fcb)

**Comment by AlexAndBear** [comment]
Which version is running? It should just show tags if there are any

**Comment by nazarifard** [comment]
![image](https://github.com/user-attachments/assets/8ba52c60-a47b-480b-af48-2d8d132a0535)

I am using last version that cloned from master. As shown all resources including new file has tags but Resource-Table doesn't show Tag column! can it be related to the  previous related bug, can't be?

**Comment by AlexAndBear** [comment]
I don't think its related, but can you check the console logs for any errors?

I think that the problem you encounter is the viewport width, we hide some table columns if the viewport is small

Thats how it looks on, viewport width < 1200px:
![image](https://github.com/user-attachments/assets/69df6c19-0af9-445d-a957-77e2fade9861)
 
And thats > 1200px:
![image](https://github.com/user-attachments/assets/c9be918e-f86b-446e-b09a-3b2bff309783)

**Comment by nazarifard** [comment]
thank you for your attention, 
My display is flat and wide. however I run OCIS from localhost. 
It reported two errors but likely they aren't related to Tag-Column.

2024/07/16 20:12:57 http: TLS handshake error from [::1]:46968: remote error: tls: unknown certificate
{"level":"error","service":"thumbnails","time":"2024-07-16T20:12:58+03:30","message":"resource info is missing checksum"}

**Comment by AlexAndBear** [comment]
No not related, just something from thumbnail service thats creating previews. 

I am a little confused as the status and tag columns are hidden an that's exactly what we do when the browser width is under 1200px. 

Which browser do you use and could you try another one ?

**Comment by nazarifard** [comment]
![image](https://github.com/user-attachments/assets/e5da6b45-7d68-4b95-aa1e-bbf7f85f1bff)

I'm using Chrome, but its works fine with demo site. it doesn't show tags for my local site. it may be related to ocis/web configuration not browser/display.

**Comment by nazarifard** [comment]
Dear @Alex it works under docker container. Thank you for your supports.
![image](https://github.com/user-attachments/assets/7890b838-9db1-4d85-b349-5595e30715bb)

**Comment by AlexAndBear** [comment]
Glad for helping you but unfortunately I don't get why it wasn't working in the first place. 

Can we close the issue ?

**Comment by nazarifard** [comment]
yes, certainly. 

It's understandable. Alex It seems names part in resource table uses most part of row space while Tags column may need more spaces, How can I shrink expand Tags columns? I found .oc-table-header-cell-tags in ResourceTable.vue, but I don't know how can resize the column ( or shrink the Name column)? 
can you guide me?

**Comment by nazarifard** [comment]
@AlexAndBear  any idea about expanding Tags column?

**Comment by AlexAndBear** [comment]
Sure, ResourceTable.vue line 653, set width to shrink instead of expand.
You can learn more about that here: https://owncloud.design/#/oC%20Components/OcTable

**Comment by nazarifard** [comment]
many thanks, That's what I was looking for !

**Comment by nazarifard** [comment]
> Sure, ResourceTable.vue line 653, set width to shrink instead of expand, and the tags column to expand or auto. You can learn more about setting the column width here: https://owncloud.design/#/oC%20Components/OcTable

many thanks, That's what I was looking for !
