### ISSUE TITLE
Thumbnails are displayed in some places and in some places not

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11207]
web 6.1.0+0b8559f91
ocis 9.1.0

Thumbnails are not displayed on the:
 -  /files/spaces 
 - /files/search pages

Thumbnails are displayed on the:
- /files/shares

Steps: 
1. `marie` uploads png files to the personal or project space
2. `marie` opens personal space `https://host.docker.internal:9200/files/spaces/personal/marie?fileId=uuid`

Actual: no thumbnails -> no GET preview request

3. `marie` clicks by `Details` 

Actual: can see file preview

4. `marie` shares png file to admin
5. `admin` goes to shares with me page

Expected: user can see thumbnails in the /files/spaces and files/search pages too. 
not sure about search result 
<img width="503" alt="Screenshot 2024-07-17 at 15 59 01" src="https://github.com/user-attachments/assets/b580995a-5deb-48b4-ad8a-366bd2a2d5ea">

Actual: admin can see thumbnails in the /files/shares page

https://github.com/user-attachments/assets/fe37c994-d173-4b1f-a130-95101c0c23a9

**Comment by AlexAndBear** [comment]
@ScharfViktor it behaves complete different for me, could you check the config.json in the network tab and look up the value for disablePreviews ?

**Comment by ScharfViktor** [comment]
> @ScharfViktor it behaves complete different for me, could you check the config.json in the network tab and look up the value for disablePreviews ?

I found it https://github.com/owncloud/web/blob/master/dev/docker/ocis.web.config.json#L13

Then why is it enabled on the "Share with Me" page?

I guess it behaves complete different for you because you use vite and here we enable preview: https://github.com/owncloud/web/blob/master/vite.config.ts#L81

**Comment by AlexAndBear** [comment]
Yup it should not behave different between shared with me and personal space page (some vars are missing).
I would leave the ticket open, and try to make the behavior equal for all views. (assigning myself) 

I wonder why we have the option to disable thumbnails in general @kulmann any idea?

**Comment by AlexAndBear** [comment]
@ScharfViktor can you check if everything is working now as expected: 
https://github.com/owncloud/web/pull/11209

I am not on a computer rn

**Comment by AlexAndBear** [comment]
Discussed with @kulmann we will remove all of this restriction and configuration stuff
