### ISSUE TITLE
Setting a readme space description is not reactive

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#11206]
## Describe the bug
Setting a readme file as description of a project space doesn't reactively update the space. A page reload is needed to view the changes.

## Steps to reproduce
1. Navigate to a project space
2. Create a readme file in the root of the space
3. Right click the file, click "Set as space description"

## Expected behavior
The space description updates.

## Actual behavior
The space description does not update. A page reload is needed.

**Comment by AlexAndBear** [comment]
closing in favour of https://github.com/owncloud/web/issues/11276
