### ISSUE TITLE
Remove config option `options.ocm.openRemotely`

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#11219]
## Describe the bug
The current implementation of the ocm `openRemotely` feature is not secure. We don't want to allow that you can enabled it. Only user is CERN. Let's remove the config option `options.ocm.openRemotely` and instead allow the `openRemotely` feature when `cernFeatures` is set to `true`.

Please also remember to remove the config option from the ocis config struct.

**Comment by AlexAndBear** [comment]
Reopened, see reason: https://github.com/owncloud/web/pull/11244
