### ISSUE TITLE
SSE adapter is throwing errors on reload

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#11235]
## Describe the bug
Reloading the page prints errors from the SSE adapter in the browser console.

## Steps to reproduce
1. Make sure you've set your browser console to "preserve log"
2. Reload the page

## Expected behavior
No error logs in the console.

## Actual behavior
The SSE adapter prints errors in the console. I guess it comes from disconnecting the SSE connection during a reload, so everything will be fine after the reload. Still worth investigating.

**Comment by AlexAndBear** [comment]
This is implemented on purpose we throw a RetriableError. So when the connection gets closed [fetch-event-source](https://github.com/Azure/fetch-event-source) can try to reconnect, we can't differentiate whether the server closed the connection or gets cut via the browser (reload). 
I don't think we need further investigation.
