### ISSUE TITLE
user can see a public link from another space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11262]
related https://github.com/owncloud/enterprise/issues/6785 

https://ocis.ocis.production.owncloud.works/
```
ocis | 5.0.6
web 8.0.4
```

Steps: 
- admin creates a space `s1` and adds a public link to that space
- without reloading page admin goes to spaces room and creates new space `s2`
- opens the sidebar of the members of space `s2`

Expected: no created links

Actual: admin sees a link from `s1`.

https://github.com/user-attachments/assets/7e61d24e-9c61-440d-b754-95941f793577

Note: after reload page -> admin cannot see link in the space `s2`

**Comment by AlexAndBear** [comment]
@kulmann can you maybe answer this question ?

**Comment by kulmann** [comment]
Expected to be released with ocis `v5.0.7`. No ETA for that.
