### ISSUE TITLE
Show More - Show Less

### ISSUE THREAD

**Issue by dragotin** [owncloud/web#11261]
When I open the share pane on the side, it only shows a few share receiver plus a link saying "Show More", as in this screenshot:
![showmore](https://github.com/user-attachments/assets/da8e59ed-684d-4087-a426-41792d55e476)

Clicking on it, enlargens the pane and shows (in this case) the full list of share receivers. However, instead of showing "Show Less" to shrink the dialog again, it still shows "Show More", which is probably wrong.
![showless](https://github.com/user-attachments/assets/80099a5c-b0dc-436e-a324-8485de4de74f)

**Comment by AlexAndBear** [comment]
Whoopsie, thx for report

**Comment by AlexAndBear** [comment]
@kulmann @dragotin On master we don't have the show more / show less button for space members anymore, I can't track down, when this has been removed.

**Comment by kulmann** [comment]
## Steps to reproduce

1. Share a space with e.g. 5 people
2. Select a folder from the file listing of the space
3. Go to the sharing panel

**Comment by AlexAndBear** [comment]
I was under the impression, this was the space root panel, which is working fine.
But I can reproduce it that way
