### ISSUE TITLE
[web] Unzip in Web

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#11264]
# Description
- Unzip is performed on the user side (not server side), because: 
  - filefirewall should take effect
  - simpler handling of quota-check
  - zip-bombing will not affect the server (only the client)

## User Stories

* > As a user I want to unzip files so that I dont rely on a local unzip app.

## Acceptance Criteria
- new web extension "Unzip" in web-extensions repo
- new context menu item for a compressed file: "Extract here" 
- supported formats: `tar` and `zip`
- standard maximum filesize is 64MB 
- click on "Extract here" extracts all files from the archive to the current location into a new folder with the foldername of the archive ( `archive.zip` ->`archive` )
  - filename conflict: If the new extracted folder already exists, the new foldername gets implicitly an appended `archive.zip` ->`archive (2)`
- If extraction for a file is not available, disable the action and show a tooltip "Exceeds maximum size of 64MB"
- while the unzip is in progress, show the top loading bar
- ❌ Not available: batch actions for unzip
- ❌ Not available: extract password protected archives (follow up story)
  - Show error message "File is password protected. Password protected files can not be extracted."
 

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

## Visual
![screenshot_002939](https://github.com/user-attachments/assets/a695f233-7e82-4517-a6e7-9f0b5c6f344b)

**Comment by AlexAndBear** [comment]
Nice 🙂 

But I wonder why we need a new config variable. Will there be systems or user clients where the admin knows that they can safely set a higher value ?

**Comment by JammingBen** [comment]
This is predestined to run in a web worker since this is most likely a synchronous (=UI blocking) task.

> But I wonder why we need a new config variable. Will there be systems or user clients where the admin knows that they can safely set a higher value ?

Also unsure about this. I feel like we need to limit the number if we really want to do this on the client side. Hence a config might not be necessary 🤷

**Comment by dschmidt** [comment]
Dunno, I assume we should be rather conservative when assuming how much power the users' computers have... 
I assume setting a higher value might only be relevant in super small private instances and seeing your current crusade against config options :P it might not be worth adding a config option for that for now

**Comment by AlexAndBear** [comment]
> Just to clarify the requirement - "Extract here" does that mean that "here" is the folder that the Zip file itself is in?
> So as "web" unpacks each file from the zip-file, it will write the file back to the server (= upload it).

Correct

**Comment by kulmann** [comment]
Candidate for a lib: https://github.com/nika-begiashvili/libarchivejs

**Comment by AlexAndBear** [comment]
> Candidate for a lib: https://github.com/nika-begiashvili/libarchivejs

Looks like it has inbuilt web-worker, which is kinda cool
+ Password decryption for possible follow-up
