### ISSUE TITLE
No undo operation using keyboard shortcut (cmd+z) in text editor

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11326]
```
ocis 6.1.0+4b8acf7e4

web 10.0.0
```

Steps: 
- create .txt file or .md file
- add content and try to undo change using keyboard shortcut (cmd+z)

Expected: works
Actual: doesn't work

https://github.com/user-attachments/assets/54866118-22bc-4ef8-b8df-fd9084f2411c

**Comment by AlexAndBear** [comment]
@ScharfViktor indeed

**Comment by AlexAndBear** [comment]
@ScharfViktor we have disabled the command shortcuts for the editor via         useCommandShortcut: false

but I can't remember why, otherwise it would work fine

**Comment by ScharfViktor** [comment]
> @ScharfViktor we have disabled the command shortcuts for the editor via useCommandShortcut: false
> 
> but I can't remember why, otherwise it would work fine

it's strange. because all shortcuts except of`cmd+z` work fine
