### ISSUE TITLE
Margin on "New"-menu is missing

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#11336]
## Describe the bug
The margin above and below the first separator line in the "New"-menu is missing.

## Steps to reproduce
1. Open the "New"-menu

## Expected behavior
There should be a slight margin above and below the first separator line. See e.g. the "Upload"-menu.

## Actual behavior
The margin is missing.

<img width="381" alt="image" src="https://github.com/user-attachments/assets/4b93be65-fb13-4f57-a1ec-99175036fbed">

**Comment by yhmyhm0910** [comment]
Can I be assigned to try solving this issue? Thank you.

**Comment by JammingBen** [comment]
> Can I be assigned to try solving this issue? Thank you.

Sure, I'll assign you. Thank you, this is much appreciated!
