### ISSUE TITLE
Distinguish federated users from internal users

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#11361]
# Description

## User Stories

* > As a user I want to distinguish external from internal users so that I know with whom I share.
## Acceptance Criteria

- show "globe icon" for federated users (in the share list in sidebar and in the share suggestions)
- add context helper "External user, registered with another organization’s account but granted access to your resources. External users can only have “view” or “edit” permission."
- Show in Access details "Type: External"
- The role select for external shares should only suggest the 2 existing external roles (view & edit)

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

## visual

![image](https://github.com/user-attachments/assets/69066aa1-ec4b-4edd-b22c-3b8e55e2df73)

![screenshot_003054](https://github.com/user-attachments/assets/800ab2ee-f4c7-4336-bc8b-914f6a68cb7a)

**Comment by JammingBen** [comment]
Needs https://github.com/owncloud/ocis/issues/9898 to be fixed first.
