### ISSUE TITLE
Nightly fails on app provider ( web master )

### ISSUE THREAD

**Issue by S-Panta** [owncloud/web#11378]
### Description
Nightly fails on e2e test app provider.
```feature
Then "Alice" should see the content "Microsoft Word Content" in editor "OnlyOffice"
    ✖ failed
      locator.click: Timeout 30000ms exceeded.
      Call log:
        - waiting for frameLocator('[name="app-iframe"]').frameLocator('[name="frameEditor"]').locator('#id_viewer_overlay')
        -   locator resolved to <canvas width="931" height="486" class="block_elem" id="id_viewer_overlay"></canvas>
```
Failed log: https://drone.owncloud.com/owncloud/web/46606/14/14
Tracing log: `npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/46606/tracing/open-office-suite-files-with-collabora-and-only-office-alice-2024-8-20-01-39-04.zip`

**Comment by S-Panta** [comment]
@anon-pradip Can you take this task?

**Comment by anon-pradip** [comment]
sure
