### ISSUE TITLE
Group space members can't see other members on resource

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#11384]
## Describe the bug
Users that are member of a space via one of their groups can't see the space member list in the right sidebar for regular resources.

## Steps to reproduce
1. As "admin", create a space and add the group "users" as member
2. As "admin", upload a file within the space
3. As "einstein" (part of group "users"), access that space and open the sharing sidebar panel for the created resource

## Expected behavior
The space members should be listed.

## Actual behavior
They are missing.

<img width="437" alt="image" src="https://github.com/user-attachments/assets/1512ebb7-b9ce-437e-b984-2a248a440511">

**Comment by kulmann** [comment]
Looks ok to me 🤔 

<img width="450" alt="Screenshot 2024-08-26 at 06 49 07" src="https://github.com/user-attachments/assets/01d18d33-f436-4a44-9346-b66901184dc4">

**Comment by JammingBen** [comment]
This has been fixed.
