### ISSUE TITLE
Mobile: Reorganize Account Settings

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#11453]
# Description

## User Stories

* > As a user I want the settings to be optimised for small screens so that I can use it on my mobile phone.

## Value
- improve usability

## Acceptance Criteria
- Stack table header and cells for small screens
-  Actions:
  - Drop menus, links: New line, full width
  - Checkboxes: Side-by-side with description text
  - Matrix: Side-by-side with headline; headline repeats

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

## Visual

![screenshot_003093](https://github.com/user-attachments/assets/0d2e350a-4bc4-47ae-9e24-d690d0b16d85)

**Comment by AlexAndBear** [comment]
Fixed via https://github.com/owncloud/web/pull/11440
