### ISSUE TITLE
User does not get logged out when token renewal fails

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#11478]
## Describe the bug
The user does not get logged out when token renewal fails. As a result, they can still navigate the UI, but all requests will fail.

## Steps to reproduce
1. Login with a user
2. Wait and make sure your device goes into standby
3. Wake up your device and check the UI

## Expected behavior
The user should be logged out if no active refresh token present.

## Actual behavior
They are not.

Kinda hard to debug... maybe manually deactivating the token renewal worker could work for finding a solution.

**Comment by kulmann** [comment]
cc @hodyroff this is what you described in the chat recently.
