### ISSUE TITLE
Add "Save as" to App Top Bar (without rename)

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#11525]
# Description

## User Stories

* > As a user I want a `save as` action so that I can save documents to a different location without leaving the editor.

## Value
- web office basics

## Acceptance Criteria
- Add option "Save as" to App Top bar context menu
- click on "Save as" opens the web embedd mode in location picker mode
- if a file already exists with the same filename, a suffix `document (1).odt` gets implicitly added to the filename (no file conflict resolution dialog)

**not part of this story:** 
- rename file, will be handeled in a different ticket

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

## VIsual
![image](https://github.com/user-attachments/assets/bf78c992-852c-4f32-b871-93b4d0df5d3d)

**Comment by kulmann** [comment]
I see multiple issues here:

1. We could offer the `Save As` action for our native editors (like e.g. the `text-editor`). But we also have an autosave for that, so the result might be VERY confusing for the user: autosaved content in the current file and then the diff from the last autosave to the current state in a new file.
2. We can't offer the `Save As` action for the app provider apps, similar to how we can't offer the `Save` action for the app provider apps. Saving happens server side for the app provider apps.

**Comment by kulmann** [comment]
As discussed in zoom a few minutes ago: We'll finish the `Save As` action for client side editors and offer it in the three dots context menu (not for app provider apps though!).

@AlexAndBear would also make sense to offer this for read-only content, right? That's basically a `copy and rename` use case which might come in handy.

For app provider apps we need a different approach.

**Comment by AlexAndBear** [comment]
@kulmann Implemented, comes in very handy 👍

**Comment by AlexAndBear** [comment]
Since save as in Only Office will just be implemented with version 8.1, the focus of that ticket is for our packaged editors not for external apps.

**Comment by AlexAndBear** [comment]
OO 8.1.3 has been released, save as copy works fine without any interaction needed in web
