### ISSUE TITLE
No more thumbnail for ggs files

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#11576]
## Describe the bug
ownCloud Web UI 10.2.0 is not doing thumbnail requests for ggs files.

## Steps to reproduce
1. use eg. https://ocis.ocis.rolling.owncloud.works/
2. upload a ggs file

## Expected behavior
See a thumbnail as it's the case with earlier versions of oCIS / Web

## Actual behavior
No thumbnail is shown

**Comment by AlexAndBear** [comment]
What exactly is a ggs file? Could You provide an example file and/or a mime type ?

**Comment by kulmann** [comment]
> What exactly is a ggs file? Could You provide an example file and/or a mime type ?

See https://github.com/owncloud/ocis/issues/7768 - the issue includes an example file. We're talking about Geogebra slides files... you can build your own file here https://tafel.mebis.bycs.de and download it as .ggs file in the left hand expandable menu.
