### ISSUE TITLE
Comments in sidebar

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#1158]
## Description:
Add comments panel into the Phoenix sidebar

## Open tasks:
- [ ] Requirements
- [ ] Acceptance tests
- [ ] Mockups
- [ ] Implement in Phoenix

**Comment by felixboehm** [comment]
Was asked about priority. Can be postponed for some weeks, if you want to focus on other user functionality first.

**Comment by PVince81** [comment]
I recently stumbled upon UIKit's "Comment" elements, which we could use: https://getuikit.com/docs/comment

**Comment by fschade** [comment]
@tbsbdr is this planned, if not please close the issue.

**Comment by JanAckermann** [comment]
AFAIK not in planning, please re-open if so
