### ISSUE TITLE
Media viewer

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#1159]
## Description:
port the OC 10 app to Phoenix

## Open tasks:
- [x] Port to Phoenix
- [ ] Preview APIs

**Comment by micbar** [comment]
Fixes https://github.com/owncloud/files_mediaviewer/issues/80

**Comment by DeepDiver1975** [comment]
refs #1530

**Comment by LukasHirt** [comment]
@DeepDiver1975 @felixheidecke Can be closed? Let's leave video/audio to upcoming milestones?

**Comment by PVince81** [comment]
raised https://github.com/owncloud/phoenix/issues/2051 for missing video playback

**Comment by PVince81** [comment]
more missing stuff:
- preloading: https://github.com/owncloud/phoenix/issues/2052
- swiping (mobile friendliness): https://github.com/owncloud/phoenix/issues/2053

**Comment by PVince81** [comment]
Reopening

**Comment by PVince81** [comment]
- [ ] zoom in/out buttons: https://github.com/owncloud/phoenix/issues/2054

**Comment by pascalwengerter** [comment]
Closing this since all the mentioned/missing features are documented in dedicated tickets
