### ISSUE TITLE
[keycloak] Add test coverage for importing group from keycloak

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#11605]
## Describe
oCIS now supports importing groups from keycloak https://github.com/owncloud/ocis/issues/5538

## Tests coverage 
- add api request to create group at keycloak and sync group to oCIS

## Point to Note
- docker image should be `ocis-7.0.0-rc.1` or rolling

**Comment by amrita-shrestha** [comment]
It seems on oCIS with keycloak setup, group will sync to ocis-web only when group assigned user login on ocis-web. 

## ocis feature 
 We only get to know the new group membership when the user logs in (via the claims submitted in the accesstoken or in the userinfo). There is not active sync between the IDP and ocis going on.

## Finding
to sync a group on oCIS, we have to log in group assigned user first which seems off-the-track with our current web e2e test plan until there is active sync feature support on oCIS we can't do much. Either we have to make a separate test suite to test keycloak-group 

cc @saw-jan @ScharfViktor do we want to add separate test suite for keycloak-group ?

**Comment by ScharfViktor** [comment]
> cc @saw-jan @ScharfViktor do we want to add separate test suite for keycloak-group ?

yes, for such cases, I would create a separate test suite and exclude it in ocis ci and in web ci ( usual tests).

**Comment by saw-jan** [comment]
By the looks of this, it seems that we have to do workarounds in existing groups related tests to them run with keycloak.
 
>>cc @saw-jan @ScharfViktor do we want to add separate test suite for keycloak-group ?
>
>yes, for such cases, I would create a separate test suite and exclude it in ocis ci and in web ci ( usual tests).

Yeah, would be good to have minimal group test scenario only for keycloak.

**Comment by amrita-shrestha** [comment]
The approach to create a group using keycloak API has been dropped (demo PR- https://github.com/owncloud/web/pull/11876 )due to the oCIS 5-minute synchronization time as a detailed explanation is provided on https://owncloud.dev/services/proxy/#claim-updates

**Comment by amrita-shrestha** [comment]
https://github.com/owncloud/web/pull/11887 PR has been merged so closing this issue
