### ISSUE TITLE
[Playwright] Problem with playwright trace

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#11648]
## Describe the bug
Traces generated when test scenarios fail on retry should give the proper file name. 
Build : https://drone.owncloud.com/owncloud/web/47874/14/16
Due to some reason trace file named as `*.zip`.   Recent changes done on this PR https://github.com/owncloud/web/pull/11640
```
npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/47874/tracing/\*.zip
```

![Screenshot from 2024-09-25 13-13-03](https://github.com/user-attachments/assets/4982c6d5-07bd-422c-8a90-bb1df9dee264)

**Comment by amrita-shrestha** [comment]
Finding 
Failed because trace build on retry stored on different location 
![image](https://github.com/user-attachments/assets/f603ccc0-9671-4534-bfbf-e997e2af6846)

**Comment by saw-jan** [comment]
> Failed because trace build on retry stored on different location changes done on this PR bring that changes https://github.com/owncloud/web/pull/11640

storing tracing reports in different location is expected. But the problem here is that the reportTracing config changes to false and the moving of failed tracing reports to the actual folder doesn't occur.

**Comment by saw-jan** [comment]
I will fix this in PR https://github.com/owncloud/web/pull/11659 if your PR is not ready

**Comment by saw-jan** [comment]
The problem was not in PR #11640 but in the first PR #11571 where I tried to collect only the reports of failing tests. In the PR, the reports were not filtered correctly
