### ISSUE TITLE
Support view mode selection on the external apps page

### ISSUE THREAD

**Issue by micbar** [owncloud/web#11667]
# Description

When i open an external app URL like

`https://ocis.owncloud.test/external-onlyoffice/personal/admin/New%20file.docx?fileId=d3519f5d-f36c-4aa6-9801-8ae0ff82599b%2414467625-be3a-4ad2-ad86-6453a4da89b3%213f05f6e4-f911-440e-be18-d01fe20471b3&view_mode=view`

i want to select the view mode via url parameter.

## Current Behavior

![web-view-mode](https://github.com/user-attachments/assets/cd253420-8ff9-4115-80b9-d6d820f92ace)

## User Stories

* > As a webOffice user, i want to choose my edit mode to avoid unwanted changes

## Value

Better WebOffice Integration

## Acceptance Criteria

- [ ] url param changes the view mode on the app-external page 
- [ ] if no param is selected, use the resource permissions 

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by micbar** [comment]
@AlexAndBear Thank you for helping today. This is the ticket.

**Comment by AlexAndBear** [comment]
@micbar you are always welcome, this should do the trick https://github.com/owncloud/web/pull/11668
