### ISSUE TITLE
Recipient with the editor role cannot add/remove shared resource tags on the search results page

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11681]
use https://ocis.ocis-web.master.owncloud.works/
```
ocis | 6.4.0
web 10.3.0
```

Steps: 
- admin creates space `s1` and folder `f1` inside the space
- admin adds `tag1` and `tag2` to folder `f1`
- admin shares folder `f1` to einstein with edit permission
- einstein opens search result and finds folder by tag `tag1`
- einstein opens details of finded folder and tries to add new tag or delete existing tag

Expected: einstein can add/delete tags in the search result page
Actual: not possible to add/delete tags

https://github.com/user-attachments/assets/e0059fd4-cb7e-4d89-9c2f-7478a7f06e57

**Comment by JammingBen** [comment]
This is actually a server issue, I created https://github.com/owncloud/ocis/issues/10214. Fixing it in the server will fix it in Web as well, hence closing here.
