### ISSUE TITLE
Cannot build 10.2 or 10.3

### ISSUE THREAD

**Issue by pascuflow** [owncloud/web#11694]
## Describe the bug
Trying to build Web 10.3 but get a rollup failed to resolve import error, 10.1 works fine. 

## Steps to reproduce
1. Checkout 10.2 or 10.3
2. pnpm install
3. pnpm build

## Expected behavior
The build finishes

## Actual behavior
```
 Rollup failed to resolve import "@ownclouders/design-system/src/composables" from "/web/packages/web-pkg/src/components/FilesList/ResourceTile.vue?vue&type=script&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

**Comment by pascalwengerter** [comment]
Could you share your node and pnpm version @pascuflow ?

**Comment by pascuflow** [comment]
Node 21.6
Pnpm 8.9.2

**Comment by kulmann** [comment]
> Node 21.6.1 Pnpm 8.9.2

Please try with pnpm v9.

If you use pnpm via corepack our nice little project will always be built with the pnpm version defined in our package.json, see https://github.com/owncloud/web/blob/7088fbe353f565fd94ddc5f7ab8218aa9a0c3c87/package.json#L95 🤓 
See https://pnpm.io/installation#using-corepack
