### ISSUE TITLE
Publish current version of eslint-config

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#11743]
We should publish the current version of `@ownclouders/eslint-config` since it includes the `eslint` update  to `v9`. Then we can update the linters in all apps.

To-Dos in the course of this:
* use a version range for the `typescript` dependency
* specify some ignore patterns: `{ ignores: ['**/node_modules/', '.git/', '**/dist/'] }`

@kulmann What version schema do you think makes sense here? Also couple it to the main Web releases like `web-pkg` etc.?

**Comment by kulmann** [comment]
Is the `jest` config already gone?

**Comment by kulmann** [comment]
> @kulmann What version schema do you think makes sense here? Also couple it to the main Web releases like `web-pkg` etc.?

I can't think of anything more useful, so let's go with that.

**Comment by JammingBen** [comment]
> Is the `jest` config already gone?

Yes, this has been removed quite a while ago.
