### ISSUE TITLE
Support Only Office template files 

### ISSUE THREAD

**Issue by AlexAndBear** [owncloud/web#11750]
# Description
Subset of https://github.com/owncloud/ocis/issues/9785

Context 
https://github.com/owncloud/ocis/pull/10276

## User Stories

As a user I want to create editable office files via templates 

## Value
Creating multiple files with the same template

## Acceptance Criteria

- [ ] Web Client reads the target_ext field from the app/list response.
- [ ] Files with that flag will trigger a new default action, which is "Create file from template"
  - [ ] New extension within the `external` app
  - [ ] Needs to be registered for the default (left click) and context (right click) extension points
  - [ ] Left click should take priority over viewing/editing the template file
  - [ ] if the authenticated user has no personal space, the action is not available
  - [ ] flow when action is triggered:
    - [ ] Show input modal for new file name (use the `target_ext` field for the file extension)
    - [ ] File is to be placed in the root of the personal space, file name collisions need to be handled client side (propfind to personal space needed)
    - [ ] Create new file by calling the `app/new` endpoint (same as if the `+ New` menu had been used)
    - [ ] Open the newly created file (`app/open` endpoint), but add the fileId of the template as `template_id` to the `app/open` request
    - [ ] Use the `loadingService` to visualize that there are things happening in the background (until the new document gets opened)
- [ ] The existing file action "Open this File in ..." will stay and can be used via right click.

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
  - [ ] e2e test for the happy path of this feature, with a `dotx` to `docx` conversion
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by tbsbdr** [comment]
template testing files (word, excel, powerpoint) for a start:
[Archive.zip](https://github.com/user-attachments/files/17376590/Archive.zip)

**Comment by micbar** [comment]
Backend has been merged.
