### ISSUE TITLE
[FR] How to configure the App Order

### ISSUE THREAD

**Issue by dj4oC** [owncloud/web#11847]
As a User, I want to be able to define the order of the Apps in the "+ New" Button Menu.

![image](https://github.com/user-attachments/assets/27ca4d95-9bde-45e4-aa5f-261e966819b5)

Is this feature available?

\cc @wkloucek

**Comment by kulmann** [comment]
Sorting is not available. Not possible to implement it for oCIS 7.0 as it would be an enhancement.

**Comment by kulmann** [comment]
With `As a User`, do you have an Admin in mind or really that regular users should be able to configure this for them individually?
I see this as an admin config option, not as a user customization option.

**Comment by dj4oC** [comment]
Yes, User = Admin

**Comment by kulmann** [comment]
Right now it's not sorted, so some kind of sorting would make sense. E.g. by displayname of the file type or by the file extension. Really letting the admin decide usually adds unnecessary complexity in the code base, is hard to document and is typically something that needs support.

You're the first I hear you ask about the order of the items, so I'd like to hear very specific answers to:
- What's the goal you're trying to achieve?
- What's the value for the user?
- Can the same or similar value achieved by "dictating" an order via code?

**Comment by dj4oC** [comment]
- the user has shorter mouse paths to the mostly used apps
- new apps can be presented prominent
- apps can be sorted logically e.g. ggp + ggs behind each other and word + forms too. they kind of are connected from a user standpoint.

**Comment by AlexAndBear** [comment]
We can reorganize them, but I don't see users or admins configuring their own menus. Waste of time Ihmo

**Comment by kulmann** [comment]
Is this wishful thinking or by customer request?

Like Alex said, we can reorganize them. Making it configurable won't happen. Not important enough and like I stated before, creates too much initial effort (think of docs, handbook, useful concept for configuration with respect to extensions, maintenance for the future, ...

**Comment by kulmann** [comment]
If this is by customer request please open a new issue in the enterprise repo, stating the prio, deadline and ARR.
From a product point of view this is not planned.
