### ISSUE TITLE
Uncomment and adjust ocm test steps after issue is fixed

### ISSUE THREAD

**Issue by SagarGi** [owncloud/web#11866]
### Description
An issue related to OCM https://github.com/owncloud/ocis/issues/10272 has been fixed. And We have some steps in OCM feature test where we have commented those steps https://github.com/owncloud/web/blob/e9cababf79f6d8d19ace5c3f0f7cb7d8ea49eb4a/tests/e2e/cucumber/features/ocm/ocm.feature#L52 due to the above issue. Since the above issue has been fixed and closed. 

TODO:
- [ ] Uncomment those tests steps and adjust the test

**Comment by amrita-shrestha** [comment]
seems wrong issue has been pinged on this comment 
```
      # should be work after fixing https://github.com/owncloud/ocis/issues/11821
      # | sampleGif.gif  | file   |
      # | testavatar.jpg | file   |
```

**Comment by ScharfViktor** [comment]
closed in favor https://github.com/owncloud/web/pull/11884
