### ISSUE TITLE
User can see hidden files in the preview app on Shared with me page

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11883]
ocis 7.0.0-rc.1+22d80256d
web 11.0.2

Steps: 
- `admin` shares folder image files to `einstein`
- `einstein` opens one image file in preview app and tries to scroll through all the images of the shares jail

Expected: `einstein` can scroll through all the images of the shares jail
Actual: 

https://github.com/user-attachments/assets/9d3e1427-c358-4e87-8ca9-8a796cf60086

## another strange thing: 

- admin share folder `f1` with two image files
- `einstein` opens first image file

Actual:  he cannot scroll through two images

- `einstein` opens second image file

Actual:  he can scroll through two images

https://github.com/user-attachments/assets/8a11a931-3b3b-4ee9-8b8f-45fc165a5f9b

**Comment by ScharfViktor** [comment]
I can confirm that it's work but I noticed several another problem: 


1. user cannot open concrete image
Steps: 
- admin shares several image files to einstein
- einstein opens Shares with me page and tries to open second (or last image)

Actual: 
first image opens

https://github.com/user-attachments/assets/0e25c307-a363-468f-87b5-829d525f014e



2. hidden files in the preview app
- einstein hiddes shared file
- einstein opens preview app

Actual: hidden file is in the app


3. secure view files in the preview app
- admin shares image file with secure view role to einstein
- einstein opens any image file in the preview app

Actual: secure view files in the preview app

**Comment by JammingBen** [comment]
I fixed issues 1. & 3, via https://github.com/owncloud/web/pull/11947.

Issue 2 is a known issue for now, respecting the filters would take much more effort.

**Comment by ScharfViktor** [comment]
can confirm that 1. & 3 are fixed
I renamed issue name to case 2
