### ISSUE TITLE
Inconsistency/bug in show details for a space (personal vs project)

### ISSUE THREAD

**Issue by mmattel** [owncloud/web#11911]
Running rolling 6.6.1

At the moment, there is no direct access showing details for a personal space compared to project space.

To get details for a project space, you just click the three dots and select `Details`.
A similar access for a personal space is missing.

This is relevant for example when enabling show `WebDav URL` in personal settings to get the space ID.

To get personal spaces details, you currently must show the details of a project space - if exists - and then directly click on the personal space selector. If there is no project space, there is no way to get the personal space details.

Imho this is a bug that should be fixed.

**Comment by JammingBen** [comment]
> If there is no project space, there is no way to get the personal space details.

That's not quite true, you can always go to your personal space and simply open the right sidebar via the button on the top right (it even says "Open sidebar to view details"). Because of that, and because we don't have an overview like for all the project spaces, I consider this a won't do, sorry.

**Comment by mmattel** [comment]
ok, thanks. makes sense 👍
