### ISSUE TITLE
[QA] download chromium in Ci only after updating playwright

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11921]
I noticed that we download chromium every pipeline which is unnecessary and inefficient.

<img width="826" alt="Screenshot 2024-11-18 at 10 36 15" src="https://github.com/user-attachments/assets/2f87fc08-5e24-4a51-8657-4f3efa0b5cce">

https://playwright.dev/docs/browsers#chromium  

chromium update comes out quite often, but playwright uses the latest stable versions of browsers in its update, so if we don't update playwright for a long time we are using an old browser. 

So we need to: 
- [ ] automatically check for playwright updates and update playwright to use the fresh browser version
- [ ] download Chromium to CI ONLY after playwright has been updated.

cc @saw-jan

**Comment by ScharfViktor** [comment]
in the ocisCI we don't install chromium because owncloudci/nodejs:20 has chrome https://github.com/owncloud-ci/nodejs/blob/1f6b1263a5439e1954281a910d5a613048d64911/v20/Dockerfile.amd64#L29 and e2e tests use this chrome

**Comment by pascalwengerter** [comment]
> in the ocisCI we don't install chromium because owncloudci/nodejs:20 has chrome https://github.com/owncloud-ci/nodejs/blob/1f6b1263a5439e1954281a910d5a613048d64911/v20/Dockerfile.amd64#L29 and e2e tests use this chrome

Came here to point this out 🙌🏽

**Comment by ScharfViktor** [comment]
> * [ ]  automatically check for playwright updates and update playwright to use the fresh browser version

this is half done
@saw-jan bot renovate periodically checks and updates playwright. here is example https://github.com/owncloud/web/pull/11802

**Comment by amrita-shrestha** [comment]
### Remaining Task:
- [ ] download Chromium to CI ONLY after playwright has been updated. 

Currently, the **owncloudci-nodejs** image ([owncloud-ci/nodejs](https://github.com/owncloud-ci/nodejs/blob/1f6b1263a5439e1954281a910d5a613048d64911/v20/Dockerfile.amd64#L30C1-L30C66)) installs the **google-chrome-stable_current_amd64.deb** package, which is used in the end-to-end (e2e) testing pipeline.
However, only the **design-system-build-and-tests** pipeline uses the **Playwright Chromium**, which gets cached during each build via the **playwright-install** step-piepline (part of the **cache-pnpm** pipeline).

Goal:
- Cache Playwright Chromium once and store it in a long-term cache.
- Check if the cached Chromium version is outdated. If it is, update the cache with the latest Chromium version or re-cache it if it’s deleted or missing.

## Solution
- Implement a bash script that:
  -  check the cached Chromium version, compare it with the latest version 
  -  Updates the cache with the latest version if the existing one is outdated or missing
     -  Note: The cache has a defined lifespan, and if the version is not updated within this lifespan, the cache will be deleted automatically.

@saw-jan @ScharfViktor does this approach align with your expectations?

**Comment by ScharfViktor** [comment]
> @saw-jan @ScharfViktor does this approach align with your expectations? 
 
 yes, correct
 
  >   * check the cached Chromium version, compare it with the latest version

A small nuance: we need no latest chromium, but the one that supports installed playwright version
https://playwright.dev/docs/release-notes#browser-versions if we use Playwright 1.49 -> we need chromium 131.0.6778.33

**Comment by amrita-shrestha** [comment]
I have created a feature request issue for a way to retrieve the browser version corresponding to the Playwright version: https://github.com/microsoft/playwright/issues/33726.

It appears that there is currently no direct method to get the browser version, which is necessary for comparing the Chromium version against the cache. The proposed approach is as follows:

- Cache the Chromium binary and associate it with the Playwright version.
- Check whether the Playwright version has changed. If it has, update the cached Chromium binary to match the new Playwright version.
While a change in the Playwright version does not necessarily imply a change in the browser version, we must account for it since there is no available way to directly determine the browser version.

**Comment by ScharfViktor** [comment]
>   While a change in the Playwright version does not necessarily imply a change in the browser version, we must account for it since there is no available way to directly determine the browser version.

Usually chromium is updated while playwright is updated, so yeah, let's check playwright version. if it's updated -> install the new chromium and cache it.

**Comment by saw-jan** [comment]
> in the ocisCI we don't install chromium because owncloudci/nodejs:20 has chrome https://github.com/owncloud-ci/nodejs/blob/1f6b1263a5439e1954281a910d5a613048d64911/v20/Dockerfile.amd64#L29 and e2e tests use this chrome

this is same for the web e2e pipelines.
The question would be should we use `chromium` for e2e tests in web instead of `chrome`?
https://playwright.dev/docs/browsers#when-to-use-google-chrome--microsoft-edge-and-when-not-to
CC  @ScharfViktor

**Comment by amrita-shrestha** [comment]
can't use cached chromium in **design-system-build-and-tests** pipeline because test step-pipeline missing test execution script
as mentioned in this issue https://github.com/owncloud/web/issues/11971

**Comment by saw-jan** [comment]
>- if we want to update playwright in a timely manner - we can use here (in web repo) fresh chromium (it gives peace of mind that the upcoming Google Chrome or Microsoft Edge releases won't break your site) and use chrome in ocis repo (like a regression testing with old browser)

yeah, second one sounds good.
