### ISSUE TITLE
x-request-id identic while uploading and (batch) deleting files

### ISSUE THREAD

**Issue by butonic** [owncloud/web#11925]
When checking the logs I see multiple delete requests with the sambe request id `78df25d3-da57-4afc-b0fa-1b879a059783`: 

```json
2024-11-18 17:00:58.335	
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"78df25d3-da57-4afc-b0fa-1b879a059783","traceid":"c832d180391a7de3aecf1aa74baedfbb","remote-addr":"77.21.27.45","method":"DELETE","status":204,"path":"/remote.php/dav/spaces/52a78aa9-aba0-4403-a5d5-421cb51766ea$16a17b88-aff0-4a8d-89f2-a1e34f25d6a3/1000_4k/f18.bin","duration":575.723237,"bytes":0,"time":"2024-11-18t16:00:58Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
	
	
2024-11-18 17:00:57.662	
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"78df25d3-da57-4afc-b0fa-1b879a059783","traceid":"9790231858154f715b03a3f1b56fc912","remote-addr":"77.21.27.45","method":"DELETE","status":204,"path":"/remote.php/dav/spaces/52a78aa9-aba0-4403-a5d5-421cb51766ea$16a17b88-aff0-4a8d-89f2-a1e34f25d6a3/1000_4k/f11.bin","duration":623.722751,"bytes":0,"time":"2024-11-18t16:00:57Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
	
	
2024-11-18 17:00:56.479	
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"78df25d3-da57-4afc-b0fa-1b879a059783","traceid":"5de615cf1ae22214bd6f79cd071e4d40","remote-addr":"77.21.27.45","method":"DELETE","status":502,"path":"/remote.php/dav/spaces/52a78aa9-aba0-4403-a5d5-421cb51766ea$16a17b88-aff0-4a8d-89f2-a1e34f25d6a3/1000_4k/f15.bin","duration":30018.324353,"bytes":0,"time":"2024-11-18t16:00:56Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
	
	
2024-11-18 17:00:26.421	
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"78df25d3-da57-4afc-b0fa-1b879a059783","traceid":"853aa3dc79b34e9c448ae4b9007e6966","remote-addr":"77.21.27.45","method":"DELETE","status":204,"path":"/remote.php/dav/spaces/52a78aa9-aba0-4403-a5d5-421cb51766ea$16a17b88-aff0-4a8d-89f2-a1e34f25d6a3/1000_4k/f13.bin","duration":674.282122,"bytes":0,"time":"2024-11-18t16:00:26Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
	
	
2024-11-18 17:00:25.503	
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"78df25d3-da57-4afc-b0fa-1b879a059783","traceid":"4fde1d099e1ff0dcd6e612cba7648a6e","remote-addr":"77.21.27.45","method":"DELETE","status":502,"path":"/remote.php/dav/spaces/52a78aa9-aba0-4403-a5d5-421cb51766ea$16a17b88-aff0-4a8d-89f2-a1e34f25d6a3/1000_4k/f1.bin","duration":30105.127429,"bytes":0,"time":"2024-11-18t16:00:25Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
```

I was selecting multiple files in a folder and then hitting delete.

cc @micbar mentioned that he also sew this with upload requests.

**Comment by micbar** [comment]
# Easy Reproducer

Upload 10 files at once, all uploads get the same Request ID

**Comment by butonic** [comment]
hm .... DELETE requests still seem to reuse the id https://github.com/owncloud/enterprise/issues/6987#issuecomment-2493106248

**Comment by JammingBen** [comment]
I can't reproduce it, can somebody else verify this in a browser by inspecting the network tab? And make sure it's Web version 11.0.4?

**Comment by jnweiger** [comment]
with web 11.0.4 and 7.0.0-rc.3:
go to a folder with 500 small pictures, select all, delete, go to trashbin, select all, delete.


In firefox/132.0 the network tab shows different X-Request-ID for each DELETE.

Sometimes (not reproducable) the webUI shows **many** error notifications. But all files are gone, and are in the trashbin:
![image](https://github.com/user-attachments/assets/d4fbd445-0545-4242-8057-38510a787ebf)
----

Deleting files from the trashbin logs this error for each selected file. But the delete works fine.
```
Nov 22 10:07:30 jw-ocis-v7-0-0-rc-3-30k ocis[9254]: {"level":"error","service":"activitylog","error":"resource id is required","event":{"Type":"events.ItemPurged","ID":"739440ca-a961-4315-8cbf-ebc9e617ff9b","TraceParent":"00-c027912e65cb2057340ce4313ea82583-ad7cbba3ba745804-00","InitiatorID":"2819aaed-6099-4c82-a357-b2c147bf0293","Event":{"Executant":{"idp":"https://dog-7rc3-20241121.jw-qa.owncloud.works","opaque_id":"fe12ee7b-c62f-4bb6-a488-6e7cb46630b5","type":1},"ID":null,"Ref":{"resource_id":{"storage_id":"ceca6deb-3224-44e3-922c-a45b7359eb6a","opaque_id":"fe12ee7b-c62f-4bb6-a488-6e7cb46630b5","space_id":"fe12ee7b-c62f-4bb6-a488-6e7cb46630b5"},"path":"."},"Owner":null,"Timestamp":{"seconds":1732270050,"nanos":95367188},"ImpersonatingUser":null}},"time":"2024-11-22T10:07:30Z","line":"github.com/owncloud/ocis/v2/services/activitylog/pkg/service/service.go:143","message":"could not process event"}
```

When not selecting files, but using the "Empty trash bin" button, this error is only logged once.

**Comment by JammingBen** [comment]
> Sometimes (not reproducible) the webUI shows many error notifications. But all files are gone, and are in the trash bin:

Any console logs during that? And what does the server return for these (presumably failed) requests? It's strange that the request ids seems to be missing... 🤔

**Comment by jnweiger** [comment]
Hmm, cannot reproduce.. sorry. 
The only error that occurred in the browser console is this, but that seems unrelated to deleting:

![image](https://github.com/user-attachments/assets/966bbfa2-8e24-495b-a9a8-036a86399753)

**Comment by jnweiger** [comment]
Got it:

![image](https://github.com/user-attachments/assets/7c641ac8-e8db-42d7-9622-b39f28fb0d05)

**Comment by AlexAndBear** [comment]
In packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts:L204 we actually hand over `new Error()` to the `showErrorMessage` method, this is why, we cant extract any x-request-id

**Comment by JammingBen** [comment]
> In `packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts:L204` we actually hand over `new Error()` to the `showErrorMessage` method, this is why, we cant extract any x-request-id

True 🤦 Yeah, so there's that...

The error itself is more concerning though. I tried several times locally, but can't reproduce that. @jnweiger Any chance you had a look at the network tab? Did these requests fail on the server side?
