### ISSUE TITLE
The userName, the userID and current bearer token should be listed in the users preferences

### ISSUE THREAD

**Issue by mmattel** [owncloud/web#11939]
## Is your feature request related to a problem? Please describe.
We need for a couple of CLI ommands the internal userName (not the display name), the userID (the uuid string) and the current bearer token (for authentication).

## Describe the solution you'd like
The userName, the userID and current bearer token should be listed in the users preferences

## Describe alternatives you've considered
The userID and current bearer token can be queried via complex CLI methods. No knowledge about how to get the UserName.

## Additional context
For example,
* The auth-app, which generates tokens for 3 party apps, needs all three
* Some CLI commands need an active bearer token to authenticate the request.

Independent if which webUI methods will there be in the future, we need to add these infos now. It does no harm and and helps any admin.

@micbar @kobergj fyi

**Comment by AlexAndBear** [comment]
No way, we will expose the bearer token

**Comment by micbar** [comment]
@mmattel these info is neither user nor admin facing. So we keep it secret.

**Comment by mmattel** [comment]
The infos are necessary for a bunch of cli commands.
It can be gathered via the browser anyways - so nothing "secret" ( ?? 🤔 )
Without presenting via the webui, an admin needs to go an unnecessarily longer path to get it.
Just imagine, an admin now needs to do screensharing and does the full stuff manually.
Imho, there is no rational declining this...
Just my 2c

**Comment by AlexAndBear** [comment]
Easy attacking vector. Won't happen
