### ISSUE TITLE
run UI tests in Firefox

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#1197]

**Comment by DeepDiver1975** [comment]
moved to backlog - we need to come back in a few weeks/months ....

**Comment by pascalwengerter** [comment]
@fschade posted this in the chat already but to document it here as well: https://github.com/microsoft/playwright could be an awesome solution!

**Comment by individual-it** [comment]
Wouldn't that mean to rewrite all UI acceptance tests to port them from nightwatch to playwright?

We could also try (again) to create a pipeline that executes selenium with FF and runs the current tests there

**Comment by pascalwengerter** [comment]
> Wouldn't that mean to rewrite all UI acceptance tests to port them from nightwatch to playwright?
> 
> We could also try (again) to create a pipeline that executes selenium with FF and runs the current tests there

We'd have to at least restructure them, discussed this with @fschade but definitely not pressing at the moment. Just wanted to document the possibility above for documentation reasons :)

**Comment by fschade** [comment]
should already work with https://hub.docker.com/r/selenium/standalone-firefox/ and https://github.com/owncloud/web/tree/acceptance-tests-docker. need to try that out and hopefully find time to finalize the pr

**Comment by pascalwengerter** [comment]
It's possible by running the playwright smoke tests with `BROWSER=firefox`, and since we'll focus on them in the near future I'll close this one
