### ISSUE TITLE
[CI] Pipeline `design-system-build-and-tests` missing test execution script

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#11971]
## Describe the bug
In the Drone pipeline **design-system-build-and-tests**, no tests are being executed. It seems the script was removed in the past. If this was intentional, why does the pipeline still exist?
**design-system-build-and-tests** pipeline introduced in this PR https://github.com/owncloud/web/pull/10374

## Drone Error
```
+ pnpm --filter @ownclouders/design-system test:e2e
None of the selected packages has a "test:e2e" script
```

![Screenshot from 2024-11-27 12-18-40](https://github.com/user-attachments/assets/5c054777-2dda-446f-aa5e-031dff70ca50)

cc @JammingBen @kulmann @LukasHirt

**Comment by JammingBen** [comment]
This CI step is to make sure the design-system successfully builds. In the future me might add a step to publish it to https://owncloud.design. However, there are no specific e2e or unit tests, so this step can be removed.

**Comment by saw-jan** [comment]
what about these tests? get rid of them?
https://github.com/owncloud/web/tree/master/packages/design-system/tests/e2e/specs

**Comment by JammingBen** [comment]
Huh, I didn't even know they existed. I'd say yes - we don't really need tests for the docs part of the design system, especially not e2e tests.

**Comment by saw-jan** [comment]
It was added in https://github.com/owncloud/web/pull/10374

**Comment by JammingBen** [comment]
> It was added in #10374

Ah, now I remember. Still, I stand by what I said, there's no need for e2e tests as of now.

**Comment by saw-jan** [comment]
okey, got it

**Comment by saw-jan** [comment]
> Huh, I didn't even know they existed. I'd say yes - we don't really need tests for the docs part of the design system, especially not e2e tests.

CC @amrita-shrestha
