### ISSUE TITLE
ocm. user cannot change share role

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11991]
Version	7.0.0-rc.1+22d80256d6
Web client version	11.0.2

setup: https://owncloud.dev/ocis/development/testing/#running-test-suite-with-federated-sharing-ocm

Steps: 

- 2 users create connection
- `user1` creates folder `f2` shares to `user2` with edit role
- `user1` tries to change share role to view

Actual: `user1` sees that role was changed but role was not changed for `user2` -> he can edit
PROPFIND response body for shared folder doesn't change permissions- > still `DNVCK` so web doesn't disable buttons

when `user2` tries to create new or edit existing resources -> 500 

cc @rhafer

**Comment by rhafer** [comment]
@JammingBen This is the one we just mentioned

**Comment by JammingBen** [comment]
As discussed: The solution is to prevent editing of OCM shares - they can only be created and deleted.

**Comment by saw-jan** [comment]
updating from sharer side was fixed in https://github.com/owncloud/ocis/pull/9980

**Comment by rhafer** [comment]
> updating from sharer side was fixed in [owncloud/ocis#9980](https://github.com/owncloud/ocis/pull/9980)

Yes the update on the sharer side works, but that is barely half of what is needed. The share update is not forwarded to the sharee's side, because the http protocol currently lacks an UpdateShare call. (AFAICS it's not part of the spec).
