### ISSUE TITLE
[IE11-QA] Special characters in file/folder name

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/web#1234]
Steps to recreate:
1) Click + New button
2) Select Create new folder 
3) Enter *
4) Click OK

Actual result: 'File name is a reserved word' message
Expected result: 'Folder name cannot contain  *' message

There is already a message 'Folder name cannot contain  /'
The same applies to file creation. The message has to correctly state if it is file or folder.

![image](https://user-images.githubusercontent.com/49001702/58943965-1dae3d80-8781-11e9-957d-4f2df91883b6.png)

**Comment by HanaGemela** [comment]
When renaming a file/folder to a *, nothing happens. No message but file name is not changed

**Comment by jnweiger** [comment]
According to 
https://docs.microsoft.com/en-gb/windows/desktop/FileIO/naming-a-file this is a list of invalid file characters on Windows 10:
The following are special characters which cannot be assigned to a directory or file in Windows 10 :

```
< (less than)
> (greater than)
: (colon)
“ (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)

```

I can create a file named : though. It should be forbidden by the same logic that forbids * as a file (or folder :-) ) name.

**Comment by jnweiger** [comment]
There are more reserved words on windows. E.g. this one is especially scary:

![grafik](https://user-images.githubusercontent.com/1108546/58946656-b0051000-8786-11e9-9c98-d15107f7056b.png)

**Comment by DeepDiver1975** [comment]
> Actual result: 'File name is a reserved word' message
> Expected result: 'Folder name cannot contain *' message

most likely a server issue .....

**Comment by DeepDiver1975** [comment]
> According to
> https://docs.microsoft.com/en-gb/windows/desktop/FileIO/naming-a-file this is a list of invalid file characters on Windows 10:

we don't care about reserved words in windows - the server is on linux ;-)

**Comment by HanaGemela** [comment]
File name in webUI differs from file name that gets downloaded 

![image](https://user-images.githubusercontent.com/49001702/58955219-a2a65080-879b-11e9-81d2-bb19393e6778.png)

**Comment by DeepDiver1975** [comment]
> File name in webUI differs from file name that gets downloaded

we are having most likely an escaping issue here - needs analysis ...

**Comment by LukasHirt** [comment]
@DeepDiver1975 Do we have somewhere list of all reserved words / names/characters we don't want to allow in Phoenix? I'd go ahead and add them to the check to throw a proper error.

**Comment by DeepDiver1975** [comment]
reserved works, dis-allowed characters, max path length and max filename length are all server controlled.

some logic is here: https://github.com/owncloud/core/blob/bdfd3899082ade02ae7b3f59f871bfb246dcab8c/lib/private/Files/View.php#L1859

and here https://github.com/owncloud/core/blob/826fd7cabc3580a9569ebb7f9d6d4a3ce74e1ad3/lib/private/Files/Storage/Common.php#L495-L514

**Comment by DeepDiver1975** [comment]
needs reevaluation

**Comment by pascalwengerter** [comment]
Closing this as we're not supporting IE11 anymore
