### ISSUE TITLE
Drag and drop within folders does not work

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#1242]
In old style ownCloud web view it is possible to drag icons of files and folders into other folders. This moves the object to the new location.

In phoenix the icons do not respnd to drag at all.

**Comment by DeepDiver1975** [comment]
Unrelated to IE - not implemented at all yet

**Comment by DeepDiver1975** [comment]
has been implemented with #1350

**Comment by PVince81** [comment]
From the old UI:
- [ ] drag one or multiple files into a folder visible in the web UI
- [ ] drag and drop to breadcrumb

Design-wise the question is whether we want to stick with just drag and drop or whether we want to introduce other ways of moving files.

@michaelstingl @pmaier1

**Comment by michaelstingl** [comment]
> or whether we want to introduce other ways of moving files

Out of scope of this issue. Needs separate issue…

**Comment by pascalwengerter** [comment]
Superseded by #5592, drag&drop of multiple selected items and having breadcrumbs become drag-targets will be tracked in dedicated issues by @tbsbdr
