### ISSUE TITLE
search in favorites / deleted files (trashbin) does search in the global scope

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#1726]
### Steps to reproduce
1. create folders: `deleted` `just a folder`
2. delete the folder `deleted`
3. go to trashbin and search for `deleted`
4. search for `just a folder`

### Expected behaviour
`deleted` folder should be listed in the search
`just a folder` should not be listed in the search

### Actual behaviour
`deleted` folder is not listed in the search
`just a folder` is listed in the search

the RESTORE & DELETE IMMEDIATELY buttons are there and can be clicked without any real effect

similar problem in the favorites

**Comment by LukasHirt** [comment]
Deleted files shouldn't be listed in the search. Also searching globally is the right behaviour. That was discussed already here - https://github.com/owncloud/phoenix/issues/980#issuecomment-483533206 For searching in the current folder only is input in filters - bad solution. A better way to do this needs to be figured out. Seeing still the restore and delete actions is wrong though.

**Comment by DeepDiver1975** [comment]
for the time being we keep the current implementation - search/filtering files will be re-designed in milestone2
