### ISSUE TITLE
a file is not restored from trashbin if files with the same name already exists

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/web#1730]
### Steps to reproduce
1. Create a file eg. ```file.txt```
2. Delete ```file.txt``` and create ```file.txt```
3. Restore ```file.txt```

### Expected behaviour
```file.txt``` should be restored.

### Actual behaviour
```file.txt``` is not restored

**Comment by LukasHirt** [comment]
Hmm, seems like this will need change in the API. You'll probably need to take over here @DeepDiver1975 ?

**Comment by PVince81** [comment]
Like for the files drop feature we could add a "OC-Autorename" header that tells the server that we're ok with it renaming the target if a duplicate exists.

**Comment by fschade** [comment]
@tbsbdr please have a look, i tested it and think it's ok how web handles the case.

* create file foo
* delete file foo
* create file foo
* go to trash and restore foo

then ui shows an error (see screenshot).

alternatively web could show an option in thrashbin 'restore as'... but really not sure if it makes sense.
![Bildschirmfoto 2022-03-24 um 14 56 48](https://user-images.githubusercontent.com/49308105/159932644-98a5a6a5-2e45-47a7-a5ce-1e5e6547d70a.png)

**Comment by JanAckermann** [comment]
Closing as we have a name collision dialog now and everything is working as expected
