### ISSUE TITLE
Hidden file checkbox unchecks after page reload

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/web#1733]
### Steps to reproduce
1. Check the menu to display hidden files.

![hidden](https://user-images.githubusercontent.com/34328907/62692500-7f448f80-b9f0-11e9-9c33-fd2146242020.png)

2. Now reload the page

3. Hidden files checkbox is unchecked
![reload](https://user-images.githubusercontent.com/34328907/62692518-88356100-b9f0-11e9-9e4e-a3b3048cdf93.png)

### Expected behaviour
Hidden files check box must be checked even after page reload

### Actual behaviour
Hidden file checkbox is unchecked after file reload

**Comment by DeepDiver1975** [comment]
Solution:
save filter settings in vuex and make sure it is stored to the local storage

**Comment by PVince81** [comment]
needed for feature parity as we used to save this setting

there should already be an API of some sorts in the OC server where the old setting is saved, we could simply use that ?

**Comment by pascalwengerter** [comment]
Related to an old version of the UI, closing this for now
