### ISSUE TITLE
Trying to rename a view only share doesn't generate any error message

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/web#1748]
### Steps to reproduce
1. Share a file (eg. ```oc.txt```) to user ```user1``` and change his collaborators permission from ```Co-owner``` to ```Viewer```
2. As user ```user1``` try to rename ```oc.txt```. 

   Here, trying to rename a view-only file doesn't generate any error or warning messages like ```permission denied or could not rename "oc.txt" ```

### Expected behaviour
Trying to rename a view-only share should display an error message

### Actual behaviour
Trying to rename a view-only share doesn't display an error message

**Comment by DeepDiver1975** [comment]
Renaming a share is always possible. 

Expected behavior:
- rename is possible (only for the recipient - not the owner)
- no error message shall pop up

**Comment by pascalwengerter** [comment]
Closed this as fixed, we've refactored the permissions checks in the actions so users shouldn't be able to see the "Rename" action anymore if they're not allowed to perform the action
