### ISSUE TITLE
Not possible to rename a file on the favorites page to a name of a file from an other folder

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#1750]
### Steps to reproduce
1. favorite file `folder/file1.txt`
1. favorite file `folder2/file2.txt`
1. navigate to the favorite page
1. try to rename `folder/file1.txt` to `file2.txt`

### Expected behaviour
renaming should be possible, because there is no conflict

### Actual behaviour
renaming is not possible, the UI claims that filename `file2.txt` is taken

**Comment by DeepDiver1975** [comment]
Workaround - disallow renaming - apply this to all other views as well

**Comment by Julian1998** [comment]
temporary solution in https://github.com/owncloud/phoenix/pull/2129

**Comment by PVince81** [comment]
Prepared possible fix with #2318, but will need also to solve https://github.com/owncloud/phoenix/issues/2150 to add a "flat list" mode to ignore conflicts

**Comment by pascalwengerter** [comment]
Can confirm this still happens on https://ocis.ocis-web.latest.owncloud.works

**Comment by tbsbdr** [comment]
Bug, but would consider it a `Prio-3` as this exists ins classic -> assume not many users experienced it until today; + there is a workaround by navigating into the respective folder.
