### ISSUE TITLE
Batch Action Using Mobile Phone

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/web#1763]
### Steps to reproduce
1. Select all files for batch action in files page or trashbin page. Here ```Name```, ```Search```, ```+New``` .... all overlap with each other. Also once all file have been selected for batch action, we can't unselect all file in batch as ```all file selection checkbox``` is overridden by blue colored ```+New``` box as in screenshot below:
![5](https://user-images.githubusercontent.com/34328907/62775016-4bd43480-bac6-11e9-96c6-da193eb84f99.png)

2. If you perform batch action in trashbin page, whole page is filled with success and failure messages
![7](https://user-images.githubusercontent.com/34328907/62775621-e41ee900-bac7-11e9-86ec-e0771c985f70.png)
![6](https://user-images.githubusercontent.com/34328907/62775627-eb45f700-bac7-11e9-9d4d-35d723ca2e73.png)

### Expected behaviour
- It must be possible to batch unselect file after batch selection
- ```Name``` , ```Search``` rows should not overlap with each other while performing batch selection
- Success and failure message should not occupy whole OC screen after batch action

### Actual behaviour
- It is not possible to batch unselect file after batch selection
- ```Name``` , ```Search``` rows  overlap with each other while performing batch selection
- Success and failure messages occupy whole OC screen after batch action

**Comment by Julian1998** [comment]
@PVince81 @LukasHirt What to about the notification messages? It's an uikit thing. Not much we should/can do here... We could just go ahead and hide all status messages on narrow screens. But this can't be an acceptable solution.

**Comment by LukasHirt** [comment]
@Julian1998 We should limit how many of them are displayed on smaller screens. e. g. only 2 of them on mobile devices?

**Comment by Julian1998** [comment]
@LukasHirt This isn't possible via uikit. We have to write sth on our own then.

**Comment by Julian1998** [comment]
@LukasHirt We could group them as well. Means all succesfull notifications can be closed at the same. We could do a "All selected files have been restored successfully" message instead of one for each file

**Comment by LukasHirt** [comment]
> This isn't possible via uikit. We have to write sth on our own then.

Indeed. But we can't limit ourselves with what UIkit can or cannot do.

> We could group them as well.

I'd like that. What do you think @PVince81 @wuenschedesign Would need to be thought through though how to handle then if only some get restored and some fail. But nevertheless the original issue still needs to be taken care of.

**Comment by Julian1998** [comment]
@LukasHirt In my opinion even one message is "spam" as the message blocks the whole width of the screen. 

> Would need to be thought through though how to handle then if only some get restored and some fail.

That's what grouping is for. You can either group all succesfull messages into one group and all failed ones in an other group or just group the succesfull and ignore (don't group) all unsuccesfull messages

**Comment by JammingBen** [comment]
This has been fixed meanwhile.
