### ISSUE TITLE
after accepting a remote share the files-list is not reloaded

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#1774]
### Steps to reproduce
1. accept an incoming remote share

### Expected behaviour
files list should be reloaded to show the new resource immediately like its doe with local shares that need to be accepted

### Actual behaviour
file list is not reloaded, user has to reload the page to see the new resource

**Comment by PVince81** [comment]
in OC 10 this was tricky because we had to have some kind of event and listener that detects that the notification is of a certain type and was dismissed.

**Comment by LukasHirt** [comment]
Yeah, we have the same. There is already implemented refresh for accepting pending share which was done in the same way - not a nice solution.

**Comment by pascalwengerter** [comment]
@kulmann @LukasHirt can one of you check if this has been fixed by #5130, too?
