### ISSUE TITLE
assigning permissions for collaborator share from api/curl is not displayed in the webui

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/web#1853]
### Steps to reproduce
1. From api or curl share a file/folder with a user with any permission (eg, share, create, delete...)
Eg
 ```curl --user hari:admin "http://localhost/core2/ocs/v1.php/apps/files_sharing/api/v1/shares" --data 'path=/folder&shareType=0&shareWith=receiver&permissions=16'```
2. As a sharer check the permission on the shared folder you just shared using the webui
![1](https://user-images.githubusercontent.com/34328907/63844018-1c1e9b00-c9a7-11e9-9b0f-1db3075e2877.png)

### Expected behaviour
Collaborator share permission assigned from api or curl must be maintained by the webui

### Actual behaviour
Api or curl collaborator share permission is not maintained in the webui.
Only all permission i.e. permissions=31 from curl is maintained by the webui
### Curl output
```
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <id>528</id>
  <share_type>0</share_type>
  <uid_owner>hari</uid_owner>
  <displayname_owner>hari</displayname_owner>
  <permissions>16</permissions>
  <stime>1566984723</stime>
  <parent/>
  <expiration/>
  <token/>
  <uid_file_owner>hari</uid_file_owner>
  <displayname_file_owner>hari</displayname_file_owner>
  <path>/folder</path>
  <item_type>folder</item_type>
  <mimetype>httpd/unix-directory</mimetype>
  <storage_id>home::hari</storage_id>
  <storage>4</storage>
  <item_source>2147541846</item_source>
  <file_source>2147541846</file_source>
  <file_parent>2147492189</file_parent>
  <file_target>/folder</file_target>
  <share_with>receiver</share_with>
  <share_with_displayname>receiver</share_with_displayname>
  <share_with_additional_info/>
  <mail_send>0</mail_send>
  <attributes/>
 </data>
</ocs>
```
### Server configuration
**Operating system**:
ubuntu 18.04
**Web server:**
apache
**Updated from an older ownCloud or fresh install:**
fresh install

**Comment by HariBhandari07** [comment]
permissions are maintained in webui if permission read is also passed in combination with other permissions.

**Comment by PVince81** [comment]
this would likely require us to also add a checkbox "can read" that is permanently checked.

or consider such set of permissions invalid and don't display it, or display it as "invalid role" or something.

the only use case where we remove the read permission is for "drop files only" link shares.

not sure what to do with this. we could also prevent setting such combinations of permissions ?

what does the OC 10 UI do in such cases ?

**Comment by JanAckermann** [comment]
Web has predefined roles that can be handled, unfortunately we don't support custom permissions that doesn't match our roles.
