### ISSUE TITLE
Sidebars need better transition

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#1855]
## Motivation
Current transitions are either too harsh for the user or there are no transitions at all.

**Comment by PVince81** [comment]
also related https://github.com/owncloud/phoenix/issues/1905

**Comment by PVince81** [comment]
@LukasHirt still valid or close ?

**Comment by LukasHirt** [comment]
@PVince81 Still valid. E. g. right sidebar still has no animation on opening so it just "jumps" into view.

**Comment by pascalwengerter** [comment]
Closing this since we've introduced a slight animation for the sidebar. Further feedback from @tbsbdr welcome
