### ISSUE TITLE
Use Vue style guide

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#1867]
## Motivation
We are using no style guide for how we code and it's becoming quite a mess (or at least it seems to me like it). If we use some we could make reviewing easier so we know where to look for and don't need to search where the thing we actually want is. And since we are open source I think using official Vue.js style guide would make sense - https://vuejs.org/v2/style-guide/ Of course we don't need to follow every rule there and can adjust it but at least those with priority essential and strongly recommended would be nice to have.

I know it would be a little bit more work in the beginning until we would get used to it but what do you think about it @DeepDiver1975 @felixheidecke @Julian1998 ?

**Comment by felixheidecke** [comment]
@LukasHirt (and the crew) that's a very good idea and I read thru the first few examples and I strongly agree. 👍 

BTW: This is also how a design style-guide works with the do's and don'ts, listing how to use elements and what not to do.

**Comment by Julian1998** [comment]
@LukasHirt I totally agree! But can't we just use the auto linter to do so? Thought there is one that parses the new delta and adapts it according to our style guide before comitting?

**Comment by LukasHirt** [comment]
> But can't we just use the auto linter to do so?

@Julian1998 We can but not for everything. Some rules are already in place and I don't think we will need to touch those. Maybe just add some new ones. But still, there are things we'd need to do on our own (e. g. https://vuejs.org/v2/style-guide/#Prop-definitions-essential)
