### ISSUE TITLE
Confirmation dialogs for deletion of collaborators and links

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#1872]
## Description
If a user deletes collaborator or public link confirmation dialog has to be triggered to ensure he is sure about the delete action and to prevent deletion by accident.

**Comment by PVince81** [comment]
We never had this before, need to discuss whether we want to add this step.

Another approach would be to have the ability to undo the action.

@michaelstingl @pmaier1

**Comment by LukasHirt** [comment]
@PVince81 reference to why this could be helpful - https://github.com/owncloud/phoenix/issues/1833#issuecomment-525781459

**Comment by michaelstingl** [comment]
Adding @wuenschedesign to the discussion…

**Comment by PVince81** [comment]
cc @kulmann

**Comment by pascalwengerter** [comment]
Update: Implemented for (public) links by now on `master`, only collaborator dialogue missing

**Comment by kulmann** [comment]
Both implemented, closing here

<img width="514" alt="Screenshot 2022-08-01 at 10 28 15" src="https://user-images.githubusercontent.com/3532843/182106931-c2551a2b-c471-4cb9-a64d-575733a79d86.png">
<img width="512" alt="Screenshot 2022-08-01 at 10 28 29" src="https://user-images.githubusercontent.com/3532843/182106941-bce966e4-d858-4beb-b118-458e5759a48a.png">
