### ISSUE TITLE
Trips on missing slash in config.json server value with subpath

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#1901]
In my setup I have the following config.json:
```
{
  "server" : "http://localhost/owncloud",
  "theme": "owncloud",
  "version": "0.1.0",
  "auth": {
    "clientId": "xxxxx",
    "url": "http://localhost/owncloud/index.php/apps/oauth2/api/v1/token",
    "authUrl": "http://localhost/owncloud/index.php/apps/oauth2/authorize"
  },
  "apps" : ["files"]
}
```

This is because ownCloud is hosted in a sub-path.
The OAuth authorization fails due to the missing slash as it concatenates it directly with a "ocs/..." URL. Adding a trailing slash works for me.

This issue was encountered also by @VicDeo with the same resolution.

@LukasHirt who has OC directly in the root did not have a slash nor experience issues.

We should decide if we want to auto-add the trailing slash when it's missing, but first need to fully understand why it works with URLs that have no path and not when there's a path.

**Comment by VicDeo** [comment]
I guess it was not spotted before bacause `npm run dev` start the dev server at `localhost:8080` by default :)

**Comment by PVince81** [comment]
README was improved to indicate the need for trailing slash https://github.com/owncloud/phoenix/pull/1920
