### ISSUE TITLE
Fonts / layout too big

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#1902]
On my laptop's screen 1920x1080 with HiDPI and zoom 100%:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/277525/64349375-1fdd9d80-cff7-11e9-94eb-710bb95293a9.png">

Compare this to Github in the same browser and same zoom factor:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/277525/64349400-2f5ce680-cff7-11e9-9d57-2e7f35afac43.png">

I think we should reduce the font size a bit to match what other websites are using.

Currently I need to reduce the zoom factor on my screen to be able to properly appreciate the public link panel or sharing panel. Should we aim to make those panels fit on the screen with such resolution ? (it won't fit on mobile and that's ok)

**Comment by pascalwengerter** [comment]
@marcus-herrmann is this still relevant after the re-design?

**Comment by marcus-herrmann** [comment]
@pascalwengerter No, I think not

**Comment by pascalwengerter** [comment]
Closing this since it's not an accessibility issue and seems okay for now. @tbsbdr please shout if you receive user feedback regarding font sizes (will also be customizable via theming soon btw)
