### ISSUE TITLE
Popup animation too slow

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#1905]
### Steps to reproduce
1. Create a new folder
2. Wait
3. Type
4. Enter
5. Repeat this a bunch of times

### Expected behaviour
Popup should appear faster.

### Actual behaviour
The first time it looks fancy. The next bunch of times it gets annoying as I want to focus on the field to type folder names.

### Version
Phoenix master 2f7b3d781175e63a45291127bb3d2dfc3cfa5153

**Comment by pascalwengerter** [comment]
Can't reproduce, popup appears instantly
