### ISSUE TITLE
Search box + filter losing visual connection to file list when sidebar is open

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#1909]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/277525/64351357-74cee300-cffa-11e9-9df5-9aadc40ef4a3.png">

The search box and filter button have a relationship with the file list, not with the sidebar. Seeing them on the top of the sidebar makes them lose their visual connection to the file list.

Not sure how to improve this one, as putting them more to the left or center might not look good either.

Depending how often we expect people to use the search and filter, we could decide to have a three dot button on the right of the table header and have it produce a dropdown with said fields.

A designer could confirm whether this is more appropriate.
Would require to confirm the assumption that people are not using search as often as we think,  else this would hide it behind an additional click.

### Version
Phoenix master 2f7b3d781175e63a45291127bb3d2dfc3cfa5153

**Comment by LukasHirt** [comment]
The sidebar is now aligned directly under the top bar and buttons are on the left so there's no chance of pushing them anymore.
