### ISSUE TITLE
Private links are missing target view

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#1919]
In ownCloud core when opening a private link a user can be redirected either to "All files", "Deleted files" or "Shared with you" for pending shares.

@pmaier1 @michaelstingl I assume we'll want the same behavior as core in Phoenix.

Phoenix currently doesn't make this distinction and would not work with links to trashed files or links to pending shares. (note that the latter are sent as part of notification contents)

The SDK https://github.com/owncloud/owncloud-sdk/blob/master/src/fileManagement.js#L126 points at a Webdav property "meta-path-for-user" for resolving the original path. We should extend the core Webdav properties "meta-view-for-user" or similar to indicate what view the file is in.

I didn't test the current code but suspect that one might get a 404 on Webdav when accessing the meta endpoint with file id.

@DeepDiver1975 @LukasHirt

**Comment by PVince81** [comment]
Additional thing: we also have an extra URL parameter "details=xxxx" which points at the id of a given tab in the sidebar.

Such links would need to be converted also to the correct Phoenix route.

**Comment by JammingBen** [comment]
This is working by now.
