### ISSUE TITLE
Publish to marketplace

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#1950]
## Description
Upload [0.2.1 version of Phoenix](https://github.com/owncloud/phoenix/releases/tag/0.2.1) into Marketplace so oc users can easily try the current progress out.

**Comment by PVince81** [comment]
Maybe we need to automate this somehow ? Unless there is a risk of having a broken release in there. We could call all releases "tech preview" ?

**Comment by LukasHirt** [comment]
Done https://marketplace.owncloud.com/apps/web
