### ISSUE TITLE
Adjust README section for acceptance tests

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#1959]
When trying to follow, I bumped into many issues.
I managed to resolve them by following a slightly different path.
This ticket is for documenting the actual path.

Raw paste of my notes:

- setup that worked:
	- disable XDebug as it slows down requests a lot
	- use sqlite + tmpfs on the data folder for OC core to make test runs much faster (else the skeleton copy might take ages before each test)
	- disable firewalld! or `firewall-cmd --permanent --zone=trusted --change-interface=docker0`
	- need to bind to 0.0.0.0:8300 by setting SERVER_HOST env var
	- make sure to have an **actual host name** for the current host and all related settings. For example "devhost.local"
	- configure ownCloud server and Phoenix to always use said host name (see occsetupphoenix.sh)
	- `docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm --add-host devhost.local:192.168.1.3 --name selenium selenium/standalone-chrome-debug`
	- `SERVER_HOST=http://devhost.local:8300 SELENIUM_HOST=devhost.local BACKEND_HOST=http://devhost.local/owncloud/ yarn run acceptance-tests tests/acceptance/features/webUIFiles/createFolders.feature`

- guide for possible reasons for random failures:
	- need to wait for button to be enabled before clicking. for this append ":enabled" to the selector when waiting for visibility
	- clearValue not triggering vue events: use clearValueWithEvent() instead of clearValue()
        - selenium clicks using screen coordinates, so sometimes it might click on the wrong element if for example targetting a "td" but there's a checkbox in the middle of it, it might click the checkbox instead...

**Comment by PVince81** [comment]
sometimes I wonder if we should simply provide a bootstrap script that will git clone everything that is needed and automatically configure it, including the client id

**Comment by LukasHirt** [comment]
Tests are documented in https://owncloud.github.io/clients/web/testing/
