### ISSUE TITLE
Missing placeholder texts

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#1960]
Across the Phoenix frontend, there are many text fields that are plain empty, or when emptying their contents, they do not display a placeholder.

Some notable places:
- [ ] search box in header: https://github.com/owncloud/phoenix/issues/1649
- [ ] expiration date field
- [ ] rename prompt dialog
- ...

**Comment by PVince81** [comment]
we should polish this, adding to M1

**Comment by pascalwengerter** [comment]
Closing this since we've put in quite some effort to eliminate getting all user-facing strings translated and the list isn't actionable
