### ISSUE TITLE
Custom role entry useless for file shares

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#1961]
For file shares, the available set of permissions are
- Viewer: can share
- Editor: can share + can change
- Custom Role: can share + can change

Custom role here is not useful as it will have the same result like picking either "Viewer" or "Editor".

It is likely that this was made like this to accommodate for future additional permissions that will only be selectable there.

I suggest to remove the "Custom Role" entry if no additional permissions exist to avoid cluttering the UI (and also cluttering the automated test cases)

@pmaier1

**Comment by PVince81** [comment]
@LukasHirt let's always raise tickets for everything that was discussed and is pending implementation

**Comment by PVince81** [comment]
Now thinking, we might need to keep this entry in case there are additional roles: https://github.com/owncloud/phoenix/issues/2063

**Comment by JammingBen** [comment]
The custom role makes sense now because of the re-sharing permission.
