### ISSUE TITLE
Cannot run dev server on different port

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#1989]
The server host and port are hard-coded in webpack config.

We should read it from the env variables instead.

cc @VicDeo

**Comment by DeepDiver1975** [comment]
Where is the problem in using 8300? This should not collide with anything else .... changing webpack config is enough configurability from my POV.

Am I missing anything? THX

**Comment by PVince81** [comment]
then maybe we should just update README.

@VicDeo tried to run it on a different port and was expecting that setting SERVER_HOST=xxx would do but it didn't because it's not read everywhere.

**Comment by VicDeo** [comment]
@DeepDiver1975 I see no problem here except it's a documented possibility ;) 
https://github.com/owncloud/phoenix#running-phoenix

**Comment by PVince81** [comment]
I suspect it might be a conflict between the "host: and port:" args in the config that are hard-coded and also the yarn command that runs the web server with `--public` which would override the "public:" setting.

I guess we might need to pick the one or the other. I'm not sure what difference there is.

**Comment by pascalwengerter** [comment]
You can by now run the dev server on a different port, by using e.g. `PORT=3006 yarn serve`. Since this is not very useful/there's no real usecase to do this with the setup guides for oCIS/OC10 I won't add it to the docs.
