### ISSUE TITLE
Public link access for file editor apps

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#1996]
Provide public link access for file editor apps.

It means the editor should open for files accessible through public links. (also single file shares!)

I suggest we do this for the text editor and/or markdown app to figure out the missing pieces and also to provide an example app for other file editor app developers.

@pmaier1 @LukasHirt

**Comment by PVince81** [comment]
Markdown app doesn't work, but likely for different reasons:
![image](https://user-images.githubusercontent.com/277525/65691620-70ce3800-e071-11e9-80ef-16cb6dce535b.png)

**Comment by MonksterFX** [comment]
Would be nice to have an Opportunity to do this. If it possible a short example would be great.

**Comment by pmaier1** [comment]
Maybe @LukasHirt can provide some hints?

**Comment by LukasHirt** [comment]
This would need to features in Web:

- Offer a select for which app should be used. Could be a dropdown in the create link dialogue
- Handle the param in the URL when opening the link to open the correct app

Both should be quite straight forward to implement. What I am a bit uncertain about is the server part. Currently, we're redirecting the link in oC10 to the new WebUI. I need to check if the redirect could already handle some arbitrary params or if it would need to be extended which would then mean the need for a new release of the server.

**Comment by pmaier1** [comment]
> This would need two features in Web:

I think there's a misunderstanding. If I understand correctly, this ticket is about making viewers/editors (e.g., media viewer or a text editor) available when accessing files via a public link. Currently those are only available for logged in users.

**Comment by MonksterFX** [comment]
@pmaier1 Yes and No, It depends on your application model. In the first place it would be awesome (as you mentioned) to be able to open publicly shared files with an editor/viewer by link.

For more advanced Applications it is perhaps necessary to route the request to an Service outside of Ocis/oC10 (Extension).

**Comment by LukasHirt** [comment]
Ah, okay. Sorry for the confusion. I remember we once discussed opening the files directly in those editors and my brain merged it into this ticket 🙈

Then we'd have to first check and potentially adjust the sdk to use the correct headers in such case and then just enable it in editors (there is a check for the route so we'd only add public as enabled). I'll check the sdk and will see how much would need to be changed there.

**Comment by kulmann** [comment]
This has recently been done in https://github.com/owncloud/web/pull/6667
Also, in https://github.com/owncloud/web/pull/6763 the (originally) markdown editor has been renamed to `text editor`.
Closing this ticket as done ✅
