### ISSUE TITLE
Allow displaying files app sidebar while a file editor is open

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#1997]
Whenever the user is editing a file, the editor is opened in the full page (with header).
In this state it would be nice to still have the sidebar on the right available for the user to perform actions on the file like sharing, commenting, etc.

@pmaier1

**Comment by pascalwengerter** [comment]
Closing this as unresponsive, @tbsbdr feel free to give it a think and reopen if applicable. Could be achieved by adding a config option to fileEditor apps so app developers can decide whether that should be possible
