### ISSUE TITLE
Refresh list on click on the home icon in breadcrumbs

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#2018]
## Description
Currently, if the user clicks on home icon in the breadcrumbs and is in home folder, nothing happens. Needs to be able to refresh the home folder. Same for logo.

**Comment by pascalwengerter** [comment]
Logo works for me now (`href="#/"`) on oCIS master. Home icon in the files list still doesn't (link in breadcrumb list is `href="#/files/list/%2F"`)
