### ISSUE TITLE
Header of sidebar needs to be sticky

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#2019]
## Description
When the user scrolls in the sidebar the header containing icon, name, size, mdate and tabs needs to stay on the screen.

## Motivation
If the header stays sticky the user can still easily see what item he's got the sidebar opened for and can easily navigate between different tabs.

**Comment by pascalwengerter** [comment]
@lukashirt can we close this now that #evilPR is merged? :)

**Comment by LukasHirt** [comment]
@pascalwengerter Not yet - this hasn't been tackled in that PR...
