### ISSUE TITLE
Introduce JS unit test framework for utility functions

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2026]
Currently we already have a lot of acceptance tests.

These are useful to test user interaction in the UI.

Once we start going into some details like checking with every possible file name, like testing if natural sort works, using acceptance tests through the UI are overkill. They will take a long time to run for not much gain.

So here the idea is to introduce JS unit tests. The JS unit tests should never test any UI components but focus on making sure that the **utility functions** (like in the mixins) are working properly for any set of inputs, including corner cases.

We could look at https://vuejs.org/v2/guide/unit-testing.html

Here's a list of things we could cover with unit tests:
- utility functions for mapping permissions to roles (for https://github.com/owncloud/phoenix/issues/1897)
- utility functions for natural sort (for https://github.com/owncloud/phoenix/pull/1972)

@DeepDiver1975 @individual-it @LukasHirt

**Comment by individual-it** [comment]
I think that would be great! also for things like testing the DOM see https://github.com/owncloud/phoenix/commit/10c93d646f473ae0c4535ff909a7360ff8cafb34

**Comment by DeepDiver1975** [comment]
The original Idea was to have such util code outsoured in thier own repos/packages where unit tests can be executed.basically like we already so With owncloud-sdk

**Comment by LukasHirt** [comment]
I'd propose to bring [Jest](https://jestjs.io/). The configuration is simple and it comes with some powerful features like e. g. snapshots. An alternative could be then [Mocha](https://mochajs.org/) which comes with more flexibility.
