### ISSUE TITLE
Federated sharing

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2050]
- [x] FE: accepting federated shares through notification (tested through https://github.com/owncloud/phoenix/issues/1785)
- [ ] FE: "add to owncloud" in public page
- [ ] FE: dialogs for accepting + enter password
- [x] FE: sharing dialog entries
- [ ] FE: "shared with me" entries: https://github.com/owncloud/phoenix/issues/3178
- [ ] BE: private ajax APIs in the app / core (for accepting) ?

**Comment by JammingBen** [comment]
Closing in favour of https://github.com/owncloud/web/issues/9852.
