### ISSUE TITLE
Video playback

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2051]
The current media viewer implementation is missing video playback.

@felixheidecke please add details about what the challenges are for this.

Some points I think that will need to be addressed:
- video playback in general
- loading indicators
- preloading
- range requests (with CORS + Bearer)

**Comment by DeepDiver1975** [comment]
It is technically possible to stream data from fetch/xhr with bearer headers into the video element by using the media source api - https://developer.mozilla.org/en-US/docs/Web/API/MediaSource

But there are downsides:
- loading chunks needs to be implemented by us - finding proper chunks sizes is a challenge
- before writing data to the source stream the mimetype AND the codecs need to be analysed, this requires additional libraries (for mp4: mp4box)

A draft implementation (no chunked download of video data yet) can be found here: https://github.com/owncloud/phoenix/pull/3245

Especially detecting the codecs is a critical part and it not possible in a reliable manner (yet?).

It looks like that passing the video source url into the video element directly (and using cookies/presigned url query parameter) is still more reliable.

**Comment by LukasHirt** [comment]
It is now possible to play videos
