### ISSUE TITLE
Media viewer swiping

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2053]
Touchscreen swiping currently doesn't work with the media viewer.

We need to add this back for a smoother mobile experience, especially considering that we had it in the OC 10 version.

@felixheidecke

**Comment by kulmann** [comment]
Something worth looking into: https://vueuse.org/core/useswipe/

**Comment by AlexAndBear** [comment]
I think this is not possible because of our pinch and zoom implementation without having bad effects on the UX side. 

Therefore closing as not planned.
