### ISSUE TITLE
File actions for the current folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2061]
Provide a way to perform actions / open the sidebar for the current folder.

Not sure how the UX would look like as the user needs to select something. Or maybe select nothing and the sidebar always stays visible ?

This is needed to be able to allow sharing of the current folder with the exception of the root folder.

**Comment by PVince81** [comment]
Note: we don't have this feature in OC 10 but it was discussed many times.

Would consider this "nice to have" but not for feature parity.

**Comment by pascalwengerter** [comment]
Closed in favor of #3919
