### ISSUE TITLE
Support additional sharing roles through extensions

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2063]
The ownCloud server has support for "share attributes" which can be attached to a user share, additionally to the regular permissions.

We should provide an extension point for Phoenix apps to provide their own set of share attributes / extra permissions. Since the Phoenix UI is now working with roles, we should also consider providing a set of roles and their mappings to permissions + share attributes.

- [ ] extension point
    - [ ] ability to define extended permissions through share attributes
    - [ ] ability to define roles and their mappings to permissions + share attributes
    - [ ] share attributes that have no role mapping must appear as extra checkbox (like "can share")
    - [ ] UI components to be provided by the Phoenix app (like we did in OC 10.3.0)

**Comment by PVince81** [comment]
- [ ] Note that for files and folders the set of permissions is different for the roles.
This might apply as well for share attributes, so we might want to provide separate definitions for folder and for files

**Comment by PVince81** [comment]
might imply extending on the server side by hooking into the roles API.

but this API only returns roles, not permissions, so might need further extensions there ?

@DeepDiver1975

**Comment by kulmann** [comment]
Not relevant anymore, since the new `SharingNG` API defines sharing roles backend side, in a for an admin configurable way.
