### ISSUE TITLE
Markdown editor not working with public links

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2076]
### Steps
1. Create folder "public"
1. Enter the "public" folder
1. Create a file with the menu and call it "test.md"
1. Share "public" with link
1. Copy the link
1. Log out
1. Open the link
1. Type some text and save

### Expected result
Editor opens, text is saved.

### Actual result
First access redirects through the oauth authorize pages.
Second access shows the editor with vue errors in the console.
![image](https://user-images.githubusercontent.com/277525/65691620-70ce3800-e071-11e9-80ef-16cb6dce535b.png)

This is likely an issue with the app and not with the APIs.
It would be good to fix the issues to confirm that editor apps can already work with public links (for https://github.com/owncloud/phoenix/issues/1996)

@DeepDiver1975 @LukasHirt FYI

**Comment by pascalwengerter** [comment]
Closed since #1996 describes the problem in a more generic way
