### ISSUE TITLE
Public link page should not display links and collaborators

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2090]
### Steps

1. Create folder "public"
1. Create subfolder "public/sub"
1. Share a folder "public" with link with "Editor" role
1. Log out
1. Open the link
1. Open the sidebar for "sub"

### Expected result
Only versions tab displayed.

### Actual result
"Links" and "Collaborators" tabs are present.
Creating a public link results in a validation error "Please specify an authorization first".

We should remove those panels in public view mode !

**Comment by pmaier1** [comment]
> Expected result
Only versions tab displayed.

The current oC10 public link frontend does not have the sidebar at all. I don't necessarily think that versions should be available there.

**Comment by kulmann** [comment]
The right sidebar in public link contexts now only shows actions. No people, links or versions anymore.

**Comment by saw-jan** [comment]
@kulmann this issue still persists.
And the result is different for different cases.

1. When opened in new tab (without logout):
![hasothers](https://user-images.githubusercontent.com/52366632/156341316-e03e7771-50e5-47d2-839f-fe631b6c8329.png)

2. When opened in private tab: (loading doesn't finish)
![privateloading](https://user-images.githubusercontent.com/52366632/156341573-865651d0-9778-4ebc-a02c-cb9ff0a37d5a.png)

**Comment by saw-jan** [comment]
Looks like that happened only in my machine. Sorry!

**Comment by saw-jan** [comment]
But wait :smile:, `people, links, versions` panels are still visible on the public link page when using `oCIS` server.

![webUISharingPublicManagement-shareByPublicLink_feature-L90](https://user-images.githubusercontent.com/52366632/156531781-c3be5993-3d7a-4322-a515-be9a0e72240b.png)

Failed in drone: https://drone.owncloud.com/owncloud/web/23211/68/15

**Comment by kulmann** [comment]
I guess that is a regression. I'll make a PR. Thanks for bringing it up!
