### ISSUE TITLE
[QA] No indicator if filter is active

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#2121]
* Click open the Filters dialog. Default: both [X] Files and [X] Folders are selected.
* Deseselect [ ] Folders. All folders disappear.
* click elsewhere, the dialog closes. 

There is no message or sign which informs the user that a filter is active.
Expected result: The filter button should be displayed as activated (button in petrol or gray, etc)

**Comment by DeepDiver1975** [comment]
Can you please post Screenshots or an animated gif to Show What happens?
THX

**Comment by jnweiger** [comment]
This issue affects both, filter and search.

Filter: 
This folder contains 7 subfolders, three of which have 'er' in their names:
![image](https://user-images.githubusercontent.com/1108546/67010640-54607100-f0ee-11e9-9fad-97f903d3f4ce.png)

When I click the filter button again, the dialog closes, and still only these three are shown:

![image](https://user-images.githubusercontent.com/1108546/67010804-a86b5580-f0ee-11e9-9209-3b69febd0a53.png)

Search:
Text entered in the search field remains visible after the search. The search field normally cannot be closed. GOOD.
But if there is a long path name, the search field is shown as an extra dialog

![image](https://user-images.githubusercontent.com/1108546/67011181-61ca2b00-f0ef-11e9-9fcc-07d72c20f30f.png)

A click on empty space makes the extra dialog disappear, but the search is still active.

**Comment by pascalwengerter** [comment]
Closed since we don't currently have a filter anymore
