### ISSUE TITLE
[QA] Menu button stays activated after closing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#2126]
Click the menu button, the menu opens to the left, and the menu button is activated. (Color changes from black to petrol)
Click the menu button again, the menu closes, but the button remains activated.

![image](https://user-images.githubusercontent.com/1108546/66033919-8677ad80-e508-11e9-86b2-ca4dea1e5812.png)

(The button turns black, when closing the menu with the [X], but not when closing the menu by clicking the button again.)

Expected result: the button always turns black again.

**Comment by DeepDiver1975** [comment]
This was already discussed and afaik we agreed that the current behavior is the right one - @LukasHirt do you remember the arguments?

**Comment by DeepDiver1975** [comment]
ah - here - https://gitea.owncloud.services/fheidecke/daimler-design-system/issues/20#issuecomment-31635

**Comment by pascalwengerter** [comment]
Not relevant anymore since the menu stays open on desktop and follows a different logic on mobile
