### ISSUE TITLE
[QA] Show progress bar when delete or rename takes longer

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#2134]
Steps:

* Click on the "Rename" or "Delete" button of any folder for which the user is permitted
* Type another name and click on OK

ACTUAL: After clicking on "OK" the pop-up will be closed. Ther is no loading bar displayed. After a few seconds the entered name is displayed correctly.

EXPECTED: After the pop-up is closed, a loading bar should be displayed besides the navigation bar while updating the folder name.

**Comment by jnweiger** [comment]
Same when adding a favorite:

Steps:

*  Click on the Favorite icon on any folder/file

ACTUAL: See attached video - After clicking on favorite icon, for a short time nothing happens. There is no loading bar displayed. After a few seconds the folder/file is flagged as favorite correctly.

EXPECTED: After clicking on favorite icon, a loading bar should be displayed besides the navigation bar while updating the content area.

**Comment by PVince81** [comment]
favorite already reported here: #1903

**Comment by PVince81** [comment]
I see showing visual feedback as an important feature to make the UI look polished and avoid people wondering whether something is broken.

**Comment by dj4oC** [comment]
I think my issue is related to this one, but I'm not sure.
When I delete a file or a folder, the DELETE gets disabled after clicking and user needs to wait until action is finished.
but: there is no progress or "please wait" or something else shown to the user and the CANCEL Button is still enabled.
So in my opinion, there should be a busy-spinner and the CANCEL-Button needs to be disables
