### ISSUE TITLE
renaming a ressource to a name including a `\` does not show any error

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#2144]
### Steps to reproduce
1. rename a folder to `test\test`

### Expected behaviour
an error should be shown

### Actual behaviour
rename dialogue disappears and no error is shown

![image](https://user-images.githubusercontent.com/2425577/66118810-01b78d00-e5f7-11e9-8e5b-9c981eaa3dce.png)

**Comment by LukasHirt** [comment]
We get now general error message after #2177 has been merged. Should be though handled the same way as we handle other invalid characters but for this we'll need to first move forward with this issue #1906

**Comment by pascalwengerter** [comment]
Can't reproduce on current master, closing this for now
