### ISSUE TITLE
Always display hidden files

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#2157]
## Description
We have implemented the same way of handling hidden files as is in the old webUI. Do we actually need to implement this like in that way? What about simply showing the files all the time even if they start with the dot?

## Motivation
Normal user isn't probably really going to even know what it means in webUI to "display hidden files" and we already have a use case where we simply completely remove the option from the filter menu. And if the users would really want to use something like this it could be done as a app.

What do you think about this? @pmaier1 @michaelstingl @PVince81

**Comment by PVince81** [comment]
original core ticket: https://github.com/owncloud/core/issues/2589

one reason was that many users have hidden files/folders, sometimes even syncing their Linux/Mac home folders which contain a lot of dot files and folders.
