### ISSUE TITLE
Truncate names

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#2158]
## Description
We use a lot of boxes with fixed width which contain file/folder names. As soon as they get longer it simply goes away from the box creating an ugly UI. We need to decide how do we want to handle this and then implement this.

## Proposed solutions:
- Truncate the end of the name and keep only the part that fits the boxes replacing then the end with dots.
- Split the name into two parts and keep only certain number of characters in both parts if it goes over some number of characters and put dots in between them.

**Comment by jnweiger** [comment]
I'd vote for second solution!

**Comment by pascalwengerter** [comment]
I'll close this one as unspecific and unresponsive. We do have classes to truncate text and use them more and more. Adding @tbsbdr here to raise awareness and looking forward to actionable tickets in the future. Thanks for the input :)
