### ISSUE TITLE
Acceptance tests for uploads

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#2222]
Currently we test only file upload. Folders needs to be added as well.

**Comment by PVince81** [comment]
- [ ] All files
    - [ ] using "+ New" button
        - [ ] single file upload into root
        - [ ] single file upload into subdirectory
        - [ ] folder upload into subdirectory
    - [ ] using drag and drop
        - [ ] single file upload into root
        - [ ] single file upload into subdirectory
        - [ ] folder upload into subdirectory
    - [ ] uploading folder containing empty folder entries: empty folder entries do **NOT** appear (not supported, known limitation)
- [ ] Public link
    - [ ] using "+ New" button
        - [ ] single file upload into root
        - [ ] single file upload into subdirectory
        - [ ] folder upload into subdirectory
    - [ ] using drag and drop
        - [ ] single file upload into root
        - [ ] single file upload into subdirectory
        - [ ] folder upload into subdirectory
- [ ] Files drop (upload-only public link)
    - [ ] using "+ New" button
        - [ ] single file upload into root
        - [ ] single file upload into subdirectory
        - [ ] folder upload into subdirectory
    - [ ] using drag and drop
        - [ ] single file upload into root
        - [ ] single file upload into subdirectory
        - [ ] folder upload into subdirectory

@individual-it

**Comment by skshetry** [comment]
@PVince81, simple uploads of files and folders are complete.

"Empty folders" test is not possible at the moment, as we use the `filesForUpload` that is checked out in git (and, `git` doesnot support empty folders).

I have not invested much time in drag-and-drop, as it's not supported by selenium (but, can be simulated, but that way, I feel it will be closely coupled to the drag-and-drop implementation, so, we will be simulating drag and drops and will only be testing the file uploads).

**Comment by individual-it** [comment]
I tried tests for dragging an element into phoenix but did not succeed see #1302

@LukasHirt @PVince81 should we close this issue?

**Comment by LukasHirt** [comment]
I'd still like to keep this open. Having the drop upload feature untested seems rather scary to me. I guess I or @PVince81 could schedule some time in some upcoming sprint to look into this if we'd find a way.

**Comment by pascalwengerter** [comment]
@ScharfViktor I'll assign this to you, maybe we can add this to the smoke tests once they run in CI!
