### ISSUE TITLE
Top right icon not clear

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2249]
Not clear if it indicates user account.

Might need icon ?
Or remove as it has no functionality ?
But we do need an indicator to know what user is logged in ?

@wuenschedesign

**Comment by PVince81** [comment]
<img width="173" alt="image" src="https://user-images.githubusercontent.com/277525/66812962-246d6e00-ef34-11e9-96fb-2eaae679894a.png">

**Comment by PVince81** [comment]
This design decision was made because of feedback we got that OC 10 had two menus: left nav bar and top right menu.

**Comment by marcus-herrmann** [comment]
> Or remove as it has no functionality ?
> But we do need an indicator to know what user is logged in ?

Either you could give it functionality by linking to the /account when logged in (and place a link to the login in this place when the user is a guest)

OR

Re-phrase: "Hello, demo" or "Hello, guest" respectively. Then you would perceive it as an indicator/as part of the voice-of-tone-friendlyness of the interface.

**Comment by LukasHirt** [comment]
User menu was completely re-worked 

![Uploading Screenshot 2021-01-05 at 20.55.36.png…]()
