### ISSUE TITLE
Filter functionality in file list confusing

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2250]
- [ ] missing indicator if active: https://github.com/owncloud/phoenix/issues/2121
- [ ] filter icon not clear enough ? it's not clear that this is a filter. might need a different visual design ?

@wuenschedesign

**Comment by PVince81** [comment]
- [ ] the dropdown is visually not distinct enough from the background
=> might need a general styling change (uikit?)

**Comment by PVince81** [comment]
- [ ] when no checkboxes ticked => show all files anyway ?

@wuenschedesign or do you suggest a different

**Comment by PVince81** [comment]
@pmaier1 means that requirement for file and folder checkboxes is very low.

We could remove them in a first place.

This might even remove the need for having the filter dropdown in the first place.

- [ ] also need to reconsider the search field, should we have only a single field ?

To me it looks like we need a broader discussion about how to do the filter / search and the hidden checkbox.

**Comment by PVince81** [comment]
- [ ] should the "used space" indicator reflect the current folder contents or global contents ?

**Comment by LukasHirt** [comment]
> filter icon not clear enough ? it's not clear that this is a filter. might need a different visual design

At least on the desktop view, we could simply add the "Filter" label inside the button.

> missing indicator if active

Then we would need in default no checkboxes having checked state as mentioned by @PVince81 

> when no checkboxes ticked => show all files anyway ?

**Comment by marcus-herrmann** [comment]
Some UX thoughts
* I would work here with a labelled button as well since it the current filter icon looks more like a hamburger nav icon. Sometimes a "funnel" icon is not clear enough.
* My suggestion, also for the active filter state

![Artboard](https://user-images.githubusercontent.com/505181/68118845-57869a00-ff01-11e9-86db-5cf48fc92b29.png)

**Comment by pascalwengerter** [comment]
Closing since we don't currently have filtering in the files list
