### ISSUE TITLE
Improve design for file actions

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2252]
- disabled icon for download a bit confusing for folder download
- "zu prominent"

what better ways are there for file actions ?
keep in mind that we need to be touch-friendly

@wuenschedesign

**Comment by PVince81** [comment]
- why is delete prominent ?

**Comment by PVince81** [comment]
before doing right click we need to evaluate if this is even a good idea in the web, maybe doing some research in the UX fields to see what speaks for and against.

maybe users to not think about right clicking in a web UI

**Comment by LukasHirt** [comment]
Yes, we should do the research. I'll try to collect some links and will add them here. From personal experience, I used a few web apps that had this and it was a nice addition. But this is my experience - as said needs research to see it in a bigger picture.

**Comment by PVince81** [comment]
additional note: right click on web UI must have mobile equivalent as long press

**Comment by wuenschedesign** [comment]
This would be my suggestion for actions in the file list for a sharing concept that differentiates between Public Link and Collaborator.

List View:
<img width="1440" alt="List-View-5-Icons-01" src="https://user-images.githubusercontent.com/40062503/67854294-583dbb80-fb10-11e9-8d32-84b5b05212eb.png">

Actions Menu:
<img width="1440" alt="List-View-5-Icons-02" src="https://user-images.githubusercontent.com/40062503/67854296-583dbb80-fb10-11e9-99f7-317cf7e15919.png">

**Comment by wuenschedesign** [comment]
This would be my suggestion for actions in the file list for a sharing concept that leads with just one sharing action to the sharing process (public links and collaborators will be differentiated in a different process).

List View:
<img width="1440" alt="List-View-4-Icons-01" src="https://user-images.githubusercontent.com/40062503/67854651-05183880-fb11-11e9-83d4-2cde05536d10.png">

Actions Menu:
<img width="1440" alt="List-View-4-Icons-02" src="https://user-images.githubusercontent.com/40062503/67854702-182b0880-fb11-11e9-8b5b-b7087a0f9ebe.png">

**Comment by PVince81** [comment]
- need to take into account that extensions can add more actions
- action spec might decide whether always inline or always in menu, or "responsive"

**Comment by LukasHirt** [comment]
File actions were moved to the sidebar and quick actions were implemented for quick access.
