### ISSUE TITLE
Improve breadcrumb design

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2254]
@wuenschedesign found it confusing. The house icon as represented here might not be interpreted as being the home folder.

I think we might need to improve what's around it like borders, colors, etc.

Also note: when screen is small it already becomes an icon. Please check that as well.

Check how other solutions are doing.

**Comment by marcus-herrmann** [comment]
My UX thoughts:
* A breadcrumb navigation that only has one item, your current location, has no function. Maybe the breadcrumb nav should only appear when you are at least one level deep.
* Otherwise, text labels, even for the breadcrumb nav itself could be boring, but would be very unambiguous

**Comment by pascalwengerter** [comment]
Closing since we don't have the home icon anymore and overhauled the breadcrumbs anyways
