### ISSUE TITLE
Feedback file list design

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2256]
![image](https://user-images.githubusercontent.com/277525/74639232-d67ca700-516d-11ea-8c47-3c36c4d0d1f2.png)

@wuenschedesign

**Comment by marcus-herrmann** [comment]
There are parts of the image missing on the right side of the image, but I guess one of the comments is about the same visual importance that both "New" and "Add Link" buttons have, but shouldn't. 

Also I think that the close button for the "File/folder drawer", or the whole concept could be solved differently. Here's Google Ads Interface:

Closed (click on > opens)
<img width="173" alt="Bildschirmfoto 2019-11-04 um 10 35 12" src="https://user-images.githubusercontent.com/505181/68111282-0d94b880-feef-11e9-9547-a2d008ac2634.png">

Open (click on < closes)
<img width="281" alt="Bildschirmfoto 2019-11-04 um 10 35 20" src="https://user-images.githubusercontent.com/505181/68111295-14233000-feef-11e9-9fdb-767587b43597.png">

**Comment by PVince81** [comment]
I've updated the screenshot.

Some already obsolete, here are the feedback items that might still be valid:

- [ ] improve row highlight color
- [ ] folder stats should be on top, not bottom
- [ ] primary buttons are fighting for attention
- [ ] recheck public link button wording in case it's still the same
- [ ] confusing position of closing button

**Comment by pascalwengerter** [comment]
Closing this as (long) outdated
