### ISSUE TITLE
Favorite, shared with you, etc views as filters/search/quick access

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2260]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/277525/66812821-e83a0d80-ef33-11e9-8444-18c4e80f89a6.png">

**Comment by PVince81** [comment]
not only that, but also "All files" is hierarchical but all other views are flat lists.

this ticket was raised from @wuenschedesign's feedback.

we can discuss here why it's not a good then close it.

**Comment by pascalwengerter** [comment]
Closing this as outdated since we've stuck to different pages and I haven't heard anything contrary in the last months
