### ISSUE TITLE
Trashbin page design improvements

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2262]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/277525/66813763-a9a55280-ef35-11e9-8ff3-82300bb68c39.png">

@wuenschedesign

**Comment by PVince81** [comment]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/277525/66813836-cf325c00-ef35-11e9-904d-0ab46a3ab29d.png">

**Comment by PVince81** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/277525/66814138-613a6480-ef36-11e9-9075-b19c6aa3c3ee.png">

fix notifications styles in design system ?

guideline about when to use notifications ?

@wuenschedesign

**Comment by PVince81** [comment]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/277525/66814189-7911e880-ef36-11e9-8f24-0204419413e0.png">

**Comment by PVince81** [comment]
<img width="277" alt="image" src="https://user-images.githubusercontent.com/277525/66814207-816a2380-ef36-11e9-90a8-04eee0846da7.png">

**Comment by PVince81** [comment]
<img width="155" alt="image" src="https://user-images.githubusercontent.com/277525/66814234-8fb83f80-ef36-11e9-87c9-fb3074730ccd.png">

**Comment by marcus-herrmann** [comment]
My UX thoughts: 
* Shared Icon is not distinct enough, should be accompanied with a text label, like "shared"
* Agree with @PVince81's remarks that there should be variantions in the use of buttons, some are more important than others
* Also agree on more explicit button labelling when it comes to the last step of deleting

**Comment by pascalwengerter** [comment]
Closing this as outdated, most points have been adressed by now
