### ISSUE TITLE
[QA] Breadcumbs behaviour when 'delete selected' Trashcan needs more space

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#2282]
I am using the [ ] checkbox next to the 'Name' heading to select all files.

With Firefox: 
The path /JW/240/tree/randfiles_400_flat is wrapped nicely to make space. OK
The private link icon does not follow the last path component.
![image](https://user-images.githubusercontent.com/1108546/66948442-ffbce780-f054-11e9-8b25-896dbcd622cd.png)

Expected behaviour: The private link icon is next to the last component "randfiles_400_flat".

With IE11:
The path does not wrap. Parts of the path and the private link icon extend behind the search field. 
![image](https://user-images.githubusercontent.com/1108546/66948745-912c5980-f055-11e9-9522-690271887126.png)

Expected behaviour: Wrap correctly.

**Comment by LukasHirt** [comment]
Breadcrumbs are now on their own row. All actions are on the next one.
