### ISSUE TITLE
Integrate with roles API

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2316]
- owncloud-sdk
   - [ ] query existing roles from roles API https://github.com/owncloud/core/pull/36024 to be able to browse and display them
   - [ ] provide methods to query and resolve roles to permission and back
	- key/value also for bitmask perms, converted transparently
        - makes it more straightforward to work with permissions and roles (no more bitmasks)
   - [ ] interface only works with role ids on the interface level (exception maybe for compatibility "manual permissions" aka "custom role")
- oc10:
   - [ ] extend roles API to also provide role names for collaborator roles (current one only provides them for public link)
- ocis:
   - assumption is that OCIS will provide roles also using the same endpoint
- [ ] Should a role be usable in both public link and collaborators or be considered technically separate ?

@DeepDiver1975 @pmaier1 @LukasHirt FYI

**Comment by PVince81** [comment]
in the short term we are going to remove all bitmask usages from the UI as part of https://github.com/owncloud/phoenix/issues/1897#issuecomment-545401933 but the code for the role to permission mapping will stay in Phoenix.

then as part of this ticket here we can move it to the SDK after carefully thinking about the API design

**Comment by DeepDiver1975** [comment]
Roles API is at the moment only for public links

**Comment by kulmann** [comment]
Since the roles API is not used in oc10 (according to linked tickets) and oCIS will likely build an API around the new roles & permissions system it is unlikely that we'll integrate with the oc10 roles API. Closing here. We can reopen if product design changes.
