### ISSUE TITLE
Middle click to file/folder open in new tab

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2317]
When clicking on a folder with middle click or right click + open in the new: it should open the file app in the clicked folder into a separate tab. (this was the case with OC 10)

For files, we should think whether we also open the editor there. This would require a default action.

**Comment by LukasHirt** [comment]
Also, consider making the name link/button. I guess without it it could be an accessibility issue. @marcus-herrmann pls clarify.

**Comment by marcus-herrmann** [comment]
For that behavior for folders the trigger needs to be a link, linking to the route with the folders contents: e.g. https://phoenix.owncloud.com/custom/phoenix/index.html#/files/list vs https://phoenix.owncloud.com/custom/phoenix/index.html#/files/list/First.

For files I think it should be a button, given a click will make the oc-file-actions dialog visible everytime (right? Or are there occasions where a file will be downloaded directly? In this case it should be a link again, with a `download` attribute).

Right now both file and folder triggers are not interactive, semantically speaking. Assistive technology cannot detect that there's a click event listener on the <span>.

Rule of thumb when it comes to links vs. button:
* Does it open/expand/show something, or changes state of the app? -> Button
* Does it lead somewhere? -> Link

([A great presentation about the "duel" of the elements](https://marcysutton.com/talk/smashing-conf-sf-the-links-vs-buttons-showdown)

**Comment by PVince81** [comment]
There are at least three possible actions:

1) For a file, if it's a known file type and there's an editor registered: open the editor. (in the current implementation it will show a footer with a list of actions, but this might change, needs to be discussed)
2) For a file, if unknown type: download
3) For a folder: navigate into folder.

The above is for left click.
For middle click I'd expect the same behavior but happening in a separate folder.

If we use a button there it is likely that middle click will not work ?

**Comment by marcus-herrmann** [comment]
@PVince81 The concept of "Middle click" is not standardized in any way, I'm not sure what you are refering to exactly.

**Comment by PVince81** [comment]
@marcus-herrmann with "middle click" I mean "open in new tab" which is also accessible from the context menu. In general that functionality only works for links that have an href defined

**Comment by marcus-herrmann** [comment]
> 1. For a file, if it's a known file type and there's an editor registered: open the editor. 

If a state, in this case a particular file, has an unique URL, a link should be used. Currently in phoenix that is not the case, so the "editor" trigger should be a button.

> 2. For a file, if unknown type: download

`<a href="/some/path/file.whatever" download>Herunterladen</a>`

> 3. For a folder: navigate into folder.

`<a href="index.html#/files/list/myfoldername">Myfoldername</a>`

> If we use a button there it is likely that middle click will not work ?

If middle click maps to open in new tab: correct. As you said: only links can be opened in new tabs/windows.

> (in the current implementation it will show a footer with a list of actions, but this might change, needs to be discussed)

If this usage pattern stays there will be urgent need for focus management in this case if the "actions" can't be solved with the disclosure widget pattern (as of now "actions" has more of a "dialog character")

**Comment by marcus-herrmann** [comment]
@PVince81 Stepping one step back: I would label adding the correct semantics for folder and file controls not as enhancements, but crucial, therefore "Bug". As of now the File/Folder controls are not operable via Screen Reader or keyboard.

**Comment by kulmann** [comment]
Superseded by more recent https://github.com/owncloud/web/issues/11222
