### ISSUE TITLE
bigger thumbnails in web interface (feature request) 

### ISSUE THREAD

**Issue by robertboyl** [owncloud/web#2341]
Hello, friends!

Just wondering, any chance to have bigger thumbnails in the web interface?

I shared an album of photos with friends, but thumbnails are so small...

See how they appear

![example](https://user-images.githubusercontent.com/13451604/67764593-12f28e80-fa29-11e9-8455-19a35425d104.png)

Thanks!

**Comment by pascalwengerter** [comment]
Closed as fixed since we now have a `Details` panel in the right sidebar with a bigger preview (please reopen if you disagree @robertboyl  @tbsbdr)
