### ISSUE TITLE
Complex theming

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2404]
## Requirements
- Exchange assets (icons, buttons, ...)
- Size of HTML elements (logo, 
- Margins, paddings, sizes (e.g., height of top bar)
- Consent on login => needs separate extension, not theming
- Ability to change arbitrary strings and translations (ex: User types in sharing (e.g. "Guest" => "EXTERNAL"; GC))

**Comment by PVince81** [comment]
- [ ] have a look at existing Phoenix internal theme to find out which bits we needed to adjust (texts, etc) and define extension points to allow such extensions

**Comment by PVince81** [comment]
4d for the diff

**Comment by PVince81** [comment]
we should work on the diff first in case we find more items to discuss for complex theming

**Comment by PVince81** [comment]
Possible extension of requirements:

- ability for example to decide whether to always hide or not the file actions
- customize / replace share indicators: https://github.com/owncloud/phoenix/issues/2895

Idea: split this ticket further into:
- complex theming that is about replacing stuff visually (string, margin, icons)
- customizing which is about writing extensions and modifying visual behavior ?

**Comment by PVince81** [comment]
- [ ] important to discuss: with complex theming, how to provide alignment on mobile and desktop clients, considering the broad scope of customizations ?

**Comment by LukasHirt** [comment]
Tests are still failing, will investigate more and there is one error in console regarding vuex mutations which I'm digging deeper in now. I think you can do a "first round" of the review though @PVince81

**Comment by pascalwengerter** [comment]
I guess this can been closed/has been addressed via #9698? I'd prefer smaller and more actionable tickets going forward
