### ISSUE TITLE
Research how to debug while working on npm modules

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2445]
As we're going to touch the owncloud-design-system and owncloud-sdk often, we need a good way to be able to prebuild these from branches and pull requests.

So far the thing that worked for me was:

1. In the npm module, use the "npm prepare" step to have it built. This step is run by npm after "npm install" see https://github.com/owncloud/owncloud-sdk/pull/372/files
2. In Phoenix, edit package.json and append "#" + the commit hash of the PR to use from the SDK or design system (find it in the PR page)
3. Run "npm install" in Phoenix.
4. Work
5. When done and the PR is ready to merge, revert the "npm prepare" stuff before merging

TODOs:
- [ ] research whether we can keep the prepare step for production builds
- [ ] make sure we have a dev / debug mode with source maps in design system and SDK
- [ ] document the approach

@DeepDiver1975 @LukasHirt @marcus-herrmann

**Comment by PVince81** [comment]
One alternative would be to have the webpack from Phoenix rebuild those submodules, but I'm not sure if it's a good practice.

**Comment by marcus-herrmann** [comment]
For ODS's package.json, the temporary prepare fix would be the additon of the following line to scripts:

```
"prepare": "npm run build:system"
```

**Comment by LukasHirt** [comment]
For debugging with local clones use `yarn link`. For PRs use their links in package.json
