### ISSUE TITLE
Error message displayed should be congurent in both files page and shared with me page

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/web#2447]
### Steps to reproduce
1. Disable resharing and share a file ```abc.txt``` with user ```user1```
2. Relogin as ```user1``` and try to share ```abc.txt``` to another user ```user2```. Here sharing input is not displayed as 
![1](https://user-images.githubusercontent.com/34328907/68662039-2131c600-0564-11ea-9d2a-4f82d3af3faf.png)

3. Now browse to shared with me page and try to share ```abc.txt``` with ```user2```. Here sharing input is visible 
![2](https://user-images.githubusercontent.com/34328907/68662152-5ccc9000-0564-11ea-854d-004550c26ea8.png)
Here now type ```user2``` in sharing input and provide any role you like. Then only you get error message as:
![4](https://user-images.githubusercontent.com/34328907/68662544-22172780-0565-11ea-993a-a0e9e1b08108.png)

### Expected behaviour
There must be congruency in displaying an error message when resharing is disabled but the user try to reshare from different pages.

### Actual behaviour
Error message is displayed differently according to pages even though the issue is same.

**Comment by JanAckermann** [comment]
not able to reproduce anymore
