### ISSUE TITLE
"shared with me" and "shared with others" page are still displayed even when sharing api is disabled

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/web#2459]
### Steps to reproduce
1. Disable share api using occ command or using webui from owncloud's settings>admin>sharing and disabling ```Allow apps to use the Share API```
2. Go to phoenix's menu
![Screenshot from 2019-11-13 12-09-29](https://user-images.githubusercontent.com/34328907/68738462-7cb88e00-060e-11ea-9377-e896e759a96c.png)
Here you can see ```shared with me``` and ```shared with others``` page is still displayed and you can browse to these pages

### Expected behaviour
```shared with me``` and ```shared with you``` pages should not be displayed when sharing api is disabled
### Actual behaviour
```shared with me``` and ```shared with you``` pages are displayed even when sharing api is disabled

**Comment by PVince81** [comment]
Just had in mind to test this soon, thanks for raising!

**Comment by pascalwengerter** [comment]
Update: Can still reproduce
