### ISSUE TITLE
Cannot browse directly to folders with special characters in its names

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#2467]
### Steps to reproduce
1. Create a folder with special characters in its name. (eg. ` ?&%0 ` )
2. Browse to that folder using the webUI (It works)
3. Copy the URL from the Address bar and use that URL to browse on another window (or tab)
OR
 Reload the current page

### Expected behaviour
The page should load correctly

### Actual behaviour
Tell us what happens instead
The page doesn't loads correctly. Empty page.

**Comment by individual-it** [comment]
Tests added in  #2501

**Comment by pascalwengerter** [comment]
@dpakach couldn't reproduce on web.owncloud.com and running oCIS locally with current master. Can you?

**Comment by dpakach** [comment]
@pascalwengerter seems to be fixed. Closing this issue now.
