### ISSUE TITLE
Idea: sidebar entries as sections instead of tabs

### ISSUE THREAD

**Issue by wuenschedesign** [owncloud/web#2493]
### Steps to reproduce
1. Clicking on a list item opens the sidebar with additional information and actions

### Actual behaviour
Right now the different sections of information (links, collaborators) are organized by a tab navigation in the sidebar. With just two nav elements it would be usable, but with more nav elements the space provided will not be sufficient anymore for displaying all the nav items in one row (espacially considering translation into other languages!)

### Expected behaviour
Instead I suggest a sidebar which aligns all information sections from top to down.
1) That allows to see all information at once just by scrolling downwards
2) more sections can be added without concerns over limited space (priority has to be discussed).
Future information sections show information about how and wether a user has access to this information and if he can alter it:
- private link
- indicators showing the ownership of the folder/file
- public links (quantity; type)
- collaborators (quantity; organized by users, externals, groups, etc.)
- comments (author, date)
- tags (linking to a flat list with all folders/files that are tagged the same?)
- creation date (as differentiation to modification date)
- additional description (explanation
- additional or linked files (folders or files that have importance or are linked to the selected folder/file)

### Server configuration
**Operating system**: Any browser

**ownCloud version:** Current implementation of Phoenix UI

**Comment by wuenschedesign** [comment]
The following screens show how the sidepanel could look like.
- The individual sections are organized via accordeon, so that by opening at first sight the user has an overview over all the sections. By opening the various sections he gets detailed information. General workflow could be that one a user decided to open certain sections, this setting will automatically saved for future use, even if he clicks onto other items in the file list.
- The sidepanel should also automatically be open, if the portview of the screen is big enough (desktop use).

1) First screen shows a side panel for a folder that is not owned by the user, he has got the following permissions, user can:
- preview
- download
- reshare

![List-View-Detail-Open-02](https://user-images.githubusercontent.com/40062503/69147204-ba675c00-0ad1-11ea-8cb6-6850c8c5000f.png)

2) Second screen shows a side panel for a folder that is not owned by the user, with more limited permissions (user cannot reshare!), user can just:
- preview
- download

The section info about links and collaborators is still visible, so that the user understands, that this information is generally available for ownCloud, but in secondary colour to indicate, that he has no access to further actions (creating links, inviting collaborators)

![List-View-Detail-Open-Shared-with-me](https://user-images.githubusercontent.com/40062503/69147428-2f3a9600-0ad2-11ea-82cc-c2653e2b7169.png)

**Comment by LukasHirt** [comment]
Done

![Screenshot 2021-01-05 at 21 02 46](https://user-images.githubusercontent.com/25989331/103693314-60597c80-4f99-11eb-8b80-c3e3ef9c0b69.png)
