### ISSUE TITLE
Favourites page shows first previous files

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#2505]
### Steps to reproduce
1. Mark items as a favourite
2. Navigate to the favourites page

### Expected behaviour
After the load has been finished, the favourite items should be immediately displayed.

### Actual behaviour
After the load has been finished, the previous items are displayed, then disappear and after that, the favourites ones are displayed.

### Phoenix version
- 0.2.5

**Comment by PVince81** [comment]
This is partly connected to https://github.com/owncloud/phoenix/issues/2150 where an empty array would make it display the previous file list. We should introduce a proper progress bar here.

**Comment by PVince81** [comment]
need to be retested, might be solved already

**Comment by LukasHirt** [comment]
Fixed
