### ISSUE TITLE
Federated shares not showing in shared with me page.

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#2510]
### Steps to reproduce
1. Setup two owncloud servers for federated share
2. Share a file `lorem.txt` from one server to another
3. On the receiving server open through phoenix and go to shared with me page

### Expected behaviour
The file `lorem.txt` should be listed on the shared with me page.

### Actual behaviour
The file `lorem.txt` is not listed on the shared with me page.

**Comment by kulmann** [comment]
Works now via OCM 1.1 in oCIS.
