### ISSUE TITLE
reshared share that is shared with a group the sharer is part of shows twice on "Share with me" page

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#2512]
### Steps to reproduce
1. as "user1" share a folder to "user2"
2. put "user2" in group "group1"
3. as "user2" share the received folder with "group1"
4. as "user2" check the "Shared with me" page

### Expected behaviour
the folder should be there only once

### Actual behaviour
folder is listed twice, once shared by "user1" and once shared by "user2"

**Comment by PVince81** [comment]
Right, the API doesn't merge them together on the backend. The merging is only done on FS level but not in the OCS Share API. So need to implement grouping.

**Comment by kulmann** [comment]
We're in the process of removing the resharing feature from oCIS. Rationale is here: https://github.com/owncloud/enterprise/issues/6341

Closing here.
