### ISSUE TITLE
Allow providing alternative file list views

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2585]
Ability to replace the view inside of FileList.vue with another Vue control (Web Component).
This would make it possible to provide a thumbnail view like the gallery app used to do.

This also implies that switching the view can be done in other places like "Shared with you", "Favorites" and "Trashbin".

This would likely require additional buttons *somewhere* to switch the view.

This should be done using an extension point within the files app.

Will require some refactoring to add an additional switchable layer.

**Comment by dschmidt** [comment]
A lot of development has happened since 2019 - is there a mechanism for this by now? 
If not: I see huge refactorings happen, maybe it's now time to sneak it in? ;-)

**Comment by kulmann** [comment]
It's currently planned `soonish` ™️ in the web roadmap to have a grid view and even an extension point for providing other file view modes as web extensions (not planning to use web components though). Stories don't exist yet, as that will not be part of the next two sprints. Will update here (and then close this issue) when we're further in the planning process.

**Comment by JanAckermann** [comment]
We've already implemented different view modes, extension system is coming up, but since the key feature request if fulfilled, I am closing this issue
