### ISSUE TITLE
Warn leaving users about running uploads

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2590]
### Steps

1. Upload many files
1. During the upload, close the browser tab or navigate to another URL

### Expected result
A browser warning appears to tell that the upload will cancel if the user proceeds to leave.

### Actual result
No warning, upload is cancelled. Confused user.

This should be a metter of adding a `window.onbeforeunload` or similar to the right places and check for pending uploads (or any other operation, really)

@LukasHirt @hodyroff as discussed

**Comment by anaswaratrajan** [comment]
Hi, I know this issue is old, but it still seems to exist. Can I take this up?

**Comment by pascalwengerter** [comment]
> Hi, I know this issue is old, but it still seems to exist. Can I take this up?

Hey @anaswaratrajan, do you need any more details/help to get started? Happy to have you give it a shot 💪🏽

**Comment by anaswaratrajan** [comment]
@pascalwengerter, Thanks! I'm currently having some issues with the setup. Can't seem to login with the test credentials. Looking into it. 

But I was able to navigate the respective file upload, progress components and get some ideas on how to implement a solution. Will let you know if I'm having trouble.

**Comment by pascalwengerter** [comment]
@anaswaratrajan just assigned you to this for now ;)

Could you give us an overview on how your local setup looks like/what you've tried to get it running?

**Comment by anaswaratrajan** [comment]
Followed these [instructions](https://owncloud.github.io/clients/web/backend-ocis/) and docker to serve OCIS.

**Comment by pascalwengerter** [comment]
Feel free to join us on https://talk.owncloud.com/channel/phoenix and ping me using the `@` for quicker feedback btw!

What's the error message you're getting right now?

**Comment by anaswaratrajan** [comment]
![OCIS_web_issue](https://user-images.githubusercontent.com/42616235/111146482-83169b80-85af-11eb-84ae-88c60024c490.png)

**Comment by pascalwengerter** [comment]
Seems odd, how are you running oCIS (built locally, Docker, using a VM client etc)? And did you kill the `web` service and replace it with running the `yarn serve` in the web repo? (Could be interesting _not_ to kill the web service and see if the error persists)

Also, any clues within the logs?

**Comment by anaswaratrajan** [comment]
I'm running OCIS with Docker.  

I tried this `docker exec -it <id> ocis kill web` to kill the web and it gave a success message as well. 
Also tried after running it again. 

Found this in logs 
```
http: TLS handshake error from 172.17.0.1:44184: remote error: tls: unknown certificate
```

**Comment by pascalwengerter** [comment]
Can you try starting the web app using `yarn serve` first and docker(-compose) afterwards?

Also, are you using https://localhost:9200 (https, not http)?
