### ISSUE TITLE
[Backlog issue] Accessible tooltips

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#2623]
@wuenschedesign You might remember, in a joint videocall some weeks ago where the Phoenix team and us discussed about improvements and design of the FileList, we very shortly covered the topic of icon-only buttons or icon-only indicators: Here's a way how they could look like: https://van11y.net/downloads/simple-tooltip/demo/index.html

Regardless of the implementation, this is possibly a visual design topic to consider.

If there is no need for special styling (as long as it has all the necessary contrast ratios) this issue can serve as a hook/reminder for the implementation.

**Comment by pascalwengerter** [comment]
Closed via #5055 for now
