### ISSUE TITLE
[Accessibility related bug] Too many tabstops in New File menu

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#2628]
[This is a ticket for the "accessibility backlog"]

<img width="343" alt="New File menu with invisible superflouous tabstops" src="https://user-images.githubusercontent.com/505181/70324673-69c16400-1830-11ea-9b48-0587acb43924.png">

As of now, when a user operates the New File menu with the keyboard they will find that after each visible menu item/action/in this case link, there is one more invisible tab stop. When you look into it in the web inspector you will find according input[type=file] elements.

In addition, I recommend this menu to be an action menu [[related PR in ODS](https://github.com/owncloud/owncloud-design-system/pull/522)] since it changes state (opens an upload prompt but has no navigational influence that could justify the usage of the `<a>` element.

**Comment by pascalwengerter** [comment]
Closing this since #5018 is merged and we're waiting for feedback (and will open new tickets with the requested changes from the `a11y` audit)
