### ISSUE TITLE
Make CI fail when warnings in console

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2728]
We should trigger a CI failure whenever we detect warnings in the browser console at the end of any successful test.

If this is too complicated to do technically, then at least add scenarios for the main pages like the files app, public link page and files drop.

This way we can catch these earlier as they could be signs of regressions.

@individual-it @DeepDiver1975 @LukasHirt

**Comment by PVince81** [comment]
Context: we had ODS updates recently that introduced new required attributes but CI still passed.
Ref to a PR of mine that fixes this kind of warnings: #2727

**Comment by PVince81** [comment]
I found this API to access log entries: https://stackoverflow.com/a/53780970

**Comment by individual-it** [comment]
we could have a check in the AfterScenario hook

**Comment by PVince81** [comment]
I managed to come up with something that works: https://github.com/owncloud/phoenix/pull/2729

**Comment by pascalwengerter** [comment]
We should take another look at this after #5194 got merged

**Comment by pascalwengerter** [comment]
Closing as not relevant anymore. We usually check the console for warnings&errors when doing PR reviews and releases

Also @ScharfViktor maybe take note of this idea for improving smoke tests in the future. Not pressing from my POV, though
