### ISSUE TITLE
Display previews

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#276]
- [x] display preview in file list: use mediaSource plugin in Phoenix to connect to Webdav preview API to generate one like we did in core
   - [x] oc-file addition: https://github.com/owncloud/owncloud-design-system/pull/678
   - [x] add icon URL to file lists
- [ ] display preview at the top of sidebar ?
- [ ] where to get the default thumbnail sizes ?
   - might be in old PHP template
   - need a way to retrieve from user settings ?
- [ ] only show previews if previews are enabled: https://github.com/owncloud/core/blob/master/core/js/config.php#L207
   - [ ] REQUIRES: capability: TODO raise core ticket
- [ ] get enabled mime types to find out whether we should attempt retrieving a preview or whether to fall back directly to an icon: https://github.com/owncloud/core/blob/master/core/js/config.php#L208
   - [ ] REQUIRES: capability: https://github.com/owncloud/core/issues/31267

**Comment by PVince81** [comment]
- [ ] preview as thumbnail in the file list row
- [ ] preview at the top of the sidebar ?

**Comment by DeepDiver1975** [comment]
> * [ ]  preview as thumbnail in the file list row
> 

I wonder if this are really hard requirements for the frontend.

Cons:
- small previews are almost impossible to view
- heavy computation is required to create/deliver a lot of previews
- personal opinion: they have never been usefull

**Comment by PVince81** [comment]
Previews would start to become interesting once we get to implement a grid view of files (like gallery). Indeed the previews are rather small and even for pictures it doesn't show much.

**Comment by PVince81** [comment]
The previews will be retrieved using the Webdav API like OC 10 has.

**Comment by PVince81** [comment]
- [ ] where to get the default thumbnail sizes ?
   - might be in old PHP template
   - need a way to retrieve from user settings ?

**Comment by PVince81** [comment]
- cannot send Bearer token through headers, so need to use `fetch()` API to retrieve the image data and then pack them into "data:" URLs
- no cookies
- not related to CORS

=> would require pre-signed URLs on OC 10 side

So far the current logic is ok for images but would require the pre-signed URL approach for videos.

**Comment by PVince81** [comment]
@C0rby ^

**Comment by PVince81** [comment]
to clarify, we already have an implementation that uses the preview endpoint in the media viewer app, and the approach above is what I described, see:
- thumb path: https://github.com/owncloud/phoenix/blob/master/apps/media-viewer/src/Mediaviewer.vue#L181
- media source blob fetching and repacking as data URL: https://github.com/owncloud/phoenix/blob/master/src/plugins/mediaSource.js#L13

**Comment by PVince81** [comment]
similar topic happens for downloads: https://github.com/owncloud/phoenix/issues/526#issuecomment-534554638

for the scope of this sprint I suggest focusing only on bringing the same logic to the file list and its thumbnail retrieval.

later on we can look into pre-signed URL as part of https://github.com/owncloud/enterprise/issues/3912

**Comment by PVince81** [comment]
updated top post with some findings

**Comment by PVince81** [comment]
added tests but discovered some new issues:

- [ ] preview not loading directly after upload ?
- [ ] scrolling down then back up quicky sometimes removes the already loaded previews: maybe the elements are re-created or something and we need to requery the URL ? (svg appears there for icon type instead of the expected img from the previous load, makes acceptance tests fail)

**Comment by butonic** [comment]
server side merged with https://github.com/owncloud/ocis/pull/157

**Comment by PVince81** [comment]
PR for file previews in file list was merged: https://github.com/owncloud/phoenix/pull/3187

next up is adding a preview on top of the sidebar and solving the further points

**Comment by pascalwengerter** [comment]
We're now able to display thumbnails and do so for certain file types in the files list/table. There's also discussions about having larger previews in the sidebar or on a grid view, but that's a different story.

If further previews are needed please open a new ticket.

**Comment by phil-davis** [comment]
Note: the last entries in expected-failures linked to this issue are removed in PR https://github.com/owncloud/web/pull/5787
