### ISSUE TITLE
Test: Possible race condition

### ISSUE THREAD

**Issue by skshetry** [owncloud/web#2805]
We set some global variables in the `filesContext`: `timeOfLastDeleteOperation` and `timeOfLastUploadOperation`. 
https://github.com/owncloud/phoenix/blob/c0db320637bd38ea7deefd83c0775b40a6672856/tests/acceptance/stepDefinitions/filesContext.js#L11-L12

We are over-engineering here. I don't think we really need to track these things as we only need to wait for 1 second (and, they are only used at a single place + we only save ~300ms to be honest). But, this doesn't solve the problem, so, we need some way to prevent multiple deletion/upload operation or make it safer via some better design pattern.

Similarly, in `client.globals`, we change the state in [`runOnRemoteBackend`](https://github.com/owncloud/phoenix/blob/c0db320637bd38ea7deefd83c0775b40a6672856/tests/acceptance/helpers/backendHelper.js#L36).

There is the possibility of having race conditions when multiple functions run concurrently. I believe this could be a problem that's making "versions" related test flakey. It is too easy to step into your own feet and could be problematic in future (if it's not already).

We should also add `eslint` config rule `"require-atomic-updates": "error"` so that it is easily noticed in the future.

**Comment by skshetry** [comment]
Note: This is not that much of a priority. I created this issue, so, that everyone understands the possible problem with this(eg: someone might upload multiple files in serial and expect to have multiple versions, or probably forgot to even await, or run multiple API calls on both local and remote servers at the same time [or, without awaiting]).

**Comment by pascalwengerter** [comment]
@individual-it could you take a look here and closed if not applicable anymore?

**Comment by dpakach** [comment]
@individual-it I've removed the code to do the wait and add a simple 1 second wait for every upload/delete in https://github.com/owncloud/web/pull/5494
Do you think it's better that way as stated in this issue? otherwise  we can close this issue.

**Comment by individual-it** [comment]
Is this code used in every single upload? e.g. we are not using the skeleton folder much anymore, but uploading the files in `Given` steps. It would be a shame if every of those steps would take 1sec

**Comment by dpakach** [comment]
@individual-it In that case, the existing solution is fine. I'll close the PR and this issue too.
