### ISSUE TITLE
Markdown editor navigates back to root instead of last opened folder when closing

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#2882]
### Steps to reproduce
1. Navigate to a subfolder
2. Open a md file in markdown editor
3. Close markdown editor by clicking on "x" button

### Expected behaviour
The user should get navigated to the subfolder where the opened file is located.

### Actual behaviour
The user gets navigated into the root folder.

### Phoenix version
- 0.2.7-alpha1

**Comment by kulmann** [comment]
Closing in favour of duplicate ticket https://github.com/owncloud/web/issues/5928 (which has a tiny bit of more details)
