### ISSUE TITLE
Feedback on Links

### ISSUE THREAD

**Issue by pmaier1** [owncloud/web#2903]
- ~~[ ] When clicking a public link name, the public link opens in the current tab and you can hardly go back because of the redirect. => Should open in a new tab~~
- [ ] When clicking on a public link name for a password-protected link it doesn't work
![Screenshot from 2020-01-21 14-58-39](https://user-images.githubusercontent.com/21193500/72810806-a1f4f880-3c5e-11ea-9277-fcc134eb2d01.png)
- [ ] Expiration date picker changes height if you click through the months (at some point you need to move the mouse to change to the next month)
- ~~[ ] "Expires on" indicator only works for the current year. If you set an expiration date next year, the remaining time is calculated using the date in the current year instead of next year)~~
- ~~[ ] Usually link properties are displayed as text (role, expiration). Only the password-protection state is displayed using the link icon which is unintuitive.~~
- ~~[ ] The on-click visualization of the "copy to clipboard" button is too less visible. Maybe use checkmark as when copying a private link?~~

**Comment by kulmann** [comment]
* crossed out items moved to https://github.com/owncloud/phoenix/issues/1307
* error needs further investigation. not happening in a standard setup
* date picker has to be solved in the dependency. we'll have to look into making a PR there. postponed for now.

**Comment by pascalwengerter** [comment]
Closing this since passwords now work and we have enough other tickets for the datepicker and need to replace it to become fully a11y-compliant (see e.g. #2258) - we should tackle the `changes height if you click through the months` there.
