### ISSUE TITLE
Missing folder/path information in flat lists

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2925]
### Steps

1. Create a folder "test"
1. Mark it as favorite
1. Create a folder "sub/test"
1. Mark "sub/test" as favorite
1. Open the "Favorite" list

### Expected result
A way to distinguish the two "test" entries, like for example a column that displays the full path to the folders.

### Actual result
Two folders "test" appear and no way to know which one is which.

### Version
git master e0df137a74cd6a0a28a0b5d328abc65127fab364

@pmaier1

**Comment by PVince81** [comment]
also applies to other flat lists like "shared with me" and "shared with others"

**Comment by kulmann** [comment]
Closing in favour of more detailed https://github.com/owncloud/web/issues/5953
