### ISSUE TITLE
German wording of contributor role for public links

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#2934]
Wording issue raised by @pmaier1:
`The translation for the "Contributor" role ("Mitarbeiter") is bad as Collaborators would also translate to "Mitarbeiter". We should change it.`

Context is the file links sidebar for a folder. Has to be fixed in transifex, no code issue.

Moving this to a separate ticket, so that https://github.com/owncloud/phoenix/issues/1307 can be closed.

**Comment by PVince81** [comment]
and also "Zuhause" :wink: 

it's probably worth it going through the current translations and fixing whatever we find

**Comment by JanAckermann** [comment]
Seems to be fixed, closing:
![image](https://user-images.githubusercontent.com/26169327/200270562-8e6165b7-0a63-4df5-a6d8-44c341a7db92.png)

**Comment by kulmann** [comment]
Unfortunately not solved at all. This issue is about **public link** roles. See attached screenshots.

<img width="413" alt="Screenshot 2022-11-07 at 13 03 16" src="https://user-images.githubusercontent.com/3532843/200306703-4d66667d-2bdb-467e-8d21-9abdeb9ee6ec.png">
<img width="408" alt="Screenshot 2022-11-07 at 13 07 44" src="https://user-images.githubusercontent.com/3532843/200306709-eca94f81-2fa0-40fe-8a1d-cd1e52919ca7.png">

**Comment by JanAckermann** [comment]
Fixed 

![image](https://github.com/owncloud/web/assets/26169327/b9e80118-e852-4fe7-9005-6d06d3d3cf9b)
