### ISSUE TITLE
Roles select must be limited to disallow permission increases

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2963]
### Steps

1. Create three users "Alice", "Bob" and "Charlie"
1. Login as "Alice"
1. Create a folder "test"
1. Share "test" with "Bob" with the "Viewer" role, and allow re-sharing
1. Login as "Bob"
1. Share "test" with "Charlie" with "Editor" permissions

### Expected result
The roles dropdown should not allow selecting anything else than "Viewer".
Maybe if there's only a single entry, don't even show the dropdown and keep a single entry.
Maybe grey out the other entries in the dropdown so we know they exist but cannot be selected.

### Actual result
All entries are visible and can be selected.
Saving will leave the dialog with an error "Cannot set the requested share permissions for test".

Side note: when catching such error in general, the "add collaborator" dialog must not disappear!

### Version
v0.3.0

@kulmann FYI as we observed this during our recent work.

cc @pmaier1

**Comment by kulmann** [comment]
Wait with implementation until https://github.com/owncloud/web/pull/6039 is merged

**Comment by JanAckermann** [comment]
Resharing seems not to be allowed anymore, so is this still an issue?

![image](https://user-images.githubusercontent.com/26169327/168769593-7156f186-92e9-405e-b869-de22ff9cabd9.png)

**Comment by pascalwengerter** [comment]
> Resharing seems not to be allowed anymore, so is this still an issue?
> 
> ![image](https://user-images.githubusercontent.com/26169327/168769593-7156f186-92e9-405e-b869-de22ff9cabd9.png)

Yes, resharing is part of KoKo (ideally this week in oCIS)
