### ISSUE TITLE
PDF viewer shows document in tiny size

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2966]
### Steps

1. Upload a PDF file in Phoenix
1. Open it in the Phoenix PDF viewer

### Expected result
Properly display the page using the whole width.

### Actual result
Tiny size, like a scaling issue.
![image](https://user-images.githubusercontent.com/277525/73828852-48fe9600-4802-11ea-9321-0eaa9aa81ef3.png)

Also: seems there is some alignment issues in the toolbar.

### Version
v0.3.0

**Comment by LukasHirt** [comment]
Doesn't seem to scale it down for me (version 0.3.0).

![image](https://user-images.githubusercontent.com/25989331/74336695-1410b700-4d9f-11ea-8814-5b312760e7e8.png)

Still, the whole sizing in the pdf viewer is simply broken. Plus scrolling is not possible.
