### ISSUE TITLE
Always show notifications bell

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2968]
Regardless whether notifications are available or not, always display the bell.

When clicked, if no notifications, show a message in the dropdown that says so.

I guess we should still visually change the bell whenever notifications exist, like adding a small number ?

@pmaier1

**Comment by pascalwengerter** [comment]
@tbsbdr should we implement this?

**Comment by tbsbdr** [comment]
yes

**Comment by kulmann** [comment]
> yes

![spongebob-one-eternity-later](https://user-images.githubusercontent.com/3532843/219379035-c993a30c-d2f6-4965-ae8d-351a4f4b01f6.gif)

https://github.com/owncloud/web/pull/8450 😁
