### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/web#298]
[Feedback on central.owncloud.org](https://central.owncloud.org/t/issues-using-the-app-on-desk-and-ipad/16497) opened my eyes:

> Hi, I have try using own cloud from my browser on my iPad, then via the app.
> I’m using the app on my iPad, and I experience one or two issues.
> From the browser, I can’t select files, drag and drop them, or move them to another folder, either manually, or with a contextual menu.

Is there already touch and drag and drop supported in the stack we plan to use?

**Comment by tempelgogo** [comment]
Files are already sortable via (Drag&)Drop events.

This feature has been ported to support vuetify.

**Comment by pascalwengerter** [comment]
Closing this as outdated since drag&drop has been dropped in the meantime. We'll bring it back sometime soon and will do our best to make it usable on touchscreen devices
