### ISSUE TITLE
Overwrite file while version tab is open

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2984]
### Steps

1. Upload a file "test.txt"
1. Open the versions tab for it
1. Upload the same file again and overwrite

### Expected result
Versions tab updates itself with a new version

### Actual result
Versions tab stays empty, needs page refresh

### Version
v0.3.0

**Comment by LukasHirt** [comment]
This might be helpful in this context - https://github.com/owncloud/phoenix/issues/2573#issuecomment-580668497

**Comment by pascalwengerter** [comment]
Closed as fixed, can't reproduce
