### ISSUE TITLE
Move extensions into own repos

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#2991]
Currently, we have some extensions living directly in Phoenix. This leads us into a few not so ideal scenarios IMHO.

- We have two separated fields in the config for extensions and load logic needs to handle two separated locations
- We are bloating the core repo with configs for different parts
- We are not following what we are trying to bring with the whole microservices approach

I'd suggest moving extensions into their own repos where it would be easier to implement stuff like e.g. single binary as done with [ocis-hello](https://github.com/owncloud/ocis-hello) which we promote as an example extension. Also, the Phoenix core will then become really minimal and easy to maintain and we won't mix configs together.

What do you think @PVince81 @kulmann ?

**Comment by pascalwengerter** [comment]
Closing this as we're discussing moving even more stuff into `web` and then release it as separate NPM packages
