### ISSUE TITLE
Text and wording improvements

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2994]
- [ ] go through transifex to find inconsistencies
- [ ] use double quotes around file names / folders ? (make a decision in ODS about this)
- [ ] when to capitalize ? "Delete Share" vs "Delete share"
- [ ] get rid of "share" and use collaborators and links where possible ?
- note: having a single translate guarantees more consistency in wording
- dots vs no dots at the end of sentences
- [ ] merge "file" and "folder" into "resource" ?

@pmaier1 FYI

**Comment by PVince81** [comment]
- [ ] error messages consistency

**Comment by PVince81** [comment]
- [ ] check if we are escaping too much in some places ?

**Comment by PVince81** [comment]
- [ ] move away from using `$gettextInterpolate` and use the actual custom parameters https://github.com/Polyconseil/vue-gettext#custom-parameters
- [ ] check plural usage

**Comment by PVince81** [comment]
- [ ] do we use "you" / "me" or a neutral tone ?
- [ ] some wording starting with "There is ..." should be improved
- [ ] capitalization ? ex: "Save Collaborators" vs "Save collaborators"
- [ ] add translation annotations in code to specify whether the text is a shortened version or regular sentence. Useful to decide whether to use articles when translating or resorting to a short version.

**Comment by PVince81** [comment]
- [ ] items => resources ? (I find it hard to translate)

**Comment by PVince81** [comment]
@michaelstingl has similar work been done already for the clients regarding wording ? We might want to come up with general client-agnostic design guidelines

**Comment by JammingBen** [comment]
Closing as wordings changed quite heavily over the last few years, so there is no relevant action item anymore.
