### ISSUE TITLE
Access denied page appears for a short while after authorisation

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3029]
### Steps to reproduce
1. Authorise Phoenix with oauth2
2. Wait for redirection

### Expected behaviour
After redirection page files app should be directly visible.

### Actual behaviour
Access denied shows up for a brief moment and then the files app is visible.

**Phoenix version:** 0.3.0

**Comment by dschmidt** [comment]
![Screenshot_20220307_151349](https://user-images.githubusercontent.com/448487/157050740-32bc8e20-7eda-42df-ba20-0118c6b2bd56.png)

This is all I see and that seems totally legit.

I've tested against staging customer portal which is using oauth2 and it seems just fine.
