### ISSUE TITLE
Cannot rename after returning from trash bin

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3035]
### Steps

1. Create a folder "test" in the "All files" section
1. Go to trash bin
1. Go back to "All files"
1. Rename "test" to "test_renamed"

### Expected result
Renaming works

### Actual result
No dialog appears, JS errors:

![image](https://user-images.githubusercontent.com/277525/74511615-ac757b80-4f06-11ea-98d2-72ab20c196dc.png)

Workaround is to refresh the page.

### Version
0.3.0 and master

**Comment by kiranparajuli589** [comment]
@PVince81 Do we need to add acceptance tests???

**Comment by PVince81** [comment]
@kiranparajuli589 I'm not sure, this sounds a bit too specific

**Comment by pascalwengerter** [comment]
Can't reproduce on https://ocis.ocis-web.latest.owncloud.works
