### ISSUE TITLE
Improve visual focus management

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3046]
When tabbing through the Phoenix UI, the focus border is barely visible or sometimes completely absent.

On the other hand, the file list receives a colored border when focused by clicking with the mouse.

We should make these consistent.
Ideally the focus border should only be visible when tabbing with the keyboard, not the mouse (except for input fields and buttons maybe).

For this I found about distinction between mouse and keyboard:
- https://stackoverflow.com/questions/31402576/enable-focus-only-on-keyboard-use-or-tab-press
- focus-visible (needs polyfill): https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible
- more research visible

cc @marcus-herrmann @LukasHirt

**Comment by LukasHirt** [comment]
Refs https://github.com/owncloud/owncloud-design-system/issues/445

**Comment by LukasHirt** [comment]
Tips for tools from @marcus-herrmann

- https://github.com/ten1seven/what-input
- https://github.com/WICG/focus-visible polyfill for :focus-visible

**Comment by pascalwengerter** [comment]
Should have been fixed by the `a11y` improvements (at least for Chrome)
