### ISSUE TITLE
Pass locale into filesize

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3067]
The filesize js lib needs to receive a locale to use correct formatting. We already have a way to pass the locale in plain js with vue-gettext but unfortunately haven't got it reactive yet. As soon as we have the reactivity there as well, we need to pass it to each definition of filesize

**Comment by pascalwengerter** [comment]
@LukasHirt what's the DoD here? :)

**Comment by LukasHirt** [comment]
> what's the DoD here? :)

Updated the description
