### ISSUE TITLE
oidc-callback URL filling browser history

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3071]
I wonder if we should replace/rewrite history after processing the callback to avoid having its URL and its token stored in the browser history.

Needs some research to see if there are best practices there.

**Comment by pascalwengerter** [comment]
@kulmann @dschmidt have you touched this topic in your recent auth PR?

**Comment by dschmidt** [comment]
Not specifically, to some extent the oidc library should handle it (no idea if it actually does) or if there's more we can/should do. 
As I said, we did not look into this - verification if still necessary would be appreciated.
