### ISSUE TITLE
Placeholders for empty panels

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3119]
Whenever no collaborators, no public links, no versions, etc appear, instead of showing a boring message, we should add an icon with a less boring message and an optional call of action, similar to what we did in the file lists when they are empty.

- no collaborators => doesn't happen any more as we have the owner always displayed there
- [ ] no public links
- [ ] no versions
- [ ] other panels ?

**Comment by pascalwengerter** [comment]
@tbsbdr I'd be in favor of closing this issue, maybe you want to draw some inspiration from it when redesigning the sharing sidebar though? Or should we leave it open? 😉

**Comment by tbsbdr** [comment]
ah, thanks! nice idea, got it. maybe i'll find someplace in the new sharing dialog. closing to tidy up.
