### ISSUE TITLE
Collaborators column must stay up to date

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3138]
### Steps

1. Create folder "test"
1. Share "test" with other users
1. Go to "Shared with others" section
1. Open the share panel for "test"
1. Add another collaborator or remove one
1. Observe the "Collaborators" column after the change

### Expected result
Collaborators column automatically updated

### Actual result
No update

### Version
Phoenix v0.5.0

Likely due to the fact that the aggregated info is using a different model, or is not being automatically recomputed when the main model changes.

**Comment by PVince81** [comment]
This could either be tackled by having the actions commit to the various structures, or we can decide to first solve the issue that we are storing similar share information in different places first: https://github.com/owncloud/phoenix/issues/3172

**Comment by pascalwengerter** [comment]
Closed in favor of #5296
