### ISSUE TITLE
Disabled expiration date are handled differently in links and collaborator share

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#3168]
### Description
After #3086, expiration feature is on both links and collaborators share, but one thing to be noticed:
When using past dates or using enforced expiration dates, there are dates which cannot be set as new expiration date

**Inside collaborators share(core/phoenix):**
Such dates [year, month, day]  are disabled and can't be selected. (without any err msgs or popups)
![Screenshot from 2020-03-10 16-46-50](https://user-images.githubusercontent.com/39373750/76306356-d431e680-62ee-11ea-9394-d0263910186f.png)

**Inside links share(phoenix):**
Such dates can be selected but after selection, a error message is displayed as
![Screenshot from 2020-03-10 16-42-22](https://user-images.githubusercontent.com/39373750/76306223-9f259400-62ee-11ea-8e4a-33f5eaff2c85.png)

**Inside links share(core):**
Such dates are disabled and can't be selected. (without any err msgs or popups)
![Screenshot from 2020-03-10 16-49-09](https://user-images.githubusercontent.com/39373750/76306517-207d2680-62ef-11ea-9a16-9b800de7c19f.png)

### Steps to reproduce
1. Use enforced expiration date for collaborators/links shares
2. Try to set past-dates or dated beyond maximum expiration date

### Expected behaviour
Similar handling mechanism

### Actual behaviour
Different techniques used  in link shares and collaboration share in phoenix

### Server configuration
latest core master
latest phoenix master

**Comment by PVince81** [comment]
@pmaier1 @LukasHirt

**Comment by pascalwengerter** [comment]
Seems like this has been long fixed
