### ISSUE TITLE
Single state location for all file shares

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3172]
Currently, and due to some optimizations, we opted for having share information stored in various different formats:

- shares array related to the currently highlighted resource only, to be used by the collaborator/link panel: `currentFileOutgoingCollaborators`, `currentFileOutgoingLinks`
- list of shares for arbitrary paths, used for knowing about indirect shares for all the parents of the currently viewed folder: `sharesTree`
- aggregated list of shares to populate the "Collaborators" column of the "shared with others" page: see `_aggregateFileShares`

Having all these separate information makes it difficult to keep them in sync and have the UI react properly on changes, like for example https://github.com/owncloud/phoenix/issues/3138

We should try and design a single shares structure that is the one authority for the list of shares for any file. To avoid having too much information in place, it should work like a cache.
Then each view can pick up whatever information from there and aggregate as needed within the matching Vue.
And every change needs to be committed back to that single share structure, this way all changes can bubble up to the proper Vues automatically by using Vue's natural reactivity.

@LukasHirt @kulmann FYI

**Comment by PVince81** [comment]
In some code paths, we might not receive the full share informations, so many the state can have a "partial" mode in which case only pieces of information are there. One notable example is the "share types" list (array of ints) that we receive from Webdav for the "All files list" without having to query the OCS Share API for every single item. This is just a shortcut.

**Comment by JammingBen** [comment]
Closing has this has been refactored quite some time ago.
