### ISSUE TITLE
user and group expiration dates do influence each-other

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#3174]
### Steps to reproduce

1. Enable `shareapi_enforce_expire_date_group_share` and `shareapi_enforce_expire_date_user_share`
```sh
sudo -u www-data ./occ config:app:set core shareapi_enforce_expire_date_user_share --value=true
sudo -u www-data ./occ config:app:set core shareapi_enforce_expire_date_group_share --value=true
```
2. Set different default expiration for user and groups
- `shareapi_expire_after_n_days_group_share` to say `10`
-  `shareapi_expire_after_n_days_user_share` to say `20`
3. Create a user `user0` and a group `grp1`, add the user to the group
4. Now try to create a collaborator share

### Expected behaviour
Sharing using collaborator `user0` should provide expiration days options **20** days beyond current day

### Actual behaviour
Sharing using collaborator `user0`, expiration days options for only **10** days beyond current day
![Screenshot from 2020-03-12 11-35-35](https://user-images.githubusercontent.com/39373750/76491404-af0bb800-6455-11ea-8cb0-14c2dac99882.png)

**Note**
- _Sharing using group as collaborators works fine (expiry dates are enabled/disabled as per settings)_
- _Sharing using user as collaborators works fine (expiry dates are enabled/disabled as per settings) **when editing the created share**_

### Server configuration
latest **phoenix** master
latest **core** master

**Comment by kiranparajuli589** [comment]
issue reproduced in #3159 

https://github.com/owncloud/phoenix/blob/f9064306d7eedca965c8944d0210c1b9cb585efc/tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature#L677-L700

**Comment by kulmann** [comment]
Has been fixed in https://github.com/owncloud/web/commit/926bc0b1e6f5186a26a94a6469303dcc6a46b1e9#diff-5ad2af1f8df798d6259a745bdf05f36c38e58167266762e91092319177ed793aR90
