### ISSUE TITLE
Collaborators column remote user is too long

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3175]
### Steps

1. Create a federated share with "admin@http://host.domain/..." (pick a valid instance)
1. Go to "shared with others" and look at the Collaborators column

### Expected result
Remote share appears in collaborators list with proper icon and "Admin".

### Actual result
Remote share appears with an information icon and has the full URL.
Also, there seems to be a bogus colon in front of the entry.

![image](https://user-images.githubusercontent.com/277525/76603261-f5701e00-650c-11ea-97e8-ac7f28469bd3.png)

### Version
Phoenix master e0415bb42f515aa928cedd384d4ab7fb004c3b47

**Comment by pascalwengerter** [comment]
Solved a while ago by only showing an avatar group with a tooltip
