### ISSUE TITLE
Collaborators column group names repeated

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3177]
### Steps

1. Recreate the sharing scenario from the screenshot
1. Go to "shared with others"

### Expected
Collaborators list shows admin group once, davegroup ones and the other collaborators.

### Actual
![image](https://user-images.githubusercontent.com/277525/76609311-79c79e80-6517-11ea-8710-f42a2c682f10.png)

### Versions
Phoenix master e0415bb42f515aa928cedd384d4ab7fb004c3b47

**Comment by pascalwengerter** [comment]
Can't reproduce, closing this for now
