### ISSUE TITLE
Federation: Show pending remote shares in "shared with me" section

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3178]
Same as https://github.com/owncloud/core/pull/37022

Use the endpoint https://github.com/owncloud/core/pull/37022/files#diff-967a08ad256ad17ff0294efede3bff41R247 to retrieve all federated shares, including the pending ones.

As far as I can see, the incoming federated shares are not displayed at all in "shared with me", so we'll be implementing this from scratch.

@pmaier1 FYI (we can link this back to user stories later)

**Comment by mcarioscio-ownCloud** [comment]
I cannot see any Federated shares in the "Shared with me" section: 
https://github.com/owncloud/web/issues/2510
could this be a part of the pending remote shares issue?

**Comment by JammingBen** [comment]
Closing here since this topic will be re-evaluated completely. Currently when using OCM shares will be listed on the "Shared with me" page. You can use a filter to explicitly search for this as well.
