### ISSUE TITLE
Don't reload folder after create action

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3184]
After creating the resource the reload is triggered. This leads to extra network calls and extends the time needed to wait when confirming rename. We need to drop this and adjust the state without doing the network call.

**Comment by PVince81** [comment]
I think the same happens for folder creation, please have a look at this as well.

We should also make sure to scroll to the newly added / renamed item as it might fall outside the view due to sorting. I believe we already have a function that achieves the "scroll into view" part.

**Comment by pascalwengerter** [comment]
Shouldn't be the case anymore on current master with the new files table etc @LukasHirt ?

**Comment by kulmann** [comment]
Correct, we don't reload the various file lists anymore. That caused us some other headache, but meanwhile fixed. ;-) Closing here.
