### ISSUE TITLE
[Tests Only] Use value from await rather then setting in the callbacks

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#3253]
With new update in nightwatch js we must be able to get the return values using await in the nightwatch builtin functions rather than setting the value in callback functions as we do currently. 
In order to improve the test code we need to replace such callbacks with async-await.

Nightwatch  Update PR - https://github.com/owncloud/phoenix/pull/2931

_Originally posted by @PVince81 in https://github.com/owncloud/phoenix/pull/2931#issuecomment-602584470_

**Comment by PVince81** [comment]
In general I suggest to not go ahead and change all occurrences. We can consider this tech debt, so we only add `await` for parts of the code that we need to touch as part of other tasks.

Does that make sense @dpakach ?

**Comment by dpakach** [comment]
> Does that make sense @dpakach ?

@PVince81, Yes definitely does. In fact making all changes will be a really big refactor so we can do it small part at a time whenever we need to.

**Comment by SwikritiT** [comment]
For this we will need to upgrade nightwatch but since we've decided that we won't be making any new changes to nightwatch test code so this issue is obsolete. Hence I'm closing it.
