### ISSUE TITLE
Rounding of share expiry dates

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#3272]
### Steps to reproduce
1. Share a resource with some expiry date in the future (e.g. 14 days away)
2. In the morning, look at the UI expiry text - "Expires in 15 days"
3. In the afternoon, look at the UI expiry text - "Expires in 14 days"

### Expected behaviour
Be consistent. In  the example, always report "Expires in 14 days" if the expiry is 14 to 14.99 days ahead of now.

### Actual behaviour
The number of days are different depending on morning/afternoon viewing time.
This might be a bit unexpected if the user knows, for example, that the expiration policy is 14 days and then they see "Expires in 15 days".
It is also a bit painful for automated testing - depending on when the test is run (morning or evening) the text displayed on the UI is different.

### Server configuration
Current phoenix repo.

Probably just needs `apps/files/src/mixins.js`
```
    formDateFromNow (date) {
      return moment(date).locale(this.$language.current).fromNow()
    },
```
To add another method like `formDateFromToday(date)` that uses the day-only of the date passed in, and the day-only of "now" to calculate the `moment`. That should avoid some "odd" transition at midday - the transition from "in 14 days" to "in 13 days" will happen at midnight.

Then use `formDateFromToday` when displaying public-link/user/group share expiration.

**Comment by phil-davis** [comment]
Noticed this in PR #3199

**Comment by PVince81** [comment]
I always wonder whether we should also add the hours there, or maybe only add them while we reach 1-2 days. Or add the exact time in a tooltip or something.

As as user I'd expect the time to be based on midnight, but not sure which timezone. The timezone of share creation ? Or UTC ? As far as I remember in OC 10 it would be UTC, so people in non-UTC timezone would get expiry at less expected time.

@pmaier1 @LukasHirt thoughts ?

**Comment by phil-davis** [comment]
`formDateFromNow` works out "appropriate" text to put - when it is months away it will say some number of months and so on. IMO when it gets closer it will start telling hours all by itself.

**Comment by pmaier1** [comment]
> formDateFromNow works out "appropriate" text to put - when it is months away it will say some number of months and so on. IMO when it gets closer it will start telling hours all by itself.

Using this sounds great, I think :+1: Midnight would be the expectation, yes. In the best case we could use the server time zone to make expiration more predictable and understandable for users.

**Comment by kulmann** [comment]
One thing to consider here, is that we have to set the locale on `moment`, so that `formDateFromNow` is displayed in the correct language.
https://momentjs.com/docs/#/i18n/

**Comment by jnweiger** [comment]
Can we add a mouse over to the "Expires in 14 Days message" that has the exact date, including timestamp and timezone?
That way it look clean, but the exact information is also available. (Maybe rounding issues become less important then)

Idea stolen from github:
![image](https://user-images.githubusercontent.com/1108546/125066250-0f931f80-e0b3-11eb-8017-992e8efa89ca.png)

**Comment by kulmann** [comment]
Fixed by https://github.com/owncloud/web/pull/6037
