### ISSUE TITLE
Tedious to open files in apps

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#3299]
It's tedious always having to select the app, when opening an image or a pdf file for example.

### Steps to reproduce
1. Click a file
2. App selection bar opens where you have to select the app every time

### Expected behaviour
At least for me looking at a file (preview) is the more common case than actually downloading it.
So when clicking the file and there's only one app for this file type I would expect the app to just open it instead of offering me to download it. Download could be added to context menu for my taste and for the mediaviewer in particular, there's already a download button when previewing the image.

**Comment by DeepDiver1975** [comment]
It was an explicit design decision to not have any default behavior for clicking a file.
In oc10 there are enough cases where this just exploded in the past years.
e.g. an office doc which can be opened in collabora, only office and office 365 - still an unsolved issue in oc10 :see_no_evil: 

phoenix addresses this by not having a default action for files (folders -> opens it)

**Comment by DeepDiver1975** [comment]
^ just an explanation about the WHY - up to the team to change this behavior for sure

**Comment by dschmidt** [comment]
Yeah, I'm sure there were reasons for it and that's why I opened an issue, instead of sending a trivial PR just changing the behavior. 

Just wanted to document my impression when first playing around with phoenix. I talked to @kulmann about this the other day and he as well thought this didn't feel optimal.

**Comment by PVince81** [comment]
I think we had a ticket somewhere to revisit this behavior.

cc @pmaier1

**Comment by kulmann** [comment]
The main question here is whether or not downloading a file should be considered a "main action" along with opening it in mediaviewer etc. In my opinion the download should be in the three dots menu only. Then if there is only one app for the file extension available we should open the file in that app directly, without showing the prompt. But again, this really depends on where we want to make the download available.

**Comment by pmaier1** [comment]
> In my opinion the download should be in the three dots menu only.

Yep, I agree. This is also how other products handle it - viewers/players in the browser always have priority over download. Additionally users can trigger a download from within the preview as in the Media Viewer.

> Then if there is only one app for the file extension available we should open the file in that app directly, without showing the prompt.

Yep. If there's only one viewer available, we should use that one. If there's multiple, we should use the menu and allow users to make their choice.

**Comment by pascalwengerter** [comment]
Closing this in favor of #5160 where dealing with the various "Open with" should be handled (plus we now have a contextmenu for quicker access and a details panel for better previews)
