### ISSUE TITLE
 mediaviewer: Images can't be added to favorites

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#3300]
### Steps to reproduce
1. Open an image in mediaviewer

### Expected behaviour
Personally I would like to have a star to add an image to my favorites or remove it again.

### Actual behaviour
There's no way to add a file to the favorites from mediaviewer

I can probably do it, just wanted to check it's actually desired.

### Things to keep in mind
Looking at the favorites folder and removing favorites from there might (or might not) need special handling.

**Comment by PVince81** [comment]
@pmaier1 let's make a story for this ?

would be useful when triaging pictures.

however I wonder if favorite is the right action as favorite is a general list of all favorites
tagging might be a better option, but we don't have this yet

**Comment by JanAckermann** [comment]
will be solved in https://github.com/owncloud/web/issues/9491
