### ISSUE TITLE
Gallery view with thumbnails

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3341]
Improve the media viewer by providing a gallery view like the [old gallery app](https://github.com/owncloud/gallery) had.

This requires a new extension point to allow an app to provide its own file list view: https://github.com/owncloud/phoenix/issues/2585

**Comment by PVince81** [comment]
Could use something like https://github.com/parys-github/vue-masonry-gallery for display, but this is more designed for pictures, not really file thumbnails.

**Comment by kulmann** [comment]
uikit also has masonry support in their grid component: https://getuikit.com/docs/grid#masonry

**Comment by pascalwengerter** [comment]
@tbsbdr needs product decision and prioritization if applicable

**Comment by kulmann** [comment]
Currently prioritized for after the first spaces features. Could be possible to have it for the oCIS GA, but might also be a little bit later. Might get prioritized higher, because it's a quite important feature...

**Comment by kulmann** [comment]
More recent ticket with much more details and mockups is https://github.com/owncloud/web/issues/6126 - closing here.
