### ISSUE TITLE
Make requests to generic URLs from Phoenix

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#3344]
All endpoint calls made in phoenix are passed through the [requests.ocs](https://github.com/owncloud/owncloud-sdk/blob/2f6441b5f617564f590fa1c3e4f041849ef07ef2/src/helperFunctions.js#L523) method which sets the authorization headers. The issue with this is that it hardcodes the prefix with the OCS route, and we need to make requests to other services hosted along with phoenix. Specifically, we need to make calls to the OCM service hosted along with phoenix using [reva](https://github.com/cs3org/reva).

So this is a request to define a generic request handler in the owncloud-sdk repo, capable of redirection to other services.

**Comment by PVince81** [comment]
With "All endpoints" I guess you mean all share related calls ?
The file management calls are not going through the OCS API.

I guess you mean something like https://github.com/owncloud/owncloud-sdk/blob/master/src/shareManagement.js#L117 ?

I'm also guessing that you might mean that the OCS service for creating local shares and OCS service for creating federated shares are located on a different domains ?

Maybe in owncloud-sdk the shareManagement could have a check that if a remote call is needed, then use a new method `this.helpers._makeOCMrequest()` ?

and then have those endpoints configurable somehow in the SDK

**Comment by diocas** [comment]
This no longer seems relevant? Feel free to re-open @ishank011
