### ISSUE TITLE
Breadcrumb appears as dropdown even with only a single element

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3467]
### Steps

1. Open Phoenix on a mobile phone, with a resolution that has the breadcrumb collapsed into a dropdown looking element
1. Navigate / stay in home folder

### Expected result

No dropdown arrow, only "Home" displayed.

### Actual result

"Home" appears with a dropdown arrow and gives the impression that one can tap it, but tapping does nothing since there are no further elements.

### Version
Phoenix git master 6dd48ebc5d93e02a83514e161573f2f41d557582

Might need fixing in ODS

@LukasHirt

**Comment by pascalwengerter** [comment]
Closing this in favor of https://github.com/owncloud/owncloud-design-system/issues/809
