### ISSUE TITLE
Swipe gestures to open/close sidebar

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3468]
Follow up on #3442

On smaller screens where the sidebar can be closed/opened would be nice to have swipe gestures for those actions to make it easier for users. However, this needs to be thought through since on iOS there are swipe gestures which could fight with those (e. g. going back/forward in history)

**Comment by pascalwengerter** [comment]
Closing since mobile view is not in the focus currently. We can take another look and create a more actionable ticket down the road
