### ISSUE TITLE
Change icon of `shared with others` in files app

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#3469]
### Expected behaviour
We should not have duplicate icons in the sidebar.

### Actual behaviour
The files app sidebar shows the same icon for `shared with me` and `shared with others`.

The current mockups already have a different icon for `shared with others`, so we should adopt that.

![Screenshot 2020-05-15 at 12 56 39](https://user-images.githubusercontent.com/3532843/82043270-96b15700-96ab-11ea-954b-d0390779f7e3.png)

**Comment by LukasHirt** [comment]
Icons have been changed

![Screenshot 2021-01-05 at 21 00 11](https://user-images.githubusercontent.com/25989331/103693075-05c02080-4f99-11eb-94b0-78fe63a173f6.png)
