### ISSUE TITLE
Avatar in topbar is cropped in Safari

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#3476]
### Steps to reproduce
1. Open phoenix in Safari on macOS.

### Expected behaviour
Personal avatar in the top right of the screen should not be cropped.

### Actual behaviour
Avatar is cropped.

### Server configuration
phoenix.owncloud.com

### Client configuration
**Browser:** Safari 13.1 (15609.1.20.111.8)

**Operating system:** macOS Catalina 10.15.4

### Screenshot
![Screenshot 2020-05-18 at 09 28 34](https://user-images.githubusercontent.com/3532843/82292009-4c312280-99aa-11ea-897a-27759bc8b925.png)

**Comment by kulmann** [comment]
@davitol thanks for reporting this!

**Comment by pascalwengerter** [comment]
Can't reproduce with current web version, Safari 14.1 and macOS Big Sur 11.3.1
