### ISSUE TITLE
Tag the docker image releases to mirror the repo's

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/web#3481]
While building the Phoenix chart for https://github.com/owncloud/helm-charts, I've seen `latest` is the only tag on https://hub.docker.com/r/owncloud/phoenix/tags - but there are proper tagged releases in here (https://github.com/owncloud/phoenix/releases). It might be a good idea to keep them mirrored for upgrades/rollbacks, etc. 

What do you think?

**Comment by PVince81** [comment]
@micbar something for more automation ?

**Comment by LukasHirt** [comment]
Every tag now creates also a tagged docker image https://hub.docker.com/r/owncloud/web/tags?page=1&ordering=last_updated
