### ISSUE TITLE
Enable accessibility tests in CI

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3495]
There already exists script `accessibility-tests-drone` but it is not being run in the CI. It needs to be enabled again.

**Comment by LukasHirt** [comment]
It seems that axe-core just checks the page but doesn't do any actions so I am not sure how to handle authorisation in such a case. /cc @michaelstingl

**Comment by pascalwengerter** [comment]
Closing here since the collaborators as well as the mentioned approach/scripts/technology are outdated. I'll open a new issue since the general issue remains relelvant
