### ISSUE TITLE
Provide undo option when deleting files in files list 

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3578]
After #3577 it would be great if we'd have an undo option. It could be e.g. a link button in the alert. Of course `control + z` would be awesome but not sure if needed 🤷 

Not sure though if this should be available if the trashbin is disabled. That might prove expensive on the technical side.

**Comment by JanAckermann** [comment]
Closing after clear definition by @tbsbdr https://github.com/owncloud/web/issues/5974
