### ISSUE TITLE
Confusion between quick actions and indicators

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3580]
Possible approaches:
- Merge indicators with quick actions
- Indicators displayed under the file name

**Comment by pascalwengerter** [comment]
I suppose they're more easy to keep apart now that we've redesigned them, they also feature tooltips that start with "Show ..." for _indicators_ and "Copy/Add ..." for _actions_. Closing as resolved, awaiting further user feedback

![Screenshot 2022-05-05 at 17-26-26 Personal - ownCloud](https://user-images.githubusercontent.com/16822008/166957762-5db23041-b45f-46cd-be2c-96647e61a2f6.png)
