### ISSUE TITLE
Media viewer video subtitles

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3591]
Once we have a video player in place: https://github.com/owncloud/phoenix/issues/2051

I discovered today that it is possible to add subtitles withe the HTML5 video standard: http://html5doctor.com/video-subtitling-and-webvtt/

It requires a separate "WebVTT" file and additional `<track>` elements each for each language.

So in the future, if the media viewer detects such file in the folder that has the same name as the video, it could point to that (using the download URL / pre-signed URL).

For other videos where the subtitles are embedded or in another format, it would require a separate service that first converts those to WebVTT (on the fly?) and makes them accessible through some endpoint which we can refer to in the `<track>` element.

**Comment by JanAckermann** [comment]
We've renamed the media viewer to preview. We decided to do so as the app is not meant to be a full media viewer with all the features we know as of today, rather it has a very limited feature set. 

Hopefully a full media viewer will be introduced soon. 

But closing now as this is not in scope of preview app.
