### ISSUE TITLE
Speed Up CI

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#3600]
### Need to speed ui the CI
The CI steps to setup the test environment takes a lot of time just to start the acceptance tests.
If we can optimize those steps somehow that would be very helpful in making the CI faster.
Especially now that we run the tests with openIdconnect login, we need several ocis services to set it up and it takes time to build each services.
Some options to explore would be
1. Investigate if we can build once and use the build product in all other pipelines.
2. Run the services with docker (if we dont want to use the latest versions of the services)
3. Run only smoke tests with openIdConnect and rest with oauth (that save few minutes per pipeline)
       (edit: Only for tests that run with OC10 backend)
4. Improve the phoenix build process (https://github.com/owncloud/phoenix/issues/2884)

**Comment by kulmann** [comment]
Option 3 won't work, because we use the account uuid of the authenticated user for ocis-settings (and probably other services in the future). That account uuid comes from ocis-proxy and only works when authenticated through OIDC.

**Comment by dpakach** [comment]
> Option 3 won't work, because we use the account uuid of the authenticated user for ocis-settings (and probably other services in the future). That account uuid comes from a middleware in ocis-proxy and only works when authenticated through OIDC.

@kulmann I am talking about the tests that run with OC10 backend. Sorry for not making it clear.

**Comment by LukasHirt** [comment]
What about running acceptance tests in a single pipeline instead of a pipeline for each feature? Then there could be one pipeline for oCIS, one for oC10. Would be nice not to have to build server for every feature.

**Comment by dpakach** [comment]
> What about running acceptance tests in a single pipeline instead of a pipeline for each feature? Then there could be one pipeline for oCIS, one for oC10. Would be nice not to have to build server for every feature.

@LukasHirt that would be a good idea but we have too many tests that we will end up having one pipeline that takes a lot of time to finish. That would take even longer than what it takes now. So proper solution would be a way to share files across the pipelines.

**Comment by dpakach** [comment]
Most of the things are already done. so closing this.
