### ISSUE TITLE
Complete the acceptance test setup with proxy

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#3601]
The setup we use to run acceptance test in CI is actually not complete. We need to run the ocis-proxy service on top of the konnectd, glauth and phoenix to complete the setup in the CI.

**Comment by micbar** [comment]
Partly done with https://github.com/owncloud/ocis/pull/334/

## Needs cleanup

- API tests still pointing to the backend without the proxy (preview issues)
- Maybe use a valid cert to get rid of https://github.com/owncloud/ocis/pull/334/files#diff-74dc60589e0610c07e491b31f8693b2bR223

**Comment by dpakach** [comment]
Maybe before moving forward with this, we will need to address another issue in glauth
https://github.com/owncloud/ocis-glauth/issues/21
@micbar

**Comment by micbar** [comment]
@dpakach THX

Do you have an idea about the cert?

**Comment by dpakach** [comment]
@micbar for that we need to create certificates valid for all the hosts we run different ocis services in and also sign them with a trusted authority. 
I created an issue in ocis about that (https://github.com/owncloud/ocis/issues/301) to see if that can be one option.
But I guess we can also somehow add our certificate as a trusted authority in the containers before running the service.

**Comment by wkloucek** [comment]
@dpakach can this be closed?

**Comment by dpakach** [comment]
@wkloucek I'm not sure, I think we will need to fix the setup to use a standard setup of ocis-web with owncloud10. We currently use the ocis-web with ocis-glauth and ocis-konnectd, But there may be a better way to do it, making it work together with ocis-proxy.

We will at least remove this line
https://github.com/owncloud/web/blob/master/.drone.star#L1251

**Comment by wkloucek** [comment]
> @wkloucek I'm not sure, I think we will need to fix the setup to use a standard setup of ocis-web with owncloud10. We currently use the ocis-web with ocis-glauth and ocis-konnectd, But there may be a better way to do it, making it work together with ocis-proxy.
> 
> We will at least remove this line
> https://github.com/owncloud/web/blob/master/.drone.star#L1251

Oh sorry I came here via a similar Issue and thought this is still the ocis/ocis repository.
But this definitely looks open. Actually glauth is built from abandoned source code.

Is https://github.com/owncloud/ocis-glauth/issues/21 still the blocker here? Because this should work like done here:https://github.com/owncloud/ocis/tree/master/deployments/examples/owncloud10_with_oc_web

**Comment by pascalwengerter** [comment]
Any updates on this @dpakach @wkloucek ? :)

**Comment by phil-davis** [comment]
I added this to the QA Backlog project so that it will get noticed. @dpakach feel free to close if there is nothing left to do.

**Comment by dpakach** [comment]
This issue was relevant when we were running web acceptance tests with openid setup, since we dont do that anymore, we can close this.
