### ISSUE TITLE
Check all button texts for correct upper-/lowercase texts

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#3616]
Important to check before we release the new button style from https://github.com/owncloud/owncloud-design-system/pull/791

Previously, button texts were capitalized. The new button style is not capitalized anymore. Looks much better, but we have to double check that all button texts in Phoenix are correct regarding upper-/lowercase (e.g. check if there are buttons that start with a lowercase letter, which would be wrong).

**Comment by kulmann** [comment]
@pmaier1 @LukasHirt Do we have a common understanding of how button texts should be written out? My personal preference is to start with a capital letter and then write everything else like it would be in a normal sentence. There are voices out there which state, that buttons should have every word starting with an uppercase letter. I'm not a fan of that.
E.g. "Close and comment" vs "Close And Comment". I would prefer "Close and comment".

**Comment by LukasHirt** [comment]
I would also vote for only starting with the capital letter.

**Comment by pmaier1** [comment]
> Do we have a common understanding of how button texts should be written out? My personal preference is to start with a capital letter and then write everything else like it would be in a normal sentence.

I'm not aware of any 'official guidelines' we have for this but I agree a lot with your preference and would just decide to do it like this :+1:

**Comment by pascalwengerter** [comment]
Closing this as fixed within the `a11y` efforts, I do have extracted your opinions and will publish them in a `conventions` file I'm sourcing right now for this repo
