### ISSUE TITLE
CI doesn't work with current glauth version 

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#3655]
The Phoenix CI has been failing since https://github.com/owncloud/ocis-glauth/pull/19/files
A bunch of configuration has changed in Glauth so its connection to the owncloud service in the CI is currently broken.

Need to investigate how to reconfigure Glauth to talk with the owncloud and the openIdConnect service and fix the test in CI.

**Comment by individual-it** [comment]
CC @butonic

**Comment by dpakach** [comment]
Looks like the backend server option was removed from the config
```
Incorrect Usage: flag provided but not defined: -backend-server
```
But When I run locally even log-level option is not available even when it is still in the available configs.
```
Incorrect Usage. flag provided but not defined: -log-level
```

**Comment by dpakach** [comment]
Blocked by https://github.com/owncloud/ocis-glauth/issues/21

**Comment by pascalwengerter** [comment]
@individual-it can this be closed now? :)

**Comment by individual-it** [comment]
CC @dpakach ?

**Comment by dpakach** [comment]
We run CI setup with oauth now so can be closed.
