### ISSUE TITLE
Spinner appears below file list row

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3682]
### Steps

1. Upload a file
1. Download said file and observe the file row

### Expected result
No visual shifting

### Actual result
The spinner appears below the file row.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/277525/85982462-27d35780-b9e6-11ea-8038-faed862a9697.png">

### Version
Phoenix 0.11.0

@LukasHirt FYI

**Comment by pascalwengerter** [comment]
@PVince81 can't reproduce this one (Firefox 86.0), could you check if this still happens to you? And if so, more details for reproduction, please :)

**Comment by kulmann** [comment]
This is not reproducible anymore.
