### ISSUE TITLE
"New" button weight too big behind the breadcrumbs

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3683]
### Steps to reproduce

1. Create a folder "test"
1. Enter that folder
1. Look at the breadcrumb bar

### Expected

Ability to comfortably look at the breadcrumb

### Actual

Feel awkward trying to look at the breadcrumb while the "New" button is trying to get your attention by making itself look big.
Its visual weight is too high compared to the breadcrumb, needs a better balance.
Maybe some extra spacing ?

<img width="149" alt="image" src="https://user-images.githubusercontent.com/277525/85982735-9d3f2800-b9e6-11ea-916b-0f914c35ff9e.png">

### Version
Phoenix 0.11.0

@LukasHirt FYI

**Comment by LukasHirt** [comment]
New button is now on the second row.
