### ISSUE TITLE
Jumpy breadcrumbs while loading

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3694]
### Steps to reproduce

1. Have a slow enough environment where loading folder contents takes a few seconds
1. Create a folder "test"
1. Enter the folder "test"
1. While the folder is loading, move the mouse on top of "New", intending to create or upload as soon as the folder is loaded
1. Once the folder is loaded, click

### Expected result
The breadcrumb should already show "test" while loading.
The "New" button should not move once loading is done.

### Actual result
The breadcrumb is still showing the root folder during load progress and "New" is directly behind it.
As soon as the folder is loaded, the "New" button jumps to the right, so you cannot click in place on the button even though you were prepared.

### Version
Phoenix 0.11.1

@LukasHirt FYI

**Comment by pascalwengerter** [comment]
Can't reproduce anymore, files table gets loaded asynchronous and breadcrumbs + "New" button stay fixed/don't jump
