### ISSUE TITLE
Remove loadConfig on extensions

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#3726]
At the moment we run a `loadConfig` action on external extensions, which is required in vuex-stores of all ocis-web extensions. It looks like it is obsolete now and could be removed. After that it could be removed from external extensions as well. We need to check if it is unused (afaik it is).

Loading config of external extensions happens here and is probably obsolete:
https://github.com/owncloud/phoenix/blob/f9a0874dc016ee0269c698914ef3f2c75ce3e2e6/src/store/apps.js#L52

`loadConfig` action in a vuex-store of an external extension (example):
https://github.com/owncloud/ocis-hello/blob/818b83724f54f1ba8b4bfb34e766f42c2942a69d/ui/store.js#L17

**Comment by pascalwengerter** [comment]
@kulmann could you check if this can be closed since @fschade refactored the runtime boot logic quite heavily?

**Comment by kulmann** [comment]
@pascalwengerter yes, he removed it (which is good) and now it can be removed in ocis/accounts, ocis/settings and ocis-hello. Do you want to take care or should I?

**Comment by pascalwengerter** [comment]
> @pascalwengerter yes, he removed it (which is good) and now it can be removed in ocis/accounts, ocis/settings and ocis-hello. Do you want to take care or should I?

Let me take a look later this week 💪🏽

**Comment by kulmann** [comment]
Afaik no, thank you for keeping track of it... and of course for fixing it 😇
