### ISSUE TITLE
Utilize breadcrumb for actions

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#3727]
As pointed out by @refs in an [issue comment](https://github.com/owncloud/phoenix/issues/3722#issuecomment-652833791) we could utilize the last segment of the breadcrumbs (i.e. the currently active folder) for offering context aware actions (e.g. create / upload file, ...)

Opening this new issue to track that idea.
Pro:
- button could be removed - one less element cluttering the view
- makes it inherently clear that the offered actions affect the context = current folder

Con:
- one needs to know that the breadcrumb segment is usable as a button (could be solved with clever styling...)
- big con: in responsive mode the breadcrumbs are already a dropdown, so we can't utilize the last breadcrumb segment for another dropdown (for actions). Could be solved by having one dropdown with a) breadcrumb segments b) horizontal separator line or something c) list of actions for the current folder

Unclear:
- accessibility implications? proper aria-labels would probably make this understandable
- is this still an option worth considering, if we decide for a universal / reusable primary action button in the top bar?

Needs brainstorming. @LukasHirt @micbar

This is what google does:
![86328925-c4dffb80-bc45-11ea-8911-b79d9f72f537](https://user-images.githubusercontent.com/3532843/86397214-b45e6e00-bca3-11ea-8793-589dbcb0242b.png)

**Comment by ChrisEdS** [comment]
Yeah, I like that approach. 👍

**Comment by kulmann** [comment]
Closing in favor of more recent https://github.com/owncloud/web/issues/6030
