### ISSUE TITLE
Check skiponocis tags

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3737]
Like for API tests, we should check what acceptance tests are disabled in Phoenix and raise tickets accordingly.

@micbar FYI

**Comment by PVince81** [comment]
also: wondering if we have new OC 10 UI test scenarios that need to be synced / added to Phoenix ? or did we do this systematically ? @individual-it

**Comment by individual-it** [comment]
@phil-davis @swoichha is this still applicable? AFAIK we now run all the tests and have the accepted-failure file?
closing?

**Comment by phil-davis** [comment]
Done
