### ISSUE TITLE
Improve usability of *Shared with* info text.

### ISSUE THREAD

**Issue by labkode** [owncloud/web#3742]
If the file hasn't been shared why to show this text in the fist place? Absence is meaning.

![Screenshot 2020-07-07 at 17 01 44](https://user-images.githubusercontent.com/5175912/86800966-d7a66600-c073-11ea-85aa-2667e636b99c.png)

When the file is shared with a named collaborator, is much more accesible to have her name direclty visible.
The icon could be used as a fallback when there multiple shares and there isn't enough space.

![Screenshot 2020-07-07 at 17 02 29](https://user-images.githubusercontent.com/5175912/86801135-002e6000-c074-11ea-9814-c819296339d2.png)

**Comment by PVince81** [comment]
also, doesn't look nice in responsive mode:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/277525/87305969-9d2b4600-c517-11ea-8f4f-d25d0141b25a.png">

@LukasHirt FYI

**Comment by diocas** [comment]
This no longer applies, so I'm closing this ticket. Feel free to re-open if necessary.
