### ISSUE TITLE
Reload current state by clicking on home icon or All files tab

### ISSUE THREAD

**Issue by labkode** [owncloud/web#3743]
If you click on All files or the home button it will show you the contents of the folder.
Files can be added/removed to the space of the user by other means (sync client, mobile) so I want to refresh the page to see new changes.

If I click again the *home* icon or the *All files* tab nothing happens. 

The only way is to hit F5 and reload the page or navigate back and forth to other section (Favourites, for example).

**Comment by diocas** [comment]
This no longer applies, so I'm closing this ticket. Feel free to re-open if necessary.
