### ISSUE TITLE
Public links page has wrong footer offset

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#3745]
### Steps to reproduce
1. Create a public link (e.g. through quick action)
2. Open public link in private session or different browser

### Expected behaviour
The footer element (with number of subfolders and files + the folder size) should stick to the bottom of the page.

### Actual behaviour
The footer element has a huge offset from the bottom. Probably because the topbar is not visible on the public link page. Offset height matches the topbar height.

### Server configuration
phoenix.owncloud.com

### Client configuration
**Browser:** Chrome

**Operating system:** macOS

### Screenshots
<img width="1792" alt="Screenshot 2020-07-07 at 23 09 15" src="https://user-images.githubusercontent.com/3532843/86843482-e65a4080-c0a6-11ea-9c68-f5eb4d89d36d.png">

**Comment by pascalwengerter** [comment]
Closed, perhaps was fixed when _the evil PR_ ™️ got merged
