### ISSUE TITLE
Breadcrumbs are being escaped in location picker

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3753]
1. During move, navigate into a folder structure like this
![Screenshot 2020-07-09 at 08 34 43](https://user-images.githubusercontent.com/3532843/87005523-6bd11400-c1bf-11ea-8f9e-9a66e9267658.png)

2. Navigate back by clicking on the folder name with a blank. The blank converts to `%20` after navigating to the folder. Only happens in the title breadcrumb, not in the regular breadcrumbs we have above the files list.
![Screenshot 2020-07-09 at 08 34 50](https://user-images.githubusercontent.com/3532843/87005651-a20e9380-c1bf-11ea-8efc-8bd9bff457a4.png)

Thanks @kulmann for spotting!

**Comment by kulmann** [comment]
Solved in the meantime. See screenshot:

<img width="552" alt="Screenshot 2021-10-15 at 23 19 00" src="https://user-images.githubusercontent.com/3532843/137554738-83b484ee-86b7-49d3-a2df-45f14d78998c.png">
