### ISSUE TITLE
Add "create folder" and "search" action into location picker

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3757]
Mockups - https://www.figma.com/file/7MvPgcwufnZdwSha7f4dOz/ownCloud-Web-App?node-id=3013%3A3931

- [ ] Create folder
- [ ] Search

**Comment by fschade** [comment]
@LukasHirt is this still aligned and should keep opened? cc: @tbsbdr

**Comment by LukasHirt** [comment]
@fschade It was a plan since beginning and there haven't been any discussion about not doing this

**Comment by JammingBen** [comment]
Closing since we achieved that with the new embed mode.
