### ISSUE TITLE
Update all deps

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3758]
- [ ] see https://github.com/owncloud/phoenix/pulls/app/dependabot-preview and update as many as possible
- [ ] also update deps in ODS where it makes sense
- [ ] also update deps in owncloud-sdk where it makes sense

@LukasHirt FYI

**Comment by pascalwengerter** [comment]
Closed as outdated, we'll have to update dependencies regularly in all three mentioned repositories anyways
