### ISSUE TITLE
Capabilities seem to be loaded too late sometimes

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3771]
Sporadically an error `Cannot read property 'api_enabled' of undefined` in quickActions is appearing. Since this key is being read from capabilities, it seems that they are being read too late. This needs to be investigated.

**Comment by LukasHirt** [comment]
Seems that this is happening also in public links and there it's 100 % reproducible - probably missing a check for the public link since getting capabilities requires a user to be signed in. Thanks @PVince81 for spotting!

**Comment by pascalwengerter** [comment]
Fixed as tracked by loading capabilities twice (authenticated context) and tracked in #5863
