### ISSUE TITLE
Right click on file list rows

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#3819]
A right click on a files list row shows the default browser context menu. We could interfere this and show our "three dots menu" instead. While that's quite easy to solve, we would also need to show the three dots menu at the location of the click. That would require some changes.

**Comment by ChrisEdS** [comment]
Some users have useful tools in their right click menu. Is there a way to allow these users to open the system context menu instead of the one from ownCloud UI. For example with Control + right click?

**Comment by LukasHirt** [comment]
> Some users have useful tools in their right click menu. Is there a way to allow these users to open the system context menu instead of the one from ownCloud UI. For example with Control + right click?

If they do right click twice the default context menu opens. It's not that clear but at least it's possible 🤷

**Comment by ChrisEdS** [comment]
> It's not that clear but at least it's possible.

Great! Works for me.

**Comment by LukasHirt** [comment]
Agreed in design initiative to implement this but need more research beforehand.

**Comment by pascalwengerter** [comment]
Closed in favor of the more recent #5103
