### ISSUE TITLE
Public Share is not displayed in "Shared with others" page

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/web#3841]
### Steps to reproduce
1.  from ocis repo start phoenix `bin/ocis server` . For details about the setup, check the section `run tests > with Ocis backend` https://owncloud.github.io/clients/web/testing/
2. Create a folder: `folder1`
3. Create a public share with name `Public Link` for `folder1`
4. Browse to `Shared with others` page
5. `folder1` is not listed here

### Expected Behavior
1. Run normal phoenix setup with owncloud core backend
2. Repeat above steps from step 2 to step 5
3. `folder1` is listed here

**Comment by pascalwengerter** [comment]
Can not reproduce, @HariBhandari07 can you confirm this still fails for you?

**Comment by pascalwengerter** [comment]
Closed since I can't reproduce and received no answer

**Comment by HariBhandari07** [comment]
@kiranparajuli589 @Talank  can you guys please confirm if this issue is resolved?

**Comment by Talank** [comment]
Putting this in the backlog and adding a QA label.

Todo:
- [ ] Need to confirm if this issue is resolved

**Comment by Talank** [comment]
Reopening to confirm if the issue is resolved.

**Comment by SwikritiT** [comment]
I cannot reproduce this issue either. Maybe it has been solved . I'm closing this issue for now.
