### ISSUE TITLE
Phoenix displays different resources owners once a share is created

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#3895]
### Steps to reproduce
1. Share a file from einstein's account with marie.
2. Log in as marie and view the collaborators on any of marie's files.

### Expected behaviour
All the files created by marie should list her as their owner. 

### Actual behaviour
The files actually list einstein as their owner with marie assigned the role of a viewer.

### Configuration
Run from ocis commit [ea11f7](https://github.com/owncloud/ocis/commit/ea11f701aae4b086e1ce715c63fba56b82dcc58b) with REVA_USERS_DRIVER as "json".

**Comment by PVince81** [comment]
Is this with EOS as storage ? I think I remember seeing this a similar issue in the share panel with @kulmann but couldn't find the ticket any more.

**Comment by ishank011** [comment]
@PVince81 nope, faced this when using owncloud fs as well.

**Comment by PVince81** [comment]
hmmm, strange. @LukasHirt does this ring any bells ?

**Comment by LukasHirt** [comment]
> does this ring any bells ?

Haven't seen that yet. But haven't looked at collaborators in quite a while

**Comment by ishank011** [comment]
Here's what we get even with owncloud fs

<img width="1435" alt="Screenshot 2020-07-30 at 10 33 34" src="https://user-images.githubusercontent.com/10387289/89400502-4549be80-d714-11ea-93d3-2fba0396ae72.png">

**Comment by pascalwengerter** [comment]
@ishank011 could you confirm this isn't reproduce-able anymore (and then close the issue)? :)

**Comment by ishank011** [comment]
Fixed!
