### ISSUE TITLE
Sharing the share folder itself shouldn't be allowed

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#3897]
The Shares folder itself can be shared with other users as well as publically - it is only when the recipient tries to access it that it returns an error. There's a PR to handle it in reva https://github.com/cs3org/reva/pull/1051, but it should be prevented by phoenix in the first place.

**Comment by diocas** [comment]
@ishank011 I think we can close this. We no longer can share the shares folder (and we even want to hide it). Please re-open if not true.
