### ISSUE TITLE
CERN feedback from Phoenix UX workshop

### ISSUE THREAD

**Issue by labkode** [owncloud/web#3898]
This issue superseded:
https://github.com/owncloud/phoenix/issues/1833

Overall there has been progress on the UI from the previous design to the current one as of 6/08/2020.
The UI feels more modern and more usable. The team is going into the right direction.

- [X] When clicking the "manage my account" button a new tab opens, from my perspective this is annoying. 

- [X] I've been logged out at least four times the last 20 minutes

- [X] When clicking "Menu" the file information is covered by the navigation bar

- [X] Nothing happened when I clicked "open in pdfviewer" and "open in markdown editor", but maybe this is intentional for now?

- [X] Clicking on 'Manage your account' takes you to the login screen, and though you don't have to enter the credentials again, it takes some time to redirect to /account, which is not really UX-friendly.

- [X] The design is not balanced. Some things are big and with lots of space (i.e buttons), others small (the text inside the buttons).

- [X] There is no alt text information on the elements (i.e the applications button)

- [X] There's no "move" option, to move files around

- [X] The mimetype icons are ready for a redesign (they look outdated)

- [X] No sortable headers in files view

- [X] Updating link fails with an error.Expiration date input on public link is free form, no calendar pop-up.

- [X] Sidebar transitions (sharing, left menu) are abrupt, harsh to the the end-user experience:
https://github.com/owncloud/phoenix/issues/3925

- [X] I think the progress circle when searching is placed in a strange place.:
https://github.com/owncloud/phoenix/issues/3909

- [X] Hovering the file list could show up shortcuts to the most used actions (instead of always hidding them in "..."):
https://github.com/owncloud/phoenix/issues/3912

- [X] Drag and drop of files would be handy:
https://github.com/owncloud/phoenix/issues/3914

- [X] Login should be automatic (instead of showing the "login" button; at least make this configurable): 
https://github.com/owncloud/phoenix/issues/3915

- [X] The session should be refreshed without sending users to the login 
page:https://github.com/owncloud/phoenix/issues/3916

- [X] The "open" dialog that appears in the bottom is a nice concept, but I would prefer to set a default action for 
opening (maybe a checkbox to choose this?:
https://github.com/owncloud/phoenix/issues/3918

- [X] Harsh transitions:
https://github.com/owncloud/phoenix/issues/1855

- [X] Display username alongside display name when searching users in share menu
https://github.com/owncloud/phoenix/issues/3804

- [X] Make home path configurable:
https://github.com/owncloud/phoenix/issues/4248

- [X] When clicking "collaborators" I also get other file information such as versions and links, maybe this should be called something more generic?
https://github.com/owncloud/phoenix/issues/3907

- [X] When clicking "collaborators" and "collaborators" I get first one progress bar and then a progress circle, for me this feel very cluttered:
https://github.com/owncloud/phoenix/issues/3908

- [X] It would be useful to have a right click menu:
https://github.com/owncloud/phoenix/issues/3920

- [ ] Improve usability for received shares:
https://github.com/owncloud/phoenix/issues/3926

- [ ] The menu on the right has relevant links. The screen has plenty of space. So the menu should be visible all the time:
https://github.com/owncloud/phoenix/issues/3910

- [x] The warnings/errors should disappear automatically. If there's a need to keep them, then they should be part of a "notifications" menu: 
https://github.com/owncloud/phoenix/issues/3911

- [ ] There's no "download selected" button, when selecting multiple files: 
https://github.com/owncloud/phoenix/issues/3913

- [ ] Overlay elements like the date picker should prevent clicks on background elements
https://github.com/owncloud/phoenix/issues/3917

- [ ] No option to share a folder when inside it:
https://github.com/owncloud/phoenix/issues/3919

- [x] When I go to share with others, the api might take some time replying. When it does, I see a flash of a message in the background before seeing the files (probably the message that appears when there's nothing shared with other):
https://github.com/owncloud/phoenix/issues/3921

- [ ] No favourites:
 https://github.com/owncloud/phoenix/issues/3922

- [x] No shared with public link:
 https://github.com/owncloud/phoenix/issues/3923

- [ ] Public link deletion does not trigger a popup for confirmation, compared to deleting a file or a user share, restoring the public link is not possible:
https://github.com/owncloud/phoenix/issues/3924

- [X] The creation of a public link doesn't show the public link URL, user has to click the chain symbol to get it copied, it is not intuitive (EDIT: It does now)

- [x] Hovering the mouse over the favourite start does not trigger a change in the cursor (probably because it isn't a link), the checkbox does it:
https://github.com/owncloud/phoenix/issues/1645

**Comment by micbar** [comment]
@labkode Seems that you tested an outdated version.

Which version did you tests?

**Comment by labkode** [comment]
@micbar this is the feedback from the last UX workshop we had together in March.
If some of the items have been addressed, please specify which ones.

**Comment by micbar** [comment]
@labkode Please open individual issues for the remaining items. These large "all in one" issues are hard to process :-)

**Comment by labkode** [comment]
@micbar done 👍

**Comment by fschade** [comment]
@kulmann points are still open, we should discuss this and decide how to handle them.

**Comment by kulmann** [comment]
Closing here, since the individual issue have their own tickets. All of them have a label that lets them appear in our fastlane, so they have sufficient attention.
