### ISSUE TITLE
Move auth code into owncloud-sdk

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3906]
Instead of reimplementing auth code for a file picker, it would be nice to move it to our sdk. Thoughts @PVince81 @kulmann ?

**Comment by fschade** [comment]
@LukasHirt, is this still relevant regarding the lastest filepicker improvements?

**Comment by JammingBen** [comment]
Closing since the owncloud-sdk is officially deprecated and won't receive any updates in the future.
