### ISSUE TITLE
UX: two progress styles for same action in collaborators pane

### ISSUE THREAD

**Issue by labkode** [owncloud/web#3908]
When clicking "collaborators" and "collaborators" I get first one progress bar and then a progress circle, for me this feel very cluttered.

**Comment by pascalwengerter** [comment]
@labkode can you confirm this is still the case? The side panel has been updated and I'm only seeing a progress bar

**Comment by diocas** [comment]
I'm closing this ticket as now it's a bit more consistent. The progress bar is shown even on sharing options.
