### ISSUE TITLE
UX: fill space with actions

### ISSUE THREAD

**Issue by labkode** [owncloud/web#3910]
The menu on the right has relevant links. The screen has plenty of space. So the menu should be visible all the time.
Actions in the three dots can be visible if space is available.

**Comment by kulmann** [comment]
We will do two things to solve this:
1) implement all kinds of quick actions
2) make quick action visibility customizable for users
Timeline is not clear though, yet.

**Comment by pascalwengerter** [comment]
@tbsbdr could you add this issue to your "to be discussed" list?

**Comment by tbsbdr** [comment]
maybe this issue is addressed with the planned show/hide sidebar switch as shown by @elizavetaRa

**Comment by pascalwengerter** [comment]
Closing in favor of other, more actionable (future) tickets. We have since changed the sidebar and merged the overall redesign changes
