### ISSUE TITLE
UX: errors notifications should disappear automatically

### ISSUE THREAD

**Issue by labkode** [owncloud/web#3911]
The warnings/errors should disappear automatically. If there's a need to keep them, then they should be part of a "notifications" menu

**Comment by kulmann** [comment]
This has been implemented in https://github.com/owncloud/web/pull/5018 but is waiting for a release. Planned to be released by the end of this month with the next web release. We'll have a hard time merging that PR, so there's some uncertainty.

**Comment by pascalwengerter** [comment]
Closed since we merged #5018 💪🏽
