### ISSUE TITLE
FEATURE: There's no "download selected" button, when selecting multiple files

### ISSUE THREAD

**Issue by labkode** [owncloud/web#3913]

**Comment by PVince81** [comment]
I think @DeepDiver1975 worked on zip download, not sure how far we are and whether it was added to Phoenix yet

**Comment by pmaier1** [comment]
There is no archive download for multiple files or folders in the backend yet. Roadmap item.

**Comment by kulmann** [comment]
This needs an implementation in REVA first. Any progress on this @labkode ?

**Comment by pascalwengerter** [comment]
Closed in favor of the more recent #5809

**Comment by kulmann** [comment]
Fine because we're solving both in one PR, but actually this ticket is about an archive download for multiple selected files, while the other issue is about a download opportunity for a single folder. ;-)

**Comment by pascalwengerter** [comment]
> Fine because we're solving both in one PR, but actually this ticket is about an archive download for multiple selected files, while the other issue is about a download opportunity for a single folder. ;-)

Okay sry, reopened & linked to your PR
