### ISSUE TITLE
Include requirejs in the core.js bundle

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3951]
Include requirejs directly into the core js bundle instead of having it in the node_modules folder as part of the build artifact.

**Comment by pascalwengerter** [comment]
What's necessary to do this / has it been done in the meantime?

**Comment by LukasHirt** [comment]
Has been done when switching to rollup https://github.com/owncloud/web/blob/535f3586ef4e03c38c6fd3c51294b71e7d276133/rollup.config.js#L71
