### ISSUE TITLE
Remove root folder from config.json

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3964]
It is possible to define a specific root folder in config.json. This was done some time ago as a workaround and was supposed to be implemented in backend instead because with frontend-only solution comes too many issues.

Having this still in codebase lead us to having to take care of such code in a lot of different places when new logic was being introduced and with some latest changes it hasn't been tackled at all resulting in a big inconsistency (and bugs if anyone would be actually using this feature).

**Comment by pascalwengerter** [comment]
@kulmann is this still relevant?

**Comment by kulmann** [comment]
It was used for one customer for whom we created a fork anyway. We already went ahead and removed the code for it.
