### ISSUE TITLE
Fetching config.json is not authenticated

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#4007]
In order to build a dynamic config.json in ocis-phoenix which is based on the permissions of the authenticated user, we need to fetch the `config.json` file in a way that allows us to look up the roleIDs of the authenticated user. I.e. the bearer token (if present) needs to be set on the fetch header options when fetching config.json. Needs investigation how and if this is possible.

**Comment by LukasHirt** [comment]
Related #2962?

**Comment by kulmann** [comment]
Closing, not relevant at the moment
