### ISSUE TITLE
[QA] Menu gets cutted using Mozilla Firefox 80 for Mac as Browser

### ISSUE THREAD

**Issue by davitol** [owncloud/web#4052]
Tested using  Mozilla Firefox 80 for Mac and Chrome 64 as Browsers

<img width="1280" alt="Screenshot 2020-09-09 at 16 56 51" src="https://user-images.githubusercontent.com/10596560/92619476-d555c780-f2c1-11ea-9b38-9b7fe5cce3e6.png">

**Comment by pascalwengerter** [comment]
@davitol could you pull the most recent version and check if it's still the case? 🙌🏽

**Comment by davitol** [comment]
Works OK for me. Let's close the ticket

**Comment by pascalwengerter** [comment]
Thanks for the quick reaction!

**Comment by pascalwengerter** [comment]
Thanks for the quick reaction!
