### ISSUE TITLE
[QA] Language changes shown in the left sidebar

### ISSUE THREAD

**Issue by davitol** [owncloud/web#4064]
Tested with ocis-1.0.0-rc1 via https://gitea.owncloud.services/jw/hetzner/src/branch/master/make_ocis_eos_test.sh

### Steps to reproduce

1. Change user language several times

<img width="1275" alt="Screenshot 2020-09-10 at 09 40 52" src="https://user-images.githubusercontent.com/10596560/92697006-04644b80-f34b-11ea-9b5f-b61b3e342ae2.png">

Changes appear in the left side, what is the purpose? Tested using Mozilla Firefox 80 for Mac

**Comment by pascalwengerter** [comment]
Hey @davitol, can't reproduce/what's your issue here? Could you check with the latest release of oCIDS (1.4.) or `web` on master?

**Comment by pascalwengerter** [comment]
Closed due to inactivity, feel free to re-open with more info! :)
