### ISSUE TITLE
[QA] Some elements are not translated

### ISSUE THREAD

**Issue by davitol** [owncloud/web#4065]
<img width="1278" alt="Screenshot 2020-09-10 at 09 41 37" src="https://user-images.githubusercontent.com/10596560/92698592-e0a20500-f34c-11ea-9c76-b7f90484b2db.png">

<img width="310" alt="Screenshot 2020-09-10 at 10 05 39" src="https://user-images.githubusercontent.com/10596560/92698878-31b1f900-f34d-11ea-8b1a-2e8da26afc54.png">

<img width="753" alt="Screenshot 2020-09-10 at 10 08 08" src="https://user-images.githubusercontent.com/10596560/92700035-a2a5e080-f34e-11ea-9846-4e267deec15e.png">

**Comment by pascalwengerter** [comment]
@davitol the strings should be translate-able by now, if you want to support us in bringing the Spanish translations over please read https://github.com/owncloud/core/#important-notice-on-translations - we're looking for contributors there, too :)
