### ISSUE TITLE
oc-drop in right sidebar is behind files list

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#4085]
### Steps to reproduce
1. As alice, share a folder with bob
2. Login as bob, re-share the folder with charlie
3. Login as alice, open the right sidebar with share information (tab "people")
4. click on the `show resharer details`
5. resize the window until the oc-drop flips over to the left side (i.e. oc-drop is wider than the right sidebar)

### Expected behaviour
The oc-drop with resharer-details should be in front of the files list

### Actual behaviour
The oc-drop with resharer-details is behind the files list (see screenshots)

#### Sidebar wider than oc-drop
<img width="598" alt="Screenshot 2020-09-18 at 14 34 20" src="https://user-images.githubusercontent.com/3532843/93598184-a07dfa80-f9bc-11ea-9959-d2a4291e25d2.png">

#### Sidebar narrower than oc-drop
<img width="674" alt="Screenshot 2020-09-18 at 14 34 25" src="https://user-images.githubusercontent.com/3532843/93598190-a247be00-f9bc-11ea-99d6-5102817858b1.png">

**Comment by pascalwengerter** [comment]
Tried to reproduce this one with the new users and couldn't manage, always ran into **You don't have permission to share this folder.**

**Comment by LukasHirt** [comment]
@pascalwengerter when using oCIS as a backend we do not allow yet resharing. Should be possible to reproduce with oC10 backend.

**Comment by pascalwengerter** [comment]
Can't reproduce anymore
