### ISSUE TITLE
Parent folder breadcrumb is not properly displayed when child file/folder in favorites page

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/web#4113]
### Steps to reproduce
1. Create folders in the structure `New folder one/New folder two/New folder three`
2. Favorite `New folder three`
3. Browse to `Favorites` page
![Screenshot from 2020-09-29 11-34-43](https://user-images.githubusercontent.com/34328907/94517520-d71f0500-0247-11eb-80f3-8f549fb815e7.png)

As seen in the above screenshot `.../New folder two/New folder three` is displayed instead of `New folder one/New folder two/New folder three`. 
Is this the proper behavior for displaying breadcrumb file/folder structure?
 I think this way of displaying file/folder is fine for small screen size but for larger screen full path must be displayed or at least full path must be available in HTML element.

**Comment by pascalwengerter** [comment]
Contrary to #4608, needs a product decision @tbsbdr

**Comment by JammingBen** [comment]
Closing as this is not an issue anymore:

<img width="185" alt="image" src="https://github.com/owncloud/web/assets/50302941/ef8ca66a-8659-405a-86e4-3f70677a180f">
