### ISSUE TITLE
Clickable area in the burger menu for the sidebar is shifted 

### ISSUE THREAD

**Issue by C0rby** [owncloud/web#4130]
In Phoenix on ocis.owncloud.works I noticed that when the burger menu for the side bar is shown, the clickable area of that burger menu is a bit shifted to the left.

![2020-10-02-155012_952x1171_scrot](https://user-images.githubusercontent.com/5579653/94930921-64bc5800-04c7-11eb-96f7-ce8c5c37ccff.png)
![2020-10-02-155109_952x1171_scrot](https://user-images.githubusercontent.com/5579653/94930932-68e87580-04c7-11eb-87c5-a2b3560a346e.png)

**Comment by jnweiger** [comment]
Confirmed fixed in web-1.0.2 when running on owncloud server 1.6.0
