### ISSUE TITLE
[OCIS] share indicator in files are not shown until sharing sidebar is opened

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#4167]
### Steps to reproduce
1. With ocis create a share using the sharing API.
2. log in as the user.

### expected result
1. The indicator icon for share should be shown

### Actual behavior
1. The sharing indicator is not shown until the sharing sidebar is opened.

![Screenshot from 2020-10-15 13-19-00](https://user-images.githubusercontent.com/19869344/96091232-10fb3700-0ee9-11eb-82a8-93ff508e6175.png)
![Screenshot from 2020-10-15 13-19-10](https://user-images.githubusercontent.com/19869344/96091245-148ebe00-0ee9-11eb-9209-3581af2a89b0.png)

**Comment by kiranparajuli589** [comment]
### `Update`: at the date of the comment
- for user shares: indicators work properly (also with subfolders and files)
- for link shares: 
    - just after submitting the creation form and the sidebar is not closed, the shared resource shows the link indicator 
    - after the sidebar is closed the indicator is completely gone. it does not reappear after reload or anything.
    - subfolders and files has the link indicators

**Comment by kiranparajuli589** [comment]
related https://github.com/owncloud/ocis/issues/1038

**Comment by ScharfViktor** [comment]
It's fixed. Re-tested with local server oCIS version 1.12.0 and web 4.2.0



> ### `Update`: at the date of the comment
> * for user shares: indicators work properly (also with subfolders and files)
> * for link shares:
>   
>   * just after submitting the creation form and the sidebar is not closed, the shared resource shows the link indicator
>   * after the sidebar is closed the indicator is completely gone. it does not reappear after reload or anything.
>   * subfolders and files has the link indicators

@kiranparajuli589 this case is relevant. for it there is https://github.com/owncloud/ocis/issues/1038
