### ISSUE TITLE
[OCIS] opening a folder from shared with me page fails

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#4170]
### steps to reproduce
1. Share a folder to another user eg `folder1`
2. As a share try to open the folder from `shared with me` page

### expected result
1. Gets redirected into `Shares/folder1`

### Actual result
1. Gets redirected to `/folder1`

**Comment by kulmann** [comment]
Works properly by now. Tried to reproduce it again just now, without any luck. Closing here.
