### ISSUE TITLE
[OCIS] Not shared sub folders get sharing indicator icons when one share is created.

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#4172]
### Steps to reproduce
1. login as Richard and create a folder `hello`
2. Create file a file `hello.txt` and `hellofolder` inside `hello`
3. As Einstein share a file to richard.
4. As Richard accept the share.
5. As Richard open the folder `/hello` 

### Expected
no share indicators

### Actual
Sharing indicators are shown for the files and folders inside`hello`
![Screenshot from 2020-10-15 17-09-18](https://user-images.githubusercontent.com/19869344/96117251-8414a580-0f09-11eb-964a-f146978e9caa.png)

**Comment by fschade** [comment]
Fixed in latest master
