### ISSUE TITLE
[OCIS] renamed file cannot be shared

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#4192]
### Steps to reproduce
1. Login as user Einstein
2. Upload a file eg. `lorem.txt`
3. Rename file to `ipsum.txt`
4. Try to share file `ipsum.txt` to richard

### Expected behaviour
Sharing should work

### Actual behaviour
Sharing fails with error message `grpc create share request failed.`
![Screenshot from 2020-10-16 12-03-25](https://user-images.githubusercontent.com/19869344/96219975-9fce8900-0fa7-11eb-9f13-a406ec24d73c.png)

**Comment by HariBhandari07** [comment]
JankariTech Reminder: Swikriti is working on bug demonstration test for this issue

**Comment by dragotin** [comment]
This might be related to #4893 . I think it can only not be shared if the extension is changed.

**Comment by fschade** [comment]
Error does not happen anymore in latest master. I close this for now
