### ISSUE TITLE
[OCIS] People tab in sidebar shows same user twice sometimes.

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#4193]
The sidebar tab for people shows the same user twice sometimes.
I ran into this issue when running tests. So I think it might be caused by https://github.com/owncloud/ocis-reva/issues/357

![Screenshot from 2020-10-16 13-50-10](https://user-images.githubusercontent.com/19869344/96233700-27bc8f00-0fb8-11eb-89b1-69c90436dda4.png)

**Comment by pascalwengerter** [comment]
Can you still reproduce this? Never seen this before and would like to close the ticket if outdated :)

**Comment by dpakach** [comment]
I haven't seen this issue recently, so must have been fixed
the cause was probably https://github.com/owncloud/ocis/issues/1226#issuecomment-855643637
which seems to be fixed too
