### ISSUE TITLE
[OCIS] displayname of a user doesn't gives any result in sharing autocomplete

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#4194]
Entering the displayname of the user in shareWith field doesn't gives any result
![Screenshot from 2020-10-16 16-13-57](https://user-images.githubusercontent.com/19869344/96248008-9d315b00-0fca-11eb-98cd-7fb796e76994.png)

**Comment by dschmidt** [comment]
Cannot reproduce in current master. Please reopen if still valid.
