### ISSUE TITLE
quotes in the filename are not correctly displayed in the upload bar

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#4214]
![image](https://user-images.githubusercontent.com/2425577/96579487-a8e88e80-12f6-11eb-9495-df1069b44426.png)

**Comment by fschade** [comment]
i can confirm that the issue still happens in latest master.
<img width="1088" alt="Bildschirmfoto 2021-06-15 um 13 27 18" src="https://user-images.githubusercontent.com/49308105/122045085-91a66600-cddd-11eb-90cb-c16f37d9f63c.png">

**Comment by dschmidt** [comment]
This is a bug in `vue-gettext`. I've sent a PR, which fixes it and hope we can get that merged soon and a release afterwards.
https://github.com/Polyconseil/vue-gettext/pull/135
