### ISSUE TITLE
items on the top-level cannot be deleted if `share_folder` is set in oC10

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#4243]
### Steps to reproduce
1. upload some files/folders
2. set the `share_folder` to `Shares` (`./occ config:system:set share_folder --value=Shares`)
3. open the action menu of any item in the top level

### Expected behaviour
the `DELETE` button should be visible

### Actual behaviour
no `DELETE` button
![image](https://user-images.githubusercontent.com/2425577/97257015-c9f03880-183c-11eb-8741-e4fc0132dc53.png)

in subfolders the button is shown again

![image](https://user-images.githubusercontent.com/2425577/97257006-be9d0d00-183c-11eb-9460-d679210e5d9b.png)

**Comment by pascalwengerter** [comment]
@kulmann @individual-it could you re-check and close if resolved? Screenshots look way outdated 😬

**Comment by individual-it** [comment]
seems to work in the current version
