### ISSUE TITLE
[oC10] federation shares are not listed in "shared-with-me"

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#4246]
### Steps to reproduce
1. setup federation sharing
2. from remote server share to the server where phoenix is running
3. check "shared-with-me" page

### Expected behaviour
federation share should be listed

### Actual behaviour
federation share is not listed

![fed-sharing](https://user-images.githubusercontent.com/2425577/97290523-c24a8700-1870-11eb-84b9-bb890c1a29e0.gif)

**Comment by HariBhandari07** [comment]
JankariTech Reminder: Sawjan is writing bug demonstration test for this issue

**Comment by JammingBen** [comment]
Closing this as won't fix since we dropped oC10 support beginning with version 7.1.0.
