### ISSUE TITLE
preview of image shared through public link in the media viewer doesn't work

### ISSUE THREAD

**Issue by swoichha** [owncloud/web#4295]
### Steps to reproduce 
1. User `moss` creates a folder `testFolder` and upload an image `test.jpg`
2. User `moss` creates public link to share the folder
3. The public access the public link created by user `moss` and opens the image in media viewer 

### Expected behaviour
The image `test.jpg` should be displayed in the media viewer webUI

### Actual behaviour
Image doesn't load in media viewer

### Screenshot
![Screenshot from 2020-11-10 17-11-59](https://user-images.githubusercontent.com/17021686/98668399-ef6e5d80-2377-11eb-8785-e4709d5ecdc6.png)

**Comment by phil-davis** [comment]
Is this with oC10 server or OCIS server or both?

**Comment by swoichha** [comment]
> Is this with oC10 server or OCIS server or both?
 It happens in both oC10 and OCIS server

**Comment by saw-jan** [comment]
Now working with oC10
![ss](https://user-images.githubusercontent.com/52366632/112830400-31dbd100-90b2-11eb-9004-742406ddf440.jpg)

Configuration:
- `Web` build from latest master (commit id: `c22cf7aadd14293fd7d8914d9f1f8fd0433c75f8`)
- oC10 version `10.7.1 prealpha (git)` (commit id: `157353ab081537d08a8467543cb75561e4044817`)

**Comment by fschade** [comment]
@swoichha, issue didn't happen on latest master anymore.
