### ISSUE TITLE
UX: show actions also for the current folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#4304]
### Current situation
The entries in a folder each has a actions on the right hand side: sharing, linking, and a 3-dots-menu. ![image](https://user-images.githubusercontent.com/1108546/98872818-7fdf9780-2477-11eb-9f31-740e20b0e2e8.png)
But the current folder itself does not have them.
If a user wants to e.g. share the current folder, he needs to navigate to the parent folder and find the folder again by scrolling down.

### Enhancement idea
Add the action icons also to the folder too.
E.g as sketched below with icons at the right hand side (, or maybe a little dropdown triangle  on the breadcrumbs ... )

![image](https://user-images.githubusercontent.com/1108546/98873279-64c15780-2478-11eb-8ebf-7a270fa410e1.png)

**Comment by pascalwengerter** [comment]
Closed in favor of #3919
