### ISSUE TITLE
Indirect shared indicator shown in shared folder

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#4310]
When running against oCIS, if a user navigates into the share mount folder, he sees indirect shared indicator for all the shares.

**Comment by individual-it** [comment]
- [ ] ToDo QA-team: check if we have tests for that, if not add them, if yes link them here

**Comment by fschade** [comment]
@individual-it, can we close the issue or is it still needed?

**Comment by individual-it** [comment]
@fschade if the issue itself is solved we can close it. I cannot see any test failures marked with this issue so I guess its fixed
closing
