### ISSUE TITLE
 Audit #1 – Login Page – Color contrast of text input placeholder too low

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4320]
Connected to Audit 1, see #4300 
1.1 Login Page, URL: https://ocis-a11y.owncloud.works/

# Issue

Text contrast of placeholder text to text input background is too low (namely 1.51:1). It has to be at least 4.5:1.

# Remediation

Fixing the color ratio, or not relying on placeholders as label, see #4319

**Comment by pascalwengerter** [comment]
Closing this since #5018 is merged and we're waiting for feedback (and will open new tickets with the requested changes from the `a11y` audit)
