### ISSUE TITLE
 Audit #1 – Login Page – Non-text contrasts in text inputs too low

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4321]
Connected to Audit 1, see #4300 
1.1 Login Page, URL: https://ocis-a11y.owncloud.works/

# Issues

1. The color contrast ratio of the text input's outline to its adjacent overall page background is too low (2.63:1 instead of at least 3:1)
2. The color contrast of the text input's background to the page background is too low (1.1:1 instead of at least 3:1)

# Remediation

Using for example `#fffff`for the outline color and using the same color value for background of input and background of page.

**Comment by pascalwengerter** [comment]
Closing this since #5018 is merged and we're waiting for feedback (and will open new tickets with the requested changes from the `a11y` audit)
