### ISSUE TITLE
[Bug] Messages not shown in fullscreen apps

### ISSUE THREAD

**Issue by VirtualEvan** [owncloud/web#4335]
### Steps to reproduce
1. Define an app as full screen
    ```js
    {
      name: 'draw-io-edit',
      path: '/edit/:filePath',
      components: {
        fullscreen: DrawIoEditor
      },
      meta: { hideHeadbar: true }
    }
    ```
2. Use the `showMessage` function

The message is shown if the `fullscreen` property is changed to `app` and `hideHeadbar` is removed
```js
{
  name: 'draw-io-edit',
  path: '/edit/:filePath',
  components: {
    app: DrawIoEditor
  }
}
```

### Expected behaviour
The speified message should be shown

### Actual behaviour
The message is not displayed

**Comment by pascalwengerter** [comment]
Hey @VirtualEvan, is this issue still open after your PR has been merged? :)

**Comment by VirtualEvan** [comment]
Yes, this issue is something I found while working in the draw.io app, my PR did not addressed it

**Comment by kulmann** [comment]
Apps are now always forced into an application layout which contains the message-bar component and handles the active messages. The fullscreen mode has been removed entirely in https://github.com/owncloud/web/pull/6401 - closing this issue here as solved.
