### ISSUE TITLE
Audit #1 – General Overview when logged in – Page title stays the same all across the app

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4338]
Connected to Audit 1, see #4300 
1.2 General Overview when logged in, URL: https://ocis-a11y.owncloud.works/#/files/list

# Issue
Document title stays "ownCloud" no matter what you do and where you are. But should describe the page, route or state that a user is on or on.

Update 2021-02-24: Good advise is to have a constant part of the string, e.g. "owncloud", and a part which is depending on the document you are on (or route you are in): "Foo Bar" (given that is a folder name in your ownCloud). The recommended order is: {individual} - {constant}

# Remediation
Set `document.title` after successful route change to a more descriptive text regarding the "page"/route. Dream Vue code:

```
  watch: {
    $route: function(to) {
      this.$nextTick(function() {

        document.title = "ownCloud - Einstellungen"; // = "ownCloud settings", for settings route

      });
    }
  },
```

**Comment by pascalwengerter** [comment]
Closing this since #5018 is merged and we're waiting for feedback (and will open new tickets with the requested changes from the `a11y` audit)
