### ISSUE TITLE
Audit #1 – General Overview when logged in – lang attribute on HTML is set to English but interface is German

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4342]
Connected to Audit 1, see #4300 
1.2 General Overview when logged in, URL: https://ocis-a11y.owncloud.works/#/files/list

# Issue
`lang` attribute on `<html>` seems to be hard coded

# Remediation
Make the `lang` attribute on `<html>` the actual language of the interface.

**Comment by pascalwengerter** [comment]
Fixed via #4811 a while ago
