### ISSUE TITLE
Audit #1 – General Overview when logged in – Ids are not unique

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4345]
Connected to Audit 1, see #4300 
1.2 General Overview when logged in, URL: https://ocis-a11y.owncloud.works/#/files/list

# Issue
* Ids are not unique (`files-quick-action-public-link`, `files-quick-action-collaborators`, `files-list-row-checkbox`, `files-quick-action-public-link`)
* wrong nesting (`h3` in `span`, `h1` in `span`, `div` in `button, style in button`)

# Remediation
* Using unique Ids
* Correct nesting

To check, use: https://validator.w3.org/nu/ and look out for "not allowed as child of element" and "Duplicate ID" errors.

**Comment by LukasHirt** [comment]
@marcus-herrmann Could you elaborate on the wrong nesting? E.g. in buttons for styling reasons we need to have spans/divs inside to properly separate the content from icons

**Comment by marcus-herrmann** [comment]
@LukasHirt Here's what https://validator.w3.org/ yields:

![Screenshot 2020-11-25 at 14 18 57](https://user-images.githubusercontent.com/505181/100233207-b4e4f300-2f29-11eb-82b8-cf991d8ff125.png)
![Screenshot 2020-11-25 at 14 21 33](https://user-images.githubusercontent.com/505181/100233211-b6162000-2f29-11eb-8585-6d6b310eb7b2.png)

It's about that a button mustn't have a block level element (as a div) as a child. It's about the "user menu" button and, among other things, the avatar in it.

You could replace divs with spans and it still works.

**Comment by pascalwengerter** [comment]
## Update
We resolved all (known) offenders in the design system in the **v4.0.0** release, now it's time to clean up the web

This comment shall be used to collect things to be fixed, feel free to append the list

- [ ] `<div>` and `<ul>` inside `<h1>` when moving a file/folder

**Comment by pascalwengerter** [comment]
Fixed via #5018, we'll open new ticket(s) if more offenses appear
