### ISSUE TITLE
Possibilities to reach WCAG 2.1, Level AAA

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4405]
In last week's meeting, Holger asked about WCAG Success Criteria in Level AAA. While it's common to aim for WCAG 2.1 AA/BITV 2.0 May 2019, it does not hurt at all to improve the accessibility further. 

**Priorititywise, this issue lists ideas for passing certain Level AAA criteria. In my opinion, this ticket shouldn't be worked on until all Level AA issues are taken care of.**

However, for Phoenix, I consider the following Success Criteria as theoretially reachable:

- A Color Contrast for Text of 7:1 (instead of 3.5:1) (WCAG 1.4.6)
- Providing a breadcrumb trail. (WCAG 2.4.8 Location). The existing breadcrumb component is nearly there, to make it match a WCAG (sufficient) technique, wrap it in a `<nav>` element and provide an accessible name (https://www.w3.org/WAI/WCAG21/working-examples/breadcrumb-trail/). 
- Making sure that all link/button texts work without context/surrounding text content (WCAG 2.4.9)
- Ensuring the target Size (clickable, touchable size of interactive elements) at least 44x44px (WCAG 2.5.5)
- The removal of infinite scroll in the central file list would, in my opinion, pass "Change on request" (WCAG 3.2.5)

**Comment by pascalwengerter** [comment]
Closing this since A11y audit is in progress, thanks for all the support along the way!
