### ISSUE TITLE
Audit #1 – Share a single file  – Accordions have no visible focus

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4408]
Connected to Audit 1, see #4300 
1.5 Share a single file , URL: https://ocis-a11y.owncloud.works/#/files/list

# Issue
The accordions for "Personen" and "Links" inside the "add people" dialog can be operated with keyboard only (activation by SPACE key), but don't have a focus style.

# Remediation
Supply focus style for button part of accordion in its focus state.

**Comment by pascalwengerter** [comment]
Closing this since #5018 is merged and we're waiting for feedback (and will open new tickets with the requested changes from the `a11y` audit)
