### ISSUE TITLE
sort out UI test scenarios related to product issue 203

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#4418]
Some code has been improved in OCIS to fix https://github.com/owncloud/product/issues/203 "file_target in share response". Now the `file_target` value includes the `Shares` folder that is the default in OCIS.

There are scenarios that demonstrate the correct behaviour of oC10.

There are also scenarios that demonstrated the wrong behaviour of OCIS. Many of those scenarios were edited to add the `Shares` folder when the problem was fixed. But actually the scenarios should have been deleted, and the correct scenarios should have been enabled to run on OCIS. For example https://github.com/owncloud/phoenix/pull/4412/files and https://github.com/owncloud/phoenix/pull/4413/files

To do:
- enable the correct scenarios (remove the `skipOnOCIS` tag)
- deleted the old bug-demo scenarios

Try to sort out as many as possible.

- report on what bug-demo scenarios still remain related to https://github.com/owncloud/product/issues/203

**Comment by phil-davis** [comment]
I did 1 example in #4419

**Comment by phil-davis** [comment]
Fixed by #4503

**Comment by individual-it** [comment]
reopening, because some tests still claim to fail because of product issue 203 see https://github.com/owncloud/web/blob/3152b7be93712a2720ef9071d06c4d43a1636489/tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md#file_target-in-share-response

partly fixed in https://github.com/owncloud/web/pull/4780

**Comment by pascalwengerter** [comment]
@individual-it @SwikritiT what's the state on this issue? :)

**Comment by individual-it** [comment]
I believe we can close it
