### ISSUE TITLE
[QA] oc10 public link with password fails 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#4531]
Deployed web-1.0.0 into docker run -ti --rm -v $HOME/oc10-mnt-data:/mnt/data -p 8080:8080 owncloud/server:10.6.0
using https://owncloud.github.io/clients/web/deployments/oc10-app/

* login as admin
* create a public link on folder Documents, set password 1113
* paste the link into another window of the same browser session
* An error occurs: Error: User did not have the required privileges. BAD

![image](https://user-images.githubusercontent.com/1108546/102432235-94352800-4013-11eb-981c-fc69b2a894e7.png)

This problem only occurs in the same browser session.
In a different browser session we get

![image](https://user-images.githubusercontent.com/1108546/102434181-8c29b800-4014-11eb-99fc-be131630aa9b.png)

A requester that asks for username and password -> https://github.com/owncloud/ocis/issues/829

**Comment by jnweiger** [comment]
Sometimes a different error occurs:

![image](https://user-images.githubusercontent.com/1108546/102434181-8c29b800-4014-11eb-99fc-be131630aa9b.png)

**Comment by davitol** [comment]
Just tested and it looks it works for me. It can be tested in https://demo.owncloud.com and cannot reproduce it

**Comment by micbar** [comment]
public links are redirected by the oc10 backend.

Config option: `web.baseUrl`

**Comment by jnweiger** [comment]
@micbar the documentation disagrees with that: "To display ownCloud Web in the app switcher and to redirect all private and public links to the new WebUI, add the following config into config/config.php:

'web.baseUrl' => 'https://<your-owncloud-server>/apps-external/web',
"

That is what I did, and thus I end up in the New Design.

**Comment by micbar** [comment]
Public / private links are always redirected to web

**Comment by micbar** [comment]
@jnweiger Maybe semantic misunderstanding

> public links are redirected by the oc10 backend.

I meant the oc10 backend does the redirects. It redirects to the new WebUI.

**Comment by jnweiger** [comment]
Reproduced unchanged in 1.0.2 
Not sure what the misunderstanding is. Feel free to close if irrelevant.

**Comment by pascalwengerter** [comment]
@kulmann could you take a look eventually?

**Comment by kulmann** [comment]
Cannot reproduce with web v3.2.0 as oc10 app.
