### ISSUE TITLE
can we clean up the URL path to avoid urlencoded /, eg

### ISSUE THREAD

**Issue by butonic** [owncloud/web#4595]
`https://phoenix.owncloud.com/index.html#files/list/eos%2Fusers%2Fhugo`

It would allow cnp the path and in the future make the url more similar when using other apps, eg for collabora: `https://phoenix.owncloud.com/index.html#collabora/eos%2Fusers%2Fhugo`?

**Comment by butonic** [comment]
might be related to spaces ... but there really is no reason to have `%2F` after the `#` in the url

**Comment by LukasHirt** [comment]
This requires first a update to vue-router@4 which requires vue@3. @fschade thought of a dirty hack which could do this already now but we decided against it and delay this until the update of vue and vue-router.

**Comment by labkode** [comment]
@LukasHirt any idea of the proposed update of the vue components?

**Comment by LukasHirt** [comment]
> any idea of the proposed update of the vue components?

No progress so far. The update is not part of the current sprint. We were focusing on our accessibility tasks at the moment because of the WCAG certification. Is this ticket urgent for you? Last time I heard it wasn't, so we weren't putting too much priority to it.

**Comment by labkode** [comment]
Hi @LukasHirt, it is as we plan to expose the new system, where user would be able to copy/paste the url to access the resources and if the  URL changes this will break behaviour.

**Comment by LukasHirt** [comment]
The current sprint ends in two weeks - should we escalate this and tackle this already @pmaier1 or would it be possible to wait until the next one @labkode ?

**Comment by labkode** [comment]
@LukasHirt it can wait until next one, thanks for following it up

**Comment by kulmann** [comment]
We were thinking about an entirely new URL format recently. There was some concepting done here https://github.com/owncloud/web/issues/5313 but it stalled lately. Needs to be on our agenda again. cc @tbsbdr

**Comment by pascalwengerter** [comment]
At least the %2F encoding should be fixed via #5715 (patched until we switch to Vue3) and just landed in master, closing this issue for now (yet we'll perhaps need some more routing-related ones in the future)
