### ISSUE TITLE
Tooltip in file list cell is not localized

### ISSUE THREAD

**Issue by hosy** [owncloud/web#4597]
Tooltips for `Add People` and `Create and copy public link` is currently not localized

### Steps to reproduce
1. Change language to non English 
2. Hover the mouse over this items in the file list

### Expected behaviour
Tooltips are localized

### Actual behaviour
Tell us what happens instead

<img width="436" alt="Bildschirmfoto 2021-01-08 um 15 37 48" src="https://user-images.githubusercontent.com/736109/104027480-be6ba700-51c7-11eb-8137-617ba25dcabd.png">

**Comment by fschade** [comment]
done by latest translations
