### ISSUE TITLE
Updating uploaded .txt file containing long contents throw an error

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#4605]
Note: works fine for `.md` file 

### Steps to reproduce
1. upload a `.txt` file with large contents
2. open file in the editor
3. try to save some changes on the editor

Error message:
![erlog](https://user-images.githubusercontent.com/52366632/104286488-36461400-54dd-11eb-97bf-a1d516fdbbf0.png)

Video Reference:

https://user-images.githubusercontent.com/52366632/104286521-42ca6c80-54dd-11eb-86bd-0953784865c6.mp4

### Server configuration
**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** MySql

**PHP version:** 7.4.3

**ownCloud version:** 10.6.1alpha (git)

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.6.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_sharing: 0.14.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - notifications: 0.5.2
  - oauth2: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - testing: 0.1.0
  - updatenotification: 0.2.1
```

**Comment by pascalwengerter** [comment]
@saw-jan do you have any indication how large the file has to be for the error to occur? :)

**Comment by saw-jan** [comment]
The issue is still relevant.
@pascalwengerter, you can use the `lorem-big.txt` from `tests/e2e/filesForUpload`. I retested with that one.

**Comment by JanAckermann** [comment]
related to #6947
