### ISSUE TITLE
Loading of avatars fails with 500 error

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#4610]
### Steps to reproduce
1. Load any file list where column "owner" or "shared with" is present (e.g. "Shared with me " or "shared with others")
2. AJAX Calls to load avatars fail (see dev console)

### Expected behaviour
500 error should not happen 

### Actual behaviour
GET https://cloudurl.com//remote.php/dav/avatars/username/128.png fails with 500 status

#### Browser log
```
Error loading avatar image for user "archive":  Unexpected status code 500 core.bundle.js:366:52759
    setUser https://cloudurl.com/index.php/apps/web/core/core.bundle.js:366
```

**Comment by hurradieweltgehtunter** [comment]
Just saw that the avatar URL has a double slash:
https://cloudurl.com**//**remote.php/dav/avatars/username/128.png

Removing one slash manually and resending the request makes it return with a 404 (which might be bevause the user I tsted with has no avatar). Anyhow, 404 is much better than 500.

**Comment by individual-it** [comment]
500 should not be returned anyway, if the client sends a wrong request the server should not return 500

ToDo QA-team:
- [ ] reproduce in what case 500 error are returned
- [ ] create (API) tests for that cases

**Comment by individual-it** [comment]
for me `https://localhost:9200//remote.php/dav/avatars/admin/128.png` is requested and 404 is returned
I've updated the topBar image in the tests here: https://github.com/owncloud/web/pull/4773
