### ISSUE TITLE
Avatars get reloaded

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#4611]
### Steps to reproduce
1. Load filelist with avatars (e.g. "Shared with me" or "Shared with others"); have many list entries to be able to scroll
2. Wait until avatars are loaded
3. Scroll down until any avatar is scrolled out of viewport
4. Scroll up again until avatar is in viewport

### Expected behaviour
Avatar should be loaded initially and stay.

### Actual behaviour
Each avatar is loaded again each time it comes into viewport:
AJAX call to `GET https://cloudurl.com//remote.php/dav/avatars/username/128.png`

**Comment by pascalwengerter** [comment]
@hurradieweltgehtunter could you check if that's still the case sometime next week/once web `v3.1.0` is officially released? We've added some caching for the avatar images now

**Comment by hurradieweltgehtunter** [comment]
Quite hard to reproduce since we don't have oc web enabled in our internal cloud anymore :/

**Comment by fschade** [comment]
fixed by https://github.com/owncloud/web/pull/5194
