### ISSUE TITLE
Password protected public links broken in authenticated context

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#4614]
### Steps to reproduce
1. Create a public link
2. Set a password for the public link
3. Open the public link within your active browser session

### Expected behaviour
The public link loading page should ask for the password of the public link

### Actual behaviour
A `403 Forbidden` comes back from the `PROPFIND` on the public-files dav endpoint for the public link (e.g. this: `https://cloud.owncloud.com/remote.php/dav/public-files/EQUE5lucS5WNWQI`) and the UI shows an error page about missing DAV read privileges (see screenshot).

<img width="891" alt="Screenshot 2021-01-14 at 23 15 06" src="https://user-images.githubusercontent.com/3532843/104656234-3f8ed680-56bf-11eb-958a-72515e18077e.png">

**Comment by individual-it** [comment]
ToDo QA-team:
- [ ]  reproduce, check if there are UI tests that cover this case and if not add UI tests for it

**Comment by HariBhandari07** [comment]
@kulmann this issue is not reproduced locally on my machine as well on drone ci. Can you please check if this test https://github.com/owncloud/web/pull/4686/files covers the issue and please confirm if the issue still exists for you.

**Comment by HariBhandari07** [comment]
@kulmann  this issue is not reproduced locally and on drone CI. Here's a PR https://github.com/owncloud/web/pull/4686 demonstrating the issue is not reproduced.

**Comment by kulmann** [comment]
I can still reproduce it. The issue lacks a description of the environment though. I think I only told it to you in the chat, but just to be sure:
The environment is an ownCloud 10.6.0 with oauth2 app and ownCloud Web running either from the dev server (`yarn serve`) or as the oc10 app from marketplace. Can you check again? The issue is still happening for me. @HariBhandari07

**Comment by kulmann** [comment]
I recently upgraded to current master and (because I do that with a script for my dev instance) also reset the config. The issue disappeared. Switching back to 10.6 didn't let the issue resurface. So I suppose that it's related to config. Closing here until it pops up somewhere again. Thanks for your awesome work @HariBhandari07
