### ISSUE TITLE
Phoenix is mentioned in visual regression tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#4620]
PR #4574 created the infrastructure for the first visual regression tests. There were some references in that PR  to "phoenix", particularly in `.drone.star` - for example, uploading to:
```
'bucket': 'phoenix'
```

Migrate these to "web".

**Comment by HariBhandari07** [comment]
Blocked as S3 bucket is not renamed.

**Comment by dpakach** [comment]
Fixed by https://github.com/owncloud/web/pull/4959/files
