### ISSUE TITLE
web 1.0.2

### ISSUE THREAD

**Issue by micbar** [owncloud/web#4623]
### Reason

- Release needed for the correct version bump.

### Product approval 

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [ ] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [ ] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" #4638 

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [ ] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [ ] Create github tag for `v${version}RC1` on release branch
- [ ] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [ ] Upload as Github release using changelog entries
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [ ] Publish tarball for customers (see handbook in confluence for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [ ] Rename QA milestone to `$version`
- [ ] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [ ] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [ ] Close the milestone
- [ ] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by micbar** [comment]
@jnweiger Only needs a quick sanity check, install and enable.

**Comment by jnweiger** [comment]
My first attempt to use the above guide failed: https://github.com/owncloud/QA/blob/master/Server/Test_Plan_web.md

The Settings -> New Design only show a blank page. Nothing in docker logs, nothing in owncloud.log

**Comment by micbar** [comment]
Check browser log and Console

**Comment by micbar** [comment]
I followed the guide yesterday, it worked, same for @pmaier1

**Comment by jnweiger** [comment]
## Issues opened while testing

* #4636 - [QA] blank page with trivial syntax errors in config.json

**Comment by jnweiger** [comment]
@pmaier1 @micbar please evaluate the new and old issues.
