### ISSUE TITLE
[QA] blank page with trivial syntax errors in config.json

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#4636]
Seen with web-1.0.2

Follow the instructions at https://github.com/owncloud/QA/blob/master/Server/Test_Plan_web.md

but introduce a trivial syntax error in config.json -- e.g. a trailing comma `,` before closing `}` brace:
```
      "title": { "en": "Classic Design", "de": "Dateien", },
```

* the oauth2 authorization is performed, 
* then the browser is redirected to a blank web page.
* server has no error messages, neither in the docker logs output, nor in `owncloud.log` with log verbosity "Everything".
* firefox console reports (only)
![image](https://user-images.githubusercontent.com/1108546/105251013-0650dd80-5b7b-11eb-93d7-591ecc3299dd.png)

Expected behaviour: The json syntax error is reported. Somewhere.

**Comment by micbar** [comment]
Not so easy. The same happens when you add a comment in the json file.

@kulmann @LukasHirt We could add config.json validation, but please be sure that this doesn't happen on every request.

**Comment by LukasHirt** [comment]
> but please be sure that this doesn't happen on every request.

We fetch the config once when Web is opened: https://github.com/owncloud/web/blob/5878eeb7a9d7a1ef9259c1942d0ac8be57ecef02/src/web.js#L214

So it should be already safe to do the validation and not be afraid of having it in every request. The config is then afterwards saved to store.

**Comment by LukasHirt** [comment]
Something to consider https://www.npmjs.com/package/jsonschema

**Comment by individual-it** [comment]
ToDo QA-Team:
- [ ]  add UI tests for this case

**Comment by LukasHirt** [comment]
> add UI tests for this case

@individual-it Would it be possible to get this done with unit tests?

**Comment by individual-it** [comment]
good thought, I haven't looked into what they currently doing but I've changed the todo above
