### ISSUE TITLE
[QA] multiple errors in browser console

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#4637]
Seen with web-1.0.2 in owncloud server 10.6.0

Follow the setup instructions at https://github.com/owncloud/QA/blob/master/Server/Test_Plan_web.md for http-only:

* visit Settings -> New Design
* firefox console shows numerous errors:

![image](https://user-images.githubusercontent.com/1108546/105251410-b7577800-5b7b-11eb-815e-53e5f85ffa85.png)

Expected behaviour:
 * no error messages in the browser console when operating normally. (ideally)
 * at least: more errors when loading fails. (Currently e.g. #4636 has less console errors)

**Comment by jnweiger** [comment]
In an https-enabled server, the console errors are a bit different:

![Uploading image.png…]()

**Comment by pascalwengerter** [comment]
@jnweiger is that still the case? I remember @wkloucek changing some stuff regarding that

**Comment by wkloucek** [comment]
> @jnweiger is that still the case? I remember @wkloucek changing some stuff regarding that

I didn't touch any thing related to these specific errors. I wonder if we allow inline scripts on the whole route of the Web frontend. We already have it for some places, eg:

https://github.com/owncloud/web/blob/10f17f36ba5efb7253292f4e8b53c0cbcbb63853/packages/web-integration-oc10/lib/Controller/FilesController.php#L122

**Comment by kulmann** [comment]
Inline scripts are allowed for the entire index.html file, which is basically the full ownCloud Web.

**Comment by pascalwengerter** [comment]
Closed as fixed, we'll have to check for new ones every once in a while ofc
