### ISSUE TITLE
[QA] files view collapses whitespace

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#4639]
Seen with web-1.0.2 in owncloud server 10.6.0

Follow the setup instructions at https://github.com/owncloud/QA/blob/master/Server/Test_Plan_web.md for http-only:

*    visit Settings -> New Design
*  + New -> New folder ...
    `New  Folder` with two spaces in between.
* copy that folder name 
 
![image](https://user-images.githubusercontent.com/1108546/105253917-bd038c80-5b80-11eb-9a41-fe2a52a3df4c.png)

* paste into an editor and count whitespaces. There is only a single whitespace in the name.

* when opening the rename dialog, we can see that actually there are two whitespaces:
![image](https://user-images.githubusercontent.com/1108546/105254221-55017600-5b81-11eb-90ec-ad96cd9a2ebe.png)

Expected behaviour: file and folder names survive cop and paste without any changes.

**Comment by kulmann** [comment]
We tackled this rendering glitch in the new files list component in the design system. Currently integratnig it into ownCloud web. This issue will be fixed by https://github.com/owncloud/web/pull/4627
