### ISSUE TITLE
[QA] mediaviewer in web app offers less functionality than files_mediaviewer-1.0.4

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#4641]
Seen with web-1.0.2 in owncloud server 10.6.0

Follow the setup instructions at https://owncloud.github.io/clients/web/deployments/oc10-app/

* workaround #4640 
* visit Settings -> New Design
* click on a JPG file in the Photos folder.
* photos cannot be rotated or zoomed.

Expected behaviour: both mediaviewers offer identical functionality  (or the "new design" one offers more)

Workaround: use files_mediaviewer app 1.0.4 or later.

**Comment by micbar** [comment]
these two implementations are not the same and do not have the same feature set

**Comment by kulmann** [comment]
The two mentioned features "rotate" and "zoom" are part of https://github.com/owncloud/web/issues/7160 - since that issue is more specific I'm closing this one here in favour of the linked one.
