### ISSUE TITLE
[QA] Favorites are harder to reach than in classic design

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#4644]
Seen with web-1.0.2 in owncloud server 10.6.0

Follow the setup instructions at https://owncloud.github.io/clients/web/deployments/oc10-app/

*  visit Settings -> New Design
*  Setting Favorites is the far right 3-dots menu, a) In the heading as a star icon, and b) as a text element "Mark as favorite":
![image](https://user-images.githubusercontent.com/1108546/105322400-1f807b00-5bc9-11eb-8809-0277ff3fd267.png)
Why twice? What is the difference between the two ways?
----
* In the Classic Design: Favorites were easily reachable at the left of each Thumbnail with the well known star icon.
![image](https://user-images.githubusercontent.com/1108546/105321840-4be7c780-5bc8-11eb-8fb6-7b77822aedc7.png)

Expected behavior: 
* Usability would not degrade from Classic to new Design:
  * All favorites in a folder are directly visible without the need of clicking open one menu per folder entry
  * redudant textual clutter is avoided
  * excessive mouse travel is avoided

**Comment by kulmann** [comment]
There is also the action `Mark as favorite` in the list of actions. But I agree, having it accessible from the files list would make sense. I'd love to have it as a quick action. Compared to the classic frontend it would switch sides (far right instead of far left) then, but I'd be fine with that.

**Comment by pascalwengerter** [comment]
@tbsbdr needs a PM/UX decision :)

**Comment by tbsbdr** [comment]
as benedikt said - should be covered by a quickaction. additionally favorising will be available via righclick. added this issue to our quickaction-epic

**Comment by pascalwengerter** [comment]
Okay so will get closed via #5576 🌟

**Comment by kulmann** [comment]
> Okay so will get closed via #5576 🌟

Nope, because that PR doesn't introduce favorites as quickaction. ;-)

**Comment by JanAckermann** [comment]
Favorites will be implemented with a new look and feel in web/ocis, closing here
