### ISSUE TITLE
Link to developer manual in contribution guides is broken

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#4655]
### Steps to reproduce
1. Think about contributing to this repository
2. Go to [the contribution guidelines](https://github.com/owncloud/web/blob/master/.github/CONTRIBUTING.md)
3. Click on the link to the [developer manual](https://owncloud.com/dev/) to further educate yourself

### Expected behaviour
I've done some research and perhaps [this page](https://owncloud.com/docs-guides/) was meant to be linked

### Actual behaviour
You find a 404 error page

### Server configuration
Non applicable

### Client configuration
**Browser:** Any

**Operating system:** Any

### Logs
Non applicable

**Comment by pascalwengerter** [comment]
PR from my side incoming

**Comment by phil-davis** [comment]
See PR review comment https://github.com/owncloud/web/pull/4656#pullrequestreview-575556343

@kulmann intends to make another PR to update the words and link to a more-specific place in the docs...
