### ISSUE TITLE
Preview images of media files with .webm and .ogg formats are not loaded

### ISSUE THREAD

**Issue by jasson99** [owncloud/web#4667]
### Steps to reproduce
1. Upload a file `sampleOgg.ogg` or `sampleWebm.webm`
2. The preview image of the uploaded file is not visible
![Screenshot from 2021-01-28 10-29-08](https://user-images.githubusercontent.com/40829116/106091228-0f7e1380-6154-11eb-920d-32b5cca92033.png)

### Expected behaviour
The preview image of media files with .ogg and .webm formats should be visible

### Actual behaviour
The preview images are not visible

**Comment by fschade** [comment]
Need to be implemented in [thumbnails](https://github.com/owncloud/ocis/tree/master/thumbnails) service. For videos it's hard to decide which frame should be used for preview. I leave this open for discussion and collecting ideas.

cc: @C0rby

**Comment by C0rby** [comment]
In oc10 we display a generic video icon for video files.
I would propose to do the same for oCIS since thumbnailing for videos is a bit more complex.

**Comment by pascalwengerter** [comment]
Closing this in favor of #4667
