### ISSUE TITLE
missmatch of return value types and used value types in provisioning context

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#4679]
`getDisplayNameOfDefaultUser()` &  `getEmailAddressOfDefaultUser` return `null` if the user is not in the list but `createUser` checks `if (displayName !== false) {` same for email

I just notices that while trying to use the context for desktop client tests and getting a `Bad Request` response because `null` is in the email field `key=email&value=null`

how does that work in web?

**Comment by dpakach** [comment]
Mabye because we never create users in ui tests that are not in the default user list. but fixed it in https://github.com/owncloud/web/pull/4782 just in case
