### ISSUE TITLE
Adjust webUI test scenarios with "tries to" in its step

### ISSUE THREAD

**Issue by swoichha** [owncloud/web#4680]
Currently we have tests with "tries to" in Gherkin. Which are used when the actions (like MOVE, COPY, RENAME) performed intended to give an error which are checked mostly in `Then` step. 

But, now we want to check if the action is actually performed or not. 

For example:
```
  Scenario: cancel moving a file
    Given user "user1" has logged in using the webUI
    And the user has browsed to the files page
    When the user tries to move file "data.zip" into folder "simple-empty-folder" using the webUI
    And the user cancels the attempt to move file into folder "simple-empty-folder" using the webUI
    Then file "data.zip" should be listed on the webUI
    But  file "data.zip" should not be listed in the folder "simple-empty-folder" on the webUI
```
 Here in this scenario we want to cancel moving of a file but this test doesn't actually move a file. Maybe we can do more precise while writing step definition or we can have more explicit description of each specific scenario.

**Comment by phil-davis** [comment]
We need to think of words that explain enough of what is happening here. Instead of "tries to" we could write "start to" - or write more words explaining what point in the user workflow the user is getting to.

**Comment by phil-davis** [comment]
```
When the user opens the move file dialog to move file "data.zip" into folder "simple-empty-folder" using the webUI
```
Maybe?

**Comment by phil-davis** [comment]
For these sort of cases, when we want to test scenarios that "interrupt" the normal workflow of the UI, we will write much smaller `When` steps that take the scenario through more detail of the UI workflow. That will allow the scenario to stop at any point in the workflow and then take another path (for example, "the user cancels...").

For example, the UI workflow might have 3 steps like:
- the user opens the file actions menu
- the user selects the "Move" action
- the user selects "some-folder" as the place to move the file

For the "normal" workflow, we keep having a single step written in the scenario. The single describes what the user wants to achieve, not the detail of all the "clicks". That makes the "normal" scenarios more readable and less brittle.

**Comment by phil-davis** [comment]
I will add some documentation. See issue https://github.com/owncloud/docs/issues/3128 for that.

**Comment by pascalwengerter** [comment]
@SwikritiT is this resolved now? :)

**Comment by SwikritiT** [comment]
@pascalwengerter the issue described is addressed by the PR above but we still need to do some refactoring in test scenarios with `tries to` in its step. 

For Example 
```
 Scenario: copy a file into another folder with no change permission
    Given user "Brian" has been created with default attributes
    And user "Brian" has shared folder "simple-folder" with user "Alice" with "read" permissions
    And user "Alice" has logged in using the webUI
    When the user tries to copy file "lorem.txt" into folder "simple-folder (2)" using the webUI
    Then it should not be possible to copy into folder "simple-folder (2)" using the webUI
```
In this scenario , at `When`  step, we want user to actually click the `copy` button but our current implementation selects the folder only and returns. So, there's still some refactoring needed.

**Comment by HariBhandari07** [comment]
"tries to" for `copy` and `move` have been adjusted here https://github.com/owncloud/web/pull/4824 and for `rename` no need to make extra adjustment as it already does what it is supposed to do.
