### ISSUE TITLE
web with oc10 + openidconnect using ocis-idp is not working

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#4742]
### Description
Using setup https://owncloud.github.io/ocis/deployment/bridge/
We used oc10 + openidconnect setup to run tests in CI but it is failing now. The setup was already not working with the latest version of ocis-glauth, so we had to run with a old version of ocis-glauth https://github.com/owncloud/web/blob/master/.drone.star#L1282

this needs to be investigated and fixed. We also need to discuss what setups to use for running tests in CI
https://github.com/owncloud/web/issues/4713

Logs
```
2021-02-15T13:08:59+05:45 DBG Bind request basedn=dc=example,dc=com binddn=cn=idp,ou=sysusers,dc=example,dc=org name=glauth service=glauth src={"IP":"127.0.0.1","Port":54014,"Zone":""} verbosity=6
2021-02-15T13:08:59+05:45 INF BindDN not part of our BaseDN basedn=dc=example,dc=com binddn=cn=idp,ou=sysusers,dc=example,dc=org name=glauth service=glauth verbosity=2
2021-02-15T13:08:59+05:45 ERR identifier failed to logon with backend error="ldap identifier backend logon connect error: LDAP Result Code 49 \"Invalid Credentials\": " service=idp
2021-02-15T13:08:59+05:45 DBG  bytes=44 duration=1.139746 method=POST path=/signin/v1/identifier/_/logon proto=HTTP/1.1 request=298d034f-213f-4686-9568-a14983360354 service=idp status=500
```

Looking at the loogs it seems like it uses the binddn `cn=idp,ou=sysusers,dc=example,dc=org` to connect to the ldap server, 
when we specify `LDAP_BINDDN='cn=admin,ou=users,dc=example,dc=com'` for the ocis-idp service

**Comment by pascalwengerter** [comment]
@wkloucek could you give this a look?

**Comment by wkloucek** [comment]
Currently oC10 tests are done with oAuth2 authentication in the Web CI. Is it still up to date to switch this to OIDC, too? (like we do it with oCIS).

I don't see the benefit we would gain from it. In the current state, Web is tested against oAuth2 and OIDC, which is good. Setting up OIDC for oC10 hase some more overhead than oAuth2 (adding graph-api app, configuring the OIDC app, running Glauth, running and OIDC provider vs. installing the oAuth2 app).

@kulmann @phil-davis Please share your thoughts on this. If it is desirable to use OIDC also with oC10, I can have a look.

**Comment by kulmann** [comment]
Afaik it's part of the migration strategy to migrate oc10 instances to OIDC for all clients (web, desktop, ios, android). Maybe @micbar @michaelstingl can tell if that's still valid? If yes, this would be required.

**Comment by wkloucek** [comment]
> OIDC for all clients (web, desktop, ios, android). Maybe @micbar @michaelstingl can tell if that's still valid? If yes, this would be required.

Yes, for sure it is still needed for migration. But we already test Web with OIDC (on oCIS). That's why I ask, if it is really needed on oC10, too.

**Comment by kulmann** [comment]
Yes, as long as it's part of the migration strategy we should have some smoke tests running. Not the full suite though.

**Comment by JanAckermann** [comment]
Unfortunately we discontinues oc10 support on web, therefore closing
