### ISSUE TITLE
Align with 10.7 sharing behavior

### ISSUE THREAD

**Issue by pmaier1** [owncloud/web#4762]
## User story
As a user I want to share with other users by entering their email address. Currently I usually get two results when I search for a user
1. the real user on the system and
2. a federated user (because federation IDs have the same syntax like email addresses). As I'm not familiar with ownCloud specifics, I don't know what a "federated" user is.
As the lookup for the "real user" takes some time in my installation, it happens that I only see the "federated user" first. When I'm too quick, I click on it and see the share failing (because there actually is no federated user; I'm looking for the real user) which I don't understand. At this point I open a support request.

## Solution approach
Change the sharing autocomplete to only display the federated user 
1. once the regular user search has finished and
2. did not find results for the input provided

As a consequence in case that the entered email address matches a known user, only show that user.

**Comment by kulmann** [comment]
This is properly solved with OCM 1.1 in oCIS. Federated users get discovered properly.
