### ISSUE TITLE
Audit #1 – General Overview when logged in – Adding more headlines

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4764]
Connected to Audit 1, see #4300
1.2 General Overview when logged in, URL: https://ocis-a11y.owncloud.works/#/files/list

# Issue
In 1.3.1a, BITV's requires that contents are structured by headlines, if a page is "information-oriented". While I personally consider the phoenix interface functionality-oriented, a tester could disagree.

# Remediation
Regardless: Adding [visually-hidden](https://www.a11yproject.com/posts/2013-01-11-how-to-hide-content/) headlines above certain sections won't hurt nobody. My ideas:

- `<h2 class="visually-hidden">Navigation</h2>` above `.oc-sidebar-nav ul`, and an IDREF to said headline in the `<nav>`: `<nav class="oc-sidebar-nav" aria-labelledby="navHeadline"><h2 lass="visually-hidden" id="navHeadline">Navigation</h2> ...`
- Same for the container wrapping all account functionality: `<h2 class="visually-hidden">Account management</h2>`
- Same for the files table: `<h2 class="visually-hidden">Files in this folder</h2>`

This means the final headline structure could be:
h1 "New Folder" (actual name of the folder one is in)
h2 "Files in this folder"
h2 "Navigation"
h2 "Account Management"

**Comment by pascalwengerter** [comment]
Closing this since #5018 is merged and we're waiting for feedback (and will open new tickets with the requested changes from the `a11y` audit)
