### ISSUE TITLE
Audit #1 – General Overview when logged in – Text zoom causes visual regressions

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4765]
Connected to Audit 1, see #4300
1.2 General Overview when logged in, URL: https://ocis-a11y.owncloud.works/#/files/list

# Issue
For BITV 1.4.4a, I had to resize the window to 1280x768 pixels, and then **text zoom** to 200%. In the data table, I found the following:

![CleanShot 2021-02-24 at 11 17 20](https://user-images.githubusercontent.com/505181/108986003-f6ed1480-7691-11eb-918f-c2ffc999a19c.png)

This counts as "loss of content".

# Remediation
"Einstellungszeit" is actually a button, whose text content does not break. An idea would be to add `max-width: 100%;` to the button.

**Comment by pascalwengerter** [comment]
Closing this since #5018 is merged and we're waiting for feedback (and will open new tickets with the requested changes from the `a11y` audit)
