### ISSUE TITLE
Audit #1 – General Overview when logged in – Nav landmark disappearing

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4766]
Connected to Audit 1, see #4300
1.2 General Overview when logged in, URL: https://ocis-a11y.owncloud.works/#/files/list

# Issue
In the mobile state/mediaquery, the main navigation landmarks seems to get lost. The trigger for the mobile menu then lives directly in the header landmark.

# Remediation
Keep the navigation landmark, and make sure that both triggering button and the navigation list itself is kept in it.

Sketch:
```
nav
  trigger-button
  ul
```

Related BITV test step: 2.4.1a

**Comment by pascalwengerter** [comment]
Closing this since #5018 is merged and we're waiting for feedback (and will open new tickets with the requested changes from the `a11y` audit)
