### ISSUE TITLE
Audit #1 – General Overview when logged in –  Add People -> Links: "Ablaufdatum" label and "Ablaufdatum" input not connected  

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4769]
Connected to Audit 1, see #4300
1.2 General Overview when logged in, URL: https://ocis-a11y.owncloud.works/#/files/list

# Issue
Once the user starts the "Add people" process from a file or folder, opens the "Links" accordion, click "Öffentlicher Link" and discovers the "Ablaufdatum" input they find the label connected to a div instead of an input.

# Remediation
`<label for="oc-files-file-link-expire-date"></label> <input id="oc-files-file-link-expire-date" type="text" placeholder="Ablaufdatum" class="vdatetime-input">`.

Knowing Vue, this looks like inheritAttrs: false could help: https://stackoverflow.com/questions/56224091/what-are-inheritattrs-false-and-attrs-used-for-in-vue. Also page 54 of Accessible Vue ;)

**Comment by pascalwengerter** [comment]
Closing this since #5018 is merged and we're waiting for feedback (and will open new tickets with the requested changes from the `a11y` audit)
