### ISSUE TITLE
improve testing docs

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#4775]
things that I miss:
- [ ]  ocis needs to run with the owncloud storage: `PROXY_ENABLE_BASIC_AUTH=true STORAGE_HOME_DRIVER=owncloud STORAGE_USERS_DRIVER=owncloud`
- [ ]  the selenium command needs to be run from the web folder
- [ ] need more explanation for the `OCIS_SKELETON_DIR` ?
- [ ] starting the redis server is not mentioned

@LukasHirt do we need to mention those things and are there more things to add/correct in the testing docs?

**Comment by LukasHirt** [comment]
> ocis needs to run with the owncloud storage

Is it not a default value?

> starting the redis server is not mentioned

Do we actually need the redis server?

**Comment by individual-it** [comment]
the default storage driver is ocis, for that we need magic commands to cleanup the user data see https://github.com/owncloud/ocis/blob/aed03b5bf5ffcd6ef0fee0674659f5c7b8004f73/.drone.star#L459 - that is not implemented in the web tests (waiting for the provisioning API to cleanup itself after user deletion)
so we need to run the owncloud storage for web tests (https://github.com/owncloud/web/blob/036de0edb10929421f449e4efc80d66a3d7daf30/.drone.star#L1452-L1453) and the owncloud storage driver needs redis for some operations (I believe favorites and maybe also sharing)
