### ISSUE TITLE
Batch deletion of files and folders fails after throwing an error in webUI, but the resource seems to be deleted even after the error message.

### ISSUE THREAD

**Issue by jasson99** [owncloud/web#4784]
## Description:
1. Run this test: `webUITrashbinFilesFolders/trashbinFilesFolders.feature:56` (Scenario: Delete multiple files at once and check that they are all in the trashbin)
2. There is sometimes a problem in the deletion of simple-folder during batch deletion. An error about deletion of the folder is shown in UI but the folder seems to be deleted. However, the folder in trashbin item has a preceding slash `/`. During that case, the deletion error and the trashbin items are as follows: 

![Screenshot from 2021-03-02 15-53-07](https://user-images.githubusercontent.com/40829116/109632726-76d21d80-7b6f-11eb-908a-87d58ab6a637.png)
    
![Screenshot from 2021-03-02 15-32-47](https://user-images.githubusercontent.com/40829116/109631444-0d054400-7b6e-11eb-83f2-303bd1901f25.png)

![Screenshot from 2021-03-02 15-35-35](https://user-images.githubusercontent.com/40829116/109631472-15f61580-7b6e-11eb-85e0-08e9cd0ffd17.png)

3. But during the normal deletion, the trashbin items are as follows:

![Screenshot from 2021-03-02 15-46-07](https://user-images.githubusercontent.com/40829116/109631881-856c0500-7b6e-11eb-9edf-98775c6ff6f4.png)

![Screenshot from 2021-03-02 15-33-08](https://user-images.githubusercontent.com/40829116/109631625-3cb44c00-7b6e-11eb-8446-1d73c62e778a.png)

The difference between normal run and the intermittent failure case can be easily observed in the following screen record: 

https://user-images.githubusercontent.com/40829116/109633965-cfee8100-7b70-11eb-845f-1c07637679db.mp4

**Comment by jasson99** [comment]
The server log is as:

```
{"reqId":"750427cd-021d-401c-af4a-e28eea05201f",
"level":4,
"time":"2021-03-01T10:48:27+00:00",
"remoteAddr":"::1",
"user":"Alice",
"app":"webdav",
"method":"DELETE",
"url":"\/oc\/remote.php\/webdav\/simple-folder",
```
```"mmessage":"Exception: An exception occurred while executing 'UPDATE `oc_filecache` SET `storage` =  ?, `path` = ?, `path_hash` = ?, `name` = ?, `parent` =? WHERE `fileid` = ?' with params [44, \"files_trasbin\\\/files\\\/simple-folder.d1614595707\", \"52dfb8e9c7fbfd5cacfc4e6a85890264\", \"simple-folder.d1614595707\", 2147512418, 2147512300]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '44-52dfb8e9c7fbfd5cacfc4e6a85890264' for key 'fs_storage_path_hash': {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Message\":\"An exception occurred```

**Comment by individual-it** [comment]
I believe the real issue is in core see https://github.com/owncloud/core/issues/38221
closing this one
