### ISSUE TITLE
Audit #1 – Share a single file – Datepicker Ablaufdatum: tabular data, but no table

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4789]
Connected to Audit 1, see #4300 
1.5 General Overview when logged in, URL: https://ocis-a11y.owncloud.works/#/files/list

# Issue
The days of the month are presented in a grid and are usually marked up in a data table

# Remediation
Using `<table>` instead of `<div>`

**Comment by pascalwengerter** [comment]
Closing this since #5018 is merged and we're waiting for feedback (and will open new tickets with the requested changes from the `a11y` audit)
