### ISSUE TITLE
selectFolder in locationPicker.js does not select anything

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#4806]
the function `selectFolder` in `locationPicker.js` does not select any folder but just moves the mouse to it, so if that function is really needed (I doubt it) it has to be renamed

**Comment by HariBhandari07** [comment]
This issue can only be addressed after https://github.com/owncloud/web/issues/4680 is resolved.

**Comment by saw-jan** [comment]
`selectFolder` in `locationPicker.js`, what it does is it opens the destination folder where the file(s) will be moved/copied into.

@individual-it do you still think that the changes are needed?
Or Does renaming to something like `openFolder` or `navigateToFolder` sound good?

**Comment by individual-it** [comment]
I think we can close this, the current implementation looks good to me
