### ISSUE TITLE
Intermittent failing of sharing notification tests

### ISSUE THREAD

**Issue by Talank** [owncloud/web#4828]
The scenario `notifications about new share is displayed` is failing intermittently in CI. Failing step is `And the user should see 2 notifications on the webUI with these details`. For the further details, refer to these builds in drone.
- https://drone.owncloud.com/owncloud/web/13622/10/14
- https://drone.owncloud.com/owncloud/web/13612/10/14

Need to investigate why is these `webUISharingNotifications` tests are failing.

**Comment by HariBhandari07** [comment]
fixed
