### ISSUE TITLE
update sdk

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#4829]
the SDK is now able to work with node.js as well as the browser
would be a good time to have an update here to make sure all works well
should be as simple as using the current version (1.0.0-2114)in packages/web-runtime/package.json and run `yarn install`. 

please ping @fschade on that PR

**Comment by dpakach** [comment]
Blocked by https://github.com/perry-mitchell/webdav-client/issues/261

**Comment by pascalwengerter** [comment]
Closed via #5063
