### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/web#4850]
PR: https://github.com/owncloud/web/pull/4627 is failing and needs investigation
- [ ] https://drone.owncloud.com/owncloud/web/13754/5/14 is a random failure / passing locally (WIP @kiranparajuli589)
- [x] https://drone.owncloud.com/owncloud/web/13754/8/14 is a random failure / passing locally (WIP @Talank )
- [ ] https://drone.owncloud.com/owncloud/web/13754/13/14 needs an update of the topBar baseline image, but that doesn't work. image doesn't get updated when running according to the docs.@SwikritiT 
- [ ] https://drone.owncloud.com/owncloud/web/13754/41/14 no idea (WIP @saw-jan )
- [x] https://drone.owncloud.com/owncloud/web/13754/50/14 some of these are even marked as expected failures, but this pipeline doesn't seem to look at the expected failures files at all. (@jasson99 )
 - [x] https://drone.owncloud.com/owncloud/web/13754/52/14 same as above. (@jasson99 )
 - [ ] https://drone.owncloud.com/owncloud/web/13754/63/11 also needs the topbar baseline image updated, but for ocis. @SwikritiT 
 - [x] https://drone.owncloud.com/owncloud/web/13754/76/11 didn't check this pipeline at all, yet. ( might be the change in line number ) (@jasson99 )

The iPhone & XGA resolution runs don't have any expected failures files configured in the drone

**Comment by Talank** [comment]
New issues have been made for skipped tests. https://github.com/owncloud/web/issues/4861 https://github.com/owncloud/web/issues/4859
