### ISSUE TITLE
public cant get access to public link shares

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#4856]
### Description
With PR https://github.com/owncloud/web/pull/4627

### Steps to reproduce
1. create a user `Alice`
2. create a folder `simple-folder`
3. upload a file inside `simple-folder` as `testfile.txt`
4. create a pubic link share for `simple-folder`
5. copy the public link of the share
6. get to a new browser tab (incognito) and open the public link just copied

### Expected behavior
- public should be able to get access the public link created by user `Alice`
- `testfile.txt` should be displayed in the files list view of the web UI

### Actual behavior
- Error message as `An error occurred while loading the public link`
- Screenshot:
![Screenshot from 2021-03-25 15-26-44](https://user-images.githubusercontent.com/39373750/112452281-8f081780-8d7e-11eb-9a81-446bcdd95218.png)

### Server configuration
**Operating system**: Ubuntu

**Web server:** https://github.com/owncloud/web/pull/4627

**Database:** mysql

**PHP version:** 7.4

**ownCloud version:** (see ownCloud admin page) ownCloud 10.7.0beta2 (git)

#### ownCloud log (data/owncloud.log)
```
No logs detected
```

#### Browser log
```
3:34:52 PM - SEVERE - http://localhost/img/app.png - Failed to load resource: the server responded with a status of 404 (Not Found)
3:34:52 PM - SEVERE - http://localhost/web/dist/#/files/public-link/UIuK5pRYfi4fxfv - Error while trying to use the following icon from the Manifest: http://localhost/img/app.png (Download error or resource isn't a valid image)
3:34:52 PM - SEVERE - http://localhost/img/app.png - Failed to load resource: the server responded with a status of 404 (Not Found)
3:34:52 PM - SEVERE - http://localhost/web/dist/#/files/public-link/UIuK5pRYfi4fxfv - Error while trying to use the following icon from the Manifest: http://localhost/img/app.png (Download error or resource isn't a valid image)
3:34:53 PM - SEVERE - http://localhost/coreremote.php/dav/public-files/UIuK5pRYfi4fxfv - Failed to load resource: the server responded with a status of 404 (Not Found)

```

**Comment by dragotin** [comment]
I can not reproduce this any more. Closing, please reopen if you disagree.
