### ISSUE TITLE
Preview of a text file is not available even when preview is enabled

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#4858]
### Description
With PR https://github.com/owncloud/web/pull/4627
### Steps to reproduce
1. login to web
2. upload a text file

### Expected behaviour
Preview of a text file as below:
![p1](https://user-images.githubusercontent.com/52366632/112461117-badbcb00-8d87-11eb-82cb-7f4b6ce23e16.png)

### Actual behaviour
No preview for a text file
![p2](https://user-images.githubusercontent.com/52366632/112461105-b7e0da80-8d87-11eb-9869-e10547ebc049.png)

### Server configuration
oc10 server from lastes master
`config.php`
```php
...
'enable_previews' => true,
...
```

**Comment by kulmann** [comment]
The preview is only available after a page reload. We'll need to load the preview when the upload is finished and the resource gets added to the store.

**Comment by LukasHirt** [comment]
It should be available, just not immediately. When the upload is finished, the load of preview is triggered. So it can take a second or two until it's displayed depending on your connection. Can you pls try it out that the preview is really not getting displayed after a brief moment?

**Comment by saw-jan** [comment]
Yeah, it's working now
previously the preview was not working also with refreshing page
