### ISSUE TITLE
Rename dialog box does not disappears after rename (random failure in CI)

### ISSUE THREAD

**Issue by Talank** [owncloud/web#4859]
The test `Scenario: Rename a file using both double and single quotes` https://github.com/owncloud/web/blob/62006051520026c5393c8c82a418bc8c38917c2d/tests/acceptance/features/webUIRenameFiles/renameFiles.feature#L86 is failing randomly in CI but passes locally all the time.

There might be a problem with renaming a file but it does not occur all the time, so need to investigate. 

Currently, the test is skipped in https://github.com/owncloud/web/pull/4627/commits/7dc0b37072bc663fb4f7b44ec579d7d005bed30b

**Comment by Talank** [comment]
refer to this PR: https://github.com/owncloud/web/pull/4852,
And these build:
- https://drone.owncloud.com/owncloud/web/13788
- https://drone.owncloud.com/owncloud/web/13783

**Comment by jasson99** [comment]
this is fixed in this pr https://github.com/owncloud/web/pull/4908
