### ISSUE TITLE
Investigate intermittent failing tests

### ISSUE THREAD

**Issue by jasson99** [owncloud/web#4861]
## Description:
 The following tests are failing randomly: 
- https://drone.owncloud.com/owncloud/web/13817/53/14
- https://drone.owncloud.com/owncloud/web/13817/52/14
- https://drone.owncloud.com/owncloud/web/13826/51/14

These 4 tests are skipped for now in this commit: https://github.com/owncloud/web/pull/4857/commits/87417333791a8a8968280e4f4e10783b4f0087cd

We need to investigate

**Comment by Talank** [comment]
For a random failure, the files rename test has been skipped. Related issue: https://github.com/owncloud/web/issues/4859

**Comment by jasson99** [comment]
Fixed in this PR: https://github.com/owncloud/web/pull/4908
