### ISSUE TITLE
Accessibility issues in site-wide search

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/web#4867]
More or less by accident (#4812) I saw that there is meant to be a general search feature, which isn't active on the basis of my audit, ocis-a11y.owncloud.works. If this would have been the case, my audit ticket regarding this would be as follows:

# Issue
Without a submit button, it is not really obvious how to trigger the search form. Voice Control users can't trigger the submission, for example. Additionally, a submission of the search form causes a change of context. This SO comment describes it in a very complete way: https://ux.stackexchange.com/a/23441. On top of that, the close button is a clickable div, that has no name, no role and no keyboard accessibility.

# WCAG test steps:
- WCAG 3.2.2
- WCAG 3.3.2
- WCAG 4.1.2
- WCAG 2.1.1

# Remediation
## Baseline
- Add a submit button (all rules regarding button labelling apply here of course)
- Make the close button a proper `<button>` (all rules regarding button labelling apply here of course)

## Best practice
- It also would not hurt to make this div a `<form>`:

![CleanShot 2021-03-26 at 11 20 47](https://user-images.githubusercontent.com/505181/112617616-79016200-8e25-11eb-961e-b1b005e337c0.jpg)

Tip: don't apply `role="search"` on a form directly, because this would change the role from form to search, and the form role would be "gone again". Think of role search as an fictional native HTML element (`<search>`).

**Comment by pascalwengerter** [comment]
@marcus-herrmann thanks for this!

Could you check out https://owncloud.design/#/oC%20Components/OcSearchBar and see if that already redeems some of the issues (e.g. the `close` div/button situation)? We'd still need to bring it to the web app, though and make it a proper `<form>`

**Comment by marcus-herrmann** [comment]
@pascalwengerter Ah I see. It looks way better!

**Comment by pascalwengerter** [comment]
Closing this since it's kinda fixed (and not within the scope of the accessibility audit) for OC10 through the ODS and search isn't implemented for oCIS
