### ISSUE TITLE
split slow running suites

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#4876]
these suites should be split:
- [x] webUISharingInternalUsersToRoot (https://github.com/owncloud/web/pull/4912)
- [x] webUISharingInternalUsers https://github.com/owncloud/web/pull/4900
- [x] webUIFiles https://github.com/owncloud/web/pull/4877
- [x] webUIResharing https://github.com/owncloud/web/pull/4922
- [x] webUISharingPublic https://github.com/owncloud/web/pull/4886

**Comment by individual-it** [comment]
all open PRs are merged, is this done?

**Comment by saw-jan** [comment]
yeah, above mentioned tests suites have been splitter to smaller suites. And drone runtime is also comparatively faster
