### ISSUE TITLE
Investigate and solve unexpected fails and passes

### ISSUE THREAD

**Issue by Talank** [owncloud/web#4878]
Some tests might be passing or failing intermittently. And the cause might be related to https://github.com/owncloud/web/issues/4850

### These tests are passing unexpectedly 
- https://drone.owncloud.com/owncloud/web/13940/5/14
-  https://drone.owncloud.com/owncloud/web/13928/5/14 @saw-jan https://github.com/owncloud/web/pull/4879
    - [x] webUIPreview/imageMediaViewer.feature:33
    - [x] webUIPreview/imageMediaViewer.feature:24
    - [x] webUIPreview/imageMediaViewer.feature:110
- https://drone.owncloud.com/owncloud/web/13940/41/14 @saw-jan https://github.com/owncloud/web/pull/4879
    - [x] webUISharingPublic/shareByPublicLink.feature:61
- https://drone.owncloud.com/owncloud/web/13940/74/11 ( these scenarios were deleted because they were duplicates)
    - [x] webUIResharing/reshareUsers.feature:235 (fixed)
    - [x] webUIResharing/reshareUsers.feature:236 (fixed)
- Share with group tests https://drone.owncloud.com/owncloud/web/14201/65/11 (fixed by #4911)
    - [x] webUISharingInternalGroups/shareWithGroups.feature:231
    - [x] webUISharingInternalGroups/shareWithGroups.feature:245

### These tests are failing unexpectedly. (Intermittent)
- https://drone.owncloud.com/owncloud/web/13940/42/14 
    - [ ] webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:92
    - [ ] webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:104
- share indicators ~~(hopefully fixed by https://github.com/owncloud/web/pull/4881/commits/e943f40aea326d112759d4d988ec4c8b193f7132)~~ @HariBhandari07  https://github.com/owncloud/web/pull/4902
    - [x] webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature:92 (https://drone.owncloud.com/owncloud/web/14052/30/14)
    - [x] webUISharingExternal/federationSharing.feature:61 (https://drone.owncloud.com/owncloud/web/14062/48/20)
    - [x] webUISharingPublic/shareByPublicLink.feature:673 (https://drone.owncloud.com/owncloud/web/14062/76/11)

**Comment by HariBhandari07** [comment]
`webUIResharing/reshareUsers.feature` unexpected passing scenarios will be fixed by https://github.com/owncloud/web/pull/4874

**Comment by Talank** [comment]
<b>TO-DO:</b>
## Unexpected failures of public link tests
- [ ] webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:92 at https://drone.owncloud.com/owncloud/web/13990/42/14, and https://drone.owncloud.com/owncloud/web/13982/42/14
- [ ] webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:104 on https://drone.owncloud.com/owncloud/web/13982/42/14

It looks like `webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:92` is hard failure and  `webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:104` is intermittent.

**Comment by HariBhandari07** [comment]
> TO-DO:
> 
> ## Unexpected failures of public link tests
> * [ ]  webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:92 at wip @HariBhandari07 https://drone.owncloud.com/owncloud/web/13990/42/14, https://drone.owncloud.com/owncloud/web/13982/42/14, https://drone.owncloud.com/owncloud/web/13986/42/14, and https://drone.owncloud.com/owncloud/web/13994/42/14
> * [ ]  webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:104 on https://drone.owncloud.com/owncloud/web/13982/42/14, and https://drone.owncloud.com/owncloud/web/13986/42/14  wip @HariBhandari07
> 
> It looks like `webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:92` is hard failure and `webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:104` is intermittent.

Both of the above fails are the same and fixing one will fix both.

**Comment by Talank** [comment]
All the failures that have been listed here and not in https://github.com/owncloud/web/issues/4919 have been fixed. So, closing this issue.
