### ISSUE TITLE
pin oc10 commit id for test-runs

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#4885]
tests are run with an defined commit id of ocis, but for oc10 we are using the QA tarball
the risk is that things change in oc10 and we only notice after the QA tarball is rebuild and a new drone job is run in web. see https://github.com/owncloud/web/pull/4879
ToDo
- [x] pin the oc10 build to a specific commit id https://github.com/owncloud/web/pull/4978
- [ ] cache the oc10 artefact to save the time rebuilding oc10

**Comment by dpakach** [comment]
@individual-it I don't think we really need to cache oc10. currently, it takes about 40-50seconds to install oc10. That less time than what it would take if we were to check the oc10 cache, pull it and install the dependencies as we won't be adding all the dependencies in the cache. So it would end up taking more time.

**Comment by individual-it** [comment]
In that case we can close the issue
