### ISSUE TITLE
Copy private link to clipboard broken in oCIS

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#4892]
### Steps to reproduce
1. Run `web` with oCIS, click on "Links" Accordion item in sidebar for random file/folder
2. Run `web` with OC10, click on "Links" Accordion item in sidebar for random file/folder
3. See that using OC10 you see a link and can click the icon to copy it to your clipboard, while in oCIS you see no link (but an icon that doesn't copy anything to clipboard)

#### OC10
![Screenshot_2021-03-30 All files - ownCloud](https://user-images.githubusercontent.com/16822008/112983098-28577500-9155-11eb-9a1a-656288f54716.png)

#### oCIS
![Screenshot_2021-03-30 files-personal - ownCloud](https://user-images.githubusercontent.com/16822008/112983109-2b526580-9155-11eb-8c08-629691bd2b50.png)

### Expected behaviour
Both OC10 and oCIS should have the same behavior, allowing the user to copy a private link to clipboard.

### Actual behaviour
oCIS either has a bug or lacks functionality here.

**Comment by butonic** [comment]
I tried to add it in https://github.com/cs3org/reva/pull/1604 but it only works when the owner accesses the link 🤪

**Comment by pascalwengerter** [comment]
We're hiding this based on capabilities now that #5018 is merged. Closing this ticket since it was originally a bug report
