### ISSUE TITLE
Unexpected behavior when renaming files

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#4893]
### Steps to reproduce
In the sidebar,
1. Rename a `folder`: The name updates correctly in both file table and sidebar heading without a page reload
2. Rename a `file` without touching the filetype-extension (e.g. change `demo.txt` to `demo2.txt`: The name updates correctly in both file table and sidebar heading without a page reload
3. Rename a `file` including the filetype-extension (e.g. change `demo.txt` to `demo.md`: The name updates correctly in the sidebar heading, but in the File table only the file name (and not the filetype-extension) gets updated dynamically. Updating the filetype-extension requires a full page reload

### Expected behaviour
File name should correctly update in Files table without having to perform a page reload

### Actual behaviour
File name only updates in Files table when name (and not extension) are changed

### Server configuration
**Backend:** oCIS (unclear about OC10)

**Comment by dragotin** [comment]
Can reproduce. Even more strange: When I change the file name (not the ext.) it was displayed with two dots - as shown on the screenshot.
![ksnip_20210526-122858](https://user-images.githubusercontent.com/1070214/119645284-2a207a80-be1e-11eb-9c50-ed429008eb57.png)

**Comment by kulmann** [comment]
Moved this issue to our fastlane. Bug probably lies somewhere in the design system's OcResource* components.

**Comment by individual-it** [comment]
this is a good example why relying on the `data-test-*` attributes is dangerous
The test attributes have changed in the DOM, but the view for the user not.
IMHO we should check the real-values and not rely only on the test attributes in E2E tests

![grafik](https://user-images.githubusercontent.com/2425577/145149415-b89f19e3-3813-4460-add9-dac646e909e4.png)

**Comment by individual-it** [comment]
I would suggest to use the `data-test-*` attribute to find the element, but adding an extra assertion to check the real displayed name
@amrita-shrestha could add that to her PR

**Comment by kulmann** [comment]
> this is a good example why relying on the `data-test-*` attributes is dangerous The test attributes have changed in the DOM, but the view for the user not. IMHO we should check the real-values and not rely only on the test attributes in E2E tests
> 
> ![grafik](https://user-images.githubusercontent.com/2425577/145149415-b89f19e3-3813-4460-add9-dac646e909e4.png)

Afaik the `data-test-*` attributes are mostly used to find rows in the file list. I agree that checks for file names after rename should happen with `getText()`, good spot. 👍
