### ISSUE TITLE
uploading a new version of a file creates a second entry with the same name in the list

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#4895]
### Steps to reproduce
1. upload a file
2. upload a file with the same name again
3. select to create a new version

### Expected behaviour
the list should only contain one file

### Actual behaviour
![image](https://user-images.githubusercontent.com/2425577/113085067-e420af00-91fe-11eb-8311-dc99bcaf35ab.png)

**Comment by fschade** [comment]
fixed by https://github.com/owncloud/web/pull/5130
