### ISSUE TITLE
adjust webUI test scenarios with "tries to" in its step

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#4933]
Description: see issue description from here https://github.com/owncloud/web/issues/4680 

After issue https://github.com/owncloud/web/issues/4680, tries to steps with following are refactored:
- [x] tries to move
- [x] tries to copy

TODO:
- [x] tries to rename https://github.com/owncloud/web/pull/5134
- [x] tries to create a public link share https://github.com/owncloud/web/pull/5137
- [x] tries to create files/folder https://github.com/owncloud/web/pull/5157
- [x] tries to login https://github.com/owncloud/web/pull/5162
- [x] tries to navigate private liink https://github.com/owncloud/web/pull/5174

**Comment by SwikritiT** [comment]
I think we still need some adjustments in webUI test scenarios with "tries to" in its step for renaming , so I'm un-checking the box and adding it to TODO 

for eg: 
https://github.com/owncloud/web/blob/4bf7899f57dbf8f10a2c0258e4c6e5bdb2022671/tests/acceptance/features/webUIRenameFiles/renameFiles.feature#L182 
The file should be renamed in this case and we shouldn't use `tries to rename`  we should use `rename` instead. 

Similar case here 
https://github.com/owncloud/web/blob/4bf7899f57dbf8f10a2c0258e4c6e5bdb2022671/tests/acceptance/features/webUIRenameFolders/renameFolders.feature#L113

https://github.com/owncloud/web/blob/4bf7899f57dbf8f10a2c0258e4c6e5bdb2022671/tests/acceptance/features/webUIRenameFolders/renameFolders.feature#L144

**Comment by SwikritiT** [comment]
I couldn't find anything that can be refactored with `tries to` share so I'm removing it from todo

**Comment by SwikritiT** [comment]
@individual-it @phil-davis can you take a look at this issue and make sure if we can close it?
