### ISSUE TITLE
Toggle hidden files

### ISSUE THREAD

**Issue by labkode** [owncloud/web#4943]
## User story
> As a user I want to hide/show hidden files (, dot files) in the UI ala OC10
![Screenshot 2021-04-09 at 13 13 24](https://user-images.githubusercontent.com/5175912/114172003-5eef7580-9935-11eb-9640-cd2c6b60da10.png)

## Acceptance criteria
- have a dropdown above the files list (first scribble from [~tbaader]) with a `Show hidden files` checkbox
- store the information in localStorage, so that it survives a browser session
- same interpretation of "hidden files" as in oc10
- `Show hidden files` applies to files and folders
- unit tests
- default: unchecked (hide hidden files)
- (don't modify the page number, only make sure that you move to the last page, if the page from before doesn't exist anymore after hiding hidden files)

**Comment by labkode** [comment]
cc @elizavetaRa

**Comment by pascalwengerter** [comment]
@labkode @diocas two questions before we can get started working on this
- should this be done on an instance-wide basis (via the `config.json`, perhaps) or configurable per user (which may take longer to implement)?
- who defines what a hidden file is, do you want to provide your own list, should we follow some standard, same approach as OC10 etc?

**Comment by labkode** [comment]
@pascalwengerter user-based. Hidden files are files starting with `.`. This is the OC10 model and is good enough. If more features will need to be added can be added in steps.

**Comment by tbsbdr** [comment]
discussed a good idea by @elizavetaRa showing the switch in direct context the files list - and maybe in the future next to view-options like grid/condensed view. @elizavetaRa could you add a screenshot?

**Comment by kulmann** [comment]
UX-wise I fully agree. Related to https://github.com/owncloud/web/issues/5239
If we want to use the settings service (including the settings UI) from oCIS we need a concept of how changing the filter option in the files app also changes the setting in the settings service. We could start without the settings service, only storing the choice in the local storage of the browser (i.e. not persisted forever, user might be annoyed that this setting is not in sync across devices).

**Comment by kulmann** [comment]
> @kulmann We have some urgency on this. Persistent settings are ofc great, but starting with the browser storage is the quickest way and I would say more than enough for now.

Fine by me 👍 Waiting on a screenshot from the UX discussion.

**Comment by tbsbdr** [comment]
adopting elizas idea to place the switch next to the filelist and make it possible to add more options in the future like "show deleted files" and "show quick access files".

## first screen is, whats planned next for short term:
 the other screens depict possible next levels, taking the sidebar-switch and more options into account:
![image](https://user-images.githubusercontent.com/26610733/122398498-3d84b880-cf7a-11eb-8942-9850b2f30dd2.png)

**Comment by tbsbdr** [comment]
adopting elizas idea to place the switch next to the filelist and make it possible to add more options in the future like "show deleted files" and "show quick access files".

## first screen is, whats planned next for short term:
 the other screens depict possible next levels, taking the sidebar-switch and more options into account:
![image](https://user-images.githubusercontent.com/26610733/122399935-88530000-cf7b-11eb-8d36-05c1be453e7a.png)

![image](https://user-images.githubusercontent.com/26610733/122400000-94d75880-cf7b-11eb-87cf-a0d75217c532.png)

![image](https://user-images.githubusercontent.com/26610733/122400033-9d2f9380-cf7b-11eb-9504-eb12a02d1fc8.png)

![image](https://user-images.githubusercontent.com/26610733/122400057-a587ce80-cf7b-11eb-9d9c-6d32a0476486.png)

**Comment by tbsbdr** [comment]
![image](https://user-images.githubusercontent.com/26610733/122400320-e67fe300-cf7b-11eb-8cb7-3fdcaf13a9c7.png)

**Comment by kulmann** [comment]
(closed accidentally)

**Comment by tbsbdr** [comment]
> (closed accidentally)

you know me...

**Comment by diocas** [comment]
Mockups look really good. Suggestion: I would try to put the right buttons vertically aligned with the left buttons ("+ New") to avoid having even less vertical real-estate.

**Comment by kulmann** [comment]
FYI: I removed the `Early-Adopters:CERN` label because we planned this issue in our new sprint. `Early-Adopters:CERN` tickets live in our fastlane, which makes them unusable in sprints.
