### ISSUE TITLE
Fixed aspect ratio in login/error screen logo doesn't work nicely with theming

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#4947]
### Steps to reproduce
1. Configure a custom file in `theme.json`'s **logo** section, e.g. `"login": "https://home.cern/sites/home.web.cern.ch/files/logo/cern-logo.png"`
2. Go to `https://localhost:9200/#/access-denied`
3. See the screenshot below

![Screenshot_2021-04-09 accessDenied - ownCloud](https://user-images.githubusercontent.com/16822008/114193328-518eb700-9946-11eb-9171-70de9d7f9d60.png)

### Expected behaviour
Logo should be displayed in correct aspect ratio

### Actual behaviour
Logo is shown in the aspect ratio that is hardcoded for an ownCloud logo file

### Remedy
PR in the [design system](https://github.com/owncloud/owncloud-design-system/) opened, bringing this over next week

**Comment by kulmann** [comment]
Fixed with https://github.com/owncloud/owncloud-design-system/pull/1207, already updated in web.
