### ISSUE TITLE
Will oCIS server support sharing to root directory like oC10 in upcoming releases?

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#4955]
With oC10, we can choose between `root directory` and `Shares` folder to decide where accepted shares will go. But with oCIS, accepted shares can be listed only inside `Shares` folder not root.

This topic should be discussed because there are separate sharing acceptance tests for `Root` and `Shares`, and we are running both test suites against oCIS. If oCIS is designed not to support accepting shares to the root directory in any circumstances then it will be a good idea not to run sharing tests specific for root-directory against oCIS server, as they don't test anything but take CI pipeline.

Some SharingToRoot tests Suite running gainst oCIS:
https://drone.owncloud.com/owncloud/web/14529/73/11
https://drone.owncloud.com/owncloud/web/14529/81/1

**Comment by individual-it** [comment]
according to @dragotin the functionality to share to root will not be implemented in OCIS and the tests are already tagged `@notToImplementOnOCIS`
@phil-davis should we just delete these pipelines from ocis drone?

**Comment by phil-davis** [comment]
> should we just delete these pipelines from ocis drone?

yes, that will be safe enough, the scenarios in those suites all involve share-to-root and the naming of the suite indicates that. So I don't think that people will accidentally add other unrelated test scenarios to those suites.

**Comment by saw-jan** [comment]
TO DO:
- [ ] Remove sharingToRoot test suites from oCIS drone
