### ISSUE TITLE
Configurable languages in settings service (ocis)

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#4966]
### Expected behaviour
As an admin, I want to configure which languages are provided inside the frontend and can be used by the users. Therefor, I'd assume I can alter configuration to limit the available languages to a certain set.

### Actual behaviour
Available languages are hardcoded in the `packages/web-runtime/src/index.js` file in web and in https://github.com/owncloud/ocis/blob/fb30483d6fc4a88464929c93b69514482a8c5632/settings/pkg/service/v0/settings.go#L95 for ocis, so the admin has no way of configuring or changing them.

## Acceptance criteria
- new prop in the settings service flagset (ocis) for providing the set of available languages

**Comment by pascalwengerter** [comment]
@micbar @butonic what's the planned usage for `var languageSetting` (see oCIS link above)?

Background: We need a decision on whether the available languages in `web` should be defined in the `web`'s `config.json` or "inherited" from an oCIS config/setting :)

**Comment by kulmann** [comment]
For now we went with just deploying a custom patched and built version of ocis where only the languages exist in the code that we want to deploy. Might not even be a good idea to have knowledge about the languages in an env var.

**Comment by pascalwengerter** [comment]
Becomes obsolete with https://github.com/owncloud/ocis/pull/5463, so closing here. New settings options on the account page will be translated "the usual way" on transifex
