### ISSUE TITLE
Send avatar requests in the background

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#4973]
When the 'Shared with me' or 'Shared with others' tab is opened, web sends requests to the `/remote.php/dav/avatars/$username/128.png` to get the profile pictures for the collaborators. While it definitely improves the UX, it significantly increases the latency.

**Comment by pascalwengerter** [comment]
Great feedback, thanks!

For anyone looking into this:
- we perhaps want to use the native lazy loading functionality provided by [the HTML img tag](https://www.w3schools.com/tags/tag_img.asp)
- we're using the [avatar component](https://owncloud.design/#/oC%20Components/OcAvatar) from the ownCloud design system
- the avatar component is based on https://github.com/eliep/vue-avatar - I've already openend an issue for lazy loading of avatar images, might work on this myself soon

**Comment by ishank011** [comment]
Still happens in foreground. Tested with e229c60e423266cb55da9747851109afbfb4688d

**Comment by micbar** [comment]
@ishank011 did you test with a local build?

https://github.com/owncloud/web/pull/5073 is not yet released. It is part of `v3.2.0-rc2`
