### ISSUE TITLE
Remove `@skip` and `@yetToImplement` tags from tests and use expected-to-fail files

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#4977]
There are some acceptance tests that are tagged  `@skip` or `@yetToImplement`, we need to do the followings:
- Feature implemented
   - remove tags
   - add required step defs.
- Feature not implemented
   - remove tags
   - add tests to expected-failures

**Comment by saw-jan** [comment]
blocked because of https://github.com/owncloud/web/pull/5018

**Comment by fschade** [comment]
@saw-jan any progress on this?

**Comment by saw-jan** [comment]
@fschade there are still some tests tagged with `@skip` I need to look at those and then may be we can close this issue after they have been resolved.
