### ISSUE TITLE
web does not work with older versions of chrome

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#5006]
since c8a64ff8 chrome 74 is not supported anymore, it works fine with chrome 90
ToDo: find out in which version of chrome exactly it started to fail

**Comment by saw-jan** [comment]
From the commit-id https://github.com/owncloud/web/commit/c8a64ff8e27a7f255516e5d0b01aa66519231f3f, `web` is not working for `chrome version` `79` and lower.
But works from `chrome version` `80` and above.

And for selenium docker image, web will work with `selenium/standalone-chrome-debug:3.141.59-zirconium` and above.
But with selenium docker lower than this image version, web won't work (lower versions have chrome `79` and lower)

**Comment by individual-it** [comment]
CC @kulmann does that information help you?

I will close this issue now, please feel free to re-open or create a new one if any follow up is needed

**Comment by kulmann** [comment]
It does, thanks @saw-jan for the info! Chrome version 80 is already more than one year old. That sounds reasonable to me.
