### ISSUE TITLE
Admin settings feature not implemented yet

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5015]
Admin user cannot access admin settings using web ui yet

**Comment by phil-davis** [comment]
@kulmann (or anyone) OCIS has an accounts and a settings UI for doing these things, if an admin wants to use a UI.

The oC10 "traditional" web UI has the user/group management UI and various settings UI pages.

But from the new "web" when used with oC10 backend, these "admin UI" things are not available.

Will these be provided in the new "web" "some day"?
Or do admins of oC10 keep using the "traditional" web UI for this?

The reason I ask, is that if these things will not be implemented in new "web", then we will clean up the test scenarios that describe those "potential features".

**Comment by kulmann** [comment]
It is not planned at the moment that ownCloud Web will have the admin settings from the classic UI. The only thing we support at the moment is that an admin can set up a custom link in the user menu for going directly into the settings page of the classic UI.

**Comment by phil-davis** [comment]
OK - the "pending likely test scenarios" have been removed in PR #5469 

The link to the settings page of the classic UI will be a different test that can be written when the feature is being implemented.
