### ISSUE TITLE
webUIFilesActionMenu/versions.feature:14 behaves differently on CI

### ISSUE THREAD

**Issue by Talank** [owncloud/web#5022]
### Description
Scenario webUIFilesActionMenu/versions.feature:14 behaves differently on CI than locally, which needs to be investigated and removed from the expected failure file.

### Related CI builds
- https://drone.owncloud.com/owncloud/web/15116/13/14

**Comment by dpakach** [comment]
It gives error `Error: HTTP Request Failed: Could not create the file "lorem.txt" for user "user0"., Status: 423 undefined`

This means that the file is locked. I think we had similar issue in other tests as well.

**Comment by saw-jan** [comment]
blocked because of #5018
