### ISSUE TITLE
UI hangs when directory contains a large amount of files

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#5060]
### Steps to reproduce
1. Create many files in local setup (tried with 5000, 8000)
2. Try to list them in the web UI

### Expected behaviour
UI doesn't freeze

### Actual behaviour
 UI freezes or the response comes after a longer time (approx. 2 minutes) and are not clickable

### Server configuration
Newest ocis version

![image](https://user-images.githubusercontent.com/5175912/117401909-b74e6e80-af05-11eb-8af9-8e974f084800.png)

**Comment by ishank011** [comment]
Adding that the issue wasn't visible in the previous web version (2.1.0) used in ocis.

**Comment by kulmann** [comment]
We're planning to introduce [pagination](https://github.com/owncloud/ocis/issues/1178) to solve this

**Comment by micbar** [comment]
> Adding that the issue wasn't visible in the previous web version (2.1.0) used in ocis.

Web 2.1.0 was using virtual scrolling and only kept 10 items in the DOM

In web 3.0 there is no virtual scrolling because it was necessary to remove it.

Web 3.x needs pagination instead of the virtual scrolling.
