### ISSUE TITLE
Occ commands in web tests not working locally

### ISSUE THREAD

**Issue by jasson99** [owncloud/web#5065]
### Steps to reproduce
1. Run web tests having steps to set `shares_folder` to `Shares` locally

### Expected behaviour
The `shares_folder` should be set to `Shares` and hence the tests should execute properly. 

### Actual behaviour
The `shares_folder` is not set to `Shares` and hence the tests fail in the later steps where the share is to be accepted from `Shares` folder. However, the tests do not fail on the step where it is to be set. In fact the response is `System config value share_folder set to string Shares`.

The tests run as expected when the desired value is set manually before the test run.

Note: We need to investigate if the value is not set in the first place or is reverted back due to some other steps.

**Comment by LukasHirt** [comment]
I tried today as well and works perfectly!
