### ISSUE TITLE
Do not block main rendering on preview (thumbnail) requests

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5075]
When listing a directory with N files  there will be N requests send to create a preview.
These requests instead of being sent in the background block the rendering of the UI and the file list.

For example:
When listing a folder with 100 entries, 100 requests to fetch the previews are made. The PROPFIND response takes 300ms and user get a render after 7 seconds because you wait for the preview requests to finish. This is a design flaw. Previews MUST be rendered dynamically and NOT block the UI.

The same happens on the "Shared with me/you" tabs, in this case with the avatars endpoint:
#4973

**Comment by pascalwengerter** [comment]
Updated this to only reflect thumbnail loading since #4973 has successfully been closed

**Comment by labkode** [comment]
Probably related with testing on old version 2.1
