### ISSUE TITLE
Increase density of the UI

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5078]
The current UI shows less items than the OC10 one.
In my Mac: 12 items (OC10) vs 9 (OCIS).
A higher density needs to be configured.

**Comment by pascalwengerter** [comment]
@labkode can you give us an idea of
a) how this should be achieved
b) how the results should look like
from your perspective?

My first naive suggestion would be to tackle it a) by reducing the row height as shown in the screenshot below by b) moving the configuration of the row height from the component to the theming so every `web` theme can define the "denseness" of their UI themselves

@tbsbdr @elizavetaRa perhaps can also can give opinions?

![Screenshot_2021-05-07 Alle Dateien - ownCloud](https://user-images.githubusercontent.com/16822008/117429353-e32a1e00-af1e-11eb-9c98-1550b3038cba.png)

**Comment by tbsbdr** [comment]
suggestion: lets make the corresponding variables themable so you can adjust it to your needs.

**Comment by pascalwengerter** [comment]
Update for the ODS is in progress: https://github.com/owncloud/owncloud-design-system/pull/1291/files

**Comment by pascalwengerter** [comment]
> > Update for the ODS is in progress: [owncloud/owncloud-design-system#1291](https://github.com/owncloud/owncloud-design-system/pull/1291)
> 
> Note on that: web is currently using ODS 6.0.1, while the PR is directed to the ODS master. We must either backport it to 6.0.1 and make a 6.0.2 from it (breaks semver of ODS) or merge the a11y-swarming branch as soon as possible to be on the latest ODS again.

Prepared the 6.0.2 as discussed with Benedikt, let's see if we can include some more minor stuff for CERN there and release it this week?

**Comment by pascalwengerter** [comment]
> Hi, I gave it a try with row height but the folder icon was not resized. I'm not a front-end guru, but as a suggestion I'd say take a look at OC10 UI and see what makes it more dense (row height, top menu, ...)
> 
> @elizavetaRa

@labkode how do you suggest we proceed with this issue/ticket?

A couple of thoughts from my side:
- we're developing the new `web` frontend dedicatedly to *not* look like the OC10 UI, so looking at the old UI for inspiration feels wrong
- while you're looking for a more dense UI at the CERN, there's only a small chance those requirements and the resulting changes will make it upstream into the main repo. This is why we've invested a lot of time and energy into making theming work, and are more than happy to iterate on that if you need more configurability or find spots that don't quite work yet for you
- we're a frontend development and not design team, so please provide us with an idea of what we should implement. The smaller table row height was my first guess at what you're looking for, and it will be released with the web `v3.1.0`/oCIS release in the upcoming days. I'm reluctant to now invest further energy into working on this ticket if it's not clear what you want 
- For us to efficiently and pragmatically being able to deliver on your needs, we need clearer requirements to act upon - as stated above I suspect those change requests to come in form of more theme-ability, and am more than happy to discuss this with you and help make it happen quickly

**Comment by tbsbdr** [comment]
@pascalwengerter @labkode thanks for trying to solve this issue "ad hoc". let @elizavetaRa and me try to find a solution on 20.5.2021 in our meeting.
fyi @pmaier1 @diocas

**Comment by tbsbdr** [comment]
- short term / quickfix: Reduce the row height to the possible minimum of 49px (https://github.com/owncloud/owncloud-design-system/pull/1319)
- longterm: maybe move the sharing indicators out of the 2nd row (below the filename) to a dedicated column. needs scribbles and more concepting in the future. maybe also groundwork for a special condensed view-switch.

**Comment by pascalwengerter** [comment]
@elizavetaRa we've reduced the default table row height in the design system to 49px, however it won't be included in the `v3.2.0` web release but only in the next version. If you want it you can of course easily change it via your `theme.json` :)

**Comment by diocas** [comment]
@pascalwengerter we are using our fork of ODS and web when building our oCIS, so we can deploy everything from the tip of the master branch. But @elizavetaRa told me there were some incompatibilities with the latest ODS. Can I use latest everything or is there some "stable" branch I should use instead?

**Comment by pascalwengerter** [comment]
> @pascalwengerter we are using our fork of ODS and web when building our oCIS, so we can deploy everything from the tip of the master branch. But @elizavetaRa told me there were some incompatibilities with the latest ODS. Can I use latest everything or is there some "stable" branch I should use instead?

Hey, yeah the current release to use with web `master` is [v6.0.3](https://github.com/owncloud/owncloud-design-system/releases/tag/v6.0.3), the current ODS master will get released as v7.0.0 later today and needs some more work until we can merge it into web...

**Comment by diocas** [comment]
Ok, so I'll wait for everything to be fixed to use the latests (with the fix for the density). Can you ping me when this process finishes? thanks

**Comment by pascalwengerter** [comment]
> Ok, so I'll wait for everything to be fixed to use the latests (with the fix for the density). Can you ping me when this process finishes? thanks

The themable row height was part of `v6.0.3` so you should already be able to set the `height-table-row` property via the `theme.json` (we did this release for you at CERN to reduce the wait time after all, cangelog for the release: https://github.com/owncloud/owncloud-design-system/releases/tag/v6.0.3). Theming docs are [here](https://owncloud.dev/clients/web/theming/) if you want to check (and work for web `master`)

**Comment by diocas** [comment]
Ah sorry, didn't realize that! Will try then.

**Comment by pascalwengerter** [comment]
@diocas @labkode @elizavetaRa I would like to close this ticket unless you have any actionable items for us that are open currently?

**Comment by diocas** [comment]
Well, you provided a workaround for now. But ideally we want the ui elements to be resized as well, because right now we do not consider them appropriate for desktop/laptop usage as everything is too large/big.

**Comment by pascalwengerter** [comment]
> Well, you provided a workaround for now. But ideally we want the ui elements to be resized as well, because right now we do not consider them appropriate for desktop/laptop usage as everything is too large/big.

Thanks for the quick reply! Quite a lot of ui elements are resize-able through theming, could you provide us with a list of the ones that aren't themable yet so we can make them customizable on your end, too?

**Comment by pascalwengerter** [comment]
Closed as unresponsive and not actionable, resizing elements via theming is possible and we're implementing the new design over the next weeks
