### ISSUE TITLE
Sharing permission not respected consistently

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5080]
If I click the share icon on a resource I don't have the right to share the following happens:

1) the collaborators panel shows that I don't have permissions to share
<img width="539" alt="Screenshot 2021-05-07 at 07 44 29" src="https://user-images.githubusercontent.com/5175912/117403207-1ad99b80-af08-11eb-93c4-af7f8521a7eb.png">

2) the public link button is still available:
<img width="531" alt="Screenshot 2021-05-07 at 07 44 34" src="https://user-images.githubusercontent.com/5175912/117403237-262cc700-af08-11eb-887c-3c0ee7eea9f4.png">

3) When you click it fails:
<img width="525" alt="Screenshot 2021-05-07 at 07 44 41" src="https://user-images.githubusercontent.com/5175912/117403263-2d53d500-af08-11eb-986f-5b9384fdb30c.png">

The expected behaviour is that the public links should be disabled as well.

**Comment by fschade** [comment]
we merged it into the a11y branch which will go to master soon, i close this for now
