### ISSUE TITLE
Dialog to overwrite files does not work as expected

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5081]
I upload the same file and the dialog appears:
<img width="1081" alt="Screenshot 2021-05-07 at 07 48 03" src="https://user-images.githubusercontent.com/5175912/117403908-43ae6080-af09-11eb-9b27-307de3b36a87.png">

After clicking accept, I see two entries with the SAME name.
<img width="1074" alt="Screenshot 2021-05-07 at 07 49 03" src="https://user-images.githubusercontent.com/5175912/117403912-4741e780-af09-11eb-95cd-3f6ce3b5ab2f.png">

I refresh the page and only one entry is shown. The new file has overwritten the original one.
<img width="1088" alt="Screenshot 2021-05-07 at 07 51 43" src="https://user-images.githubusercontent.com/5175912/117403918-490bab00-af09-11eb-91ad-5a76eedb0532.png">

The expected behaviour is to have another entry with a suffix (file_2) not to overwrite.

**Comment by kulmann** [comment]
Closing as duplicate here, there is this ticket already: https://github.com/owncloud/web/issues/4996
@ishank011 also already added the proper label to the other ticket
