### ISSUE TITLE
The via button sends you to the parent of the share entry

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5082]
The "Via" button send you to the parent of the share entry, however this folder may not be accessible to the user.
The "Via" button should send you the to share entry.

For example:

If I have received a share to folder Two, the user will see the following path:
`/eos/user/d/diogo/One/Two/Three`

If I am in Three and click "Via" button I get redirected to "One" where I should have been redirected to "Two".

**Comment by labkode** [comment]
Still reproducible.

**Comment by kulmann** [comment]
I just re-tested it from the current web master and can confirm the fix with an oc10 and and ocis backend. 🤔 

1: Create a folder `One`
2: Create a subfolder `One/Two`
3: Upload a file `image.jpg` into `One/Two/image.jpg`
4: Share folder `One/Two` with user bob
5: Login as bob and accept the share - for bob it's now `Two` as a root level share
6: Open the right sidebar in `People` accordion item for `Two/image.jpg`
7: Click on `Via Two`
8: Land in `Two`

**Comment by labkode** [comment]
8. You land in "Shares" not in Two.



https://user-images.githubusercontent.com/5175912/119121504-cb2dc080-ba2d-11eb-9b8f-ea494743fa00.mov

**Comment by kulmann** [comment]
@labkode ocis.owncloud.works is not deployed with web master, but only from ocis master (with the most recent web release). I will check internally if we can get an oCIS test system that has web from current master at least nightly.

**Comment by labkode** [comment]
@kulmann is the same behaviour on our deployment which uses latest version from web@master since yesterday.

**Comment by labkode** [comment]
@kulmann is it a config option maybe that we're missing?

**Comment by kulmann** [comment]
Not related to config options. It's actually changed without exception. If you can still see the `scrollTo` in the URL, then it really is not the most recent master.

**Comment by labkode** [comment]
Fixed. Thanks!
