### ISSUE TITLE
When navigating to areas I don't have permissions it says I'm the owner

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5083]
![image](https://user-images.githubusercontent.com/5175912/117404397-2af27a80-af0a-11eb-8f7e-76ef318d9b83.png)

 In this example, the folder is owned by user: gagarcia but I'm shown as the owner.

**Comment by pascalwengerter** [comment]
Should be fixed by #5112

**Comment by pascalwengerter** [comment]
@labkode could you try with the current master and confirm it has been resolved?

**Comment by labkode** [comment]
@pascalwengerter will tested it and let you know

**Comment by labkode** [comment]
@pascalwengerter not fixed. Reproducible from master branch

**Comment by pascalwengerter** [comment]
> @pascalwengerter not fixed. Reproducible from master branch

Thanks for the feedback, could you give me exact steps to reproduce your issue?

**Comment by labkode** [comment]
@pascalwengerter 

https://user-images.githubusercontent.com/5175912/119123865-51e39d00-ba30-11eb-9815-152ed2b0a06e.mov

**Comment by kulmann** [comment]
Clarified in a call that this is not related to sharing, but about actual file ownership. The owner is available in the fileInfo as `{http://owncloud.org/ns}owner-id` and `{http://owncloud.org/ns}owner-display-name`. Needs to be used in `buildResource` in the resources.js helper.

**Comment by fschade** [comment]
@labkode, i was ale to reproduce the issue now with ocis driver. We first need to implement this 

https://github.com/cs3org/reva/blob/e8a00d9b236877bcb9302070a967cc7632e8ca84/internal/http/services/owncloud/ocdav/propfind.go#L586-L586

before we can fix this

**Comment by ishank011** [comment]
@fschade can you share the steps to reproduce? Are you exposing the global namespace as well?

**Comment by fschade** [comment]
@ishank011 to reproduce it i attached a different owner to a folder by doing

```
xattr -w user.ocis.owner.id f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c storage/users/nodes/root/4c510ada-c86b-4815-8820-42cdf82c3d51/foo
```

in this case the ui still shows `einstein` as owner instead of `marie`.

**Comment by pascalwengerter** [comment]
@ishank011 any update on this? :)

**Comment by diocas** [comment]
I guess the "owner" info was dropped from the sidebar, right? (at least I no longer see it)
So I suppose this issue got "resolved"

**Comment by kulmann** [comment]
> I guess the "owner" info was dropped from the sidebar, right? (at least I no longer see it)
> So I suppose this issue got "resolved"

The `owner` info is not in the people / shares panel anymore. Instead there is an `owner` row in the top level `Details` panel of the right sidebar.

**Comment by kulmann** [comment]
> When I look at a folder that belongs to someone else, the owner row doesn't appear. I don't know if this is some other bug, but at least it looks ok for us.

The web ui doesn't look at file owners, only at share owners. That explains why you don't see the owner in such a case.

**Comment by diocas** [comment]
then it's fixed :D
