### ISSUE TITLE
File extensions should behave the same independently of case

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5084]
File extensions appear to be case-sensitive: .PNG and .png files behave differently (the first opens the download dialog, the second the media viewer)

**Comment by kulmann** [comment]
Issue was fixed in https://github.com/owncloud/web/pull/4627/files#diff-4a03aa98718dbdf36de7394680eada567e49e4127471b917bca4a8129fc7bfc1R28 and released in [v3.0.0](https://github.com/owncloud/web/releases/tag/v3.0.0)
