### ISSUE TITLE
Sharing tab is not consistent

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5087]
If I click on the "Add collaborator" I don't see the list of existing people I'm sharing.

<img width="674" alt="Screenshot 2021-05-07 at 08 10 38" src="https://user-images.githubusercontent.com/5175912/117405382-d51ed200-af0b-11eb-9685-0fc65db70770.png">

If I open the share tab by just clicking on the row the list of people is displayed:
<img width="543" alt="Screenshot 2021-05-07 at 08 10 45" src="https://user-images.githubusercontent.com/5175912/117405431-ea93fc00-af0b-11eb-8362-ae021ff61877.png">

I expect that when you click on add a collaborator you still see the people you've shared the file with.

**Comment by kulmann** [comment]
The way the sharing form works as of now would suggest that saving the share would apply the selected role to all pre-existing shares as well. There's a new concept for sharing, which is agreed with you as far as I know. That concept shows a combined view of pre-existing shares and the new ones. Unfortunately the tickets for it are not available here, yet, as concepting is not finished (and happens in another place). As soon as the concept is ready we'll jump into the implementation, as it has very high priority on our roadmap.

**Comment by kulmann** [comment]
@labkode @diocas any comment on this?

**Comment by labkode** [comment]
Hello @kulmann, when will be the new sharing introduced?

**Comment by kulmann** [comment]
@labkode It will most probably **not** be part of the next sprint, but the one after that. If that is the case, it would be released mid of July. That has some uncertainty as of now.

**Comment by pascalwengerter** [comment]
This has been resolved by redesigning the sharing tab for quite a while now already 💪🏽
