### ISSUE TITLE
Theming: Logo sizing options are missing

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#5128]
![er](https://user-images.githubusercontent.com/7430156/118960077-352d6380-b963-11eb-82c9-13cbb6c9b4e3.png)

### Steps to reproduce
1. Embed the logo image in theme.json

### Expected behaviour
Option for different sizes (S, M, L..), also option for max height/width

**Comment by kulmann** [comment]
Created https://github.com/owncloud/owncloud-design-system/pull/1380 which will add theming options for the max-width and max-height of the logo in the sidebar.

@elizavetaRa Could you clarify what the different sizes are needed for? We always have the same size for the left sidebar anyway, so I don't see the need for size options. max-width and max-height should be sufficient.

**Comment by pascalwengerter** [comment]
I'd also strongly vote in favor of handling this via theming (and then one can decide individually if it should be `px`, `rem` or `%`) which keeps it simple yet flexible :)

Needs a theming docs update once the next ODS release gets integrated into web

**Comment by pascalwengerter** [comment]
This has been fixed now that ODS `7.4.0` is merged in the web master. @elizavetaRa you can now use [sizes within theming](https://owncloud.dev/clients/web/theming/#sizes) to set `var(--oc-size-max-height-logo)` and `var(--oc-size-max-width-logo)` according to your needs!
