### ISSUE TITLE
[Tests-Only] Implement owncloud test middleware

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#5132]
### Description
Currently, most of the test-related code here is also moved to https://github.com/owncloud/owncloud-test-middleware. 
We can use the middleware to run tests using the middleware.
But that will increase the complexity of the test runner.

We need to think about how to implement the middleware on our existing test framework.

**Comment by pascalwengerter** [comment]
Closed via #5136 if I'm not mistaken 🥳
