### ISSUE TITLE
let extensions register more flexible file open actions

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#5135]
As an extension developer I want an extension to be able to:
- [X] Register a name per file extension: "open in x", where x is the name, eg: "open in Collabora" and "open in CodiMD" #5805 
- [ ] Register a custom action name: "y in x", where y is the action name, eg: "open in x" or "edit in x" or "view in x" => needs 
- [ ] Register a file action dependent on the permissions on a file, usecase: if I received a share with viewer permissions I see only actions "view in x". Whereas when I received a share with editor permissions I also see the "edit in x" action => needs concepting
- [ ] Load the list of available file extensions from a non static external endpoint (eg. the extensions api) => needs concepting

**Comment by wkloucek** [comment]
@kulmann The answer to all requests is currently not supported I suppose? ;-) Are there already plans to support it?

**Comment by kulmann** [comment]
1) and 2) are easy, we can allow that file handlers define their own name for the action entirely.
For 3) we'd have to extend the first one even more and react differently depending on the permissions on the file. The resource (and with that the permissions) is available anyway, so we just have to come up with a reasonable mapping structure.
4) needs changes in the way we load extensions. As of now only static code is possible in extension loading, but for making your request possible we need access to the store of the runtime. Needs concepting first (we have ideas about this but need to write them down).

**Comment by wkloucek** [comment]
A discussion with CERN today raised the question to not use the file extension but the mimetype from the propfind of a file when looking for the open in app action. This allows oCIS / REVA adminstrators to add custom mimetypes without changing the Web frontend. Should be easily doable, what do you think about this @kulmann?

Example:
mimetype `application/vnd.oasis.opendocument.text` is able to be opened in Collabora and OnlyOffice (Web gets this information from an API endpoint). Then it will get the mimetype for a particular file from the propfind information and can look up, what the user can be offered to open that file with. Currently an Web extension does this by providing the file extensions (eg. `.odt`) that it can open.

CC @labkode @ishank011

**Comment by kulmann** [comment]
Currently we're not using mime types in web, but they are available with the DAV property `{DAV:}getcontenttype`, so at least retrieving it would be easy.

**Comment by labkode** [comment]
cc @elizavetaRa

**Comment by kulmann** [comment]
FTR: we have mime type now on resources: https://github.com/owncloud/web/blob/29341a1c1162e8e1f41fa926b13dde340902df75/packages/web-app-files/src/helpers/resources.js#L37

**Comment by wkloucek** [comment]
can this be closed after https://github.com/owncloud/web/pull/5805 is merged or are there open points?

**Comment by pascalwengerter** [comment]
> can this be closed after #5805 is merged or are there open points?

I've refactored the acceptance criteria in this ticket and so far we've only checked the first box ;) the other ones needs further concepting and backend changes (not sure if oCIS/Reva/... though)

**Comment by wkloucek** [comment]
@kulmann does this ticket still have some right to exist? The last comment was already in 2021...
