### ISSUE TITLE
Trying to create a (public) link share of the `Shares` folder throws an error

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#5152]
### Steps to reproduce
1. Go to all files
2. Open right sidebar for `Shares` folder
3. Try to create a public link for the folder

### Expected behaviour
One perhaps shouldn't even see the buttons to create a public link for one's `Shares` folder

### Actual behaviour
See an error

<img width="904" alt="Screenshot 2021-05-26 at 09 46 51" src="https://user-images.githubusercontent.com/16822008/119631300-a9ef1a80-be07-11eb-834e-8e2552919be3.png">

**Comment by phil-davis** [comment]
Is this with OCIS or oC10 server back-end, or both?

**Comment by pascalwengerter** [comment]
> Is this with OCIS or oC10 server back-end, or both?

Good point, oCIS from current master. We'll have to check this on the frontend independently of the backend though I suppose since you perhaps shouldn't be able to share your `Shares` folder from my understanding ;)

**Comment by phil-davis** [comment]
The `Shares` folder is a system-wide thing. So it is a bit odd for a user to share the whole of it. The receiver would end up with a `Shares/Shares` folder! A product manager should decide what is the requirement, and we can easily first have an API test that checks for the desired behaviour.

**Comment by pascalwengerter** [comment]
> The `Shares` folder is a system-wide thing. So it is a bit odd for a user to share the whole of it. The receiver would end up with a `Shares/Shares` folder! A product manager should decide what is the requirement, and we can easily first have an API test that checks for the desired behaviour.

Agreed that it shouldn't be possible to do it, @tbsbdr could you take a look and add a corresponding story to our backlog?

**Comment by dpakach** [comment]
Also when trying to create a user share, it doesn't shows any error message on ocis.
![Screenshot from 2021-05-27 10-47-08](https://user-images.githubusercontent.com/19869344/119769105-9318f880-bed9-11eb-94da-3459297fcab9.png)

While on oc10 it shows error message
![Screenshot from 2021-05-27 11-10-09](https://user-images.githubusercontent.com/19869344/119770625-27845a80-bedc-11eb-923b-8708dda45b61.png)

**Comment by pascalwengerter** [comment]
Closed via #6593, in oCIS shares are now displayed in a different view and in OC10 the permissions are handled correctly, see screenshot below

<img width="470" alt="Screenshot 2022-05-06 at 17 10 44" src="https://user-images.githubusercontent.com/16822008/167161162-87554d56-8679-4896-8405-42668a6deaa0.png">
