### ISSUE TITLE
[Tests-Only] Combine the pipelines that take less time

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#5158]
Looks like there are make suites that complete fairly quickly, For these suites, we don't need to start seperate pipelines, we can just combine these so we don't take up too many drone agents and reduce the overall load at the CI infrastructure.
since each pipeline needs to set up its own owncloud server, reducing the pipelines will reduce the load at the system.

Here is a list of times taken by different pipelines on a build, we can combine the ones that take around 10 minutes and maybe average out everything to around 15 - 20 minutes, then we can reduce the load without increasing the time it takes for one build to complete

cc @individual-it @phil-davis 
| index | suite | time(minutes) |
| -- | -- | -- |
| 0 | "webUIOCISFiles2-chrome" | 26 |
| 1 | "webUISharingInternalUsers-chrome" | 23 |
| 2 | "iPhone2-chrome" | 22 |
| 3 | "OCISSharingPublicBasic-chrome" | 22 |
| 4 | "webUIRename-chrome" | 21 |
| 5 | "SharingExternal-chrome" | 20 |
| 6 | "webUIOCISBasic-chrome" | 20 |
| 7 | "OCISFavorites-chrome" | 20 |
| 8 | "OCISSharingInternalGroups-chrome" | 20 |
| 9 | "webUIResharing-chrome" | 19 |
| 10 | "SharingPermissionToRoot-chrome" | 19 |
| 11 | "SharingExternalRoot-chrome" | 19 |
| 12 | "XGAPortrait2-chrome" | 19 |
| 13 | "webUIBasic-chrome" | 18 |
| 14 | "webUIFiles2-chrome" | 18 |
| 15 | "SharingFolderAdvPermissionsGrp-chrome" | 18 |
| 16 | "SharingPublicBasic-chrome" | 18 |
| 17 | "iPhone1-chrome" | 18 |
| 18 | "OCISResharing2-chrome" | 18 |
| 19 | "IntegrationApp2-chrome" | 18 |
| 20 | "OCISSharingInternalUsers1-chrome" | 17 |
| 21 | "ResharingToRoot-chrome" | 16 |
| 22 | "XGAPortrait1-chrome" | 16 |
| 23 | "IntegrationApp1-chrome" | 16 |
| 24 | "webUISharingBasic-chrome" | 15 |
| 25 | "webUIFiles1-chrome" | 15 |
| 26 | "SharingAutocompletion-chrome" | 15 |
| 27 | "SharingFolderAdvancedPermissionMU-chrome" | 15 |
| 28 | "SharingInternalGroups-chrome" | 15 |
| 29 | "SharingInternalGroupsRoot-chrome" | 15 |
| 30 | "webUISharingInternalUsersRoot1-chrome" | 15 |
| 31 | "SharingPermissionsUsers-chrome" | 15 |
| 32 | "webUIOCISRename-chrome" | 15 |
| 33 | "OCISSharingInternalUsers2-chrome" | 15 |
| 34 | "OCISSharingInternalUsersExpire-chrome" | 15 |
| 35 | "OCISSharingPermissionsUsers-chrome" | 15 |
| 36 | "OCISSharingFolderAdvPermissionsGrp-chrome" | 15 |
| 37 | "webUISharingInternalUsersRoot2-chrome" | 14 |
| 38 | "OCISSharingFolderPermissionsGroups-chrome" | 14 |
| 39 | "OCISResharing1-chrome" | 14 |
| 40 | "OCISSharingPublicDifferentRoles-chrome" | 14 |
| 41 | "SharingInternalUsersExpire-chrome" | 13 |
| 42 | "SharingInternalUsersExpireToRoot-chrome" | 13 |
| 43 | "SharingPublicDifferentRoles-chrome" | 13 |
| 44 | "TrashbinRestore-chrome" | 13 |
| 45 | "webUIOCISFiles1-chrome" | 13 |
| 46 | "OCISSharingPublicManagement-chrome" | 13 |
| 47 | "webUICreate-chrome" | 12 |
| 48 | "Move-chrome" | 12 |
| 49 | "SharingFolderPermissionsGroups-chrome" | 12 |
| 50 | "SharingPublicManagement-chrome" | 12 |
| 51 | "Upload-chrome" | 12 |
| 52 | "XGAPortrait1-Notifications-chrome" | 12 |
| 53 | "iPhone1-Notifications-chrome" | 12 |
| 54 | "webUIOCISRestrictSharing-chrome" | 12 |
| 55 | "Favorites-chrome" | 11 |
| 56 | "SharingFilePermissionMultipleUsers-chrome" | 11 |
| 57 | "SharingFolderPermissionMultipleUsers-chrome" | 11 |
| 58 | "webUIOCISSharingNotifications-chrome" | 11 |
| 59 | "webUIOCISFiles3-chrome" | 11 |
| 60 | "OCISSharingFilePermissionsGroups-chrome" | 11 |
| 61 | "OCISSharingFilePermissionMultipleUsers-chrome" | 11 |
| 62 | "OCISSharingFolderPermissionMultipleUsers-chrome" | 11 |
| 63 | "webUIDelete-chrome" | 10 |
| 64 | "MarkdownEditor-chrome" | 10 |
| 65 | "RestrictSharing-chrome" | 10 |
| 66 | "SharingFilePermissionsGroups-chrome" | 10 |
| 67 | "SharingInternalUsersRootSharingIndicator-chrome" | 10 |
| 68 | "webUISharingNotifications-chrome" | 10 |
| 69 | "webUIOCISCreate-chrome" | 10 |
| 70 | "webUIOCISDelete-chrome" | 10 |
| 71 | "OCISTrashbinDelete-chrome" | 10 |
| 72 | "oc10-integration-notifications-chrome" | 10 |
| 73 | "SharingInternalGroupsEdgeCases-chrome" | 9 |
| 74 | "SharingInternalGroupsSharingIndicator-chrome" | 9 |
| 75 | "SharingInternalGroupsRootSharingIndicator-chrome" | 9 |
| 76 | "SharingInternalUsersBlacklisted-chrome" | 9 |
| 77 | "SharingInternalUsersSharingIndicator-chrome" | 9 |
| 78 | "SharingInternalUsersRootBlacklisted-chrome" | 9 |
| 79 | "SharingPublicExpire-chrome" | 9 |
| 80 | "webUIOCISSharingBasic-chrome" | 9 |
| 81 | "OCISSharingPublicExpire-chrome" | 9 |
| 82 | "OCISTrashbinRestore-chrome" | 9 |
| 83 | "OCISUpload-chrome" | 9 |
| 84 | "OCISSharingFolderAdvancedPermissionMU-chrome" | 9 |
| 85 | "SharingInternalGroupsRootEdgeCases-chrome" | 8 |
| 86 | "OCISMarkdownEditor-chrome" | 8 |
| 87 | "OCISSharingAutocompletion-chrome" | 8 |
| 88 | "OCISMove-chrome" | 8 |
| 89 | "TrashbinDelete-chrome" | 7 |
| 90 | "TrashbinFilesFolders-chrome" | 7 |
| 91 | "webUINotificationBasic-chrome" | 7 |
| 92 | "OCISTrashbinFilesFolders-chrome" | 7 |
| 93 | "OCISJourney-chrome" | 3 |
| 94 | "unit-tests" | 2 |
| 95 | "check-starlark" | 2 |
| 96 | "lint-test" | 1 |
| 97 | "website" | 1 |
| 98 | "changelog" | 0 |
| 99 | "cache-ocis" | 0 |

**Comment by phil-davis** [comment]
I added this to QA Test Automation Backlog. But it is probably easy to do, so put it in the current QA Test Automation project if there are resources to do it.
