### ISSUE TITLE
oc10: Activities download count on public shares broken?

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/web#5207]
### Steps to reproduce
1. Create a public shared folder
2. Download from the share
3. Take a look at the activities of the share

### Expected behaviour
The downloads are tracked.
### Actual behaviour
It appears that without the web app the downloads are tracked.  However this is not the case with web installed.

### Server configuration
**Operating system**:
Docker
**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
10.7.0.4
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Comment by kulmann** [comment]
Next steps (to whoever is working on this in the fastlane):
Try to reproduce if this is a web issue at all. Try the steps from above with web oc10 app installed and enabled + without web oc10 app installed. Check if this behaviour is reproducible at all and if it only surfaces if the web oc10 app is active. If unrelated to web, this issue needs to be moved to the core repo.

**Comment by kulmann** [comment]
The classic UI uses a different download URL than we're using in the new web UI.
- classic: https://github.com/owncloud/core/blob/9b8a804d4aee0bd14fbc8db00a9bf431d4572bee/apps/files_sharing/lib/Controllers/ShareController.php#L384
- new: https://github.com/owncloud/core/blob/817f54f53d64249166feaa0eb9231c50ca1ed7e0/apps/dav/lib/Files/PublicFiles/PublicFilesPlugin.php#L151-L199

**Comment by JanAckermann** [comment]
Closing as OC10 Support has been discontinued with version 7.1.0
