### ISSUE TITLE
When a user shares folder to a group, the sharer is shown as group in group member's sharing-sidebar

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5216]
### Steps to reproduce
1. Create user `Alice` and `Brian`
2. Create group `Group101` and add user `Brian` to this group
3. Login as `Alice`, create a folder `SHAREME` and share it with group `Group101`
(the collaborator list seems fine)
4. Login as `Brian`, open sharing-sidebar (user `Alice` is displayed as group)

Alice's view (Sharer):
![gs01](https://user-images.githubusercontent.com/52366632/121297416-ff501f00-c911-11eb-94e9-5b23aff33725.png)

Brian's view (Group member aka Sharee):
![gs02](https://user-images.githubusercontent.com/52366632/121297423-02e3a600-c912-11eb-9a00-176e06838c2e.png)

### Expected behaviour
The sharer should be displayed as user (showing as group is confusing)

### Actual behaviour
The sharer is shown as a group

### Server configuration
**Operating system**: `Ubuntu 20.04`
**Web server:** `Apache`
**Database:** `MySQL`
**PHP version:** `7.4`
**ownCloud version:** `10.8.0 prealpha (git)`

**Comment by kulmann** [comment]
Shown information will change in https://github.com/owncloud/web/pull/6039 - but we should at least double check if the `Details` panel in the right sidebar shows the correct owner information in the described scenario.
