### ISSUE TITLE
increase unit test coverage

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#5217]
This is an epic and needs to be divided into smaller parts.
Currently only very limited areas are covered by unit test for now this areas should be prioritised to be covered:

- vue components
   - events (fired mostly by `@click`, `@input`, `$emit`): check if desired action happens, check for issues when invalid input is given
   - properties: check if desired action happens when certain properties are set or unset
   - configuration: check if setting specific configurations lead to the desired outcomes
   - displayed Vue elements: check if elements are displayed & have the correct content (mostly triggered by events, properties, configurations)
- helpers: check the logic of the functions with simple unit tests, they should not have anything to do with Vue

For now **don't** test:
- functions in the store (they should be moved out from there in the future)
- functions that use HTTP requests (they will be moved to the SDK)

Other jobs:
- [x] collect coverage data in web repo and send to sonarcloud (https://github.com/owncloud/web/pull/5223)
- [x] collect coverage data in owncloud-design-system repo and send to sonarcloud (https://github.com/owncloud/owncloud-design-system/issues/1365)
- [x] adjust CI scripts so that acceptance tests are not run when only unit tests are changed (https://github.com/owncloud/web/issues/5231)

**Comment by pascalwengerter** [comment]
Closed as tracked in #5234, #5236, #5237, thanks for the great work so far!
