### ISSUE TITLE
Public link quick action opens a copy dialog

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#5221]
### Steps to reproduce
1. Click on public link quick action in files list

### Expected behaviour
A public link is created and copied

![Screenshot 2021-06-09 at 14 50 49](https://user-images.githubusercontent.com/25989331/121357952-844b3080-c932-11eb-9e3f-55b48d225131.png)

### Actual behaviour
A copy to clipboard dialogue is opened.

### Server configuration
**ownCloud version:** 10.7

### Client configuration
**Browser:** Chrome 91

**Operating system:** MacOS

**Comment by pascalwengerter** [comment]
`master` or `a11y-swarming` branch? Just tried to reproduce on the latter, got different behaviour

**Comment by LukasHirt** [comment]
> master or a11y-swarming branch?

Master

**Comment by kulmann** [comment]
Can't reproduce on master 🤷 maybe you have a local link of ODS and some issue because of that?

**Comment by pascalwengerter** [comment]
Can't reproduce either, what was your setup like (accessing through Selenium/VNC viewer), which part(s) of backend/frontend was/were dockerized? :)

**Comment by LukasHirt** [comment]
Cannot reproduce it anymore as well...

> maybe you have a local link of ODS and some issue because of that?

Might have been :shrug:
