### ISSUE TITLE
Run only unit tests when only unit tests are changed

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#5231]
TODO:
- [ ] adjust CI scripts so that acceptance tests are not run when only unit tests are changed

workaround used:
- [x] do not run acceptance tests if PR title contains `unit-tests-only` https://github.com/owncloud/web/pull/5255

**Comment by phil-davis** [comment]
And if we manage to do this, then we can apply similar logic to CI of other repos. And try to do "run only the changed acceptance test suites when only some feature files are changed"
