### ISSUE TITLE
list of components for unit testing

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#5234]
#### AppBar

- [x] AppBar.vue #5603

##### AppBar/SelectedResources
- [x] SizeInfo.vue #5522
- [x] BatchActions.vue #5282, #5519

##### AppBar/Upload
- [x] FileDrop.vue #5552
- [x] FileUpload.vue #5258
- [x] FolderUpload.vue #5559

#### FilesList
- [x] ListInfo.vue #5495
- [x] ListLoader.vue (test may not be required: has no logic)
- [x] NoContentMessage.vue #5517
- [x] NotFoundMessage.vue #5521
- [x] Pagination #5524 
- [x] QuickActions.vue #5526

#### Search
- [x] List.vue #5693
- [x] Preview.vue #5694

#### SideBar

- [ ] Sidebar.vue #5580
- [ ] FileInfo.vue #5580

##### SideBar/Actions
- [x] FileActions.vue #5557

##### SideBar/Links
- [x] PrivateLinkItem.vue #5638 
- [x] FileLinks.vue #5638
- [x] CopyToClipboardButton #5638

###### SideBar/Links/PublicLinks
- [x] LinkActions.vue #5577
- [x] LinkEdit.vue #5609 
- [x] LinkInfo.vue #5495 
- [x] ListItem.vue #5629

##### SideBar/Shared
- [ ] RoleItem.vue #5580

##### SideBar/Shares
- [ ] FileShares.vue https://github.com/owncloud/web/pull/5699

###### SideBar/Shares/Collaborators
- [x] AdditionalPermissions.vue #5646
- [x] AutocompleteItem.vue #5250
- [ ] CollaboratorsEditOptions.vue #5662
- [ ] ShowCollaborator.vue  #5267  #5295 #5308  WIP @individual-it 
- [ ] EditCollaborator.vue #5662
- [ ] NewCollaborator.vue https://github.com/owncloud/web/pull/5696

##### SideBar/Versions
- [x] FileVersions.vue #5649

#### Upload
- [x] DetailsWidget.vue #5674
- [x] ProgressBar.vue #5682

### packages/web-runtime/src/components/:
- [x] ApplicationsMenu.vue #5717
- [x] Avatar.vue #5718
- [x] FeedbackLink.vue
- [x] MessageBar.vue #5719
- [x] Notifications.vue #5218
- [x] OcAppContent.vue #5721
- [x] SidebarQuota.vue #5229
- [x] SkipTo.vue #5720
- [x] TopBar.vue
- [x] UserMenu.vue #5206

### packages/web-app-markdown-editor/src/
- ~~MarkdownEditorAppBar.vue~~ comment from @kulmann please don't test the markdown editor. limit tests to `web-runtime` and `web-app-files` for now.

## Motivation
- https://github.com/owncloud/web/issues/5217

**Comment by kulmann** [comment]
Components in `web-app-files` have been renamed and restructured recently in this PR https://github.com/owncloud/web/pull/5347 - please adjust the checklist in the issue description accordingly. Sorry for the inconveniences...

**Comment by pascalwengerter** [comment]
> Components in `web-app-files` have been renamed and restructured recently in this PR #5347 - please adjust the checklist in the issue description accordingly. Sorry for the inconveniences...

Went ahead and did this since I'm the culprint behind the restructuring 😈

**Comment by pascalwengerter** [comment]
Closing this one as we're taking care of the (new) sidebar component unit tests in #6076. Thanks a lot to @individual-it & team!

**Comment by pascalwengerter** [comment]
@swoichha can be considered done 😉
