### ISSUE TITLE
Move transifex resources from `ownCloud Web` to `ownCloud`

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#5238]
Our transifex resources currently live in the `ownCloud Web` project. Should be moved back to the original `ownCloud` project, since it doesn't make sense that we maintain two.

**Comment by pascalwengerter** [comment]
@kulmann added to fastlane as a quick-win ;)

**Comment by kulmann** [comment]
It's not that `quick` because transifex doesn't have resource transfer built in. We need to export from the `ownCloud Web` project and the re-import into the `ownCloud` project. But yes, fastlane seems to be appropriate. ;-)

**Comment by kulmann** [comment]
Won't happen anymore. All web related resources are in the `ownCloud Web` transifex project now (partially because of move to mono repo) and translation activity is increasing. Will keep it like that.
