### ISSUE TITLE
More space between icons in People view

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#5240]
As a user, I need a little more space between the icons. Sometimes I click next to it.

![image](https://user-images.githubusercontent.com/33026403/112190745-9526b880-8c05-11eb-955b-8602317c0004.png)

**Comment by ChrisEdS** [comment]
It depends on how many icons are in that view in the end. I'd vote for `oc-m-s` if it stays like this. 
Also the click/hover behaviour is nice then. 

If it is imaginable to have 5 icons in a row later, then `oc-m-xs` might be the better option.

**Comment by pascalwengerter** [comment]
I guess this occurance of the icons will stay with two icons for a while. I'd vote for the `oc-m-xs` myself in any case to not create to much space between the icons

Adding @tbsbdr into the mix for a final decision on that issue plus to give him feedback for the re-structuring of the sidebar!

**Comment by kulmann** [comment]
We'll implement a new sharing widget in the right side bar within the next two sprints. So it will change soon anyway. 😅 but still, a bit more margin is a quick win. I like the smaller of the two proposals more.

**Comment by tbsbdr** [comment]
i would opt for `oc-m-xs` - the second one - as well. thanks for the proposals!
