### ISSUE TITLE
[QA] File names with whitespace are downlaoded as application/octet-stream

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#5245]
tested with
* ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

+New -> new drawio file.  -> the default name is "New file.drawio"

Click the file name. select drawio. Drawio opens (if the browser allows "popups"). Draw something, save, exit. :heart:

Click the file name. select download. A save dialog opens
tested with
 
![image](https://user-images.githubusercontent.com/1108546/92533752-62057480-f233-11ea-891c-ab5d33f7384a.png)

The saved name is only "New". The part after the whitespace (including the suffix) is missing.

Expected behaviour: the entire filename including whitspace and with suffix is passed to the save dialog.

Workaround: rename the file to "New_file.draqio"
Now it can be downloaded as type "drawio File"
![image](https://user-images.githubusercontent.com/1108546/92533889-bb6da380-f233-11ea-8bc4-e6ef73ebc7d6.png)

**Comment by kulmann** [comment]
Not reproducible
