### ISSUE TITLE
Report tests that passes on retry

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#5257]
## Description
Acceptance tests are retried 1 time if it fails for the first time. If a test passes on a retry, the CI will go green silently. If not examined properly, these passes ( with a retry ) will go unnoticed.
We should be able to report (to `GitHub` or `rocket chat `🤔 ) if tests pass on a retry so that they can be investigated at the same time when they arise, but not when they explode.

## Motivation
- catching/reporting flaky tests

**Comment by dpakach** [comment]
The tests that pass on retry are now reported in github PR
eg. https://github.com/owncloud/web/pull/5287#issuecomment-866722585

**Comment by phil-davis** [comment]
Example: https://github.com/owncloud/web/pull/5359#issuecomment-867295422
