### ISSUE TITLE
Reduce buildpipeline complexity and duration

### ISSUE THREAD

**Issue by fschade** [owncloud/web#5259]
Web currently uses rollup for its builds, the configuration started to get huge and complex.
It's hard to understand and adopt as a extension developer.

Beside the complexity it also needs up to 7 seconds to rebuild after a code change (MacBook Air M1).

[RFC](https://github.com/owncloud/web/discussions/5260)

**Comment by dschmidt** [comment]
Fixed in https://github.com/owncloud/web/pull/7952
