### ISSUE TITLE
Share status displayed wrongly after accepting/declining

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#5263]
### Steps to reproduce
1. Click "Accept", "Decline" in "Shared with me"

### Expected behaviour
The status changes immediately corresponding to the button action

### Actual behaviour
The status changes to "Pending" with no buttons shown. After reloading the page status is shown correctly.
![Files shared with me - ownCloud](https://user-images.githubusercontent.com/7430156/122014612-9cea9900-cdbf-11eb-9d07-fd0ba92a1cba.gif)

### Server configuration
OCIS version: 1.7.0
Web version: https://github.com/owncloud/web/commit/1c02a21774a4e7b1e1c0b7fc6092b643f36a9c5c (latest master)

**Comment by kulmann** [comment]
I just re-tested with your provided server configuration and can't confirm. Not likely to be a caching issue, because there is no caching of the server application. Closing here. Please re-open and provide more details if this is still failing for you.
