### ISSUE TITLE
Incorrect MIME type for vue.js

### ISSUE THREAD

**Issue by m0nhawk** [owncloud/web#5272]
## Describe the bug

`vue.js` is not loading due to wrong MIME type.

## Additional context

<img width="1440" alt="Screen Shot 2021-02-26 at 11 46 27 PM" src="https://user-images.githubusercontent.com/8220926/109376909-3764b200-788d-11eb-8a58-0f58a0fda9cd.png">

**Comment by fschade** [comment]
@m0nhawk can you provide the information requested above?

**Comment by m0nhawk** [comment]
I completely forgot about this issue, sorry.

It stopped happening around version 1.2-1.4 (I'm not exactly sure, I missed updating to few versions).

And since then it was not happening, and this issue can be closed.
