### ISSUE TITLE
Media files with .jpeg, .gif, .ogg, .webm formats cannot be viewed in preview

### ISSUE THREAD

**Issue by jasson99** [owncloud/web#5273]
## Describe the bug

Media files with extensions such as .jpeg, .gif  cannot be viewed, only the ones with .jpg and .png can be viewed.

## Steps to reproduce

1. upload an image file, say `screenshot.jpeg` to https://localhost:9200/
2. The thumbnail for `screenshot.jpeg` is not visible
![Screenshot from 2021-01-26 15-06-03](https://user-images.githubusercontent.com/40829116/105825818-1d168a80-5fe8-11eb-91b1-074233c331df.png)
3. Click on `screenshot.jpeg`
4. The image is not visible, and a red-exclamation sign is present.
![Screenshot from 2021-01-26 15-07-35](https://user-images.githubusercontent.com/40829116/105825978-53eca080-5fe8-11eb-86cd-ffe24bb7e60d.png)

5. Rename `screenshot.jpeg` to `screenshot.png` or `screenshot.jpg`
6. The thumbnail is visible (try reloading)

![Screenshot from 2021-01-26 15-09-20](https://user-images.githubusercontent.com/40829116/105827862-9911d200-5fea-11eb-90fe-8cdd6893880d.png)

7. Click on the renamed file `screenshot.jpg`
8. The image is visible
![Screenshot from 2021-01-26 15-25-01](https://user-images.githubusercontent.com/40829116/105827969-b6df3700-5fea-11eb-8812-21801fe29dda.png)

## Expected behavior
The thumbnail and image should be visible for all media formats including `.jpeg`

## Actual behavior
Thumbnail and image are not visible in the case of `.jpeg` files

**Comment by pascalwengerter** [comment]
Look at #4667 for more information

**Comment by kulmann** [comment]
Not reproducible anymore (for the image types). The preview app still doesn't support `webm` files, but that is because there is no reliable native browser playback support, so that's "unsupported by product decision" as of now. Might be added later as a feature.
