### ISSUE TITLE
[QA] Media player is not used for mp3 files

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#5275]
Deployed ocis master 2020-12-15 13:00h via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/
 
* login as einstein
* upload a copy of https://www.einstein-website.de/z_biography/einstein1930.mp3 as einstein.mp3
* click the file name. Download is offered. BAD
* rename the file einstein.mp3 to einstein.ogg
* click the file name. The Media Player plays the file. Okayish

Expected behaviour: As it is technically able to play mp3, that mime type should also be registered with the media player.

**Comment by pascalwengerter** [comment]
Has been resolved via #6514 thanks to @kulmann 🎶
