### ISSUE TITLE
use the same linting and prettier config like in ODS

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#5286]
should we have the same configuration here as in ODS?
I noticed it because we are using single quotes here and double quotes in ODS

@kulmann @LukasHirt @pascalwengerter

**Comment by LukasHirt** [comment]
It's actually the other way round https://github.com/owncloud/owncloud-design-system/issues/717

We wanted to create a repository with one config which will be then only pulled as a npm package into all projects where needed

**Comment by individual-it** [comment]
closing in favour of #717

**Comment by pascalwengerter** [comment]
You perhaps meant https://github.com/owncloud/owncloud-design-system/issues/717 but let's keep it open since it applies to both repos

**Comment by dschmidt** [comment]
We imported the ODS in https://github.com/owncloud/web/pull/7940.

Naturally it shares the same config now.
