### ISSUE TITLE
collaborator role icon does not change directly after changing the role

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#5296]
### Steps to reproduce
1. add a collaborator
2. change it's role
3. examine the icon

### Expected behaviour
icon should have changed

### Actual behaviour
the icon of the original role is shown, it only changes after reloading that part of the sidebar

https://user-images.githubusercontent.com/2425577/122513342-053cb300-d02a-11eb-8009-e6b1a34a2084.mp4

**Comment by pascalwengerter** [comment]
Duplicate but newer than #3138, so closing the old issue to give this more visibility

**Comment by kulmann** [comment]
@individual-it could you re-test and close if fixed? we merged and released https://github.com/owncloud/owncloud-design-system/pull/1407 today, sounds like it was the issue here as well.

**Comment by kulmann** [comment]
Re-tested myself and can confirm the fix. Closing here. Please re-open if needed.
