### ISSUE TITLE
no resharing popup displayed if a share is only reshared once

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#5299]
### Steps to reproduce
1. as `admin` share to `user1`
2. as `user1` share to `user2`
3. as `admin` click the `shared by user1` button in the people list

### Expected behaviour
a box should be displayed with the information

### Actual behaviour
a slightly visible empty box is displayed
it works fine if the share is reshared again from `user2` to `user3`

https://user-images.githubusercontent.com/2425577/122516599-ad547b00-d02e-11eb-982a-c9fa833910f7.mp4

I'm currently writing unit tests for that ares, lets see if I can catch the bug there

**Comment by individual-it** [comment]
in FF it only shows the content of the box for one reshare
![image](https://user-images.githubusercontent.com/2425577/122517060-4aafaf00-d02f-11eb-9f99-f3b354d01f03.png)

but

![image](https://user-images.githubusercontent.com/2425577/122517093-54d1ad80-d02f-11eb-8fad-7de8a5e23606.png)

**Comment by pascalwengerter** [comment]
Hint: Perhaps the `<oc-drop>` in web/packages/web-app-files/src/components/Collaborators/Collaborator.vue was forgotten when we switched to tippy whilst doing all the a11y changes (and were mostly checking with oCIS backends which don't support reshares)

**Comment by individual-it** [comment]
I cannot see any differences in the DOM, I think the problem is that the dropdown is opening down and then its hidden

**Comment by paulcod3** [comment]
OC10 issue, since oCIS doesn't allow resharing yet.
