### ISSUE TITLE
Saving public share is not possible

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5321]
### Steps to reproduce
As user `admin`:
1. create a folder `folder123` and upload a file
2. create public share of a folder `folder123`

As user `Brian`
1. access the public link shared by user `admin`
2. try to save the public share to own owncloud account.

### Expected behaviour
Able to save public share to own account like in oC10: with `Add to` button
![coresaveshare](https://user-images.githubusercontent.com/52366632/122739919-307e0700-d2a3-11eb-8a53-0a8321b891ad.png)

### Actual behaviour
Cannot save the public share 
in Web:
![websaveshare](https://user-images.githubusercontent.com/52366632/122739938-3673e800-d2a3-11eb-9e48-aff2cb566eef.png)

### Server configuration
**Operating system**: `Ubuntu20.04`
**Web server:** `Apache`
**Database:** `MySQL`
**PHP version:** `7.4`
**ownCloud version:** `10.8.0 prealpha (git)`

**Comment by pascalwengerter** [comment]
@saw-jan could you please use the provided issue-template and write the `actual` and `expected` behaviour so it's clear what we're looking at here? If you want to download the file with the new frontend, you need to click on the file row and then the right sidebar will open which contains a "Download" button

**Comment by saw-jan** [comment]
Yeah, I am sorry about that.
I have edited the issue description
