### ISSUE TITLE
Wait for unit & integration tests to succeed before running all acceptance tests

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#5322]
### Steps to reproduce
1. Check CI runs
2. See that unit & acceptance tests run in parallel with a lot of acceptance test pipelines

### Expected behaviour
Acceptance tests should only run after unit & integration tests have succeeded

### Actual behaviour
Unit & integration tests run in parallel with acceptance tests. Unit & integration tests are supposed to fail (or pass) early and should prevent the (costly) acceptance tests from even starting

**Comment by pascalwengerter** [comment]
@phil-davis @individual-it could we prioritze this for the upcoming days?

**Comment by phil-davis** [comment]
Yes, that should be an easy job.

Note: example https://drone.owncloud.com/owncloud/web/16615/5/1
unit and integration tests take 5 or 6 minutes. So waiting for them to finish before starting acceptance tests will increase the elapsed time of a successful CI  run by 5 or 6 minutes. We need to all understand that there is this trade-off between running various pipelines sequentially or in parallel.

**Comment by pascalwengerter** [comment]
> Yes, that should be an easy job.
> 
> Note: example https://drone.owncloud.com/owncloud/web/16615/5/1
> unit and integration tests take 5 or 6 minutes. So waiting for them to finish before starting acceptance tests will increase the elapsed time of a successful CI run by 5 or 6 minutes. We need to all understand that there is this trade-off between running various pipelines sequentially or in parallel.

No free lunch, huh? 😉 maybe we can work on the unit test speed from the dev team side and/or parallelize them a bit to cut the unit & integration test step completion time by 50-66%? In terms of server load and wasted resources I still think the tradeoff is fine in any case

**Comment by individual-it** [comment]
What about the fail early strategy? All tests start together, if unit tests fail all other pipelines get cancelled

**Comment by individual-it** [comment]
Running the unit tests in parallel will not help because most time is consumed in the setup phase and for sonarcloud

**Comment by pascalwengerter** [comment]
> What about the fail early strategy? All tests start together, if unit tests fail all other pipelines get cancelled

While I'm a huge fan of the fail early strategy, I find it absurd to kick off ~60 pipelines and create a huge workload on the server without having tested if the basics (= unit tests) are right

> Running the unit tests in parallel will not help because most time is consumed in the setup phase and for sonarcloud

Good insight, thanks

**Comment by dpakach** [comment]
fixed by https://github.com/owncloud/web/pull/5366
