### ISSUE TITLE
Correctly prefix CI acceptance tests pipelines with `OC10-` and `oCIS-`

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#5323]
### Steps to reproduce
1. Check `web` CI runs on Drone
2. Check acceptance pipeline names
3. Have no clue which pipeline uses which backend (OC10 vs oCIS). Currently, everything that doesn't carry `ocis` in its name is run with OC10, but that's implicit and hard to understand for newcomers/outsiders

### Expected behaviour
It should be obvious which (failing) pipeline is running which backend, so I'd like to have them prefixed as shown in the PR title

### Actual behaviour
Especially for an outside contributor, it is totally unclear which pipeline runs with which backend (plus the naming is inconsistent for the ones that carry a hint):

![Screenshot 2021-06-21 at 11-39-03 Build #16632 1 1 - owncloud web - Drone CI](https://user-images.githubusercontent.com/16822008/122749637-79bf5e00-d285-11eb-8dcd-7ea29d1bcfcd.png)

**Comment by phil-davis** [comment]
Should be fixed by #5328
