### ISSUE TITLE
Endless loading when opening a file in section "Shared with me" or "Shared with other"

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#5324]
### Steps to reproduce
1. user 1 share file with type "jpeg" to user 2 
2. user 2 accepted file and 
3. user try to open file in section "shared with me"

### Expected behaviour
File can be opened in Mediaviewer. 

### Actual behaviour
endless loading. "Cannot read property 'substr' of undefined".  

### Client configuration
**Browser: Chrome v. 91.0.4472.106 **

**Operating system: Macos Big Sure v.11.2.3**

### Server configuration
ocis v1.7.0 reachable at https://localhost:9200
```
### Browser log
TypeError: Cannot read property 'substr' of undefined
    at s.thumbUrl (web-app-media-viewer-31ff9edb.js:1)
    at Xf.get (vendor-ec2977a5.js:28)
    at Xf.evaluate (vendor-ec2977a5.js:28)
    at s.thumbUrl (vendor-ec2977a5.js:28)
    at s.loadMedium (web-app-media-viewer-31ff9edb.js:1)
    at s.activeIndex (web-app-media-viewer-31ff9edb.js:1)
    at Xf.run (vendor-ec2977a5.js:28)
    at Gf (vendor-ec2977a5.js:28)
    at Array.<anonymous> (vendor-ec2977a5.js:28)
    at Cd (vendor-ec2977a5.js:28)
```
<img width="1425" alt=" 1" src="https://user-images.githubusercontent.com/84779829/122752354-24894980-d291-11eb-9d46-05b1e8e237a4.png">
<!--

**Comment by kulmann** [comment]
@ScharfViktor could you add the server (oCIS or ownCloud 10? which version?) and the used web version if run standalone?

From your screenshot I can already guess that it's an oCIS, probably with the embedded version of web. But please write it down here in the ticket, just to be sure. :-)

**Comment by wkloucek** [comment]
@kulmann I reproduced this with oCIS 1.9.0-RC1 / Web 3.4.1

https://user-images.githubusercontent.com/34452982/125445424-f26e64ae-b32c-4785-8b20-8471eebb9b6a.mp4

**Comment by pascalwengerter** [comment]
Fails initially on https://ocis.ocis-web.latest.owncloud.works with `this.activeMediaFile.etag is undefined` but mediaViewer works fine on page reload..

**Comment by dschmidt** [comment]
Fixed in https://github.com/owncloud/web/pull/6456
