### ISSUE TITLE
Mimetype extension should be case preserving and is not

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5339]
Filenames are:
* TEST.png
* TEST.PNG

Both are shown equally which is very confusing.
![image](https://user-images.githubusercontent.com/5175912/122891738-0b41d500-d345-11eb-8370-ceef0c8adc8c.png)

**Comment by kulmann** [comment]
Analysis: file extension gets converted to lowercase here: https://github.com/owncloud/web/blob/274ea6b9f3d0068ed3a22ea7d314c08c401b8afa/packages/web-app-files/src/helpers/resources.js#L27 assigned to the resource object here https://github.com/owncloud/web/blob/274ea6b9f3d0068ed3a22ea7d314c08c401b8afa/packages/web-app-files/src/helpers/resources.js#L38 and used like that in the design system here https://github.com/owncloud/owncloud-design-system/blob/329e55351b8d34b344f28ade25cdf3318155760a/src/components/resource/OcResource.vue#L33

We are currently planning to come up with an interface for resources (typescript) and implementations for it (files, folders, shares). That's a good chance to solve this issue. E.g. by having two getters. One for unmodified file extension and one for a lowercase file extension for comparison purposes.

**Comment by kulmann** [comment]
Has not happened for a long time. Let's check why we have the lower case file extension at all. If it's only needed in a few cases we should use the original file extension again in the resource object and convert it to lower case on demand where needed.

**Comment by kulmann** [comment]
cc @axstet
