### ISSUE TITLE
Custom file action labels in oCIS extensions

### ISSUE THREAD

**Issue by anaswaratrajan** [owncloud/web#5369]
Currently, file actions from out of the box extensions can only have labels "Open in `extension-name`". I'm building an extension to provide some jupyter notebook features. The usecase requires adding 2 file actions to the filetype `.ipynb`. Is there a way to provide support for custom labels? Atleast the text after "Open in" will suffice. 

Further note: There are usecases where a file (Eg. `.doc`) can be opened with Collabora or office 365 with ocis-wopiserver where this support might be helpful. 

### Steps to reproduce

- Add 2 file actions to the appInfo object to the same extension. Like so -

```
const appInfo = {
  name: 'extension-name',
  id: 'extension-id',
  icon: 'icon-label',
  isFileEditor: false,
  extensions: [
    {
      extension: 'ipynb',
      newFileMenu: {
        menuTitle($gettext) {
          return $gettext('Random file action 0')
        }
      },
    },
    {
      extension: 'ipynb',
      newFileMenu: {
        menuTitle($gettext) {
          return $gettext('Random file action 1')
        }
      },
    }
  ]
}
```

### Expected behaviour
![ocis-jupyter-file-actions-expectation](https://user-images.githubusercontent.com/42616235/123378215-12b5e800-d5aa-11eb-88c3-cb96cec0f16f.png)

### Actual behaviour
![actual-ocis-jupyter](https://user-images.githubusercontent.com/42616235/123382611-c1a8f280-d5af-11eb-88d2-fd438b5a7e12.png)

**Comment by glpatcern** [comment]
+1!

A related discussion takes place in https://github.com/cs3org/reva/issues/1779 - eventually, we'd like the web to query for the list of possible handlers (or AppProviders in Reva's parlance) of a given file and show a menu item for each of them, plus registering one of them as "default" for the response to the direct click.

**Comment by pascalwengerter** [comment]
Has long been fixed [here](https://github.com/owncloud/web/blob/6714071acc81fa258fd37a7fb0615515cbb57b09/packages/web-app-files/src/mixins/fileActions.js#L184) with the App Provider, at least from my understanding
