### ISSUE TITLE
Refactor upload business logic and update tus-js-client to 2.3.0

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#5371]
We're using `tus-js-client` in version 1.8.0. The client is now at version 2.3.0 and received major improvements regarding upload tracking and fingerprinting. We should look into upgrading the client.

In addition to this it makes sense to clean up our code base regarding uploads. At the moment most of the code lives in the huge `mixins.js` of the files app. It makes sense to move code into helpers dedicated to uploads.

This is also a good chance to have a look at some earlier ideas of improving the upload handling with TUS:
- https://github.com/owncloud/web/pull/3436
- https://github.com/owncloud/web/pull/3472

**Comment by pascalwengerter** [comment]
Link to migration guide: https://tus.io/blog/2020/05/04/tus-js-client-200.html

**Comment by pascalwengerter** [comment]
Updating the tus-js-client was done in #6177 and the refactoring of the upload logic will be done together with #6268 so closing this ticket
