### ISSUE TITLE
Undefined steps in acceptance tests should fail CI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#5411]
Example: https://drone.owncloud.com/owncloud/web/16897/49/10
```
  tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature:144

    Given user "Alice" has been created with default attributes and without skeleton files
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 914 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 373 milliseconds.
√ Element <.oc-app-container> was visible after 982 milliseconds.
    And the user has browsed to the files page
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 62 milliseconds.
    Given user "Alice" has created file "lorem.txt"
    And the user has reloaded the current page of the webUI
    And user "Alice" has created a "normal" tag with name "lorem"
    ? undefined
    And user "Alice" has added tag "lorem" to file "/lorem.txt"
    ? undefined
    When the user browses to the tags page
    ? undefined
    And the user searches for tag "lorem" using the webUI
    ? undefined
    Then file "lorem.txt" should be listed on the webUI
    - skipped
    When the user deletes file "lorem.txt" using the webUI
    - skipped
    Then as "Alice" file "lorem.txt" should not exist
    - skipped
    And file "lorem.txt" should not be listed on the webUI
    - skipped
    When the user browses to the files page
    - skipped
    Then file "lorem.txt" should not be listed on the webUI
    - skipped
```

And that pipeline is using this expected-failures file:
```
Checking expected failures in /var/www/owncloud/web/tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
```

That scenario is listed in expected-failures. So maybe that is OK?

But maybe we should always fail the pipeline when some step(s) are undefined?

**Comment by dpakach** [comment]
@phil-davis  I think many of the undefined steps comes mostly from suites such as webUITags and webUIAdminSettings. these features are not available in web but the feature files were copied from core when we first constructed tests for web 2 years ago. Maybe we can delete those suites and copy them back when these features are available in web.

**Comment by phil-davis** [comment]
Could do so. Or we make "dummy" step definitions just have a call to make the step really fail?

It would be nice if nightwatch can pre-process a scenario, and if any step definition is not found, then fail the scenario without executing any steps. That would avoid wasting time in CI, where it currently executes  various `Given` steps  then fails. That wastes time creating the users/groups and then deleting them again.

**Comment by jasson99** [comment]
The following tests have undefined steps:
1. webUIAdminSettings:  [Admin settings feature not implemented yet](https://github.com/owncloud/web/issues/5015)
-   [webUIAdminSettings/adminAppsSettings.feature:11](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminAppsSettings.feature#L11)
-   [webUIAdminSettings/adminAppsSettings.feature:17](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminAppsSettings.feature#L17)
-   [webUIAdminSettings/adminGeneralSettings.feature:12](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature#L12)
-   [webUIAdminSettings/adminGeneralSettings.feature:30](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature#L30)
-   [webUIAdminSettings/adminGeneralSettings.feature:36](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature#L36)
-   [webUIAdminSettings/adminGeneralSettings.feature:42](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature#L42)
-   [webUIAdminSettings/adminGeneralSettings.feature:49](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature#L49)
-   [webUIAdminSettings/adminGeneralSettings.feature:56](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature#L56)
-   [webUIAdminSettings/adminGeneralSettings.feature:63](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature#L63)
-   [webUIAdminSettings/adminSharingSettings.feature:8](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L8)
-   [webUIAdminSettings/adminSharingSettings.feature:14](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L14)
-   [webUIAdminSettings/adminSharingSettings.feature:20](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L20)
-   [webUIAdminSettings/adminSharingSettings.feature:26](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L26)
-   [webUIAdminSettings/adminSharingSettings.feature:32](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L32)
-   [webUIAdminSettings/adminSharingSettings.feature:38](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L38)
-   [webUIAdminSettings/adminSharingSettings.feature:44](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L44)
-   [webUIAdminSettings/adminSharingSettings.feature:50](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L50)
-   [webUIAdminSettings/adminSharingSettings.feature:56](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L56)
-   [webUIAdminSettings/adminSharingSettings.feature:63](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L63)
-   [webUIAdminSettings/adminSharingSettings.feature:69](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L69)
-   [webUIAdminSettings/adminSharingSettings.feature:75](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L75)
-   [webUIAdminSettings/adminSharingSettings.feature:82](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L82)
-   [webUIAdminSettings/adminSharingSettings.feature:89](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L89)
-   [webUIAdminSettings/adminSharingSettings.feature:96](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L96)
-   [webUIAdminSettings/adminSharingSettings.feature:103](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L103)
-   [webUIAdminSettings/adminSharingSettings.feature:110](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L110)
-   [webUIAdminSettings/adminSharingSettings.feature:117](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L117)
-   [webUIAdminSettings/adminSharingSettings.feature:124](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L124)
-   [webUIAdminSettings/adminSharingSettings.feature:131](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L131)
-   [webUIAdminSettings/adminSharingSettings.feature:138](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L138)
-   [webUIAdminSettings/adminSharingSettings.feature:145](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature#L145)
-   [webUIAdminSettings/adminStorageSettings.feature:8](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature#L8)
-   [webUIAdminSettings/adminStorageSettings.feature:14](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature#L14)
-   [webUIAdminSettings/adminStorageSettings.feature:20](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature#L20)
-   [webUIAdminSettings/adminStorageSettings.feature:29](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature#L29)
-   [webUIAdminSettings/adminStorageSettings.feature:48](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature#L48)
-   [webUIAdminSettings/adminStorageSettings.feature:64](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature#L64)
-   [webUIAdminSettings/adminStorageSettings.feature:81](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature#L81)
-   [webUIAdminSettings/adminStorageSettings.feature:99](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature#L99)
-   [webUIAdminSettings/adminStorageSettings.feature:109](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature#L109)
-   [webUIAdminSettings/adminStorageSettings.feature:120](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature#L120)
-   [webUIAdminSettings/adminStorageSettings.feature:135](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature#L135)
-   [webUIAdminSettings/helpAndTips.feature:16](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/helpAndTips.feature#L16)
-   [webUIAdminSettings/helpAndTips.feature:17](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/helpAndTips.feature#L17)
-   [webUIAdminSettings/helpAndTips.feature:18](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/helpAndTips.feature#L18)
-   [webUIAdminSettings/helpAndTips.feature:19](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/helpAndTips.feature#L19)
-   [webUIAdminSettings/helpAndTips.feature:20](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAdminSettings/helpAndTips.feature#L20)

**Comment by jasson99** [comment]
### 6. webUIFileDetails: [Tags page not implemented yet](https://github.com/owncloud/web/issues/5017)
-   [webUIFilesDetails/fileDetails.feature:143](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIFilesDetails/fileDetails.feature#L143)

**Comment by jasson99** [comment]
### 9. webUISharingAcceptShares:
-   [webUISharingAcceptShares/acceptShares.feature:71](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature#L71)

### 10. webUISharingAcceptSharesToRoot:
- [webUISharingAcceptSharesToRoot/acceptShares.feature:172](https://github.com/owncloud/web/blob/master/tests/acceptance/features/tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature#L172)
- [webUISharingAcceptSharesToRoot/acceptShares.feature:190](https://github.com/owncloud/web/blob/master/tests/acceptance/features/tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature#L190)
- [webUISharingAcceptSharesToRoot/acceptShares.feature:208](https://github.com/owncloud/web/blob/master/tests/acceptance/features/tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature#L208)
- [webUISharingAcceptSharesToRoot/acceptShares.feature:215](https://github.com/owncloud/web/blob/master/tests/acceptance/features/tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature#L215)

**Comment by jasson99** [comment]
### 11. webUISharingExternalToRoot: Might need to adjust test steps
- [webUISharingExternalToRoot/federationSharing.feature:167](https://github.com/owncloud/web/blob/master/tests/acceptance/features/tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature#L167)

**Comment by jasson99** [comment]
### 17. webUITags: [Tags page not implemented yet](https://github.com/owncloud/web/issues/5017)
-   [webUITags/createTags.feature:16](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUITags/createTags.feature#L16)
-   [webUITags/createTags.feature:26](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUITags/createTags.feature#L26)
-   [webUITags/createTags.feature:37](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUITags/createTags.feature#L37)
-   [webUITags/createTags.feature:51](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUITags/createTags.feature#L51)
-   [webUITags/createTags.feature:61](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUITags/createTags.feature#L61)
-   [webUITags/createTags.feature:79](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUITags/createTags.feature#L79)
-   [webUITags/tagsSuggestion.feature:25](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUITags/tagsSuggestion.feature#L25)
-   [webUITags/tagsSuggestion.feature:35](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUITags/tagsSuggestion.feature#L35)

**Comment by jasson99** [comment]
The tests related to `AdminSettings`, `comments`, and `tags` have been removed now. This is moved to backlog now, as we have planned to make some changes in nightwatch(if possible) such that the tests are parsed before they are run and whenever there is not stepdefinition, the tests fail early.

**Comment by phil-davis** [comment]
I moved this out of the backlog. Can someone please report the status of this. It would be nice that if we accidentally write a typo in a feature file, that the undefined step causes the CI to fail - otherwise it is easy not to notice this kind of accidental error.

**Comment by pascalwengerter** [comment]
> I moved this out of the backlog. Can someone please report the status of this. It would be nice that if we accidentally write a typo in a feature file, that the undefined step causes the CI to fail - otherwise it is easy not to notice this kind of accidental error.

Pretty sure this is the status as of now? We've had this a bunch of times now with the middleware

**Comment by phil-davis** [comment]
> Pretty sure this is the status as of now? We've had this a bunch of times now with the middleware

I noticed this week the problem that if:
- a scenario is already in expected-failures, and
- someone refactors the scenario (for example, to change some Given step(s) to a form that uses the middleware) and
- they make a typo in the step text

Then CI does not fail.

The scenario now fails in a different way - it has an undefined step. But the scenario is in expected-failures so the pipeline still "passes".

Maybe we can add a dry-run of all the acceptance test scenarios as a pipeline that happens "early" in CI. That could be done in a pipeline that runs at the same time as the e2e tests, or even earlier at the same time as other "lint"-related pipelines. That would catch undefined steps in feature files.

**Comment by phil-davis** [comment]
We are currently pinned to nightwatch https://github.com/nightwatchjs/nightwatch/releases/tag/v1.7.11 
nightwatch is up to release https://github.com/nightwatchjs/nightwatch/releases/tag/v2.1.7

@individual-it 
What to do? Update to nightwatch v2 and then do something to address this issue? Close this issue and stay on nightwatch v1? Or?

**Comment by individual-it** [comment]
I would suggest to have a short looks how difficult and how time-consuming it would be to update nightwatch. If it requires too much refactoring I would be reluctant to update because we don't want to focus on nightwatch tests in future

**Comment by SwikritiT** [comment]
Since we've decided that we won't be making any changes in Nightwatch tests, let alone implementing new steps, this issue is now irrelevant. Now what we can do is remove all the scenarios that have unimplemented steps. I'll create a separate issue for that. I'm closing this issue.

cc @phil-davis @individual-it @kiranparajuli589

**Comment by SwikritiT** [comment]
new issue to remove undefined steps is here: https://github.com/owncloud/web/issues/7215
