### ISSUE TITLE
Lock information on resources is not present

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5417]
### Steps to reproduce
1. user locks a file/folder
2. look for lock information (lock icon, locks section in app sidebar) in the web UI

### Expected behaviour
expect to see lock information like in `oC10`
![lockinfo](https://user-images.githubusercontent.com/52366632/123905941-07d8ca00-d993-11eb-998e-41b9f09c2406.png)

### Actual behaviour
cannot see any information about locked resources in the webUI

### Server configuration
**Operating system**: `Ubuntu20.04`
**Web server:** `Apache`
**Database:** `MySQL`
**PHP version:** `7.3`
**ownCloud version:** `ownCloud 10.8.0 prealpha (git)`

**Comment by micbar** [comment]
fixed by https://github.com/owncloud/ocis/pull/2280

**Comment by pascalwengerter** [comment]
> fixed by [owncloud/ocis#2280](https://github.com/owncloud/ocis/pull/2280)

@micbar you mean the capability is now part of oCIS, right? AFAIK we're not displaying locked state (or the interaction to lock a file/folder) in `web` even if OC10 is able to. Might be worth to add this soon now that both backends support it

**Comment by micbar** [comment]
interesting. The CI just "passes" now after a reva update.

**Comment by micbar** [comment]
was a false positive in the CI

**Comment by kulmann** [comment]
acceptance criteria to get this done:
- [ ] add locking related props to `DavProperty` and `DavProperties.Default`
- [ ] add to resource mappings in `resources.js`
- [ ] create indicator with a `lock` icon for the file list
- [ ] add locking information to `Details` panel in right sidebar

**Comment by JammingBen** [comment]
Solved meanwhile via https://github.com/owncloud/web/pull/9566 and https://github.com/owncloud/web/pull/9658.
