### ISSUE TITLE
[media-viewer] Reloading does not work

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#5427]
### Steps to reproduce
1. Open an image in the media-viewer
2. Reload the page

### Expected behaviour
The same image that was shown before the reload is shown again

### Actual behaviour
MediaViewer triggers `loadFolder` action which fails because it was removed in https://github.com/owncloud/web/pull/4627, more specifically in https://github.com/owncloud/web/pull/4627/commits/138a492fcce7bee73aba162d1997c30f2229810e.
A broken MediaViewer is shown, but at least it can be closed by clicking the `x`.

![Screenshot_20210701_000549](https://user-images.githubusercontent.com/448487/124037608-1c06e080-da00-11eb-9c1e-72af245fdab6.png)

`loadFolder` is still used in
https://github.com/owncloud/web/blob/master/packages/web-app-media-viewer/src/mixins/loader.js#L31
https://github.com/owncloud/web/blob/master/packages/web-runtime/src/components/Notifications.vue#L67

This issue is caused by the former appearance, more issues might be caused by the latter - but I don't know :-)

When we fix it, we should add tests to avoid another regression further down the road...

@LukasHirt (as you replaced the `loadFolder` with new code:) is this a no-brainer for you to fix? 
Then I'd be happy if you could fix it. If not, I'd still be happy for pointers and I can probably take care of it

**Comment by LukasHirt** [comment]
It should be a no-brainer, I can take care of it
