### ISSUE TITLE
Update social preview image

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#5440]
### Expected behaviour
As someone sharing the link to this repo on socials, I'd expect the preview image to be up to date

### Actual behaviour
Preview image still contains the old project name "Phoenix"

<img width="325" alt="Screenshot 2021-07-02 at 11 34 37" src="https://user-images.githubusercontent.com/16822008/124262156-98e1a980-db29-11eb-8bdc-d936febbd8d5.png">

Can easily be done by a repo admin in the settings

**Comment by ChrisEdS** [comment]
Also the color is the old one. New color code is #041e42.

**Comment by kulmann** [comment]
Update to
<img width="1280" alt="Web App" src="https://user-images.githubusercontent.com/3532843/124273493-5d060e80-db40-11eb-893c-1eae6717ccae.png">

Please close this issue if you think this solves our needs @pascalwengerter
