### ISSUE TITLE
Permissions: Web UI does not properly check for Download permission for files

### ISSUE THREAD

**Issue by rpocklin** [owncloud/web#5451]
Permission Issue - there is a missing check for the 'D' on files to validate whether the Download option is shown in the File Sidebar.

### Steps to reproduce
1.  Remove the ability for a user to download a file `extendedAttributes.push({ scope: 'permissions', key: 'download', enabled: false })`
2. Using a new browser window, go to the Web UI and login as the user you modified.
2.  Navigate to a file which the user could previously download.
3.  Highlight the file.
4. 'Download' option is present in the Sidebar under Actions, yet clicking the download correctly gives a 403 Forbidden error (and will do every time).

![image](https://user-images.githubusercontent.com/876651/124533696-26890600-de56-11eb-8057-26eaa4e5a75a.png)

### Expected behaviour
Should not show 'Download' under actions.

### Actual behaviour
Show 'Download' under actions.

### Recommended Fix
Change this function:
https://github.com/owncloud/web/blob/589cf7ee4c59b21fd35eb370e3ba1f5c7f5bef2a/packages/web-app-files/src/helpers/resources.js#L63-L66

To this:
```
    canDownload: function() {
      return !isFolder && this.permissions.indexOf('R') >= 0
    },
```

I have tested this on our own codebase with success.

See #5452 for a similar related issue for copying of files.

**Comment by kulmann** [comment]
oCIS has an `X` webdav permission now, which prohibits downloads. Was implemented in web with https://github.com/owncloud/web/pull/10973
