### ISSUE TITLE
Permissions: Web UI does not properly check for Copy permission for files

### ISSUE THREAD

**Issue by rpocklin** [owncloud/web#5452]
Permission Issue - there is a missing check for the ability to **create** on the parent folder to enable the Copy option being shown in the File Sidebar.

### Steps to reproduce
1.  Remove the ability for a user to create files in a folder.
2. Using a new browser window, go to the Web UI and login as the user you modified.
2.  Navigate to a file which the user could previously create new files.
3.  Highlight the file.
4. 'Copy' option is present in the Sidebar under Actions, yet attempting the operation fails (and will do every time).

![image](https://user-images.githubusercontent.com/876651/124538025-52a88500-de5e-11eb-8229-010b5030792f.png)

### Expected behaviour
Should not show 'Copy' under actions.

### Actual behaviour
Show 'Copy' under actions.

### Recommended Fix
Change this function:
https://github.com/owncloud/web/blob/871ec76571fce1f139013191e2506459dd77148f/packages/web-app-files/src/mixins/actions/copy.js#L25-L30

To this:
```
            return this.currentFolder.canCreate()
          }
```

I have tested this on our own codebase with success.  I am not sure why you would return true and only check the `canCreate` function for public pages.  IMO it should be a similar check for `canCreate` which does show and hide the buttons with the main file navigator correctly.

See #5451 for a similar related issue for downloading of files.

**Comment by JammingBen** [comment]
Hi @rpocklin, is this still an issue for you? IMO it is the correct behaviour now: The copy-action is available for files inside a read-only folder, but you are not allowed to paste them into such folder.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/50302941/236778020-5574a950-ac0d-4fa8-a947-8d883858684d.png">
