### ISSUE TITLE
Allow extensions to inject views in files app

### ISSUE THREAD

**Issue by diocas** [owncloud/web#5460]
As we discussed before, this feature would allow extensions to hook into the files app in order to add extra buttons in the sidebar menu. These buttons would route to provided views, thus extending the normal files app with extra functionality.

Example, in our case we will create an extension to list our EOS Projects (while we wait for the spaces functionality).

@kulmann feel free to improve the description of this ticket.

**Comment by fschade** [comment]
@diocas thank you for the request, we are currently defining how the api for such a feature could look like. We did something like that by using portals but not sure if this is a good fit in your case.

You have any idea or input how such a api could look like from the perspective of a extension developer?

**Comment by diocas** [comment]
@elizavetaRa do you have suggestions?

**Comment by JammingBen** [comment]
Closing here since this has been implemented via https://github.com/owncloud/web/pull/9814. We will shortly update our dev docs with all the information about the extension system.
