### ISSUE TITLE
[ocis] no checkbox for share while using advanced permissions as role

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#5461]
### Steps to reproduce
1. create a user `uu1`
2. create a folder `simple` using user `uu1`
3. login as user `uu1
4. open actions sidebar for folder `simple
5. expand `People` dropdown
6. select `advanced permissions` for the role field

### Expected behavior
share checkbox should be visible

### Actual behavior
share checkbox is not available
![Screenshot from 2021-07-07 09-56-11](https://user-images.githubusercontent.com/39373750/124699222-1599cc80-df0a-11eb-8a11-aca92bb1b7e4.png)

### Configurations
- ocis: `git` `latest`

**Comment by kulmann** [comment]
oCIS doesn't support resharing, yet. As soon as it's implemented and properly announced in capabilities the web ui will respect it. Closing here since there are no code changes needed.
