### ISSUE TITLE
[ocis] share recipient doesn't see resharer in collaborators list

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#5462]
### Steps to reproduce
1. create users `uu1`, `uu2`, `uu3`, `uu4`
2. create a group `grp1`
3. add user `uu4` to grp `grp1`
2. create a folder `simple` using user `uu2`
3. share folder `simple` with `uu1` using `uu2`
4. accept the incoming share for folder `simple` using `uu1`
5. share folder `simple` with `uu3` using `uu2`
4. accept the incoming share for folder `simple` using `uu3`
5. share `Shares/simple` with user `uu4` using `uu1`
6. share `Shares/simple` with group `grp1` using `uu3`
7. accept the share offered by `uu1` for `simple` using `uu4`
8. login as user `uu4`
9. open `Shares` folder and open share dialog for folder `simple`
### Expected behaviour
( display names of users are visible on WebUI)
- user `uu2` should be listed as `owner`
- `uu1` and `uu3` should be listed as `reshared through`

### Actual behavior
- user `uu2` is listed as the owner ✅ 
- only `uu1` is listed as `re-sharers` ⛔ 

### Server configuration
OCIS:
- Version: git
- Branch: latest master

### References
- tests is covered [here](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIResharing1/reshareUsers.feature#L260)

**Comment by amrita-shrestha** [comment]
Closing this issue beacuse reshare has been deprecated from ocis on this PR https://github.com/owncloud/ocis/pull/8762. Mentioned in migration doc https://github.com/owncloud/docs-ocis/pull/739/files#diff-04cd79e526c8a7f0162d8fc5bc5fa8c501fe9e5899024268837c05a74349b26cR148-R149
