### ISSUE TITLE
browsing directly to a details 'tab'  is not possible

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#5464]
in oC10 UI a file can be selected and a specific details tab can be opened by providing an detailed URL. e.g. `localhost/owncloud-core/index.php/apps/files/?dir=/&fileid=2147484025&details=shareTabView` will open the sharing tab of the file with the id `2147484025`

Is a similar feature planned for web? We have those tests currently skipped in web, so if this feature is planned we should run those tests and put them in the expected failures list or if the feature will not come in the foreseen future we should delete those tests

**Comment by kulmann** [comment]
Yes, IMO a feature worth having. Please add to expected failures. 👍 
cc @tbsbdr for the links concepting

**Comment by JammingBen** [comment]
Has been implemented via https://github.com/owncloud/web/pull/8021.
