### ISSUE TITLE
No batch action buttons in favorites page

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5467]
### Description
From (including) commit id `e8eef030324fc40ed7660b9ba5388e5d172c5852`, batch action buttons do not appear in favorites page whenever the file is selected.
(Also you can see some options are missing in sidebar's actions menu)

This is a merge commit which links to PR https://github.com/owncloud/web/pull/5340

### Steps to reproduce
1. as admin, create folder `COOL`
2. mark folder `COOL` as favorite
3. goto favorites page
4. select folder `COOL`

### Expected behaviour
expected to see batch action buttons as it did previously
![batchac_old](https://user-images.githubusercontent.com/52366632/124752524-ae9b0880-df47-11eb-9741-21133a93bdaa.png)

### Actual behaviour
no batch action buttons
![batchac_new](https://user-images.githubusercontent.com/52366632/124752584-c1154200-df47-11eb-903c-8e977fcf766d.png)

### Server configuration
**Operating system**: `Ubunut 20.04`
**Web server:** `Apache`
**Database:** `MySQL`
**PHP version:** `7.4`
**ownCloud version:** `10.8.0 prealpha (git)`

**Comment by individual-it** [comment]
@kulmann @fschade is this change intended?

**Comment by kulmann** [comment]
Not intended. Needs investigation

**Comment by kulmann** [comment]
Not relevant anymore because in https://github.com/owncloud/web/pull/5973 batch actions have been removed from the favorites page entirely (by design).
