### ISSUE TITLE
Unify test locations

### ISSUE THREAD

**Issue by fschade** [owncloud/web#5471]
As [discussed](https://github.com/owncloud/web/discussions/5425) we decided to use `test` as the default tests location.
We now need to unify all tests to this location and adjust the jest config.

## tasks:
- [x] move all *.spec.ts, *.spec.js, or other test related files into `packages/{{app-name}}/tests/unit` or `packages/{{app-name}}/tests/integration` folder
- [x] check jest config

**Comment by individual-it** [comment]
fix in #5412
