### ISSUE TITLE
share file that has versions

### ISSUE THREAD

**Issue by fschade** [owncloud/web#5472]
sharing a file that has multiple version seems to be broken.

## steps to reproduce
- upload a file
- upload the same file again an confirm the "create version" dialogue
- then try to share the file with another user

the collaborator dropdown shows for a few moments and then disappears right after.
It only happens in ocis, not oc10

**Comment by kulmann** [comment]
Doesn't happen in oCIS either. What you describe happens when you enter a username of a user who already received a share for the same file. Was trying to find a similar issue now in this repo, but couldn't find one... :-/

**Comment by individual-it** [comment]
I cannot reproduce nether what @fschade nor what @kulmann is describing, is that problem fixed?

**Comment by kulmann** [comment]
I guess so, can't reproduce either.
