### ISSUE TITLE
[QA] applications[].url is documented inconsistently http:// and https://

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#5491]
Seen in  https://owncloud.dev/clients/web/deployments/oc10-app/#configure-owncloud-web while testing oc10.8.0 beta2
```
"applications" : [
    {
      ...
      "url": "http://<your-owncloud-server>/index.php/apps/files"
   },
    {
      ...
      "url": "https://<your-owncloud-server>/index.php/settings/personal"
    }
```

The two URLs differ in their schema.

Expected behaviour: Document the reason, why they have to differ, or make them equal (suggest all https://)

**Comment by JanAckermann** [comment]
@mmattel FYI

**Comment by micbar** [comment]
this is devdocs -> web team

@LukasHirt @pascalwengerter Let us use both times `https`
