### ISSUE TITLE
[QA] Ldap users are duplicated in the "Add People" dropdown

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#5498]
Seen in web-3.3.1 running on core 10.8.0-beta2

* Create "User Local" in owncloud.
* Create "User One" and "User Two" via LDAP
* Type in a search prefix that matches all three E.g. `User ` 
* Each ldap user is show twice, the local user is only shown once.
![image](https://user-images.githubusercontent.com/1108546/125067914-26d30c80-e0b5-11eb-8c44-8e6eb585aa25.png)

**Comment by micbar** [comment]
@pmaier1 @tbsbdr @hodyroff At the moment, the only possible qa-blocker.

**Comment by fschade** [comment]
@jnweiger tried to reproduce. The case seems not to happen in my local setup (user9999 is my local user).
Could you check your ldap if the user is there  twice?

Stack:
- openLDAP 2
- [ownCloud 10.8.0-beta2](https://hub.docker.com/layers/owncloud/server/10.8.0-beta2/images/sha256-71985aee51389be340818bc6c4eb39451d8e8faecbbd0e996278d093006be3f6?context=explore)
- [web v3.4.0] (https://github.com/owncloud/web/releases/tag/v3.4.0)

<img width="1185" alt="Bildschirmfoto 2021-07-11 um 19 27 15" src="https://user-images.githubusercontent.com/49308105/125204572-45383400-e27e-11eb-8afc-61affe4f3c05.png">
<img width="1187" alt="Bildschirmfoto 2021-07-11 um 19 27 10" src="https://user-images.githubusercontent.com/49308105/125204576-48332480-e27e-11eb-8636-936413127517.png">
<img width="1186" alt="Bildschirmfoto 2021-07-11 um 19 27 05" src="https://user-images.githubusercontent.com/49308105/125204577-48332480-e27e-11eb-88b3-564eed3be5c1.png">
<img width="1186" alt="Bildschirmfoto 2021-07-11 um 19 26 59" src="https://user-images.githubusercontent.com/49308105/125204579-49645180-e27e-11eb-8330-2bcfbebbe16d.png">
<img width="1179" alt="Bildschirmfoto 2021-07-11 um 19 26 54" src="https://user-images.githubusercontent.com/49308105/125204580-49645180-e27e-11eb-863d-2c45a8c887af.png">
<img width="1169" alt="Bildschirmfoto 2021-07-11 um 19 26 48" src="https://user-images.githubusercontent.com/49308105/125204581-49fce800-e27e-11eb-880f-abc953f9be73.png">
<img width="1185" alt="Bildschirmfoto 2021-07-11 um 19 26 43" src="https://user-images.githubusercontent.com/49308105/125204582-4a957e80-e27e-11eb-84a3-29b596bf3e7f.png">
<img width="1163" alt="Bildschirmfoto 2021-07-11 um 19 26 24" src="https://user-images.githubusercontent.com/49308105/125204584-4b2e1500-e27e-11eb-8e08-222486dc631c.png">
<img width="1432" alt="Bildschirmfoto 2021-07-11 um 19 25 35" src="https://user-images.githubusercontent.com/49308105/125204586-4b2e1500-e27e-11eb-9013-c2525a63995d.png">
<img width="1336" alt="Bildschirmfoto 2021-07-11 um 19 21 15" src="https://user-images.githubusercontent.com/49308105/125204588-4c5f4200-e27e-11eb-8fe5-a4e65c874696.png">
<img width="1158" alt="Bildschirmfoto 2021-07-11 um 19 20 13" src="https://user-images.githubusercontent.com/49308105/125204589-4e290580-e27e-11eb-90fb-d2bfb6faa105.png">
<img width="1435" alt="Bildschirmfoto 2021-07-11 um 19 19 14" src="https://user-images.githubusercontent.com/49308105/125204590-4ec19c00-e27e-11eb-94cc-74c4dda29438.png">

**Comment by jnweiger** [comment]
This was due to duplicate imports from my LDAP server. I'll investigate there, should not have happened, but I already have an idea, what might have caused it.
The test system also sees duplicate entries in the admin overview and in sharing dialogs with the classic web UI.

Sorry for the noise.
Closed invalid.
