### ISSUE TITLE
Drone doesn't run the full ci on tags

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#5500]
Creating a tag in web doesn't result in a full ci run in drone, see e.g. here https://drone.owncloud.com/owncloud/web/17240

Tags have a hard requirement to run the full ci, because we want to release with confidence.

**Comment by phil-davis** [comment]
IMO it was accidentally broken by the change that analyses "unit-tests-only". That code "sees" that there were no diffs at all between the tag and master (they are the same!), and so it deduces that "only unit tests changed", and so there is no need to run acceptance tests - actually nothing at all changed!
