### ISSUE TITLE
[QA] Cannot create folder with .part in the folder name

### ISSUE THREAD

**Issue by sakshamgurung** [owncloud/web#5518]
### Steps to reproduce
1. User creates a folder `test.part`

### Expected behaviour
- The folder `test.part` should be created.

### Actual behaviour
Tell us what happens instead
- The folder `test.part` is not created and the create folder dialog box neither closes nor shows any warning and the create button is disabled.

![oc10-actual](https://user-images.githubusercontent.com/41365307/125391465-4a9f9680-e3c4-11eb-9651-cae86306cb63.png)

![oc10-after-create](https://user-images.githubusercontent.com/41365307/125391483-50957780-e3c4-11eb-8ee7-bef6a61fd035.png)

### Behavior in OCIS
- But the behavior is as expected in ocis
![ocis-part](https://user-images.githubusercontent.com/41365307/125391737-b5e96880-e3c4-11eb-9322-e69781624359.png)

**Comment by phil-davis** [comment]
Note: `.part` files are forbidden in oC10. They are used as temp files in chunked uploads.
![Screenshot from 2021-07-13 10-34-46](https://user-images.githubusercontent.com/1535615/125392600-2a70d700-e3c6-11eb-8838-7f43ac39ccd2.png)

The traditional web UI is aware of forbidden file type/extensions. `owncloud/web` needs to also be aware of these.

**Comment by pascalwengerter** [comment]
@tbsbdr citing Phil [here](https://github.com/owncloud/web/pull/5510/files#r670990812) this would need some sort of UI feedback. Could you draft a concept and create a story? :)

**Comment by phil-davis** [comment]
It should be easy enough for the web front-end to be aware of the forbidden file name patterns of the backend - that information should be available in some capability information. And the web front-end can display reasonable notification/error messages when a user tries to create/upload/rename/... to a forbidden name. That will make the front-end auto-adapt to the backend capability.

One of the challenges will be what to do with differences in the back-end forbidden file list between oC10 and oCIS. One day there will be federated sharing between sets of federated cloud storages that have a mix of oC10 and oCIS... and files might be shared from one federated cloud to another federated cloud storage where that file name is forbidden. (Not a web issue!)

**Comment by tbsbdr** [comment]
@kulmann is the ".part issue" (1) just a single case we missed for validation or is this a more (2) general problem, that we dont programmatically check backend-sensitiv against forbidden filenames?
- if (1) **"single case"** we would just need an additional validation error message "Folder name cannot end with ".part""
- if (2) **"general problem"** we would need a more programmatic approach I guess

**Comment by kulmann** [comment]
oC10 core has a file blacklist regex, see https://github.com/owncloud/core/blob/46ab926f70f8bb739b9d23e4bde45f060f282346/lib/public/Files/FileInfo.php#L64

The capabilities in oc10 have an array `files.blacklisted_files` which only contains `.htaccess` has forbidden file name by default.

Maybe we can get it in 10.9 to add the regex in there as well? @JammingBen @JanAckermann @pmaier1 do you know details about the files blacklist and could give an opinion about this? Afaik we're already quite late or even too late for code freeze... :-/

**Comment by kulmann** [comment]
> @kulmann is the ".part issue" (1) just a single case we missed for validation or is this a more (2) general problem, that we dont programmatically check backend-sensitiv against forbidden filenames?
> 
> * if (1) **"single case"** we would just need an additional validation error message "Folder name cannot end with ".part""
> * if (2) **"general problem"** we would need a more programmatic approach I guess

Hotfix would be (1) since there is only a regex matching `part` and `filepart` in oc10 core. See comment above. Having it via capabilities would be nicer. But we already have some hardcoded checks for filenames, so it probably doesn't make it worse to add `.part` and `.filepart` in there.

**Comment by JammingBen** [comment]
> The capabilities in oc10 have an array files.blacklisted_files which only contains .htaccess has forbidden file name by default.
> Maybe we can get it in 10.9 to add the regex in there as well? @JammingBen @JanAckermann @pmaier1 do you know details about the files blacklist and could give an opinion about this? Afaik we're already quite late or even too late for code freeze... :-/

Personally, I wouldn't mix "full file names" and file extensions/parts (=regex) in one and the same property. The client would then require some logic to distinguish both cases. Also, as far as I understand, `blacklisted_files` is a fully configurable setting. Meaning if we add more default values here, they can easily be overwritten by an admin.

We're only talking file extensions here, aren't we? Maybe add an additional capability `blacklisted_file_extensions` or something like that?

**Comment by kulmann** [comment]
Thanks, additional capability for blacklisted file extensions would be fine as well 👍

**Comment by JammingBen** [comment]
https://github.com/owncloud/core/pull/39493 has been merged -> new capability `blacklisted_files_regex` will be available with 10.9.
