### ISSUE TITLE
create file with file handler does not refresh the files list

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#5530]
### Steps to reproduce
1. use oCIS with WOPI extension (eg. https://ocis.ocis-wopi.latest.owncloud.works/#/login or locally https://owncloud.dev/ocis/deployment/ocis_wopi)
2. create a new file with the file creation action of oCIS WOPI server
3. the file will open in Collabora
4. close Collabora / go back to oCIS
5. the file view is empty
6. refresh the page
7. the file you created before is there

### Expected behaviour
in 5) the file should be already displayed

### Actual behaviour
in 5) the file is not displayed

https://user-images.githubusercontent.com/34452982/125769087-b99b5748-8a56-49ca-948d-3adb07e2e5e9.mp4

### Server configuration
oCIS 1.9.0 with ownCloud Web 3.4.1
oCIS WOPI owncloud/ocis-wopiserver@02083dea4f213be94455007ffffb376f5ad1c9f4

**Comment by pascalwengerter** [comment]
From my understanding that technically not a bug since we're not using websockets at the moment and don't update the UI state from the server, yet a good feature request to implement this!

**Comment by wkloucek** [comment]
> From my understanding that technically not a bug since we're not using websockets at the moment and don't update the UI state from the server, yet a good feature request to implement this!

I'm not creating a file on the server side. I'm creating it directly in ownCloud Web just like creating a new folder. Folders are correctly displayed after creating.

**Comment by dschmidt** [comment]
Can be reproduced with draw.io integration.
Create a new draw.io document: draw.io app opens automatically in a new tab but the file list in the old tab is not reloaded, although the file is immediately created even without saving in draw.io.

**Comment by dschmidt** [comment]
Oh sweet :-)
