### ISSUE TITLE
[oCIS] Deleting accepted share doesn't change share status from Accepted to Declined

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5532]
### Steps to reproduce
(using web with oCIS server)
1. as admin, create folder `FOLDER` and share it with user `moss` with all permissions (look #5531)
2. as moss, accept the share from `share-with-me` page
3. as moss, open Shares folder and delete folder `FOLDER`
4. as moss, navigate to  `share-with-me` page (The share status is still `Accepted`)

### Expected behaviour
expected to see `Declined` share status after the shared folder has been deleted from Shares folder

### Actual behaviour
the status of share doesn't change (status is still `Accepted`)

### Server configuration
oCIS server built from latest master

**Comment by kulmann** [comment]
Apparently fixed in latest ocis version. CI reported this issue as unexpected pass in https://github.com/owncloud/web/pull/5602
