### ISSUE TITLE
[QA] private link to folder opens parent folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#5533]
Seen in oc 10.8.0-beta2 with web-3.3.1

* User admin creates a private link on folder beta2adminphotos
![image](https://user-images.githubusercontent.com/1108546/125788245-f31b0265-afa7-4a3c-af1e-24757d59c624.png)

* Paste the link into a fresh browser session
* authorize user admin
* the new Web UI opens the parent folder, highighting `beta2adminphotos` and its sidebar open.
![image](https://user-images.githubusercontent.com/1108546/125787809-dd5153bd-6dd3-4209-b97e-1d4e8f519324.png)

Expected behaviour: same as in classic web ui: the link opens the folder itself, without showing distracting parent folder contents.
![image](https://user-images.githubusercontent.com/1108546/125788194-c4160a5b-ba75-4b18-b0a1-09dfe6afb465.png)

**Comment by tbsbdr** [comment]
nope, if you share a folder, the receiver should view the contents of the folder.
why? Because most of the systems (I know) do it this way (dracoon, Google Drive, onedrive, dropbox, box, egnyte)
