### ISSUE TITLE
UI test steps "in the webUI"

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#5545]
Most of the acceptance test steps use "on the webUI" for when the user does something, or something exists "on the webUI"

In core we exclusively use "on the webUI" rather than "in the webUI" for consistency.

Most of the web acceptance test steps use "on the webUI" for when the user does something, or something exists "on the webUI". But there are about 15 steps that use "in the webUI".

Refactor so that we consistently say "on the webUI".

**Comment by saw-jan** [comment]
It would be good to have consistent test steps
