### ISSUE TITLE
[QA] enabling the new web UI is overly complex

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#5560]
Seen with https://github.com/owncloud/web/releases/download/v3.4.1/web-3.4.1.tar.gz

The steps to get the web UI up and running are described in 
* https://owncloud.dev/clients/web/deployments/oc10-app/#configure-owncloud-10
* we link to that calling it "easily"
![image](https://user-images.githubusercontent.com/1108546/126630860-7359f13e-4321-47d4-90a9-360f751d8dcd.png)

The linked instructions contain
* manually enabling another app,
* three config variables to set, including "[a] decision [that] should be carefully evaluated",
* a lengthy config file that needs to be created correctly, including a choice between two auth methods.

Expected behaviour: `occ app:enable web` should be sufficient, (as with other apps).
A web-setup-wizard app dialog could guide the user through the need decisions, if any.

**Comment by JammingBen** [comment]
Closing here since Web dropped support for oC10 with version 7.1.0. This means the process for enabling the UI in oC10 likely won't change.
