### ISSUE TITLE
Disabling search shifts topbar layout

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#5561]
### Steps to reproduce
1. Look at `All files` page with enabled searchbar (currently only possible in oc10)
2. Then...
  a. Disable search by setting `options.hideSearchBar` to `true` in `config.json` OR
  b. Browse to a page that doesn't have a search, e.g. personal menu -> `Account`

### Expected behaviour
The remaining content of the topbar should not shift to the left / remain in unchanged positioning

### Actual behaviour
The remaining content of the topbar shifts to the left

### Server configuration
**ownCloud version:** 10.6+

### Screenshots
<img width="1663" alt="Screenshot 2021-07-22 at 13 24 51" src="https://user-images.githubusercontent.com/3532843/126632111-8efac259-dddd-4595-ab7d-e5b1bbe82409.png">
<img width="1662" alt="Screenshot 2021-07-22 at 13 26 02" src="https://user-images.githubusercontent.com/3532843/126632114-9393e28e-ffa8-42b6-bd9c-9900b8361aef.png">

cc @refs thanks for spotting this

**Comment by pascalwengerter** [comment]
Resolved on current master

Without search:
![Screenshot 2021-08-25 at 09-54-41 All files - ownCloud](https://user-images.githubusercontent.com/16822008/130760701-a87408d8-ba57-41a4-a3c5-ab8cd622d9f7.png)

With search:
![Screenshot 2021-08-25 at 09-53-50 All files - ownCloud](https://user-images.githubusercontent.com/16822008/130760718-f2183ab7-bb43-43b5-baa9-75923b17e16f.png)
