### ISSUE TITLE
behavioral difference for sub-shares to classic frontend

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#5562]
### Description
On a oC10 backend there is a behavioral difference between the classic frontend and ownCloud Web when browsing on Sub-Shares.

### Steps to reproduce
1. Einstein shares Marie a folder "Root-Share" with read only permissions
2. Einstein creates a folder "Sub-Share" inside the "Root-Share" folder and shares it to Marie with full permissions
3. Marie browses to the "Root-Share" by using the classic frontend and isn't allowed to change anything inside the folder
4. Marie browses to the "Sub-Share" folder inside the "Root-Share" folder by using the classic frontend and isn't allowed to change anything inside the folder
5. Marie reloads the page and is now in the "Sub-Share" folder OUTSIDE of the "Root-Share" folder in the classic frontend and is allowed to change everything inside the folder
6. Marie browses to the "Root-Share" by using ownCloud Web and isn't allowed to change anything inside the folder
7. Marie browses to the "Sub-Share" folder inside the "Root-Share" folder by using ownCloud Web and isn't allowed to change anything inside the folder
8. Marie reloads the page and is still in the  "Sub-Share" folder INSIDE of the "Root-Share" folder in ownCloud Web and is isn't allowed to change anything inside the folder
9. Marie browses to the "Sub-Share" folder OUTSIDE of the "Root-Share" folder in ownCloud Web and is allowed to change everything inside the folder

https://user-images.githubusercontent.com/34452982/126636810-24441fa6-2f04-4174-aba3-e7198ebf5a4d.mp4

### Expected behaviour
It would be more desirable to not need to reload the page in the classic frontend (step 5) in order to see the right permissions of the "Sub-Share" - but that is out of scope here.

For compatibility reasons, ownCloud Web should mimic the behavior  of the classic frontend if possible (step 8 should have the same result as step 5).

An overkill solution would be to not have to refresh the page at all in ownCloud Web if the right permissions would be picked up automatically from the "Sub-Share". 
This is already the case in oCIS, but handled by the backend

https://user-images.githubusercontent.com/34452982/126637990-ba21882f-2d83-4631-879a-3b5a940eb964.mp4

### Actual behaviour
ownCloud Web does not behave like the classic frontend ( step 5 vs. step 8)

### Related Issues
- https://talk.owncloud.com/group/ocis-early-adopters?msg=2QfrF7m2xCkMDGffR

**Comment by wkloucek** [comment]
@rpocklin Thanks for raising the issue in the chat. Is your described case fully covered?
@kulmann @pascalwengerter

**Comment by rpocklin** [comment]
Yes - this is the behaviour I detected and was confused by.  My ideal scenario is that the UI 'acts' as though you are still in the sub-folder (eg. currenet OCIS UI behaviour) but correctly applies the _permissions_ of the sub-folder share.  I believe this is what most people would want, and even going so far as to hide the sub-folder share from the root folder in the default view.

This would effectively give you sub-folder permission controls on shares with minimal changes, although there may be performance impacts on turning this on.

**Comment by JammingBen** [comment]
Tested again as the share jail has been implemented in the meantime.

> Marie reloads the page and is still in the "Sub-Share" folder INSIDE of the "Root-Share" folder in ownCloud Web and is isn't allowed to change anything inside the folder

When reloading the page, you still stay inside "Sub-Share" folder inside of the "Root-Share", but you will be able to create folders. IMO this is the correct behaviour, no need to redirect the user to the single "Sub-Share" tree.
