### ISSUE TITLE
Display all available roles when creating shares

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#5572]
In reva, we support a variety of available roles when creating shares (some of which include the ability to reshare resources) https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocs/conversions/permissions.go#L28-L44

But in web, only viewer and editor are displayed https://github.com/owncloud/web/blob/master/packages/web-app-files/src/helpers/collaboratorRolesDefinition.js

**Comment by JammingBen** [comment]
With sharing NG, we display all the available roles the server is sending. Hence closing here.
