### ISSUE TITLE
Web always asks for permission to access your account if it is configured as defaultapp

### ISSUE THREAD

**Issue by fschade** [owncloud/web#5579]
As the title says, if web is configured as the default app in oc10 the user is asked for permission on every reload and logout.
Reported through [twitter](https://twitter.com/nemethstarpro/status/1420373899892690944?s=21)

### Steps to reproduce
1. setup oc10 10.8
2. setup oauth
3. enable web 
4. [Make ownCloud Web the default web interface](https://owncloud.dev/clients/web/deployments/oc10-app/#make-owncloud-web-the-default-web-interface)
5. login 
6. reload

### Expected behaviour
only ask the user for permissions if needed

### Actual behaviour
the permission dialogue appears on every reload

### Screenshot
![E7YuiIiXMAAbqpK](https://user-images.githubusercontent.com/49308105/127367083-8f426393-815d-4c60-97b8-b9cf4ab208a1.jpeg)

**Comment by LukasHirt** [comment]
Not a bug - currently needed behaviour

https://github.com/owncloud/web/issues/2064
https://github.com/owncloud/web/issues/511

Originally was supposed to be solved by ocis-brige which would completely remove the need for the oauth and would enable us to depend only on OIDC. Unfortunately that hasn't happened... :tired_face:

**Comment by pascalwengerter** [comment]
Wasn't this tackled and documented in https://owncloud.dev/clients/web/deployments/oc10-app/#configure-oauth2 @fschade @kulmann ?

**Comment by kulmann** [comment]
Yes 👍 was nut a bug but an enhancement in the oauth2 app and documented for web in the link that you provided.
