### ISSUE TITLE
Move action, user feedback is missing, takes very long

### ISSUE THREAD

**Issue by frankaellen** [owncloud/web#5584]
### Steps to reproduce
1. Choose file
2. Select file
3. Click move icon
4. Navigate to desired location
5. Press move here
6. Button gets disabled / greyed out
6. Wait
7. Wait …
8. Page reloads

### Expected behaviour
I as a user expect some sort of user feedback. System is thinking, a spinning wheel or something comparable. I was confused whether my action was submitted and if anything would happen. Additionally it took very long to perform the action itself.

### Actual behaviour
Button gets disabled / greyed out, nothing happens for a while.

### Server configuration
Internal ownCloud cloud

Please find here a screen recording:
"Click move - nothing happens for a while.mp4"
https://cloud.owncloud.com/index.php/f/5494391

Let me know if you need additional information.
Thank you! Looking forward to hearing from you :)

**Comment by JammingBen** [comment]
Has been tackled meanwhile via https://github.com/owncloud/web/pull/8611 -> closing.
