### ISSUE TITLE
Renaming of folders takes long, does not provide user feedback

### ISSUE THREAD

**Issue by frankaellen** [owncloud/web#5586]
### Steps to reproduce
1. Click on folder
2. Choose actions in right sidebar
3. Click Rename
4. Enter new folder name
5. Press rename
6. Nothing happens for a while
7. Dialog window disappears

### Expected behaviour
I as a user would expect some sort of user feedback. System is thinking, spinning wheel, could not rename, etc. Was confused whether my action was submitted at all. Then tried again and clicked cancel and reload. Renamed the folder anyway

### Actual behaviour
Button got greyed out / disabled, nothing happened. Dialog window disappeared after a while. Or: pressed cancel dialog window closes, pressed reload, folder was renamed anyway.

### Server configuration
ownCloud cloud

Please find here a screen recording: 
https://cloud.owncloud.com/index.php/f/5494391
"Renaming takes long, cancel, reload, renames anyway.mp4"

Let me know if you have additional questions. 
Thank you! Looking forward to hearing from you :)

**Comment by pascalwengerter** [comment]
@frankaellen where did you check that? 

- https://web.owncloud.com/ (latest web release with OC10)
- https://ocis.ocis-web.latest.owncloud.works (current web master with oCIS)
- ...?

**Comment by frankaellen** [comment]
Hey @pascalwengerter, 

on https://cloud.owncloud.com

**Comment by pascalwengerter** [comment]
Closing since I've never come across this and can't remember any similar complaints recently. We have a dedicated ticket to add waiting/loading indicators to the UI, but renaming folders usually works pretty fast (unless the backend is unresponsive or the connection laggy, ofc)
