### ISSUE TITLE
[oC10] Web UI: Redirecting  Please wait a while. You are being redirected

### ISSUE THREAD

**Issue by ivnmad** [owncloud/web#5587]
### Steps to reproduce
1. Followed instructions on https://owncloud.dev/clients/web/deployments/oc10-app/#configure-owncloud-10
2. Logged in ownCloud
3. Clicked on "New Design"
4. Authorised Access

### Expected behaviour
I should be able to see the Web UI interface instead of the Classic interface

### Actual behaviour
Redirecting  Please wait a while. You are being redirected (see screenshot)
Nothing happens after showing that message.

### Server configuration
**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB 10.3.29

**PHP version:** 7.3.29

**ownCloud version:** 10.8

-----------------

The log file doesn't show any errors.
The "Web" app is installed udner apps-external folder instead of apps folder.

![Screenshot 2021-07-29 at 14 44 26](https://user-images.githubusercontent.com/35845319/127506149-9d390e86-53de-40d0-ac9b-00c297884553.jpg)

**Comment by bfren** [comment]
I am having this issue too, I've gone round the houses on config etc.  I am seeing a JavaScript error in the console:

`failed to load app undefined TypeError: t is undefined` in `web-runtime-03539e51.js:1:69806`.

**Comment by pascalwengerter** [comment]
@ivnmad @bfren could you check with OC10.9 and the latest web release? We've made quite some progress in the last couple of months

**Comment by bfren** [comment]
@pascalwengerter I'm afraid not, the same issue occurs.  I am on OC 10.9.1.2 and Web app 4.9 (installed through the Market Place).  One thing I've not tried yet is installing it as a separate Docker container - mostly because I want it to run within the same site as the server.

**Comment by ivnmad** [comment]
OwnCloud version 10.9.1.2
Web app version  4.9.0

Followed the instructions again, but still no luck.
Nothing happens when after authorising the application, it just hangs.
I can see the message has changed since I opened this thread, but that was probably introduced via one of the latest updates.
Here the screenshots I've just taken:

![Screenshot 2022-02-09 at 21-41-05 ownCloud png](https://user-images.githubusercontent.com/35845319/153295415-c0423359-aa17-400c-a9dd-0bad6718dfea.jpg)

![Screenshot 2022-02-09 at 21-41-32 Oidc callback - ownCloud](https://user-images.githubusercontent.com/35845319/153295445-b624bbd0-fbdb-4589-974f-af6ae8e10256.png)

**Comment by bfren** [comment]
Yes those screenshots mirror exactly what happens on my setup.

**Comment by dschmidt** [comment]
In the meantime we reworked the auth flow, could you check again with oC Web 6.0.0?

**Comment by bfren** [comment]
Afraid not - the infinite loop persists though I briefly get a message as per the below:

![Screenshot 2022-12-14 102512](https://user-images.githubusercontent.com/17511478/207570394-83d9d6ee-ea8e-4773-9269-c70efa294fe3.png)

I can't click Log In Again before it automatically tries / redirects / loops.

**Comment by kulmann** [comment]
> Afraid not - the infinite loop persists though I briefly get a message as per the below:
> 
> ![Screenshot 2022-12-14 102512](https://user-images.githubusercontent.com/17511478/207570394-83d9d6ee-ea8e-4773-9269-c70efa294fe3.png)
> 
> I can't click Log In Again before it automatically tries / redirects / loops.
> 
> Web App 6.0.0, ownCloud 10.11.0.6 (Docker)

Hey, could you open the browser console and check if there are different errors than before? And also the `Network` tab and see if there are failing requests, and which error status codes they produce?

**Comment by bfren** [comment]
The issue appears to be related to something in the database - I ran it with the same setup, same server, config, same files, same everything - but a blank db - and the redirect didn't happen. 

However I went through the db user tables to see what could possibly be causing it and couldn't see anything likely 🤷‍♂️.

**Comment by SiebeVE** [comment]
> Just tried as well, and I can confirm the same exact behavior as reported by @bfren
> 
> ![Screenshot 2022-12-14 at 10 46 01](https://user-images.githubusercontent.com/35845319/207581462-f39af226-8833-4988-8f48-59baf30cef61.jpg)
> 
> Moreover, when I tried to remove the config.json file and the additional lines in config.php, ownCloud was still trying to login using the Web App. I had taken a snapshot before testing, so luckily restoring that solved the issue.

```
./occ app:disable web
```
Disables the new web ui so you can login again.

I've got the same redirect issue.

**Comment by JammingBen** [comment]
Closing here since Web dropped support for oC10 with version 7.1.0.
