### ISSUE TITLE
Incorrect Icon - Logout menu

### ISSUE THREAD

**Issue by rpocklin** [owncloud/web#5590]
In our user testing, we have found that the logout icon on the right-hand side dropdown is actually the UI Kit **sign-in** icon (https://getuikit.com/docs/icon).  This is labelled in **owncloud-design** as "exit_to_app".

(https://owncloud.design/#/Design%20Tokens/Icon) but isn't an accurate depiction of what the user is doing and feedback has been it's confusing for some people.

![image](https://user-images.githubusercontent.com/876651/127585682-356a6f43-d2e7-463a-bd99-72282f72a65a.png)

![image](https://user-images.githubusercontent.com/876651/127585617-0303f251-754f-49b3-a287-a2dff2ff86b4.png)

UI Kit has a "sign-out" icon (https://getuikit.com/docs/icon) which would work well here (would need to be added to **owncloud-design** first), and may be better to improve the naming of these 2 icons in **owncloud-design** to something like "enter" or "exit" so it could work for both apps and the user session use cases.

![image](https://user-images.githubusercontent.com/876651/127585639-a843a2b7-7bf1-47f0-abb4-431c2e468d43.png)

**Comment by pascalwengerter** [comment]
Great feedback! If @tbsbdr agrees we can make that happen _fast_ ™️

**Comment by tbsbdr** [comment]
nice one! and of course - please change it. Thanks a lot!!

**Comment by kulmann** [comment]
Fixed by https://github.com/owncloud/web/pull/5681
