### ISSUE TITLE
Shares folder "New" button should be invisible

### ISSUE THREAD

**Issue by lookacat** [owncloud/web#5591]
### Steps to reproduce
1. Go to Shares folder
2. Eg. create a new folder
3. When you try to create the folder the dialog doesn't show an error but won't work

### Expected behaviour
The "New"-Button should not be visible when inside Shares folder

### Actual behaviour
The "New"-Button as visible but actions wont work

**Comment by phil-davis** [comment]
https://github.com/owncloud/ocis/issues/2322 reports the same problem.

IMO we are coming to the decision that oC10 and OCIS servers are going to keep behaving differently for this - oC10 let's you write you own "random" stuff to the "Shares" folder. OCIS makes the "Shares" folder a place to only receive shares.

There might be back-end server changes to help clients understand whether they cam write directly into Shares or not.

And then clients need to respond effectively to that - e.g. the web browser client here.
