### ISSUE TITLE
[Bug] Mediaviewer: pictures with ü or # in filename cant be viewed in mediaviewer

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#5594]
A user reported the following bug via our survey https://owncloud.com/web-design-feedback (thanks for feedback!! )

### Steps to reproduce
1. goto demo.owncloud.com
2. upload a jpg file and give it the name "asd#2_Blick-nach-Süd_Hauswand_zu-#1.jpg"
3. click on the filename to open the image with the media viewer
4. mediaviewer shows a "❗️"
(preview in sidebar and thumbnail works)

![image](https://user-images.githubusercontent.com/26610733/127636394-f2ff63fb-ced1-4641-80ea-ccd5d0793633.png)
![image](https://user-images.githubusercontent.com/26610733/127636424-7b59fc92-b53c-407d-913a-087b913f9f86.png)

### Expected behaviour
show the image

### Actual behaviour
If the filename contains a # or ü the mediaviewer shows a "❗️"

**Comment by pascalwengerter** [comment]
Closed as duplicate to #5593 but referencing for more info + screenshots
