### ISSUE TITLE
[Bug] "Share" does not show sharing-dialog in right sidebar

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#5608]
### Steps to reproduce
1. login to https://ocis.ocis-web.latest.owncloud.works/
2. create fresh folder
3. rightclick -> "share"
4. no sharing in right sidebar
![2021-08-02_18-15-07 (1)](https://user-images.githubusercontent.com/26610733/127892953-e0bacb4a-cee4-4297-b9e3-7005b1fca68a.gif)

### Expected behaviour
You should see the sharing dialog:
![image](https://user-images.githubusercontent.com/26610733/127893092-56f0e9d5-e893-4436-b7d7-e871a3c012a6.png)

**Comment by kulmann** [comment]
Since we will have the invite form on the same level as the list of existing shares really soon, I don't see much priority on fixing this to be honest. 😅

**Comment by kulmann** [comment]
Will be fixed by https://github.com/owncloud/web/pull/6039
