### ISSUE TITLE
Broken acceptance tests defaults

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#5611]
Default `SERVER_HOST` and `BACKEND_HOST` has been recently changed in the code but not in the documentation. It should either be changed in the docs or brought back to the original value.

![image](https://user-images.githubusercontent.com/25989331/127975129-02a6d92f-a53c-43ba-91fa-af6a71f15d83.png)

**Comment by pascalwengerter** [comment]
@LukasHirt could you shed some light on what's broken here? Gave it a look last week and couldn't figure it out properly

**Comment by LukasHirt** [comment]
> Default SERVER_HOST and BACKEND_HOST has been recently changed in the code but not in the documentation.

@pascalwengerter https://github.com/owncloud/web/blob/8f9791cbd763acefbd20fff91b09b1241aa5f468/nightwatch.conf.js#L7
**vs**
https://owncloud.dev/clients/web/testing-manual/#available-settings-to-be-set-by-environment-variables

**Comment by pascalwengerter** [comment]
Closing since it's not recommended to run the acceptance tests un-dockerized (also `LOCAL_LAUNCH_URL` is being set _from_ SERVER_HOST if it's provided so shouldn't have changed the setup)
