### ISSUE TITLE
No default sorting/ Sort by name does not work correctly

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#5614]
[checkSort copy.zip](https://github.com/owncloud/web/files/6919460/checkSort.copy.zip)

-  ### **1.No default sorting:**

1. Upload folder with files [checkSort copy.zip](https://github.com/owncloud/web/files/6919460/checkSort.copy.zip)

2. Open folder "Check Sort"

**Expected behaviour:**
by default sort by name, then follow the selected sorting

**Actual behaviour:**
No default sorting. Files are displayed in the order in which the server sent them

- ### **2. The selected sorting is not saved:**

1. Open folder "Check Sort"
2. Choose the sort by name/size/modified
3. Go back to "All files"
4. Reopen folder "Check Sort"

**Expected behaviour:**
custom sort is saved and it works on all pages 

**Actual behaviour:**
custom sort is not saved

- ### **3. Sort by name does not work correctly:**

1. Open subfolder "Check Sort/WithText"
2. Choose the sort by name

**Expected behaviour:**
the order in which the files are displayed: copy0 -> copy1 -> copy02->copy2 ->copy101-> copy110

**Actual behaviour:**
the order in which the files are displayed: copy0 -> copy02 -> copy1 ->copy101 ->copy110-> copy2

![Screenshot 2021-08-03 at 11 58 03](https://user-images.githubusercontent.com/84779829/127997092-2f55d8dd-9d0d-4b3c-85a7-72203fa6120d.png)

- ### **4. Sort when file more than 100:**

1. Open subfolder "Check Sort/CheckPagination"
2. Choose the sort by name
3. Go to page 2

**Expected behaviour:**
files on page 2: 101, 102, 103, 104

**Actual behaviour:**
files on page 2: the last 4 files from the response (random)

![Screenshot 2021-08-03 at 11 53 17](https://user-images.githubusercontent.com/84779829/127996765-c402a3b7-3903-41f6-8733-16a2401e35e1.png)
![Screenshot 2021-08-03 at 11 56 52](https://user-images.githubusercontent.com/84779829/127996844-fa693c8f-0a2b-41d4-8a99-f97f5d2ea97f.png)

- ### **4. Sort by modified does not work corectly:**

1. Open subfolder "Check Sort"
2. Choose the sort by modified

**Actual behaviour:**
![Screenshot 2021-08-03 at 12 11 56](https://user-images.githubusercontent.com/84779829/127999146-01593dbf-1ee8-4f57-a398-ed26ebbb8091.png)

### Server configuration

branch: release-4.0.0
backend: ocis 1.9.0 with docker reachable at https://host.docker.internal:9200/
browser: chrome Version 92.0.4515.107

**Comment by kulmann** [comment]
Hey, good findings, thank you! Could you please split this issue into four different ones? Having one big issue makes it harder to work on fixing issues with pull requests.

**Comment by ScharfViktor** [comment]
Yeah sure, I'll do it.

**Comment by ScharfViktor** [comment]
https://github.com/owncloud/web/issues/5684
