### ISSUE TITLE
Avoid stacked batch actions on small screens

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#5633]
## Userstory
> As a user on a small screen I want the batch actions to be aligned in one row so that I dont get confused by a sudden stacked and mixed-up looking button alignment.

### Steps to reproduce
1. login to https://ocis.ocis-web.latest.owncloud.works/
2. select an item (sidebar should be open now)
2. check the items checkbox (batch actions should be visible now)
3. resize the browsers window until batch actions get stacked
![image](https://user-images.githubusercontent.com/26610733/128313688-f9596581-9b2d-43f4-bec0-98c522a58850.png)

### Expected behaviour
The batch actions should be visually clearly arranged, e.g. in one line. This could be achieved by dropping the text next to the icons from a certain breakpoint on. (We also thought of making the quickactions available via a drop-down menu, but on very small screens we would then have 2 dropdowns stacked on each other, as the breadcrumb becomes a dropdown on small screens.)

![image](https://user-images.githubusercontent.com/26610733/128317546-b4a5cd0b-2f2f-4545-a468-7fbfefb360aa.png) 

### Actual behaviour
Buttons are stacked

## Acceptance Criteria
- batch actions are not stacked
- only on small screens: remove text from the batch action buttons to save space
- only on small screens: remove clear "X"-button
- remove text "xx items selected - xx byte"
- Add tooltip "copy" "move" "delete" 

**what are small screens?** @paulcod3 lets tinker around on this, I currently have stacked buttons on < 1200 px (which is not "small" ;-) ) please give me a call, so we can define what "small screens" are. not sure about this yet.

**Comment by tbsbdr** [comment]
As discussed with benedikt, we could also consider to just provide a ... 3 dots button that "truncates" the buttons and show a drop with the truncated options. @tbsbdr add scribbles

**Comment by JammingBen** [comment]
Closing as we have the expected behaviour now :)
