### ISSUE TITLE
[Bug] Guests are displayed as "Users"

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#5634]
### Steps to reproduce
1. OC10.8: login to classic ui
2. share a file with a guest (enter an email)
3. switch to Web UI
4. select the same, shared file and open "People" section the sidebar
5. guest share with email gets displayed as "User" share (which is wrong, its a guest)

![image](https://user-images.githubusercontent.com/26610733/128336173-98e93e36-331c-4d03-8eae-5ab89203c457.png)

### Expected behaviour
Display "Guest" for guest shares

### Actual behaviour
Guest shares are displayed as "User" shares

## Background
- The Web UI relys on the share-type of oc10
- oC10 provides sharetype = 0 for guest shares which we won't change any more (sharetype 0 = user; sharetype 4 = guest)
- @kulmann mentioned that there should be a flag llike "isGuest" which we could use to display the right role in WebUI+oC10

**Comment by tbsbdr** [comment]
@JanAckermann do you maybe have an idea how to distinguish guests from users? @kulmann mentioned some flag or tag "isguest" do you maybe know more?

OCS api doesnt know about guests:

> The share’s type. This can be one of:
> 
> ```
> - 0 = user
> - 1 = group
> - 3 = public link
> - 6 = federated cloud share
> ```

https://doc.owncloud.com/server/next/developer_manual/core/apis/ocs-share-api.html

**Comment by JanAckermann** [comment]
@tbsbdr we only know this by config flag in oc_preferences. We can learn the API

**Comment by kulmann** [comment]
In oc10 you can do `$this->config->getUserValue($uid, 'owncloud', 'isGuest', false);` to determine in the php code if a user is a guest user. The classic UI is utilizing that information. To my knowledge there is no API that makes this information available. Best would be to use the proper `guest` share type in OCS responses. 😞 but I don't know the implications of such a change.

**Comment by JanAckermann** [comment]
@kulmann With ownCloud 10.7 I implemented user types that are `user` or `guest`.
We can emit this information via the share API, for example by adding a  new field called `<share_with_user_type/>`

I think breaking changes to the share api are not favorable.

**Comment by JanAckermann** [comment]
![image](https://user-images.githubusercontent.com/26169327/164727845-34a5bbea-c48c-4571-bc2d-80a24e2ddf4f.png)

**Comment by JanAckermann** [comment]
Oc10 Backend part: https://github.com/owncloud/core/pull/40013

**Comment by JanAckermann** [comment]
SDK part: https://github.com/owncloud/owncloud-sdk/pull/1046

**Comment by JanAckermann** [comment]
Frontend part: https://github.com/owncloud/web/pull/6813
