### ISSUE TITLE
PRs from forks fail the stop-recent-builds check

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#5640]
https://drone.owncloud.com/owncloud/web/18035/2/2
```
alpine: Pulling from drone/cli
Digest: sha256:29517295f5c1dd9ef78645f08afe360a47bc3e2bbac70c7dd755c61551b4202f
Status: Downloaded newer image for drone/cli:alpine
+ drone build ls rpocklin/phoenix --status running > /var/www/owncloud/web/recentBuilds.txt
client error 404: {"message":"Not Found"}
```

I suspect that either:
1) the person from the fork does not have privilege to list and cancel drone builds, or
2) the PR is from another repo, and so the `drone build ls` command does not understand the reference to another fork repository.

IMO we need to detect this case of a PR coming from a fork, and just skip stop-recent-builds from trying to do the `drone build` etc commands. The script can exit with "success" in this case, and do nothing.

**Comment by phil-davis** [comment]
The same problem is also in `owncloud/ocis` - needs to also be fixed there.

**Comment by wkloucek** [comment]
solved in:
- oCIS: https://github.com/owncloud/ocis/pull/2368
- Web: https://github.com/owncloud/web/pull/5645

**Comment by wkloucek** [comment]
always using `ctx.repo.slug` is safe from my point, since this is always the referrer to the drone repo, even if the PR is coming form an fork

**Comment by wkloucek** [comment]
@phil-davis a quick github search didn't find this on other repos. Do you know of any others?

**Comment by phil-davis** [comment]
> @phil-davis a quick github search didn't find this on other repos. Do you know of any others?

We haven't added this to other repos yet. core PR https://github.com/owncloud/core/pull/39074 needs to be finished, so @jasson99 can make sure to include the changes here.

**Comment by wkloucek** [comment]
@phil-davis this can be closed since https://github.com/owncloud/core/pull/39074 was merged, too!?

**Comment by phil-davis** [comment]
Yes - closing
