### ISSUE TITLE
ownCloud Web should display it's version somewhere.

### ISSUE THREAD

**Issue by dragotin** [owncloud/web#5657]
### Expected behaviour

It should be possible to see the version of ownCloud Web, the backend type and its version in ownCloud web.

### Actual behaviour

The version is not displayed anywhere

Probably an oCIS API to query the version of the backend is required.

**Comment by pascalwengerter** [comment]
Closing in favor of #5954 which already elaborates on possible approaches and is "owned" by @tbsbdr :)
