### ISSUE TITLE
modified date - user expectations

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#5671]
### Description
1. use oC Web 4.0.0
2. browse some files an have a look at the modified row and last modified field in the details

![image](https://user-images.githubusercontent.com/34452982/129336336-18f0d9a8-0ea6-40a3-91f8-7651d301ec8a.png)

### Findings
1. Sorting by `modified` is not working. It`s completely random. My expectation would be that I can sort it from oldest to youngest and vice versa.
2. I cannot find out when something was modified. It says only "5 months ago", but please give me an exact timestamp (at least in the details section, there you can show these... ehm details...)

cc @kulmann @tbsbdr

**Comment by tbsbdr** [comment]
Hey Willy,

thanks! should be covered by:

- https://github.com/owncloud/owncloud-design-system/issues/1552
- https://github.com/owncloud/web/issues/5672

We'll take care 👍

**Comment by wkloucek** [comment]
> Hey Willy,
> 
> thanks! should be covered by:
> 
> * [[Bug] "sort by modified date" shows mixed order owncloud-design-system#1552](https://github.com/owncloud/owncloud-design-system/issues/1552)
> * [Show detailed date in tooltip #5672](https://github.com/owncloud/web/issues/5672)
> 
> We'll take care

Great, didn't find them. Will close this issue
