### ISSUE TITLE
Sidebar does not open for resource in files page

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#5679]
### Steps to reproduce
1. have web setup with oc10 backend
2. browser to web base URL (for my case it is http://localhost/web/dist)
3. after a successful login user is redirected to the files page
4. create a file or a folder using the `+ New` button
5. pick the uploaded file or click the `info` icon button in the Actions column or open details from the actions menu

### Expected behavior
the sidebar should open for the picked file

### Actual behavior
the sidebar does not open for the picked file
the sidebar does not open when adding people icon button is clicked

the sidebar can only be opened if one of the files in the list table is checked, after that if we pick or from the menu try to open the sidebar some other file then the sidebar content is not changed.

### ScreenRecording
![web-sidebar-issue-2021-08-16_15 58 37](https://user-images.githubusercontent.com/39373750/129548511-d5bcfb86-7bf8-4c64-8c1e-0971f4fa060c.gif)

### Configurations
- web: latest master
- node: v14.17.1
- chrome: Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by kulmann** [comment]
@kiranparajuli589 Could you please check if running `yarn install` fixes it? I cannot reproduce this issue locally.

**Comment by kiranparajuli589** [comment]
> @kiranparajuli589 Could you please check if running `yarn install` fixes it? I cannot reproduce this issue locally.

it works perfectly after `yarn install`
thank you
