### ISSUE TITLE
No default sorting

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#5684]
[checkSort copy.zip](https://github.com/owncloud/web/files/6919460/checkSort.copy.zip)

### **No default sorting:**

1. Upload folder with files [checkSort copy.zip](https://github.com/owncloud/web/files/6919460/checkSort.copy.zip)

2. Open folder "Check Sort"

**Expected behaviour:**
by default sort by name, then follow the selected sorting

**Actual behaviour:**
No default sorting. Files are displayed in the order in which the server sent them

<img width="1434" alt="Screenshot 2021-08-17 at 13 06 54" src="https://user-images.githubusercontent.com/84779829/129715787-b347ea4f-ac49-493e-bbf0-06b200fd4646.png">

### Server configuration

branch: release-4.0.0
backend: ocis 1.9.0 with docker reachable at https://host.docker.internal:9200/
browser: chrome Version 92.0.4515.107

**Comment by pascalwengerter** [comment]
Note: Should be fixed by ODS release `v9.1.0` later this week
