### ISSUE TITLE
Sort by name/modified does not work correctly

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#5686]
[checkSort copy.zip](https://github.com/owncloud/web/files/6919460/checkSort.copy.zip)

### ** Sort by name does not work correctly:**

1. Open subfolder "Check Sort/WithText"
2. Choose the sort by name

**Expected behaviour:**
the order in which the files are displayed: copy0 -> copy1 -> copy02->copy2 ->copy101-> copy110

**Actual behaviour:**
the order in which the files are displayed: copy0 -> copy02 -> copy1 ->copy101 ->copy110-> copy2

![Screenshot 2021-08-03 at 11 58 03](https://user-images.githubusercontent.com/84779829/127997092-2f55d8dd-9d0d-4b3c-85a7-72203fa6120d.png)

### **Sort by modified does not work corectly:**

1. Open subfolder "Check Sort"
2. Choose the sort by modified

**Actual behaviour:**
![Screenshot 2021-08-03 at 12 11 56](https://user-images.githubusercontent.com/84779829/127999146-01593dbf-1ee8-4f57-a398-ed26ebbb8091.png)

### Server configuration

branch: release-4.0.0
backend: ocis 1.9.0 with docker reachable at https://host.docker.internal:9200/
browser: chrome Version 92.0.4515.107

**Comment by pascalwengerter** [comment]
Note: Should be fixed by ODS release `v9.1.0` later this week

**Comment by kulmann** [comment]
> Note: Should be fixed by ODS release `v9.1.0` later this week

Actually no. This will not be fixed by ODS `v9.1.0` because we don't do so called `natural sorting` (yet).
