### ISSUE TITLE
Incorrect sort when you use pagination

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#5687]
### **Sort when file more than 100:**

1. Open subfolder "Check Sort/CheckPagination"
2. Choose the sort by name
3. Go to page 2

**Expected behaviour:**
files on page 2: 101, 102, 103, 104

**Actual behaviour:**
files on page 2: the last 4 files from the response (random)

![Screenshot 2021-08-03 at 11 53 17](https://user-images.githubusercontent.com/84779829/127996765-c402a3b7-3903-41f6-8733-16a2401e35e1.png)
![Screenshot 2021-08-03 at 11 56 52](https://user-images.githubusercontent.com/84779829/127996844-fa693c8f-0a2b-41d4-8a99-f97f5d2ea97f.png)

### Server configuration

branch: release-4.0.0
backend: ocis 1.9.0 with docker reachable at https://host.docker.internal:9200/
browser: chrome Version 92.0.4515.107

**Comment by kulmann** [comment]
Urgh. we're sorting inside `OcTableFiles` (ownCloud Design System). Since we're handing only the paginated data to the `OcTableFiles` component we're only sorting the data of the current page. :-(

**Comment by kulmann** [comment]
We should remove the sort logic from the design system and only emit events for sorting. Sorting needs to happen within web (and later on server side).

**Comment by kulmann** [comment]
Wait with fixing until https://github.com/owncloud/web/issues/4893 is merged

**Comment by dschmidt** [comment]
> Wait with fixing until #4893 is merged

You probably meant:
https://github.com/owncloud/owncloud-design-system/pull/1817

> We should remove the sort logic from the design system and only emit events for sorting. Sorting needs to happen within web (and later on server side).

What would sorting in web look like? 
I don't see any reasonable client side solution for sorting (except for retrieving the whole folder in background ... uuuuuurgh)

**Comment by dschmidt** [comment]
Nice! Thanks a lot for bringing this over the finish line 💖

**Comment by kulmann** [comment]
Thanks for doing the heavy lifting @dschmidt 😍
