### ISSUE TITLE
Moving items in ownCloud Web not possible

### ISSUE THREAD

**Issue by frankaellen** [owncloud/web#5688]
### Steps to reproduce
1. Click on small (and/or) large file
2. Select move
3. Click on parent folder
4. Wait, nothing happens anymore

Please find a video with a screencast here: 
https://cloud.owncloud.com/index.php/f/5515993

### Expected behaviour
Should be able to move even very large files easily within the ownCloud Web frontend

### Actual behaviour
Nothing happens. Waiting, spinning wheel. Until I click cancel. 

### Server configuration

**Web server:**
https://cloud.owncloud.com

**Comment by pascalwengerter** [comment]
@frankaellen I guess this is more about lack of (visual) feedback about the move process having started/successfully finished? Moving did work fine last time I checked which was around 2 weeks ago and should be also covered by acceptance tests

**Comment by frankaellen** [comment]
Hm, it behaves differently than the other issue I opened some weeks ago. 

Screencast from 3 weeks ago:
https://cloud.owncloud.com/index.php/f/5494392

Screencast from yesterday: 
https://cloud.owncloud.com/index.php/f/5494392

Differences: 
- In the newer one I can't even navigate to the parent folder
- Spaces in the folder names (or the symbols between different hierarchy levels) are replaced by some sort of Unicode symbols

**Comment by JammingBen** [comment]
Closing as the whole move-process has been reworked (via drag&drop).
