### ISSUE TITLE
[tests-only] Investigate tests in webUIWebdavLockProtection suite

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5700]
Since the issue https://github.com/owncloud/core/issues/38912 has been fixed, some of the test scenarios in `webUIWebdavLockProtection` should pass.

Test scenarios expected to pass:
- webUIWebdavLockProtection/delete.feature:57
- webUIWebdavLockProtection/move.feature:105, 127
- webUIWebdavLockProtection/upload.feature:75

But those tests are failing currently. Need to investigate why the tests are not passing and make proper changes to the tests if needed.

Sometimes some tests pass in CI. Example
https://drone.owncloud.com/owncloud/web/18430/8/15

**Comment by SwikritiT** [comment]
@sakshamgurung is working on this issue

**Comment by saw-jan** [comment]
fixed by #5728
