### ISSUE TITLE
Details in right sidebar for pending/declined shares and trashbin

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#5701]
## User story
> As a user who received a share, I would like to see available file/folder details in the right sidebar, so that I can find out additional information than displayed in the file list.
> As a user who received a share, I would like to accept it via the `Actions` panel in the right sidebar
> As a user who deleted a file, I would like to see available file/folder details in the right sidebar, so that I can find out more information than displayed in the file list.

## Acceptance criteria
- Make sure that all panels are available that make sense
  - for `Shared with me`: Details, Actions, if resharing is possible: Sharing and Links
  - for `Trashbin`: Details, Actions

**Trashbin:**
- deleted on: (deletion date)
- Size: size

**Shared with me**
- owner
- Status: pending/acepted/declined
- Shared on: date
- Mime type: tbd

**Comment by AlexAndBear** [comment]
For deleted files and folders, this has been already implemented

**Comment by kulmann** [comment]
all we need is done
