### ISSUE TITLE
Drag & Drop for move: highlight drop target

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#5705]
## User story
> As a mouse user using the `drag & drop for move` feature I'd like to get a visual feedback about where my selected file(s) will be moved, so that I'm sure I'll drop them in the right location.

## Acceptance criteria
- visually highlight the row which represents the drop target
- make sure that the bg color of the drop target is not the selection color

**Comment by pascalwengerter** [comment]
@kulmann can we add this to the current sprint? Fixed it today in https://github.com/owncloud/owncloud-design-system/pull/1610, only needs an ODS release to work

**Comment by kulmann** [comment]
> @kulmann can we add this to the current sprint? Fixed it today in [owncloud/owncloud-design-system#1610](https://github.com/owncloud/owncloud-design-system/pull/1610), only needs an ODS release to work

Yes, of course :-) Thanks for taking care! :heart:
