### ISSUE TITLE
Provide peerDependencies to standalone apps

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#5716]
### Steps to reproduce
1. Create a standalone app (one that is not built inside this repo)
2. Declare `vuex` or `luxon` as `peerDependencies`
3. Try to load app
4. See it fail because `requirejs` does not know how to provide `vuex` or `luxon`

```
failed to load app http://localhost:8082/assets/standalone-app.js Error: Script error for "vuex", needed by: http://localhost:8082/assets/standalone-app.js
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168)
    at HTMLScriptElement.onScriptError (require.js:1738)
```

### Expected behaviour
Apps load fine without shipping their own copy of `vuex` or `luxon`.
I'm not sure if we want to *somehow* provide all modules to apps or just some whitelisted modules. 
I think it makes sense for at least `vuex` and `luxon`.

### Actual behaviour
Apps fail to load because `requirejs` does not know about these modules.

Related code:
https://github.com/owncloud/web/blob/b9a8989b51ff462c32b608a67785230f21285a5c/packages/web-runtime/src/index.js#L269-L314
https://github.com/owncloud/web/blob/b9a8989b51ff462c32b608a67785230f21285a5c/packages/web-runtime/src/index.js#L117-L124

**Comment by fschade** [comment]
this is pretty hard to do with require js, a good pick for those cases is SystemJS which supports kind of es import-maps for older browsers.

We need to find a way, @kulmann, @pascalwengerter, @paulcod3 thoughts ideas?
