### ISSUE TITLE
Some tooltips are missing

### ISSUE THREAD

**Issue by pmaier1** [owncloud/web#5723]
Just noticed in 4.1.0 that some of the actions miss tooltips:
- "Expand/collapse right sidebar" button
- "View options" button (e.g. "show hidden files")
- "Details" quick action

**Comment by pascalwengerter** [comment]
`Expand/collapse right sidebar` => removing the button based on @tbsbdr's feedback in https://talk.owncloud.com/channel/web

Thanks for the other ones, will take care of them soon
