### ISSUE TITLE
right sidebar stays empty when navigating from a details view to "All Files"

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#5742]
### Steps to reproduce
1. open the right sidebar for any item
2. click on "People" (or any other details item like Actions or Links)
3. click on "All files"

### Expected behaviour
right sidebar should show "Select a file or folder to view details."

### Actual behaviour
right sidebar is blank

**Comment by pascalwengerter** [comment]
Can't reproduce on current master, closing for now

**Comment by kulmann** [comment]
Was solved in https://github.com/owncloud/web/pull/5793
