### ISSUE TITLE
cleanup structure of unit test files

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#5744]
most tests follow the structure: fixtures and mocks at the top, helpers at the bottom, tests in between
ToDo: go through all tests that don't follow the structure and fix them

**Comment by pascalwengerter** [comment]
Also: Add a a section to the testing docs where this is being documented :)

**Comment by phil-davis** [comment]
@individual-it is this still P2? I suspect that it can easily wait a few more weeks.

**Comment by kiranparajuli589** [comment]
done with #6489 and #6490
