### ISSUE TITLE
Sidebar not appearing on file click/ calling "All actions" or "Details"

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#5757]
### Steps to reproduce
1. Click the file field
2. Click "All actions" in the context menu
3. Click "Datails" in the context menu

### Expected behaviour
Sidebar should appear

### Actual behaviour
Sidebar is not appearing
Tested with web/master https://github.com/owncloud/web/commit/05f8735a3210116f0fff0b40170846ee4cdec1d1 (latest)

![All files - ownCloud](https://user-images.githubusercontent.com/7430156/131500951-810c3a27-d3fb-4654-981c-d2e15ab3878e.gif)

**Comment by kulmann** [comment]
Hey @elizavetaRa as far as I can tell from your video you are running the most recent design system (v9.3.0), which is not in web master, yet. Probably with a local link. Is that correct?

We have an open PR for updating ODS to 9.3.0 https://github.com/owncloud/web/pull/5725

**Comment by elizavetaRa** [comment]
@kulmann Yes, I tested with the newest ods master. Thanks, now I understand the reason.

**Comment by kulmann** [comment]
Cool, good that this is the reason. :-) closing this issue here. will cc you in the PR so that you get notified when it's merged.
