### ISSUE TITLE
How to add custom icons?

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5760]
How can we add a custom icon for this mime type?

<img width="995" alt="Screenshot 2021-09-01 at 08 27 33" src="https://user-images.githubusercontent.com/5175912/131622651-dd4ebb15-ffb3-4f8d-a7d3-351dc78b5c61.png">

**Comment by pascalwengerter** [comment]
Since the `.root` file format seems pretty CERN-specific it's probably best to only add it to your ODS/web fork :) closing this issue as it is technically answered, feel free to ping us if you face any problems @elizavetaRa
