### ISSUE TITLE
Open files via public link in associated App (Collabora, OnlyOffice, Word etc.)

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#5776]
**Needed for Cern Stage 1 in Sept 2021**

## Userstory
> As a user who receives a public link I want to have the option to open the file inside a "browser app" so that I don't have the need to install a local app to open the file.

## Acceptance Criteria
- show shared file(s) in files list
- click on file executes standard action
- context menu (via rightclick or 3-dots) offers alternative open-with ... apps
- ~~download is in the quickactions permanently visible as call-to-action~~

## Context
In order to deliver the feature for cern until the end of September 2021, we need to focus on a solution that meets the minimum requirements. A more sophisticated solution (but not feasible in September) could be to open files directly in the associated app and provide "download" and "open with ..." from here. But such a solution would require a Full-screen view (see https://github.com/owncloud/web/issues/5786).

# Examples
### Example oc10:
check it out: https://cloud.owncloud.com/index.php/s/VtY8JeMjKjtxj8F
![image](https://user-images.githubusercontent.com/26610733/132029171-5dff8150-aeed-4cef-a69b-b99cde6a7faa.png)

### Example Google Drive
check it out: https://docs.google.com/document/d/1WrkFjgioofvYe2uLsVdCW6zRvBb6qPp7/edit?usp=sharing&ouid=112080943748993282565&rtpof=true&sd=true

![image](https://user-images.githubusercontent.com/26610733/132032980-1cbbdd97-bd66-4e84-a6f6-e5ed066c2e00.png)

### Example One Drive
check it out: https://1drv.ms/w/s!AmFv-ruebwpFkBX6BvqNLz3zRxAA?e=ky6BHQ

view mode:
![image](https://user-images.githubusercontent.com/26610733/132033014-36036509-7efb-4cbf-94e7-fb634fd5a525.png)

edit mode:
![image](https://user-images.githubusercontent.com/26610733/132033090-c3b2f7cd-f24c-4e0d-a8b1-50070f42120b.png)

### Example Dropbox
check it out: https://www.dropbox.com/scl/fi/bco1nmvm9i8cp0ptujo77/Document.docx?dl=0&rlkey=pjwoqlyqdmxji4skh0tzoyrkk
![image](https://user-images.githubusercontent.com/26610733/132033133-f8b1d9c7-f249-4c9e-aa3b-0bb20771d223.png)

### Example Box.com
check it out: https://app.box.com/s/w0s97nf92wjrmj78oedlda73007c3tya

![image](https://user-images.githubusercontent.com/26610733/132033257-8ddb05a0-3c05-41c4-af9d-3e6a1924f25a.png)

**Comment by tbsbdr** [comment]
@labkode could you please check the acceptance criteria ^ to meet your "stage 1" requirements?

**Comment by labkode** [comment]
@diocas @elizavetaRa

**Comment by labkode** [comment]
@tbsbdr as of today OCIS does not offer the single view as we're used in OC10. OCIS currently shows a file listing independently if it was a public link targeting a folder or a file (attached  screenshot).

(public link to a file)
![Screenshot 2021-09-08 at 17 34 46](https://user-images.githubusercontent.com/5175912/132540131-27da31a4-5d57-401b-aeb1-12268c1d534b.png)

If I understood correctly what you propose is the same behaviour as will have when under "Your files".
To me is acceptable.

@diocas @elizavetaRa please comment.

**Comment by tbsbdr** [comment]
> If I understood correctly what you propose is the same behaviour as will have when under "Your files".

Yep, correct

**Comment by wkloucek** [comment]
@tbsbdr @micbar this is not possible without backend changes, I created a ticket for oCIS here: https://github.com/owncloud/ocis/issues/2479
