### ISSUE TITLE
Sidebar "People": Unite into 1 panel

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#5797]
## Userstory
> As a user i want to see the most important sharing ui-elements in one view, so that i dont have to click around to get an overview of the sharing-section.

## Acceptance Criteria
- No "Add People" Button in main sharing panel
- instead of add people button: sharing form-panel is always directly visible
- No "Cancel" Button (other than in the screenhot)
- Only "Share" Button is visible
- "Shared with" is visible and can be expanded/collapsed

#### With collapsed list
![image](https://user-images.githubusercontent.com/26610733/132873747-07744894-4e8a-4a59-818f-1aeced553e83.png)

#### With expanded list
![image](https://user-images.githubusercontent.com/26610733/132874159-ddeb4627-eeb6-4a7b-a51f-819d145dd4da.png)

## Current status with sub-panel on click at "add people"
![2021-09-10_17-02-46 (1)](https://user-images.githubusercontent.com/26610733/132875058-81a569d3-c019-43b7-925a-fa3fe83c8e75.gif)

**Comment by diocas** [comment]
Please take into consideration https://github.com/owncloud/web/issues/5923 as well. We also consider that having to click in the avatars, to display the full list of users, one step too much. This compact view can be displayed in the details pane.

**Comment by pascalwengerter** [comment]
Whoever works on this please also check if #5608 can be closed in the same PR (by jumping into the dialogue from the quick actions)

Also, @tbsbdr could you clarify how #5923 should be handled (currently: uncollapsed by default)

**Comment by pascalwengerter** [comment]
> Whoever works on this please also check if #5608 can be closed in the same PR (by jumping into the dialogue from the quick actions)
> 
> Also, @tbsbdr could you clarify how #5923 should be handled (currently: uncollapsed by default)

Clarified that it should be open by default => please implement with this
