### ISSUE TITLE
Not found page

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#5804]
## Userstory
> As a user I want to have a meaningfull not found page if I opened a non existing URL.

> As a user I want to be able to recover from a not found page so that I can navigate to my files again.

## Acceptance Criteria
- A not found page is available
- The not found page contains a link to ownCloud Web

**Comment by wkloucek** [comment]
@tbsbdr What do you think about this? I have something similar in mind like described here: https://medium.com/designer-recipes/how-to-make-a-custom-404-error-page-for-your-website-1af37a8b20d1

**Comment by tbsbdr** [comment]
Examples how others communicate 404s:
![image](https://user-images.githubusercontent.com/26610733/133206331-dd3f9cdb-afac-449d-9a42-e79ffebec387.png)
![image](https://user-images.githubusercontent.com/26610733/133206357-a68c3cc9-2bca-4853-98dd-3359df2869c6.png)
![image](https://user-images.githubusercontent.com/26610733/133206375-8cb2dea9-fa09-4845-974a-67c383fbc439.png)
![image](https://user-images.githubusercontent.com/26610733/133206393-bd693c5d-409a-4c7e-97c4-b1d82b6eba54.png)
![image](https://user-images.githubusercontent.com/26610733/133206543-c251cf48-5349-4e17-9c70-00e71a5a1090.png)

**Comment by kulmann** [comment]
The screenshots are mixing `resource not found within files app` and `page not found`. ;-) A `resource not found within files app` already exists. See screenshot:

<img width="1516" alt="Screenshot 2021-09-14 at 10 12 34" src="https://user-images.githubusercontent.com/3532843/133221014-fe027c69-3e41-4ba9-9dc3-ebd2530234d0.png">

**Comment by tbsbdr** [comment]
@wkloucek Can you work with that or was your request more about a friendlier appearance of the 404?

**Comment by wkloucek** [comment]
> @wkloucek Can you work with that or was your request more about a friendlier appearance of the 404?

My request is about a not found site outside of the files app. Eg. when an oC 10 bookmark (eg. https://ocis.ocis-traefik.latest.owncloud.works/apps/files?dir=/&fileid=16) is opened after the migration to oCIS you would just see a "404 not found" page

![image](https://user-images.githubusercontent.com/34452982/133234905-31685cca-b715-4eb1-8020-f80fecca22e2.png)

**Comment by wkloucek** [comment]
That example could be misleading since once could argue that we are migrating links inside the files app, which is true. But that won't probably apply to other apps, eg. `https://ocis.ocis-traefik.latest.owncloud.works/apps/richdocuments/index?fileId=48`

**Comment by kulmann** [comment]
I understood from your issue, that it's about a generic 404 page for `page not found`. I was just pointing out that the screenshots are mixing two different things.

**Comment by kulmann** [comment]
As we found out today: we can't offer the `notFound` page in an anonymous context at the moment:
- user doesn't get initialized 
- apps don't get initialized

We might change that in the future, but for now we need to accept that the notFound page only works in user- and publicLink-contexts. That was now added in https://github.com/owncloud/web/pull/11737
