### ISSUE TITLE
Empty "expiration date" field when editing a public link

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#5807]
branch release 4.2.0
with ocis docker(version 1.11.0)

### Steps to reproduce
1. Create link to file or folder with "password" and "expiration date"
2. Try to change link

### Expected behaviour
the "expiration date" field is filled with the current value, otherwise how do we know its value

### Actual behaviour
the "expiration date" field is empty. The "password" field also empty

<img width="1386" alt="Screenshot 2021-09-14 at 16 41 01" src="https://user-images.githubusercontent.com/84779829/133285177-237d4837-ccc7-4967-a00f-9f44f3a56c0d.png">

**Comment by kulmann** [comment]
Fixed as part of the release: https://github.com/owncloud/web/pull/5793/commits/aa20dbbfb243ee1a5ae8fa59ec9f869a0418495d
