### ISSUE TITLE
Drag & drop for move kills drag & drop for upload

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#5808]
### Steps to reproduce
1. try to drag a file from your system into the files app - not on whitespace but on a file row

### Expected behaviour
drag area appears for accepting the upload

### Actual behaviour
the highlighting of the files table indicates that a move target is to be selected. no drag area appearing. dropping the file opens the file in a new browser tab. switching back to ownCloud Web shows a success message for 0 files being successfully moved.

Todos:
- [ ] ODS Update in Web

**Comment by paulcod3** [comment]
Should be fixed with this PR, needs ODS update.
https://github.com/owncloud/owncloud-design-system/pull/1732

**Comment by pascalwengerter** [comment]
Closed as fixed via #1732 by @paulcod3

**Comment by pascalwengerter** [comment]
> Closed as fixed via #1732 by @paulcod3

Correction: Fix is part of the ODS update in #5973 which should get merged before the next release
