### ISSUE TITLE
File Share Quota incorrectly determined for share folders

### ISSUE THREAD

**Issue by rpocklin** [owncloud/web#5817]
There is a current issue in logic checking if `quota && quota.free > 0` in `AppBar.vue`  in order to enable or disable the `New +` button.  

https://github.com/owncloud/web/blob/76036fd83dbd3a787db8321114e88d81d04cf63f/packages/web-app-files/src/components/AppBar/AppBar.vue#L264-L273

This makes an assumption the user is in his/her personal space (as it looks up the quota returned from the `$client.users.getUser(this.user.id)` which works well for personal space.

https://github.com/owncloud/web/blob/60b60d1e1da7e9da77c195e28c20e9f2de2d8465/packages/web-app-files/src/views/Personal.vue#L373-L376

This does not work well for shared folders.

If User A shares a folder 1 with user B, correct me if i'm wrong, but all files added or modified in the folder 1 would relate to User A's quota, not user B (as user A is the owner of folder 1).  Currently, if user B is set to have 0B personal quota, the buttons for `New +` get disabled, even in the shared folder screens as it assumes, since the current user B has no available personal quota, he/she cannot add or upload any more files, even within a shared folder.

### Steps to reproduce
1.  Create User A with 0B quota.
2. Create User B with a quota.
3. With User B, create a folder 1.
4. Share folder 1 with User A.
5. Log in as User A.
6. Navigate to the share 1.
7. Verify that User A cannot click the `New +` button because this user has 0B quota.

### Expected behaviour
It should either do a `fileInfo` call on the `currentFolder` or similar to ascertain the quota metrics in this share.
I am unsure how to approach a fix to this - there are 4 metrics for the quota (`free`, `relative`, `used` and `total`).
The application should then call `SET_QUOTA` with these correct values, relative to the share.

Expected user behaviour is that the user can click on the `New +` button.

### Actual behaviour
The user cannot click on the `New +` button.

**Comment by rpocklin** [comment]
Is it possible to get this looked at for comment?

**Comment by kulmann** [comment]
@rpocklin do you want to work on that yourself or should we bring in a PR?

**Comment by rpocklin** [comment]
Hi @kulmann, I'm not confident creating one as I am unsure how to get the relevant metrics of the share info.  Let me know if you are able to make a PR for this and I can certainly review / test it.

**Comment by JanAckermann** [comment]
@kulmann @rpocklin 
As far as I can see, we have some problems we need to solve first before we can tackle this:
1. The backend graph endpoint me/drives doesn't expose the quota
2. The frontend route files/spaces/shares/ needs to have the storageId as additional parameter

**Comment by kulmann** [comment]
> @kulmann @rpocklin As far as I can see, we have some problems we need to solve first before we can tackle this:
> 
> 1. The backend graph endpoint me/drives doesn't expose the quota of a shared folder
> 2. The frontend route files/spaces/shares/ needs to have the storageId as additional parameter

I think in a first iteration we should just disable the quota check inside shared folders. I.e.
a) if share jail is enabled -> any folder inside the `files/spaces/shares` route shouldn't have quota checks
b) if share jail is disabled -> any subfolder of a shared folder shouldn't have quota checks

Uploads would then just fail with a quota related response from the backend if the quota is exceeded. That's better than never being able to upload into a share.

**Comment by JanAckermann** [comment]
@kulmann Maybe we also want to think about discarding the check and disabling the button entirely.  
I think it is an edge case, that the remaining quota space is EXACTLY **0**, we also have an quota check while uploading files via uppy.

**Comment by kulmann** [comment]
> @kulmann Maybe we also want to think about discarding the check and disabling the button entirely.
> I think it is an edge case, that the remaining quota space is EXACTLY **0**, we also have an quota check while uploading files via uppy.

Sounds good, let's do that.

**Comment by JanAckermann** [comment]
According to my comment:
>The backend graph endpoint me/drives doesn't expose the quota of a shared folder 

I don't think this will be possible, we would likely expose sensitive user information
