### ISSUE TITLE
versions tests sometimes fail with too little versions listed

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#5853]
`webUIFilesActionMenu/versions.feature:36` sometimes fails in the step `And the versions list should contain 2 entries` because only one version could be found
![grafik](https://user-images.githubusercontent.com/2425577/135325050-4401921b-89d3-4f6f-8a0c-6eac806a490c.png)
e.g. https://drone.owncloud.com/owncloud/web/19297/12/14

**Comment by jasson99** [comment]
This has been more frequent now. This should be fixed soon

**Comment by individual-it** [comment]
those tests have been deleted in #5973 but I think that was a mistake @SwikritiT please bring the tests back that were deleted in #5973 but are still valid
In the same PR you can try to fix the timing issue similar to #5883
We need to understand if that is an issue in the backend or in our testing code
If its a backend issue the tests can stay skipped but we need a core and/or ocis issue to track the problem

**Comment by kulmann** [comment]
Do you have any findings, yet, if this is a backend issue or a CI timing issue? Since it's flaky I'd be fine skipping it with reference to this issue.

@fschade is already taking care of skipping it... would be nice to get an actual fix though.

**Comment by individual-it** [comment]
@kulmann I thing the function that was waiting between uploads (because oc 10 only stores one version per sec) had an issue, this PR https://github.com/owncloud/web/pull/6047 should fix it

**Comment by phil-davis** [comment]
PR #6047 fixed this, except for unusual timing situations if uploading a large file followed by overwriting with small content.

I raised issue #6081 to improve the solution.
