### ISSUE TITLE
Sort order in trash is broken

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/web#5855]
Experienced with 4.2.0 and oc 10.8
![image](https://user-images.githubusercontent.com/200626/135412771-4f421bab-3837-496a-915e-e8dc07ab8c73.png)

**Comment by kulmann** [comment]
This has been solved when we introduced callbacks for sorting-values (i.e. calculate a value for comparators in contrast to the one that is rendered). @TheOneRing could you re-check with a recent version? The 4.7.0 that is included in ownCloud 10.9 does the job right.

**Comment by dschmidt** [comment]
Pagination and sorting have been refactored and it seems to work just as expected now.
