### ISSUE TITLE
No capabilities in public context with password

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#5863]
### Steps to reproduce
1. Receive a public link share with password
2. Don't see any behavior that is communicated via capabilities from the backend

### Expected behaviour
Not necessarily all capabilities, but at least the most interesting ones should be available for the `web` frontend in an unauthenticated password protected context

### Actual behaviour
No capabilities are available in an unauthenticated password protected context since they only get loaded when initializing a user session (https://github.com/owncloud/web/blob/808be1ac3bed026d7ca1d2f0820f989d97665e4a/packages/web-runtime/src/store/user.js#L99)

### Qualification
- [x] Check if fetching capabilities is authenticated in OC10
- [x] Check if fetching capabilities is authenticated in oCIS

**Comment by kulmann** [comment]
Capabilities for public links are not available as of now. Ideally we would use the public auth middleware for oCIS for making capabilities available on public links. For oc10 the solution is not clear, but less pressing since the two linked tickets are oCIS-only features so far.

**Comment by fschade** [comment]
currently this is fixed for public links without password but not for public links with passwords, we use this as tracking issue for this behavior

**Comment by diocas** [comment]
can we have an ETA for this?
