### ISSUE TITLE
Media viewer watermarks

### ISSUE THREAD

**Issue by rpocklin** [owncloud/web#5869]
It would be very beneficial to have the media viewer support watermarks to protect images and the like from being downloaded or printed (ie. would be useful when a user does not have the download permission).

A brief search yields these libraries:

* https://github.com/brianium/watermarkjs
* https://github.com/CoderMonkie/js-watermarker

Let me know if this would be considered as a PR if not a priority within Owncloud.

**Comment by AlexAndBear** [comment]
Currently we are implementing secure view for high sensitivity data:

https://github.com/owncloud/ocis/issues/9068
