### ISSUE TITLE
Redirect to homeFolder only

### ISSUE THREAD

**Issue by diocas** [owncloud/web#5875]
When I open ocis web (I go to `/`), I get redirected first to `/#/files/list/all` and only then I'm redirected to `homeFolder` (in our case, `/#/files/list/all/eos/user/<letter>/<username>`). I should only be redirected to the latter.

We suspect that with our latest update, getting `/` might have become slightly slower. And this became quite noticeable due to #5085, which is causing the view of my home dir to be replaced by the view of the root dir.

**Comment by fschade** [comment]
@elizavetaRa is it possible that you have a look at the console which url is requested and what the response is?
