### ISSUE TITLE
Files are displayed bigger than they are (or: one KB has 1024 Bytes and not 1000)

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#5879]
### Steps to reproduce
1. create a file with 8GB (`fallocate -l 8G 8G.bin`)
2. upload it to ownCloud
3. show file listing

### Expected behaviour
The file with the name `8G.bin` has a size of 8.0GB.

### Actual behaviour
The file with the name `8G.bin` has a size of 8.6GB.

![image](https://user-images.githubusercontent.com/34452982/136207879-0d86c093-2651-47ba-8878-1642b4234b91.png)

Turns out that the Webdav endpoint give the correct amount of bytes:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:s="http://sabredav.org/ns">
   <d:response>
      <d:href>/remote.php/webdav/8G.bin</d:href>
      <d:propstat>
         <d:prop>
            <oc:permissions>RDNVW</oc:permissions>
            <oc:favorite>0</oc:favorite>
            <oc:fileid>MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OmZhNzllNWZiLTM4ZWEtNGE4YS1iODgwLTFlOWM2YjY1ZDBjOA==</oc:fileid>
            <oc:owner-id>einstein</oc:owner-id>
            <oc:owner-display-name>Albert Einstein</oc:owner-display-name>
            <d:getcontentlength>8589934592</d:getcontentlength>
            <oc:size>8589934592</oc:size>
            <d:getlastmodified>Wed, 06 Oct 2021 12:43:57 GMT</d:getlastmodified>
            <d:getetag>"f7337389e4807b661e29a4a445f9b78e"</d:getetag>
            <d:getcontenttype>application/octet-stream</d:getcontenttype>
            <d:resourcetype />
         </d:prop>
         <d:status>HTTP/1.1 200 OK</d:status>
      </d:propstat>
      <d:propstat>
         <d:prop>
            <oc:share-types />
            <oc:privatelink />
            <oc:downloadURL />
         </d:prop>
         <d:status>HTTP/1.1 404 Not Found</d:status>
      </d:propstat>
   </d:response>
</d:multistatus>
``` 

8589934592 Bytes / 1024 / 1024 / 1024 = 8GB

ownCloud Web seems to calculate GigaByte like this:
8589934592 Bytes / 1000 / 1000 / 1000 = 8.6 GB, which is actually wrong

### Server configuration
oCIS 1.12.0
oC Web 4.2.0

**Comment by kulmann** [comment]
That was actually a conscious decision by product management. The lib that ownCloud Web is using for calculating human readable file sizes recently had a major version upgrade which switched from base 2 to base 10 calculation for file sizes, see [their changelog](https://github.com/avoidwork/filesize.js/blob/master/CHANGELOG.md).

**Comment by wkloucek** [comment]
I didn't find that, that's quite all information you need. So basically what Linux shows me and what I expected to have in Web are Gibibytes :laughing:

**Comment by butonic** [comment]
Um but ... isn't this platform dependant then? Shouldn't we reflect the same numbers as shown by the native tools? So win GiB and MacOS GB?
