### ISSUE TITLE
uploading many files freeze the browser

### ISSUE THREAD

**Issue by fschade** [owncloud/web#5882]
### Steps to reproduce
1. upload 2k files to a folder

### Expected behaviour
ui keeps responsive

### Actual behaviour
ui gets unusable

### Server configuration
oc10, ocis

**Comment by pascalwengerter** [comment]
@fschade could you check if introducing Uppy via #6202 resolved the issue for you?

**Comment by kulmann** [comment]
Unfortunately this is still an issue. While the situation has improved a lot, the uploads still seem to bring the UI into a blocked state. IMO the uploads need to be pushed into a web worker / separate thread.
