### ISSUE TITLE
Pass view mode to /app/open

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#5903]

**Comment by pascalwengerter** [comment]
> > Could someone share some insights on what the expected format/possible parameters on the backend are / what we should pass there? @ishank011 @wkloucek
> 
> I'm sorry, but I still need to point you to a draft PR https://github.com/owncloud/ocis/pull/2580/files . I just wrote a section about query parameters of the `/app/open` endpoint

Enough to at least get started, thanks!

**Comment by pascalwengerter** [comment]
@fschade we talked about this one, I'll assign you

**Comment by tbsbdr** [comment]
Hey @ishank011 I guess the usecase is the following:
_As a user who just wants to sneak peek into files I want to be sure that I don't accidentally modify them._
Is this correct?

**Comment by ishank011** [comment]
Hi @tbsbdr, apologies for the late response.

Yes, that would be the use case. For users having a conjunction of permissions on a file, they should be able to open it in any specific view mode. The `/app/open` endpoint accepts a `view_mode=(view|read|write)` query parameter for this

**Comment by JammingBen** [comment]
This has been implemented via https://github.com/owncloud/web/pull/9879, hence closing here.
