### ISSUE TITLE
User/group filters type does not work

### ISSUE THREAD

**Issue by gmgigi96** [owncloud/web#5913]
In reva the user and group provider implement some filters which allow a user to filter by the user/group type (primary, secondary, lightweight account), when creating a share of a folder.
These filters are specified prepending a letter to the actual query name, i.e. `<letter>:<user/group>`, and can be `a` to get all the primary, service and secondary accounts, `l` to get only the lightweight accounts, and no filter for only primary accounts.

In web side only the last works because the list got from reva is re-filtered according to the user query, and the filters are indeed broken.

**Comment by pascalwengerter** [comment]
What's the definition of done for this ticket? For me it's not clear whether this is a CERN/Reva specific topic which we should solve in a generic way in web and what you're actually looking for (e.g. "a dropdown to filter for account types when looking for people to share with")
