### ISSUE TITLE
Testing against current oC10 core master

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#5915]
In issue #5908 PR #5909 we now run regular CI against the oC10 "latest" server version. Currently that is ownCloud 10.8.0
That confirms that web browser code works successfully against a current release of oC10 server - good.

We also want to know, at some interval, that the web browser code works against the later code in core master that will become the next ownCloud 10.x release.

For discussion:

How often do we want to run web acceptance test CI against the code in core master?

IMO these are the options:
1) Nightly in drone CI
2) Weekly in drone CI
3) When we think there have been significant changes in core master, the next day run CI against the daily-master-qa tarball by doing it in a test PR
4) Only run it against core release tarballs (e.g. 10.9.0-RC1 tarball...) during the release phase

Or... ?

**Comment by pascalwengerter** [comment]
Closing as answered, we'll know if we have to refine the process after OC10.9 has been released in a bunch of weeks
