### ISSUE TITLE
Show sharing compact view in Details

### ISSUE THREAD

**Issue by diocas** [owncloud/web#5923]
This is a detail, but I leave the ticket here to start a discussion.

To me it doesn't make much sense that when I click "People" (in the sidebar) to see who I shared a file/folder with, I see first a compact view which I need to click to view the full details. This is an extra step that doesn't bring much to my experience.

I would suggest having this compact view in the Details pane, leaving the People's pane solely with the full details view.

![image](https://user-images.githubusercontent.com/2589871/137697586-355694c9-4059-4080-9ad1-d5e8dda86999.png)

Ofc that you might already have other plans for these views and therefore my suggestion might not apply.

**Comment by pascalwengerter** [comment]
@tbsbdr please take a look :)

**Comment by pascalwengerter** [comment]
Clarified that it should be open by default
