### ISSUE TITLE
File sorting is not persistent

### ISSUE THREAD

**Issue by diocas** [owncloud/web#5930]
When navigating within my files (same /files/list/all view), the sorting options are not preserved. Meaning that if I order by date, for example, once I enter a different folder I get back to sorting by name. 
In OC10 this choice is preserved, so we consider it a regression.

**Comment by micbar** [comment]
@kulmann any ETA on that?

**Comment by kulmann** [comment]
Currently working on it. Will be available in master early next week. Probably not part of the release, but that's not relevant for CERN, having it in master is sufficient.
