### ISSUE TITLE
OCIS Web in Safari 13.1.2 shows blank screen

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5949]
Opening new interface in Safari 13.1.2 shows a blank screen. Tried empty caches but did not help. I'm using macOS High Sierra 10.13.6

Attached console message.

![image](https://user-images.githubusercontent.com/5175912/139067577-8767877c-1295-4879-851a-a29136ad7657.png)
![image](https://user-images.githubusercontent.com/5175912/139067590-2873dfdc-0cb6-45f3-ac46-53b885e9e106.png)

**Comment by pascalwengerter** [comment]
Closed as clarified & not applicable since it's an unsupported browser
