### ISSUE TITLE
show web ui version number to users

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#5954]
# Description

## User Stories

* > As a owncloud product owner/manager I want to know the version of oc Web that im currently looking at in a deployment so that i can qualify meaningful bugreports.

## Value
- save developers time

## Acceptance Criteria
- show web ui + backend version number in html meta tag <generator>
- show web ui + backend version number in console

**examples:**
- `<meta name="generator" content="ownCloud Web UI 4.5.0, ocis 10.0.11 reva">`
- `<meta name="generator" content="ownCloud Web UI 4.5.0, ownCloud 10.8.0 community">`
- print version number in console "ownCloud Web UI 4.5.0"
- print version number in console "ocis 10.0.11 reva"

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

**Comment by dragotin** [comment]
@hodyroff FYI
