### ISSUE TITLE
Performance: blank page because of timeout

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5957]
Tested on ocis.owncloud.com with network throttling as depicted in the video:

https://user-images.githubusercontent.com/5175912/139440424-e9fdd109-854e-4def-8349-fc5974dde822.mov

To alleviate renders after initial page load we have the following directives in NGINX:
```
    location ^~ /
    {
      root /var/www/web;
      autoindex on;
      add_header Cache-Control "no-cache";
      etag on;
      gzip on;
    }
```

This is only and intermediate solution regarding caching.
Ideally only `index.html` should be exposed to this caching technique, the rest of the assets (JS, CSS, IMG, ...) would be handled with:

```
    location ^~ *js$
    {
      add_header Cache-Control "pubic,max-age= 31536000,immutable";
      gzip on;
    }
```

However, the last one can be applied only if the generated JS files have a suffix that changes on build or on checksum.

The previous configuration are just workarounds and do not help for the first render where people is blocked.
For that, a mechanism to optimise the loading or reduce the size of the payload is needed.

**Comment by diocas** [comment]
The final configs are a bit different, but the idea the same.
Issue address in #5986 and #5985

**Comment by pascalwengerter** [comment]
@diocas could you clarify if having sorted out the CERN extension JS bundles has resolved this issue for your users? (We'll slim down web by a bit and improve rendering performance nonetheless, just curious if we can close this specific issue)

**Comment by tbsbdr** [comment]
discussion notes with benedikt
- timeout increased
- removed ui kit
- added loading indicator to reassure the user of the systemstatus

**Comment by kulmann** [comment]
With https://github.com/owncloud/web/pull/6320 being merged, can we close this issue?

**Comment by pascalwengerter** [comment]
> discussion notes with benedikt
> 
>     * timeout increased
> 
>     * removed ui kit
> 
>     * added loading indicator to reassure the user of the systemstatus

Side note: We've now removed UiKit (and more, smaller and not necessary dependencies) and will also bring a 30% bundle size reduction with the SDK bump sometime soon. Not sure how noticeable the difference is for the end user

**Comment by kulmann** [comment]
> discussion notes with benedikt
> 
> * timeout increased
> * removed ui kit
> * added loading indicator to reassure the user of the systemstatus

And another side note: configurable timeout and loading indicator during initial load / error page on timeout was done by @diocas - thank you for the upstream contribution! 🥇

**Comment by pascalwengerter** [comment]
@labkode can this be considered "done" and closed?
