### ISSUE TITLE
Wrong iframe size for external apps

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#5960]
## Bug
In the external apps view, there is always a scrollbar on the right and you don't see the full iframe. Looks like the iframe is too high.

https://user-images.githubusercontent.com/34452982/135443123-890091d8-de83-4ce0-b939-832f049ca891.mp4

_Originally posted by @wkloucek in https://github.com/owncloud/web/issues/5805#issuecomment-931216680_

**Comment by wkloucek** [comment]
The top bar is now gone and the iframe takes 100% percent high. Therefore the scrollbar is gone

![image](https://user-images.githubusercontent.com/34452982/142861684-78c34696-c92d-4e6f-be2c-fd7a8d7eabc5.png)


Tested with oCIS 1.15.0-rc1 with Web 4.5.0

**Comment by wkloucek** [comment]
@pascalwengerter @kulmann was removing the top bar intended?

**Comment by kulmann** [comment]
Afaik not intended, no.

**Comment by pascalwengerter** [comment]
I just double-checked and we introduced this when making the app-provider available on public links from my understanding - usually you'd set `hideHeadbar` to false in the routes, but adding it below clashes between hideHeadbar and auth [here](https://github.com/owncloud/web/blob/c15f365b0ddaa64628203043a45dc14b1e2522c4/packages/web-app-external/src/index.js#L24)


```
      hideHeadbar: false,
      auth: false
```
