### ISSUE TITLE
use default app for external apps when not specifying one

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#5962]
## Bug description

https://github.com/owncloud/web/blob/bdd7075dc65fb7bad0f9d1b40fbf6889494069ea/packages/web-app-files/src/mixins/fileActions.js#L142-L150

If a user clicks on a file, which can be opened by multiple external apps, it will be opened with the first one in the internal array. This is quite random to a user and false in the sense, that oCIS knows about default apps (configurable by an admin atm).

Opening a file with the default app is done by calling `/app/open` without a `app_name` query parameter.
Additionally we also could add this information on the `/app/list` endpoint, which application is the default, if this is helpful to you.

_Originally posted by @wkloucek in https://github.com/owncloud/web/pull/5805#r718774885_

**Comment by kulmann** [comment]
Good one. And an easy fix: if at least one app for a mimetype: call `/app/open`, if no app available for the mimetype: don't use the app provider. :trollface: 

If think we don't need the default info in the `/app/list` endpoint, but sorting or an `app weight/prio` would be helpful. I think there was another ticket about that, right?
