### ISSUE TITLE
[Receive Public Link] Don't show "+ New" Button

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#5971]
- Don't show the "+ New" Button in the Public Link view, if you can't create new files there. (Also, if the button is disabled, it's still confusing)
- Please remove the New Button but keep the height of the remaining whitespace, so that we don't get a jumpy layout when selecting files (-> batch actions get visible) 

![image](https://user-images.githubusercontent.com/26610733/139870423-4b108d8e-1fb0-4421-982d-104c35e68443.png)

**Comment by kulmann** [comment]
Closing in favour of the more detailed https://github.com/owncloud/web/issues/5618
