### ISSUE TITLE
Rewrite ShowCollaborators (sharees list) acceptance tests

### ISSUE THREAD

**Issue by paulcod3** [owncloud/web#5975]
We've created a pull request in web where the sharees-list (or ShowCollaborators) gets completly reworked. So it would be really cool if you could rewrite the acceptance tests.

This is the PR: https://github.com/owncloud/web/pull/5789

**Comment by phil-davis** [comment]
I suggest that whoever takes this, branch off from the PR branch and get the tests passing in a separate branch/PR. Then we can sort out merging it all together...

**Comment by sakshamgurung** [comment]
This PR https://github.com/owncloud/web/pull/6013 was handed over to owncloud team due to their time constraints. So, I unassigned myself from this issue.

**Comment by pascalwengerter** [comment]
Actually closing this, I'm taking care of this in #6039. Thanks @sakshamgurung for bringing this up!
