### ISSUE TITLE
Move share indicators into their own column

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#5976]
## User story
> As a user I want to see at a glance if a file or folder can be accessed by anyone other than myself, so that I can deal with confidential files in a confident way.
> As a user I want to modify shares and get more detailed sharing information with one click from the file list, so that I can deal with shares in an efficient way.

## Acceptance criteria
- load share indicators for all file listing views in an authenticated context (`All files`, `Favorites`, `Shared with others`, `Shared via link`, if possible also for `Trashbin`)
- add share indicators into a dedicated column (directly after resource name) with title `Shared`
- accessible names for share indicators `Shared via link` for share type link, `Shared with people` for all other share types
- make share indicators prettier (@tbsbdr for scribbles)
- also make sure that the same share indicator look and feel is used in the details panel
- remove share indicators from below the resource name
- remove avatars list as dedicated column in the `Shared with others` and "shared via link" views. "shared with me" stays untouched. That costs us too much performance, especially rendering performance and the UX is confusing (they are not clickable, it is not useful to make them clickable because the click behaviour is not clear and cannot be directed into the dedicated panels, users expect to be able to click)
- click on a share indicator opens the respective right sidebar panel (people or links)

**Comment by tbsbdr** [comment]
<img width="1920" alt="Web UI Share Indicator 11-2021" src="https://user-images.githubusercontent.com/26610733/140295948-dafe8892-66ae-4968-81e9-bd2263180dbe.png">

Same asset in Figma: https://figma.fun/cyjJma

...or just grab:
**Link-shareindicator**

```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M7.35832 16.3738C6.45071 15.4662 6.45431 13.9871 7.36636 13.075L9.4998 10.9415L8.49132 9.93306L6.35785 12.0665C4.88578 13.5386 4.87999 15.9223 6.34493 17.3872C7.80986 18.8522 10.1935 18.8464 11.6656 17.3743L13.7991 15.2408L12.7906 14.2323L10.6572 16.3658C9.74512 17.2779 8.26596 17.2815 7.35832 16.3738ZM10.0759 14.7178L14.3428 10.4509L13.2813 9.38935L9.01435 13.6563L10.0759 14.7178ZM11.6915 6.73288L9.55806 8.86632L10.5665 9.8748L12.7 7.74136C13.612 6.82927 15.0912 6.82567 15.9988 7.73331C16.9064 8.64095 16.9029 10.1201 15.9908 11.0321L13.8573 13.1656L14.8658 14.1741L16.9993 12.0406C18.4714 10.5685 18.4772 8.18486 17.0122 6.71992C15.5473 5.25498 13.1636 5.26078 11.6915 6.73288Z" fill="#515F78"/>
<circle cx="12" cy="12" r="11.5" stroke="#515F78"/>
</svg>
```

**People-shareindicator**

```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M15 11.25C16.245 11.25 17.2425 10.245 17.2425 9C17.2425 7.755 16.245 6.75 15 6.75C13.755 6.75 12.75 7.755 12.75 9C12.75 10.245 13.755 11.25 15 11.25ZM9 11.25C10.245 11.25 11.2425 10.245 11.2425 9C11.2425 7.755 10.245 6.75 9 6.75C7.755 6.75 6.75 7.755 6.75 9C6.75 10.245 7.755 11.25 9 11.25ZM9 12.75C7.2525 12.75 3.75 13.6275 3.75 15.375V17.25H14.25V15.375C14.25 13.6275 10.7475 12.75 9 12.75ZM15 12.75C14.7825 12.75 14.535 12.765 14.2725 12.7875C15.1425 13.4175 15.75 14.265 15.75 15.375V17.25H20.25V15.375C20.25 13.6275 16.7475 12.75 15 12.75Z" fill="#515F78"/>
<circle cx="12" cy="12" r="11.5" stroke="#515F78"/>
</svg>
```

**Comment by pascalwengerter** [comment]
There's some more things to be done for this (forget about the rest of the acceptance criteria above for now):
- Share indicators in right sidebar should have the same styling as OcStatusIndicator (check if  OcStatusIndicator can be used in FileDetails.vue)
- Make AvatarsList in ResourceTable clickable 
    - SharedWithOthers: Should open people shares in right sidebar
    - SharedViaLinks: Should open link shares in right sidebar
- Remove link shares from SharedWithOthers table (needs an updated shares filter)

**Comment by pascalwengerter** [comment]
> 



> * Make AvatarsList in ResourceTable clickable
>   
>   * SharedWithOthers: Should open people shares in right sidebar
>   * SharedViaLinks: Should open link shares in right sidebar
> 
> * Remove link shares from SharedWithOthers table (needs an updated shares filter)

@lookacat these items still are _to be done_, just checked on current master?
