### ISSUE TITLE
Only select files filtered by search

### ISSUE THREAD

**Issue by jumbi77** [owncloud/web#5984]
Hello,

We are using owncloud and we sometimes need to restore or final-delete a lot of files from trashbin and currently there is (a) no multi-select function (select first, press SHIFT, select last to select all in between) available or (b) using "select all" with filter available. For (b) check this [https://github.com/nextcloud/server/issues/2781](https://github.com/nextcloud/server/issues/2781) or [https://github.com/nextcloud/server/issues/2075](https://github.com/nextcloud/server/issues/2075) .

Both features would be really handy. Note: As far as i know option (a) is already possible with "normal files" but not in trashbin/deleted files in the web app. Option (b) isnt available either in "normal" file or "deleted" file view (filtering works but "select all" always select really all files and not only the filtered onces if filter is used)

Much thanks

**Comment by tbsbdr** [comment]
Hi @jumbi77 jep, good idea!

We already discussed this idea as we generally want to align the Web UI to common fileexplorer ux-pattern that users know eg. from windows Explorer or mac Finder. The behaviour you described is one of those well-known pattern.  I think we will take care of this issue in 2022 at the earliest, but would also appreciate contributions from the community to speed things up :-)

**Thanks for bringing this up!**

**Comment by tbsbdr** [comment]
ah, just to be sure: I was referring to the new "Web UI" to which this repo belongs (not the "classic UI" which you can find here: https://github.com/owncloud/core/ )

**Comment by jumbi77** [comment]
Thanks for the reply, nice to hear that the File Browser UI improvements are on the List for 2022. I indeed initially meant the "classic" repo but the fix in either the classic or new repo would be fine :)
