### ISSUE TITLE
Context menu is hidden by the menu bar for selected items

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#5994]
Can't scroll to the options at the top as they're hidden by the menu bar

<img width="1134" alt="Screenshot 2021-11-08 at 12 26 55" src="https://user-images.githubusercontent.com/10387289/140734234-2514fe96-dad8-4861-9cf1-7dd23c8a68bc.png">

**Comment by pascalwengerter** [comment]
Resolved by @fschade in https://github.com/owncloud/owncloud-design-system/pull/1691
