### ISSUE TITLE
Should sorting by name be case insensitive?

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#5995]
<img width="419" alt="Screenshot 2021-11-08 at 10 40 52" src="https://user-images.githubusercontent.com/10387289/140734413-4c6eadfc-698f-4841-a31f-7f6971c780d3.png">

**Comment by pascalwengerter** [comment]
Fixed in the ODS already (https://github.com/owncloud/owncloud-design-system/pull/1735), will come to web this release ;)
