### ISSUE TITLE
No right click menu nor action on non app-providder items

### ISSUE THREAD

**Issue by diocas** [owncloud/web#6002]
After the latest update, if I right click or click on a file whose extension doesn't have an app provider app associated, nothing happens. In the console it complains on `packages/web-app-files/src/mixins/fileActions.js:179` that `app_providers` is undefined. 

### Steps to reproduce
1. Pull the latest master
2. Right click on a file

**Comment by dschmidt** [comment]
Cannot reproduce. Is this still an issue?
What's the filename you are using?
![Screenshot_20211211_114445](https://user-images.githubusercontent.com/448487/145673729-64532287-6c19-4c6b-a3a9-63340bc01ec1.png)

**Comment by diocas** [comment]
Just built from latest master and I still see the issue. Do you have the app provider enabled and configured with apps? It needs to return something other than an empty list, otherwise it works.

You can see my fix to understand the issue: if the app provider list is completely empty, the function that returns the handlers returns empty early. If it's not empty, then it filters it to get the apps that handle that particular mimetype, which will fail later if the filtered list is empty.

**Comment by pascalwengerter** [comment]
> Cannot reproduce. Is this still an issue? What's the filename you are using? ![Screenshot_20211211_114445](https://user-images.githubusercontent.com/448487/145673729-64532287-6c19-4c6b-a3a9-63340bc01ec1.png)

@dschmidt did you use app-provider related services a la https://owncloud.dev/ocis/deployment/ocis_wopi/? Perhaps the problem is not visible if you don't start WOPI+Collabora/OnlyOffice/Codimd/*
