### ISSUE TITLE
Replace/remove obsolete Vue dependencies

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6019]
### List
- [X] `vue2-touch-events` since mobile/touch gestures are not a focus anymore in https://github.com/owncloud/web/pull/6086
- [ ] `vue-scrollto` can be replaced by https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView with a bit of love ™️ 
- [x] `vue2-dropzone` as mentioned in #1953
- [ ] ...

### Expected behaviour
Only necessary dependencies are fetched, used in the codebase and shipped to our users
Also, this will make the Vue3 upgrade easier since not every library has a compatible version yet

### Actual behaviour
Technical debt

**Comment by pascalwengerter** [comment]
@dschmidt could I ask you to take over here/double check/update/close? 🥇

**Comment by pascalwengerter** [comment]
Or close it in favor of the `update to Vue3`/merge my content there

**Comment by dschmidt** [comment]
When I did a bit of research for https://github.com/owncloud/web/issues/7948 I could not find usage of vue-scrollto.

I would recommend we keep tracking this in that issue.
