### ISSUE TITLE
Accessible breadcrumb current folder info broken

### ISSUE THREAD

**Issue by fschade** [owncloud/web#6022]
### Steps to reproduce
1. login
2. create some folders and resources
3. inspect `<p class="... oc-breadcrumb-sr"> ...`

### Expected behaviour
if folder is empty and you add some content it should update (reactivity), then it should render the info with the `itemCount` instead of the raw output.

### Actual behaviour
no reactivity and no placeholder replacement

### Screenshot
![Bildschirmfoto 2021-11-14 um 15 25 44](https://user-images.githubusercontent.com/49308105/141685309-7462810c-20e9-4cdb-9912-abbc078597e1.png)

**Comment by pascalwengerter** [comment]
Seems like it needs a `$gettextInterpolate` from my first understanding
