### ISSUE TITLE
Authentication pop-up when you open public link

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6033]
### Environment
via docker
version web: 4.5.0 
version ocis: 1.14.0

### Steps to reproduce
1. Admin creates public link for file or folder 
2. Try to open public link

### Expected behaviour
the link opens regardless of whether the user is logged or not

### Actual behaviour
when you try to open link you get authentication pop-up
![image](https://user-images.githubusercontent.com/84779829/142006724-4bf27fd1-61a3-4db3-8662-311d5a050657.png)
- if you click "cancel"  you get  401 Unauthorized `GET https://host.docker.internal:9200/ocs/v1.php/cloud/capabilities?format=json` but public link opens: 207  Multi-Status `PROPFIND https://host.docker.internal:9200/remote.php/dav/public-files/BPTtubUKASnVtwc`
- if you reload page you get again authentication pop-up

**Comment by dschmidt** [comment]
Can you still reproduce this?

**Comment by ScharfViktor** [comment]
Re-tested:
web v. 4.9.0
ocis v. 1.16.0

bug doesn't reproduce. 

@dschmidt thank you for pointing that out
