### ISSUE TITLE
Cleanup implicit dependencies

### ISSUE THREAD

**Issue by fschade** [owncloud/web#6048]
In web we use implicit code in several places, the most prominent example are vue mixins.
This introduces some problems regarding code quality, analyzability and also introduces cognitive complexity.

Please read [for a deeper dive](https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html).

In Vue 2 it was common practice to use those and accept the downsides,
with the release of vue 3 and it's composition api the coin has flipped and there are now better options.

This is a bucket issue to group touching PR's.

# Benefits
* Preparation for Vue 3 upgrade
* Increase developer ergonomics 
* Isolated testing (reduce susceptibility to errors)

# Rules
* New Code must be tested (unit)
* Old tests must stay intact (if the test makes sense)
* No Performance regressions
* No implicit code path (must be analyzable)
* All dead code down the road gets removed (getters, mutations, ....)
* A bit duplication here and there is ok while this PR is open, the last PR should cover this and abstract sharable code away

# Bucket
* [X] ~~#6049~~
* [X] ~~#6065~~

**Comment by dschmidt** [comment]
We all agree that we want to get rid of mixins and we heavily use composables now. 
The two linked PRs are merged. 

Can we close this ticket now? 
If not what are acceptance criteria? Last mixin gone?
