### ISSUE TITLE
Add screenshots/browser log for the smoke test in CI when the test fails

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6052]
To understand why the test fails in the SI, you need more information, like a screenshot, a browser log

- [x] screenshots are disabled by default. make it possible to control this, for example to enable them via the header
- [ ] ~abort the test if we have console error/warning~ @pascalwengerter: extracting this to a separate ticket, debatable ticket

**Comment by fschade** [comment]
Some ideas: Video, traces, screenshots, browser console output & images. 

Those only should created on first retry to keep the load low.

Let’s discuss the options tomorrow. Thanks 4 taking care ❤️

**Comment by pascalwengerter** [comment]
@ScharfViktor can this considered "done" by your changes in Playwright? :)

**Comment by ScharfViktor** [comment]
everything is done except - abborting tests if we have console error/warning

**Comment by pascalwengerter** [comment]
> everything is done except - abborting tests if we have console error/warning

I will extract the "abort on log warnings/errors" into a separate ticket and close this one here. Huge progress, thanks for the awesome work @ScharfViktor!
