### ISSUE TITLE
[Sharing Permissions] Inform user, why some "Custom Permissions" can turn into "Roles"

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6068]
### Steps to reproduce
1. Login to ownCloud Web UI
2. Share a folder, eg. with Albert
3. Set the permissions to "Custom Permission", check "read" + "share", then apply + save.
4. Dropdown shows "Custom Permission"
5. reload
6. Dropdown shows "Viewer"

### Whats the Problem?
The Page reload appears to change the permissions (step 4 to step 5), because the dropdown changes on-reload from "Custom permissions" to "Viewer". Benedikt and I expect this to confuse some users as the dropdown appears to lead a life of its own. Its logically correct, but could feel unstable. 

### Technical Background
The reasoning for this behaviour is, that we bundle "a set of permissions" as "roles" **in the frontend** to keep the ui simple. But: As of now **we dont store roles in the backend**, but only the single permissions.
- Permission "read" + "share" --> Role: "Viewer"
- Permission "read" + "share" --> "Custom Permission"

--> If e.g the permissions "read" + "share" where applied, its as of now impossible to say if we only look at the backend infos if this was done via "Custom permissions" or via Role "Viewer".

### Remedy
Provide a tooltip, that explains: If custom permissions match to a role, the role gets displayed (not "Custom Permissions"). This is intended behaviour as long as we dont store Roles in the backend.

**Comment by JammingBen** [comment]
Closing since we removed custom permissions.
