### ISSUE TITLE
CI chat notification comes before build is finished

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6075]
I noticed this:
![web-ci](https://user-images.githubusercontent.com/1535615/144203471-37ee9011-f1ff-4aea-8328-45e65117adf2.png)

The chat notification comes to rocket chat while the "build" pipeline is still running. So if the "build" pipeline fails, we will still have a green notification in the chat.

**Comment by pascalwengerter** [comment]
@phil-davis could you add this to your backlog? Should be trivial to fix
