### ISSUE TITLE
Improve pause between uploads in acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6081]
PR #6047 (issue #5853 ) improved the handling of the "at least 1 second" delay between uploading versions of a file. We need to make sure that 2 uploads of the same filename are not done in the same second because some backend server implementations (oC10) use a 1-second-resolution timestamp as part of recording versions of a file.

In the code of PR #6047 it remembers the time of upload before doing the upload request. If the upload request takes some time, that means that the actual upload second recorded in the server backend might be later than what the test-runner remembered. For example:

- test runner remembers 12:30:35.30
- test runner sends upload request of a big file at 12:30:35.35
- server-under-test receives file, sends response and finally moves the old content to a version at 12:30:36.20 (the timestamp of the version has 12:30:36)
- test runner  waits until at least 12:30:36.30 and uploads another (small) file
- server-under-test receives file, sends response and moves the old content to a version at 12:30:36.50 (the timestamp of the version has 12:30:36)

Now both versions are using the same timestamp. The later version effectively overwrites the older version.

The upload time in the test-runner needs to be remembered after the upload has finished. That should be safe.

**Comment by individual-it** [comment]
This also needs to be done in the middleware

**Comment by phil-davis** [comment]
> This also needs to be done in the middleware

I raised middleware issue https://github.com/owncloud/owncloud-test-middleware/issues/59

**Comment by SwikritiT** [comment]
> > This also needs to be done in the middleware
> 
> I raised middleware issue [owncloud/owncloud-test-middleware#59](https://github.com/owncloud/owncloud-test-middleware/issues/59)

I'll assign myself and make a PR there too
