### ISSUE TITLE
Smoke tests are flaky

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6082]
I noticed a few of these earlier in the week, but couldn't reproduce it yesterday. Just now I got this:

https://drone.owncloud.com/owncloud/web/20591/10/18
```
    Then "Brian" downloads the following files
      │ resource │ from             │
      │ data.zip │ Shares/meal plan │
    ✖ failed
      page.click: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for selector "//span[@data-test-resource-name="data.zip"]/ancestor::tr[contains(@class, "oc-tbody-tr")]//button[contains(@class, "oc-table-files-btn-action-dropdown")]"
      ============================================================
          at Object.open (/var/www/owncloud/web/tests/smoke/support/cta/files/sidebar.ts:5:16)
          at AllFilesPage.downloadFiles (/var/www/owncloud/web/tests/smoke/support/page/files/allFiles.ts:64:43)
          at World.<anonymous> (/var/www/owncloud/web/tests/smoke/features/step_definitions/app.files.ts:75:27)
```

That was running with oC10 server as the back-end. I think that I have only seen it fail when using the oC10 back-end.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/20603/10/16
```
    Then "Alice" downloads the following files
      │ resource      │ from                                 │
      │ parent.txt    │ groups/Kindergarten Koalas/meal plan │
      │ lorem.txt     │ groups/Kindergarten Koalas/meal plan │
      │ lorem-big.txt │ groups/Kindergarten Koalas/meal plan │
      │ data.zip      │ groups/Pre-Schools Pirates/meal plan │
      │ lorem.txt     │ groups/Pre-Schools Pirates/meal plan │
      │ lorem-big.txt │ groups/Pre-Schools Pirates/meal plan │
      │ data.zip      │ groups/Teddy Bear Daycare/meal plan  │
      │ lorem.txt     │ groups/Teddy Bear Daycare/meal plan  │
      │ lorem-big.txt │ groups/Teddy Bear Daycare/meal plan  │
    ✖ failed
      page.click: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for selector "//span[@data-test-resource-name="data.zip"]/ancestor::tr[contains(@class, "oc-tbody-tr")]//button[contains(@class, "oc-table-files-btn-action-dropdown")]"
      ============================================================
          at Object.open (/var/www/owncloud/web/tests/smoke/support/cta/files/sidebar.ts:5:16)
          at AllFilesPage.downloadFiles (/var/www/owncloud/web/tests/smoke/support/page/files/allFiles.ts:64:43)
          at World.<anonymous> (/var/www/owncloud/web/tests/smoke/features/step_definitions/app.files.ts:75:27)
```

Another example.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/20621/11/13
```
    Given "Brian" has logged in
    ✖ failed
      page.fill: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for selector "#oc-login-username"
      ============================================================
          at OcisLoginAdapter.login (/var/www/owncloud/web/tests/smoke/support/page/login/ocis.ts:12:20)
          at LoginPage.login (/var/www/owncloud/web/tests/smoke/support/page/login/index.ts:16:28)
          at World.<anonymous> (/var/www/owncloud/web/tests/smoke/features/step_definitions/session.ts:10:21)
```

That one failed with oCIS backend.

I really don't understand why the smoke-test "user journey" tests have become flaky in the last few days.

**Comment by phil-davis** [comment]
@ScharfViktor FYI - I wonder what has happened to make the smoke test scenarios flaky?

**Comment by ScharfViktor** [comment]
A large PR has been added in the last few days. https://github.com/owncloud/web/pull/6005
although some of the errors that you have attached do not apply to the PR.
I will identify flaky places in test into CI and fix it

**Comment by ScharfViktor** [comment]
https://drone.owncloud.com/owncloud/web/20624/11/12
![image](https://user-images.githubusercontent.com/84779829/144471900-dc62f989-52d7-424a-85ee-db3abb780623.png)

**Comment by ScharfViktor** [comment]
https://drone.owncloud.com/owncloud/web/20618/11/12

![image](https://user-images.githubusercontent.com/84779829/144472126-ebb1ac0c-c584-47de-9c6e-086ea8063241.png)

**Comment by ScharfViktor** [comment]
https://drone.owncloud.com/owncloud/web/20634/10/17
![image](https://user-images.githubusercontent.com/84779829/144607197-caaef0ff-60c0-4339-8cd1-7ffdc25a332a.png)

**Comment by phil-davis** [comment]
PR #6092 should have improved this.

But the merge CI had a smoke test fail:
https://drone.owncloud.com/owncloud/web/20783/9/12
```
    When "Alice" creates new version of the following files
      │ resource   │ to               │
      │ simple.pdf │ folder_to_shared │
    Then "Alice" ensures that the resource "folder_to_shared/simple.pdf" has 1 version
    ✖ failed
      Error: expect(received).toEqual(expected) // deep equality

      Expected: 1
      Received: 0
          at World.<anonymous> (/var/www/owncloud/web/tests/smoke/features/step_definitions/app.files.ts:156:80)
```
That was the pipeline running on oCIS. The pipeline on oC10 passed.

We need to see if this is intermittent on only oCIS or also on oC10.

**Comment by pascalwengerter** [comment]
@ScharfViktor I've tried running the smoke tests on #6114 locally a couple of times now and they fail when Alice is supposed to log in but already has a session running

**Comment by ScharfViktor** [comment]
https://drone.owncloud.com/owncloud/web/20836/11/12
add a response check when copying a file:

<img width="583" alt="Screenshot 2021-12-09 at 13 55 59" src="https://user-images.githubusercontent.com/84779829/145400558-faecdd8c-8043-4d72-b2a4-fcb806c154fd.png">

**Comment by pascalwengerter** [comment]
> @ScharfViktor I've tried running the smoke tests on #6114 locally a couple of times now and they fail when Alice is supposed to log in but already has a session running

Turns out this is only a result of a previous `.feature` file failing and skipping Alice's logout step.

The two most popular issues (on oCIS, at least) seem to be:
1. Carol can't download her files as expected. Brian can download the file some steps before without problems, and if you comment him out Carol's downloads work as expected 
2. Sharing via the quick actions is broken because the right sidebar hides the quick actions (which I can't reproduce locally because the automated Chrome does weird viewport things)

**Comment by ScharfViktor** [comment]
> 1. Carol can't download her files as expected. Brian can download the file some steps before without problems, and if you comment him out Carol's downloads work as expected

I found the problem

**Comment by pascalwengerter** [comment]
> > 1. Carol can't download her files as expected. Brian can download the file some steps before without problems, and if you comment him out Carol's downloads work as expected
> 
> I found the problem

Just used the debugger, the step definitions are fine but it seems like the tests are "running through" too fast and don't wait long enough for the sidebar content to be replaced or sth

**Comment by pascalwengerter** [comment]
> > > 1. Carol can't download her files as expected. Brian can download the file some steps before without problems, and if you comment him out Carol's downloads work as expected
> > 
> > 
> > I found the problem
> 
> Just used the debugger, the step definitions are fine but it seems like the tests are "running through" too fast and don't wait long enough for the sidebar content to be replaced or sth

Working with @fschade on disabling animations since "tests running too fast" most likely is a result of animations being too slow

**Comment by phil-davis** [comment]
> Working with @fschade on disabling animations since "tests running too fast" most likely is a result of animations being too slow

Yes, we have had this challenge elsewhere - tests have to wait for animations to finish. I think we have methods like `waitForAnimations`that we had to write in the other frameworks, that figure out a way to check/poll the browser animation state. It is all a bonus nuisance for test code. And if an animation always takes, for example, 1 second, then the test (and a real advanced user) is always slowed up 1 second waiting-and-watching the animation.

**Comment by pascalwengerter** [comment]
> > Working with @fschade on disabling animations since "tests running too fast" most likely is a result of animations being too slow
> 
> Yes, we have had this challenge elsewhere - tests have to wait for animations to finish. I think we have methods like `waitForAnimations`that we had to write in the other frameworks, that figure out a way to check/poll the browser animation state. It is all a bonus nuisance for test code. And if an animation always takes, for example, 1 second, then the test (and a real advanced user) is always slowed up 1 second waiting-and-watching the animation.

I wish we would be that far already... https://github.com/owncloud/web/blob/1badbff426a07843cee7a587828c08b5b3c911e7/tests/acceptance/customCommands/waitForAnimationToFinish.js#L6

**Comment by phil-davis** [comment]
Hmmm - it's all rather sad. I thought that we dug into this more. But I have found discussion here:
https://github.com/owncloud/core/issues/34689

And core still has a couple of places where there is a hard-coded 1-second wait. That is a brittle point, because if the animation speed is slowed in the browser code, then the test will start failing (but not necessarily a "hard" fail). And if the animation is removed, the test will waste that time forever (nobody is likely to remove the `sleep` in the test when they remove the animation).

Ideally there would be a `waitForAppToBeReadyForNextAction` method, and that "magically knows when any browser page is ready for the user". But in the modern world of live pages, some things are "never"  really ready, they are "constantly" firing off requests to a backend and updating the weather report, the stock market, exchange rates, the list of files that the server has,... This is an impossible problem to solve in the general case, and it is a problem also for real users - their brain just instructs their finger to click, and the page updates at that moment and what they click on is something different. I have this happen to me often when dismissing GitHub notification. Just as I go to click to dismiss the notification, the list updates and I end up dismissing a notification that didn't even reach my brain yet!

So the test code has to have more-and-more knowledge about the back-end implementation, to try and second-guess it. PITA!

**Comment by fschade** [comment]
At least they say it’s supported, https://playwright.dev/docs/actionability/

**Comment by fschade** [comment]
i can confirm that playwright waits 100% i tested it by setting a 5 second animation duration for the sidebar and resources table.... playwright handled it without any problem.

**Comment by pascalwengerter** [comment]
Disabling thumbnails via #6143 reduced flakiness by quite a bit, we still see failing OC10 pipelines (like https://drone.owncloud.com/owncloud/web/21008/8/17) sometimes

**Comment by ScharfViktor** [comment]
> Disabling thumbnails via #6143 reduced flakiness by quite a bit, we still see failing OC10 pipelines (like https://drone.owncloud.com/owncloud/web/21008/8/17) sometimes

<img width="484" alt="Screenshot 2021-12-14 at 10 23 02" src="https://user-images.githubusercontent.com/84779829/145970477-0bd036a1-7134-4bfd-9ea4-e270c470fbef.png">

strange the test did not find the file, but it is definitely there and this test has already checked. 

common mistake in OC10- when the Shares folder is not displayed after accepting share(helps reload page)

**Comment by ScharfViktor** [comment]
waiting response "accept share" didn't help 
https://drone.owncloud.com/owncloud/web/21021/10/18
