### ISSUE TITLE
[tests-only] Balance out length of web acceptance test pipelines

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6095]
web acceptance test pipelines are taking between 10 and 25 minutes to finish. Balance out the number of features/scenarios in each pipeline so that each pipeline can finish in about the same time (let's aim for about 15 minutes maximum for a pipeline)

**Comment by phil-davis** [comment]
Also, do not increase the number of pipelines. (Sorry, I didn't explicitly write that in my first issue description)

**Comment by pascalwengerter** [comment]
@phil-davis please also add an item to your next sprint to do the same in oCIS (see recent web ui acceptance pipelines lengths in https://drone.owncloud.com/owncloud/ocis/8215)

**Comment by phil-davis** [comment]
> @phil-davis please also add an item to your next sprint to do the same in oCIS (see recent web ui acceptance pipelines lengths in https://drone.owncloud.com/owncloud/ocis/8215)

The CI there auto-splits the available web test suites into 20 pipelines. There are currently 67 suites! So each pipeline runs 3 or 4 test suites, chosen in alphabetical order. That does result in some "random" effects, if a couple of longer test suites are close to each other alphabetically.

We can manually specify them in the oCIS `.drone.star` and manually balance the run-times. The challenge that we have doing that in the past is that when someone adds/changes.... test suites in web, "someone" (tm) has to remember to update the test suite matrix in oCIS. We had times in the past when a new suite was forgotten, and never being run in oCIS.

I guess that will be less of a problem for the future, since we are minimizing our nightwatch test changes anyway.

Issue https://github.com/owncloud/ocis/issues/2872
