### ISSUE TITLE
Filename changed on upload when including "."

### ISSUE THREAD

**Issue by axstet** [owncloud/web#6107]
## Describe the bug

Filename changed on upload when including ".".

## Steps to reproduce

1. Setup OCIS
2. Log into web client
3. Upload file named "a b. C"

## Expected behavior
File "a b. C" is uploaded.

## Actual behavior
File "a b. c" is uploaded. Somehow "C" becomes lowercase.

## Setup

Stock 1.15

**Comment by kulmann** [comment]
Thanks for reporting this bug @axstet. It's already tracked in https://github.com/owncloud/web/issues/5339 - I'll close this one here as duplicate and mention you in the other one so that you'll get notified when it gets fixed.

Thanks @wkloucek for qualifying the bug!
