### ISSUE TITLE
Logout issues with oauth2 / oc10

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#6108]
### Steps to reproduce
1. Log in to oc10
2. Switch over to new design / oC Web
3. Log out

### Expected behaviour
Be logged out

### Actual behaviour
I get re-logged in automatically.

### Bug analysis
When web is configured as an oauth2 trusted client, I get a new access token automatically because my oc10 session is still active. Logging out should kill both my oc10 session and my access token. Same the other way around, when I log out in oc10 my access token should be killed automatically.

**Comment by pascalwengerter** [comment]
Duplicate to #5886?

**Comment by kulmann** [comment]
Oh yes, sorry for the noise. Closing here, thanks for the quick spot!
