### ISSUE TITLE
delete test steps that can be used through the middleware

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#6111]
follow up of https://github.com/owncloud/web/issues/5132

since #5136 the testing-middleware is implemented in web, to finish the work
- [x] rename steps so that they use the middleware
- [x] delete duplicated code from web 

This can be done in multiple PRs

**Comment by dpakach** [comment]
### Context files that needs to be partially of fully remove from web tests
- [ ] - filesContext.js
- [ ] - generalContext.js
- [ ] - notificationsContext.js
- [ ] - provisioningContext.js
- [ ] - publicLinkContext.js
- [ ] - sharingContext.js
- [ ] - webdavContext.js

### helper files that needs to be partially of fully remove from web tests
- [ ] - backendHelper.js
- [ ] - codify.js
- [ ] - config.js
- [ ] - httpHelpepr.js
- [ ] - ldapHelper.js
- [ ] - objects.js
- [ ] - occHelper.js
- [ ] - path.js
- [ ] - sharingHelper.js
- [ ] - testHelper.js
- [ ] - userSettings.js
- [ ] - webdavHelper.js

**Comment by SwikritiT** [comment]
All the PR's for this issue have been merged. So closing this.

**Comment by pascalwengerter** [comment]
Thanks for all the efforts!
