### ISSUE TITLE
Delete current folder -> left sidebar disappears

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6115]
### Steps to reproduce
1. Login at: https://ocis.ocis-traefik.latest.owncloud.works/
2. create "new folder"
3. enter "new folder"
4. breadcrumb 3-dots menu -> delete
5. left sidebar disappears

### Expected behaviour
1. left sidebar should stay visible

### Actual behaviour
left sidebar disappears

![2021-12-08_21-01-09 (1)](https://user-images.githubusercontent.com/26610733/145277086-96a4f8e6-a7ec-4357-aef3-88efe79fe8d2.gif)

**Comment by dschmidt** [comment]
Cannot reproduce anymore.
