### ISSUE TITLE
customization options of the files list are hidden behind the sidebar

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#6116]
### Steps to reproduce
1. Open sidebar
2. Open files list configuration

### Expected behaviour
Options are in front of the sidebar

![Screenshot_20211208_212213](https://user-images.githubusercontent.com/448487/145279938-8de97153-68f1-430a-8bf7-13a9f25f69de.png)

**Comment by kulmann** [comment]
Which browser? Both Firefox and Chrome on macOS show it like this:

<img width="744" alt="Screenshot 2021-12-09 at 11 13 47" src="https://user-images.githubusercontent.com/3532843/145377457-7c5dab43-3c11-4803-b222-0745899d7f42.png">

**Comment by pascalwengerter** [comment]
Screensize/Viewport would be interesting as well for debugging :)

**Comment by dschmidt** [comment]
Yeah, good points - will try to reproduce and add info :)

**Comment by dschmidt** [comment]
`window.visualViewport`:
```
VisualViewport {
height: 544
offsetLeft: 0
offsetTop: 0
onresize: null
onscroll: null
pageLeft: 0
pageTop: 0
scale: 1
width: 2210
}
```

**Comment by JanAckermann** [comment]
I don't think this is an issue anymore, 
not reproducible even with the same width

![image](https://user-images.githubusercontent.com/26169327/168559424-38568606-7f8f-45c3-b179-b6109cf529f5.png)
