### ISSUE TITLE
failing test scenario shareByPublicLinkExpiringLinks.feature:106

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6158]
https://drone.owncloud.com/owncloud/web/21094/35/21

This scenario is testing with a public link expiry date 15 days in the future. That is current 16 Dec 2021 + 15 days = 31 Dec 2021.
```
Timed out while waiting for element <//div[not(contains(@class, "is-not-in-month"))]/span[contains(@class, "vc-day-content vc-focusable") and normalize-space(.)="31" and @aria-label="Friday, December 31, 2021"]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10003ms)
```

That is the last day of 2021. I suspect that the date picker is behaving a bit differently as we come to changing over to 2022. Needs investigating.

**Comment by pascalwengerter** [comment]
> https://drone.owncloud.com/owncloud/web/21094/35/21
> 
> This scenario is testing with a public link expiry date 15 days in the future. That is current 16 Dec 2021 + 15 days = 31 Dec 2021.
> 
> ```
> Timed out while waiting for element <//div[not(contains(@class, "is-not-in-month"))]/span[contains(@class, "vc-day-content vc-focusable") and normalize-space(.)="31" and @aria-label="Friday, December 31, 2021"]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10003ms)
> ```
> 
> That is the last day of 2021. I suspect that the date picker is behaving a bit differently as we come to changing over to 2022. Needs investigating.

Checked on web.owncloud.com, selecting the "next month" in December automatically switches to January in the next year

What we need in the acceptance tests is a _sustainable_ solution that calculates if the expiry date would be in the following month, then changes the month in the datepicker reliably and picks the (calculated) expiry date there

**Comment by phil-davis** [comment]
> What we need in the acceptance tests is a sustainable solution that calculates if the expiry date would be in the following month, then changes the month in the datepicker reliably and picks the (calculated) expiry date there

Agree with "sustainable"! Maybe the test should directly insert (type...) the date into the DOM element, and not try to use the date-picker at all? That would avoid having to give the test code full knowledge of the date-picker mechanics.

But there might still be some test cases where we want to check that invalid dates (in the past...) are actually disabled in the date-picker. Since we are moving away from nightwatch anyway, we could remove such tests (if they exist).

**Comment by phil-davis** [comment]
@SwikritiT do you have any code ideas/proposals yet to fix this?

**Comment by phil-davis** [comment]
@SwikritiT please have a look at what was done in PR #6161 and answer https://github.com/owncloud/web/pull/6161#issuecomment-995926895

We need to see if anything else might need to be done in the coming days, as other tests with different expiry get close to 2022.

**Comment by fschade** [comment]
> @SwikritiT please have a look at what was done in PR #6161 and answer [#6161 (comment)](https://github.com/owncloud/web/pull/6161#issuecomment-995926895)
> 
> We need to see if anything else might need to be done in the coming days, as other tests with different expiry get close to 2022.

the solution is just a workaround as it does not reflect real user behavior, please be careful when (re-)using it.
