### ISSUE TITLE
Create new draw.io fails with If-None-Match Error

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#6162]
Seen with web 4.6.1 and core 10.9.0 rc2

![image](https://user-images.githubusercontent.com/1108546/146463670-4e440fae-c383-4be1-8ea6-1c5b5a5e354a.png)

**Comment by jnweiger** [comment]
"New draw.io document" is the only file type that can be created. 
TXT and office files are not available in the [+NEW] dropdown. (richdocuments is installed and works fine in the classic UI)

![image](https://user-images.githubusercontent.com/1108546/146463923-de7cce59-5a0d-4a45-b36e-410eb8abaeda.png)

**Comment by dschmidt** [comment]
New txt and New markdown file options are available when markdown-editor app is enabled

**Comment by pascalwengerter** [comment]
Can't reproduce anymore, closing here
