### ISSUE TITLE
Smoke test failed in nightly - waitForResponse timeout

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6163]
https://drone.owncloud.com/owncloud/web/21119/9/12
```
  Scenario: Alice shares file to Brian # tests/smoke/features/shareFileJourney.feature:13
    Given following users have been created
      │ Alice │
      │ Brian │
    And admin set the default folder for received shares to "Shares"
    And admin disables auto accepting of the shares
    Given "Alice" has logged in
    When "Alice" opens the "files" app
    And "Alice" creates the following folder
      │ folder_to_shared │
    And "Alice" uploads the following resource
      │ resource        │ to               │
      │ testavatar.jpeg │ folder_to_shared │
    And "Alice" shares the following resource via the quick action
      │ resource                         │ user  │ role   │
      │ folder_to_shared/testavatar.jpeg │ Brian │ viewer │
    ✖ failed
      page.waitForResponse: Timeout while waiting for event "response"
          at AllFilesPage.shareResouce (/var/www/owncloud/web/tests/smoke/support/page/files/allFiles.ts:101:22)
          at World.<anonymous> (/var/www/owncloud/web/tests/smoke/features/step_definitions/app.files.ts:53:9)
```

**Comment by phil-davis** [comment]
@ScharfViktor FYI somehow `waitForResponse` can timeout.

**Comment by phil-davis** [comment]
Rerun passed: https://drone.owncloud.com/owncloud/web/21121/9/12

So this intermittent, sadly.

**Comment by pascalwengerter** [comment]
> @ScharfViktor FYI somehow `waitForResponse` can timeout.

From the playwright docs [waitForResponse](https://playwright.dev/docs/api/class-page#page-wait-for-response-option-timeout) the default is 30s which makes sense because at some point the tests _should_ fail if nothing appears on the page?

Sharing sometimes fails due to animations when the sidebar "unfolds" from the left, disabling styles/animations like in https://github.com/owncloud/web/pull/6039/commits/96d38dcbeeae5f65576bbbc488e35bda3554149d makes that more stable (part of an unmerged PR)

**Comment by kulmann** [comment]
> disabling styles/animations (part of an unmerged PR)

Worth to make a dedicated PR from it?

**Comment by phil-davis** [comment]
Also note: PR #6144 was just merged. That has test changes. I don't know if they might help this.

**Comment by ScharfViktor** [comment]
> Also note: PR #6144 was just merged. That has test changes. I don't know if they might help this.

I hope they will help. They certainly won't make it worse)

**Comment by pascalwengerter** [comment]
@fschade did some awesome work in #6166 which should have made smoke tests very stable again. Closing here
