### ISSUE TITLE
Redesign Follow-up

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6203]
After #6086 has been merged, there's some follow-up tasks to be done:

## theming
- ~~Hard coded inverse buttons could be problematic if the user has a bright theme~~
- ~~Extract colors to ODS / make theme-able~~
- [ ] Decide until which width is SideNav visible (e.g. tablet in landscape mode) and introduce viewsize helpers

=> Regarding colors: to be solved via https://github.com/owncloud/web/issues/6221

## a11y
- [x] Tooltips don't survive reactivity (e.g. SidebarNavItem.vue)

## ux
- [ ] mediaviewer (zero items in SidebarNav which then disappears feels sluggish) => disabled transition
- [x] SidebarNav: Re-introduce animation https://github.com/lookacat/vue-blob-menu-animation

## ui
- [x] SidebarNav: Shadow issues next to SidebarNav 
- [x] SidebarNav top left rounded corner has a white artifact border
- [x] Files app container: Scrollbar styling with many files
- [x] Upload drop area has an offset to the right

## features
- ~~Mobile views for Topbar & SidebarNav~~ (Will be done late)
- [ ] Show reduced topbar on public pages
- [x] Unify usage of `icon` and `iconMaterial` for app routes

**Comment by wkloucek** [comment]
The Iframe for external apps also has the wrong height (doesn't fill the window). 

![image](https://user-images.githubusercontent.com/34452982/148212801-8dfd59a8-2775-4d5c-900f-b4d6b8d0b89d.png)

**Comment by pascalwengerter** [comment]
Opening the mediaviewer and closing it doesn't re-introduce the SidebarNav with the page navigation (which wasn't shown anymore since the mediaviewer doesn't have SidebarNavItems)
