### ISSUE TITLE
e2e tests: run playwright e2e tests using the middleware

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#6209]
### TODO:
- [ ] run e2e playwright tests using the middleware service

**Comment by pascalwengerter** [comment]
@phil-davis is this targeting the nightwatch `@smokeTest` flag or the Playwright "smoke" tests? Because the later doesn't need the middleware AFAIK

**Comment by kiranparajuli589** [comment]
> @phil-davis is this targeting the nightwatch `@smokeTest` flag or the Playwright "smoke" tests? Because the later doesn't need the middleware AFAIK

@pascalwengerter this is for the playwright smoke tests. so far, the API _(Given and Then)_ steps are within the `tests/e2e` but these can be reused from the middleware.

Another reason to depend on middleware for e2e tests is to completely move `tests/acceptane/filesForUpload` from web to middleware repo. Since the `e2e` tests also need `fileForUpload`, it will not be neat to clone and the middleware just for `filesForUpload`.

open for your comments and suggesns :).

**Comment by phil-davis** [comment]
Note: the middleware gives access to all the `Given` test steps that set up scenarios using the server API - create users, groups, shares, upload initial files, create folder(s) for users and so on.

Without the middleware, each implementation of an end-2-end test framework/language needs to code all those things. For example, the similar steps have to be written in PHP (Behat). JS for nightwatch, TS for Playwright, Squish for the desktop client....

**Comment by fschade** [comment]
@phil-davis @kiranparajuli589, the idea we had when we introduced the e2e tests (former smoke tests) was, to have something that is isolated without any external dependencies. 

It was important for us to be able to run them also against external, internal (non dockerized) setups.
Now we're forced to start the middleware and have a strong dependency to it.

Beside that we do not need to use the files provided by the middleware and can provide our own set of (few) files.
Can you please revert the middleware e2e binding again?

**Comment by individual-it** [comment]
@fschade we haven't been aware that this is the purpose of the e2e test. See comments above why we think using the middleware is a good thing in the e2e tests. But if reducing the dependencies is of higher priority than reducing code duplication we can revert the work done for the e2e tests, resulting in having to implement all the steps that the middleware provides again in playwright and also copy any filesForUpload needed to playwright.

CC @ScharfViktor

**Comment by kulmann** [comment]
> @fschade we haven't been aware that this is the purpose of the e2e test. See comments above why we think using the middleware is a good thing in the e2e tests. But if reducing the dependencies is of higher priority than reducing code duplication we can revert the work done for the e2e tests, resulting in having to implement all the steps that the middleware provides again in playwright and also copy any filesForUpload needed to playwright.
> 
> CC @ScharfViktor

Yes, please do. Sorry that this communication didn't happen earlier. I was not aware of this ticket, although it has been open for 9 days... we are aware of the duplication and think that it's unavoidable. Regarding files, another approach than keeping files in the repo could be ok as well. e.g. creating fake files on demand or `curl`ing them during test runtime from another repo.

**Comment by fschade** [comment]
yes please revert it, if we have to share things at a later point we could do it by using a npm package

**Comment by phil-davis** [comment]
Reverted in #6249
