### ISSUE TITLE
Redesign "Context Menu"

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6212]
# Description
## User Stories

* > As a user I want Context Menus to be presented in an appealing and well structured way so that my cognitive costs are low.

## Value
- Reduce cognitive costs
- increase acceptance for the new Web UI

## Acceptance Criteria (Desktop)
- Style context menus according to the design
- reorder actions according to screenshot
- re-apply shadow or some visual hint to distiguish context menu clearly from background
- Cherry on Top 🍰: keylistener for arrow up/down 
- Not part of this story: The "?" on the right of an item.

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] codre review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

![image](https://user-images.githubusercontent.com/26610733/148075111-ea46911a-c215-4e47-bf05-8f3e70cfeff2.png)

## Research (fyi)
checked other context menus; numbers indicate the position in the corresponding contextmenu.
![image](https://user-images.githubusercontent.com/26610733/148075170-06b066ca-3052-42ca-b215-62b915872c8a.png)

**Comment by pascalwengerter** [comment]
Ideally also needs definitions for 
- oCIS => multiple resources selected (debatable if it's a different context to have only files, only folder or a mixture selected)
- oC10 => multiple resources selected (debatable if it's a different context to have only files, only folder or a mixture selected)

**Comment by tbsbdr** [comment]
⬆️ icons in the screenshot are deprecated - we decided to use the lighter "line" icosn as they looked nicer to us
