### ISSUE TITLE
Redesign "Breadcrumb"

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6218]
# Description

## User Stories

* > As a user I want the Breadcrumb to be presented in an appealing and well structured way so that my cognitive costs are low.

## Acceptance Criteria (Desktop)
- Design Component "Breadcrumb" Variant "leveltwo, default": https://www.figma.com/file/EqAiB1wY7cYaMaitjyzup3/?node-id=109%3A48626
- apply remix icons ✅
- apply hover states to raw button 
- note: align on visual guiding line where possible

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] codre review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

![image](https://user-images.githubusercontent.com/26610733/148190553-873c8994-b60c-4e07-8a5a-8bcfa10f7d97.png)
![image](https://user-images.githubusercontent.com/26610733/148190570-1d6251a4-04fb-41fd-bdc2-fdef35c4e5c5.png)

visual guiding line:
![image](https://user-images.githubusercontent.com/26610733/148190854-52a5e5b5-c004-43f0-9f48-6d75a2ddfa51.png)

**Comment by pascalwengerter** [comment]
There's a different definition of "hover state for raw button" in this ticket - the breadcrumb items raw buttons (aka *links into folders*) have an underline as hover state, while the "show breadcrumb context menu" raw button changes its background color (and does so differently than, for example, the dropdown raw buttons in other tickets. This may become a pain, esp. when taking theme-ability into consideration)
