### ISSUE TITLE
tests/acceptance/report/index.js is inside the acceptance folder

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6224]
PR #5743 moved `tests/report/index.js` down a level to `tests/acceptance/report/index.js`

But that file was created in PR #5650 "Add report for Smoke tests" so I am surprised that it does not belong in the Playwright test folders that are now named `e2e`

**Comment by phil-davis** [comment]
@ScharfViktor I am not familiar with this. Should the `report/index.js` ggot in the `e2e` folder?

**Comment by ScharfViktor** [comment]
> @ScharfViktor I am not familiar with this. Should the `report/index.js` go in the `e2e` folder?

Sorry, I forgot all about it. I can move the report to e2e

**Comment by phil-davis** [comment]
Good thanks - maybe @dpakach accidentally moved it inside `acceptance`

**Comment by ScharfViktor** [comment]
I think we can close it
