### ISSUE TITLE
Performance Gap with oC10 Backend

### ISSUE THREAD

**Issue by dragotin** [owncloud/web#6241]
On @hodyroff computer, it takes long time (~2.5 minutes) to render the file list after login to cloud.o.c.

![holger_longrunning](https://user-images.githubusercontent.com/1070214/149184073-d5c40a3b-9ace-45ee-a2fe-ae221a31a4a2.png)

His "homedir" in cloud.o.c consists of around 550 items.

**Comment by pascalwengerter** [comment]
Which OS and browser are being used?

**Comment by hodyroff** [comment]
Windows 10 - Edge
![image](https://user-images.githubusercontent.com/2643573/149189636-42d49de9-bf06-4082-aea0-b6e18cd294d8.png)

**Comment by fschade** [comment]
@hodyroff can you reproduce it in other browsers too (ff, chrome)? If yes, which version?

**Comment by pascalwengerter** [comment]
@fschade @kulmann regarding rendering performance of (large-ish) tables in Vue https://github.com/vuejs/vue/issues/2000

**Comment by fschade** [comment]
i tested it today and tried to reproduce it, without luck. We need to test it on your machine next week and hopefully find out why it's that slow
![Bildschirmfoto 2022-01-16 um 13 40 31](https://user-images.githubusercontent.com/49308105/149660355-dc1f2140-7a65-41bf-a57e-44653ac388a0.png)
.

**Comment by fschade** [comment]
we tested it now together and found 2 symptoms:
- the table rendering seems to get slower each time we reload
- the backend (oc10 in this case) sometimes (today after the ~ 10'th retry) hangs up and the come back alive after 2.4M

@JanAckermann is there something known?

**Comment by kulmann** [comment]
@fschade thanks for taking the time today! Did you manage to reproduce it on your machine afterwards?

**Comment by fschade** [comment]
i handover the long backend response topic to @JammingBen, i test the table rendering meanwhile

**Comment by JanAckermann** [comment]
Closing as OC10 Support has been discontinued with version 7.1.0 please reopen if you think performance tweaks are still necessary on older versions
