### ISSUE TITLE
oc10 language setting does not take effect in the Web UI

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6243]
### Steps to reproduce
1. Set your browser language to english
2. Login to oc10, go to user settings (via classic ui)
2. Set oc10 language to german (via classic ui)
3. switch to Web UI "New design"

### Expected behaviour
UI language in Web UI should be german

### Actual behaviour
UI language is english

### Note
This works as designed, but can be considered as a bug from a users perspective and should be changed therefore.

**Comment by kulmann** [comment]
This cannot be solved without changes in oc10. The language is not exposed in any API. Would be good to have it in OCS user endpoint.

**Comment by jnweiger** [comment]
Interesting... Chrome on my Android very nicely translates to German, though:

![image](https://user-images.githubusercontent.com/1108546/168807090-71d2d1f8-6310-4029-83ea-2620324ec262.png)

**Comment by JanAckermann** [comment]
> Interesting... Chrome on my Android very nicely translates to German, though:
> 
> ![image](https://user-images.githubusercontent.com/1108546/168807090-71d2d1f8-6310-4029-83ea-2620324ec262.png)

Have you tried, to set the lang to french ? ;)

**Comment by kulmann** [comment]
Web uses the browser default language as of now. So you should see the language that your browser is set to (as long as it's one of our supported languages).
