### ISSUE TITLE
FileInfo sometimes renders incorrectly in Sidebar

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6251]
### Steps to reproduce
Don't have a reliable reproduction guide as of now, sadly

### Expected behaviour
Fileinfo opens with relevant information for the currently selected file/folder

### Actual behaviour
`FileInfo.vue` detail rendering issues if `obj.sourceTime` is undefined (e.g. doesn't have an `mdate`)

**Comment by pascalwengerter** [comment]
@tbsbdr @kulmann could you eventually take a look? Could be that this has long been resolved actually

**Comment by tbsbdr** [comment]
have not seen this issue in the wild on my side.

**Comment by kulmann** [comment]
same for me. let's close and re-open if it ever resurfaces.
