### ISSUE TITLE
Redesign finetuning: Icons + white bar

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6256]
Hey! The following things have caught my eye, would be happy if some could have a look:

### change to remix icon `link` 

- https://github.com/Remix-Design/RemixIcon/blob/master/icons/Editor/link.svg

![image](https://user-images.githubusercontent.com/26610733/149383681-6a2c216e-fb08-4891-928e-eb10e30c0b9d.png)
and:
![image](https://user-images.githubusercontent.com/26610733/149396507-f16084c3-741c-4426-b6af-c751705fd131.png)

### change to remix icon `share-forward-fill`
- https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/share-forward-fill.svg
### please change to remix icon `reply-fill`
- https://github.com/Remix-Design/RemixIcon/blob/master/icons/Business/reply-fill.svg

![image](https://user-images.githubusercontent.com/26610733/149388299-947c83c2-397c-47e4-9512-a2390790fbf1.png)
should look like:
![image](https://user-images.githubusercontent.com/26610733/149388371-a1df6cda-3bb2-437a-b45d-22bbe7310a86.png)

### change to remix icon `upload-fill` (or just the same like we have in the "new" -drop menu)
- https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/upload-fill.svg
![image](https://user-images.githubusercontent.com/26610733/149388944-52fa58f4-de1e-41f3-9f40-c3883a754292.png)

### change to remix icon `user-line.svg`
- https://github.com/Remix-Design/RemixIcon/blob/master/icons/User/user-line.svg

### change to remix icon `tools-line.svg`
- https://github.com/Remix-Design/RemixIcon/blob/master/icons/Design/tools-line.svg
![image](https://user-images.githubusercontent.com/26610733/149399053-7ea13b16-3321-4868-9553-0146248294de.png)

### fix white bar on right side
- bug occurs in: current safari, chrome on MacOS❌
- ok in: firefox ✅
![image](https://user-images.githubusercontent.com/26610733/149400693-2ff01a53-5adf-4603-a085-c1aa9d87f108.png)

**Comment by kulmann** [comment]
I will include the icon changes in https://github.com/owncloud/web/pull/6228
The sidebar issue is already fixed in that PR

**Comment by tbsbdr** [comment]
perfect, thanks!! if you find some icons inappropriate, feel free to change them. did my best..

**Comment by tbsbdr** [comment]
eh - missed the 3-dots in the breadcrumb. the context menu icon should be used consistently (3-dots icon). would be nice you could still add this
![image](https://user-images.githubusercontent.com/26610733/149512404-b2ca2cc9-9212-4315-bf9a-677d26ee3858.png)

**Comment by pascalwengerter** [comment]
> eh - missed the 3-dots in the breadcrumb. the context menu icon should be used consistently (3-dots icon). would be nice you could still add this ![image](https://user-images.githubusercontent.com/26610733/149512404-b2ca2cc9-9212-4315-bf9a-677d26ee3858.png)

Can easily be done in https://github.com/owncloud/web/pull/6240

**Comment by pascalwengerter** [comment]
Or actually https://github.com/owncloud/owncloud-design-system/pull/1886 since it's an ODS task IIRC

**Comment by pascalwengerter** [comment]
Fixed here https://github.com/owncloud/owncloud-design-system/pull/1886/commits/c37cbbd79ccf0558652c3473ed3a5a6488cf379f @tbsbdr
