### ISSUE TITLE
badges for nav-items

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#6259]
## User story
* > As an ownCloud project manager/owner I'd like to make it clear that the project spaces featureset is not fully functioning, yet, so that users don't have wrong expectations.
* > As a user I'd like to be informed in the UI that the project spaces featureset is not in a stable state, yet, so that I don't expect it to be fully functional, yet.

## Value 
Expectation management

## Discussion
- technically, `alpha` would be more appropriate, but `beta` is the well known term for everyday users, `alpha` not so much. What should we choose for the badge text?

## Acceptance criteria
- The nav item in the left sidebar has a nice badge with a text value or an icon, based on the outcome of the discussion stated above

### Design proposal
![image](https://user-images.githubusercontent.com/26610733/149508128-7598b229-59d6-48e5-9d0a-a7235741aaf5.png)

**Comment by tbsbdr** [comment]
added design proposal
