### ISSUE TITLE
add documentation to run e2e tests

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#6263]
### Description
Currently web docs https://owncloud.dev/clients/web/ only contains documentation for:
- running acceptances tests
- running acceptance tests manually

It will be very helpful if we also have the docs for running the e2e tests

**Comment by kiranparajuli589** [comment]
cc @individual-it @ScharfViktor @kulmann @pascalwengerter

**Comment by pascalwengerter** [comment]
I'll gladly take care of this next week, thanks for bringing it up!
