### ISSUE TITLE
mediaviewer download button does not trigger download

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#6273]
### Steps to reproduce
1. Open Image in mediaviewer
2. Click download button

### Expected behaviour
File is downloaded

### Actual behaviour
Browser navigates to file without triggering a download

This is especially annoying on a phone.

I have only tested it with OC10 for now, needs to be confirmed with oCIS. We possibly need to add a query parameter so headers telling the browser to initiate a "download" are sent

**Comment by pascalwengerter** [comment]
Can't confirm when running something-close-to-current-master with dockerized OC10/oCIS on Firefox/Ubuntu O.o both trigger the "normal" download file dialogue

**Comment by kulmann** [comment]
Tested it with a sidecar oc10 deployment, also without issues with the download.
