### ISSUE TITLE
Image that is uploaded first, if opened first the picture is not displayed in the image media viewer in ocis backend

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6289]
The image that is uploaded first, if opened first the picture is not displayed in the image media viewer

### Steps to reproduce
1. `docker-compose pull`
1. `docker-compose up ocis selenium vnc `
2. Access `ocis` through `vnc`
3. Log in to `Einstein`
4. upload `testavatar.jpg` first and then upload `testavatar.png`
5. Now open `testavatar.jpg` in a media viewer through the details panel. A blank white screen is shown instead of a picture. 
![image1](https://user-images.githubusercontent.com/41103328/150333891-858b2291-07c1-46a1-84c0-2791363d57b4.png)
 
6. Go to the next picture `testavatar.png` through the media viewer. It displays.

![image2](https://user-images.githubusercontent.com/41103328/150334060-6b363b2c-c7f0-4e0e-bbcf-feb45d0efdd8.png)

7. Now go back to the previous picture. White screen again but the name at the bottom is `testavatar.png`

![image3](https://user-images.githubusercontent.com/41103328/150334484-89e53865-b2e2-47e9-ac9f-3bcb827ac130.png)

8. Delete both of the pictures and repeat step 4
9. This time open `testavatar.png` first (i.e the image that was uploaded second) through details panel. It's displayed.

![image4](https://user-images.githubusercontent.com/41103328/150335031-4fc559c6-7555-481a-849e-58e4d9021ce9.png)

10. Switch to the next image. It is also displayed.

![image5](https://user-images.githubusercontent.com/41103328/150335305-e9fc7e4d-691e-4cd3-83e1-18ecf4986e8f.png)

11. This issue does not exist for video formats or if only one picture is uploaded.

### Expected behaviour
The image should be displayed no matter the order of upload.

### Actual behaviour
As described above

**Comment by individual-it** [comment]
@SwikritiT please try to see if that works with an older version of web (as it works with the web that is compiled into ocis)
and with `git bisect` find the commit that caused it

**Comment by SwikritiT** [comment]
I think the problem with the media viewer arose from this https://github.com/owncloud/ocis/pull/2739 PR in ocis. I couldn't track it down to a single commit because a lot of ocis commits didn't build properly and I had to skip them. Upon git bisect, it showed that one of these might be the first faulty commits. 
```
b63b322b6f0abfd2cb4e6a7f3359b6517e56f723
c36e99895bbfd25b923455feb6b1c16f0f52e576
5a29959a0bfe26fa468101207c0343cd283f737f
de7620af98a2ec3fdd36bc90a83cd0597a3fb89b
5ec72daaeb512efbc83c62e13fc098f4f49ed5a0 
```
Surprisingly I couldn't reproduce the problem in the current master ocis. It can be reproduced in commits from this PR https://github.com/owncloud/ocis/pull/2739 to this https://github.com/owncloud/ocis/pull/2989

but after this commit, it cannot (so maybe it fixed it?) https://github.com/owncloud/ocis/pull/2979/commits/0bfc1f08b7f7a2298185af73b356bd8bfab3aef1

I also tried to reproduce it with the previous version of the web and yes it can be reproduced if the ocis is between https://github.com/owncloud/ocis/pull/2739 to this https://github.com/owncloud/ocis/pull/2989 commit

**Comment by phil-davis** [comment]
Yes, the problem is not happening in CI any more when it points to the very latest oCIS commit id. So "something happened" in the last week or so that fixed it.
