### ISSUE TITLE
E2E Tracing in ci reports too much traces

### ISSUE THREAD

**Issue by fschade** [owncloud/web#6291]
It looks like that the tracing (generation) is enabled by default in the ci.
It should only generate traces (by default) in cases where the ci fails.

See https://github.com/owncloud/web/pull/6288#issuecomment-1017413845 for reference , here we should only have 3 trace zips for the failing step.

Expected behavior:
* if a feature failed it, should create a github comment with the title of the feature and attach the zips
* it should not generate traces if no feature fails (default)
* it should not compose multiple feature traces into one comment (or add a headline to see which feature the trace belongs to)

**Comment by ScharfViktor** [comment]
Okay, I'll try to figure it out.

**Comment by fschade** [comment]
Thanks 🤟  @ScharfViktor, if you need some pairing/brainstorming ping me.
