### ISSUE TITLE
Configuration unavailable within extensions

### ISSUE THREAD

**Issue by diocas** [owncloud/web#6296]
Web is loading the configs **before** registering the apps (which populates `state.fileEditors`). This means that the following code has no effect:

```js
  LOAD_EXTENSION_CONFIG(state, { id, config }) {
    // make available in editors
    const editors = [...state.fileEditors]
    for (const editor of editors) {
      if (editor.app === id) {
        editor.config = config
      }
    }
    state.fileEditors = editors
(...)
```
(https://github.com/owncloud/web/blob/master/packages/web-runtime/src/store/apps.js#L109)

Without this, there are no configurations available within the extension context.

**Comment by dschmidt** [comment]
Thanks for debugging!
