### ISSUE TITLE
preview: filename hovers the image when the viewport is too small

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#6300]
... and becomes unreadable

![Screenshot_20220122_135613](https://user-images.githubusercontent.com/448487/150639447-f42b2c66-ae0a-4fb3-b982-805629ccd91a.png)

... also visible in this screenshot:
neither image nor controls are centered correctly :trollface:

**Comment by JanAckermann** [comment]
@kulmann As we have the toolbar on top for the pdf-viewer and text editor app, we might think about moving the preview toolbar to the top as well, easier to implement + consistency reasons

**Comment by pascalwengerter** [comment]
> @kulmann As we have the toolbar on top for the pdf-viewer and text editor app, we might think about moving the preview toolbar to the top as well, easier to implement + consistency reasons

Bonus points to have them stuck to bottom on mobile screens maybe? 😉 @tbsbdr

**Comment by kulmann** [comment]
> @kulmann As we have the toolbar on top for the pdf-viewer and text editor app, we might think about moving the preview toolbar to the top as well, easier to implement + consistency reasons

Yes, all in for the consistency :-) I think we'll have more button-candidates for the topbar, which I would try to align to the top right, see https://github.com/owncloud/web/issues/7160 so having the topbar as you described would be a good preparation for that as well.
