### ISSUE TITLE
JS Error while using ownCloud Web Collabora integration

### ISSUE THREAD

**Issue by xoxys** [owncloud/web#6313]
![image](https://user-images.githubusercontent.com/3391958/151008104-5ff63964-fb12-4324-8c6d-f43ca2a0169e.png)

ownCloud Web is running as a docker sidecar container.

### Steps to reproduce
1. Setup Collabora integration in ownCloud Web
2. Open a document
3. Take a look at the browser console

### Environment general
**Operating system**: Ubuntu 18.04

**Backend (ownCloud Core or Infinite Scale)**: ownCloud Core

### Environment ownCloud Core
**Version:** 10.9.0

**Where did you install ownCloud from:** Tarball

**Comment by pascalwengerter** [comment]
@xoxys could I ask you to check again with web >`v5.x.x` to see if the error persists?

**Comment by xoxys** [comment]
Sure :) Just in case, you can easily check this on your own at web.owncloud.com where OnlyOffice as well as Collabora is available as well.

Issue still exists:

![image](https://user-images.githubusercontent.com/3391958/155694971-fbc0ba90-8493-4252-b170-d04ad54edb0f.png)
