### ISSUE TITLE
Allow uploads outside of user home despite user not having enough quota

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#6318]
The `/ocs/v1.php/cloud/users/$username` endpoint returns the home quota of the user and based on this, the upload button is disabled irrespective of the path. For shares and project spaces, this shouldn't be the case.

The propfind response contains the permission string, which starts with an `S` if the path is a shared folder, so that can be used to disable this check.

Also, related issue, this error is not visible to the user https://github.com/owncloud/web/issues/5937

**Comment by kulmann** [comment]
Related: https://github.com/owncloud/web/issues/5817
