### ISSUE TITLE
nightwatch test failures with new SDK version 1.0.0-2933

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6322]
https://drone.owncloud.com/owncloud/web/22195/18/21
```
runsh: Total unexpected failed scenarios throughout the test run:
webUILogin/oauthLogin.feature:42
webUILogin/oauthLogin.feature:50
```

example:
```
  Scenario: the user session of a deleted user is cleared properly # features/webUILogin/oauthLogin.feature:42
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (407ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    Given user "Alice" has logged in using the webUI
√ Element <#user> was visible after 1096 milliseconds.
√ Element <#user> was not present after 12 milliseconds.
√ Element <button[type=submit]> was visible after 43 milliseconds.
√ Element <button[type=submit]> was not present after 37 milliseconds.
√ Element <.app-content> was visible after 1180 milliseconds.
    And the user has browsed to the files page
√ Element <//nav[@id="files-breadcrumb"]//*[(self::a or self::button) and contains(text(),'All files')]> was visible after 61 milliseconds.
    And user "Alice" has been deleted in the server
    When the user reloads the current page of the webUI
    Then the user should be redirected to the owncloud login page
Timed out while waiting for element <#user> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10005ms)
undefined    ✖ failed
      Timed out while waiting for element <#user> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10005ms)
          at Proxy.waitTillLoaded (/var/www/owncloud/web/tests/acceptance/pageObjects/ownCloudLoginPage.js:56:20)
          at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/loginContext.js:129:42)

  Result: FAILED
```

This is in PR #6309 

Investigate what needs adjusting in the tests, and push the fix to that PR branch `bump-sdk`

**Comment by saw-jan** [comment]
In branch https://github.com/owncloud/web/tree/bump-sdk, reloading does not redirect to the login page after the user is deleted.

Steps to reproduce:
1. create a user `Alice` in the server
2. from web, log in with user `Alice`
3. delete user `Alice` from the server
4. reload the web

CC @phil-davis @kulmann

**Comment by phil-davis** [comment]
Is it a real failure, that needs web code adjusting?
Or is there any change to the UI elements that just needs the test code to be adjusted?

**Comment by saw-jan** [comment]
yeah, I can reproduce it manually.
I think either `web` or `sdk` needs some fixing.
And I don't think we need any changes in test code.

**Comment by phil-davis** [comment]
@kulmann ^

**Comment by saw-jan** [comment]
> @saw-jan can you explain a bit more what needs to be fixed in the SDK?

@fschade I really don't know the fix. It's just my speculation that since the user is not redirected to the login page after deleting logged in user and refreshing the page, either web or sdk might need some fixes.

**Comment by kulmann** [comment]
I rebased the branch. Can't reproduce it manually and the tests are succeeding in local dockerized CI. Let's see what CI says.

@saw-jan thank you for taking the time! Next time, could you add browser console logs to such an analysis?

**Comment by saw-jan** [comment]
Ohh!
What might be the issue?
I still can reproduce on my local machine.

When reloading after user has been deleted, I get this browser log:
![console-log](https://user-images.githubusercontent.com/52366632/151804844-4af85312-d9cc-4a55-92d8-b40d5fb1e7fe.png)

oC10 config:
version: `ownCloud 10.9.2 prealpha (git)` commit: `75979aa57579c0d3810db056bda2668b697ae120`
config:
```php
<?php
$CONFIG = array (
  'instanceid' => 'oc9qt9g5pb6l',
  'passwordsalt' => '2DekKZxN/VKSyrpK/7LEmfQV+pvCrJ',
  'secret' => 'K/n17K95ufI1KamnLpJCNstRWXoPqPrw3pbNt65ELHv0udlS',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/mnt/workspace/www/core/data',
  'overwrite.cli.url' => 'http://localhost/core',
  'dbtype' => 'mysql',
  'version' => '10.9.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'owncloud',
  'dbpassword' => 'owncloud',
  'allow_user_to_change_mail_address' => '',
  'logtimezone' => 'UTC',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/mnt/workspace/www/core/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/mnt/workspace/www/core/apps-external',
      'url' => '/apps-external',
      'writable' => true,
    ),
  ),
  'cors.allowed-domains' => 
  array (
    0 => 'http://localhost:9100',
  ),
  'htaccess.RewriteBase' => '/core/',
  'web.baseUrl' => 'http://localhost:9100',
  'web.rewriteLinks' => true,
  'installed' => true,
  'csrf.disabled' => true,
  'enable_previews' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'sharing.federation.allowHttpFallback' => true,
  'log_type' => 'owncloud',
  'skeletondirectory' => '/mnt/workspace/www/core/apps/testing/data/tinySkeleton',
);
```

**Comment by kulmann** [comment]
Thank you for the additional clues @saw-jan - that helped me reproduce it and fix it. Was an issue in the SDK with failing network requests not leading to a rejected promise but exiting the application entirely instead. Fixed it with https://github.com/owncloud/owncloud-sdk/pull/978 - locally I always get back to the login page now with the scenario/steps that you described. Let's see if CI succeeds now in https://github.com/owncloud/web/pull/6309
I'll add this issue to the `Fixes` section in the PR so it gets closed on merge.
