### ISSUE TITLE
"empty trashbin" as capability

### ISSUE THREAD

**Issue by diocas** [owncloud/web#6324]
At CERN we want to disable the empty trashbin button to avoid the permanent delete action (per policy decision).
Right now we have commented the buttons, but can we add this as a capability?

**Comment by pascalwengerter** [comment]
Capabilities are being handled by the backend, so we'd have to add some sort of functionality to oCIS/Reva ("only" hiding the button in the frontend could be made configurable via the `config.json`  in `web`, but then users could theoretically still send e.g. CURL requests to delete files/folders 😅 )
Also needs a product decision so adding @kulmann and @tbsbdr
