### ISSUE TITLE
Breadcrumb disappears in personal view after going to spaces

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#6326]
### Steps to reproduce
1. Go to personal view
2a. Go to spaces (or deleted files) and change back to personal view, breadcrumb is not displays
2b Go to shared views, breadcrumb is displayed. Reload, it disappears.

### Expected behaviour
Breadcrumb is displayed in personal view
Breadcrumb is not displayed in other views

Test in https://ocis.ocis-web.latest.owncloud.works/ on 27.01.22

![breadcrumb](https://user-images.githubusercontent.com/7430156/151363634-f9fe8cd8-95b4-4c2e-bd8a-f259e1d79fb0.gif)

**Comment by kulmann** [comment]
Briefly looked into this today. Seems like the location checks that restrict the breadcrumbs to certain active routes are not reactive / not updated on route change.
