### ISSUE TITLE
Properly document configuration and bundling options

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6329]
### Expected behaviour
As an admin user or possible contributor, I want a centralized place where I can educate myself about configuration options in a clear and structured manner

### Actual behaviour
Currently, configuration (config.json) and bundling (= Rollup) options can only be found in various places in the source code itself (e.g. `config/config.json*`, `dev/docker/*.web.config.json`, drone configs, `rollup.config.js`, ...) and lack general discoverability for people that are not familiar with the codebase or the used tools already

**Comment by Divyansh013** [comment]
Hey, I would like to take up the issue. Please let me know if it's open

**Comment by pascalwengerter** [comment]
> Hey, I would like to take up the issue. Please let me know if it's open

@Divyansh013 please go ahead an ping me or one of the others maintainers if questions arise - looking forward to your PR:)

**Comment by pascalwengerter** [comment]
Closing here since https://owncloud.dev/clients/web/ has received quite some love in the last years
