### ISSUE TITLE
Don't show unix timestamp 0 as "52 years ago"

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#6342]
### Steps to reproduce
1. Log in to an oCIS instance (which has a `Shares` folder with a last modified date of unix timestamp 0)

### Expected behaviour
Don't show `52 years ago` as a relative date in the UI

### Actual behaviour
`Shares` folder shows `52 years ago` as last modified date

**Comment by pascalwengerter** [comment]
Might be worth thinking about if we want to treat the `Shares` folder differently from all the other resources, e.g. also exclude it from "Select all"

**Comment by phil-davis** [comment]
Note https://github.com/owncloud/web/issues/6305#issuecomment-1022217793

There was also some discussion in #6305 about whether to implement "special knowledge" about the `Shares` folder on oCIS.

**Comment by JanAckermann** [comment]
@kulmann does this error still exist? As the mentioned shares folder is not there anymore

**Comment by JanAckermann** [comment]
Closing for now, please reopen if issue persits
