### ISSUE TITLE
empty subfolder inside a folder to be uploaded is not created on the server

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#6348]
### Description
When we try to upload a folder containing empty subfolders, the folder gets uploaded to the server but the empty folders are neglected.

### Steps to reproduce
1. create `/parent/sub1/lorem.txt` locally
1. create `/parent/sub2/` locally _(empty subfolder)_
1. create a user `uu1` and login to the web UI
1. upload `/parent` using the web UI

### Expected behaviour
For user `uu1` (works fine with oc10 classic UI)
- `/parent` should exist 
- `/parent/sub1` should exist
- `/parent/sub1/lorem.txt` should exist
- `/parent/sub2` should exist

### Actual behaviour
- `/parent` exists
- `/parent/sub1` exists
- `/parent/sub1/lorem.txt` exists
- `/parent/sub2` **does not** exist

### Environment general
**Operating system**: ubuntu

**Backend (ownCloud Core or Infinite Scale)**: oC core

**Comment by ScharfViktor** [comment]
Closed in favo https://github.com/owncloud/web/issues/6348
