### ISSUE TITLE
Files details page does not update after file version is restored without refresh

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#6361]
### Steps to reproduce
1. Create a file `version.txt` with content `version 1`
2. Upload a file `version.txt` with content `new version`
3. Restore the old version of file

### Expected behaviour
The UI must be updated with the information of the older version of file without refreshing the page

### Actual behaviour
Before restoring the older version, (file size of current version is 29B, modified 1 day ago on file details page, file size of older version is 19B, time 20 min on versions sidebar)
![version_before_restore](https://user-images.githubusercontent.com/8559121/152336830-8930492e-0370-4122-b5f4-de1d036cd5b6.png)

After restoring the older version, (file size of current version is 29B, modified 1 day ago on file details page is not updated, file size of older version is 29B, time 1 day on versions sidebar which is updated)
![version_after_restore](https://user-images.githubusercontent.com/8559121/152336839-93afc54c-e0fb-4571-9548-ed76c6bb6a56.png)

After refreshing the page, (file size of current version is 19B, modified 30 min ago on file details page is now updated)
![version_after_refresh](https://user-images.githubusercontent.com/8559121/152338046-1f99a565-d5a9-4169-92cf-85601d0739cf.png)

### Environment general
**Operating system**: Linux Ubuntu 20.04

### Environment ownCloud Core
**Web server:** latest master

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/7469
