### ISSUE TITLE
Make currentFileContext optional in closeApp()

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6371]
When closing an extension that isn't design to revolve around a single file (think: Media-Viewer, Markdown-Editor), using `closeApp()` throws an error

https://github.com/owncloud/web/blob/51734ef35ffe70f9e3d2560d281534f5ff513ade/packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts#L33

**Comment by dschmidt** [comment]
Are we talking about a concrete app?

What would you expect to happen instead?
If not needed, noone forces you to use the composable :)

**Comment by JanAckermann** [comment]
closing, as no reply since and hence no bug is known according to the issue ticket
