### ISSUE TITLE
Acceptance tests don't work out of the box locally anymore

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6388]
### Steps to reproduce
1. Try to run acceptance tests locally as suggested in https://owncloud.dev/clients/web/testing/testing/#run-acceptance-tests
2. They fail with `Error: ENOENT: no such file or directory, open '/Users/pascalwengerter/Projects/owncloud/web/tests/acceptance/report/cucumber_report.json'`
3. Remove `-f json:report/cucumber_report.json` from the commands in the tests/acceptance/package.json to make them work locally

### Expected behaviour
Works out of the box

### Actual behaviour
Modifications necessary

**Comment by kulmann** [comment]
You can also touch the file I guess, but that doesn't make the bug less of an issue.
