### ISSUE TITLE
e2e tests. Create public link story

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6389]
New feature: something like publicLinkToFolderJourney.feature

steps:
- [ ] Alice uploads folder with file. New->Upload folder. ( blocked until this issue is solved https://github.com/microsoft/playwright/issues/6854)
- [x] Alice creates public link to folder. fills in: link name, password, expiration date, role: uploader https://github.com/owncloud/web/pull/6422
- [x] unauthorized user opens link. he cannot see file (which was in the folder) (https://github.com/owncloud/web/pull/6461)
- [x] unauthorized user uploads new file (https://github.com/owncloud/web/pull/6461)
- [x] unauthorized user refreshes page. (page is empty) (https://github.com/owncloud/web/pull/6461)
- [x] Alice can see new file in folder
- [x] Alice downloads 2 files as tar. https://github.com/owncloud/web/pull/6541
- [x] Alice changes role to editor, change expiration date https://github.com/owncloud/web/pull/6557
- [x] unauthorized user refreshes old link https://github.com/owncloud/web/pull/6889
- [x] unauthorized user open new link (can see two files) https://github.com/owncloud/web/pull/6889
- [x] unauthorized user can download, upload and rename file https://github.com/owncloud/web/pull/6889
- [x] Alice deletes link https://github.com/owncloud/web/pull/6889
- [x] unauthorized user cannot open old link https://github.com/owncloud/web/pull/6889

**Comment by amrita-shrestha** [comment]
Blocked until this issue resolved https://github.com/owncloud/web/issues/6478

**Comment by SwikritiT** [comment]
@pascalwengerter @fschade @ScharfViktor 
The step `Alice downloads 2 files as tar.`  has a bug in OC10 backend 

## Issue here
https://github.com/owncloud/web/issues/6239

Bug demonstration tests in PR: https://github.com/owncloud/web/pull/6541
the test is failing in `OC10` backend

So according to https://github.com/owncloud/web/issues/6385#issuecomment-1056286215 
that PR will be open and in a blocked state until the issue is fixed

**Comment by kulmann** [comment]
> @pascalwengerter @fschade @ScharfViktor @individual-it The step `Alice downloads 2 files as tar.` has a bug in OC10 backend
> 
> ## Issue here
> #6239
> 
> Bug demonstration tests in PR: #6541 the test is failing in `OC10` backend
> 
> So according to [#6385 (comment)](https://github.com/owncloud/web/issues/6385#issuecomment-1056286215) that PR will be open and in a blocked state until the issue is fixed

Additional context: that's not a bug, but a missing feature and one example where an oc10 backend doesn't behave the same as an ocis backend. Another prominent example for such a case is ocis having spaces while oc10 doesn't have spaces. Or oc10 having favorites while ocis is not yet there. Needs another approach here, because it's unclear when we'll schedule the archive download implementation for oc10 backends.

**Comment by pascalwengerter** [comment]
My inital idea was to separate user stories into `oc10`, `ocis` (having tar download & spaces) and `shared/common/both/...`. Any objections?

**Comment by ScharfViktor** [comment]
> > @pascalwengerter @fschade @ScharfViktor @individual-it The step `Alice downloads 2 files as tar.` has a bug in OC10 backend
> > ## Issue here
> > #6239
> > Bug demonstration tests in PR: #6541 the test is failing in `OC10` backend
> > So according to [#6385 (comment)](https://github.com/owncloud/web/issues/6385#issuecomment-1056286215) that PR will be open and in a blocked state until the issue is fixed
> 
> Additional context: that's not a bug, but a missing feature and one example where an oc10 backend doesn't behave the same as an ocis backend. Another prominent example for such a case is ocis having spaces while oc10 doesn't have spaces. Or oc10 having favorites while ocis is not yet there. Needs another approach here, because it's unclear when we'll schedule the archive download implementation for oc10 backends.

I honestly thought it was a bug because in oс10 in the old web we have the ability to download the tar. for me the example of spaces is not similar since this is a new feature and was not present in os10

**Comment by ScharfViktor** [comment]
If we do not know when it will be implemented (download tar in web with oc10), it is worth not to lock this test and use it only with ocis. something like https://github.com/owncloud/web/blob/master/tests/e2e/cucumber/step_definitions/api.ts#L24-L25

**Comment by SwikritiT** [comment]
There's still one step that needs to be implemented `Alice uploads the folder with the file. New->Upload folder` but it's blocked until that feature is available in the playwright, so putting this in backlog

**Comment by ScharfViktor** [comment]
We have opened issue for uploading folder https://github.com/owncloud/web/issues/2222

we can confidently close issue. Great job)) Thanks
