### ISSUE TITLE
Closing an app doesn't redirect to the corresponding folder

### ISSUE THREAD

**Issue by diocas** [owncloud/web#6390]
`navigateToContext` (in useAppNavigation.ts) is not redirecting to the corresponding folder.

**Comment by kulmann** [comment]
We merged https://github.com/owncloud/web/pull/6331 today - that was supposed to fix it. Could you check again with that state of the web codebase?

**Comment by diocas** [comment]
I kept delaying posting this bug and when I finally did it, it was already fixed... Good job guys! xD
