### ISSUE TITLE
Show space thumbnail in front of breadcrumbs

### ISSUE THREAD

**Issue by butonic** [owncloud/web#6396]
As a user when navigating through a space I want to have a visual indicator of the space I am currently navigating.

When a space has an image set I'd like to see a thumbnail of it in front of the breadcrumbs, so it reminds me that the breadcrumbs are relative to that space.

It could also carry the alias and description when hovering over it / whatever best fits accessibility.

If no image is set we can fall back as we fall back with avatars, the first letter of the space alias with a colored shape. Maybe box with rouned corners to distinguish it from avatar circles?

**Comment by tbsbdr** [comment]
This is how i could look like. imo okay, but nice to have:

![Single Space - manager permission - no image, no description, no subtitle](https://user-images.githubusercontent.com/26610733/153192516-f0ba162e-de24-44bd-bb07-1fc7b3cb0eec.png)

**Comment by JanAckermann** [comment]
The initial request was:

> When a space has an image set I'd like to see a thumbnail of it in **front of the breadcrumbs**, so it reminds me that the breadcrumbs are relative to that space.

Which I thought was having a visual anchor, that we are in spaces, so I think I misunderstood that.


Overall, I don't see any advantage then of having the thumbnail there.

**Comment by butonic** [comment]
It's all about the eye candy. Personally, I'd even get rid of `Spaces > ` ... the space thumbnail, maybe with the alias IMO is sufficient.
Sth like `[o] Project Moon > relative > path`?

**Comment by tbsbdr** [comment]
Naa, `Spaces >` needs to stay in the breadcrumb - it's really useful for people to navigate and for orientation at a glance "where am I?".
It looks better than I expected, but its still nice-to-have. I'll show it some test people to figure out if it adds (eyecandy) value. 
(updated screenshot: added "Conferences" as last node)

**Comment by JanAckermann** [comment]
IHMO this is not eye candy and brings more of restlessness in the overall clean appearance :(

**Comment by JanAckermann** [comment]
Closing as spaces are already integrated very well. 
We show "spaces" in breadcrumbs already. 

I don't think this eye candy is needed nor requested by any other.
