### ISSUE TITLE
Discussion: Should we abort the E2E tests if we have console errors/warnings

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6397]
Extracted from #6052, suggested by @ScharfViktor. I could imagine this being both a blessing and a curse, maybe we can add a config option to run it in an "unforgiving mode" on releases?

**Comment by kulmann** [comment]
@ScharfViktor could you give an update about the current state? I see an `"earlyFail": True,` for all 3 e2e pipelines in the drone starlark file, nothing configurable. Any plans or do you want to close this as `not planned`?

**Comment by ScharfViktor** [comment]
> @ScharfViktor could you give an update about the current state? I see an `"earlyFail": True,` for all 3 e2e pipelines in the drone starlark file, nothing configurable. Any plans or do you want to close this as `not planned`?

it's not set up yet, but it could be very useful.

example here https://github.com/owncloud/web/pull/10993/files#diff-8aff85478bb51435527081e7e8bac167fe25b30b35aa64106a5feb63086f4229R25-R34

I can catch uncaught exception or or all the errors that come up in the console (But there will be normal errors like 404 or 401 as well) 

here's an example of running the test und finding error in the CI: 
- `user1` creates `f1/file.txt`
- `user1` shares `f1` with edit role
- `user2` renames `file.txt` 

Result: `user1` gets error `Cannot read properties of undefined (reading 'storageId')`
<img width="2555" alt="Screenshot 2024-06-04 at 14 09 26" src="https://github.com/owncloud/web/assets/84779829/496e16d4-ba7c-45ba-a0eb-fd328c02c677">

**Comment by kulmann** [comment]
Ah, I think I misunderstood the issue. Now I got it, thank you!

Failing tests on uncaught errors sounds like a good idea to me - happy to see this coming to the e2e code base. :-)
Like you said, failing on all errors doesn't seem to be an option, mostly for 401 and 404 that just happen in the normal application flow.

**Comment by ScharfViktor** [comment]
closed as completed https://github.com/owncloud/web/pull/10993
