### ISSUE TITLE
Icon for Draw files (.*odg)

### ISSUE THREAD

**Issue by merttumer** [owncloud/web#6416]
We recently made this pr: https://github.com/owncloud/richdocuments/pull/456 which adds a support for opening .odg files with Collabora Online. But we noticed that there's no icon for the .odg files and it just displayed as regular files.

**Comment by pascalwengerter** [comment]
Hey @merttumer, thanks for the suggestion! As far as I know CERN (@elizavetaRa @diocas) are planning to add new fileType icons (and perhaps also one for draw documents) to [our design system](https://github.com/owncloud/owncloud-design-system/) sometime soon, let's check back with them!

Relevant file is in https://github.com/owncloud/core/blob/master/core/img/filetypes/x-office-drawing.svg

**Comment by tbsbdr** [comment]
@elizavetaRa any news on that 👆 ?

**Comment by elizavetaRa** [comment]
@tbsbdr We added some icons here already and some more are planed to come soon. I will create a pr for this.
https://github.com/cernbox/owncloud-design-system/commit/fbd99a2ff8e83dee4187e093fd960d25fdb4579f

**Comment by pascalwengerter** [comment]
> @tbsbdr We added some icons here already and some more are planed to come soon. I will create a pr for this. [cernbox/owncloud-design-system@fbd99a2](https://github.com/cernbox/owncloud-design-system/commit/fbd99a2ff8e83dee4187e093fd960d25fdb4579f)

Yes please :) looking forward, and should be easily merged&published!

**Comment by pascalwengerter** [comment]
@merttumer could you check https://github.com/cernbox/owncloud-design-system/pull/222/files?short_path=96c0611#diff-96c0611a06530f1b881159642cf99d4ce92f33d212670b795e5e0548442bdde6 and see if it suits your needs? (Icon will be added in the CERN fork of the ownCloud design system first and then merged upstream, coming to the `web` codebase before the next release towards end of next week)

Also, what is the license situation with your icons? We've cleaned up our codebase and are a bit wary to not introduce any offenses again :)

**Comment by merttumer** [comment]
Unfortunately, .odg files are still displayed as black file icon 
![image](https://user-images.githubusercontent.com/6226481/157867830-2afe50c8-57c9-4398-ad8a-e1b13b0b12c9.png)

**Comment by pedropintosilva** [comment]
Hi there : ) thanks for the heads up @pascalwengerter , (@merttumer has ask me if I take a look at this and try to help)
So I have checked @elizavetaRa 's patch and they look good  :heart: 

Generally speaking I do not see any blocker here. Nevertheless and if I might share bit of context:

I would say that for the specific ODG file type I'm afraid [resource-type-graphic-fill.svg](https://github.com/cernbox/owncloud-design-system/pull/222/files?short_path=96c0611#diff-96c0611a06530f1b881159642cf99d4ce92f33d212670b795e5e0548442bdde6) might be a bit misleading. Even though when working with ODG we have the cool feature of those connectors it is not only for diagrams and there are many other use cases where users/students create drawings or documents such as one page flyer or other promotional materials. Plus it can start to get a bit confusing if we have 3 icons referencing diagrams (resource-type-drawio-fill, resource-type-graphic-fill.svg, and this one)

I would propose to play around with the main elements present in the original [mime-type icon](https://wiki.documentfoundation.org/Design/Mimetype_Icons) while trying to fit it in the current design system : ) here is my quick attempt to do so:

[resource-type-draw-fill.svg](https://user-images.githubusercontent.com/65948705/157911211-9669dc69-c2db-40bd-a042-7f8cd33e87af.svg)

What do you think?

**Comment by pascalwengerter** [comment]
Reopening since it hasn't landed in `web` yet, also would like to get a positive reply from @pedropintosilva before closing this

**Comment by pascalwengerter** [comment]
@pedropintosilva @elizavetaRa FYI :)

![Screenshot 2022-03-15 at 14-35-03 Personal - ownCloud](https://user-images.githubusercontent.com/16822008/158389205-d12a8c02-90a3-4088-923f-e8ee12b6daeb.png)

**Comment by pascalwengerter** [comment]
Hey,



thanks for getting back to me this quickly. My question was not about whether the issue can be closed (it can't, we'll need to update our design system first) but more about the license around using your SVG file :) could you clarify that in the issue (see my last question)?



Best,
Pascal



-----Original message-----
