### ISSUE TITLE
[oCIS] Sometimes `Shares` folder can have public link share

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#6419]
## Describe the bug
Basically, `Shares` folder shouldn't be allowed to share with any users and groups or by public link.
But sometimes it can be shared.

![debugSuite-try_feature-L10](https://user-images.githubusercontent.com/52366632/151949564-af7fed0e-59d5-4f18-b0a0-a75f5ac559b7.png)

Hard to reproduce manually.
This scenario has sometimes caused an intermittent test failure: see https://github.com/owncloud/web/issues/6321

## Steps to reproduce
Duplicate and Run `webUISharingPublicBasic/publicLinkCreate.feature:190` test 10-20 times.

## Expected behavior
`You don't have permission to share this folder.` message

## Actual behavior
Public share can be created

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
OCIS_VERSION=latest from git (`c6d2fdeb044aa54da8c95b7c2c5ce33ff83f49d0`)
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by SwikritiT** [comment]
Sometimes it can be shared as well the reason behind this https://github.com/owncloud/web/issues/6341 failure
![Screenshot from 2022-02-17 16-23-09](https://user-images.githubusercontent.com/41103328/154460328-114b76b6-db8c-4046-bd6e-4001fe44f0e3.png)

**Comment by phil-davis** [comment]
This causes intermittent fails in CI.
@kulmann @pascalwengerter any thoughts about how this can possibly happen?

**Comment by phil-davis** [comment]
Also see report and investigations in ocis issue https://github.com/owncloud/ocis/issues/2981

**Comment by phil-davis** [comment]
https://github.com/owncloud/ocis/issues/2981#issuecomment-1047555842

"should we skip the test(s)?"

@individual-it @kiranparajuli589 Let's wait and see if @kulmann or @pascalwengerter have any good ideas to make the behavior reliable. If it's not quick to fix, then I guess we will have to skip the test(s).

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/23076/58/15
`webUISharingInternalUsers/shareWithUsers.feature:342` failed in CI on Sunday morning.

**Comment by SwikritiT** [comment]
I noticed that while trying to share the shares folder sometimes the `permission` is set to `SRDNVCK` so while doing the `canShare` check will return `true`https://github.com/owncloud/web/blob/db72a9b34a84fd9ed65155abbac30ebbfd046653/packages/web-app-files/src/helpers/resources.js#L90-L92 .
 In the normal condition, the `permission` is set to `S` and the function will return `false`

**Comment by individual-it** [comment]
I guess we can close this for the same reason as https://github.com/owncloud/web/issues/6321#issuecomment-1057813530

CC @kulmann
