### ISSUE TITLE
Archiver in the public link doesn't work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6423]
web: 4.9.0
ocis: 1.16.0 with docker

Steps: 

- admin creates folder with two files
- admin creates public link. Role doesn't mater
- open public link. choose 2 files and click download

Expected result: files downloaded as download.tar. The same behavior if you download folder

Actual result: 

https://user-images.githubusercontent.com/84779829/153577459-93bff2cf-d21a-4d31-b965-3766d6473979.mov

**Comment by kulmann** [comment]
Could you add backend logs please? Anything in the ocis logs that looks like an error?

**Comment by ScharfViktor** [comment]
Yes, of course. forgot to do it right away.


`{"level":"error","service":"storage","pkg":"rhttp","traceid":"00000000000000000000000000000000","path":"/public/UvLBChmVDJiSCYG","error":"rpc error: code = Unknown desc = error listing shares: rpc error: code = PermissionDenied desc = auth: core access token is invalid","time":"2022-02-11T14:42:58Z","message":"propfindResponse: couldn't list public shares"}`

**Comment by kulmann** [comment]
> Interestingly, the archiver download isn't even offered as an option in the UI on password protected links 🤔

Could you check if the capabilities request was made and successful? If capabilities are not available => archiver is not available because it's announced via capabilities.

**Comment by pascalwengerter** [comment]
> > Interestingly, the archiver download isn't even offered as an option in the UI on password protected links 🤔
> 
> Could you check if the capabilities request was made and successful? If capabilities are not available => archiver is not available because it's announced via capabilities.

Can't see the capability request in either case and still, I see the download button in non-password-protected links for folders/multiple items

**Comment by pascalwengerter** [comment]
> > > Interestingly, the archiver download isn't even offered as an option in the UI on password protected links 🤔
> > 
> > 
> > Could you check if the capabilities request was made and successful? If capabilities are not available => archiver is not available because it's announced via capabilities.
> 
> Can't see the capability request in either case and still, I see the download button in non-password-protected links for folders/multiple items

Also: When using a non-password-protected link, it only loads the capabilities on initial pageload, successive reloads don't fetch them anymore

**Comment by elizavetaRa** [comment]
@kulmann Any news on this issue?

**Comment by kulmann** [comment]
The capability loading issues are resolved, but we still disable the archiver for password protected public links here https://github.com/owncloud/web/blob/1ad492a401365ad2ca10dc9def57130be0febd49/packages/web-runtime/src/services/auth/publicLinkManager.ts#L125

I checked locally what happens when I allow on the archiver on password protected public links - throws a 401 from the backend. I'll have to investigate what happens there.
