### ISSUE TITLE
Upload folder (drag and drop) doesn't work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6426]
web: v5.0.0-rc
ocis: 1.16.0 with docker

Steps:

- User tries to upload a folder (drag and drop)

Actual result: `MKCOL https://host.docker.internal:9200/remote.php/dav//New%20folder1/` 404 Not found
`<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns"><s:exception>Sabre\DAV\Exception\NotFound</s:exception><s:message>File not found in root</s:message></d:error>`

https://user-images.githubusercontent.com/84779829/153602456-15ea6ec3-b4b4-4c49-a66b-3eca67932207.mov

**Comment by kulmann** [comment]
Fixed by https://github.com/owncloud/web/pull/6424/commits/a7608a57d8bb2e9883e34d265132f5e0c66d1533 - the drag'n'drop folder upload didn't use proper webdav v2 paths after owncloud-sdk update to v2.0.0.
