### ISSUE TITLE
Adding of new routes fails for CERNbox

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#6428]
Adding of new routes doesn't work
### Steps to reproduce
1. Create a new route "/test" and a locationCommon in common.ts 
2. Add routeComponent in router.ts
3. Add nav-item in index.js
4. Create test view compenent 

### Expected behaviour
The route resolves with the corresponding view

### Actual behaviour
The route "files-common-test" is not resolving

### Environment general
branch: https://github.com/cernbox/web/tree/diogo

**Comment by kulmann** [comment]
cc @diocas

**Comment by diocas** [comment]
Yup, it fixes it :) (I had the same issue with our web extensions and also took me a while to see this change)
