### ISSUE TITLE
Public link. Change role doesn't work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6429]
web: 4.9.0
ocis: 1.16.0 with docker

Steps:

- admin creates folder 
- admin creates public link with role uploader
- open public link
- admin changes role to editor. Request PUT `https://host.docker.internal:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/DIXZPcaxJYtctTz` - 200 OK
- refresh old. 

Result: rights have not changed

- copy new new link and open again

Result: rights have not changed

**Comment by pascalwengerter** [comment]
Investigated, interestingly the permissions change seems to be fine (PUT request goes through as expected, share creator can see the changes upon page reload on his UI). The public link however resolves from (e.g.) `https://localhost:9200/#/s/eufNbYhpPVzcEWJ` to `https://localhost:9200/#/files/public/drop/eufNbYhpPVzcEWJ` (with a hardcoded *drop* in the URL) and is stuck in the uploader view

**Comment by kulmann** [comment]
I fixed the redirect in dc6f1d65dff4a23c08e256d28c9f388c2c2efc7e but it seems like the caching in oCIS is too aggressive. I don't get updated share permissions when fetching a single public link upon loading the public link view.
