### ISSUE TITLE
The "Accounts" tab is not available

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6430]
web: v5.0.0-rc
ocis: 1.16.0 with docker

Steps:
- User admin tries to go Accounts tab

Actual result: section not accessiblу

https://user-images.githubusercontent.com/84779829/153615814-afcb5db5-1f5d-4c00-a6a2-53f9af84cf9d.mov

**Comment by pascalwengerter** [comment]
Most likely resolved in https://github.com/owncloud/ocis/pull/2929, not a web issue technically

**Comment by kulmann** [comment]
Will be fixed by https://github.com/owncloud/ocis/pull/3157 - or if we decide to add a compatibility layer for old component definition in routes.
