### ISSUE TITLE
"Shares" overview

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6440]
# Description
## User Stories

* > As a user I want to navigate between "shares with me", "others" and "via link" seamlessly so that I can find the right files quickly.

* > As a user I want an uncluttered left sidebar so that I can orientate and navigate quickly in my ownCloud.

## Value
- **Meet enterprise policies:**  Clear separation of personal files and shared files

## Acceptance Criteria
- Add "Shares" as left sidebar item; on-Click navigates to shared-overview
- Add "Shared with me", "Shared with others" and "Shared via link" as tabs to the Shares-overview 
- Rename `All files` to `Personal`

not in this story: filter options
related: https://github.com/owncloud/web/issues/6448

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] codre review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

![image](https://user-images.githubusercontent.com/26610733/154441117-2482e164-6c87-4326-a3ae-f812b8864c83.png)
![image](https://user-images.githubusercontent.com/26610733/154441246-e1455269-bd28-4387-bfab-f2501ead42a3.png)

**Comment by tbsbdr** [comment]
Added AC "Rename All files to Personal files" please speak up if this changes the story point estimation.

**Comment by tbsbdr** [comment]
Hey Phil, not sure if I understood you correct. Is your main concern, that the wording "Personal files" is misleading, because it contains also shared files?

**Comment by phil-davis** [comment]
> Hi Phil, I'm not sure I've understood you correctly. Is your main concern that the wording "personal files" is misleading because it also includes shared files?

yes

In the top post is: Meet enterprise policies: Clear separation of personal files and shared files

There may/will still be shared files "mixed in" the personal files - any personal files/folders of "Alice" that have been shared by "Alice" herself (the "share owner"). And it is tricky to think how to remove those from a Personal Files view.

Use case:
- the desktop client has synced the following resources to the server for Alice:
  teaching
  teaching/overview.pdf
  teaching/language
  teaching/language/lesson1.pdf
  teaching/language/lesson2.pdf
  teaching/mathematics
  teaching/mathematics/lessonA.pdf
  teaching/mathematics/lessonB.pdf
  teaching/science
  teaching/science/lesson101010.pdf
  teaching/science/lesson101011.pdf
  folder/file.pdf
  shared-top-file.pdf
  top-file.pdf
- Alice shares teaching/mathematics with Brian
- Alice shares teaching/science with Carol
- Alice shares folder/file.pdf with David
- Alice shares shared-top-file.pdf with David
A) When Alice selects "Shared" in the web UI, she sees:

Option 1) structure presented in the same tree as it comes from in the "personal" area
folder "folder/file.pdf"
file "shared-top-file.pdf"
folder "teaching"
and when she browses inside "teaching", she sees folders "mathematics" and "science"

Option 2) structure presented with all shares directly at the top level
folder "folder/file.pdf"
file "shared-top-file.pdf"
folder "mathematics"
folder "science"

B) When Alice selects "Personal files" she sees:
Option 1) see "all personal files"
folder "folder/file.pdf"
file "shared-top-file.pdf"
file "top-file.pdf"
folder "teaching"
and if she browses inside "teaching" she sees all the files and folders:
file "overview.pdf"
folder "language"
folder "mathematics"
folder "science"

Option 2) see only the "really personal files" (those that are not shared at all)
file "top-file.pdf"
folder "teaching"
and if she browses inside "teaching" she sees only the unshared files and folders:
file "overview.pdf"
folder "language"
This option might be confusing for Alice, 

On the client Windows desktop of Alice, she "really" has all the files and folders structured as in (B) (option 1)

If I was implementing this I would need a decision about the things in the above scenario.

**Comment by tbsbdr** [comment]
Ah, okay - got you. Thanks for your words! 
- The basic approach to have a _Clear separation of personal files and shared files_ is, that I won't find any "shared with me" files in my "Personals files" any more. Those will solely live within the Shared endpoint. (https://github.com/owncloud/web/issues/6448)
- Whereas "Shared with others" and "Shared via link" will behave like they do right now: On click of a "shared via link-item", I will jump to the respective Item within the "Personal files" view [or a Space - thats new]).

Please also note https://github.com/owncloud/web/issues/6448

**Comment by phil-davis** [comment]
That sounds fine - technically it is "Clear separation of personal files and received shared files"
As long as developers are clear about that, then the implementation should be well-understood.
