### ISSUE TITLE
Shared with me-view

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6448]
# Description

## User Stories

* > As a user I want to access all files shared with me in one place so that I can effortlessly navigate, control, work with those files.

## Value
- separate personal files by-design from shared files

## Acceptance Criteria
- oc10: stays the same

### oCIS only:
- Use new Web Dav endpoints for "Personal files" and "Shared" space (Graph API / Drives)
- Navigation in the "shared with me view" stays in the view (no change to "Personal files")
- "Shares" folder does not show up in "Personal files"
- Navigating into a subfolder of "Shared with me" hides the Tabs and shows the breadcrumb "Shared" > "Shared with me" > "Subfolder"

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] codre review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

![image](https://user-images.githubusercontent.com/26610733/154445802-eb205f29-7698-4dbc-9b35-df030a231667.png)

**Comment by kulmann** [comment]
Fixed by https://github.com/owncloud/web/pull/6593
