### ISSUE TITLE
Add translations for People-Panel > Roles-Menu

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6460]
### Steps to reproduce
1. Use a browser with "German" set as language
1. login to demo.owncloud.com (-> new Design)
2. Rightclick on a file, choose "share"
3. click on "Als viewer einladen", see roles and descriptions in english

### Expected behaviour
Roles and descriptions should be displayed according to the browser setting (in our example German) 

### Actual behaviour
Roles and descriptions are displayed in english

<img width="519" alt="image" src="https://user-images.githubusercontent.com/26610733/154948752-e936851a-1979-4014-bc17-af527889c701.png">

**Comment by pascalwengerter** [comment]
I did some investigating and from what I've seen gettext doesn't get triggered correctly from inside `*.ts` files 🕵🏽

**Comment by pascalwengerter** [comment]
> I did some investigating and from what I've seen gettext doesn't get triggered correctly from inside `*.ts` files 🕵🏽

Also, seems a bit stale in the used project(s) https://github.com/Polyconseil/vue-gettext/issues/107 and seems to be resolved in its successor https://github.com/jshmrtn/vue3-gettext/issues/4
