### ISSUE TITLE
Account page group membership information is set differently for `ocis` and `oc10`

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#6475]
### Description
Account page group membership information is set differently for `ocis` and `oc10` backend.

### Steps to reproduce
- create a user (without any groups assigned to it)
- log in with the user just created
- visit the account page
- see `Group memberships` information

### Expected
Should have the value `You are not part of any group` (which is true for the "web" with "oc10" backend)

### Actual
**with the "ocis" backend:**
-> has "users" as value
 ![webUIAccount-accountInformation_feature-L10.png](https://cache.owncloud.com/owncloud/web/screenshots/23027/webUIAccount-accountInformation_feature-L10.png) 

-> if the user is assigned to a group `Group1`
 ![webUIAccount-accountInformation_feature-L20.png](https://cache.owncloud.com/owncloud/web/screenshots/23027/webUIAccount-accountInformation_feature-L20.png) 

_Originally posted by @kiranparajuli589 in https://github.com/owncloud/web/pull/6473#issuecomment-1049542770_

**Comment by kiranparajuli589** [comment]
Is this expected and we modify the test code or should this be the same with any backend?
cc @individual-it @phil-davis @kulmann @pascalwengerter

**Comment by kulmann** [comment]
> Is this expected and we modify the test code or should this be the same with any backend?
> cc @individual-it @phil-davis @kulmann @pascalwengerter

The web ui has no control over the initial group assignments. Users in ocis are by default assigned to the `users` group, for web we have to take that as a given. Can you point me to places where this is relevant in tests? Might be easier to write unit tests and get rid of problematic acceptance tests if there actually is something that makes trouble.

**Comment by kiranparajuli589** [comment]
> Can you point me to places where this is relevant in tests? Might be easier to write unit tests and get rid of problematic acceptance tests if there actually is something that makes trouble.

acceptance tests are covered at https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIAccount/accountInformation.feature#L10

**Comment by individual-it** [comment]
ToDo:
 - [ ] change the acceptance tests to only check if the page renders
 - [ ] check and improve unit tests
