### ISSUE TITLE
Logging out doesn't work with the latest oCIS server

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#6479]
### Steps to reproduce
1. Log in to the web (with oCIS server)
2. Log out

### Expected behaviour
expected to be logged out and redirected to  the login page

### Actual behaviour
After log out, the page is blank (doesn't redirect to the login page), and files page can be accessed without entering  username and password

SR: 
https://user-images.githubusercontent.com/52366632/155514655-05546cfd-1e93-4d1c-8ca2-f667f0d5ecf8.mp4

### Environment general
Backend: `oCIS`
Version: `master branch git (c87176200)`

**Comment by phil-davis** [comment]
@pascalwengerter also noticed this - issue https://github.com/owncloud/ocis/issues/3237

Someone choose which issue to close and which to leave open.

**Comment by pascalwengerter** [comment]
I'll close here, don't see why this should be a frontend issue :) but thanks for keeping your eyes open & creating an issue!
