### ISSUE TITLE
Renaming object via hamburger icon does't work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6516]
web: branch v5.2.0-rc.3:
ocis: docker v.1.17.0 

Steps:
- admin creates folder
- admin tries to rename folder via hamburger icon 

Expected: succufuly 
Actual: method `https://localhost:9200/remote.php/dav/Shares` is used instead of `https://localhost:9200/remote.php/dav/files/marie/Shares`

![Screenshot 2022-03-03 at 12 20 09](https://user-images.githubusercontent.com/84779829/156556595-3ddd6009-504f-4bd6-825a-aa8cd530a364.png)

https://user-images.githubusercontent.com/84779829/156556640-ad50b32c-969a-4254-8a98-3ba07a4433bd.mov

**Comment by pascalwengerter** [comment]
Can confirm this issue, adding it to the fastlane
