### ISSUE TITLE
User queries are not cancelled

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#6517]
### Steps to reproduce
1. Have a large user base in oCIS or the LDAP it is using -> eg. a query time ~ 10 seconds
2. share a file with another user
3. take your time to enter the name (more than the debounce interval per character)

### Expected behaviour
There is only one user query active at a time.

### Actual behaviour
There are many concurrent and outdated queries going on and put stress on the user backend.

![image](https://user-images.githubusercontent.com/34452982/156558738-13c3f336-ea3b-4c4e-a0f6-30b34861b3ac.png)

### Environment general
**Operating system**:

**Backend (ownCloud Core or Infinite Scale)**:

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### ownCloud Infinite Scale
**Version:** 1.17.0

### ownCloud Web
**Version:** 5.1.0

**Comment by jacob-nv** [comment]
I don't really see much possibility of how to deal with it without being able to pass signal and being able to abort calls.
This doesn't seem to be possible with owncloud-sdk

**Comment by dschmidt** [comment]
> I don't really see much possibility of how to deal with it without being able to pass signal and being able to abort calls. This doesn't seem to be possible with owncloud-sdk

Agreed, we plan on getting rid of owncloud-sdk anyway tho. So yes, not actionable on its own, but we need to keep this in mind when replacing owncloud-sdk

**Comment by JanAckermann** [comment]
Hopefully we can migrate those to useTask and cancel them, otherwise 
abortSignal might be the way to go with axios
