### ISSUE TITLE
Inject javascript into markDown

### ISSUE THREAD

**Issue by fschade** [owncloud/web#6526]
### Steps to reproduce
1. create space
2. edit description
3. add `[link](javascript:alert('aaa'))` as content
4. click the link in the rendered markdown

### Expected behaviour
web should prevent to inject javascript or other possible dynamic contents.

### Actual behaviour
javascript can be injected and executed from/for all space members

### Solution
for now we sanitize the md rendered content  and restrict those options, as a long term goal the backend also should handle those situations and strip out potential code parts.

**Comment by C0rby** [comment]
> as a long term goal the backend also should handle those situations and strip out potential code parts.

I don't think that this is necessary.
