### ISSUE TITLE
Items are listed in non-natural sortorder

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6532]
### Steps to reproduce
1. go to demo.owncloud.com
2. upload 15 files with filename "Nature n+1.jpg"
3. Sort by filename

### Expected behaviour
files should be listed like one would count up

- Nature 1.jpg
- Nature 2.jpg
- Nature 3.jpg
- Nature 4.jpg
- Nature 5.jpg
- ...
- Nature 9.jpg
- Nature 10.jpg
- Nature 11.jpg
- ...

### Actual behaviour
Files are listed in alphabetical order:
- Nature 1.jpg
- Nature 10.jpg
- Nature 11.jpg
- Nature 12.jpg
- Nature 13.jpg
- Nature 14.jpg
- Nature 2.jpg
- Nature 3.jpg
- ...

<img width="3008" alt="image" src="https://user-images.githubusercontent.com/26610733/156802509-3fa44d34-5c5d-4d37-bbf6-6495a1f8ac6e.png">

(Labeled it as a bug as I think this is kind of a regression iirc)

**Comment by phil-davis** [comment]
Note: it looks like the oC10 "traditional" web UI does implement the "natural sort order":
![Files - ownCloud - sort-order](https://user-images.githubusercontent.com/1535615/157238553-d92320b9-1b5d-453f-9823-ab05b220e8bd.png)

So this is a feature missing from "web".

**Comment by tbsbdr** [comment]
Correct. And iirc we had natural sort order already in web as well
