### ISSUE TITLE
Batch action download of files not available in OC10 backend

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6542]
### Steps to reproduce
1. Log in as a user 'Alice'
2. Upload two files 
3. Select both files 

### Expected behaviour 
A download button should be visible and it should be possible to download the files as `download.tar` as in ocis
![ocisDownload](https://user-images.githubusercontent.com/41103328/157013185-ac8a2dfd-e9ac-446e-8ebb-b29a41824f7a.png)

### Actual behaviour
No Download button visible in OC10 backend
![oc10Download](https://user-images.githubusercontent.com/41103328/157013326-a375670a-7fc5-422e-bbd3-821e8ffb5baa.png)

The download button is visible in the old design and the files can be downloaded as `download.zip`

![OC10old](https://user-images.githubusercontent.com/41103328/157013733-7c264959-9a05-4d8e-be22-6b77da591623.png)

**Comment by kulmann** [comment]
Already tracked as a feature request in https://github.com/owncloud/web/issues/6239 - closing here.
