### ISSUE TITLE
Cached parts of the interface by switching between accounts not updating

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#6549]
### Steps to reproduce
1. In CERNBox login with a normal account
2. Logout and login with the lightweight account, that gets another list of navItems and doesn't have quota

Implementation of different lists of navItems here: https://github.com/cernbox/web/blob/0dfa4717578cedfaa0cf976e027b20c212f76b6f/packages/web-app-files/src/index.js#L169-L171

### Expected behaviour
The navItems and the quota are changed corresponding to the account

### Actual behaviour
The list of navItems for the lightweight accounts is mixed with cached navItems from previous account. Quota is shown where it doesn't exist. By opening the app in new tab the problem disappears.

![Untitled_ Mar 8, 2022 11_49 AM](https://user-images.githubusercontent.com/7430156/157224653-c176c900-401c-467d-8a74-64e3c18d5425.gif)

**Comment by elizavetaRa** [comment]
@kulmann I found the issue with quota: if the backend returns no quota (our case with lightweight accounts), the quota in store is not reset from the previous logged in user inside one browser tab

**Comment by diocas** [comment]
@elizavetaRa I guess this can be reproduced in master if you - for example - add a new menu entry on the left sidebar?
