### ISSUE TITLE
Introduce `available()` getter for the graph API

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#6551]
As described [here](https://github.com/owncloud/web/pull/6531) it would be nice if the graph API had a `available()` check. It makes life easier for developers as oC10 does not support the graph API.

The check can currently be done via the composition API: `capabilities.spaces.enabled`.

**Comment by JanAckermann** [comment]
might not be necessary anymore after https://github.com/owncloud/web/pull/9530
