### ISSUE TITLE
Design polishing v3

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6555]
### timeboxed design refinements
Items for this ticket are limited to 15 Items for better manageability
- [x] row hover: bring back hover for single row https://github.com/owncloud/web/pull/6584
- [x] spaces overview context menus: icons should be style "line" (like the other context menu icons) - can't reproduce, this already seems to be the case in https://github.com/owncloud/web/blob/2002a9360e2bfb743acb65bbc45fd3240c2fa113/packages/web-app-files/src/views/spaces/Projects.vue#L135 
- [x] Spaces: Rename "Create Space" to "+ New Space" (= wording aligned with fileslist and usermanagement)
- [x] Spaces: Rename call to action from "~~invite~~" to "add" (Reasoning: Adding members is not an invtation, but members get forced and cant even leave a space by their own by-design) Also: remove description message ~~Add new person by name, email or federation IDs~~ task should be done via contextual help-questionmark (?)
<img width="694" alt="image" src="https://user-images.githubusercontent.com/26610733/161586155-14ee5c4f-8cf0-462f-a7f0-ea10225601d1.png">

- [x] Spaces: Set a fixed aspect ratio of eg. 12:7 for the Space image on the overview- and front page, so that the image-crop does not rely on the browser-size. (I used 300x175 px in the designs) c.f. https://github.com/owncloud/web/issues/6705

**Comment by diocas** [comment]
@tbsbdr I hope you don't mind me hijacking this issue, but here are a couple pet peeves from me, after a quick look at the latest master (some @elizavetaRa already fixed so we can push):

- [ ] Breadcrumb heigh changes when navigating folders
    * On the root, the breadcrumb has the height of the text, but then I go inside a folder and there's a small "jump" to accommodate the chevron (`>`), and another one after for the context menu button (`...`).
- [ ]  Inconsistent context menus
    * If I click in "+ New", or "Upload", or right click on a row, or click `...` in the breadcrumb, all menus are different and shouldn't. Inconsistent spacing/outer margins, min-width, hover (the `...` has underline), etc... The reference should be the right click/context menu on a row.
- [ ] iframe border on external apps
    * Sorry to bring this up again, but it's still not fixed. Visible in Chrome. iframes in general - any app - should have a border:0.
- [ ] Batch actions menu overlaps the right click context menu
- [ ] The hover effect in the context menu is wrong
    * There's a padding around the button. We can put the mouse there, which keeps the hover, but then it's not actionable/clickable. This was a mistake from our PR and @elizavetaRa will fix it.
- [ ] Huge elements in the UI/non harmonious text sizes
    * I mentioned this in the last polishing ticket but you closed it and marked that as my "opinion"/needs to be discussed. But since this keeps being mentioned by all our users, I'll mention it here once more.
    * Examples: new/upload/batch actions' buttons are humongous, as well as the action buttons in the files list are disproportionately big.
- [ ] Inconsistent rounded corners
    * The corner radius for the new/upload/batch buttons is not proportional to the rounded corners of the left sidebar, the hover effects on context menus, the modal boxes, etc

**Comment by pascalwengerter** [comment]
@diocas thanks for the list! Could you (or @elizavetaRa ) mark the ones you already have fixed/are working on so we can avoid duplicate work? 🤓

**Comment by elizavetaRa** [comment]
"Inconsistent context menus"  and " The hover effect in the context menu is wrong" need some discussion. I override some css of context menus in cernbox web but the proper way would be changing in both ods and web. So I can do it.

"iframe border on external apps" can be pushed upstream

**Comment by pascalwengerter** [comment]
> "Inconsistent context menus" and " The hover effect in the context menu is wrong" need some discussion. I override some css of context menus in cernbox web but the proper way would be changing in both ods and web. So I can do it.
> 
> "iframe border on external apps" can be pushed upstream

iframe border is being fixed in https://github.com/owncloud/web/pull/6573, updated the comment above to reference it and mark it closed

**Comment by pascalwengerter** [comment]
Actually removing this from the current sprint/backlog since there's some discussion needed on some of the items
