### ISSUE TITLE
Quota value doesn't change after uploading a file

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6574]
web v.5.2.0
ocis v.1.18.0
run local

Steps:
1. Admin creates the space
2. Admin goes inside to space
3. selects "details" from the context menu and sees the quota
4. Admin uploads file and sees quota again

Actual result: quota didn't change. Last modify date didn't change also
Refresh page or open again space helps, because method GET `https://localhost:9200/graph/v1.0/drives/spaceId` is called

https://user-images.githubusercontent.com/84779829/157675829-0b789ac9-15c0-40ec-b95d-14dd02786979.mov

**Comment by pascalwengerter** [comment]
Closed in favor of the more recent #6930
