### ISSUE TITLE
[QA] enhancement: display long file names

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#6582]
Seen with web-5.2.0 and web-5.3.0-rc1

* create a file with a name that is 100 characters long
* view in web. the name is truncated. OK
![image](https://user-images.githubusercontent.com/1108546/157892808-bea07813-67aa-424b-b40b-beefe16e9d02.png)
----
* hover mouse, try the details side bar. Nothing reveals the full name. BAD.
* resize the browser window to 2900 pixels. That is not sufficient to show 100 characters. Much whitespace is shown instead. BAD.
![image](https://user-images.githubusercontent.com/1108546/157893194-775dc589-5949-4617-b14d-1eee2c76e09e.png)
----

Expected behaviour:
* name is shown unabbreviated when it technically fits on the screen
* mouse over should reveal the unabbreviated name
* the details sidebar should have the unabbreviated name

Workaround:
* surprisingly the rename action exposes the unabbreviated name
![image](https://user-images.githubusercontent.com/1108546/157893485-3b9b458d-1016-4a78-b35a-0195585d078f.png)

**Comment by jnweiger** [comment]
This issue becomes more problematic in 5.4.0, where a new sharing column eats away more space from the filename.
Now a typical screenshot with timestamp no longer shows in full.
Screenshot of a browser window with width 1920:

![image](https://user-images.githubusercontent.com/1108546/162943595-6e9325ef-b0c1-4b91-a371-f429a73fde93.png)

Please remove some wasted whitespace between Size - Modified - Actions.

**Comment by pascalwengerter** [comment]
Closing this in favor of #6776, thanks @jnweiger for reporting! 💟
