### ISSUE TITLE
oc10IntegrationApp1 private link acceptance tests flaky

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6607]
Examples:
- https://drone.owncloud.com/owncloud/web/23776/69/21 - `webUIPrivateLinks/accessingPrivateLinks.feature:17`
- https://drone.owncloud.com/owncloud/web/23775/71/21 - `webUIPrivateLinks/accessingPrivateLinks.feature:9`

**Comment by saw-jan** [comment]
Also same failure in XGAPortrait:
https://drone.owncloud.com/owncloud/web/23781/42/20 - `webUIPrivateLinks/accessingPrivateLinks.feature:9`

**Comment by kiranparajuli589** [comment]
a bit more context can be found here too. https://github.com/owncloud/web/issues/6227

**Comment by kulmann** [comment]
Seeing a lot of examples where this test is failing. Would like to raise the prio on this.
- https://drone.owncloud.com/owncloud/web/23964/69/21
- https://drone.owncloud.com/owncloud/web/23958/71/22
