### ISSUE TITLE
In e2e test Personal Page doesn't load properly (oc10)

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#6610]
## Description
In oc10 e2e tests , 
1. User navigates to **`share page`** and **accept share**
2. User navigate to personal page
     Sometimes **`Personal page`** doesn't load properly  
     This causes e2e tests to fail intermittently.

   If we reload, all the content(files/folders) will be successfully loaded on the **` Personal page`**.
   

Playwright screenshots of personal page not loading properly are available below
![personalpage](https://user-images.githubusercontent.com/54478846/158779530-165782cb-2cb6-4ddd-ad50-078b7554639a.png)

**Comment by kulmann** [comment]
That's a known ocis backend issue: https://github.com/owncloud/ocis/issues/2995

**Comment by amrita-shrestha** [comment]
> That's a known ocis backend issue: [owncloud/ocis#2995](https://github.com/owncloud/ocis/issues/2995)

@kulmann But it is happening in oc10

**Comment by kulmann** [comment]
🤯

**Comment by amrita-shrestha** [comment]
For example, we can look on this builds
https://drone.owncloud.com/owncloud/web/23796/10/1
https://drone.owncloud.com/owncloud/web/23786/10/1
