### ISSUE TITLE
Find all deleted files in one place

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6616]
# Description

## User Stories

* > As a user I want a single navigation entry point to where I can find deleted files so that I can restore a resource or delete files permanently as on my local OS.

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] codre review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

**Comment by JammingBen** [comment]
@tbsbdr Can this be closed with the new trashbin overview (https://github.com/owncloud/web/pull/8515)?

**Comment by JanAckermann** [comment]
Closing, please re-open if trashbin overview is not sufficient
