### ISSUE TITLE
Unite "Links" + "People" in "Share" Panel 

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6621]
# Description

## User Stories

* > (Comprehend)  As a user I want to see at a glance how and who has access to a resource so that I can make sure that no unwanted access is disclosed. 

* > (Edit) As a user I want to manage access to a resource so that I'm in full control of resource-access.

**Note:**
The usecase "Just quickly sharing a resource" is covered by rightclick and quickactions and not No1 focus of this story.

## Value
* > data loss prevention by-design
* > Simplify resource access-management 

## Acceptance Criteria
- [X] Panel headline is "Share"
- [X] Right sidebar gets wider (eg. 1/3) so that line-breaks of the scopes "Everyone with the link v  can edit v" are avoided  
- [X] **OC10** only: Private link gets moved to top right corner, as in screenshots
- [X] **OC10** only: Links-Section holds only public Links, Headline: "Share via public link"

- [X] **oCIS** only: Links-Section holds Scoped links Headline: "Share via link"

- [X] **Quick Link:** Concept is introduced for oc10 and oCIS:
  - Quickaction-Link creates/copies always the quick-link
  - if more links are needed, they can get created via click on `add link`

- [ ] Sharee-List is initialy truncated to the first 3 items; (Note: this also applies to the Spaces-Share list which is grouped into `Shared with` and `Space members`)
  - `show all` expands, shows all Sharee-list entries
  - `show less` collapes, shows the first 3 items
- [ ] `Shared column / Status` => People & Link share indicators stay, get updated to "anchor scroll" in Shares sidebar panel

**Cherries on top:**
- Sidebar title selected item "name" doesn't slide when changing panels

## Questions

- Should we make the sidebar "wider" again?
- Are "Link share items" expandable, similar to "People share items"?
- How many "People" shares are initially visible?
- Should "People" and "Link" shares be expandable (akin to Summary/Details HTML tag) inside the Shares panel?

**Comment by tbsbdr** [comment]
We had a discussion how to confirm to the users, that the link had been copied in a little bit less disturbing and more polite, in-place way than via a toast. 

Problems:

- a) If we only use an Icon like 📋 -> ✅ and change it on-click for confirmation, it looks nice but is not accessible for everyone  -> Icon only  should be avoided if possible ([more about icon usability](https://www.nngroup.com/articles/icon-usability/))
- b) If we use text and the button text changes from "copy" -> "copied" or "copia" -> "copiado de" the button gets jumpy because of its changing width.

### Proposals

#### 1: use "Ok" as a kind of literal (needs no translation -> doesn't jump)
@pascalwengerter I would say even the change of the text doesn't feel so nice - though the width is fixed in the example:
![2022-04-06_22-22-20 (1)](https://user-images.githubusercontent.com/26610733/162065648-591482f3-a1ff-443f-9faa-a559d8dee168.gif)

#### 2: use the URL icon + URL to display success
I would prefer this one as it doesn't "pull the carpet" under your mouse-pointer: 
![2022-04-06_22-25-17 (1)](https://user-images.githubusercontent.com/26610733/162067321-cd0a3636-56ce-491f-992f-bdfd87d10405.gif)
Could be even nicer eg. via pushing-in from left to right and back again. Didn't want to go into more detail without your feedback.

Should be go on with proposal 2?

**Comment by kulmann** [comment]
Proposal 2 looks nice 👍
