### ISSUE TITLE
Context Menu: The context menu is in some cases not in the foreground

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6627]
Context Menu: The context menu is in some cases not in the foreground

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/33026403/156359229-b5e72834-005f-4400-ae22-30ec270788bc.png">

_Originally posted by @ChrisEdS in https://github.com/owncloud/web/issues/6492#issuecomment-1056860071_

**Comment by JanAckermann** [comment]
Closing, as this isn't an issue anymore:
![image](https://user-images.githubusercontent.com/26169327/200269556-d280fc88-87c9-431a-82f0-9642027a7433.png)
