### ISSUE TITLE
Jumping contents when opening the right menu

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6628]
Jumping contents when opening the right menu

https://user-images.githubusercontent.com/33026403/156537640-9d97e0f9-8be0-4eaa-a302-a4bbb527fe94.mov

_Originally posted by @ChrisEdS in https://github.com/owncloud/web/issues/6492#issuecomment-1057854295_

**Comment by JammingBen** [comment]
Closing as it seems to be fixed meanwhile.
