### ISSUE TITLE
Rearrange space context menu

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#6634]
Rearrange the context menus for spaces so they a) match visibly with all other context menus and b) include some separation lines.

![image](https://user-images.githubusercontent.com/50302941/159447476-6ad53f42-7822-47ca-a7eb-a73a696aacf8.png)

![image](https://user-images.githubusercontent.com/50302941/159447535-599c5eca-f62e-429d-91b0-9a255287e1bc.png)

**Comment by tbsbdr** [comment]
Proposal for Space-Context menu polishing:
Left: Space Manager - right: Regular member

@pmaier1 would you change something?

![image](https://user-images.githubusercontent.com/26610733/159885918-531c5bd6-d04f-4a0c-b899-f89935c0dc9a.png)

Wording "Restore" or "Enable" ? what do you think?
"Restore" is more common, if a item is in a trash bin
"Enable" would be more in line with "Disable" (my favorite)
![image](https://user-images.githubusercontent.com/26610733/159886467-a80be313-0cf7-4c20-81db-a9ce3b283295.png)
