### ISSUE TITLE
Share doesn't disappear from "Shared with others" filesList after last share has been deleted in sidebar

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6650]
### Steps to reproduce
1. Have a share in `Shared with others` view
2. Delete all share receivers
3. Share stays in the ResourceTable until page reload

### Expected behaviour
Share disappears from ResourceTable when last share receiver is successfully deleted

**Comment by JanAckermann** [comment]
Closing:
This is intended, so a user can unshare a resource and share it with another user without changing views
