### ISSUE TITLE
moving one folder into an other results into wrong breadcrumbs

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#6664]
### Steps to reproduce
1. create folder `f1`
2. create folder `f2`
3. move folder `f2` via drag and drop into `f1`

### Expected behaviour
content of `f2` is shown and breadcrumbs show  `All files -> f1 -> f2`

### Actual behaviour
content of `f2` is shown but breadcrumbs show  `All files -> f2`

### Environment general
**Operating system**:
Ubuntu

**Backend (ownCloud Core or Infinite Scale)**:
ocis 

### Environment ownCloud Infinite Scale
**Version:**
commit a6b1bae29ee7b01b63e00369f9354c5cc57a4143

**Updated from an older Infinite Scale or fresh install:**
fresh

**Where did you install Infinite Scale from:**
git

**Comment by pascalwengerter** [comment]
@individual-it could you try on https://ocis.ocis-web.latest.owncloud.works? I refactored the breadcrumb "calculation" yesterday and couldn't reproduce

**Comment by individual-it** [comment]
@pascalwengerter same
![image](https://user-images.githubusercontent.com/2425577/160780418-5c01b2e3-5f9f-42ae-8117-b39b9f323c8f.png)
after going back and navigating into the folders
![image](https://user-images.githubusercontent.com/2425577/160780605-9e830d23-0933-4202-8511-a0ff974123d6.png)

**Comment by JanAckermann** [comment]
Not able to reproduce anymore with the given steps
