### ISSUE TITLE
Image Preview: Show images in full browser-viewport

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6700]
## Userstory:

* > As a user I want that big images are shown as big as possible in the browser so that I get the best impression of the image. 

## Acceptance Criteria
- images bigger than the viewport get resized to cover 100% of the browser viewport
- The controls (incl. image title) overlay the image
- The controls have a fixed position while next/prev so that you don't have to reposition your mouspointer
- Image-title gets a background color
- controls + image title appear:
  - on mouse hover of the viewport
  - on single tap (touch device)
  - focus via keyboard 
- controls + image title disappear:
  - after 5 seconds without mouse-movement within the viewport
 - a transparent lightbox-background is placed "behind" the image
 - gesture: swipe left/right changes to next/prev picture

## Current status
![image](https://user-images.githubusercontent.com/26610733/159478333-8f2d0b84-2ec0-412e-be56-eccc205aecc0.png)

## Image with in full browser viewport
with controls + image visible
![image](https://user-images.githubusercontent.com/26610733/159478477-99fd5afd-d606-4bed-a12a-f9e13996855a.png)

## Image with in full browser viewport
with controls + image NOT visible after "inactivity"
![image](https://user-images.githubusercontent.com/26610733/159478613-4cd89990-fd64-4a61-b489-0778eb664418.png)

**Comment by dschmidt** [comment]
Regarding `full viewport`:

Why not both? I agree with @kulmann that we should stay in the frame of the app for a regular browser window - but I would also like a fullscreen view and that doesn't need the app frame imho.
