### ISSUE TITLE
Menu entry turns grey when opening application switcher

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#6703]
### Steps to reproduce
1. In Light Mode open the left menu (Application Switcher)

### Actual behaviour

`Files` text is getting grey without reason

https://user-images.githubusercontent.com/33026403/161080454-ed136025-38e8-4e73-9a34-a78aba2c1045.mov

**Comment by JammingBen** [comment]
Issue has been fixed meanwhile on current master.
