### ISSUE TITLE
Remove a share/space member: show confirmation dialog 

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6728]
### Steps to reproduce
1. go to https://web.owncloud.com/ -> new design
2. share a file with group "admin"
3. "Shared with" list: click on 3-dots -> `remove share`

### Expected behaviour
A confirmation dialog shows up so that I can confirm my action:
```
Remove share <displayname>?
Are you sure you want to remove this share?
[Cancel] [Remove]
```

### Actual behaviour
Share gets removed immediately

### Background:
Action should be confirmed as there is no easy undo / restore action.

**Comment by kulmann** [comment]
Why is the action irreversible? 🤔 I can easily recreate the share.

I agree that it should have a confirm dialog. But only because there is no undo and no restore action.

**Comment by tbsbdr** [comment]
> irreversible

correct, thx - updated initial post
