### ISSUE TITLE
Rename: Prevent accidental change of the file extension

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6729]
### Steps to reproduce
1. go to new design in https://web.owncloud.com/
2. select `ownCloud Manual.pdf` and choose "rename"
3. type "asd"
4. hit enter

### Expected behaviour
file is renamed to `asd.pdf` and can still be opened via rightclick -> open with pdf viewer

### Actual behaviour
file is renamed to `asd` and can not be opened with the pdf viewer

initial text-selection guides the user towards changing the file extension
<img width="512" alt="image" src="https://user-images.githubusercontent.com/26610733/161603093-36304a3a-1b92-44ac-8110-8036c9dc3bb4.png">

### Remedy
On rename, only the filename without extension should be pre text-selected
<img width="512" alt="image" src="https://user-images.githubusercontent.com/26610733/161603490-ef130405-ce2e-4f92-a93b-72ce6ed09618.png">

**Comment by phil-davis** [comment]
Note: the existing behavior of the oC10 classic webUI" is the same as the "Remedy" expected behavior here. So this issue will make web behave the same as the classic webUI.
