### ISSUE TITLE
provide switch to hide/show extensions

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6730]
### Expected behaviour
- File extension should be visible by default (but default configurable by admin)
- user should have a way of hiding file extensions

### Proposal
- define config.json option for "show/hide file extension" default value (fallback if undefined: show extensions)
- Provide a switch in the ⚙️ - Menu -> "File extensions [on/off]" to show/hide extensions; default: based on config.json option, see above
- Persist user choice in localstorage for now (similar to "show/hide hidden files")
- show/hide extensions also in the "rename" and "create" textfields (i.e. you can't accidentally change a file extension then any more)
- file name is also visible in the right sidebar header section ("FileInfo" component), needs to respect the user choice as well

### Value
- groundwork for user testing
- groundwork for user settings
- enable targeting different user groups

**Comment by kulmann** [comment]
Valid request, no worries. ;-) Only thing I'm not sure about is what we should have as a default here.

**Comment by tbsbdr** [comment]
Thats actually my point - my proposal is to hide the file extensions **by default** (like in Windows and MacOS)
