### ISSUE TITLE
Richdocuments icon not displayed in Contextmenu

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6737]
### Steps to reproduce
1. Use OC10 + latest web release + Richdocuments (classic) app
2. Try to open `.odt` or other applicable file using the contextmenu
3. Don't see an icon

### Expected behaviour
See the app icon next to `Open in $appName`

### Actual behaviour
We currently take whatever icon the app is configured to be shipped with and try to render it as one of [the icons in the ODS](https://owncloud.design/#/Design%20Tokens/IconList) - if it's not in there (which is a reasonable thing to happen for a lot of apps out there) the rendering fails

<img width="721" alt="Screenshot 2022-04-05 at 14 29 16" src="https://user-images.githubusercontent.com/16822008/161753781-eaabda9d-d78f-492a-b16f-edf837b996f8.png">

**Comment by JanAckermann** [comment]
Closing, as we unfortunately discontinued oc10 support
