### ISSUE TITLE
Quick-rename button not visible on keyboard-focus

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#6755]
### Steps to reproduce
1. have a file list
2. cycle through interactive elements with the `TAB` key on your keyboard
3. reach a file name
4. hit `TAB` once more

### Expected behaviour
The `quick rename` button that usually appears on mouse hover to the right of the file name also appears on keyboard focus.

### Actual behaviour
The `quick rename` button has keyboard focus (and can actually be interacted with) but stays visually hidden.

**Comment by kulmann** [comment]
Thinking more about this, I think the rename button should be visible for the row that has the keyboard focus on any of its interactive elements. E.g. checkbox of row 3 focused -> already make the rename button in row 3 visible.

**Comment by kulmann** [comment]
<img width="1761" alt="Screenshot 2022-04-08 at 10 51 52" src="https://user-images.githubusercontent.com/3532843/162401764-63f1c5f8-52f2-4b70-87f4-1c3e3e17b4f9.png">


Having the quick rename button visible all the time for all rows would look this this ^

**Comment by JanAckermann** [comment]
@kulmann having it visible all the time would be more accessible, IHMO otherwise it is more of a hidden feature to most users
What do you think?
FYI @tbsbdr

**Comment by kulmann** [comment]
> @kulmann having it visible all the time would be more accessible, IHMO otherwise it is more of a hidden feature to most users
> What do you think?
> FYI @tbsbdr

could you try with the muted text color as default and then use the regular text color (higher contrast) on hover?  my screenshot above is too heavy IMO

**Comment by JanAckermann** [comment]
@kulmann Sure, please have a look:
https://github.com/owncloud/web/pull/6817
