### ISSUE TITLE
PDF-Viewer doesn't work

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#6772]
### Steps to reproduce
1. Setup PDF-Viewer via config.json
2. Try to open a PDF

### Expected behaviour
PDF opens

### Actual behaviour
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/33026403/162780108-0f3779f7-f940-4dad-bbe4-bf921663e243.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/33026403/162780437-849fdfc2-fed7-428b-989e-b69398d470d4.png">

### Environment general
**Backend (ownCloud Core or Infinite Scale)**:
oC10

**ownCloud Web**
5.4.0

**Comment by kulmann** [comment]
Your instance has `web` installed as app via marketplace, correct?

**Comment by ChrisEdS** [comment]
That's correct.

**Comment by JanAckermann** [comment]
Closing, as this isn't likely an issue anymore, please reopen if problem occurs again
