### ISSUE TITLE
Make files with long filenames distinguishable

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6776]
### Steps to reproduce
1. open web.owncloud.com
2. create 2 new folders with filename `System_Library_Accessibility-BundlesBase_com-apple-FaceTime-FaceTimeNotificationCenterService-axbundle-FINAL` and System_Library_Accessibility-BundlesBase_com-apple-FaceTime-FaceTimeNotificationCenterService-axbundle-DRAFT
3. resize window to ~ 1330px width at 100% browserzoom

### Expected behaviour
The user should be able to distinguish the folders (files) - even on thouch devices

### Actual behaviour
Users can not distinguish which folder is which

### Solution proposal
1. Nice to have: show full filename on hover (= optional shortcut for mousepointer-device users)
2. Mandatory: show the full filename in the details pane.

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/26610733/162943472-5f93b4b7-d023-4dab-8d1b-4800b9114a24.png">

### Other Exmaples
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/26610733/162957858-36aaceb9-8c88-4d85-8c92-5ef5f731b5d9.png">

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/26610733/162957890-1706f160-ebfe-434d-9012-1cfc6b64368d.png">

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/26610733/162957925-3e093466-a9ee-43d2-a53c-28ef59a969cd.png">

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/26610733/162957937-03a2dc20-1d77-405b-9a46-051116cb0ba6.png">

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/26610733/162957963-3418ad9c-e6c2-454e-acf2-ba2ea0941221.png">

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/26610733/162957985-8c126a1a-fb36-42fe-8bf0-288fb438a054.png">

<img width="310" alt="image" src="https://user-images.githubusercontent.com/26610733/162957998-5091aa40-d0f3-475d-9473-a7257dd241f3.png">

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/26610733/162958009-bb90e9ee-a0e3-4647-8597-daa55bad8d24.png">

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/26610733/162958024-1cd58cc0-9641-4f95-90da-6bb2fbf77e36.png">

**Comment by jnweiger** [comment]
See also: #6582

**Comment by tbsbdr** [comment]
updated initial post:

> 1. Nice to have: show full filename on hover (= optional shortcut for mousepointer-device users)
> 2. Mandatory: show the full filename in the details pane.
