### ISSUE TITLE
[QA] folder upload discusses "trusting" ownCloud

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#6778]
Seen with web-5.4.0

* Open normal files view
* Click on "Upload"
* Choose "Folder", select a folder from the local file browser dialog that appears. 
* Click OK. A popup dialog comes up that explains what is about to happen. OK.
* But this dialog also warns: "Only do this if you trust the site". BAD.
![image](https://user-images.githubusercontent.com/1108546/162949754-416f192c-fa68-4cd5-bc73-5221d436f088.png)
----
* When uploading files, even multiple files, no concern about "trust" is raised. OK.
* I don't see, what is special when uploading a folder, that requires a user to think more about trust in this case. -- That makes a difficult decision. ( I'd say, I trust the site anyway, even for files :-) )

**Comment by pascalwengerter** [comment]
This is considered a security feature in Chrome/Chromium-based browsers AFAIK (details e.g. https://stackoverflow.com/questions/50225019/how-to-remove-warning-message-in-chrome-when-uploading-a-directory) and nothing we can do/work around. Closing
