### ISSUE TITLE
[QA] support for plain text is missing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#6780]
Seen with web-5.4.0 as installed on cloud.owncloud.com

* Select "Classic Design" and verify that text files open in files_texteditor. OK
* New text files can be created in classic design. OK
![image](https://user-images.githubusercontent.com/1108546/162964682-54cc9e46-d6a7-4e46-9dd2-9d9bc5b026f3.png)
----
* Select "New design"
* Click on a text file. Download only. BAD
* New does not offer plain text. BAD
![image](https://user-images.githubusercontent.com/1108546/162964905-bfbc87cf-4910-46e8-aa05-2948095ecfcc.png)

Sidenote: More information is needed, so that users can distinguish betwenn the different "Document" entries in this dropdown. E.g. name of the office suite as section heading, and/or file name suffix.

**Comment by kulmann** [comment]
We have a `text-editor` app which is just not enabled on cloud.owncloud.com. I'll close this ticket here, download is a reasonable behaviour if you don't have the text-editor app in an instance. Please reopen if you don't agree. 😉
