### ISSUE TITLE
Quick public-link fails silently with password policy and expiration required

### ISSUE THREAD

**Issue by IljaN** [owncloud/web#6782]
### Steps to reproduce
1. Set password policy and expiration date as required in ownCloud 10
2. Create a folder 
3. Try to create a quick share on the folder

### Expected Behavior  
A prompt which tells the user to enter the password and/or expiration date or hide quicklink altogether.

### Actual behaviour
No feedback in the UI and no public link created.

**Backend (ownCloud Core or Infinite Scale)**:
ownCloud classic 10.9.2

**Version:** (see ownCloud admin page)
10.9.1 / web 5.2

**Comment by pascalwengerter** [comment]
This isn't strictly necessary for the beta phase (Infinite Scale doesn't have the password.enforced_for public links yet), however I'd like to fix it before we release web `v5.5.0` for usage with oc10

**Comment by pascalwengerter** [comment]
Closed via #6967
