### ISSUE TITLE
Some request  fail while doing batch request in OCIS

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6796]
Seems like batch requests have not been working properly in ocis. There has been some tests failure related to batch request while deleting, restoring

## Batch Restore
- https://github.com/owncloud/web/issues/6791
build: https://drone.owncloud.com/owncloud/web/24784/68/15, https://drone.owncloud.com/owncloud/web/24755/68/15, https://drone.owncloud.com/owncloud/web/24878/68/15
- https://github.com/owncloud/web/issues/6797
build: https://drone.owncloud.com/owncloud/web/24784/68/15

## Batch Delete
- https://github.com/owncloud/web/issues/6706
build: https://drone.owncloud.com/owncloud/web/24305/67/15
- https://github.com/owncloud/web/issues/6707
- webUITrashbinDelete/trashbinDelete.feature:105
  build: https://drone.owncloud.com/owncloud/ocis/10816/50/9

## Batch Share (share with multiple users/groups)
- https://github.com/owncloud/web/issues/6721
- webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature:55
  build: https://drone.owncloud.com/owncloud/web/24878/63/15

## Upload Folder containing multiple files/fodlers
- https://github.com/owncloud/web/issues/6741

**Comment by SwikritiT** [comment]
Other issues related to batch request
https://github.com/owncloud/web/issues/6791
https://github.com/owncloud/web/issues/6706
https://github.com/owncloud/web/issues/6707

**Comment by SwikritiT** [comment]
@pascalwengerter @kulmann

**Comment by SwikritiT** [comment]
`webUITrashbinDelete/trashbinDelete.feature:105` failed 

```console
Scenario: Delete folders with dot in the name from trashbin (attempt 1, retried) # features/webUITrashbinDelete/trashbinDelete.feature:105
   ✔ Before # setup.js:41
   ✔ Before # setup.js:45
   ✔ Before # setup.js:49
   ✔ Before # setup.js:66
   ✔ Before # setup.js:73
   ✔ Before # setup.js:84
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:199
   ✔ Before # stepDefinitions/generalContext.js:237
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Alice" has created file "lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Alice" has created file "lorem-big.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "sample,1.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created folder "simple-folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created folder "Folder,With,Comma" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "simple-folder/lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "simple-folder/lorem-big.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file "data.zip" to "data.zip" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And the following files have been deleted by user "Alice" in the server # stepDefinitions/middlewareContext.js:76
       | name              |
       | lorem.txt         |
       | simple-folder     |
       | sample,1.txt      |
       | lorem-big.txt     |
       | Folder,With,Comma |
       | data.zip          |
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:64
   ✔ And the user has browsed to the trashbin page # stepDefinitions/filesContext.js:74
   ✔ Given user "Alice" has created the following folders in the server # stepDefinitions/middlewareContext.js:76
       | folders  |
       | fo.      |
       | fo.1     |
       | fo...1.. |
       | fo.xyz   |
   ✔ And the following folders have been deleted by user "Alice" in the server # stepDefinitions/middlewareContext.js:76
       | name     |
       | fo.      |
       | fo.1     |
       | fo...1.. |
       | fo.xyz   |
   ✔ And the user has browsed to the trashbin page # stepDefinitions/filesContext.js:74
   ✔ And the user has reloaded the current page of the webUI # stepDefinitions/filesContext.js:451
   ✔ When the user batch deletes these files using the webUI # stepDefinitions/filesContext.js:487
       | name     |
       | fo.      |
       | fo.1     |
       | fo...1.. |
       | fo.xyz   |
   ✖ Then the deleted elements should not be listed on the webUI # stepDefinitions/filesContext.js:402
       AssertionError [ERR_ASSERTION]: Expected resource 'fo.' to be 'not present' but found 'present'
           + expected - actual

           -false
           +true

           at assertElementsAreNotListed (/srv/app/web/tests/acceptance/stepDefinitions/filesContext.js:939:12)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
   - And the deleted elements should not be listed on the webUI after a page reload # stepDefinitions/filesContext.js:406
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:255
   ✔ After # stepDefinitions/generalContext.js:224
   ✔ After # stepDefinitions/generalContext.js:165
   ✔ After # setup.js:117
   ✔ After # setup.js:113
   ✔ After # setup.js:109
   ✔ After # setup.js:102
   ✔ After # setup.js:93
```

**Comment by saw-jan** [comment]
Those problems seem to be with oCIS server. Issues have been raised:
https://github.com/owncloud/ocis/issues/3612
https://github.com/owncloud/ocis/issues/3613 
https://github.com/owncloud/ocis/issues/3614

TODO:
- [ ] skip the tests related to those issues

**Comment by saw-jan** [comment]
Sharing failed: https://drone.owncloud.com/owncloud/web/25227/64/15
Restore failed: https://drone.owncloud.com/owncloud/web/25226/68/15

**Comment by saw-jan** [comment]
Seen again: https://drone.owncloud.com/owncloud/web/25313/64/15

**Comment by saw-jan** [comment]
Batch restore failed nightly: https://drone.owncloud.com/owncloud/web/25402/68/15

**Comment by SwikritiT** [comment]
Sharing related failure in https://drone.owncloud.com/owncloud/web/25449/64/15

**Comment by SwikritiT** [comment]
Sharing related failure: https://drone.owncloud.com/owncloud/web/25488/63/15
```console
webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature:54
```

Trashbin related failure: https://drone.owncloud.com/owncloud/web/25488/68/15
```console
webUITrashbinRestore/trashbinRestore.feature:115
webUITrashbinRestore/trashbinRestore.feature:84
```

**Comment by SwikritiT** [comment]
The failures have been pretty much consistent in recent nightly builds

**Comment by saw-jan** [comment]
Tests look pretty stable with the latest oCIS.
The culprit issue in oCIS has been fixed (https://github.com/owncloud/ocis/issues/3757).
Bumping is on the way (https://github.com/owncloud/web/pull/6946). CI should be stable after bumping.

IMO, this issue can be closed alongside the PR merge.

**Comment by pascalwengerter** [comment]
Closing via https://github.com/owncloud/web/pull/6946, thanks for the efforts!
