### ISSUE TITLE
get rid of hideSearchBar option by using existing capability

### ISSUE THREAD

**Issue by butonic** [owncloud/web#6806]
Currently web checks a dedicated option to disable the search bar, introduced wcith https://github.com/owncloud/web/pull/3817

However, the capabilities do contain the list of reports that clients can fire against webdav.

For backend search (aka sdk search) the `capabilities.dav.reports` string array has to contain `"search-files"`:
```json
...
{
  "dav":{
    "chunking":"",
    "trashbin":"1.0",
    "reports": ["search-files"],
    "chunkingParallelUploadDisabled":false
  }
}
...
```

Web should rely on that `dav.reports` property in the capabilities instead of an option in the config.

Another report is a `filter-files` report which is used to filter files by favorites and tags ... but that is a different issue.

**Comment by kulmann** [comment]
Agreed, capability should have precedence and the config.json option can be dropped immediately.
