### ISSUE TITLE
[PR 6202][Uppy] While uploading a file, file has some extra contents added

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#6810]
### Steps to reproduce
1. upload a file with some content
2. check the uploaded file content in the web
3. download file and check the content

Related to PR #6202

### Expected
To have real content

### Actual
uploaded file has some extra content
![uploaded_extra_content](https://user-images.githubusercontent.com/52366632/165026784-981e9cf0-a9d4-4ede-9e61-f6265d8314f7.png)

**Comment by pascalwengerter** [comment]
Note that this issue only occurs on #6202

**Comment by JammingBen** [comment]
Thx for noticing/reporting! Should be fixed via the latest commit to https://github.com/owncloud/web/pull/6202.
