### ISSUE TITLE
Open tasks for Uppy

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#6819]
This issue contains a list of Uppy-related open tasks after https://github.com/owncloud/web/pull/6202 has been merged.

- [x] Polish upload-info-box -> https://github.com/owncloud/web/pull/6837
    - Parent folder links are hard to read in dark mode
    - "Upload successful" message is displayed even on upload errors
- [x] ~Add possibility to remove successful uploads from the upload-info-box -> we decided against this~
- [x] Fix links in the upload-info-box when resources were uploaded to the personal space root -> https://github.com/owncloud/web/pull/6846
- [x] Remove `ProgressBar` component and `inProgress` state  -> https://github.com/owncloud/web/pull/6825
- [x] `UppyService` shouldn't extend `Vue` - use own event implementation instead (https://github.com/owncloud/web/pull/6202/files#r850141613) -> https://github.com/owncloud/web/pull/6853
- [x] Refactor file- and folder-upload-components to one component -> https://github.com/owncloud/web/pull/6859
- [x] Add unit tests -> https://github.com/owncloud/web/pull/6871
- [x] Use tus for uploads to password protected public pages when possible (needs https://github.com/owncloud/ocis/issues/3588 to be fixed first) -> https://github.com/owncloud/web/pull/6890
- [ ] a11y

## needs product decision first:
- [x] Thumbnails for files in the upload-info-box (?) // not sure, yet, if this makes the UI too chaotic. seeing it (with a quick and dirty implementation or with a mockup) side by side with and without thumbnails would be beneficial for decision making @kulmann -> not for now

**Comment by pascalwengerter** [comment]
I'd like to promote fixing #2443 here - folders uploaded via drop-links are getting "flattened"

**Comment by pascalwengerter** [comment]
Also, maybe we can give #2222 another look in the process and finally resolve it through our E2E tests
