### ISSUE TITLE
"Buffer is not defined" in typescript files

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#6821]
Buffer is used in [useAppFileHandling.ts](https://github.com/owncloud/web/blob/96f6d068ebad9692a90174589f02ecc106f8164e/packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts#L73) for basic auth. It throws error "Buffer is not defined" and causes auth to fail. Because of this, external apps are not working in password protected public links

### Steps to reproduce
1. Create public link with password for a document that opens with an external app
2. Open public link
3. Open the document: error by external app

**Comment by elizavetaRa** [comment]
We have internally a [fix](https://github.com/cernbox/web/commit/668cdfd1aac301d29a37ec144e8c51eaa8c17d50) for that
which uses the "buffer" library. I found that it's also possible to polyfill buffer. Which would be the better solution?

**Comment by pascalwengerter** [comment]
Should already be fixed as part of https://github.com/owncloud/web/pull/6202
