### ISSUE TITLE
Falsy unexpected pass on oCIS link acceptance test

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6838]
`webUISharingPublicBasic/publicLinkEdit.feature:59` sometimes unexpectedly passes in CI (e.g. https://drone.owncloud.com/owncloud/web/25032/68/15, but I've seen it in other pipelines as well). Most likely this false positive was introduced by myself in https://github.com/owncloud/web/pull/6749 recently, but we should keep our eyes open and see if we can find out why

TL;DR of the test is "password enforcement for public links" via capabilities which isn't implemented in oCIS yet

**Comment by pascalwengerter** [comment]
Also occured multiple times in #6827 already, e.g. https://drone.owncloud.com/owncloud/web/25058/68/15

**Comment by SwikritiT** [comment]
closing this as duplication of https://github.com/owncloud/web/issues/6826
