### ISSUE TITLE
when creating new users make hitting enter go to the next field and hit the create button

### ISSUE THREAD

**Issue by butonic** [owncloud/web#6857]
currently creating a user requires using tab to switch to the next field and the final step moves the focus to the cancel button.

I don't know how compatible my wish is with accessibility best practice, but it would be great if:
- hitting enter changes focus to the next field, same as tab
- focus switches from the password to the create button instead of the cancel button or
- maybe we could create the user when hitting enter in the password field?

**Comment by AlexAndBear** [comment]
FYI Some of the suggestions are not a11y compliant

**Comment by AlexAndBear** [comment]
Closing this issue. All the suggestions are against a11y compliance. We can't do this.
