### ISSUE TITLE
Changing role of a public link with expiry date doesn't work 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6858]
### Steps to reproduce
1. Create a public link of a resource with an expiry date
3. Now try to change the role of the previously created public link

### Expected behaviour
The role should be changed with the message `Link was updated successfully `

### Actual behavior
 Two messages `Failed to update link` and `Link was updated successfully ` are displayed but the role is not updated. The behavior is the same for both backends

https://user-images.githubusercontent.com/41103328/166423561-2dc463f1-a86c-4f6b-a58f-cfa2ac6f4e96.mp4

**Comment by SwikritiT** [comment]
The test in this PR is failing because of this issue: https://github.com/owncloud/web/pull/6557
link to build: https://drone.owncloud.com/owncloud/web/25145/11/18

**Comment by pascalwengerter** [comment]
This issue isn't about a problem in `master` but about something blocking your PR, or am I reading this wrong?

**Comment by SwikritiT** [comment]
> This issue isn't about a problem in `master` but about something blocking your PR, or am I reading this wrong?

It is an issue in master. In my PR I was writing new tests for changing the role and this was caught. I can reproduce it in my local setup as well.

**Comment by pascalwengerter** [comment]
I can't from the steps you outlined above, also we do have acceptance tests on master that pass for this behaviour. 

Could you narrow it down whether it Is it related to the link being password-protected or having an expiry date? A freshly created public link can have role changes without errrors

**Comment by SwikritiT** [comment]
> I can't from the steps you outlined above, also we do have acceptance tests on master that pass for this behaviour.
> 
> Could you narrow it down whether it Is it related to the link being password-protected or having an expiry date? A freshly created public link can have role changes without errrors

It's because of the expiry date. Can you check again with the expiry date?

**Comment by pascalwengerter** [comment]
Thank you for raising it and further investigation, I'll take care of this issue

**Comment by ScharfViktor** [comment]
I reproduced it. Description is here: https://github.com/owncloud/web/issues/6865
