### ISSUE TITLE
Invalid DateTime blocks link changes

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6865]
ownCloud Web UI 5.5.0 
ocis via docker

Steps:

- admin creates folder
- admin creates public link to the folder **with expireDate** - link created
- admin tries to change link (add password, change name, change role)

Actual result: although response PUT `https://host.docker.internal:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/cUSVduEYKpWJQIg` get 200,  link does not change

![Screenshot 2022-05-03 at 15 51 01](https://user-images.githubusercontent.com/84779829/166466018-4261cb21-9389-4c9e-b4b6-0527ef3c3e5f.png)

![image](https://user-images.githubusercontent.com/84779829/166465970-b278d24f-7445-4541-9b51-53f13c04e94c.png)

**Comment by pascalwengerter** [comment]
Possibly very similar to https://github.com/owncloud/web/issues/6858

**Comment by ScharfViktor** [comment]
Yes, it's similar. closed in favor of https://github.com/owncloud/web/issues/6858
