### ISSUE TITLE
Navigation bar works incorrect

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6866]
ownCloud Web UI 5.5.0
ocis via docker v.1.20

Preparation:
- admin creates the space
- creates a folder inside the space
- uploads a file to the folder

Steps:
- Opens space
- Opens folder into the space: 

url look like: `https://host.docker.internal:9200/files/spaces/projects/1284d238-aa92-42ce-bdc4-0b0000009157$7b107017-9f83-40a9-b26f-958cc099b0ce/New%20folder?sort-by=name&sort-dir=asc&items-per-page=100`
and we see file

- click to the folder in the navigation bar ![Screenshot 2022-05-03 at 18 31 32](https://user-images.githubusercontent.com/84779829/166497667-363ad907-dccd-48bd-a95a-9f0fbf9f7b67.png)

url look similar: `https://host.docker.internal:9200/files/spaces/projects/1284d238-aa92-42ce-bdc4-0b0000009157$7b107017-9f83-40a9-b26f-958cc099b0ce/New%20folder?sort-by=name&sort-dir=asc&items-per-page=100`

but we can't see the file. The folder is not clickable. According to the url, we should be inside the folder

https://user-images.githubusercontent.com/84779829/166499594-c3b8c4a7-920e-4f85-b5ec-ce88d26b6c67.mov

**Comment by pascalwengerter** [comment]
Can confirm that this is still a bug - apparently, we don't add the correct link target to the last breadcrumb item
