### ISSUE TITLE
Dev-dockerized oCIS fails upon second (or further) startup

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6872]
### Steps to reproduce
1. Run `docker compose up ocis` in this repo, stop the container, start it again
2. See `Could not create config: config in /etc/ocis/ocis.yaml already exists` in the console, startup fails

### Expected behaviour
Either conditional running of init or conscious overwrite (since it's dev-only anyways and little to none custom configuration)

**Comment by ScharfViktor** [comment]
I can confirm. We should not run `osis init` again if `ocis.yaml` has already been created

How ease solution I can propose: https://github.com/owncloud/web/pull/new/startOcisAgainFix
