### ISSUE TITLE
Cannot run `oc10` using docker-compose

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#6878]
Running oc10 with: `docker-compose up oc10`
exists with error:
```bash
...
oc10_1             | Cloning into '/mnt/data/apps/testing'...
oc10_1             | testing enabled
oc10_1             | Cloning into '/var/www/owncloud/apps/oauth2'...
oc10_1             | /usr/bin/entrypoint: line 25: make: command not found
web_oc10 exited with code 127
```

**Comment by individual-it** [comment]
does it depend on what `OC10_IMAGE` is set to?

**Comment by kulmann** [comment]
Can't confirm this 🤔 

```
web_oc10           | make: Entering directory '/var/www/owncloud/apps/oauth2'
web_oc10           | /usr/bin/composer install --no-dev
web_oc10           | Installing dependencies from lock file
web_oc10           | Verifying lock file contents can be installed on current platform.
web_oc10           | Package operations: 1 install, 0 updates, 0 removals
web_oc10           |   - Downloading rowbot/url (1.1.1)
web_oc10           |   - Installing rowbot/url (1.1.1): Extracting archive
web_oc10           | Generating autoload files
web_oc10           | make: Leaving directory '/var/www/owncloud/apps/oauth2'
web_oc10           | oauth2 enabled
```

**Comment by pascalwengerter** [comment]
@saw-jan could you provide more details on your OS, docker (compose) versions and whether you have set a `OC10_IMAGE` env variable?

**Comment by saw-jan** [comment]
> Can't confirm this thinking
> 
> ```
> web_oc10           | make: Entering directory '/var/www/owncloud/apps/oauth2'
> web_oc10           | /usr/bin/composer install --no-dev
> web_oc10           | Installing dependencies from lock file
> web_oc10           | Verifying lock file contents can be installed on current platform.
> web_oc10           | Package operations: 1 install, 0 updates, 0 removals
> web_oc10           |   - Downloading rowbot/url (1.1.1)
> web_oc10           |   - Installing rowbot/url (1.1.1): Extracting archive
> web_oc10           | Generating autoload files
> web_oc10           | make: Leaving directory '/var/www/owncloud/apps/oauth2'
> web_oc10           | oauth2 enabled
> ```

Have you tried removing `web_oc10` and `owncloud/server` docker images?

**Comment by saw-jan** [comment]
My system info:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

`docker-compose version 1.29.2`
`echo $OC10_IMAGE` is empty

**Comment by pascalwengerter** [comment]
> My system info:
> 
> ```
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.4 LTS
> Release:	20.04
> Codename:	focal
> ```
> 
> `docker-compose version 1.29.2` `echo $OC10_IMAGE` is empty
> 
> Tried to `docker-compose up oc10` with another colleague, same problem (May be we are missing something here 😕 )

Removed all the oc10/oc-server docker images and now running into this as well 😅 nice!

**Comment by saw-jan** [comment]
So this is actually a problem.

**Comment by saw-jan** [comment]
IMO, `owncloud/server` might not need the `make` command to run.
In `web`, we use `make` to build the latest `oauth2` app (`dev/docker/oc10.entrypoint.sh`) and that's where the error comes from.
So, I made PR https://github.com/owncloud/web/pull/6879 to get `make` command
