### ISSUE TITLE
Moving and copying is not possible in the project space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6886]
ocil local  branch: v2.0.0-alpha1
ownCloud Web UI 5.5.0

Preparation:
- admin creates project space
- creates "new folder"
- creates "new file.txt"

Steps: 
- select new file
- click button "move" or "copy"
![Screenshot 2022-05-05 at 13 43 39](https://user-images.githubusercontent.com/84779829/166916745-41f94b90-6ac6-4bb0-a168-6a0bc312e001.png)
- click to "new folder" 
![Screenshot 2022-05-05 at 13 47 07](https://user-images.githubusercontent.com/84779829/166917237-65e8cce0-58fd-41cf-b59d-9ab04e3fc7f0.png)

### Actual result: no button, the copying/moving process is interrupted

**since** we have no other way to copy/move object in Project space (drug and drop doesn't implemented in project space), I think this issue is a critical priority

just in case, a video:

https://user-images.githubusercontent.com/84779829/166918772-168c43ef-6580-4d13-a6ff-e104fa128ec3.mov

**Comment by JammingBen** [comment]
Also see https://github.com/owncloud/web/issues/6892, which tackles the same topic, but a bit more general (as it also affects the new share jail).
