### ISSUE TITLE
Copy/move only works with personal space

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#6892]
With the [share jail](https://github.com/owncloud/web/pull/6593) being merged the `LocationPicker` view, which let's you select a target location for a copy or move action, only lists a single webdav endpoint, namely the personal space. As each accepted share and any project space have their own webdav endpoint we need to come up with a solution to list alternative target locations. This is a regression and needs to be tackled as soon as possible.

### Steps to reproduce
1. Visit personal space
2. Select "Copy" or "Move" in the right-click context menu of any file or folder

### Expected behaviour
Get presented with all available target locations and be able to navigate into any of their subfolders

### Actual behaviour
Only see the content of the personal space

### Things to consider
This is not just a matter of listing all available webdav endpoints in the `LocationPicker` view. It requires further UX adaoptions in the web UI. As a cross-storage-move in reality is a combination of `copy` and `delete` backend-side it is in fact a slow operation. Probably important to make this transparent to the user. One solution could be that our until now separated `Copy` and `Move` actions in the web UI get merged into one `Copy or move` action. The `LocationPicker` view could then have multiple submit buttons, depending on what operation is available in the target location, e.g. `Move`, `Copy` or `Copy and delete`.

### First step
Needs a clear UI/UX concept. Nothing to implement, yet.

### Followup tasks when this is done
- re-enable the `Copy` and `Move` actions in the spaces share route / `SharedResource` view

cc @tbsbdr @butonic

**Comment by kulmann** [comment]
This has been mitigated via keyboard actions which are available on all relevant views now (`Personal`, `shares/SharedResource`, `spaces/Project` and `PublicFiles`). This also enables cross-webdav-endpoint copy / move in the web ui.

**Comment by tbsbdr** [comment]
> This also enables cross-webdav-endpoint copy / move in the web ui.

awesome 🤩

**Comment by tbsbdr** [comment]
*   contextmenu cut/move
*   add "paste" to breadcrumb 3-dots context-menu
*   make context-menu available via click in white space if time / efforts permits
*   nice to have: show keyboard shortcuts in context menu

paste here button should be dismissable, eg via a drop menu or split button with "`X`"

![](https://user-images.githubusercontent.com/26610733/179768698-b88605f1-d16a-4710-bfa2-62588db7f004.png)

**Comment by tbsbdr** [comment]
@lookacat for a first step I'd propose to not show the "Paste here" button next to the upload button but only have the "paste here" option in the context menu (MVP: breadcrumb 3-dots)

I would like to test if users really need the "Paste here" button nextx to "Upload" (my bet: yes) but lets test it.

would that procedure be ok for you?

**Comment by lookacat** [comment]
ok

**Comment by tbsbdr** [comment]
*   move should only be possible within Spaces (not possible cross storage space)
*   needs ui representation and proper dialog @tbsbdr

**Comment by tbsbdr** [comment]
Proposals for the dialog.

## What title is best?
I favour option 2 "Short question" as it's the shortest for "Only Title Reading Users" and as it is not a negative (defect-orientated) wording but more positive, solution orientated.

### Negative:
![image](https://user-images.githubusercontent.com/26610733/189696217-f1afebab-1b23-4dcf-b5d1-66a390260914.png)

### Short question:
![image](https://user-images.githubusercontent.com/26610733/189696252-2272e057-b0a1-44fd-a888-8f91711cc2c1.png)

### Long question: 
![image](https://user-images.githubusercontent.com/26610733/189696277-17bf8424-60e1-484a-9500-23ea05609d5e.png)


The target for "Learn more" does not exist yet. Context-Helper could also do the job.

Any objections or additions against / to option 2 @lookacat @kulmann ?

**Comment by kulmann** [comment]
thank you for thinking this through @tbsbdr !

I'm also in favour of option 2 (same reasoning, simple, focused on solution, reading the title gives the most important information).

For the description I'd like to suggest that we find a more generic text which works for single- and multi-file move attempts. Something like `Moving files from one space to another is not possible. Do you want to copy instead?`. What do you think?

**Comment by tbsbdr** [comment]
yep, fine 👍 so lets go with:

![](https://imgr.whimsical.com/object/41Njv7Mr6fAekF7MnVNeWt)

**Comment by kulmann** [comment]
@lookacat thank you 😇 

@tbsbdr could you provide a mockup for the contextual helper?

**Comment by tbsbdr** [comment]
```
Shares, links, and versions of this item are not copied. Tags will be copied. The copied item will be visible to all who can see “Budget-Folder 2023”.
```

![](https://user-images.githubusercontent.com/26610733/190980937-6f926f61-e28e-4236-9ecd-1464b14bee05.png)
