### ISSUE TITLE
No share indicators inside share jail

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#6894]
With the [share jail](https://github.com/owncloud/web/pull/6593) being merged, navigating into a share (via shared with me view) doesn't show any share indicators anymore. Since we don't have re-sharing with oCIS and since anything that is inside a `SharedResource` view lives there because it was shared in the first place, might make sense to just not support share indicators in the `SharedResource` views.

### Steps to reproduce
1. As einstein, share a folder with marie
2. As marie, accept the shared folder
3. As marie, navigate into the shared folder

### Expected behaviour
I guess showing share indicators doesn't make sense. If at all, I'd expect share indicators for re-shared files/folders, but we don't support re-sharing with oCIS, yet.

### Actual behaviour
Well, no share indicators are being shown. Which makes sense to me, but need to be confirmed by @tbsbdr 

### Todo
As soon as we have re-sharing with ocis we want to have share indicators in the `shared with me` view.

**Comment by JammingBen** [comment]
Closing this as we already have the expected behavior by now:

![image](https://user-images.githubusercontent.com/50302941/181213712-f8b11fdc-7294-4389-998a-50a14fa1c61c.png)
