### ISSUE TITLE
e2e tests for shares with ocis share jail

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#6895]
With the [share jail PR](https://github.com/owncloud/web/pull/6593) being merged there are UX changes regarding how to access shares. In the process of merging the PR a few tests have been deleted in the nightwatch based test suite. They do make sense as smoke tests for oCIS, so we should invest some time to come up with reasonable new e2e (playwright based) tests for the deleted scenarios. But don't blindly re-implement, let's brainstorm the scenarios first.

## Scenarios now skipped on oCIS
- [`Scenario: change the file content of a received shared file`](https://github.com/owncloud/web/blob/ec17961dd2928c2522c37295b3f5b7850b33f45c/tests/acceptance/features/webUIFilesActionMenu/versions.feature#L77)

## Additional scenarios
- browse through an accepted share
- use file actions in accepted share, according to share permissions
- pending and declined shares cannot be browsed

**Comment by grgprarup** [comment]
Tests are implemented with this PR https://github.com/owncloud/web/pull/8142. So closing this issue.
