### ISSUE TITLE
Refactor e2e tests to put selectors in constants

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6908]
Right now we are using selectors whenever necessary like
https://github.com/owncloud/web/blob/8433aa347b30aefdd645d65d10a316ad6e702672/tests/e2e/support/objects/app-files/resource/actions.ts#L22-L23

it would be better if they were made into constants 

https://github.com/owncloud/web/blob/51f31888dff248a8fa5e10e3c3a5c79d116f39fc/tests/e2e/support/objects/app-files/link/actions.ts#L25-L39

todo:
- [ ] put all the selectors in constants and reuse them as required

**Comment by sushmita56** [comment]
All done!
