### ISSUE TITLE
Space image is showing for spaces without image

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#6920]
### Steps to reproduce
1. Create 2 spaces in the spaces overview
2. Set an image for only 1 of them
3. Open the sidebar of the space with the image
4. Now open the sidebar for the other space -> the other space will have the same image, although it doesn't have one

**Comment by pascalwengerter** [comment]
Can reproduce, seems like the watcher on `space.spaceImageData` doesn't do its job properly? 🤔
