### ISSUE TITLE
Re-fetch quota when it makes sense

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#6930]
### Steps to reproduce
1. Look at personal quota (user-menu) or project space quota (right sidebar)
2. Upload or delete files / folders
3. Repeat step 1

### Expected behaviour
The respective quota info should reflect the changes made in (2)

### Actual behaviour
Quota info remains unchanged

### Possible solutions
- we could re-fetch the respective quota after IO batches of operations are done
- we could use the client-side available filesize info to re-calculate the quota info instead of re-fetcing the quota to save network requests

**Comment by pascalwengerter** [comment]
Tried doing some investigation. Some finds
- we do fetch the quota upon completed upload on https://github.com/owncloud/web/blob/899782677731942861e3c4b979c7c83c8b49058c/packages/web-app-files/src/components/AppBar/CreateAndUpload.vue#L328 - however, this only works in oC10 for me, oCIS seems to always return the same (relative) quota; it also sometimes sends _a lot_ of requests to re-fetch user/quota information
- we should probably fetch it after emptying the (personal) trashbin or deleting resources there. Other actions than uploading and (ultimately) deleting resources don't have implications on the quota, amirite?

**Comment by tbsbdr** [comment]
decision: refetch quota after upload has finished.

**Comment by JanAckermann** [comment]
@tbsbdr whats about deleting files?

**Comment by tbsbdr** [comment]
iirc @kulmann and I discussed that the problem is, that we don't want to generate too many requests just to have the quota up-to-date.

refetch quota after deletion of a file would be cool, sure but in case of batch-delete we would need some debounce I guess.

So: the quota should get updated after delete-operation only if the costs are low I'd say. whats your opinion, @kulmann ?

**Comment by JanAckermann** [comment]
Checked that, the cost is low, as I only make one request after batch delete

**Comment by JanAckermann** [comment]
Relative in OCIS gets wrong calculated, see https://github.com/owncloud/ocis/issues/4357
