### ISSUE TITLE
webUICreateFilesFolders/createFile.feature:31 is flaky

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#6931]
webUICreateFilesFolders/createFile.feature:31 started to fail in various runs
e.g. https://drone.owncloud.com/owncloud/ocis/11662/50/9
but also https://drone.owncloud.com/owncloud/web/25461/56/16

**Comment by kulmann** [comment]
Running the test locally (dockerized dev setup) shows that the web ui looks good (see screenshot). Log output states
```
Error while running .isElementDisplayed() protocol action: The command failed because the referenced element is no longer attached to the DOM. – stale element reference
```

<img width="1498" alt="Screenshot 2022-05-10 at 15 50 06" src="https://user-images.githubusercontent.com/3532843/167644607-092deee9-a1c4-40e5-8815-c361145a12de.png">
