### ISSUE TITLE
Directories in search result can not be used for navigation

### ISSUE THREAD

**Issue by aduffeck** [owncloud/web#6944]
When searching for directories the found entities show up in the result list, but clickin the directory name will not take you to the according directory but stay at the result page. 

### Steps to reproduce
1. Create a new directory "foo"
2. Search for "foo" across all files
3. Find the "foo" result in the list and click on the directory name

### Expected behaviour
The web app should navigate to and open the according folder.

### Actual behaviour
The web app stays at the result page, clicking the link has no effect.

**Comment by JanAckermann** [comment]
Closing, @aduffeck and me discussed that this is a backend issue
