### ISSUE TITLE
[QA] notifications requests are sent to the server, even when the notifications app is disabled

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#6966]
Seen with core 10.10.0 RC2 and web 5.4.0

* open file view in new WebUI
* check browser network console. Notificaitons are polled.
* occ app:disable notifications
* force reload the web page.
* Notification requests continue, but result in error 500
![image](https://user-images.githubusercontent.com/1108546/168250502-6339e73e-90d2-42fd-9770-bcb5137cfc84.png)

Expected behaviour: 
* webUI knows if notifications are supported or not, and stops sending requests, if not.

**Comment by pascalwengerter** [comment]
Does disabling notifications not disable them in capabilities (that's what `web` uses to figure whether it can fetch notifications from the backend IIRC)? Anyways, both quickly fixed (I hope) and irrelevant for oCIS GA

**Comment by kulmann** [comment]
With https://github.com/owncloud/web/pull/7072 being merged capabilities get reloaded on page reload, which fixes this issue.
