### ISSUE TITLE
click on share-indicator in files list should scroll

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6968]
### Steps to reproduce
1. login to https://ocis.ocis-wopi.released.owncloud.works/
2. share a folder with a person and also via link
3. click on "Link" or "People" share indicator
4. Right sidebar always shows "Shares" Panel with section "Share with people" on top

### Expected behaviour
Tell us what should happen
1. If click on Link-share indicator in files list and "Share via link" section is not visible, browser should scroll to "Share via link" section
2. If click on People-share indicator in files list and "Share with People" section is not visible, browser should scroll to "Share with People" section

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/26610733/168289320-0c0b5d70-e8ea-4246-b044-4b6fb8f702b7.png">

### Actual behaviour
Tell us what happens instead
- scrolling happen never, regardless on which indicator you click.

**Comment by pascalwengerter** [comment]
Test case for this should involve a lot of people shares and an expanded people share list (to make the problem more obvious, it's limited to the `link` share indicator)
