### ISSUE TITLE
Navigation in project spaces doesn't work via hrefs

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#6972]
When doing a PROPFIND inside a project space, web doesn't use the `href` returned in the response to further navigate inside the project, but rather frames its own URL using the `fileid`. Instead it should use the href field

**Comment by kulmann** [comment]
Agreed, this is an important issue. Unfortunately this requires quite some refactoring in the `owncloud-sdk`, which currently gets initialized with one single dav endpoint, then only accepts relative dav paths and concatenates those.

**Comment by kulmann** [comment]
@ishank011 is this blocking for you? We have no one working on this so far. What exactly is it blocking and can we otherwise mitigate the issue in a different way until we have the refactoring in SDK done?

**Comment by ishank011** [comment]
Hi @kulmann. The issue is that web constructs requests with the space ID being read from the `oc:fileid` field and then the relative path read from the suffix of the `href` field.

In the EOS spaces implementation, we're trying to use exact identifiers for nodes inside a space, rather than go to a space and then to a relative path. As a result, the resource IDs in the `href` and `oc:fileid` fields are different. Either of these two options could solve this issue:
- Use the href as is.
- Only use the resource ID sent in `oc:fileid`, and not append any paths. Assume that a space identified by `oc:fileid` exists and would be returned by the server.

**Comment by labkode** [comment]
I think the title of this issue says it all:
```
When doing a PROPFIND inside a project space, web doesn't use the href returned in the response to further navigate inside the project, but rather frames its own URL using the fileid. Instead it should use the href field
```

So is up to the web team to honour the href.

**Comment by labkode** [comment]
@dragotin I read it and unfortunately we cannot provide a workaround as we halted all work on the Spaces, as you know. This issue only affects Spaces, therefore, my previous comment still applies, the web team should identify the most pragmatic approach to fix this issue. If a workaround is needed on the server side, I suggest @kulmann to follow-up with @micbar on how to provide it.
This issue does not affect the deployments based on master.

**Comment by JammingBen** [comment]
Closing here since we're using the `href` meanwhile. Feel free to re-open if anything is still unclear or not working.
