### ISSUE TITLE
[QA] drawio fails to load

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#6988]
Seen in web 5.4.0 with core 10.10.0 RC2, while attempting to test https://github.com/owncloud/core/pull/40024
Also seen with web-4.8.0 and web-5.5.0-rc.6 and web-7.0.3

* Setup according to https://owncloud.dev/clients/web/deployments/oc10-app/
* Click new -> draw io file
   * firefox requests permission to open a new page, It then  shows only a white area in the blue frame.
   * chrome shows an error to the user: This content is blocked. Contact the site owner to fix the issue.
* Same when clicking on a drawio file that is known to work.

![image](https://user-images.githubusercontent.com/1108546/168768543-29981247-a668-48dd-9ad1-ea35b37ddc96.png)
----
![image](https://user-images.githubusercontent.com/1108546/168767216-ae58cb29-42cd-458f-a27b-be23469ab49d.png)
----

Expected behaviour:
* The required settings for correct content security policy directive are either automatic or mentioned in the docs.

**Comment by pascalwengerter** [comment]
@jnweiger could you post the contents of your config.json file used for web? I'm curious how web.owncloud.com is configured since I can not find the pointed-out problems there

**Comment by jnweiger** [comment]
config/config.json
```
{
  "server" : "https://oc10100rc2-web-20220512.jw-qa.owncloud.works",
  "theme": "https://oc10100rc2-web-20220512.jw-qa.owncloud.works/themes/owncloud/theme.json",
  "auth": {
    "clientId": "w5aynl5qtruquh7jl42rexeicxxdcuyg",
    "url":     "https://oc10100rc2-web-20220512.jw-qa.owncloud.works/index.php/apps/oauth2/api/v1/token",
    "authUrl": "https://oc10100rc2-web-20220512.jw-qa.owncloud.works/index.php/apps/oauth2/authorize"
  },
  "apps" : [
    "files",
    "preview",
    "draw-io"
  ],
  "applications" : [
    {
      "title": {
        "en": "Classic Design",
        "de": "Klassisches Design",
        "fr": "Design classique",
        "zh_CN": "文件"
      },
      "icon": "swap-box",
      "url": "http://oc10100rc2-web-20220512.jw-qa.owncloud.works/index.php/apps/files"
    },
    {
      "icon": "settings-4",
      "menu": "user",
      "target": "_self",
      "title": {
        "de": "Einstellungen",
        "en": "Settings"
      },
      "url": "https://oc10100rc2-web-20220512.jw-qa.owncloud.works/index.php/settings/personal"
    }
  ]
}

**Comment by pascalwengerter** [comment]
On your instance, when opening the draw-io file, I can see the following URL
`https://<server-url>/index.php/apps/web/index.html#/draw-io/files/admin/untitled.drawio?contextRouteName=files-spaces-personal-home&contextRouteParams.storage=home`

While on web.owncloud.com, the draw-io URL looks like this
`https://<server-url>/index.html#/draw-io/files/demo/untitled.drawio?contextRouteName=files-spaces-personal-home&contextRouteParams.storage=home`

I don't exactly know where the `/index.php/apps/web/` part in your URL comes from, but I suspect that this is the reason things don't work as expected?

**Comment by jnweiger** [comment]
I have to use `index.php/apps/web` in `'web.baseUrl' => 'https://oc10100rc2-web-20220512.jw-qa.owncloud.works/index.php/apps/web',` so that login works.

Workaround:
 - When drawio hangs with a blank page, removing the path component `/index.php` from the URL and hit ENTER. Then drawio loads as expected.


Maybe there is a required combination of variables that I do not yet know....
