### ISSUE TITLE
[QA] German translations only translate one word

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#6990]
Seen in web 5.4.0 with core 10.10.0 rc2 - also seen with web 4.8.0 and web 5.5.0 rc.6

* Classic UI, switch to German. (persönlich or förmlich, same effect)
* New Design
* Everything is still English. BAD
* Click open the app-switcher. "Aktivität" is the only German word. 
![image](https://user-images.githubusercontent.com/1108546/168784564-ba460d85-b7cd-4e0d-8ba9-b0b6a5df3ce7.png)
----

Expected behaviour:
* All or nothing

**Comment by pascalwengerter** [comment]
Duplicate to #6243, the few translations you see got to be coming from their respective oc10 apps

**Comment by jnweiger** [comment]
Same with French :-)
![image](https://user-images.githubusercontent.com/1108546/168787292-a6d08a11-7c79-4a9d-bb64-73ec5d7d45db.png)
