### ISSUE TITLE
Sharing sidebar looks crowded

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#6992]
Seen with web 5.5.0 rc.6 and core 10.10.0 RC2

I am not a we designer, but the new Web UI has in general a very organized and clean look.
the sharing sidebar seems to be an exception, with multiple elements very close together, some of them overlapping.

![image](https://user-images.githubusercontent.com/1108546/168804174-f3508e20-9f36-4fd7-9ed9-a3aaf218fb38.png)

Despite this seen on a desktop computer, it works very well on the small screen of my Android device.

**Comment by JammingBen** [comment]
Closing here as described above, the "issue" has been addressed meanwhile:

![image](https://user-images.githubusercontent.com/50302941/198252423-050d4b71-b43c-45e9-8a20-127c36461697.png)
