### ISSUE TITLE
Search in folder adds "ghost" spaces to the page

### ISSUE THREAD

**Issue by micbar** [owncloud/web#6995]
### Steps to reproduce
1. Create A Folder in "personal" with  a lot of files with similar names
2. Search for a string which is present in most of the files
3. Go to the "Spaces" View

### Expected behaviour
See the existing spaces only

### Actual behaviour
I see all search results from 2 rendered as "spaces"
![1652798743154](https://user-images.githubusercontent.com/4378513/168840784-4fd4ac58-4482-4b7f-9315-2dc41388b35b.png)

### Environment general

- https://ocis.ocis-wopi.latest.owncloud.works
-  ownCloud Web UI 5.5.0-rc.6
-  Infinite Scale 0.0.0+61b9b6c96 Community

**Comment by pascalwengerter** [comment]
I guess that has to do with `activeFiles` in https://github.com/owncloud/web/blob/31e62e18237871344e5a1b0755114100cb9a5458/packages/web-app-files/src/views/spaces/Projects.vue#L154 which are present in the store before `loadResourcesTask` loads the spaces themselves (curious why those don't get replaced though)
