### ISSUE TITLE
Upload of folder with same name shows error

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#6996]
# Steps to reproduce
1. Login to https://ocis.ocis-wopi.released.owncloud.works/
2. Create a new folder "Folder" on the ocis instance and on your local drive.
3. upload your local "Folder" folder
4. upload does not start, shows error "Folder "Folder" already exists."
![image](https://user-images.githubusercontent.com/26610733/168844306-c51c1723-77e3-499c-9083-73b4d26ca93f.png)

# Expected behaviour
System should offer me alternative options to upload the folder.
The appropriate dialogues are consistently shown in case of conflicting resources, eg. in context of:
- [ ] Drag'n drop upload
- [ ] upload via upload-button
- [ ] move-dialog
- [ ] copy-dialog
- [ ] trashbin-restore
- etc... 

## General rule
**User gets asked what to do in case of conflicting resources**, as there is no common pattern across different services/platforms (OneDrive, Google Drive, Box, Windows, Mac, etc. - all different).

**Note** This dialog concept is also meant to be applied to https://github.com/owncloud/web/issues/1753

## Dialogs

![image](https://user-images.githubusercontent.com/26610733/168789953-c5d8d37a-5ceb-44ee-954f-0a72e310b476.png)

## Behaviour
1. **Replace** will replace the existing file (and creates a new version implicitly).
2. **Keep both** will create a new resource with an appended number "(xx)" - counting up, if ex. (2) already exists.
3. **Cancel** will skip the current resource, if applicable shows the next conflict.
4. **Merge** will combine folders with the same name; if they contain conflicting files, user gets asked what to do (dialog for files shows up).
5. **Do this for all XX conflicts** will apply the selected option to all XX upcoming conflicts. Is only shown, if there are at least 2 conflicts. 
6. **generally applicable:** The 

## Userflows
![image](https://user-images.githubusercontent.com/26610733/168798364-d4913c33-f1d7-4665-8a92-2c4b07106259.png)

____________
**solves:**
https://github.com/owncloud/web/issues/3751
https://github.com/owncloud/web/issues/5761
https://github.com/owncloud/web/issues/5106
https://github.com/owncloud/web/issues/6546

**groundwork for**
https://github.com/owncloud/web/issues/1753

**Comment by kulmann** [comment]
We can't implement "merge" with reasonable effort or performance at the moment. Will be ignored for the initial implementation. Instead we're using our usual conflict resolve dialog with `Skip` (multiple files/folders) / `Cancel` (single file/folder), `Overwrite` and `Keep both` as options.

**Comment by tbsbdr** [comment]
👍 perfect

(I guess you mean `Replace` - not `Overwrite`)

![](https://user-images.githubusercontent.com/26610733/188568204-8d06ec63-9957-465b-a132-b4e7da648d82.png)

**Comment by kulmann** [comment]
> (I guess you mean `Replace` - not `Overwrite`)

yes 😅
