### ISSUE TITLE
Update expected to fail file to use the correct issue for failing tests

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#7011]
Issue https://github.com/owncloud/ocis/issues/1330 has been closed but we still have it referenced in the expected to fail file and we need to update it.

https://github.com/owncloud/web/blob/b8e3ccfd4dca7bcadc5c7cc80db734b810da8b9a/tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md?plain=1#L18-L38

ToDo
- [ ] find/create the correct issue for the failing tests
- [ ] reference the correct issue in the expected to fail file in both ocis and web
- [ ] try to find if there are other issues that are closed but still referenced in the expected to fail and update those as well

**Comment by kiranparajuli589** [comment]
can be continued after https://github.com/owncloud/ocis/issues/3907.

**Comment by SwikritiT** [comment]
Since we decided that we're no longer going to be updating the expected failures with new issues, this issue seems irrelevant now. We'll be removing the still failing scenarios that are linked to the closed issue in expected to fail and create a separate issue to add the removed tests in Playwright. 

cc: @individual-it @phil-davis
