### ISSUE TITLE
make CI work with owncloud 10.10

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#7019]
web tests failed with owncloud 10.10 in https://drone.owncloud.com/owncloud/web/25725/34/13 (trashbin) and oC10 was pinned to 10.9.1 in #7016

need to investigate what is different with trashbin in 10.9 and 10.10 and why the tests fail

**Comment by individual-it** [comment]
first try in #7020

**Comment by phil-davis** [comment]
Note: this could be one of the 10.10.0 changes that impacts on a client:
Bugfix - Default for propfind depth infinity adjusted: [#40016](https://github.com/owncloud/core/pull/40016)

That is now disabled by default. The setting is advertised in capabilities, but if a client does not check the capabilities setting then it may send depth-infinity requests and they will not work. Work-around would be to enable depth-infinity in CI. But clients should really have code to check the capabilities.

**Comment by saw-jan** [comment]
> first try in #7020

CI passed. Maybe there's no more task to do?

**Comment by individual-it** [comment]
CI is green after #7020
further discussion is needed to decide if that is a bug or a feature, see https://github.com/owncloud/web/issues/7029
