### ISSUE TITLE
web needs dav.propfind.depth_infinity set to true on oC 10.10

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#7029]
OC 10.10 by default does not allow to request depth=infinity in PROPFIND (oc10 replies with 412) see https://github.com/owncloud/core/pull/40016

web (and SDK) needs that somewhere, so it got enabled in CI
see https://github.com/owncloud/web/pull/7020 & https://github.com/owncloud/owncloud-sdk/pull/1058

need decision about if that is a required setting to be used in web or if that is a bug

CC @kulmann @pascalwengerter @fschade @pmaier1

**Comment by phil-davis** [comment]
Basically need to answer this:

When running web and oC10 together, do we:
1) require that the installed oC10 must have depth infinity PROPFIND enabled, or
2) enhance the web code so that it looks at the capabilities settings, and behaves accordingly

**Comment by phil-davis** [comment]
> afaik web only ever uses propfinds with depth 0 or 1 thinking

Then we need to investigate exactly what fails when depth infinity PROPFIND is disabled on the oC10 system-under-test.

@individual-it maybe there is some middleware step that is used in scenario setup Given steps somewhere that ends up doing some of its work using infinite depth PROPFIND?

If so, then the step implementation will need to understand what to do when infinite depth PROPFIND is not available.

**Comment by individual-it** [comment]
You are right, I can see 'infinity' being used by default in trashbin actions in the middleware https://github.com/owncloud/owncloud-test-middleware/blob/6257acc453f54f1cf8ecb9572ef04b2fc1227078/src/helpers/webdavHelper.js#L137
Need to find out if that is the only place, because I recall that we had the issue in the SDK also and the middleware is not used there

ToDo:
- [ ] find where depth=infinity is used in SDK tests
- [ ] find where depth=infinity is used in web tests
- [ ] get rid of the dav.propfind.depth_infinity setting in SDK CI
- [ ] get rid of the dav.propfind.depth_infinity setting in web CI

**Comment by individual-it** [comment]
I think we are done here, anything left @SagarGi ?

**Comment by SagarGi** [comment]
@individual-it  all the things in ToDo mentioned on the above things have been covered. so we can close this issue.
