### ISSUE TITLE
e2e-test-story. participant management

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7035]
steps:

- [x] admin adds role "space manager" to Alice 
- [x] Alice creates project space
- [x] Alice add member Brian with editor role
- [x] Alice add member Carol with viewer role
- [x] Brian creates folder and upload file1 to the folder
- [x] Carol can see folder with file. can preview/download but cannot edit
- [x] Alice creates public link with editor role. Members cannot see public link. Here is bug https://github.com/owncloud/web/issues/7040
- [x] Public can upload file2 to folder
- [x] Public deletes file1
- [x] Brian deletes file2
- [x] Carol can see deleted file2 in trash, but cannot empty trash or restore @SwikritiT https://github.com/owncloud/web/pull/7118
- [x] Brian can restore file2 @SagarGi https://github.com/owncloud/web/pull/7124
- [x] Alice removes access to Brian https://github.com/owncloud/web/pull/7124
- [x] Brian cannot see space https://github.com/owncloud/web/pull/7124
- [x] Alice changes role Carol to manager. https://github.com/owncloud/web/pull/7124
- [ ] After that, Alice can delete her access https://github.com/owncloud/web/pull/7637

https://user-images.githubusercontent.com/84779829/169807407-754cbbca-82fd-4f17-8db4-6062f086c5c1.mov

**Comment by ScharfViktor** [comment]
@SwikritiT

**Comment by SagarGi** [comment]
The final step is blocked due to this issue. https://github.com/owncloud/web/issues/7163

**Comment by SagarGi** [comment]
@SwikritiT @ScharfViktor i am shifting this to backlog since final step is blocked with the above issue.This can be brought back when the above issue is solved.

**Comment by SwikritiT** [comment]
The blocking issue has been closed https://github.com/owncloud/web/issues/7163

**Comment by SwikritiT** [comment]
Removing yourself from a space is possible from the UI but there's a backend problem as the user still has access to the space even after being removed from it https://github.com/owncloud/ocis/issues/4127 so this issue is blocked again

**Comment by ScharfViktor** [comment]
I tried to add the last step, but #7534 blocks it

**Comment by SwikritiT** [comment]
the blocking issue #7534 has been closed, I'll implement the remaining step
