### ISSUE TITLE
Slow file list update after uploads

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#7037]
### Steps to reproduce
1. Upload 1000 small files to a folder
2. wait until the data transfer is complete

### Expected behaviour
1. The file list updates immediately
2. The upload progress widget has all uploaded files visible (including the uploaded files count in the title) immediately

### Actual behaviour
1. It takes ages until the file list is up to date. The yellow highlighting of the files that have been added to the files list happens one by one and in random order.
2. The upload widget inserts their finished files and increments the counter in the title one by one.

**Comment by kulmann** [comment]
Probably related: https://github.com/owncloud/web/issues/5882

**Comment by JammingBen** [comment]
Should be fixed via https://github.com/owncloud/web/pull/7067
