### ISSUE TITLE
Slow loading state of file list

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#7038]
### Steps to reproduce
1. Navigate into a folder with 1000 files

### Expected behaviour
When the network request (propfind) is done the file list is visible and usable in a timely manner.

### Actual behaviour
The file list takes ages to render and even a little bit longer until the first interaction is possible (e.g. context menu).

### Action items / hints
- [ ] check if loading previews blocks the UI (especially on scroll)
- [ ] analyse what exactly takes so long after the initial propfind is done. we thought that the lazy loading of cells would improve render speed a lot, but it did not
- [ ] There seem to be a lot of events, causing (partial) re-renders (-> have a look at events in vue dev tools)
- [ ] Collecting all the different tr/td attributes in `OcTable` is apparently not cached, this might be a huge issue

**Comment by kulmann** [comment]
Probably best to solve this in a narrow scope: https://github.com/owncloud/owncloud-design-system/pull/1867

**Comment by pascalwengerter** [comment]
I've done some digging and also opened #7056 (which doesn't even seem to work now, apparently caching made it seem like it worked the other day), pretty convinced that while the OcTable/ResourceTable rendering adjustments do have some positive impact the real culprint seems to be the `loadIndicators` logic. From how I understood it, we
- load resources (network request)
- save resources to store (triggers Vue rendering)
- purge parts of the store related to share status of resources (triggers Vue rendering)
- load indicators (network request)
- save indicators to store by running a for-loop over all available resource (triggers Vue rendering)

There's a [comment](https://github.com/owncloud/web/blob/f4320705d53ba2aea4b79728c042cdeac04e95d3/packages/web-app-files/src/store/actions.js#L636) hinting at room for performance improvements by changing that logic, but there's a lower-hanging fruit from what I've seen: 

[We don't seem to run into the `continue` condition when saving indicators to the store](https://github.com/owncloud/web/blob/716a475d90ff40e6121fedcca29cd41b3bc70c11/packages/web-app-files/src/store/mutations.js#L233) - this leads to an insane amount of store commits, see screenshot below

<img width="334" alt="Screenshot 2022-05-26 at 12 33 35" src="https://user-images.githubusercontent.com/16822008/170471219-ff3277f4-03b7-49e4-8872-ff6290d0839b.png">

Ideally for now, we can reduce the continue-logic to `if (!indicators.length) { continue }` to not modify the store if there is no shareIndicators to be added/loaded

We could also discuss if we can request the share-status with the initial resource request from the backend maybe? That'd be the most performant solution I can imagine

**Comment by kulmann** [comment]
classic ui does it the right way already: using the "shareTypes" field from the propfind (= direct shares) and then doing an ocs shares request for each parent folder up to the root (= indirect shares). We should adopt the same.

**Comment by kulmann** [comment]
Apart from that I'm still convinced that the rendering itself is slow. See the ODS PR for lazy loaded icons documentation page using the OcTable without any reactivity in the data. 😅

**Comment by pascalwengerter** [comment]
> Apart from that I'm still convinced that the rendering itself is slow. See the ODS PR for lazy loaded icons documentation page using the OcTable without any reactivity in the data. 😅

Played around by replacing the table subcomponents with (mostly) canonical HTML tags and while it looses the shimmering lazy-loading, rendering then happens _ultra_fast. Might also help that I removed the 6*2275 onclick-listeners on the OcIcon instances 😄

**Comment by kulmann** [comment]
> > Apart from that I'm still convinced that the rendering itself is slow. See the ODS PR for lazy loaded icons documentation page using the OcTable without any reactivity in the data. 😅
> 
> 
> 
> Played around by replacing the table subcomponents with (mostly) canonical HTML tags and while it looses the shimmering lazy-loading, rendering then happens _ultra_fast. Might also help that I removed the 6*2275 onclick-listeners on the OcIcon instances 😄 

![image](https://user-images.githubusercontent.com/3532843/170989774-1b74b30f-e464-4d12-96a1-71a539dd5229.png)

**Comment by pascalwengerter** [comment]
> > > Apart from that I'm still convinced that the rendering itself is slow. See the ODS PR for lazy loaded icons documentation page using the OcTable without any reactivity in the data. 😅
> > 
> > 
> > Played around by replacing the table subcomponents with (mostly) canonical HTML tags and while it looses the shimmering lazy-loading, rendering then happens _ultra_fast. Might also help that I removed the 6*2275 onclick-listeners on the OcIcon instances 😄
> 
> ![image](https://user-images.githubusercontent.com/3532843/170989774-1b74b30f-e464-4d12-96a1-71a539dd5229.png)

https://github.com/owncloud/owncloud-design-system/pull/2165/commits/614318840bc75e311d811c8687775e82e1d3ddb4 not part of master since it's a breaking change

**Comment by tbsbdr** [comment]
@pascalwengerter sound like promising research ✨ Where is this currently on your prio list? I would be happy to provide a fast fileslisting for users as it affects the experience all the time.

CC @d7oc reading the thread above doesn't sound like what we discussed but maybe I'm wrong.

**Comment by tbsbdr** [comment]
> Where is this currently on your prio list?

ping @pascalwengerter

**Comment by tbsbdr** [comment]
wohaa, really good progress again!

- for 1.000 (and even 2.000 files) scrolling feels already fast enough. would still need some testing, buts fast enough on my machine I would say. awesome!
- the time after the login screen until I see the first file (with 1.000 items-pagination) takes ~5.6 seconds on my side which feels already to long.

... just sharing my experience

![Screenshot 000049@2x](https://user-images.githubusercontent.com/26610733/180437153-e8ca989a-8f4d-4abb-ad94-376c29dc2202.png)


https://user-images.githubusercontent.com/26610733/180435015-33fb059f-5c7d-4335-b48a-602241e4310e.mp4

**Comment by tbsbdr** [comment]
as remedy until we do the vue3 update: lets remove the pagination options:

*   ~1000~
*   ~all~

**Comment by JammingBen** [comment]
> as remedy until we do the vue3 update: lets remove the pagination options:
> 
> * ~1000~
> * ~all~

https://github.com/owncloud/web/pull/7597

How do further progress with this ticket? While this is still "an open thing", I think we're good in regards to GA.

**Comment by kulmann** [comment]
@JammingBen can be closed when #7597 is merged. The vue3 update is its own issue and after that's done we can create a new ticket for performance improvements as needed.
