### ISSUE TITLE
Async interactions - fix "hanging" UI during long running actions

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#7039]
Async tasks currently have the tendency of blocking the UI. The also get hibernated by the browser when the tab becomes a background tab.

Needs e.g. web workers / separate threads for:
- copy
- move
- delete (especially in batch)
- upload

**Comment by kulmann** [comment]
Related: we want progress indicators for those interactions, see https://github.com/owncloud/web/issues/6183

**Comment by kulmann** [comment]
For whoever works on this: have a look at https://github.com/GoogleChrome/workbox first

**Comment by ScharfViktor** [comment]
When a user deletes a large number of files, the web looks like it is hanging.

- dialog "delete files" hangs
- web is disabled while deleting process
- If we click "cancel" button -> deleting process will contunue until all files are deleted

**Comment by lookacat** [comment]
Related: https://github.com/owncloud/web/pull/7902

**Comment by kulmann** [comment]
Related / a very good reason for Web Workers: https://github.com/owncloud/ocis/issues/8427#issuecomment-1939668580

**Comment by tbsbdr** [comment]
Needs research first

**Comment by JammingBen** [comment]
Closing in favour of these stories:

* https://github.com/owncloud/web/issues/10951
* https://github.com/owncloud/web/issues/10952
* https://github.com/owncloud/web/issues/10953
