### ISSUE TITLE
Broken links in search results from shares

### ISSUE THREAD

**Issue by aduffeck** [owncloud/web#7043]
With the switch to the share jail the links to the parent directoy in search results from shares became broken.

### Steps to reproduce
1. Create a folder `shared` containing some file and share it with another user.
2. As that other user search for the filename of the file in `shared`

### Expected behaviour
The parent directory shows up as `shared` and clicking it takes me to `https://localhost:9200/files/spaces/shares/from-einstein`.

### Actual behaviour
Search finds the file and previews work, but the link to the parent directory is wrongly named `Persönlich` and clickin it leads to e.g. `https://localhost:9200/files/spaces/personal/home/`.

**Comment by JammingBen** [comment]
Currently on hold as it needs a way to fetch the parent share for files within a share. @fschade is currently building something for this if I'm not mistaken.

**Comment by SwikritiT** [comment]
Also, if I click on the file name from the `Shares` page, it downloads the file, but if I click to personal and click on the file name, it opens the file. 



https://user-images.githubusercontent.com/41103328/188800941-3ff1f07e-d843-4014-b42e-86c13ece5f65.mp4

While in the case of `folder` clicking on the file name navigates to the personal space.

**Comment by JanAckermann** [comment]
@SwikritiT it even goes deeper, if you hit the search all files button and enter a new term, click on a file, nothing will happen (besides console error).

**Comment by SwikritiT** [comment]
I've also created another issue related to searching in public link don't know if these might be related https://github.com/owncloud/web/issues/7603
