### ISSUE TITLE
webUIResharing2/reshareUsers.feature:29 fails in nightly

### ISSUE THREAD

**Issue by Talank** [owncloud/web#7047]
failed in https://drone.owncloud.com/owncloud/web/25812/21/20

```
Scenario: Reshare a folder without share permissions using API and check if it is listed on the collaborators list for resharer # features/webUIResharing2/reshareUsers.feature:29
   ✔ Before # setup.js:41
   ✔ Before # setup.js:45
   ✔ Before # setup.js:49
   ✔ Before # setup.js:66
   ✔ Before # setup.js:73
   ✔ Before # setup.js:84
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:199
   ✔ Before # stepDefinitions/generalContext.js:237
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And the administrator has set the default folder for received shares to "Shares" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And these users have been created with default attributes and without skeleton files in the server: # stepDefinitions/middlewareContext.js:76
       | username |
       | Alice    |
       | Brian    |
       | Carol    |
   ✔ And user "Brian" has created folder "simple-folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Brian" has shared folder "simple-folder" with user "Alice" with "read, share" permissions in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has accepted the share "Shares/simple-folder" offered by user "Brian" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has shared folder "Shares/simple-folder" with user "Carol" with "read" permissions in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Carol" has accepted the share "Shares/simple-folder" offered by user "Alice" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:64
   ✔ And the user opens folder "Shares" using the webUI # stepDefinitions/filesContext.js:155
   ✔ When the user opens the share dialog for folder "simple-folder" using the webUI # stepDefinitions/sharingContext.js:588
   ✖ Then user "Carol King" should be listed as "Custom permissions" in the collaborators list for folder "simple-folder" on the webUI # stepDefinitions/sharingContext.js:703
       AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
       + actual - expected

       + 'Custom permissions'
       - false
           at /var/www/owncloud/web/tests/acceptance/stepDefinitions/sharingContext.js:115:16
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
   - And no custom permissions should be set for collaborator "Carol King" for folder "simple-folder" on the webUI # stepDefinitions/sharingContext.js:322
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:255
   ✔ After # stepDefinitions/generalContext.js:224
   ✔ After # stepDefinitions/generalContext.js:165
   ✔ After # setup.js:117
   ✔ After # setup.js:113
   ✔ After # setup.js:109
   ✔ After # setup.js:102
   ✔ After # setup.js:93
   ```

**Comment by SagarGi** [comment]
Same fails while merging this PR https://drone.owncloud.com/owncloud/web/25793/21/20

**Comment by saw-jan** [comment]
Looks like the selector has some issue. I will create a PR for the fix.

**Comment by saw-jan** [comment]
New findings:
Sometime the elements for Role is:
```html
<span>
  <button>
    <span>Custom permissions</span>
  </button>
</span>
```

And sometimes it is:
```html
<span>
  <span>Custom permissions</span>
</span>
```

**Comment by kulmann** [comment]
> New findings: Sometime the elements for Role is:
> 
> ```
> <span class="files-collaborators-collaborator-role">
>   <button class="files-recipient-role-select-btn">
>     <span>Custom permissions</span>
>     ...
>   </button>
> </span>
> ```
> 
> And sometimes it is:
> 
> ```
> <span class="files-collaborators-collaborator-role">
>   <span>Custom permissions</span>
>   ...
> </span>
> ```

That was introduced in https://github.com/owncloud/web/pull/7015 - if there are no alternative roles available the web ui now only renders the current role read only. A drop down makes no sense if the value can't be changed.

**Comment by saw-jan** [comment]
> That was introduced in https://github.com/owncloud/web/pull/7015 - if there are no alternative roles available the web ui now only renders the current role read only. A drop down makes no sense if the value can't be changed.

Ohh, But should not it be consistent for a scenario? There's sometimes a `button` and sometimes just span for the same test scenario.

**Comment by kulmann** [comment]
> > That was introduced in https://github.com/owncloud/web/pull/7015 - if there are no alternative roles available the web ui now only renders the current role read only. A drop down makes no sense if the value can't be changed.
> 
> 
> 
> Ohh, But should not it be consistent for a scenario? There's sometimes a `button` and sometimes just span for the same test scenario.
> 
> 
> 
> This intermittent change in DOM has made the test intermittent.

@saw-jan could you adjust the initial ticket description with this detail and add the p3 label and the bug label and add it to the beta board project in the web repo? A dev should investigate why it's sometimes a button and sometimes a span.

In the meantime you could stabilize the test by changing the selector to check for button or span at the same time, no?

**Comment by saw-jan** [comment]
> @saw-jan could you adjust the initial ticket description with this detail and add the p3 label and the bug label and add it to the beta board project in the web repo? A dev should investigate why it's sometimes a button and sometimes a span.
> 
> In the meantime you could stabilize the test by changing the selector to check for button or span at the same time, no?

I will give it a shot.

**Comment by saw-jan** [comment]
Similar test failed: webUIResharingToRoot/reshareUsers.feature:25 (https://drone.owncloud.com/owncloud/web/25885/23/20)

**Comment by saw-jan** [comment]
https://drone.owncloud.com/owncloud/web/25895/21/20
https://drone.owncloud.com/owncloud/web/25896/23/20

**Comment by pascalwengerter** [comment]
Just had this as a failure in one of my PRs and both @kulmann and me can't run `webUIResharing2/reshareUsers.feature:29` locally - it always fails with 

```
Error: OCS Request Failed: Could not create share. Message: Wrong path, file/folder doesn't exist, Status: 404, Message: Wrong path, file/folder doesn't exist
```

**Comment by kiranparajuli589** [comment]
> Just had this as a failure in one of my PRs and both @kulmann and me can't run `webUIResharing2/reshareUsers.feature:29` locally - it always fails with
> 
> ```
> Error: OCS Request Failed: Could not create share. Message: Wrong path, file/folder doesn't exist, Status: 404, Message: Wrong path, file/folder doesn't exist
> ```

@saw-jan will be investigating on this.

**Comment by saw-jan** [comment]
> Just had this as a failure in one of my PRs and both @kulmann and me can't run `webUIResharing2/reshareUsers.feature:29` locally - it always fails with
> 
> ```
> Error: OCS Request Failed: Could not create share. Message: Wrong path, file/folder doesn't exist, Status: 404, Message: Wrong path, file/folder doesn't exist
> ```

Same for me as well

**Comment by saw-jan** [comment]
@pascalwengerter, that fail is due to not having `'share_folder' => 'Shares',` in core config.
The middleware should set that while running the tests but somehow it didn't or something may happened.

**Comment by SwikritiT** [comment]
This also seems like a similar failure https://drone.owncloud.com/owncloud/web/26091/23/20
<details>
<summary>features/webUIResharingToRoot/reshareUsers.feature:25 </summary>

```
Reshare a folder without share permissions using API and check if it is listed on the collaborators list for resharer (attempt 1, retried) # features/webUIResharingToRoot/reshareUsers.feature:25
   ✔ Before # setup.js:41
   ✔ Before # setup.js:45
   ✔ Before # setup.js:49
   ✔ Before # setup.js:66
   ✔ Before # setup.js:73
   ✔ Before # setup.js:84
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:199
   ✔ Before # stepDefinitions/generalContext.js:237
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given these users have been created with default attributes and without skeleton files in the server: # stepDefinitions/middlewareContext.js:76
       | username |
       | Alice    |
       | Brian    |
       | Carol    |
   ✔ And user "Brian" has created folder "simple-folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Brian" has shared folder "simple-folder" with user "Alice" with "read, share" permissions in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has shared folder "simple-folder" with user "Carol" with "read" permissions in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:64
   ✔ When the user opens the share dialog for folder "simple-folder" using the webUI # stepDefinitions/sharingContext.js:588
   ✖ Then user "Carol King" should be listed as "Custom permissions" in the collaborators list for folder "simple-folder" on the webUI # stepDefinitions/sharingContext.js:703
       AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
       + actual - expected

       + 'Custom permissions'
       - false
           at /var/www/owncloud/web/tests/acceptance/stepDefinitions/sharingContext.js:115:16
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
   - And no custom permissions should be set for collaborator "Carol King" for folder "simple-folder" on the webUI # stepDefinitions/sharingContext.js:322
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:255
   ✔ After # stepDefinitions/generalContext.js:224
   ✔ After # stepDefinitions/generalContext.js:165
   ✔ After # setup.js:117
   ✔ After # setup.js:113
   ✔ After # setup.js:109
   ✔ After # setup.js:102
   ✔ After # setup.js:93
```

</details>

**Comment by saw-jan** [comment]
The main issue has been fixed in the source code: https://github.com/owncloud/web/issues/7063
Closing this.
