### ISSUE TITLE
Possibly flaky oCIS E2E test

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#7048]
Spotted in https://drone.owncloud.com/owncloud/web/25814/12/12

Needs investigation whether it's a test setup or backend issue, not pressing until it happens more often

**Comment by ScharfViktor** [comment]
First run was flaky. 
Second run failed because we need clear store after first run

**Comment by pascalwengerter** [comment]
> First run was flaky. Second run failed because we need clear store after first run

Thanks for investigating!
