### ISSUE TITLE
Collaborator role in side-bar is sometimes a drop-down list and sometimes a plain text

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#7063]
### Steps to reproduce
1. Create users `user1`, `user2`, and `user3`
2. As `user1`, create a folder `FOLDER` and share as `Viewer` with user `user2`
3. As `user2`, reshare the received share with `user3` with `read` permission only
![custom-read](https://user-images.githubusercontent.com/52366632/170638637-e414fecf-d38d-4695-b394-e7641cc185bb.png)
4. As `user2`, refresh the side-bar panel using share indicator (`Show invited people`) button from files list
![share-indicator](https://user-images.githubusercontent.com/52366632/170639261-c9cfcdad-98a1-4661-9c8a-afdba259b25c.png)

### Expected behaviour
The collaborator role sidebar to have consistent web elements

### Actual behaviour
The collaborator role sometimes have `drop-down` and sometimes a `plain text`

drop-down:
![drop-role](https://user-images.githubusercontent.com/52366632/170640167-d10715ff-6761-488e-92ec-5ef373c00f25.png)

Plain text:
![plain-text-role](https://user-images.githubusercontent.com/52366632/170640182-306814a1-3678-488e-acc6-3a0230177baf.png)

Video:

https://user-images.githubusercontent.com/52366632/170640858-1e1b2334-3086-4c61-969d-895ae4c4ebbe.mp4

### Environment general
**Operating system**:

**Backend (ownCloud Core or Infinite Scale)**:

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Core
version: `10.10.1 prealpha (git)`

**Comment by saw-jan** [comment]
Acceptance Tests failing: https://github.com/owncloud/web/issues/7047

**Comment by JanAckermann** [comment]
@saw-jan can you check again, issue might be fixed

**Comment by saw-jan** [comment]
Tried to reproduce with the latest web but cannot reproduce.
Seems like the issue has been fixed.

Closing here!
