### ISSUE TITLE
Improve Create-FileHandler-LinkNames

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#7076]
Spotted on cloud.owncloud.com

### Expected behaviour
Give the user a clear idea of what file they will create using the `+ New` button

### Actual behaviour
The user only sees the filetype and has no idea why they're offered multiple (seemingly identical) presentation/document/spreadsheet options

<img width="334" alt="Screenshot 2022-05-31 at 22 13 14" src="https://user-images.githubusercontent.com/16822008/171276687-ac9f6bd0-85e4-4a07-b0e4-dd699010037f.png">

**Comment by jnweiger** [comment]
Same issue exists in oc10 core. Not a regression. :innocent:

**Comment by pascalwengerter** [comment]
> Same issue exists in oc10 core. Not a regression. :innocent: 

But room for improvement? Cc @tbsbdr for concepting, we could add tooltips with the file extension maybe? (Even though those would only work on desktop)

**Comment by JammingBen** [comment]
Closing this in favour of https://github.com/owncloud/web/issues/7463
