### ISSUE TITLE
Bugfix: Copy / move repeating action

### ISSUE THREAD

**Issue by lookacat** [owncloud/web#7089]
Followup to https://github.com/owncloud/web/pull/6994:
 - Repeating copy or move action with the same name should be handled correctly: (1) move "asdf" to "target/asdf" and 
select "keep both" -> creates "target/asdf copy" when "target/asdf" already existed before. (2) again, move "asdf" to "target/asdf" and select "keep both" -> tries to create "target/asdf copy", but fails because it already exists from previous move with "keep both".

**Comment by tbsbdr** [comment]
Please note:
I'm thinking about if we can replace the whole "location picker" with a "clipboard" based concept as users might know it from native os. (for oc10 we already have an app: https://marketplace.owncloud.com/apps/files_clipboard)
--> this ticket and work on the location picker might get obsolete if we decide to use a "clipboard" based concept. (Needs proper concept)
