### ISSUE TITLE
(FR) Change behaviour of Search Bar to list results from current folder listing first

### ISSUE THREAD

**Issue by JRundfeldt** [owncloud/web#7099]
The search-bar needs in my opinion also to work as navigation aid to quickly retrieve a folder or file, that is already on the screen.

I believe the Search Function of oc-web should be changed. Its first priority should be to check if the entered string exists in the current list of Folders and Files, that is shown to the user. Afterwards it can start to find the string in the files itself. 

Some Users, that includes our own internal cloud.owncloud.com, have Folders with hundreds of sub-folders. To quickly find a Folder in there, it would be  good, if I could just enter a string that exists in the folder name in the search bar. 

I could then either get an overlay (think: Google Search Autocomplete) - or the results could be shown as the first hits in the already existing pop-down that extends when the search found something. 

This behaviour seems to exist IIRC already in oc10 - but not in oc-web.

**Comment by JammingBen** [comment]
Has been implemented via https://github.com/owncloud/web/pull/9304.

**Comment by JRundfeldt** [comment]
<3
