### ISSUE TITLE
Parent folder name in the upload overlay on public links

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#7101]
### Steps to reproduce
1. Create a public link with upload permissions
2. Open the public link and upload a file to its root
3. Click on "Show details" in the upload overlay and look at the parent folder below the file name

### Expected behaviour

a) Show generic "*Public link*" as name or
b) Don't show a parent folder at all

### Actual behaviour
The token of the public link is displayed as parent folder

![image](https://user-images.githubusercontent.com/50302941/172606960-a458c57d-d484-4202-9d55-a1a3d8d5c0d9.png)

**Comment by JammingBen** [comment]
@tbsbdr Do you have a preferred expected behavior for this issue?

**Comment by tbsbdr** [comment]
B)ecause I assume people don't navigate around in dropfolders.
