### ISSUE TITLE
Make uploaded folders clickable in the upload overlay

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#7102]
When uploading a folder, it would nice to make the folder clickable in the upload overlay.

![image](https://user-images.githubusercontent.com/50302941/172623247-b63c2707-b913-46b9-92ca-65853f25776b.png)

**Comment by kulmann** [comment]
Similar for files, it would be nice if the uploaded items would trigger the respective default file action on click. I.e. same behaviour as if you'd click on the item in the file list. What do you think?

**Comment by kulmann** [comment]
> > Similar for files, it would be nice if the uploaded items would trigger the respective default file action on click. I.e. same behaviour as if you'd click on the item in the file list. What do you think?
> 
> I like the idea in general, although this might be a bit more complicated. We'd need to check what's needed for this first, especially if it's necessary to fetch the resource after an upload - which we should avoid at all cost IMO. For me, the overlay is firstly about (read-only-)information, then about navigation, and lastly about actions.

Ack, if it increases network requests then it's a nogo for the moment.

**Comment by JammingBen** [comment]
I tried it, however, file actions do indeed require some data that only comes which a propfind after the upload has finished. That means we only have folder links (at least for now): https://github.com/owncloud/web/pull/7109
