### ISSUE TITLE
link-share of a project space root has no resource name in file list

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#7103]
### Steps to reproduce
1. As admin, create a project space `asdf`
2. create/copy the quicklink for the project space root
3. Visit the `Shared via link` page

### Expected behaviour
Nice looking representation of the project space, where the space name is the resource name and a parent folder link probably doesn't make sense.

### Actual behaviour
The entry for the project space doesn't show a resource name at all. It does however show the project space in the `parent folder link`. Clicking that navigates to the project space, so at least the project space is reachable.

### Screenshot
<img width="495" alt="Screenshot 2022-06-09 at 09 25 06" src="https://user-images.githubusercontent.com/3532843/172790263-5133824b-3728-425c-950a-16a5ad415a01.png">

**Comment by JammingBen** [comment]
I've stumbled upon this in the past and created an OCIS issue as prerequisite for this. Don't know if it's still relevant though: https://github.com/owncloud/ocis/issues/3359
