### ISSUE TITLE
🏷 Tags

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7134]
# Description
> As a user I want to use tags together with my collaborators, so that we can find related files regardless of their location or file name.

## Quick summary

1. Provide Tags to find files and folders across Spaces, projects or folders
2. Focus on collaboration ex. with colleagues to "bundle" files and folders ex. from different departments. 
3. Users can only see tags of files for which they have at least read access; if you don't see a file, you also don't see its Tag
4. Tags can be created by everyone with write-permissions to the file or folder

See Stories for all details
 
## Stories for this epic:

- [x] https://github.com/owncloud/web/issues/7135
- [x] #7168 
- [x] #7169
- [x] #7167 
- [x] #7170
- [x] #7286

--- low prio / nice to have stories:
- [ ] #7285
- [x] #7208
- [ ] #7287
- [ ] Batch-edit
- [ ] add tag-taxonomy / recommendation engine cc @butonic

**Comment by JanAckermann** [comment]
Closing as we already opened a new tag improvement jira issue (https://jira.owncloud.com/browse/OCIS-3736).
 
Otherwise it get's to a certain level of confusion and we loose the ideas, due to splitted in much to many tickets
