### ISSUE TITLE
Create tags

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7135]
## User Story

> As a user I want to tag a file, so that it gets related to other files with the same tag.

## Value

*   Assign additional context to a file.

## Acceptance Criteria

*   [ ] Only users with write permission can create tags
*   [ ] Add options "Add or edit Tags" in 'Context-Menus' and 'Actions' Panel
*   [ ] Click on "Add or edit Tags" opens the right sidebar panel "Tags"
*   [ ] tags can be added to files and folders
*   [ ] New Tags can be added via click in the form field
*   [ ] `<enter>` "stages" the Tag, Button "Save" adds the Tag to the file
*   [ ] Spaces and special chars are allowed in the tagname.
*   [ ] Tags are converted to lowercase: `VERY Important` -> `very important`
*   [ ] click on `X` or removes the Tag from the form, "Save" removes the tag finally from the file.
*   [ ] default: a file/folder can have max. 100 tags.

### Unittest:

*   [ ] create and assign 1 tag
*   [ ] create and assign multiple tag
*   [ ] select and assign 1 predefined tag
*   [ ] select and assign multiple predefined tag
*   [ ] creating a staged tag and deleting it, does not assign it

### E2E Tests

*   [ ] navigate into tags panel of 1 file, create and assign 1 tag, validate, that it was assigned

## Definition of ready

*   [ ] everybody needs to understand the value written in the user story
*   [ ] acceptance criteria has to be defined
*   [ ] all dependencies of the user story need to be identified
*   [ ] feature should be seen from an end user perspective
*   [ ] user story has to be estimated
*   [ ] story points need to be less then 20

## Definition of done

*   Functional requirements

*   [ ] functionality described in the user story works
*   [ ] acceptance criteria are fulfilled

*   Quality

*   [ ] codre review happened
*   [ ] CI is green
*   [ ] critical code received unit tests by the developer
*   [ ] automated tests passed (if automated tests are not available, this test needs to be created and passed

*   Non-functional requirements

*   [ ] no sonar cloud issues

Note on terminology:  
"File" is always meant as "file and folder".

![image](https://user-images.githubusercontent.com/26610733/179566378-7ca12300-ba23-4c3b-b33f-048a2338649f.png)

**Comment by tbsbdr** [comment]
Added appendix links.

**Comment by tbsbdr** [comment]
updates:

*   re-use the groups-assignment form and behaviour from the usermanagement for Tags
*   added limit of 100 tags to cap speedblocker

CC @kulmann @pmaier1

**Comment by kobergj** [comment]
>     * added limit of 100 tags to cap it as a speedblocker; added to make this value configurable - do you agree @kobergj ?

Does not make much sense in my opinion. The idea was to have a hardcoded maximum because we do not know what issues will arise when extended attributes can no longer be written. Allowing an admin to configure it will make him run into exactly these problems sooner or later. Also: How should an admin know which number of tags is feasible for the system? He can't. This is a technical limitation. Only we can know how many tags can be supported.

So I don't see the point in making it configurable. Admins can't know which value should be used and if they raise the number too much they will run into unforseeable technical problems sooner or later.

**Comment by tbsbdr** [comment]
ok, if this is the reasoning, then lets not make it configurable but hardcoded.
