### ISSUE TITLE
Remove color gradients and improve user communication

### ISSUE THREAD

**Issue by Deaddy** [owncloud/web#7137]
### Steps to reproduce
1. Open owncloud web since 5.x or so (5.4.0 as the current release
2. Get headache
3. Notice there are lots of unwarranted gradients and which interfere with your saccades

### Expected behaviour
UI should be clean and not unnessarily draw attention to things that do not need attention.
Also design of UI elements should be an indicator on their purpose.

### Actual behaviour
We have color gradients on buttons, on little icons indicating sharing status, on highlighted entries on the left side bar, and we have a drop shadow of the left sidebar over the file list.

Color gradients by their nature draw attention and focus and thus should not be used in places which do not require immediate attention.

This is basically a regression from previous designs, which did not suffer from this accessibility issue.

Furthermore this detracts from a clear communication, because on the left side bar now things which are active  are highlighted in this gradient fashion (e.g. "favorites"), but in the file viewer things which are only status indicators have the same coloration (sharing status) but also buttons for actions (new file button) have the same color language AND furthermore demand attention of the user.

This should be more clearly separated, e.g.
 - flat button color scheme, but with a good contrast to background to indicate "this is an interactive button" (compare github submit new issue button) or like the upload button without a filling (why is there a distinction?)
 - left sidemenue which is ALWAYS there and does NOT OVERLAY the file switcher should be *next* to it visually (thinking of tiling next to each other instead of layering)
 - also inconsistent with display of right side pane, in general I think it would be nice to have that as a separate tile as well, or well, just the tiny line separating it from the files list is still better than this drop shadow indicating another layer
 - all icons indicating sharing status or anything else in flat color scheme; just dropping the gradient would work well I suspect, because then there is also a distinction to the interactive buttons on the right, though one might wonder if it would make more sense to change this and have the interactive buttons with some solid background and the sharing indicators just a line drawing
 - I think the drop shadows on popups are fine and a good use, because well, they popup and are temporary
 - highlighted entries are just highlighted by solid color, on the side pane maybe one can even be bold and use background color

**Comment by pascalwengerter** [comment]
Can be achieved by theming
