### ISSUE TITLE
Pagination: New pages should start at the top

### ISSUE THREAD

**Issue by d7oc** [owncloud/web#7138]
### Steps to reproduce
1. Go to a folder with many entries which don't fit on a single result page
2. Go to the end of the first page
3. Select the next page

### Expected behaviour
The next page should start at the top

### Actual behaviour
The next page is already scrolled to the bottom

### Environment general
Regarding environment details: This happened on cloud.owncloud.com

**Comment by tbsbdr** [comment]
thanks for reporting!
on the long run imo we should find a way to get rid of the pagination, but I'm afraid this will take some time.
@lookacat can you estimate if this is a quickwin?

https://user-images.githubusercontent.com/26610733/174309327-49f760fc-14c3-4d4b-bc59-eb739ffd907a.mp4
