### ISSUE TITLE
Console error when pasting with empty clipboard

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#7146]
Not a very visual error, yet worth preventing I suppose

### Steps to reproduce
1. Press `Ctrl` + `v` on a freshly reloaded page (e.g. personal space root)
2. Nothing happens in the UI, `TypeError: u is undefined` error in pasteSelectedFiles on browser console

### Expected behaviour
No console error, maybe display a message to the user about not being able to paste zero files? @tbsbdr could be nice, don't know of an app/OS that does this though

**Comment by tbsbdr** [comment]
> display a message to the user about not being able to paste zero files

I would recommend to stay silent in the ui because users are likely to not expect a message at that point, because - as you say - they are not used to it.
