### ISSUE TITLE
Copy/paste keyboard shortcut: can't copy/paste plaintext anymore

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7147]
### Steps to reproduce
1. Login to https://ocis.ocis-web.latest.owncloud.works/
2. Select a file, press cmd+c (keyboard shortcut: copy)
3. Select search field and press cmd+V
4. file gets pasted instead of text.

https://user-images.githubusercontent.com/26610733/174585625-4b30cd84-b211-4b36-874b-281b06fe724d.mp4

### Expected behaviour
- **Copy / Cut:**  If one or many resources are selected, the keyboard shortcuts copy, paste and cut should work, as they do.
- **Copy / Cut:** If one or many resources are selected and the user selects anything else like text-passages, the default browser behaviour should win (meaning: the selected text should get copied to clipboard and no userfacing message from ownCloud Web should appear; the resource should then not get copied/cut to clipboard)
- **Paste:** should only apply, if no actionable item like `<inputs>` are active. In that case the browser behaviour should win.

### Actual behaviour
- file gets copied regardless of its context. current implementation completely ignores the default browser behaviour

**Comment by tbsbdr** [comment]
Note: @fschade already did some quick prototyping on the issue

**Comment by kulmann** [comment]
> Should be fixed by: #7153

Can confirm the fix, closing here, thank you @lookacat !

@tbsbdr please reopen if you find something where the expected behaviour is still broken.
