### ISSUE TITLE
"Cannot read properties" when you try to create public link

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7149]
ocis: 2.0.0-beta.3
web: 5.5.0-rc.10

Steps: 

- admin creates a folder with the file 
- admin creates a public link to the folder -> default role is viewer
- admin changes the role of the link to another role 
- admin goes to the folder and tries to create a public link to the file

Actual result: imposible to create link to the file 

https://user-images.githubusercontent.com/84779829/174591665-0b540d90-7071-4bf4-be09-21c929aff1ba.mov

**Comment by pascalwengerter** [comment]
Nice find, thx! Opened a PR with a fix
