### ISSUE TITLE
User can create folder called Shares and drag-drop into it

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#7157]
### Steps to reproduce
1. login to web with ocis as an ordinary user
2. create a folder called `Shares` in the Personal area
3. open `Shares`
4. the New and Upload buttons are disabled
5. drag-and-drop a file into `Shares`
6. drag-and-drop a folder into `Shares`

### Expected behaviour
Something consistent. Either enable the New and Upload buttons, or prevent users from creating a folder called Shares in the first place, or?

The web app seems to be smart enough now to manage a folder called `Shares` in the Personal space. I guess that it accesses it via the Personal space id. Accessing an end-point like `/dav/files/alice/Shares` returns the details of incoming shares received by Alice - so `/dav/files/alice` can't be used to manage a "real" folder called `Shares` that Alice has created.

Maybe the New and Upload buttons can be enabled? (Since the drag-drop, edit, delete, share etc all seems to work)

### Actual behaviour
Files and folders can be added by drag-and-drop
They cannot be added by using the New or Upload buttons

If I navigate into the folder that I drag-dropped in `Shares` then I can use the New and Upload buttons.

I can edit a text file that I drag-drop into Shares.

### Environment general
Current oCIS and web master

**Comment by JanAckermann** [comment]
This shouldn't be a problem anymore as we have the share pages now and "Shares" won't be displayed in the users root folder any more
