### ISSUE TITLE
Changing role in space to `manager` is not possible 

### ISSUE THREAD

**Issue by SagarGi** [owncloud/web#7163]
## Description

When changing role in space project by  a `space admin user` to other user, changes is seen on the UI but after a reload or refresh the role is changed to the previous role. 

### Steps to reproduce
1. Make user `Alice` as a space admin user (By admin)
2. Log in with user `Alice`
3. Create a space project `team`
4. Add user `Brian` as a space role `editor`
5. Add user `Carol` as a space role `viewer`
6. Change user `Carol` role to `manager` 
7. Reload or refresh

#### Expected Behaviour

User `Carol`'s role should be changed to manager so that user `Alice` could also remove herself

#### Current Behaviour

This only valid's incase of changing role to `manager`

https://user-images.githubusercontent.com/46086950/175009585-bbda87ad-e391-4c2d-8ee3-9f7a33b84c8b.mp4

### Environment general
Current oCIS

**Comment by SagarGi** [comment]
This might be a reason for this Build fail https://drone.owncloud.com/owncloud/web/26378

**Comment by ScharfViktor** [comment]
fixed in https://github.com/owncloud/web/pull/7086
