### ISSUE TITLE
[ocis] Shares sidebar does not show created public-link with `Permission 3` 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#7164]
### Steps to reproduce
1. login to web with ocis as an ordinary user
2. create a folder 
3. create public link with permission 3
```
curl -k -u admin:admin -X POST https://host.docker.internal:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d permissions=3 -d path="New folder" -d shareType=3 |xmllint --format -
```

### Expected behaviour
In web GUI, **public link** should be displayed in the share sidebar. If permission 3 is not allowed then the error message should be thrown.

### Actual behaviour
<details> <summary> Public-link successfully created </summary>

    <ocs>
    <meta>
      <status>ok</status>
      <statuscode>100</statuscode>
      <message>OK</message>
    </meta>
    <data>
      <id>EOBOZNwWYrySdSz</id>
      <share_type>3</share_type>
      <uid_owner>admin</uid_owner>
      <displayname_owner>Admin</displayname_owner>
      <additional_info_owner>admin@example.org</additional_info_owner>
      <permissions>3</permissions>
      <stime>1655894625</stime>
      <parent/>
      <expiration/>
      <token>oAsVyZBrbzKSmWm</token>
      <uid_file_owner>admin</uid_file_owner>
      <displayname_file_owner>Admin</displayname_file_owner>
      <additional_info_file_owner>admin@example.org</additional_info_file_owner>
      <state>0</state>
      <path>/New folder</path>
      <item_type>folder</item_type>
      <mimetype>httpd/unix-directory</mimetype>
      <storage_id>shared::/New folder</storage_id>
      <storage>0</storage>
      <item_source>1284d238-aa92-42ce-bdc4-0b0000009157$some-admin-user-id-0000-000000000000!f3915d55-c523-4b4d-8db9-8807b49d9cd6</item_source>
      <file_source>1284d238-aa92-42ce-bdc4-0b0000009157$some-admin-user-id-0000-000000000000!f3915d55-c523-4b4d-8db9-8807b49d9cd6</file_source>
      <file_parent/>
      <file_target>/New folder</file_target>
      <share_with_user_type>0</share_with_user_type>
      <share_with_additional_info/>
      <mail_send>0</mail_send>
      <name/>
      <url>https://host.docker.internal:9200/s/oAsVyZBrbzKSmWm</url>
    </data>
  </ocs>

</details>

But in web GUI, public link is not visible in shares side bar
![permission3publiclink](https://user-images.githubusercontent.com/54478846/175013398-cb3d1007-3fca-4ab2-a047-c2261e60c409.png)

### Environment general
**Operating system**: ubuntu

**Backend (ownCloud Core or Infinite Scale)**: ocis

#### Browser log
```console
[Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'hasPermission')"

found in

---> <FileLinks>
       <SharesPanel>
         <SideBar>
           <SideBar>
             <Anonymous>
               <Anonymous>
                 <Anonymous>
                   <Root>

TypeError: Cannot read properties of undefined (reading 'hasPermission')
    at VueComponent.isPasswordEnforcedFor (web-app-files.js:19402:43)
    at web-app-files.js:19685:59
    at Proxy.renderList (vendor.js:55386:18)
    at Proxy.__vue_render__$f (web-app-files.js:19667:25)
    at vendor.js:14186:37
    at activateCurrentInstance (vendor.js:14140:18)
    at $options.render (vendor.js:14185:26)
    at Vue._render (vendor.js:56305:24)
    at VueComponent.updateComponent (vendor.js:56816:23)
    at Watcher.get (vendor.js:57229:27)
```

**Comment by pascalwengerter** [comment]
@amrita-shrestha could you check the console for errors and update the issue information? Thanks!

**Comment by amrita-shrestha** [comment]
@kulmann  In web GUI, 2 new different bugs has been reported now
After successful public link creation with `permission 3` using api request
1. Side-bar doesn't show created public link
2. If we try to create a new public link using web UI then the public link will not be visible in sidebar

`Bug Report Video`: [Screencast from 02-11-2023 06:49:31 PM.webm](https://user-images.githubusercontent.com/54478846/218259603-13fef978-a44b-46f9-ad60-8115aeb7c6ce.webm)

```Logs
vendor-ac6eee24.mjs:1 TypeError: Cannot read properties of undefined (reading 'hasPermission')
    at Proxy.isPasswordEnforcedFor (web-app-files-bc3835af.mjs:9:144269)
    at web-app-files-bc3835af.mjs:9:150494
    at _d (vendor-ac6eee24.mjs:1:44912)
    at web-app-files-bc3835af.mjs:9:150161
    at n (vendor-ac6eee24.mjs:1:28882)
    at Ar (vendor-ac6eee24.mjs:1:45654)
    at Proxy.Sm (index.html-4a66192c.mjs:7:41252)
    at Xg (vendor-ac6eee24.mjs:1:29194)
    at tp.Z [as fn] (vendor-ac6eee24.mjs:1:63959)
    at tp.run (vendor-ac6eee24.mjs:1:16592)
````
`Logs Video`: [Screencast from 02-11-2023 06:58:32 PM.webm](https://user-images.githubusercontent.com/54478846/218259954-495ff9d6-ddd3-4d93-8cda-825da1c78796.webm)

**Comment by JanAckermann** [comment]
Permission 3 means, that you can just view and edit, we don't have a  share role for that
