### ISSUE TITLE
The application switch has user management button for the public

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7165]
web: ownCloud Web UI 5.5.0-rc.8
ocis:  Infinite Scale 2.0.0-beta.4+efec53964 Community 

Steps:

- admin creates public link to the folder with viewer role
- open public link
- click to `application switcher`

Actual: "user management" unnecessary here:

![Screenshot 2022-06-22 at 13 46 51](https://user-images.githubusercontent.com/84779829/175023454-4e542bd9-9d30-443f-8f88-e830cdde5d20.png)

**Comment by kulmann** [comment]
Has been fixed in https://github.com/owncloud/web/pull/7197
