### ISSUE TITLE
Delete a single Tag

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7167]
## User Story

> As a user I want to remove a tag from a file, so that the file does not get listed any more on click of the tag.

## Value

*   tidy up tagged files

## Acceptance Criteria

*   [ ] click on "X" removes the tag from the resource
*   [ ] if there is only 1 file with ex. the Tag "mytag" left, and "mytag" gets removed via `X`, then the Tag is globally deleted because it can't live without a file attached (implicit delete)
*   [ ] Behaviour of the tags field will be same like the group-select in user management

![image](https://user-images.githubusercontent.com/26610733/179587108-a20718b8-e4b2-4a9e-8e7f-50dfcbf907df.png)

## Definition of ready

*   [ ] everybody needs to understand the value written in the user story
*   [ ] acceptance criteria has to be defined
*   [ ] all dependencies of the user story need to be identified
*   [ ] feature should be seen from an end user perspective
*   [ ] user story has to be estimated
*   [ ] story points need to be less then 20

## Definition of done

*   Functional requirements

*   [ ] functionality described in the user story works
*   [ ] acceptance criteria are fulfilled

*   Quality

*   [ ] codre review happened
*   [ ] CI is green
*   [ ] critical code received unit tests by the developer
*   [ ] automated tests passed (if automated tests are not available, this test needs to be created and passed

*   Non-functional requirements

*   [ ] no sonar cloud issues

Note on terminology:  
"File" is always meant as "file and folder".

## Appendix:

Example combobox components for Tags:

1.  https://owncloud.design/#/oC%20Components/OcSelect
2.  https://vuetifyjs.com/en/components/combobox/#advanced-custom-options

**Comment by Jay-Dee-W** [comment]
for more context on this issue :- https://github.com/owncloud/ocis/issues/3284

**Comment by tbsbdr** [comment]
update:

*   re-use the group-select in user management
*   added screenshot
*   removed old scribbles

CC @fschade
