### ISSUE TITLE
Display Tags in filelist

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7169]
## User Story

> As a user I want to see if a file is tagged so that I can browse files in a more explorative way.

## Value

*   find related files regardless of their location or file name.

## Acceptance Criteria

*   [x] New column "Tags" in the filerow
*   [ ] ~~Column is only shown, if there are Tags in the current folder~~--> won't happen as long as we have pagination. value too small
*   [x] Click on a single tag opens the respective SERP #7168
*   [ ] If one Tag is too long, it gets truncated `...` (bonus: truncation in the middle of the tag)
*   [x] in files table we only display a maximum of 2 tags
*   [x] the number of hidden tags is shown `+ 4`
*   [x] click on `+ 4` opens the tags sidebar
*   [ ] tags are sorted alpha numerically
*   [ ] We dispaly a little tag icon beside each individual tag

tags without colors:
![image](https://user-images.githubusercontent.com/26610733/182372449-81def19c-a874-4035-bbe4-e54566d8eb21.png)

colored tags (not part of this story)
![Tags upfront](https://user-images.githubusercontent.com/26610733/175536182-ba252e0d-d051-4657-b748-e6a8493de109.png)

![Tags upfront](https://user-images.githubusercontent.com/26610733/176198135-eb20e293-2df7-463e-bbd1-b46f43100886.png)

## Definition of ready

*   [ ] everybody needs to understand the value written in the user story
*   [ ] acceptance criteria has to be defined
*   [ ] all dependencies of the user story need to be identified
*   [ ] feature should be seen from an end user perspective
*   [ ] user story has to be estimated
*   [ ] story points need to be less then 20

## Definition of done

Functional requirements

 functionality described in the user story works

 acceptance criteria are fulfilled

Quality

 codre review happened

 CI is green

 critical code received unit tests by the developer

 automated tests passed (if automated tests are not available, this test needs to be created and passed

Non-functional requirements

 no sonar cloud issues

**Comment by tbsbdr** [comment]
@kulmann I think its a good idea to have a fixed colorpalette in the theme because users might want to choose special colors for their tags in the future. we can then provide the 30 colors defined in the theme.

**Comment by tbsbdr** [comment]
update: prioritized different colors for tags as 🍰 Cherry on top (nice-to-have). @kulmann

**Comment by tbsbdr** [comment]
@fschade we discussed to bypass the truncation (+4) and drop-menu if there are many tags in the column in the first step:
<img width="426" alt="screenie_Brave Browser_2022-07-18_at_20-33-31@2x" src="https://user-images.githubusercontent.com/26610733/179579133-2d212e4a-7d1d-4983-a2b7-8175590ed4a5.png">

One idea was to just list all tags in the row - but this would result in multi-line row which would mess up  the filestable 😕

proposal: 
- truncate tags + show number of truncated tags "+13"
- click on "+13" opens sidebar with Tags in the file details

could that be a compromise?

![image](https://user-images.githubusercontent.com/26610733/179583832-e3246698-ad3c-4532-8be1-b83dc1ec2d3b.png)

**Comment by kulmann** [comment]
> could that be a compromise?

Yes, please! Could even be the preferred solution (based on user feedback later on). Let's go with this approach. Multi-line rows / rows with variable height are a no go.
