### ISSUE TITLE
Speed up TUS-uploads by re-enabling `creation-with-upload`

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#7177]
## Debug and re-enable creation-with-upload TUS extension

Needs https://github.com/tus/tus-js-client/issues/397 to be solved

Code: https://github.com/owncloud/web/blob/0d301f5c5211c88175ad60f721311df0bc030043/packages/web-runtime/src/services/uppyService.ts#L52
Commit: https://github.com/owncloud/web/commit/0d301f5c5211c88175ad60f721311df0bc030043

**Comment by JammingBen** [comment]
Version 3.0.0 of the tus-client-lib has been released a few days ago which fixes this issue. Now needs to wait until uppy releases their next major version.

**Comment by kulmann** [comment]
There is https://github.com/transloadit/uppy/releases/tag/uppy%402.13.4 and https://github.com/transloadit/uppy/releases/tag/uppy%403.0.0 - both have been release after the tus client lib that you mentioned. Didn't check if both uppy releases contain the updated tus client lib.
