### ISSUE TITLE
[OCIS] wrong path is send when reshaing a share with user

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#7179]
### Steps to reproduce
1. create user1, user2, and user3
2. create a `test-folder` for user1, and share it with user2 with the `Viewer` role
3. Accept incoming share by user2
4. As user2, share `test-folder` from the `Shared with me` page to user3 with the `Viewer` role

### Expected behaviour
Resharing to another user must succeed and share must be created on the server.
```curl -kv -XPOST -u uu2:uu2 https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -d shareType=0 -d shareWith=uu3 -d path=Shares/simple-folder -d permissions=17```

```console
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <element>
      <id>81c7103d-e75c-4194-80eb-5814c2549ade</id>
      <share_type>0</share_type>
      <uid_owner>uu2</uid_owner>
      <displayname_owner>Test User 2</displayname_owner>
      <additional_info_owner>testuser1@example.org</additional_info_owner>
      <permissions>17</permissions>
      <stime>1656054423</stime>
      <parent/>
      <expiration/>
      <token/>
      <uid_file_owner>uu1</uid_file_owner>
      <displayname_file_owner>Test User 1</displayname_file_owner>
      <additional_info_file_owner>testuser2@example.org</additional_info_file_owner>
      <state>0</state>
      <path>/simple-folder</path>
      <item_type>folder</item_type>
      <mimetype>httpd/unix-directory</mimetype>
      <storage_id>shared::/Shares/simple-folder</storage_id>
      <storage>0</storage>
      <item_source>1284d238-aa92-42ce-bdc4-0b0000009157$468cce77-55a8-48af-b68d-1233e346297a!159ed5d2-b12c-4d43-8748-5f9e8526b5f0</item_source>
      <file_source>1284d238-aa92-42ce-bdc4-0b0000009157$468cce77-55a8-48af-b68d-1233e346297a!159ed5d2-b12c-4d43-8748-5f9e8526b5f0</file_source>
      <file_parent/>
      <file_target>/Shares/simple-folder</file_target>
      <share_with>uu3</share_with>
      <share_with_user_type>0</share_with_user_type>
      <share_with_displayname>Test User 3</share_with_displayname>
      <share_with_additional_info>testuser3@example.org</share_with_additional_info>
      <mail_send>0</mail_send>
      <name/>
    </element>
  </data>
</ocs>
```

### Actual behaviour
It is sending `/` in `path` instead of `path having the name of folder` when creating reshare
![uu2_uu3](https://user-images.githubusercontent.com/8559121/175484054-e77612a9-fbf6-4633-8873-254bcbd153ed.png)

It gives response with `100` status code with `<file_target>/Shares</file_target>`, but share is not created on server.
![resp](https://user-images.githubusercontent.com/8559121/175485148-1236c190-e9d3-4537-b78d-71146818bce8.png)

### Environment general
**Operating system**: ubuntu

**Backend (ownCloud Core or Infinite Scale)**: OCIS (latest)

**Comment by kulmann** [comment]
Resharing doesn't work with web+ocis, yet. https://github.com/owncloud/web/pull/7086 Needs to be finalized and merged first.
