### ISSUE TITLE
[OCIS] Share indicator is not displayed in group share after reload 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#7189]
### Steps to reproduce
1. As user einstein share a folder `New folder` to group `physics-lovers`
2. The share indicator icon is shown
![ocisIndicatorShown](https://user-images.githubusercontent.com/41103328/176166115-7d570f0c-df04-4a60-bb18-98f5d0757f44.png)

4. Now reload the page

### Expected behaviour
The icon should still be visible as the folder is shared with the group 

### Actual behaviour
The icon is gone while the folder is still shared

![iconGone](https://user-images.githubusercontent.com/41103328/176166746-067246d3-a5e9-495c-b5a9-e4ec03ea86df.png)

The indicator works for user/link share

**Comment by JammingBen** [comment]
Has been fixed meanwhile on current master.
