### ISSUE TITLE
Search: Left sidebar item is hard to read (because of wrong colors)

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7190]
### Steps to reproduce
1. Login on https://ocis.ocis-web.latest.owncloud.works/
2. create folder "New folder"
3. search for "new" in all files
4. Active item in left sidebar is hard to read (occurs in both, dark- and light mode)

![screenie_Brave Browser_2022-06-28_at_14-22-44@2x](https://user-images.githubusercontent.com/26610733/176177517-02717bc3-a5c6-4d4e-947d-df347f0061ea.png)
![screenie_Brave Browser_2022-06-28_at_14-32-00@2x](https://user-images.githubusercontent.com/26610733/176179225-ab0b2c6a-16f5-435c-856b-dc26c7e2f364.png)

### Expected behaviour
No active left sidebar item on search result page.
If there was an active item for some reason, colors should be the same like in the initial status
<img width="982" alt="screenie_Brave Browser_2022-06-28_at_14-28-37@2x" src="https://user-images.githubusercontent.com/26610733/176178943-d272e9db-8d0a-4c41-8eae-575d2a793211.png">
<img width="1118" alt="screenie_Brave Browser_2022-06-28_at_14-33-06@2x" src="https://user-images.githubusercontent.com/26610733/176179400-5fecb9d4-bc7e-44b8-bab0-af48e49ab7e8.png">

### Actual behaviour
- Left sidebar item is hard to read (because of wrong colors)

**Comment by kulmann** [comment]
@JanAckermann mentioned in a chat that it's weird that `Personal` item is active on the search result page. Which is a correct observation.

@tbsbdr I'd propose to not have an active left sidebar nav item on the search result page. Another option could be to have a temporary `Search result` nav item which gets removed again when you leave the search result page.

**Comment by tbsbdr** [comment]
> not have an active left sidebar nav item on the search result page

jep 👍 good idea.

**Comment by JanAckermann** [comment]
Well this was spoken with @kulmann which we found a good idea, easy to remove anyways if you wish so.

**Comment by JanAckermann** [comment]
Follow up PR
https://github.com/owncloud/web/pull/7270
