### ISSUE TITLE
Search does not find all files

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7192]
### Steps to reproduce
1. login at https://ocis.ocis-web.latest.owncloud.works/
2. Set pagination to Items per Page: "All"
3. Upload 2.000 Files names `File1`, `File2` ... `File2000` (download test data from here:  https://cloud.owncloud.com/index.php/s/xnvEvwmwbC7qF7a)
4. search for "file" in "all files"
5. SERP shows 200 items

### Folder with 2000 files inside:
![screenie_Brave Browser_2022-06-28_at_14-45-49@2x](https://user-images.githubusercontent.com/26610733/176182159-dafd5b1f-e081-4679-b350-17ae116e6fa5.png)

### Result page with only 200 files found:
![screenie_Brave Browser_2022-06-28_at_14-50-43@2x](https://user-images.githubusercontent.com/26610733/176182951-e81d9425-7b6c-4265-a1bf-24ec5a9502cf.png)

### Expected behaviour
- All 2000 files should be found

### Actual behaviour
- only 200 of 2000 files are found

**Comment by kulmann** [comment]
@micbar @aduffeck do we have pagination on the REPORT request? 🤔

**Comment by micbar** [comment]
> @micbar @aduffeck do we have pagination on the REPORT request? 🤔

We do not have pagination on WebDAV requests at all.

**Comment by JanAckermann** [comment]
Actually, we don't have pagination.
There is also an infinity flag we can set to retrieve an unlimited amount of results, but we could set a magic number like 1 mio or so.

How to proceed @kulmann @tbsbdr @micbar

**Comment by tbsbdr** [comment]
Proposal as long as we don't have pagination from the server:

- **Default Limit** We set a cost-effective default (=fast enough, but still useful amount of result) of max results, ex. 300 items
- **Communication** If more than 300 items where found, we communicate "**Found many, showing the 300 best matching results.**"

![screenie_Brave Browser_2022-07-11_at_15-45-19@2x](https://user-images.githubusercontent.com/26610733/178280248-0116cb02-d2f8-4bd0-ad29-1ff40e90035b.png)

Any additions or objections @aduffeck @micbar @JanAckermann ?

**Comment by JanAckermann** [comment]
@tbsbdr do we really show the best matching results?

Would rather go with: "**Found 400 matches**, showing the first 300 results. (maybe)"

**Comment by tbsbdr** [comment]
> do we really show the best matching results

@micbar can we say "best matching results" or are the results non-weighted?

**Comment by aduffeck** [comment]
@tbsbdr @micbar Search results are sorted by relevance, meaning results with the highest score will be returned first.

**Comment by JanAckermann** [comment]
Pretty cool! So we need a decision if we want to proceed with this proposal.

Requirements:
- Dav Report needs to emit a meta field with the total found items
- Frontend implementation

**Comment by micbar** [comment]
@JanAckermann @tbsbdr the proposal is fine IMO

**Comment by aduffeck** [comment]
@JanAckermann @tbsbdr you can already specify the number of results being returned using the `<oc:limit>` tag if you don't like the 200 results default. Other than that I will prepare a PR that will add the total number of results to the response.

**Comment by JanAckermann** [comment]
@tbsbdr 
1. Do we want to show "Found many, showing the 300 best matching results." or "Found [numer of results], showing the 300 best matching results."

**Comment by JanAckermann** [comment]
@tbsbdr 
Works like designed https://github.com/owncloud/web/pull/7267

But we have a problem with oc10 as backend, there is no field that gives us the number of the matching results, so 200 is the hard limit, and we cannot communicate if there might be more results

**Comment by tbsbdr** [comment]
hm.. this might have a dependency on how we solve the slow loading state of the filelist (https://github.com/owncloud/web/issues/7038)

some thoughts:
- **pagination** I'm not a fan of the pagination in the regular files list , but for the search results a pagination is legit
- **lazyloading** would be legit for both, regular files list and search result page, main problem here is to make it accessible
- **complexity maintenance** pagination comes with some complexity for features like sorting, grouping, select all / batch etc. -> if we decide to have pagination only for search results, it doesn't feel right to maintain such complexity for a one-time pattern thats not reused in other views


Proposals:
1. **Short term favorite:** a (cheap?) quickfix could be to communicate in oc10 somthing like "showing max. of 200 results"
2. return the total number of results so that we can provide a pagination
3. **Long term favorite:** show results via lazy loading (has a11y issues afaik)

--> I would favor Proposal nr 1, would you agree @JanAckermann ?

**Comment by JanAckermann** [comment]
Implemented: Short term favorite: a (cheap?) quickfix could be to communicate in oc10 somthing like "showing max. of 200 results"
