### ISSUE TITLE
UI glitch in user management

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/web#7199]
### Steps to reproduce
1. login as admin user
2. goto user management 
3. pick a user
4. switch between "details" and "edit user"

### Expected behaviour
Proper switch between panes

### Actual behaviour
![image](https://user-images.githubusercontent.com/1058116/176651937-1336b9b8-5fc6-4aeb-806d-68be1af26ced.png)

### Environment general
Linux

**Backend (ownCloud Core or Infinite Scale)**:
ocis beta4

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Environment ownCloud Infinite Scale
**Version:** ocis beta4

**Updated from an older Infinite Scale or fresh install:**
updated from beta3

**Where did you install Infinite Scale from:**
latest docker image

### Client configuration
**Browser:** Firefox 102.0

**Operating system:** Arch

**Comment by tbsbdr** [comment]
thy @dragonchaser! cant reproduce in beta5 on [https://ocis.ocis-web.latest.owncloud.works/](https://ocis.ocis-web.latest.owncloud.works/) (might be fixed)

could you please check if it still exists there and if yes, what browser + version are you using?
