### ISSUE TITLE
SERP: Refine filtered tag with searchphrase

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7208]
> Terminology: SERP = Search Engine Result Page

## User Story 
* > As a user I want to find files that are tagged, so that I can burndown a long list of tagged files.

## Value
* find related files regardless of their location, but only depending on the tag and its filenames.

## Acceptance Criteria
- [ ] In the SERP the respective filterchip for the selected Tag is rendered below the search field.
- [ ] The SERP can get refined with a regular searchphase, eg. "show all files tagged with `important` AND with "ocis" in filename"

## Definition of ready

- [ ] everybody needs to understand the value written in the user story
- [ ] acceptance criteria has to be defined
- [ ] all dependencies of the user story need to be identified
- [ ] feature should be seen from an end user perspective
- [ ] user story has to be estimated
- [ ] story points need to be less then 20

## Definition of done
- Functional requirements
- [ ] functionality described in the user story works
- [ ] acceptance criteria are fulfilled
- Quality
- [ ] codre review happened
- [ ] CI is green
- [ ] critical code received unit tests by the developer
- [ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
- [ ] no sonar cloud issues

Note on terminology:
"File" is always meant as "file and folder".

**Comment by JammingBen** [comment]
@tbsbdr Can we close this as searching for tags has been implemented by now?
