### ISSUE TITLE
Archiver (directory) download fails on macOS

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#7213]
### Expected behaviour
You can run E2E tests on any OS without having to set additional ENV vars

### Actual behaviour
Zip/Tar download success check fails on (my) macOS, see screenshot

<img width="871" alt="Screenshot 2022-07-04 at 17 36 22" src="https://user-images.githubusercontent.com/16822008/177185550-63b64692-a80c-4b8a-9814-f74942dcf41e.png">

**Comment by SwikritiT** [comment]
@pascalwengerter can you check again? Maybe https://github.com/owncloud/web/commit/b2af0b2948ffbb29c9207be97ccb0d51ba1b6c64#diff-a6b62897772087ba798e3f369081c8efa170a856ba42c02384aee8829789b9ec has fixed this.

**Comment by pascalwengerter** [comment]
Fixed via #7086, thx @SwikritiT for the ping
