### ISSUE TITLE
No share info / indicators from within received shares 

### ISSUE THREAD

**Issue by fschade** [owncloud/web#7220]
WAIT FOR https://github.com/owncloud/web/pull/7086 to be merged.

# Description
the ui currently does not show any indicators or sharing information from within received shares.

# Steps to reproduce
user a shares a resource to user b, user b then goes to the shared with me page, accepts the share, navigates into that share, the child resources do not show any sharing information information (indicators, sidebar share-panel)

**Comment by JanAckermann** [comment]
Not able to reproduce this one:
![image](https://user-images.githubusercontent.com/26169327/183866981-9a4d690d-653c-4a9e-ad7a-a8259f1d0690.png)

**Comment by kulmann** [comment]
Yes, the shared resource view (anything side a share from the `Shared with me` page) should only show resharing info. The fact that it's a share would be true for all items in the `Shared with me` page.
