### ISSUE TITLE
User unknowingly shares personal space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7225]
web: ownCloud Web UI 5.6.1
ocis: Infinite Scale 2.0.0-beta.4+24fbb4a38 Community

- admin creates folder with file and share to marie
- Marie accepts, opens the folder and clicks to button "show actions for current folder". click to to "Copy quicklink"

Actual: link created but for personal space. It's not secure because the user unknowingly shares all the resources from personal space. 

https://user-images.githubusercontent.com/84779829/177607347-4cf813e8-1145-4172-a70b-d02e40a61185.mov

**Comment by fschade** [comment]
@ScharfViktor, good catch, thanks. Fixed by https://github.com/owncloud/web/pull/7243, let's see if ci confirms it
