### ISSUE TITLE
Do not perform full app init cycle in token refresh iframe

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#7237]
This is a follow up ticket for #7072.

When using oidc/oauth2 without refresh_token (e.g. oidc without offline_access scope), inside the iframe a full app init cycle in the runtime is performed.
Can we avoid that to safe requests against the backend?

**Comment by kulmann** [comment]
Done in https://github.com/owncloud/web/commit/4538eea6ac4dd0ae14826106b0438376e3c355c6
