### ISSUE TITLE
Use `usePublicLinkPassword` composable consistently

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#7238]
…  and avoid direct usage of getter from store

This is a follow up ticket for #7072.

That PR introduced a new `usePublicLinkPassword` composable, we should make sure to use it, wherever possible instead of the getter it uses internally.

**Comment by lookacat** [comment]
@kulmann @dschmidt would close this issue since I didn't find a single case where its not using `usePublicLinkPassword`
