### ISSUE TITLE
Use `useAccessToken` composable consistently

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#7239]
… and avoid direct usage of old or new getter from store

This is a follow up ticket for #7072.

That PR introduced a new `useAccessToken` composable, we should make sure to use it, wherever possible instead of the getter it uses internally.

**Comment by kulmann** [comment]
Solved by moving authentication related state to a pinia store, available via composable `useAuthStore`. This is used everywhere, so the `consistency` nature of this issue is solved with a followup implementation.
