### ISSUE TITLE
The navbar is not reachable in mobile view

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#7253]
The navbar is not reachable in mobile view and some tablet views

### Steps to reproduce
1. Open with device toolbar of google chrome
2. Check different devices

### Expected behaviour
The navbar should be reachable (via the dedicated button/ swipe?)

### Actual behaviour
The navbar is not reachable
![Screenshot from 2022-07-08 15-34-43](https://user-images.githubusercontent.com/7430156/178003433-c1a7a519-1033-4bce-8bce-2cdb85af8e61.png)

**Comment by tbsbdr** [comment]
Hey Eliza, thanks for brining this up. Here are some proposals:

## 1 - Tabs

![](https://user-images.githubusercontent.com/26610733/180855941-420c310e-297f-4d33-a6cf-dcd686fbaf91.png)

## 2 - Dropdown

![](https://user-images.githubusercontent.com/26610733/180856350-4f82f92f-8eec-4da6-9594-1c54737f47d3.png)

## 3 - Bottom bar

![](https://user-images.githubusercontent.com/26610733/180856369-fdf7a1db-864d-405e-88e9-7992ce335c40.png)

## 4 - Burger Menu

![](https://user-images.githubusercontent.com/26610733/180856401-c0de5db1-d619-4e80-b0d4-249738f7b8e8.png)

I would favor  "1 - Tabs" or "4 - Burger Menu"

With burger menu we could tidy up the top bar and put account, feedback and theme-switcher into the menu.

We once scoped the "bottom bar" but it's really not ideal if there are more items ex. with oc10 or other items with ocis in the future. but we also must take efforts into account. CC @kulmann

**Comment by kulmann** [comment]
From my side this has very low priority at the moment. For the mobile resolutions we have native apps for both iOS and Android.

**Comment by tbsbdr** [comment]
> From my side this has very low priority at the moment. For the mobile resolutions we have native apps for both iOS and Android.

yes, same thinking here; thinking if we can provide a way to reach left sidebar items at all somehow or just show a screen that recommends the native apps.

**Comment by hodyroff** [comment]
Workaround, when you turn the phone vertical it works.
