### ISSUE TITLE
Keyboard shortcuts: selection glitches

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#7254]
Found some small glitches in the new keyboard selection options that need a followup after https://github.com/owncloud/web/pull/7153 got merged

- [ ] ~~holding down an arrow key (up/down) in the file list feels very laggy~~ this only happened in dev build for me, not when bundled into ocis and started without a dev server. Could you still have a look please if there is something impacting the render performance?
- [x] having a long file list (more rows than viewport height) and going down scrolls the view (good). Going back up immediately scrolls. I'd expect that scrolling only starts again when I reach the topmost row of the viewport and continue to move up. i.e. within the rows that are visible anyway we never want to scroll. only when I am about to reach an element which is not completely in the viewport.
- [x] using the arrow keys (up/down) or spacebar (toggle selection) only becomes available **after** I made a selection with the mouse. It should be possible to use the `TAB` key of the keyboard to reach the file list and then use the arrow keys or spacebar respectively.

**Comment by lookacat** [comment]
@kulmann closed this issue for now, first bulletpoint is not replicatable hope it may be fixed by now otherwise reopen the issue please :)
