### ISSUE TITLE
Extend DrawIO option to configure an external DrawIO server 

### ISSUE THREAD

**Issue by T0mWz** [owncloud/web#7257]
When you running a DrawIO server on premise, then you should nice if you can configure that backend in the DrawIO integration.

**Comment by kulmann** [comment]
@T0mWz could you check if a config like the following works for you?  https://github.com/owncloud/web/blob/1ad492a401365ad2ca10dc9def57130be0febd49/dev/docker/ocis.web.config.json#L35

**Comment by T0mWz** [comment]
@kulmann , nice! Yes, it works!  :-)
