### ISSUE TITLE
External Sites alternative for Web

### ISSUE THREAD

**Issue by T0mWz** [owncloud/web#7260]
Within OC10 you're able to configure `external sites` which will shown up as an application icon in the menu and opens a website in a frame within the OC10 environment.

Should be nice to have an alternative for that, which gives you the option to; 
 1. Configure a external app
 2. By providing a external URL
 3. With an own custom icon
 4. Configurable that it only shows up for certain group in the menu

To give you an idea, the currently (extended option) within OC10

![ExternalSitesOC10](https://user-images.githubusercontent.com/2477797/178217115-37154c6e-2fbf-46f3-b227-edda92889938.png)

![ExternalSitesOC10Menu](https://user-images.githubusercontent.com/2477797/178217285-2c460733-4e28-4a87-9552-34793101d889.png)

**Comment by T0mWz** [comment]
As discussed with @kulmann and @dschmidt , this feature is basically an extension of the Web External app (https://github.com/owncloud/web/tree/master/packages/web-app-external).

This app can be configured with an array of external urls, which will be presented as an app in an iframe within the Web environment.

If we can extend this array with the follow option, then it will be really useful to easily integrated external "apps" into the front-end.
These options well be; 
1. An filter option that a menu icon will only be presented to an user, when this user is member of a certain group, which is coupled to this menu option. This will be useful, that you can make some icons visible to all users, like a link to a wiki or help / feedback forum. But that certain endpoints only will be presented to a specific group, which you can filter out from the menu. Like a research tool for the user group scientists. 
2. Nice to have,  an option to provide an own/custom menu icon, instead of having to choose from the native ownCloud icons. When an icon location is provide (like http(s):///myicon.), use the icon from that endpoint. 

This requires an extension of the array which can be provided to this Web External app.
See here an example of this `applications` array; https://owncloud.dev/clients/web/deployments/oc10-app/#configure-owncloud-web

**Comment by dschmidt** [comment]
Superseded.
