### ISSUE TITLE
Balance out acceptance test durations

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#7261]
## Summary
When checking recent nightwatch acceptance test runs in CI, the individual pipelines need anywhere between ~4min and ~19min to finish. Ideally, we can redistribute tests so we have quicker CI runs overall and don't wait for few long-running individual pipelines after most of them finished quickly

## Acceptance criteria
- [ ] Don't increase the amount of nightwatch acceptance test pipelines
- [ ] CI got faster (we're mostly in the 35-40min range currently)

**Comment by grgprarup** [comment]
This will be tracked from issue https://github.com/owncloud/QA/issues/765. So closing this issue.
