### ISSUE TITLE
No InfiniteScroll/Pagination on user-management pages users/groups

### ISSUE THREAD

**Issue by cakiwi** [owncloud/web#7266]
## Describe the bug

When number of entries is longer than the window can display no scroll or pagination occurs.

## Steps to reproduce

1. Create a lot of users.
2. Create a lot of groups.

## Expected behavior
Scrolling or pagination should occur to view all users.

## Actual behavior
Only the usernames on the 'current page' are visible. Zooming browser window will display more users.

## Setup
https://owncloud.dev/ocis/deployment/ocis_traefik/

firefox or chrome on ubuntu

**Comment by JanAckermann** [comment]
@kulmann any simple solution for this?
