### ISSUE TITLE
Can't see the name of the group in dark mode theme

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7269]
ownCloud Web UI 5.7.0-rc.5 

Steps:
- switch to dark mode theme
- open "user management"
- try to add user to group 

Actual: 
dark mode: 
![Screenshot 2022-07-12 at 15 08 47](https://user-images.githubusercontent.com/84779829/178498547-b78c4ca7-7c1b-4adc-8a64-e1e925cb6e43.png)

Light mode:
![Screenshot 2022-07-12 at 15 09 38](https://user-images.githubusercontent.com/84779829/178498653-302fa430-d73c-4067-ac43-5945da2de5c4.png)

**Comment by JanAckermann** [comment]
General ODS Problem
