### ISSUE TITLE
Backend version is not showing up in console anymore

### ISSUE THREAD

**Issue by micbar** [owncloud/web#7272]
### Steps to reproduce
1. Log in
2. Open debug tools
3. Open Console

### Expected behaviour
The web version and the ocis backend version should be visible

### Actual behaviour
Only the web version is visible, backend version is missing

### Environment general
**Operating system**:

**Backend (ownCloud Core or Infinite Scale)**:
Infinite Scale 2.0.0-beta.4+dev

**Comment by pascalwengerter** [comment]
Can confirm this. We only fetch capabilities during the `updateContext` so they're empty in the `renderSuccess` (which produces the logs and would need capabilities to show the backend version)
