### ISSUE TITLE
Need redirect to files/spaces/projects after disabling or deleting space 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7291]
Web UI 5.7.0-rc.5 
ocis: Release 2.0.0-beta.5

Steps: 

- admin creates project space
- opens the space. On the context menu, click disable and then delete

Expected: the space is deleted. redirect to `https://localhost:9200/files/spaces/projects`.

Actually: the user is still on the project space page. all buttons are available, after clicking we get an error

https://user-images.githubusercontent.com/84779829/179699342-467dbd51-53b0-4d55-99a2-78038709c98b.mov

**Comment by JanAckermann** [comment]
Should rather be after disabling space, because some actions are not available on a disabled space, e.G creating a folder

**Comment by ScharfViktor** [comment]
> Should rather be after **disabling** space, because some actions are not available on a disabled space, e.G creating a folder

Probably need redirect after disabling and deleting.
in case: 
- manager disables space
Expected: redirect to `https://localhost:9200/files/spaces/projects`
- manager opens disabled space. Checks something out there
- manager deletes space
Expected: redirect to `https://localhost:9200/files/spaces/projects`

**Comment by JanAckermann** [comment]
Afaik it's not possible to open a disabled space, let me check again

**Comment by JanAckermann** [comment]
>If I have plenty of privilege, how do I find the disabled spaces, re-enable a disabled space, or completely delete a disabled space.
This is still possible in the spaces overview

**Comment by ScharfViktor** [comment]
`404 Resource not found` It's a little confusing for the user. 
It would be cool to get 400 with message that you cannot open disabled space  

https://user-images.githubusercontent.com/84779829/181006842-8f959acb-95c1-42c8-8a9a-dc9fe8506d57.mov

**Comment by JanAckermann** [comment]
As decided with @tbsbdr 
1. Disabling a space will redirect to spaces overview
2. Trying to enter a disabled space will show a warning message and space can not be entered
