### ISSUE TITLE
Uuid instead of shared file name

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7292]
Web UI 5.7.0-rc.5
ocis: Release 2.0.0-beta.5

Steps:

- admin creates a file and shares to marie 
- marie accepts the file and open

Expected: correct file name

Actual: uuid instead of name

<img width="865" alt="Screenshot 2022-07-19 at 10 14 36" src="https://user-images.githubusercontent.com/84779829/179701690-78772591-50f7-456d-bfd0-3c7e97353117.png">

**Comment by JammingBen** [comment]
Will possibly be solved via https://github.com/owncloud/web/pull/7485
