### ISSUE TITLE
Shared via link: right sidebar is broken, content is shown in tiny area

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7301]
### Steps to reproduce

1.  login to https://ocis.ocis-web.latest.owncloud.works/
2.  create a link
3.  navigate to "Shares" -> "Shared via link"
4.  select a resource
5.  open right sidebar
6.  right sidebar is broken, content is shown in tiny area

![Screenshot 000030@2x](https://user-images.githubusercontent.com/26610733/179955664-f3bcdf11-f995-430a-bdad-d2cd5e54458d.png)

### Expected behaviour

RIght sidebar should be shown like in other views

### Actual behaviour

content is shown in tiny area

**Comment by JanAckermann** [comment]
Not reproducible with latest master, @tbsbdr feel free to re-open if the bug occurs again

**Comment by JammingBen** [comment]
I am able to reproduce this now, it's actually an edge case for shared resources that you first received as share. Share a resource from the "Shared with me" table via link. Then head to the "Shared via link" panel and open the sidebar for this resource -> looks broken.

Could be related to https://github.com/owncloud/web/issues/7347

**Comment by JammingBen** [comment]
This seems to be fixed with the addition of the `shareId` to the resource.
