### ISSUE TITLE
Safari 14.1 + 15.5: rightclick-context menu appears always next to 3-dots-quickaction

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7302]
### Steps to reproduce
1. login to https://ocis.ocis-web.latest.owncloud.works/
2. create a resource
3. rightlick on the resource
4. rightclick-context menu appears always next to 3-dots-quickaction

https://user-images.githubusercontent.com/26610733/179959640-94dc4dbb-652f-48d9-8ba4-4eeecc3d413f.mp4

### Expected behaviour
context-menu should appear next to the mouse pointer

### Actual behaviour
rightclick-context menu appears always next to 3-dots-quickaction

### Environment general
- Safari 14.1 (M1 Silicon)
- Safari 15.5 (Intel)

**Comment by JanAckermann** [comment]
Also happens with FF 102.0.1
