### ISSUE TITLE
Scoped links: Can't create private-ish links

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7304]
### Steps to reproduce
1. Login to https://ocis.ocis-web.latest.owncloud.works/
2. click on "copy quicklink"
3. quicklink shows "Recipients can view and download contents."
4. there is no option to create a link that works only as a pointer for invited people

### Expected behaviour
- Option to have a link that works only as a pointer for invites people/space members
- actual feature description: https://github.com/owncloud/web/issues/6844

### Actual behaviour
- I can only create public-ish links

**Comment by kulmann** [comment]
Creating them is implemented in https://github.com/owncloud/web/pull/7133 (not merged yet, because it has no test coverage, yet). Resolving them is not possible, yet.

**Comment by kulmann** [comment]
Reminder to self and @dschmidt : for public links we also want to resolve the user into the correct context. For that we need an active user session. We wanted to look at the `session monitor` feature from `oidc-client-ts` to see if we can determine the login state without a roundtrip to the IdP.
