### ISSUE TITLE
Can't remove password from link

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7307]
### Steps to reproduce

1.  login to https://ocis.team.owncloud.works/
2.  create a pw protected link
3.  remove password
4.  try to open link
5.  password is still required

### Expected behaviour

link should be accessible without password

### Actual behaviour

passwords needs to be entered

**Comment by JanAckermann** [comment]
@tbsbdr 3.Stop should be remove password, correct?

**Comment by tbsbdr** [comment]
jo

**Comment by JanAckermann** [comment]
Error is in backend, will be fixed by: https://github.com/cs3org/reva/pull/3094
