### ISSUE TITLE
Project space have public links from the another project space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7316]
maybe related: https://github.com/owncloud/web/issues/7268

 ownCloud Web UI 5.7.0-rc.5 
ocis: 2.0.0-beta.5

Steps: 
- Katherine creates project space "first" and shares it via public link ""
- Katherine creates project space "second" and shares it via public link 
- Katherine opens "second" project space and clicks  to "show members"

Expected:  Katherine cannot see link from "first" project space

Actual: Katherine can see link from "first" project space. 

![Screenshot 2022-07-22 at 11 29 55](https://user-images.githubusercontent.com/84779829/180410572-d0c7eba8-28a2-4cf2-997f-e0f3bf94a7da.png)

**Comment by kulmann** [comment]
Please test with web master. Has been fixed in https://github.com/owncloud/web/pull/7294

**Comment by ScharfViktor** [comment]
Yes, you are right. It fixed
