### ISSUE TITLE
Share with people: Can't find people by last name

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7328]
### Steps to reproduce
1. login as admin on https://ocis.ocis-web.latest.owncloud.works/
2. create new user: User name `username`, Display Name: `first and last name`, mail: `mail@example.com` role: `User`
3. search for `last name`
4. Can't find people by last name

## userdata:
<img width="455" alt="Screenshot 000057@2x" src="https://user-images.githubusercontent.com/26610733/180929382-99b59b32-fd98-4ec3-988c-15c5eb121186.png">

## works - ok:
<img width="521" alt="Screenshot 000056@2x" src="https://user-images.githubusercontent.com/26610733/180929218-74ee711f-6e29-4b77-a483-d9dd91955500.png">

## Can't find people by last name:
<img width="500" alt="Screenshot 000058@2x" src="https://user-images.githubusercontent.com/26610733/180930025-70b2e0ff-9757-429b-a894-8b67db56e1a8.png">

### Expected behaviour
- People should be found by last name
- General: if the search phrase is contained, there should be a searchresult

### Actual behaviour
Can't find people by last name

**Comment by JanAckermann** [comment]
This seems to be a problem in the backend, sharees api doesn't return any results

![image](https://user-images.githubusercontent.com/26169327/180959287-74d70d8a-a21e-4866-be6c-34d11095ef48.png)
![image](https://user-images.githubusercontent.com/26169327/180959364-0a19a5af-eb4a-4ded-a8a5-a38f74e21e34.png)

**Comment by JanAckermann** [comment]
Issue opened in ocis repo:
https://github.com/owncloud/ocis/issues/4282 

FYI @kulmann

**Comment by tbsbdr** [comment]
backend issue, tracked here: owncloud/ocis#4282 thx @JanAckermann
