### ISSUE TITLE
Batch-Delete of > 22 files fails

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7329]
### Steps to reproduce
1. login to https://ocis.ocis-web.latest.owncloud.works/
2. upload this folder ("🗂 2k Files inside"): https://cloud.owncloud.com/index.php/s/xnvEvwmwbC7qF7a
3. enter folder "2k Files inside"
4. set pagination to 1.000
5. enjoy how fast the listing shows up now
6. select all 1.000 files in the view
7. Delete
8. Ui shows error messages "Failed to delete 'File XXX'"
9. Files are not moved to the trash bin

## Note
- deletion generally works but stopped working at batch delete of ~22 files on my side
<img width="1502" alt="Screenshot 000060@2x" src="https://user-images.githubusercontent.com/26610733/180931243-44e50cd4-5cdf-4c78-bd47-03b795f6d353.png">

https://user-images.githubusercontent.com/26610733/180931263-d7dbfbd5-995f-4fea-ba57-4aa9873194c6.mp4

### Expected behaviour
- Deletion of many should be possible (same behaviour occurs if I try to delete 40 files)
- Deletion should be performed fast (~1 second)

### Actual behaviour
- Ui shows error messages "Failed to delete 'File XXX'"
- Files are not moved to the trash bin

**Comment by kulmann** [comment]
Related to https://github.com/owncloud/web/issues/7039
