### ISSUE TITLE
Notifications block right sidebar

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7330]
### Steps to reproduce
1. login to https://ocis.ocis-web.latest.owncloud.works
2. create > 5 links for a file
3. open sidebar for that file
4. ex. batch-delete 100 files so that you get some notifications
5. right sidebar elements are blocked by notifications

![Screenshot 000062@2x](https://user-images.githubusercontent.com/26610733/180934412-8ef4e6dc-a2fe-483a-8354-67b8e23b4641.png)

![Screenshot 000068@2x](https://user-images.githubusercontent.com/26610733/180941592-05862a9d-9c80-4803-83cf-973aa3fcf9ab.png)

### Expected behaviour
- UI Elements should not be blocked / blocking
- Possible solution:
  - make notifications dismissible
  - move them to the bottom left
  - aggregate multiple notifications into a single overlay so that they don't take up to much space. on click shows all notifications.

### Actual behaviour
- UI Elements are blocked by notifications, esp. when there are many notifications.

---------------------------
---------------------------
---------------------------

## Note on our upload widget
UI is also blocked by the upload widget, but as you can collapse it and as information there are more continuously relevant, its not as disturbing as the notifications. btw: onedrive did a quite well job on the integration of the upload widget: collapsed version is integrated (not overlayed) into the ui; expanded version is implemented as a modal.

### Collapsed and Integrated:
![Screenshot 000063@2x](https://user-images.githubusercontent.com/26610733/180937716-460a15e9-2700-40ad-88f4-99ad3d337baf.png)

### Expanded and modal:
<img width="1500" alt="Screenshot 000064@2x" src="https://user-images.githubusercontent.com/26610733/180937747-a5f32e7e-d5c4-4be0-98ec-3259ca2ab2a7.png">

**Comment by hurradieweltgehtunter** [comment]
https://github.com/owncloud/web/pull/8613 fixes this a bit by making notifications dismissable

**Comment by JanAckermann** [comment]
Notifications are now dismissible. Closing.
