### ISSUE TITLE
"?" - Contextual help overlay looks unbalanced

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7331]
### Steps to reproduce
1. click on the contextual helper ex. on "Share with people" or "Share via link"

#### All bold, padding looks unbalanced
<img width="461" alt="Screenshot 000065@2x" src="https://user-images.githubusercontent.com/26610733/180939771-429eec4d-016b-4ad1-bdc8-a8e4dd963db4.png">

#### padding looks unbalanced
<img width="380" alt="Screenshot 000066@2x" src="https://user-images.githubusercontent.com/26610733/180939976-84dfcd2a-17ad-482c-8271-d455e09beb57.png">

#### padding and font sizes look unbalanced
![Screenshot 000125@2x](https://user-images.githubusercontent.com/26610733/181202470-67c1c073-459c-4593-bfc4-784e380de520.png)

### Expected behaviour
- look & feel should be aligned to the design
- added X as an optional option to close the overlay (nice to have)
- figma link: https://www.figma.com/file/EqAiB1wY7cYaMaitjyzup3/Current-oC-Web-UI-Kit-(WIP)?node-id=2214%3A223165

<img width="1353" alt="Screenshot 000069@2x" src="https://user-images.githubusercontent.com/26610733/180947876-61dba789-440f-4f7f-9a52-c89dc2d4b5d8.png">

### Actual behaviour
Contextual help overlay looks unbalanced

**Comment by tbsbdr** [comment]
update: added "Access Details" screenshot

**Comment by tbsbdr** [comment]
update: added figma link

**Comment by JanAckermann** [comment]
@tbsbdr 
I know some work is required, but could you make simple screens like that
with all contextual helpers you want to have changed?

![image](https://user-images.githubusercontent.com/26169327/181582738-26c35396-28a8-40eb-b76f-4a5c7af276b2.png)

**Comment by JanAckermann** [comment]
ODS change is here - https://github.com/owncloud/owncloud-design-system/pull/2271
Now we need to apply the changes in web

**Comment by tbsbdr** [comment]
> could you make simple screens

👍 will do. thx for the ODS Change

**Comment by tbsbdr** [comment]
@pmaier1 can you tell if the helper texts are helpful (and correct)? Would appreciate your opinion.

# 1) Helper Share via link
![Helper Share via link](https://user-images.githubusercontent.com/26610733/182438305-502ac936-ad8b-42ea-823e-54e2702b48b1.png)

# 2) Helper Share with people
![Helper Share with people](https://user-images.githubusercontent.com/26610733/182438310-a0cf6ae7-a1c7-44cc-97fd-13fb505e9fa8.png)

# 3) Helper Access details
![Helper Access details](https://user-images.githubusercontent.com/26610733/182438313-a5b2acbe-92d4-424c-b799-cfc02a24eae5.png)

# 4) Helper Indirect links
![Helper Indirect links](https://user-images.githubusercontent.com/26610733/182438315-cc2bf61f-fb19-41af-b0dd-47814dfac856.png)

# 5) Helper Space Members
![Helper Space Members](https://user-images.githubusercontent.com/26610733/182438317-d50e6f3d-ffcb-40e8-a7e9-8be4a5c1e1a6.png)

**Comment by JanAckermann** [comment]
@tbsbdr 😍
Can you provide a link to the texts so I can copy them after @pmaier1 gave feedback ?

**Comment by JanAckermann** [comment]
Note: Access details is no oc-ct-helper but  oc-drop needs to be adjusted with the same style

**Comment by pmaier1** [comment]
Nice! Some remarks:
- 4) There are also indirect user shares. Are those covered as well?
- 5) Space managers also have full editor permissions and can manage space properties like description, disable/enable, delete

**Comment by tbsbdr** [comment]
# 1) Helper Share via link

![](https://user-images.githubusercontent.com/26610733/182792429-d54792ad-93a2-427d-a5f3-02d6a0b16ac9.png)

Texts:

### Select who can access links

**Only invited people can access**  
Account and login is required. Only people from the list "Invited people" can access.

**Everyone with the link**  
No login required. Everyone with the link can access. If you share this link with people from the list "Invited people", they need to login so that their individual assigned permissions can take effect. If they are not logged-in, the permissions of the link take effect.

Learn more (https://doc.owncloud.com/webui/next/owncloud_web/web_for_users.html#sharing)

# 2) Helper Share with people

![](https://user-images.githubusercontent.com/26610733/182792471-66bc2815-7371-4dca-8fc7-ef79cf3bb8e4.png)

Texts:

### Invite specific people

Enter a name or group to share this item.

**Subfolders**  
If you share a folder, all of its contents and subfolders will be shared as well.

**Notification**  
Invited people will be notified via email or in-app notification.

**Incognito**  
Invited people can not see who else has access.

Learn more (https://doc.owncloud.com/webui/next/owncloud_web/web_for_users.html#sharing)

# 3) Helper Access details

(outlook - we could show more details in the future. currently this is mainly used to keep the shares-list clean, i.e. let not so important infos take a backseat here in the Access details)  
![](https://user-images.githubusercontent.com/26610733/182792497-14591137-a8ca-449e-8c1b-ce2d8588f0b8.png)

Texts

*   Name
*   Additional info
*   Access expires ("No" or \<Date>)
*   Shared on
*   Invited by
*   Recent view or download of the share ("Never" or \<Date>)

~Learn more~ (Will be documented as soon as we extend the infos)

# 4) Helper Indirect links

![](https://user-images.githubusercontent.com/26610733/182792528-f594665c-aebb-4a05-8467-51b6e30c97fc.png)

Texts:

### What are indirect links?

Indirect links are links giving access by a parent folder.

**How to edit indirect links**  
Indirect links can only be edited in their parent folder. Click on the folder icon below the link to navgate to the parent folder.

Learn more (https://doc.owncloud.com/webui/next/owncloud_web/web_for_users.html#sharing)

# 5) Helper Space Members

![](https://user-images.githubusercontent.com/26610733/182795877-cee2916c-9771-4eb7-9c74-207de700352c.png)

Texts:

### Add members to this Space

Enter a name to add people or groups as members to this Space.

**What members can do**  
Members can see who else has access to this space and can access all files in this space. Read or write permissions can be set by the member’s role such as “Viewer” or “Editor”.

**What Space managers can do**  
Members with the Manager role can edit all properties and content of a Space, such as adding or removing members, sharing subfolders with non-members, or creating links to share.

Learn more (https://doc.owncloud.com/webui/next/owncloud_web/web_for_users.html#sharing)

# Note on "Learn more" links

*   I would already set the links although the docu is not written in detail for all the items.
*   Setting the links should also make users aware that there is a docu
*   Settings the links should give us a push to document the items i.e. give those items prio as they are not self-explanatory via the ui.
*   Links should be updated to more specific anchors as soon as we have them written / documented (currently they only link to #sharing -anchor) 

cc @EParzefall @mmattel please take notice that we have those contextual helpers "?"

**Comment by tbsbdr** [comment]
> Note: Access details is no oc-ct-helper but oc-drop needs to be adjusted with the same style

@JanAckermann yep, noticed that as well. I thought it's a good idea to unify all kinds of "Informational ui" towards the enduser so that they don't need recognise too many different kinds of "informational ui" elements.

@pmaier1 

> 1.  There are also indirect user shares. Are those covered as well?

added it to the "share with people" helper text

> 1.  Space managers also have full editor permissions and can manage space properties like description, disable/enable, delete

Updated the text accordingly: texted it more examplarily "..such as..." to communicate implicity that the helper text is not the docu and should not taken as as comprehensive feature description.

**Comment by tbsbdr** [comment]
"Access details" helpers will get tackeled in #7340
