### ISSUE TITLE
Missing filetype Icon in details pane

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7337]
### Steps to reproduce
1. open details for a resource without preview
2. there is no icon
![Screenshot 000092](https://user-images.githubusercontent.com/26610733/181036506-8032c82c-f3fb-4806-8a75-d33bfc7f0ed1.png)

### Expected behaviour
Show filetype icon in the details pane if there is not preview.

![Screenshot 000094](https://user-images.githubusercontent.com/26610733/181035933-5fef06aa-a1f1-4da7-b7fb-d0d77e079f46.png)

![Screenshot 000095](https://user-images.githubusercontent.com/26610733/181036039-a893a962-0bfc-4548-96ff-abc65088034d.png)

**Comment by JanAckermann** [comment]
But we have the icon left of the filename, isn't is enough? 
![image](https://user-images.githubusercontent.com/26169327/181049147-e942ee60-13e2-4e25-84ab-cc329c96ec6d.png)

**Comment by JanAckermann** [comment]
@tbsbdr happy with the presentation?
![image](https://user-images.githubusercontent.com/26169327/181051332-a7a4596b-6ee7-4560-b07c-d35823e460ff.png)

**Comment by tbsbdr** [comment]
almost happy :-) I ❤️ it as it adds more whitespace and feels more relaxed like this.
In "details" the small icon next to the resourcename should be removed to avoid duplication (also for files with a preview).
On sub-panels the small icon should be there so that the user can recognise that he/she is on the right file.
CC @kulmann 

![Screenshot 000108](https://user-images.githubusercontent.com/26610733/181055658-0aa93037-d371-4af2-893d-694bbd08db45.png)

![Screenshot 000106](https://user-images.githubusercontent.com/26610733/181055672-47d5bf68-546d-448a-b226-9f9463f74d7a.png)

**Comment by JanAckermann** [comment]
@tbsbdr thx for feedback,  implemented
