### ISSUE TITLE
Missing finedesign in Shares Panel

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7340]
### Steps to reproduce
1.login at https://ocis.ocis-web.latest.owncloud.works/
2. share a fiel with several people
3. create 4 links for the same resource
4. Shares panel looks not well visually tidied up yet

![Screenshot 000098](https://user-images.githubusercontent.com/26610733/181039119-842c4d6b-d12a-4985-a745-c759cea64ee1.png)

### Expected behaviour

- [x] remove top- and bottom seperators from header
- [x] remove resource size and modified date from header
- [x] Add contextual help "?" next to "Share with people"
- [x] move helper text into "?"
- [x] round corners for the group-background https://github.com/owncloud/owncloud-design-system/pull/2242
- [x] adjust avatar size to 36 px
- [x] adjust avatar initials to regular font weight (not bold)
- [x] center-vertical 3-dots button, "via" and exp. date (related to the whole collaborator-item)  
- [x] reduce whitespace between resource-name and "Share with people" area
- [x] "Via <Folder>" should get truncated 
- [x] Adjust Access Details so that it looks like the Context-Helper UI

screens are not 100% up to date, as we reworked the position of the roles and removed the user-types, but should give an impression what the design goal is.

<img width="787" alt="Screenshot 000182@2x" src="https://user-images.githubusercontent.com/26610733/182148246-f292733b-73a6-4c38-9fe7-b0a37f5f793c.png">

![Screenshot 000099](https://user-images.githubusercontent.com/26610733/181039549-0ba63a39-0640-413e-87f5-7c556d85a08f.png)
![Screenshot 000100](https://user-images.githubusercontent.com/26610733/181039754-7057d7b0-946c-4fc7-b938-86d391275206.png)

## Helper Access details

(outlook - we could show more details in the future. currently this is mainly used to keep the shares-list clean, i.e. let not so important infos take a backseat here in the Access details)  
![](https://user-images.githubusercontent.com/26610733/182792497-14591137-a8ca-449e-8c1b-ce2d8588f0b8.png)

Texts

*   Name
*   Additional info
*   Access expires ("No" or \<Date>)
*   Shared on
*   Invited by
*   Recent view or download of the share ("Never" or \<Date>)

~Learn more~ (Will be documented as soon as we extend the infos)

**Comment by kulmann** [comment]
Would like to see written down acceptance criteria here. Otherwise the design screenshots leave too much room for interpretation.

**Comment by tbsbdr** [comment]
update: added ACs (checklist in initial post) to make changes more transparent

**Comment by tbsbdr** [comment]
regarding #7372 :

"Via" needs some truncation:

![](https://user-images.githubusercontent.com/26610733/182150094-7ca19dc5-a662-4dd0-b751-6a1f8f585fd1.png)

flip order of the items in the collaborators item; should be "via", then "exp. Date"  

![](https://user-images.githubusercontent.com/26610733/182151017-0e3b6fc7-bc55-48ed-b635-34d2a3d6f173.png)

**Comment by JanAckermann** [comment]
TBD

**Comment by JanAckermann** [comment]
Follow up: https://github.com/owncloud/web/pull/7402

**Comment by JanAckermann** [comment]
@tbsbdr 
I set the distance between Navbar-header, Navbar-resource-name and Navbar-body to 10px.
This is the same padding (10px) we already used for the left and right.

However, the distance between Share with people and Share via link is 16px. 

So we have the option to:
* Set the navbar distances to 16px 
* Set the Share with people and Share via link distance to 10px
* Leave it as it is 


![image](https://user-images.githubusercontent.com/26169327/182651445-ee8191f0-d5ab-4076-88bd-363fdaa8a421.png)

**Comment by tbsbdr** [comment]
ack

👍 nice, thanks - also for stating the other options

**Comment by tbsbdr** [comment]
Update: added "Adjust Access Details so that it looks like the Context-Helper UI"
moved here from #7331

**Comment by kulmann** [comment]
What about using our theme css variables for margin/padding? based on a grid of `8px`. Honestly not sure where we should hardcode margins and where to use the variables, but my gut feeling is that we should use the css variables here.

**Comment by JanAckermann** [comment]
@kulmann Totally agree
