### ISSUE TITLE
Users can't find "declined shares"

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7342]
### Steps to reproduce
1. Share some files with Albert
2. login as Albert
3. accept a share
4. decline a share
5. declined shares are hard to find, "toggle" pattern is hard to understand.

![Screenshot 000103](https://user-images.githubusercontent.com/26610733/181045139-8a3fcd14-4404-43cf-8918-91b69fe3e472.png)

### Expected behaviour
- Declined shares should be a dedicated 3rd, collapsed (?) item at the end of the "Shared with me" list (and not a toggle next to accepted shares)
 
@kulmann unsure why "Declined shares" should be collapsable. It's last in list and might thereby be obsolete. what do you think - make it collapsible or just have it like pending shares?

![Screenshot 000123@2x](https://user-images.githubusercontent.com/26610733/181186731-d8a93246-3044-4746-a268-7d5404de1097.png)

**Comment by kulmann** [comment]
@tbsbdr I don't have a strong opinion on the declined shares being collapsible or not. The idea was to declutter the view for users. Since declined shares are not what you're looking for most of the time we thought we could hide them initially and require a click to show them.

Before the change with categorization of shares into three different tables we only showed one big table with pending, accepted and declined shares all mixed together. Might be ok as well to have the three different tables below each other.

**Comment by tbsbdr** [comment]
ok, so if you don't veto I'd just have "Declined shares" expanded like the others. I guess the view could still be improved, but maybe this way has the best cost-effectiveness.

updated screenshot in initial post.

**Comment by kulmann** [comment]
We could make it collapsible, by default expand it, and let the admin overwrite the default via config.json. I guess users of instances with lots of shares are happy about improved render speed when the declined shares are not visible at all initially.

**Comment by tbsbdr** [comment]
one thing why I thought it's not worth making "declined shares" expandable is, that i assume the number of declined shares won't break the camel's back regarding speed. My hypothesis is, that the number of declined shares is comparatively low  (especially when Spaces kick in). So we might keep it simple.

I could image using filter-chips in the future to reorganize the shares-view more properly (as a general pattern also with )

My short vs. long term thinking is:

*   Short term (now): make it now work "good enough"
*   Long term: filter chips or similar pattern

would you agree for short term?

**Comment by kulmann** [comment]
Agreed 👍

**Comment by JanAckermann** [comment]
FYI @kulmann @kulmann : We have the possibility to only show 3 items and then show more toggle in the table footer.
Same as for pending shares, if you wish so

**Comment by kulmann** [comment]
> FYI @kulmann @kulmann : We have the possibility to only show 3 items and then show more toggle in the table footer.
> Same as for pending shares, if you wish so

Yes, good idea. Let's do that.
