### ISSUE TITLE
Shared via link > "parent folder" shows "Resource not found" on click

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7347]
### Steps to reproduce
1. receive a share
2. go to "shares" > "shared with me" > create a link for the with-you-shared file
3. go to "shares" > "shared via link" > click on the parent folder of the shared resource
4. View shows "Resource not found"

https://user-images.githubusercontent.com/26610733/181061204-6d205bdf-f99c-486a-b65b-cc2e813cad9a.mp4

### Expected behaviour
show "Shares" > "Shared with me" > "highlight resource"

### Actual behaviour
View shows "Resource not found"

**Comment by JammingBen** [comment]
It also breaks when sharing resources within the share via link. This is a similar challenge as in https://github.com/owncloud/web/issues/7043: We somehow need to determine if the resource is a share (that is easy) OR part of a share (that's not easy). Then we need to somehow retrieve the id of the underlying share to build the correct route and to show the proper parent name.
