### ISSUE TITLE
User management: Bottom bar should state "✅ Saved" on save (not "no changes" )

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7351]
### Steps to reproduce
1. login as admin on https://ocis.ocis-web.latest.owncloud.works/
2. go to user management
3. edit a user, click "Save"
4. bottom bar shows "no changes" after "save" had been clicked

https://user-images.githubusercontent.com/26610733/181183178-93af72a6-9236-47e4-8d89-195a6d026c3e.mp4

### Expected behaviour
bottom bar should confirm the latest action (for "revert" -> "no changes" is good 👍)
- If "Save" has been clicked, Bottom bar should state "✅ Changes saved" (until next changes are made)
- please check if the (then additional) notification is still necessary - could be too much redundant change on the screen. please adapt according to your impression

![Screenshot 000115@2x](https://user-images.githubusercontent.com/26610733/181182896-c1c35a9f-b1f7-431f-8a41-104c06442fb8.png)

### Please use the same check-icon like in the copy-link form
![Screenshot 000117@2x](https://user-images.githubusercontent.com/26610733/181183578-fb6df0ca-5fc6-4b14-afdf-94bb316944a3.png)

### Actual behaviour
bottom bar shows "no changes" after "save" had been clicked

**Comment by JanAckermann** [comment]
@tbsbdr any favorites in color of icon and saved text?

**Comment by tbsbdr** [comment]
please use the same text and icon color like we have for the copy-link confirmation (c.f. screenshot above)

**Comment by JanAckermann** [comment]
@tbsbdr  Looks unfortunately off in the dark mode
![image](https://user-images.githubusercontent.com/26169327/181793167-ccb627d3-f182-486b-8b8c-d0b7f701bdc8.png)
 
while looking good in light mode

![image](https://user-images.githubusercontent.com/26169327/181793249-d5802ce2-9917-4324-b8a9-28ca205272ca.png)

**Comment by JanAckermann** [comment]
Would suggest this:
![image](https://user-images.githubusercontent.com/26169327/181793558-a1f162c4-f32b-4844-8795-d822bf7ad398.png)

**Comment by tbsbdr** [comment]
👍 dark mode colors need an overhaul #7353
