### ISSUE TITLE
Loop when failing to load user information

### ISSUE THREAD

**Issue by diocas** [owncloud/web#7354]
We have an issue in our configuration that is making calls to `/ocs/v1.php/cloud/user` fail.
The user is correctly sent to the `accessDenied` page but, there, it will try to re-login again (indirectly, by redirecting the user to `/files/spaces`)... This causes the browser to enter a loop.
Although this is only seen in particular cases where the API fails when it shouldn't, I believe the web behaviour should be to not try to automatically re-login when in the accessDenied page.

Maybe somewhat related to #4677

**Comment by fschade** [comment]
https://github.com/owncloud/web/issues/4677
