### ISSUE TITLE
Sharing Panel: Show label instead of description

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7358]
Should show the label "Viewer" instead of whole description: 
![Screenshot 000136@2x](https://user-images.githubusercontent.com/26610733/181249644-088e728a-251a-40c9-b6bf-0d238b5d27ad.png)

**Comment by kulmann** [comment]
For indirect shares (no dropdown available as of now) -> show description in tooltip. For both link shares and people shares.
