### ISSUE TITLE
ODS design tokens are not aligned with Figma Design Colors

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7373]
### Steps to reproduce

Colors need to be double checked and adjusted, especially in dark mode. 
needs manual sync between figma colors and design system tokens by @tbsbdr  
Link to the Figma file: https://www.figma.com/file/EqAiB1wY7cYaMaitjyzup3/Current-oC-Web-UI-Kit-(WIP)?node-id=109%3A48360

![Screenshot 000165@2x](https://user-images.githubusercontent.com/26610733/181736946-4d27d78d-4439-4a5a-9d56-baecda072d11.png)

![Screenshot 000166@2x](https://user-images.githubusercontent.com/26610733/181737446-9ebe73f0-b912-4ca9-8585-dcedb08385f9.png)

relates to #7353 

## Expected behaviour

Balance colors according to design

<img width="1762" alt="Screenshot 000167@2x" src="https://user-images.githubusercontent.com/26610733/181737621-b8568aeb-7883-4aac-b8ea-4e3ad3d6ae48.png">

**Comment by fschade** [comment]
@tbsbdr can we provide a link to the figma design for contributors? Maybe we should also put the link into our docs or the gh readme to have it more prominent.

**Comment by tbsbdr** [comment]
sure, here comes the link to the Figma file / deeplink to colors:

https://www.figma.com/file/EqAiB1wY7cYaMaitjyzup3/Current-oC-Web-UI-Kit-(WIP)?node-id=109%3A48360
