### ISSUE TITLE
Shares: Wrong and missing share infos

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7374]
### Steps to reproduce
1. Login on https://ocis.ocis-web.latest.owncloud.works
2. `A` shares with `B` shares with `C`

### "Owner" should be "A"
![Screenshot 000133@2x](https://user-images.githubusercontent.com/26610733/181235093-6e55e04c-cdb2-44f1-91c9-40b008795629.png)

### Add "Owner" to Details-Panel
![Screenshot 000135@2x](https://user-images.githubusercontent.com/26610733/181235549-3b134132-5e3f-4d84-826b-8da3d5e64476.png)

**Comment by JammingBen** [comment]
@tbsbdr I can't reproduce the first screenshot, could you please elaborate what you did exactly to get there? The parent folder shows "Folder to be shared", so is the parent folder shared initially, or just this file?

**Comment by micbar** [comment]
Please be aware that owner is only available in personal spaces!

**Comment by micbar** [comment]
We always have a share creator, but in spaces the file owner is empty.

**Comment by tbsbdr** [comment]
> is the parent folder shared initially, or just this file?

just the file.

## Stept to reproduce

*   checkout current master (098b1f3)
*   `A` shares with `B` the file "`file.txt`"
*   `B` shares with `C` the file "`file.txt`"
*   As user `B`: navigate to `Shares` > `Shared with others` > select "`file.txt`" > Details 
*   Details show: "Owner: B"

## Current behaviour

*   Details show: "Owner: B"

## Expected Behaviour

*   Details show: "Owner: A"

**Comment by JanAckermann** [comment]
Outcome:
- Issue is not reproducible anymore for @tbsbdr after ocis upgrade, owner won't be shown in the shared resource at all
- Shares-> Shared with me column Share owner should be renamed to Shared by
- @tbsbdr and @pmaier1 will discuss if we should omit the owner field, if not we need to check what exactly it should display

**Comment by pmaier1** [comment]
Let's discuss. My opinion:
a) I want to see the owner (and potentially the resharer) of a share so that I know who the data belongs to / who gave me access.
b) I want to see the permissions I got granted so that I know what I'm allowed to do

**Comment by JanAckermann** [comment]
I like the idea!
Just some additional questions:
- Should we show those information on a public link ?
- If the sharer and the share owner are the same should we still display “owner” and “shared by” as they equal ?
- Can we find a better name instead of “owner”?

**Comment by micbar** [comment]
> Can we find a better name instead of “owner”?

CREATOR, it is always the share creator

**Comment by JanAckermann** [comment]
One more:
- if the file is not shared, should we still show owner/creator ?

**Comment by tbsbdr** [comment]
> *   Should we show those information on a public link ?

imo, nope. public link should not expose personal data of the sharer. those should only be visible after ex. a login.

> *   If the sharer and the share owner are the same should we still display “owner” and “shared by” as they equal ?

yes, we should make this explicit. otherwise the user would have to riddle why data are shown differently from time to time. 

> *   Can we find a better name instead of “owner”?

KREATOR is fine ;-)

**Comment by pmaier1** [comment]
> CREATOR, it is always the share creator

Disagree. If I share a folder with you and you upload a file into it, then you are the creator but I am the owner of the file. This is why I'd like to see the owner of the file and potentially the resharer.

**Comment by JanAckermann** [comment]
@pmaier1 

**a** shared file with **b**, **b** shared the share with **c** 

We are logged in as C, in the table we see 'Share owner' as b and in the right table Owner is 'a'.
The wording is a little confusing, any tips? 
 

![Screenshot from 2022-08-11 13-45-33](https://user-images.githubusercontent.com/26169327/184126467-fb4772e9-6335-4c80-89b8-60d6bf594905.png)

**Comment by kulmann** [comment]
The `Shared with` information is not so relevant for user shares. For group shares it is valuable information, as you might want to know **why** you have a certain share. User C might read `aha, this file was shared with the group "geniuses" and I'm part of that group`.

**Comment by pmaier1** [comment]
> The wording is a little confusing, any tips?

`Share owner` is the confusing part for me. There is an `Owner` who is the physical owner of the data. Then there is a `Sharer` or `Shared by` who is the user that created the share.

**Comment by micbar** [comment]
`Share owner` is the share creator

Please always consider that in oCIS we have no "File Owner" in spaces anymore. IMO we should skip this completely.

**Comment by tbsbdr** [comment]
Proposal:

*   [ ] rename ~Share owner~ --> "Shared by"

everything else is currently not important for GA and can stay as is. the initial bug does not exist any more.
