### ISSUE TITLE
Missing quota exceeded messages

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#7389]
### Steps to reproduce
1. Set a quota on the personal space via the graph api
2. upload data and see the upload fail
3. check the error message

### Expected behaviour
If the quota is exceeded we always get a message, that the quota is exceeded

### Actual behaviour
We don't always get a precise error message:

This uploads a single file that is already bigger than the quota.

![image](https://user-images.githubusercontent.com/34452982/182387669-28f7d39a-3111-49b3-8856-c14fea54dd86.png)

This uploads multiple files that in sum are bigger than the quota.

![image](https://user-images.githubusercontent.com/34452982/182388080-fd0cc789-9a8b-480a-b017-85a148c90ce8.png)

This uploads two files while one exceeds the quota:
![image](https://user-images.githubusercontent.com/34452982/182388500-514aba68-8df9-47b3-a6cb-f8fdfc1272ac.png)

### Environment general
**Backend (ownCloud Core or Infinite Scale)**:
oCIS owncloud/ocis@26f15c2 with ownCloud Web UI 5.7.0-rc.5

**Comment by JanAckermann** [comment]
I am not able to reproduce this properly, but this might be related to:
https://github.com/owncloud/web/issues/6930
