### ISSUE TITLE
Incorrect file path in search results

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7391]
ownCloud Web UI 5.7.0-rc.7 

Steps:
- admin creates "new/file.txt"
- admin tries to find by "file"
- in the search results try to click on the "new" folder

Expected: User goes inside the "new" folder and sees the contents

Actual: wrong path: PROPFIND `https://host.docker.internal:9200/remote.php/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157/new`

correct path: `https://host.docker.internal:9200/remote.php/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157%24some-admin-user-id-0000-000000000000/new`

https://user-images.githubusercontent.com/84779829/182406575-31ab6024-ee31-43a2-807a-67073830d7d8.mov

**Comment by hurradieweltgehtunter** [comment]
maybe related:

https://user-images.githubusercontent.com/16665512/182801881-12578202-e793-4fc0-aed9-5ae884630683.mov

File (PDF) is stored in personal quota but URL shows ".../spaces/..."

<img width="1678" alt="grafik" src="https://user-images.githubusercontent.com/16665512/182802094-1d7db49a-d439-460a-b617-5a83422bd35d.png">

**Comment by micbar** [comment]
Also related: The search results point to the wrong space:

1) File is in shares but shows up in `personal`
![1660216187436](https://user-images.githubusercontent.com/4378513/184120853-9d1c98b2-f7c4-48a0-bf49-16aeecbb4ae8.png)

2) File is in project space but also points to somewhere else

![1660216215939](https://user-images.githubusercontent.com/4378513/184120943-457859a6-f6df-4171-8bc3-c39c8a2b7f22.png)

**Comment by JanAckermann** [comment]
@kulmann GA Blocker maybe?

**Comment by kobergj** [comment]
https://github.com/owncloud/ocis/pull/4485

fixes the issues for non-shares

**Comment by JanAckermann** [comment]
Fixed via: https://github.com/owncloud/ocis/pull/4485
