### ISSUE TITLE
Regular member should not be able to change Space quota

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7400]
### Steps to reproduce
1. create a space
2. login as regular space member
3. regular member has the option in the context menu to change the quota 

### Expected behaviour
Regular member should not be able to change Space quota

### Actual behaviour
regular member has the option in the context menu to change the quota

**Comment by micbar** [comment]
There is a permission in the backend `SetSpaceQuota` which should be respected by the frontend.
