### ISSUE TITLE
Member of project space cannot see public resources link

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7406]
ownCloud Web UI 5.7.0-rc.7 
 Infinite Scale 2.0.0-beta.5+8d97b7e1a Community 

Steps: 
- admin creates space with folder and file
- admin creates public link to the folder and to the file
- admin adds marie as members of the space
- marie opens folder of the space and trie to find public link

Expected: marie can see public link

Actual: web sends 6 requests to the backend, and some requests contain links, but the user does not see the links on the page

![Screenshot 2022-08-04 at 16 45 59](https://user-images.githubusercontent.com/84779829/182881698-5c29b700-aba2-4507-a5d0-0396e73ca65a.png)

space_ref contains resorseId. Why we need `path`

**Comment by kulmann** [comment]
> space_ref contains resorseId. Why we need `path`

We don't (want to) know which backend we're talking to. So we send both `path` and `space_ref`. The backend choses what is to be used. oc10 backend will use the `path` as it doesn't know anything about the `space_ref`. `ocis` will use the `space_ref` and ignore the `path`.

**Comment by kulmann** [comment]
IMO a backend issue, no? @micbar ?

**Comment by micbar** [comment]
The indicators are broken in the backend. The ocs api returns the links correctly for the path or space_ref.

**Comment by ScharfViktor** [comment]
> > space_ref contains resorseId. Why we need `path`
> 
> We don't (want to) know which backend we're talking to. So we send both `path` and `space_ref`. The backend choses what is to be used. oc10 backend will use the `path` as it doesn't know anything about the `space_ref`. `ocis` will use the `space_ref` and ignores the `path`.

Okay, clear. 
web works with ocis and one of 6 requests get us link in response. Should we have link on the page? is it correct?
![Screenshot 2022-08-05 at 12 59 59](https://user-images.githubusercontent.com/84779829/183065043-53262aa1-788d-4132-8ae5-6d08ad7953a7.png)


request `https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares?space_ref=1284d238-aa92-42ce-bdc4-0b0000009157%24ff402562-8d09-4268-85de-bee2656f5f5d!f92b7df3-a74d-489c-9f4a-9533f43e3ec3&reshares=true` has link in response

**Comment by ScharfViktor** [comment]
> The indicators are broken in the backend. The ocs api returns the links correctly for the path or space_ref.

oops, it's not clear to me here. what indicators?

**Comment by ScharfViktor** [comment]
we have public link in response but haven't share. created backend issue: #4347

**Comment by kulmann** [comment]
Looked into the issue. This is a pure frontend issue: we hide the quick link entirely when the logged in user has no share permission. But what we need to do instead is to show the quick link component in readonly mode (only the `copy` action is allowed, everything else needs to be readonly).

**Comment by kulmann** [comment]
Why we have multiple requests needs investigation as well. Seems odd.
