### ISSUE TITLE
e2e tests. Public link for space story

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7407]
- [x] manager creates public link for the space https://github.com/owncloud/web/pull/7433
- [x] manager creates public resource(folder/file) link inside the space https://github.com/owncloud/web/pull/7433
- [x] manager adds members to the space https://github.com/owncloud/web/pull/7433
- [x] member(editor) can see public link for the space but cannot edit https://github.com/owncloud/web/pull/7433
After pressing the "show links" button, the link should be visible without the possibility of "editing"<img width="252" alt="Screenshot 2022-08-04 at 17 22 33" src="https://user-images.githubusercontent.com/84779829/182885574-63166ada-298b-479f-b69f-6293512115ed.png">

- [x] manager-member can see and edit public link to the space https://github.com/owncloud/web/pull/7484
- [x] manager-member change permissions of the link https://github.com/owncloud/web/pull/7484
- [x] member(viewer) can see public resources link https://github.com/owncloud/web/pull/7484
- [x] manager-member can see and edit public resources link https://github.com/owncloud/web/pull/7484

**Comment by SwikritiT** [comment]
All the PR's have been merged. So closing this
