### ISSUE TITLE
[Spaces] User search is cases sensitive

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/web#7411]
### Steps to reproduce
1. Enter lower case name in search field, to invite new users to a Space

### Expected behaviour
Adding new persons by name shouldn't rely on casing.

### Actual behaviour
Incorrect casing results in empty search result

### Environment general
**Operating system**:

Safari Version 15.6 (17613.3.9.1.5) on macOS Monterey 12.5 (21G72)

**Backend (ownCloud Core or Infinite Scale)**:

Infinite Scale

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Environment ownCloud Infinite Scale

https://ocis.team.owncloud.works/

![CleanShot 2022-08-05 at 12 53 37](https://user-images.githubusercontent.com/214010/183064171-690c5c54-9621-42d0-a57d-ea2a74e74cc1.png) | ![CleanShot 2022-08-05 at 12 56 30](https://user-images.githubusercontent.com/214010/183064182-eef0d173-b69a-494e-bbc5-5a78a14fc565.png)
-- | --

@kulmann @tbsbdr @pmaier1

**Comment by pmaier1** [comment]
Thanks for the report. I'd make this a GA-blocker if the others agree.

**Comment by JanAckermann** [comment]
Please note:
Searching for users is done by the backend not the frontend.
So the ticket should be moved to ocis repo.

On the other hand I am not able to reproduce the issue on latest web + latest ocis:
![image](https://user-images.githubusercontent.com/26169327/183085437-2cc56145-7763-4692-a811-696186546b34.png)

**Comment by pmaier1** [comment]
I think we've had a ticket in oCIS in that regard. Can't find it currently. Probably already fixed then. Close please, if confirmed working in latest.
