### ISSUE TITLE
OnlyOffice uses wrong language setting

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7419]
### Steps to reproduce
1. Set ownCloud to german
2. Open any file in OnlyOffice
3. OnlyOffice uses english as language

### Expected behaviour
OnlyOffice should use the language being set in ownCloud by the user

### Actual behaviour
English is used

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works/

**Comment by kulmann** [comment]
Needs a language setting for the `open` request of the wopi server, see https://github.com/owncloud/ocis/issues/4367
