### ISSUE TITLE
[QA] web-app fails in oauth

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#7429]
Seen while testing web-5.7.0-rc.8 with core 10.10
(With core 10.11.0-alpha.2 it fails with a guzzle error, see #5933 )

When logging in the admin user, after authorize, the redirect step hangs:
![image](https://user-images.githubusercontent.com/1108546/183930795-97f88de0-4031-44f7-9993-355ed9f2eec9.png)

[owncloud.log.zip](https://github.com/owncloud/web/files/9301018/owncloud.log.zip)

**Comment by kulmann** [comment]
Hmm... there is https://github.com/owncloud/web/pull/5933 but honestly I have no idea when the right time is for updating guzzle in web. Does the update to guzzle 7 break compatibility with older ownCloud 10 versions?

**Comment by kulmann** [comment]
@jnweiger do you see anything in the browser console that looks like an error?

**Comment by JammingBen** [comment]
Guzzle has been updated quite some time ago, I suppose the error does not exist anymore. Feel free to re-open if otherwise.
