### ISSUE TITLE
[QA] failing upload misses error messages from virus scanner

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#7432]
Seen while testing files_antivirus-1.1.0 with web-5.6.1 on core 10.10

* Prepare a local folder vir containing a collection of 6 eicar test signatures and other material.
* Use Upload -> Files and select an eicar test files. An error occurs. GOOD.
  - The error has no hint that a virus was detected. BAD
![image](https://user-images.githubusercontent.com/1108546/183960605-ae71538b-bdd1-470f-82ba-78f5a82bb950.png)

---

* Use Upload -> files and select all files in folder vir.
  - the clean files are uploaded. OK.
  - the infected files cause an error. OK 
  - number of reported elements is off by one, and the error message as above has no virus info. BAD

* Use Upload -> folder and select folder vir
  - the clean files are uploaded. OK.
  - the infected files are *not* uploaded. OKish 
 - The report reports 2 good files, but fails to report errors for the 6 not uploaded files.
 ![image](https://user-images.githubusercontent.com/1108546/183963080-81198773-c8e0-4814-9f30-9a3436a59514.png)

----

Good: An infected file was never uploaded.

Strange: Folder upload shows a security warning.
![image](https://user-images.githubusercontent.com/1108546/183961781-eb4d7345-a4cb-477f-8398-6fe6a1e44d8a.png)
- this leaves me puzzled, why selecting 7 files can be done without trusting owncloud, but selecting the folder with the same 7 files needs more trust. As a user, I have nothing to base my trust on. The obvious (but false) takeaway is that owncloud should no longer be trusted.

**Comment by kulmann** [comment]
The folder upload warning is a browser feature. Not something we can change unfortunately.
