### ISSUE TITLE
Fix WEB_UI_CONFIG message emitted in CI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#7452]
For example: https://drone.owncloud.com/owncloud/web/27540/44/21
```
	Could not read config file.
	Set correct path of config file in WEB_UI_CONFIG env variable to fix this.
	Some tests may fail as a result.
```

This message always appears. When people are looking into other failures in CI, it adds to the difficulty of debugging, because we see this "warning" message about "WEB_UI_CONFIG env variable" and have to understand that it is "normal" and is emitted all the time.

1) Investigate why this message is emitted.
2) Sort out a solution so that it is not emitted in the CI output

(Maybe we should actually set `WEB_UI_CONFIG`, maybe we should change the conditions under which the message is emitted, or...?)

**Comment by amrita-shrestha** [comment]
As suggested in comment https://github.com/owncloud/web/pull/7545#pullrequestreview-1091265641
> please check if that is also the case in the ocis repo

In ocis repo WEB_UI_CONFIG env variable is implemented in all acceptance tests related to the pipeline.
