### ISSUE TITLE
Stuck after session expired

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7453]
### Steps to reproduce
1. Log in
2. Wait until session expires
3. Following screen appears:

![Bildschirmfoto 2022-08-16 um 09 02 15](https://user-images.githubusercontent.com/16665512/184818095-65ed4057-fbb0-4488-8ab0-83fe4a9d1961.png)

4. Click on "exit" as suggested

### Expected behaviour
Two options:
- Auto-forward to login screen without this message. I think this is the most common behaviour, I was surprised that the mentioned message showed up at all. 

But maybe this is a required step so second option:
- Show this message but make the "exit" link an actual link. Currently it seems it's just an anchor:
`<a id="exitAnchor">exit</a>`

### Actual behaviour
5. Nothing happens, "exit" is a link without target.

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

**Comment by kulmann** [comment]
Apart from the reported bug, what do you mean by `wait until session expires`? As we have token renewal in place this should never happen... how to reproduce that? If I set the token lifetime to 1 minute (hardcoded in ocis and manually rebuild) the token renewal works as expected and I don't get logged out.

**Comment by hurradieweltgehtunter** [comment]
Not sure how it happens. I logged in yesterday, let it be, opened the browser tab today and this message appeared.

**Comment by kulmann** [comment]
Ah ok, then I understand that issue as well. There are two different ways to renew the token: with the (still valid) current access token before it expires or with a refresh token (which typically has a very long lifetime). Default oCIS uses the first way, meaning token renewal only works if the browser is open and you have a working internet connection / connection to the instance. If that's not the case and the token expires then you have nothing you can renew the token with -> the state that you described. Nothing wrong there (only the bug that you described initially), but I will discuss internally if we can hand out refresh tokens by default.

**Comment by JanAckermann** [comment]
Fixed by https://github.com/owncloud/web/pull/7491
