### ISSUE TITLE
Improve keyboard shortcuts copy/cut files

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7455]
### Steps to reproduce
1. Select file(s) / folder
2. Press shortcut Ctrl+X to cut selected files/folders

### Actual behaviour
Message appears "Copied to clipboard"

### Expected behaviour
Slight improvement:
There is no difference regarding the feedback message if user cuts (Strg+X) or copies(Strg+C) a file. Both shows "Copied to clipboard". While it is not really wrong it would be nive to have a more precise feedback, like "Cut to Clipboard".
Also, in addition, it would be nice to have some sort of visual indicator which files are cut, for example reduce the opacity.

![grafik](https://user-images.githubusercontent.com/16665512/184824532-6e806be5-da46-4d9d-9417-766938e13cdf.png)

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

**Comment by kulmann** [comment]
> Slight improvement: There is no difference regarding the feedback message if user cuts (Strg+X) or copies(Strg+C) a file. Both shows "Copied to clipboard". While it is not really wrong it would be nive to have a more precise feedback, like "Cut to Clipboard".

Agreed, would be beneficial and is easy to do.


> Also, in addition, it would be nice to have some sort of visual indicator which files are cut, for example reduce the opacity.

That's already implemented, but not yet deployed on that instance.
