### ISSUE TITLE
Open files in search context is broken

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7456]
### Steps to reproduce
1. Upload a file to a folder
2. Search for this file in the top search bar
3. Click on search results

### Expected behaviour
Depending on which search result the user click it should either
- open the file
- open the directory where file is found

### Actual behaviour
Broken screen appears (see video)

https://user-images.githubusercontent.com/16665512/184831377-a14a435a-fff6-4319-9dec-86ea60726b44.mov

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

#### Browser log
XHR request:
```
PROPFIND | 
scheme | https
host | ocis.ocis-wopi.latest.owncloud.works
filename | /remote.php/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157!65b1803d-f0ef-4dc0-a60d-8a1d0a597347/Beispiel.pdf
Statuscode: 404 (Not Found)
```

Reply:
```
<?xml version="1.0" encoding="UTF-8"?>
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns"><s:exception>Sabre\DAV\Exception\NotFound</s:exception><s:message>Resource not found</s:message></d:error>
```

<img width="1660" alt="grafik" src="https://user-images.githubusercontent.com/16665512/184832142-608a806d-d9a2-48ba-8798-c9b5c34de401.png">

**Comment by fschade** [comment]
@kulmann backend is involved, I can take it over in experimental

**Comment by JanAckermann** [comment]
Renamed the title a little, as I panicked before 😅

**Comment by JanAckermann** [comment]
Fixed via: https://github.com/owncloud/ocis/pull/4485
