### ISSUE TITLE
OnlyOffice: Different behavior when opening legacy formats

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7459]
### Steps to reproduce
1. Upload legacy format file (.doc)
2. Click on the file
3. Right-Click on the file, select "Open in OnlyOffice"

### Expected behaviour
Both clicks should either open the editor OR start a download

### Actual behaviour
Click starts the download, Context menu opens the editor.
Not sure if this is an unwanted behaviour but I was confused about the different behaviours.
AFAIK OnlyOffice doesn't support legacy formats any more since v7 which is even more confusing why it is still possible to open the document with the context menu.
Best user experience would be to have an automatic conversion to the newer file formats (.docx, .xlsx etc.)
Currently it is not clear (at least to me) how to convert legacy format files with OnlyOffice exclusively in the browser (there is a possibility to download the file in a newer format which then has to be uploaded again etc.)

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

https://user-images.githubusercontent.com/16665512/184846910-f193b491-d772-4609-829c-284a71206373.mov

**Comment by kulmann** [comment]
Explanation about what's happening here: The app provider backend announces available apps together with a flag whether or not the respective app is allowed to serve as `default app` for the given mime type. `default app` means that a left mouse click can open the file with that app (=> what you expected to happen). If none are available web has the download action as a fallback (=> what actually happened).

Two comments about that:
1. the issue itself has to be solved via configuration in the app provider. If no apps are configured as default for the mime type, web has to respect that.
2. web should be more transparent about what the default action is. I could imagine that the right-click context menu shows some indication which of the listed actions is the one that gets triggered on a left click for the specific file.

@tbsbdr what do you think?

**Comment by JammingBen** [comment]
Seems to be fixed meanwhile, closing here.
