### ISSUE TITLE
Safari glitch: rename icon cropped & resource name jitters

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7462]
### Steps to reproduce
1. open with safari: https://ocis.ocis-web.latest.owncloud.works/
2. create a file with a very long name like "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti.txt"
3. rename-pencil icon is cropped
- resource name is not left-aligned / jitters on resize

Jittering:
https://user-images.githubusercontent.com/26610733/184873974-1c433f90-43be-478e-b476-743acbbc34b1.mp4

### Expected behaviour

- rename icon should  not be cropped
- resource icon should be left-aligned / jitters

### Actual behaviour

- rename-pencil icon is cropped
- resource name is not left-aligned / jitters on resize

**Comment by tbsbdr** [comment]
cc @michaelstingl

**Comment by JammingBen** [comment]
This issue seems to be fixed meanwhile, either accidentally by us or by Safari.
