### ISSUE TITLE
Rename "New"-Menu Actions and use dedicated icons

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7463]
### Steps to reproduce
1. Click on "New"-Button

### Expected behaviour
Shows list of filetypes, which can be created.

### Actual behaviour
List is shown but names are not consitent and mixed between filetypes and office programs names ("Text-File" vs "MS Word")

![grafik](https://user-images.githubusercontent.com/16665512/184881721-5d098f03-7f57-4515-aeab-26d3d0861734.png)

| Instead of | better use |
|-----------|------------|
| OpenDocument | Dokument (odt) |
| Microsoft Word | Dokument (docx) |
| OpenSpreadsheet | Kalkulationstabelle (ods) |
| Microsoft Excel | Kalkulationstabelle (xlsx) |
| Microsoft PowerPoint | Präsentation (pptx) |
| OpenPresentation | Präsentation (ods) |

Also, the re-used icons are confisung. "Blue w", "green X" and "orange P" icons are meant to be used in MS context. OD* should use own icons, otherwise the purpose of icons to quickly find the desired menu entry is not given.

**Comment by JammingBen** [comment]
Kind of related: https://github.com/owncloud/web/issues/7076

**Comment by tbsbdr** [comment]
Quick thought: I'd prefer to have different Icons as first step for better differentiation

**Comment by kulmann** [comment]
> Quick thought: I'd prefer to have different Icons as first step for better differentiation

We show the icon based on the file extension, so that is easy. Just needs additional icons and respective mapping in the design system.

**Comment by kulmann** [comment]
We've added the file extension as additional information to the `+ New` menu items. Should be sufficient for now.
<img width="295" alt="Screenshot 2024-06-04 at 09 31 49" src="https://github.com/owncloud/web/assets/3532843/592e0f6e-3f10-4130-b7fd-94662fbb8fb9">
