### ISSUE TITLE
Contextmenu Breadcrumb: Shortcut-Hints should be right-aligned

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7493]
### Steps to reproduce
1. Create a folder
2. enter folder
3. click on 3-dots in breadcrumb-context menu
4. shortcut-Hints are not right aligned

<img width="711" alt="Screenshot 000294@2x" src="https://user-images.githubusercontent.com/26610733/185735196-a7591161-92d2-4a10-a5bd-11e01d21d8ba.png">

### Expected behaviour

- Shortcut-Hints should be right-aligned

### Actual behaviour

- shortcut-Hints are not right aligned

## Note on prio
adding this issue to GA-Blockes as its very likely that this issue will gets visible almost instantly to users (though its only visual - not functional)

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/owncloud-design-system/pull/2296. Needs an ODS update to be visible in Web though.
