### ISSUE TITLE
[Firefox only] Drag and Drop: move of folders not possible

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7495]
### Steps to reproduce
1. Browser: Firefox
2. Create 2 folders, next to each other
3. move one folder into another via drag and drop
4. on drop, user navigates into target folder and no move was executed

https://user-images.githubusercontent.com/26610733/185736083-138b05c3-2667-407f-9b1d-62c93930bc08.mp4

### Expected behaviour
- one folder should be moved into another via drag and drop.

### Actual behaviour
on drop, user navigates into target folder and no move was executed

**Comment by lookacat** [comment]
its because we drag&drop an a href, if you drag&drop the row its fine
