### ISSUE TITLE
Sidebar content floats out of the screen

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7498]
### Steps to reproduce
1. Open sidebar in file list

### Expected behaviour
The Sidebar should always fully display all elements despite of the screen size.

### Actual behaviour
Sidebar exceeds right window border on different windows widths
see red box in the bottom right corner in the video for dimensions when it happens

https://user-images.githubusercontent.com/16665512/185870242-68c83d81-b7c9-46bf-a0e6-6b91b86187bd.mp4

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

**Comment by JammingBen** [comment]
Ahh okay, it happens when selecting German as language, because the words are generally longer. No problem in English though. Thx for noticing!

I adjusted the title and the expected behavior a bit as the sidebar is supposed to have a fixed width and shouldn't resize.

**Comment by tbsbdr** [comment]
Proposal:

**Some space left** --> show Icons only

![](https://user-images.githubusercontent.com/26610733/185883052-ad781f18-71aa-4002-aca9-f803bb535de6.png)

**Almost no space left** --> move quickactions to 3-dots menu
