### ISSUE TITLE
features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:147 fails in master

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#7499]
We have a failing acceptance test in master, namely `features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:147`, see e.g. drone run https://drone.owncloud.com/owncloud/web/27701/35/20
As that has to do with link expiry alteration and it appeared in master on Saturday (I think) I suspect some date picker selection issue.
I will skip the test for now in a separat PR, because it blocks engineering work. Please decide whether the test is too unstable and should be removed entirely or if it should be fixed. @individual-it @phil-davis Would be good to get your helping hands here. 😇

**Comment by individual-it** [comment]
added to our fast-lane

**Comment by phil-davis** [comment]
Also see #7320 - it seems that this has been "a bit" intermittent recently.
Is it now a hard-fail?

**Comment by kulmann** [comment]
> Also see #7320 - it seems that this has been "a bit" intermittent recently.
> Is it now a hard-fail?

I quickly checked some recent CI runs and saw it failing in all the ones I checked. But could also be a coincidence... 🤔 Can't tell if it's failing every time or if it's only "very flaky" 😅

**Comment by individual-it** [comment]
closing in favor of https://github.com/owncloud/web/issues/7320
