### ISSUE TITLE
Scroller scrolls up automatically while trying to select an expiry date for public link

### ISSUE THREAD

**Issue by sushmita56** [owncloud/web#7513]
### Steps to reproduce
1. First of all reduce the screen resolution 
2. Log in to the WebUI and create a resource
3. Then, create a public link for the resource
4. And click on the public link edit button and then click on the `Add expiration date` option
5. Leave year and month as it is and now try to set the expiration date to the very last date of the month like 28/29/30/31

To select the last date of the month you'll have to scroll down. Whenever you scroll down and are about to click on the date, `say 30`, the scroller scrolls up automatically. 

Discovered such behavior while working on the issue: https://github.com/owncloud/web/issues/7320

### Actual behaviour
The scroller moves up instantly as we hover over the date.

### Expected behaviour
Unless we select the date the scroller was not assumed to shift upward.

### Screenshots

https://user-images.githubusercontent.com/66173400/186376131-e49668a2-09f8-4c03-b1f5-614f37a7a03f.mp4

### Environment general
**Operating system**: Ubuntu

**Backend (ownCloud Core or Infinite Scale)**: Core

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

**Comment by JammingBen** [comment]
Phew, at a first glance, the `v-calendar` lib which is used here does not provide any options to prevent this from happening. One easy solution would be to place the calendar always at the top. What do you think @tbsbdr ?

![image](https://user-images.githubusercontent.com/50302941/186412135-abf4595c-228b-44dc-a7b3-74be00595808.png)

**Comment by SwikritiT** [comment]
unskip this test in oc10 after this issue is fixed https://github.com/owncloud/web/pull/7645/files#diff-8f1afe20f5e88baf2ebfbef0ad7d5870137b6eebb5ea62edc0fa541a077152e0

**Comment by grgprarup** [comment]
Tests failed on nightly https://drone.owncloud.com/owncloud/web/32014/36/18, https://drone.owncloud.com/owncloud/web/32014/67/13, and PRs due to this issue.
Unskip the test https://github.com/owncloud/web/pull/8301/files#:~:text=in%20the%20server-,%40skip,-Write after this issue is fixed.

**Comment by SwikritiT** [comment]
This test failure is also because of this issue https://github.com/owncloud/web/issues/8902

**Comment by SwikritiT** [comment]
Unskip the test skipped in https://github.com/owncloud/web/pull/8905 after this bug is fixed
