### ISSUE TITLE
Space quota does not update reactively

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#7521]
### Steps to reproduce
1. Create a space and open the sidebar for it
2. Update the space quota

### Expected behaviour
The space quota in the sidebar should update reactively.

### Actual behaviour
The space quota remains the same until the page is reloaded.

This happens because the quota gets updated for all globally loaded spaces, but not for spaces loaded in the file store.

**Comment by JanAckermann** [comment]
This seems also to affect the space image now
