### ISSUE TITLE
Paddings inconsistent on various menus

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#7525]
Padding sizes are inconsistent for highlighted elements in the nav bar, the roles drop, the user menu and the apps menu

![Screenshot from 2022-08-25 11-09-45](https://user-images.githubusercontent.com/7430156/186631099-03be2c90-5641-495a-a4f8-35ecb2de949e.png)

![Screenshot from 2022-08-25 11-05-19](https://user-images.githubusercontent.com/7430156/186631110-26c854bd-2aa5-4b83-bcfa-c26566827bc9.png)

![Screenshot from 2022-08-25 11-05-58](https://user-images.githubusercontent.com/7430156/186633884-42a2e8e3-9cd2-4316-b250-eaba6c3ac104.png)

**Comment by diocas** [comment]
Sorry for piggy backing on this "padding issue" (maybe we can rename it to something more generic), but here are a couple more issues:

* Breadcrumb is not vertically centered (maybe the chevrons could be smaller?)
  <img width="242" alt="Screenshot 2022-08-26 at 15 27 18" src="https://user-images.githubusercontent.com/2589871/186914245-80fcad15-cdc5-41d1-817b-bb05e9fe2822.png">
* Space between batch action buttons could be smaller?
* The config menu inside the files app is not very consistent with the others (the new ones have a bit more padding/spacing)
  <img width="235" alt="Screenshot 2022-08-26 at 15 28 30" src="https://user-images.githubusercontent.com/2589871/186914476-189e1e4c-3191-4569-b993-bbba7bce6fa8.png">
* Small detail, but if we reduced the collapse button on the left sidebar, then the "all files" button would vertically align with the "new" and "upload" buttons which would be nicer (although it looks like they don't have the exact same height)
  <img width="465" alt="Screenshot 2022-08-26 at 15 29 35" src="https://user-images.githubusercontent.com/2589871/186914703-941a06c0-6874-487a-9f07-c683e3666438.png">

**Comment by JammingBen** [comment]
Closing here because the paddings have been aligned meanwhile. We didn't change anything in the account- and the share-role-dropdown though. Increasing the padding for items that have some additional info in a separate line would make the items differ in height, resulting in an even more uneven view IMO.

**Comment by diocas** [comment]
There were no suggestions of increasing the padding. Most of the elements have been fixed, but not all.

The inconsistencies that are still present:
* too much top/bottom padding on first/last button in dropdowns, in comparison with sides (applies to both roles dropdown in the sharing pane and the account dropdown)
    * this happens because every button has top + bottom padding, which should not happen in :first-* (top) and :last-* (bottom)
* In the account dropdown, the button with Username + email doesn't have a consistent spacing between the lines. This has been fixed and look very well in the roles menu (where it has the role name and description)

I still think this should be fixed (and it doesn't seem very hard), but I leave to your consideration.

**Comment by JammingBen** [comment]
> too much top/bottom padding on first/last button in dropdowns, in comparison with sides (applies to both roles dropdown in the sharing pane and the account dropdown)

Ahh okay, didn't get that initially. But you're right, there is an inconsistency.

> In the account dropdown, the button with Username + email doesn't have a consistent spacing between the lines. This has been fixed and look very well in the roles menu (where it has the role name and description)

Not 100% sure here, you mean like this (basically decreasing the spacing between the username and the email)?

<img width="289" alt="image" src="https://user-images.githubusercontent.com/50302941/232795079-4ab3b13a-0a9e-4da7-a32e-4c77de8e467a.png">

**Comment by diocas** [comment]
> Not 100% sure here, you mean like this (basically decreasing the spacing between the username and the email)?

Yup
