### ISSUE TITLE
OCIS Permissions - Failed to edit user

### ISSUE THREAD

**Issue by T0mWz** [owncloud/web#7533]
When I have a user without an email address and you try to assign a role or a quota, you get a message `Failed to edit user`. Maybe an extra hint that a valid emailaddress is required can be useful, now I discover the issue by checking the browser console.

### Steps to reproduce
1. Add a user without an email address
2. Try to assign a role or some  quota

### Expected behaviour
Littlebit more information why it is valid. 😉 

### Actual behaviour

![Screenshot 2022-08-26 at 15 52 19](https://user-images.githubusercontent.com/2477797/186919196-0f93ceae-aeb0-41f6-97ea-73b90a92b11b.png)

```
{"error":{"code":"invalidRequest","innererror":{"date":"2022-08-26T13:38:52Z","request-id":"25f743a2-9467-4e8d-9f84-0cde080387de"},"message":"' ' is not a valid email address"}}
```

### Environment general
 * IdP: KeyCloak 
 * user storage; LDAP

### Environment ownCloud OCIS
 * ownCloud Web UI 5.7.0-rc.10 
 * Infinite Scale 2.0.0-beta.7 Community

**Comment by JanAckermann** [comment]
PR https://github.com/owncloud/web/pull/7538
will take care that only the respective endpoints will be called if changes happen for either user base data, quota, or role.
Anyways, we don't want to allow changes to the user base data (displayName, mail, password) if an external IDP is involved, therefore we plan to make those fields read-only

**Comment by T0mWz** [comment]
Maybe nice if a link can be configured / shown here , that a user know where this information can be adjusted.

**Comment by JanAckermann** [comment]
good idea, 
FYI @tbsbdr @kulmann
