### ISSUE TITLE
Propose error-avoiding filename on new file creation

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7539]
### Steps to reproduce
1. Click on button New -> text file
2. Do not alter proposed filename ("New file.txt")
3. Hit "Create"
4. Click again on button New -> text file

### Expected behaviour
The current behaviour is not wrong but the user experience could be improved if the proposed filename would be "New file(2).txt" thus avoiding displaying an error.

### Actual behaviour
Error message shows "New file.txt already exists"

![grafik](https://user-images.githubusercontent.com/16665512/187188679-24f179cf-6595-4566-b4cd-a12f36e7d699.png)

### Environment general
**Operating system**: https://ocis.ocis-wopi.latest.owncloud.works

**Comment by kulmann** [comment]
Good idea! We have the same logic anyway when the user chose "keep both" in a copy/move conflict situation. Could be reused here.

**Comment by JanAckermann** [comment]
Fair enough, good catch!
