### ISSUE TITLE
(Firefox) Switch button element not aligned correctly

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7542]
Off state: ![grafik](https://user-images.githubusercontent.com/16665512/187192597-d3cb15d6-4be8-47d2-a82e-33543d9006aa.png)

On state: ![grafik](https://user-images.githubusercontent.com/16665512/187192419-a6fcb0a8-55d8-435d-8c87-243508c15d44.png)

Notice the slightly bigger space between the white circle in the middle and left / right border

```
.oc-switch-btn[aria-checked="true"]::before {
  left: 1px;
  transform: translateX(calc(100% + 1px));
}
```

could be extended with
```
@supports (-moz-appearance:none) {
  .oc-switch-btn[aria-checked="true"]::before {
    left: 1px;
    transform: translateX(calc(100% + 4px));
  }
}
```

### Result
![grafik](https://user-images.githubusercontent.com/16665512/187194164-4ff45b91-691e-430a-b9cb-56d668c0e627.png)

**Comment by rajdeepdas2000** [comment]
Can I work on this issue?

**Comment by kulmann** [comment]
Yes, of course, thank you! 😇 Please note that the component lives in https://github.com/owncloud/owncloud-design-system - if you make a PR and we have it merged we'll create a release of the design system and update it in web afterwards.
