### ISSUE TITLE
Information about new access tokens shown in console

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7543]
### Steps to reproduce
1. login
2. wait
3. check console (show debug messages)

### Actual behaviour
Console shows access token
<img width="1496" alt="grafik" src="https://user-images.githubusercontent.com/16665512/187194906-81f2b7a6-44d6-4f5f-825e-9a0b071e009c.png">

**Comment by hurradieweltgehtunter** [comment]
Also on login:
![grafik](https://user-images.githubusercontent.com/16665512/187195923-077ca3f2-d43a-4837-ba2b-bfaf56903eec.png)

**Comment by kulmann** [comment]
That's only `debug` log. By default `debug` log is not shown in the browser console.
What's the expected behaviour for you?

**Comment by hurradieweltgehtunter** [comment]
I didn`t expect this information at all but if it's intended, it's ok for me
