### ISSUE TITLE
[QA] add ability to run the full webUI CI without stopping early

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#7547]
The whole build pipelines get stopped when an early fail occurs in `e2e` test pipelines, even if the PRs have `full-ci` in them.

Implementation for acceptance is done here https://github.com/owncloud/web/pull/5184
Need to add for e2e pipelines so that if the PR title has `full-ci` in it then do not stop early - let all the pipelines run.

Related issues: https://github.com/owncloud/web/issues/5183, https://github.com/owncloud/ocis/issues/2107

Some builds which show the current behavior: https://drone.owncloud.com/owncloud/web/27900, https://drone.owncloud.com/owncloud/web/27899

CC @phil-davis @individual-it

**Comment by kiranparajuli589** [comment]
imo the stated feature is already there: https://github.com/owncloud/web/blob/12a449478cc66709a2f5150788104ca2c63f326c/.drone.star#L1334

**Comment by kiranparajuli589** [comment]
After viewing the provided build examples, the full-ci logic may be missing for the `e2e` pipelines.

**Comment by saw-jan** [comment]
I guess we only want to run acceptance if and only if the e2e tests pass that's why the acceptance is dependent on e2e (because eventually both try to test the same features).

But I don't really know the reasons, just my guesses.

CC @grgprarup @kiranparajuli589 @individual-it @phil-davis

**Comment by kiranparajuli589** [comment]
Acceptance tests waiting for e2e are not so nice in terms of resource consumption. The CI has to wait for about 5 minutes more for the acceptance tests.
If there aren't any other specific reasons behind it, then I feel the dependency should be fixed.

**Comment by ScharfViktor** [comment]
I agree with @kiranparajuli589. At first, when e2e was small and fast, it made sense. But now we have a lot of e2e tests and increasing coverage. Acceptance tests don't have to wait IMHO
