### ISSUE TITLE
Newly created OpenDocument file gets downloaded on creation

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7548]
### Steps to reproduce
1. Click on button "New"
2. Select Open Spreadsheed, Open Document or Open Presentation
3. Enter name
4. Hit Create

### Expected behaviour
File is created and gets opened in specific editor (like .md, word, excel and powerpoint files)

### Actual behaviour
File gets created and download starts

### Environment general
**Operating system**: https://ocis.ocis-wopi.latest.owncloud.works

Tested in Firefox, Chrome and Safari

**Comment by tbsbdr** [comment]
thanks @hurradieweltgehtunter 

@kulmann would say a GA Blocker, do you agree?

**Comment by JammingBen** [comment]
I can't reproduce this with any of the 3 browsers. Maybe there have been changes recently? @hurradieweltgehtunter does it still download for you?

**Comment by hurradieweltgehtunter** [comment]
yup, can confirm it doesn't happen any more. Collabora opens instead. I'm not sure if Collabora was available when I encoutered that issue. Maybe a problem if only OnlyOffice is installed? But thats just a wild guess ...

**Comment by kulmann** [comment]
It could be a misconfiguration of the app provider: if none of the apps that are configured are allowed (by config) to be the default app for the mimetype, then we fall back to the download. Web only respects the default application configuration of the app provider in this case.
However, I briefly looked into it yesterday on https://ocis.ocis-wopi.latest.owncloud.works/ and checked the `/app/list` response. That had Collabora specified as the default application for the mimetype corresponding to the `odt` file extension (`application/vnd.oasis.opendocument.text`). For me that still triggered a download, like @hurradieweltgehtunter described. Weird that it's gone today...

**Comment by kulmann** [comment]
> yup, can confirm it doesn't happen any more. Collabora opens instead. I'm not sure if Collabora was available when I encoutered that issue. Maybe a problem if only OnlyOffice is installed? But thats just a wild guess ...

The thing is, the respective entries in the `New` file menu only exist if Collabora **is** available. For me it was available yesterday.

**Comment by kulmann** [comment]
Not reproducible. Please re-open if this re-appears.
