### ISSUE TITLE
Translations: Default language differs per browser

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7549]
### Steps to reproduce
1. Load login screen

### Expected behaviour
Login screen is displayed in the same laguage in every browser (as long as no browser specific language is set)

#### Firefox
![grafik](https://user-images.githubusercontent.com/16665512/187397994-c7da8a68-4cdd-45e5-aba6-7966ac4276ac.png)

Browser language setting:
![grafik](https://user-images.githubusercontent.com/16665512/187398291-ac332ddb-90f4-413d-863c-fd8f67784b7a.png)
No alternate nor any "prefferd language for websites" is set

#### Safari
![grafik](https://user-images.githubusercontent.com/16665512/187398059-c1669360-3dff-4f23-bde6-d4675dd8dba2.png)

#### Chrome
<img width="444" alt="grafik" src="https://user-images.githubusercontent.com/16665512/187398098-3f3e3347-7ecc-4c75-a905-9c41264eb680.png">

Language system setting:
![grafik](https://user-images.githubusercontent.com/16665512/187398842-85f2e4d7-0315-477f-a208-f78466f28248.png)

Note: It affects not only the login screen but the entire frontend. Login screen is only used in this issue as an example.

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works/
MacOS 12.4

**Comment by hurradieweltgehtunter** [comment]
BTW: After login the next screen "You are redirected" is shown in english for a split second, then it switches to german. 
In Safari, Chrome this is shown directly in german.

**Comment by hurradieweltgehtunter** [comment]
Check this:
After logging in with Safari or Chrome it still appears in german **although** the language is set to "english"

<img width="838" alt="grafik" src="https://user-images.githubusercontent.com/16665512/187404220-130502bb-1b00-4e44-a46c-1aa84ceb271e.png">

With Firefox it stays in english - which is correct.

**Comment by kulmann** [comment]
The settings UI doesn't behave correctly. If no language has been set before it still shows `English` as default in the UI. In reality ownCloud Web still uses your browser language as fallback, although the settings UI suggests otherwise.

**Comment by hurradieweltgehtunter** [comment]
> The settings UI doesn't behave correctly. If no language has been set before it still shows `English` as default in the UI. In reality ownCloud Web still uses your browser language as fallback, although the settings UI suggests otherwise.

Ok but loggin in with the same user presents the frontend in english in Firefox and german in Safari
