### ISSUE TITLE
Shared with me: Bad discoverability

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7551]
### Steps to reproduce

1.  Albert is looking for the folder `Video Archive 2017` which was shared with him by Marie, but he can't find the file in his Windows Explorer
2.  Albert opens `Shares` -> `Shared with me` and sees:

![Screenshot 000356@2x](https://user-images.githubusercontent.com/26610733/187401976-44f8284a-fdf3-4898-aadb-30d29178f338.png)

1.  Albert is overwhelmed by the 3 sections `Pending shares`, `Accepted shares` and `Declined shares` and does not understand what `accept` and `decline` mean.
2.  Albert finally finds the file `Video Archive 2017` within "Pending shares" but cant open it

### Expected behaviour

*   **1 List:** Show only 1 single list as Albert expects this from other views
*   **Replace `Pending`, `Accept` and `Decline`:** Don't talk about pending, accepted or declined shares but just show all visible shares in the list
*   **Action `Hide share` / `Unhide share`**  Add option to hide shares so that irrelevant shares can get hidden; Hidden shares are not shown in the initial list.
*   **Just open all files**: All files can get opened regardless if they are hidden or not
*   **Option `Show hidden shares`:** Shows only hidden shares in "Shared with me"
*   **Grouping:** is currently a custom feature at CERN - proposal how it could be aligned with the Chip-style

<table><tbody><tr><td><strong>Status</strong></td><td><strong>Currently</strong></td><td><strong>Proposal oCIS</strong></td><td><strong>Proposal oc10</strong></td><td><strong>Desktop Client</strong></td></tr><tr><td>Pending share</td><td>"Pending shares"</td><td>"Shared with me" (like auto-accept)</td><td>Legacy - use classic UI*</td><td>Synced (default: VFS; fallback: selective sync)</td></tr><tr><td>Accepted share</td><td>"Accepted shares"</td><td>"Shared with me"</td><td>"Shared with me"</td><td>Synced (default: VFS; fallback: selective sync)</td></tr><tr><td>Declined share</td><td>"Declined shares"</td><td>"Show hidden shares"</td><td>"Show hidden shares"</td><td>not synced</td></tr></tbody></table>

\* if "Automatically accept new incoming local user shares" is disabled, click on "Shared" (=sharing jail) navigates to "shared with me" in the classic ui

#### Initial view:

![](https://user-images.githubusercontent.com/26610733/188576174-54072b98-c7f3-4560-88c2-63fb6e848a3a.png)

#### Hidden shares:

![](https://user-images.githubusercontent.com/26610733/188577754-d50f17b5-97be-4101-a873-46959d577992.png)

### Actual behaviour

*   Concept of Pending / Accepting / Declining shares is hard to understand
*   3 sections `Pending shares`, `Accepted shares` and `Declined shares`
*   unaccepted shares can't get viewed

\--  
Issue was first brought up / related: #7435 and was also reported by @elizavetaRa , @diocas - created a new issue to make it actionable.

**Comment by tbsbdr** [comment]
update:

Discussed today with @hodyroff @kulmann @pmaier1 and others - there where no objections against removing the pending status in ocis. wording for the former "decline" action needs more research.

**Comment by tbsbdr** [comment]
It could be right to have "hide" in the quickactions but tbh I'm not sure if "hide" is amongst the ~ top 5 and most often used actions and thus should take a front seat in the quickactions (It is for your users as you say - but from a product perspective I'm currently 50/50 ). I'd like to decide this as soon as I got enough feedback on the new concept.

**Comment by diocas** [comment]
Since you have 0 other quick actions in this list, having 1 automatically makes it to the top 5 :)
It's more for discoverability, I believe users would benefit from knowing that the option exists.
just my 2cents

**Comment by tbsbdr** [comment]
relates to https://github.com/owncloud/web/pull/9159/commits/11ad6f411858cf00dff427c6c0e3952b3c05a66e

**Comment by tbsbdr** [comment]
Cern: Hide ~ reject share

**Comment by tbsbdr** [comment]
Question to @elizavetaRa 
what happens, if you receive a share ex. 10GB - does the desktop client then sync the 10GB immediately?

**Comment by elizavetaRa** [comment]
Here as in our mockups: there should be s "sync" button for each share, default of the share is not synced. The size is shown, so it's up to user to sync or not

**Comment by tbsbdr** [comment]
closing in favour of more actionable ticket
Duplicate of https://github.com/owncloud/web/issues/9531
