### ISSUE TITLE
Login form design improvement

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7552]
### Steps to reproduce
1. Loadup login screen

### Actual behaviour
![grafik](https://user-images.githubusercontent.com/16665512/187406138-8261549e-4747-49d3-a55a-788d6e52bec9.png)

Design and, thus, readability could be improved.
- Use bright fill for input fields to enhance contrast to dark bg
- Use dark text color for input fields to enhance contrast to bright input bg
- Remove white border hover effect on button (we don't use any hover effect on buttons) to stay in CI
- Use default primary background (gradient) for login button to stay in CI
```
background: linear-gradient(to right, #2c588e, #4e85c8);
background-size: 103%;
background-position: -1px;
```
- Remove space above button: there is a `<br>` above the button which extends the space unnecessarily. AFAIK it serves no purpose. 
<img width="261" alt="grafik" src="https://user-images.githubusercontent.com/16665512/187409633-0813da0d-c3a0-496a-b03a-a9d0a44d5f78.png">
- Widen button to form/input fields width (100% or 300px)
- Use default border radius (5px) for input fields and button 

### Updated oCIS login screen
![grafik](https://user-images.githubusercontent.com/16665512/187415373-61ead23e-1d38-4904-9255-aa382d539fea.png)

## OC10
Have a look at the OC10 login screen:
![grafik](https://user-images.githubusercontent.com/16665512/187409061-76d7467d-70c3-47b9-a1f2-6b65440c7c83.png)

When we updated it some time ago we considered best practices for login screens. I'd suggest to use this result instead of reinvent the wheel.

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

**Comment by kulmann** [comment]
Note: this needs to be implemented in https://github.com/owncloud/ocis as the code of the `idp` service (including the frontend) lives there. Still fine to track it here.

**Comment by kulmann** [comment]
I'd prefer a gray-ish text color for the (muted) placeholder text in the form fields, like it is in oc10 as well. What do you think?

**Comment by hurradieweltgehtunter** [comment]
Maybe this leads too far but using a label and a placeholder to show the same information is a duplicate without additional purpose. If a label is present a good best practice might be to use the placeholder to show an example value like 'john@example.com'

**Comment by JammingBen** [comment]
Okay for now as stated here: https://github.com/owncloud/ocis/pull/4500#issuecomment-1235575435
