### ISSUE TITLE
Groups displayed as UUID on the Account page

### ISSUE THREAD

**Issue by rhafer** [owncloud/web#7554]
This is bascially for the web part of https://github.com/owncloud/ocis/issues/4283

## Describe the bug

![image](https://user-images.githubusercontent.com/3391958/180962666-80cbe71c-0f50-430c-b16d-31b120b397ee.png)

## Expected behavior

Value from the attribute set by `LDAP_GROUP_SCHEMA_DISPLAYNAME` should be used instead. The default should be `cn` already but even it if the env var is explicitly set to `cn` the ID is displayed.

## Setup

Container (owncloud/ocis:2.0.0-beta.5) + External OpenLDAP

**Comment by rhafer** [comment]
@kulmann with https://github.com/owncloud/ocis/pull/4476 the graph API will support `/me/?$expand=memberOf`, now web "just" needs to use that on the Account page. (AFAIK currently it's still using an 'ocs' query.

**Comment by kulmann** [comment]
Needs a capability so that I know when to request the groups via graph or via ocs. ;-) Are there any plans on some kind of a graph capability?

**Comment by kulmann** [comment]
Ticket for graph capability in ocis: https://github.com/owncloud/ocis/issues/4481

**Comment by JanAckermann** [comment]
Note, we currently use `capabilities.spaces.enabled`
in packages/web-runtime/src/services/auth/userManager.ts:165

**Comment by kulmann** [comment]
I'd be fine with using that until we have the graph capability. 👍
