### ISSUE TITLE
  [Technical] Search - collector ticket

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/web#7557]
### 1. href in REPORT doesn't match the href in PROPFIND
href in PROPFIND looks like this: 
`/remote.php/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$6dafb452-139d-4372-8772-14f23208dd6a/DHL-Paketmarke_4Y2QQDG37C58_1_Kristjan_Slokar.pdf`

while href in REPORT looks like this:
`/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157%216dafb452-139d-4372-8772-14f23208dd6a/DHL-Paketmarke_4Y2QQDG37C58_1_Kristjan_Slokar.pdf`

remote.php as prefix is missing and encoding differs

Reason for issue: 
https://github.com/owncloud/web/issues/7456
https://github.com/owncloud/web/issues/7391

### 2. name and shareId missing in REPORT on a received share 

It is necessary to retrieve the name and the shareId of a received share in order to display it correctly in the search list

currently not provided:
```
<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668%21fbcff0b5-21cc-4a75-884c-1d9af94ababa</d:href><d:propstat><d:prop><oc:fileid>1284d238-aa92-42ce-bdc4-0b0000009157!a04b9481-a928-43ed-bac3-be60ee809b28</oc:fileid><d:getetag></d:getetag><d:getlastmodified>2022-08-31T08:49:18Z</d:getlastmodified><d:getcontenttype>httpd/unix-directory</d:getcontenttype><d:resourcetype><d:collection/></d:resourcetype><oc:size>0</oc:size><oc:score>3.861326217651367</oc:score></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668%21fbcff0b5-21cc-4a75-884c-1d9af94ababa/demo.txt</d:href><d:propstat><d:prop><oc:fileid>1284d238-aa92-42ce-bdc4-0b0000009157!c334a1c0-6986-467e-b72c-17b5a1daec01</oc:fileid><d:getetag></d:getetag><d:getlastmodified>2022-08-31T08:49:23Z</d:getlastmodified><d:getcontenttype>text/plain</d:getcontenttype><d:resourcetype></d:resourcetype><d:getcontentlength>0</d:getcontentlength><oc:score>3.861326217651367</oc:score></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
```

Reason for issue:
https://github.com/owncloud/web/issues/7391

### 3. permissions missing in REPORT but is available in PROPFIND
oc:permissions is missing entirely in report

**Comment by kobergj** [comment]
https://github.com/owncloud/ocis/pull/4485

should fix most of the issues. Still permissions are empty and etag too. Not sure if that is relevant for this issue.

**Comment by JanAckermann** [comment]
Permissions are required to determine if the resource is a received share (which seems to be only true on root level), would be a good thing to have it.
