### ISSUE TITLE
Proposal: Let users decide which columns to display

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7565]
Check Mac's finder columns settings:
<img width="193" alt="grafik" src="https://user-images.githubusercontent.com/16665512/187795454-e68ebef2-c41f-4bb6-a0ce-c468a19f8bb3.png">

This could get in handy for users to customize their file list.

**Comment by kulmann** [comment]
Closing in favour of https://github.com/owncloud/web/issues/6141 (same idea). Could you add your issue description+image as comment in the other issue as additional details?
