### ISSUE TITLE
Reintroduce ClickOutside directive

### ISSUE THREAD

**Issue by lookacat** [owncloud/web#7572]
We noticed the clickOutside.js directive accidentally got removed from the right sidebar.  

### Expected behaviour
Right sidebar gets closed on click outside (e.g. files-table)

### Actual behaviour
Nothing happens

**Comment by tbsbdr** [comment]
hey @lookacat I doubt that this is expected behaviour. Have you seen this behaviour (right sidebar closes on outside-click) in any other browser-based fileexplorer so that I could have a look?

**Comment by kulmann** [comment]
I'm also fine not having it at all. but then I'd like to get rid of the dead code.
