### ISSUE TITLE
Shared with a group and a member of this group resource appears as 2 shares in "Shared with me"

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#7582]
### Steps to reproduce
1. Share resource with a group
2. Share resource with user who is group member
3. As sharee go to "Shared with me" section

### Expected behaviour
Share appears as one, share indicators show user and group

### Actual behaviour
Share appears as 2 shares
![Screenshot from 2022-09-01 18-43-31](https://user-images.githubusercontent.com/7430156/188393791-1db88695-f50f-4c0c-9c4c-5cee31f07f01.png)

**Comment by elizavetaRa** [comment]
@kulmann

**Comment by elizavetaRa** [comment]
@kulmann Found the problem. The backend request in` packages/web-app-files/src/services/folder/loaderSharedWithMe.ts `returns shares in random order. Whenever the group share and user of this group share are next to each other, they get merged into one in `addSharedWithToShares`. But when not, it doesn't happen. Is the returned shares list supposed to be sorted by name in the backend? Then it would be a backend bug, otherwise needs sorting before `addSharedWithToShares`

**Comment by kulmann** [comment]
> @kulmann Found the problem. The backend request in`packages/web-app-files/src/services/folder/loaderSharedWithMe.ts`returns shares in random order. Whenever the group share and user of this group share are next to each other, they get merged into one in `addSharedWithToShares`. But when not, it doesn't happen. Is the returned shares list supposed to be sorted by path in the backend? Then it would be a backend bug, otherwise needs sorting before `addSharedWithToShares`

Good that you found it, thank you for digging into it 💪 The backend is not supposed to sort anything at the moment. We're still at `sorting only happens in the client`.

**Comment by elizavetaRa** [comment]
@kulmann  we have a fix for it, do you want a pr? https://github.com/cernbox/web/commit/cb6d25a649907a69be3b85cbe381782bbd350433

**Comment by kulmann** [comment]
> @kulmann we have a fix for it, do you want a pr? [cernbox@cb6d25a](https://github.com/cernbox/web/commit/cb6d25a649907a69be3b85cbe381782bbd350433)

PR would be awesome, thank you!
