### ISSUE TITLE
Tags: Inconsistent save mechanism / Buttons disappear

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7585]
### Steps to reproduce
1. Right click on file -> Add or edit tags
2. Enter new tag/Delete tag

### Expected behaviour
As used from all other actions my changes get saved immediately

### Actual behaviour
At the bottom of the right sidebar two buttons appear. I have to click on "Save" to save my changes. This buttons are not only easy to oversee but i was also very surprised that this action must be saved manually.

![grafik](https://user-images.githubusercontent.com/16665512/188456992-8594c14f-5f15-48c6-8ef0-fec1cce26d29.png)

Also, the right sidebar is not adapting correctly to window width, making the buttons disappear on specific window widths:

https://user-images.githubusercontent.com/16665512/188458237-4518812b-19bf-4990-aacd-88eb59ff52fa.mov

**Comment by JanAckermann** [comment]
@tbsbdr can you give feedback on that?

**Comment by tbsbdr** [comment]
agree, the "click outside" is expected to perform a "save" especially for not-so-critical operations like tagging - I also observed what @hurradieweltgehtunter describes.

Generally having a save button is important for touch and inexperienced users "is it saved now?". "Unsaved changes" and "Revert" provides visibility of system status, user control and the ability to recover from a mistake.

*   Improvement 1: Add click outside = same as click "Save"
    *   con: might be erroneous for this patten in the usermanagement
    *   pro: best efficiency / most appropriate for tagging-form
*   Improvement 2: Position Save-dialog to bottom of the respective form, but still floating on bottom of the left sidebar if vertical size of the form gets bigger than the right sidebar (-> Save-dialog is always visible)
    *   con: looks currently not so appealing, needs some beautification
    *   pro: respects unexperienced users

@JanAckermann lets discuss if we do 1 or 2 or 1+2.

\--

### Appendix

Problem with missing save buttons for critical actions

**Comment by tbsbdr** [comment]
@JanAckermann as discussed: lets start with improvement Nr 2 and then check if its sufficient.

*    [ ]  place save-bar below form

![](https://user-images.githubusercontent.com/26610733/188894296-ef06329f-ad61-4ccc-b280-c43e4093298e.png)

**Comment by hurradieweltgehtunter** [comment]
For me it was very surprising to suddenly have a save button 🤷 
I'd prefer to get rid of it in this context

**Comment by hurradieweltgehtunter** [comment]
as lon it is intuitive and consistent it's ok for me. Just my 2 cents :)
