### ISSUE TITLE
No context menu available on search result page

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7587]
### Steps to reproduce
1. Search for a file (filename, tag, whatever). Make sure search result page shows at least one result
2. Right click on file / Click on three dots menu "open context menu"

### Expected behaviour
Context menu opens

### Actual behaviour
Nothing happens.
Either hide three dots menu to not engange user to expect a context menu 

OR, way more convenient - 

make context menu available on search result page, too as the user is used from normal file list.

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

**Comment by JanAckermann** [comment]
Please note, after https://github.com/owncloud/web/pull/7586 has been merged, there will still not be all actions avaibale in the context menu. This happens, because we don't get any permissions via the DAV REPORT, will be fixed in the backend.

**Comment by kulmann** [comment]
> Please note, after #7586 has been merged, there will still not be all actions avaibale in the context menu. This happens, because we don't get any permissions via the DAV REPORT, will be fixed in the backend.

... but the default action (like opening in text-editor for a txt-file or navigating into the folder for a folder) and `Show details` are already back again.
