### ISSUE TITLE
Filename Layout (font weight and size)

### ISSUE THREAD

**Issue by hosy** [owncloud/web#7589]
In the current version I miss the filename layout in the Web UI, which was present some month ago. This filename layout was also adopted to the iOS app and in my opinion it make sense to have it in the web UI again, because it highlights the filename.

- Filename should have a bold font weight and a larger font size as the file extension
- File extension should have a normal font weight

The corresponding iOS PR can be found here:
https://github.com/owncloud/ios-app/pull/1001

@tbsbdr what do you think about?

**Comment by pascalwengerter** [comment]
Closing this as unwanted since it's been open for two years without any feedback. Feel free to reopen if applicable
