### ISSUE TITLE
Refine Searchbar & Searchpreview

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7591]
# Replaces current filter & search

![](https://user-images.githubusercontent.com/26610733/188623927-4130d562-589f-4d26-ae62-78558fa2380e.png)

# Initial state

![09_search@2x](https://user-images.githubusercontent.com/26610733/188617282-b1bd2b46-95f4-4738-b818-c30aac3b86d6.png)

# Focused (empty / cleared)

Shows most recent search terms of the user; most recent on top.

*   no "clear- `╳`"
*   no "enter- `→`"

![09_search@2x (1)](https://user-images.githubusercontent.com/26610733/188617291-60589a4a-185c-404d-8e26-dbba9b87f0e0.png)

# Searching

shows search spinner + text "Searching ..."

if text is entered:

*   show "clear- `╳`"
*   show Divider
*   show "enter- `→`"

![09_search@2x (2)](https://user-images.githubusercontent.com/26610733/188617294-b939e60e-31a5-4617-9d07-51c23d133364.png)

# No results found

![09_search@2x (3)](https://user-images.githubusercontent.com/26610733/188617297-32c681ae-29ce-4dd6-8328-d2fc12020b9b.png)

# Recent-Suggestions

*   Show 3 most recent **matching** suggestions
*   Show "Searching-Indicator" if system is searching

![09_search@2x (4)](https://user-images.githubusercontent.com/26610733/188617299-5958196e-328a-413f-af1e-370226e833a1.png)

# Show Quick results

*   Show 1-3 most recent `matching suggestions` 
*   Show 1-4 best matching `resource results`
*   ~Speed 🚀 up `resource results`: if the current folder contains matches (filter) those are shown first in the resource results (c.f. owncloud/web#7099)~
*   Show "Show all" option (same effect as \<enter> or `→` )

![09_search@2x (5)](https://user-images.githubusercontent.com/26610733/188617302-4704fd0b-d21e-4796-8922-590e68cb56d5.png)

# Select results 1

*   \<Arrow down/up> browses through the result list
*   If one of the "recent matching suggestions" is selected, the form text gets updated, but the Quickresults don't update! (why? user should be able to browse through a stable quickresult list)
*   \<enter> shows full search result page for the current searchterm

![09_search@2x (6)](https://user-images.githubusercontent.com/26610733/188617307-16468171-77f1-4945-aba7-517cb540b575.png)

# Select results 2

*   If a resource is selected, the standardaction is executed on \<enter>

![09_search@2x (7)](https://user-images.githubusercontent.com/26610733/188617312-09a133a0-c18f-4c19-bde7-8981bf16d006.png)

# Browsing ⬇️

![09_search@2x (8)](https://user-images.githubusercontent.com/26610733/188617314-0dc1a229-ccea-4768-b407-ba6c80e4affc.png)

# Browsing ⬇️

![09_search@2x (9)](https://user-images.githubusercontent.com/26610733/188617318-208112f0-b344-45be-b720-be7836a37896.png)

# Browsing ⬇️

![09_search@2x (10)](https://user-images.githubusercontent.com/26610733/188617321-f628f7e8-e4ed-47ed-a173-87bd3b200037.png)

# Show all

*   Show "Show all" option (same effect as \<enter> or `→` )

![09_search@2x (11)](https://user-images.githubusercontent.com/26610733/188617323-145f4556-a3cc-476b-bb0d-35047fa5f487.png)

**Comment by JanAckermann** [comment]
A little note according to the screenshots: We have a hard limit of 200 search results, even in the list. So "Show all 849 results" is technically not possible.

**Comment by JanAckermann** [comment]
Additionally: If this will omit the "Search in current folder" search provider, I would be more than happy. 
We can also think about increasing the max search result limit of 5 in the preview search, as I don't think this is reasonable

**Comment by kulmann** [comment]
> Additionally: If this will omit the "Search in current folder" search provider, I would be more than happy.
> We can also think about increasing the max search result limit of 5 in the preview search, as I don't think this is reasonable

Yes, the idea here is to completely get rid of the `filter` search provider. User testing showed that it is really hard to understand when to search and when to filter with the current approach, so we wanted to go back to "only searching". Filtering will probably come back at some point in the future, but closer to the file list.

**Comment by kulmann** [comment]
@tbsbdr just to be clear, a search term history in focused & empty state would need to be solved via localStorage at the moment. We don't have a way to store such information in the backend. For the `Recent-suggestions` we'd have the same limitation.

**Comment by tbsbdr** [comment]
> need to be solved via localStorage

totally fine - the recent suggestions is just nice-to have; I'm happy if we remove the current `search all files` and `search current folder` options and replace them with the behaviour described above.

**Comment by JanAckermann** [comment]
Thanks for clarification. @kulmann Would you like to decide which features we like to implement until GA?

**Comment by kulmann** [comment]
I think the following work packages make sense:

1. remove the `filter` search provider entirely, but keep ui layout as is (including the "Search all files" list item, because otherwise there'd already be a lot of changes needed regarding keyboard interaction with up/down arrows and enter)
2. adjust search bar and list below as described in the ticket, but without the search history
3. search history (x recent terms if input is empty / x prefix-matching recent terms upon typing)

Having 1+2 for GA would be awesome. 1. is the minimum requirement. What do you think? If you can come up with a more fine grained approach for 2. I'd be happy as well. ;-)

**Comment by JanAckermann** [comment]
Action items:
- [ ] Remove filter search provider 
- [ ] Add Searching text to loading spinner 
- [ ] Add 'Show all ... results link'

**Comment by kulmann** [comment]
> The only thing we need to have a look at, is that the backend might be able to handle the recent search results correctly. For me this means that the files in personal home will have a higher score than somewhere else.

Regarding relevance score, In general the REPORT request is supposed to carry a property `oc:search-score`. Not sure if that's already implemented in ocis (in oc10 we have it if the search backend is `search_elastic`). If that exists you could use it to sort by relevance.
See here for oc10 reference: https://github.com/owncloud/core/pull/38787


> Still don’t know what to do with the show 800 more results… As I mentioned before we have a hard limit of 200.

Just show `Show more results` instead for now.


> What’s about the search limit for the preview? 5 is IHMO a little to less

Let's play with that, I also think that something like 8-10 would be good. Just make sure that it's scrollable if we don't have sufficient viewport height.

**Comment by JanAckermann** [comment]
Thx for clarification, can we please think again about the x will return to the previous page? 

It is awful, if enter a search term and will be redirected to the search route, enter a new term and click x, you will be redirected to the previous search page. This feels pretty bad and confusing. 

@kulmann mentioned already that a redirect to “/“ would be sufficient and I like to agree

**Comment by kulmann** [comment]
> Thx for clarification, can we please think again about clicking the x will redirect to the previous page?
> 
> It is awful… if I enter a search term and will be redirected to the search route, enter a new term and click x, I will be redirected to the previous search page. This feels pretty bad and confusing.
> 
> @kulmann mentioned already that a redirect to “/“ would be sufficient and I like to agree

Yes, had the same impression, the UX on subsequent searches feels just wrong.
Another idea would be to use the `closeApp` function from the `useAppNavigation` composable that we're already using in apps like `web-app-preview`. As long as the origin route is provided in the URL (look for how we build the route query to editor apps in `filesACtions.ts#$_fileActions__routeOpts`) the `closeApp` function navigates you back to your origin. Must stay the initial origin on subsequent searches then.

**Comment by tbsbdr** [comment]
Update - added to initial post:

> Speed 🚀 up `resource results`: if the current folder contains matches (filter) those are shown first in the resource results (c.f. owncloud/web#7099)

search currently feels quite slow but speed is really crucial for acceptance of a search function. The item above is a suggestion so that we can serve an appetizer for our waiting visitor until the main course (real search results) is served. what do you think? @kulmann @JanAckermann

**Comment by tbsbdr** [comment]
@JanAckermann @kulmann as we talked about the future of search in Infinite Scale I'm droping here a draft so that we have a foundation for discussion. I'll schedule a meeting so that we can cherrypick and slice: 
![image](https://user-images.githubusercontent.com/26610733/189931419-934cc1ab-3d64-4792-b634-13c046dc437b.png)

**Comment by JanAckermann** [comment]
Good idea to add markjs (yellow text background)

**Comment by tbsbdr** [comment]
Jep, right

**Comment by JanAckermann** [comment]
You got an error here, the folder is called Nuremberg Trip and the location is Neumarkt. That is not acceptable!
