### ISSUE TITLE
No scrolling to just created folder

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#7600]
### Steps to reproduce
1. Create a new folder  in the repository with many folders and name it, so that it's name is outside of the view

### Expected behaviour
The view should scroll to the created folder

### Actual behaviour
- There is no scrolling
- Users get confused if the folder was actually created (from user feedback)
- Users need to scroll manually and search for the folder

**Comment by elizavetaRa** [comment]
Related to it: https://github.com/owncloud/web/issues/7601
Our proposal is to enable scrollToResource on creation of the folders and set scrolling to the middle of the view (gdrive like)
Our implementation of this proposal: https://github.com/cernbox/web/commit/460b98c1716d601bd4813b645addec9a53183a1e

**Comment by pascalwengerter** [comment]
@elizavetaRa could you turn this into a (simple) bugfix PR to the upstream owncloud/web repo? Ideally you can even get rid of the `filesListScrolling.js`-mixin and inline the necessary 1-2 lines of JS
