### ISSUE TITLE
ScrollToResource function not working as expected

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#7601]
### Steps to reproduce
1a. By selected resource scroll up outside of the view with this resource and press key "down"
1b. By selected resource scroll down outside of the view with this resource and press key "up"

### Expected behaviour
The called `scrollToResource` function shows the resource in the middle of the view

### Actual behaviour
By 1a the resource is shown in the last row of the visible list. By 1b nothing happens

**Comment by tbsbdr** [comment]
@elizavetaRa I'd expect it work like this - are we on the same page?

https://github.com/owncloud/web/assets/26610733/b054ed8e-fa57-4947-b24b-c9362d52588d

**Comment by elizavetaRa** [comment]
So, you would change the selected resource on key up/down to previous/next, yes, that sounds logically to me.
What would happen by multiple selection? Deselect all selected and jump to the next after last?

If I scroll outside the view with the selection, I'd expect to scroll to the selection on key up/down still. Maybe not put the selection to the middle as I initially proposed.

(example how it scrolles to the view with selection on key up)
![example](https://github.com/owncloud/web/assets/7430156/18f4b9c6-b572-40d0-b551-2089bc1b0270)

**Comment by tbsbdr** [comment]
> What would happen by multiple selection? Deselect all selected and jump to the next after last?

👍 Yes

> If I scroll outside the view with the selection, I'd expect to scroll to the selection on key up/down still. Maybe not put the selection to the middle as I initially proposed.

👍 Yes
