### ISSUE TITLE
Searching in public link takes you to the personal of the creator of the public link

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#7603]
### Steps to reproduce
1. As user `Alice` create folders `test`, `test/test-folder`, `test/test-test`
2. create a public link for folder `test`
3. navigate to the public link
4. In global search, search for `test`

### Expected behaviour
The search list should display the resources with `test` keyword in them

### Actual behaviour
the search list doesn't display the result of the search query but if I `search all files`  it navigates to the `Personal` of user `Alice` 

#### OCIS
https://user-images.githubusercontent.com/41103328/189056363-8edd6870-0038-4cb0-9dcf-380cce0e6f6a.mp4

#### OC10
https://user-images.githubusercontent.com/41103328/189056656-089499ce-a16b-4888-9b86-73f4cb8c167c.mp4

If I open the link in incognito mode the search bar is not displayed

Both ocis and oc10 are the latest master

**Comment by individual-it** [comment]
with the web in the current ocis the search does not show anything but throws errors
![image](https://user-images.githubusercontent.com/2425577/195329050-57552751-36c7-4d69-aca0-1d96a8f83cee.png)
