### ISSUE TITLE
Error messages behind grey modal shader (z-index issue), bad readability.

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7607]
### Steps to reproduce
1. Open some sort of modal, e.g. Create a new Space
2. Enter some value which results in an error
3. Hit "Create"

### Expected behaviour
Error message blatant visible

### Actual behaviour
Error message shows in the bottom right corner but is overlapped by grey fullscreen shader. Makes it hard to see.

![grafik](https://user-images.githubusercontent.com/16665512/189101610-8a6faffc-32fb-4a2b-8a6a-6cab8eaaa96e.png)

Increase z-index to place it "above" grey shader element

**Comment by JanAckermann** [comment]
Seems to be fixed already:
![image](https://user-images.githubusercontent.com/26169327/199903063-dd0a79d9-49e7-4bcd-8668-6146e055dd32.png)
