### ISSUE TITLE
Usermanagement Search is inconsistent / confusing

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7613]
### Steps to reproduce

1.  login as admin, goto usermgnt
2.  type "ma"
3.  list in background filters for "ma" ✅, preview offers option "Search users", but closes the preview on click of "search users" or \<enter>
4.  preview visually blocks user from the filtered resultlist 

![Screenshot 000481@2x](https://user-images.githubusercontent.com/26610733/189208569-dd23854f-45c1-4e2b-a10c-40d99246bfc2.png)

### Expected behaviour

Short term for GA:

*   search only searches for files or tags
*   add filter to filter userslist below "+ New user" button
*   search-provider selection is never shown (#7591)

Longterm (not part of this issue):

*   omnisearch: show results from all search providers in preview #5844

![](https://user-images.githubusercontent.com/26610733/189212213-71b1445e-8205-4e79-bb04-acda57588810.png)

### Actual behaviour

*   "Search users" closes the preview but does not search or alike
*   preview visually blocks user from the filtered resultlist

**Comment by tbsbdr** [comment]
@kulmann would you agree on the proposal?

after discussion with @JanAckermann this issue also aims to get rid of the searchprovider-selection especially when it comes to files search. thats why I would rate it as p2. I'd like to have a nice files-search

![](https://user-images.githubusercontent.com/26610733/188623927-4130d562-589f-4d26-ae62-78558fa2380e.png)

**Comment by JanAckermann** [comment]
@tbsbdr THX for the write down

**Comment by JanAckermann** [comment]
Implementation is here:
https://github.com/owncloud/web/pull/7599

![image](https://user-images.githubusercontent.com/26169327/189244792-27bb9a2e-2d14-406a-a570-e2f79a06dbb2.png)

@tbsbdr please let me know if you want to change the: 'Label', 'Default text', 'Description message'
documented here https://owncloud.design/#/oC%20Components/OcTextInput

**Comment by tbsbdr** [comment]
nice. and nice nightshift 😳

I'd prefer to have a reasonable fixed width of ex. 16 rem (224px). 

Why would I prefer a fixed width? We should make sure that the form has 1 ) a min-width - it shouldn't get too small and 2 ) a max-width because short filter-terms like "albert" make a faulty impression in too long forms. So let's just have it fixed.

'Label', 'Default text', 'Description message' fine as is 👍

![](https://user-images.githubusercontent.com/26610733/189286702-8e6e7daf-d376-4576-8995-02b8fca5c8f9.png)

**Comment by JanAckermann** [comment]
THX, implemented
