### ISSUE TITLE
Context menu & roles: Text-alignment is wrong

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7619]
### Steps to reproduce
- visible only if the text gets to long, ex. in german
<img width="482" alt="Screenshot 000496@2x" src="https://user-images.githubusercontent.com/26610733/189324884-837b9373-fe69-4d9d-b944-e9663a40ee0a.png">

### Expected behaviour
text should be left aligned

**Comment by JammingBen** [comment]
@tbsbdr I can't reproduce this, is it still happening for you? If so, which browser do you use?

![image](https://user-images.githubusercontent.com/50302941/189598337-122a31dc-55fb-4c28-9e07-4eeb27a8b8b9.png)

**Comment by tbsbdr** [comment]
can't reproduce the screenshot neither.

though it might still exist for verbose translations as text is set to `text-alginment:center`

setting it to p4 as I can't provoke a userfacing issue - exists just in theory:

![](https://user-images.githubusercontent.com/26610733/189605938-02fe2e45-06e4-445c-8ade-73df3096a354.png)

**Comment by tbsbdr** [comment]
As discussed, this might be related.

*   short text in permissions is left aligned -> OK ✅
*   long text in permissions gets centered -> Not OK ❌

![](https://user-images.githubusercontent.com/26610733/189611301-b5bea99d-7ec7-4408-8f1e-6bc27a225438.png)

![](https://user-images.githubusercontent.com/26610733/189611476-75baae52-d103-48ba-a34f-df17973ed2c7.png)
