### ISSUE TITLE
Shared resources is not displayed by the global search from `personal` until the `shares` page is visited

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#7629]
### Steps to reproduce
1. As user `Einstein` create resource `test-file.txt` and share it with user `moss` 
2. As `moss` accept the share and search for `test-file.txt`, it works.
3. Now do the same from page `personal`, it works as expected the file is displayed in the list 
4. Reload the personal page and search for `test-file.txt` from the same page
5. There's no result
6. Now visit the `shares` page and search for the file, it works 
7. Go back to personal and search from there it works again

### Expected behaviour
The resource should be displayed

### Actual behaviour
The resource is not displayed until the `shares` page is visited

#### OCIS

https://user-images.githubusercontent.com/41103328/189594829-47104b28-b02a-487e-9392-51f8ed2db63f.mp4

#### OC10

https://user-images.githubusercontent.com/41103328/189594873-f71a6d6e-6835-4519-a37f-6bd3ed0586d6.mp4

All oc10, ocis and web are latest master

**Comment by SwikritiT** [comment]
tests are failing in this PR due to this issue https://github.com/owncloud/web/pull/7583

**Comment by ScharfViktor** [comment]
I tried to reproduce on a fresh master. It seems to have been fixed.

**Comment by SwikritiT** [comment]
> I tried to reproduce on a fresh master. It seems to have been fixed.

I ran the tests that were disabled due to this issue they're passing now. I'll make a PR enabling it and then close this issue

**Comment by SwikritiT** [comment]
The tests are passing here so closing https://github.com/owncloud/web/pull/7722
