### ISSUE TITLE
Web is disabled while deleting a large number of files process

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7633]
ownCloud Web UI 5.7.0 
Infinite Scale 2.0.0-beta.8

When we upload a large number of files, user has sufficient information that the download process is going on and navigation between folders is possible

When a user deletes a large number of files, the web looks like it is hanging.
- dialog "delete files" hangs
- web is disabled while deleting process
- If we click "cancel" button -> deleting process will contunue until all files are deleted

https://user-images.githubusercontent.com/84779829/189647688-570f6c97-21ad-469e-bed9-c9a0a8eec171.mov

**Comment by kulmann** [comment]
Could you add this as comment to https://github.com/owncloud/web/issues/7039 and close this issue here?

**Comment by ScharfViktor** [comment]
Okay, I knew this problem was noticed but could not find it

**Comment by kulmann** [comment]
changed the title a little bit now - hope that makes it more discoverable :-)
