### ISSUE TITLE
Token refresh broken with keycloak

### ISSUE THREAD

**Issue by micbar** [owncloud/web#7636]
### Steps to reproduce
1. Login with Keycloak
2. Watch the token refresh in the browser's network tab

### Expected behaviour
Token refresh should work

### Actual behaviour
Token refresh runs into an error

## Observations

1. The token refresh starts
2. We get a new access token with a shorter lifetime
3. After some while a kind of countdown starts, web tries to  refresh the token every second but the lifetime is always one second less than before (maybe also a keycloak issue)
4. Web runs into a session timeout

### Screenshots

![Bildschirmfoto 2022-09-12 um 20 40 25](https://user-images.githubusercontent.com/4378513/189732426-f686cd15-ba82-42aa-8ec4-5510d950b673.png)

![Bildschirmfoto 2022-09-12 um 20 40 05](https://user-images.githubusercontent.com/4378513/189732475-0444a989-bdfa-4ab2-b565-e0301eb8f6b0.png)

![Bildschirmfoto 2022-09-12 um 20 42 14](https://user-images.githubusercontent.com/4378513/189732514-26e92a3d-c3f7-4208-9007-826ecb8efe42.png)

![Bildschirmfoto 2022-09-12 um 20 42 23](https://user-images.githubusercontent.com/4378513/189732544-760d24fe-a940-4c8f-9b6b-5742bbcb966c.png)

![Bildschirmfoto 2022-09-12 um 20 40 17](https://user-images.githubusercontent.com/4378513/189732572-3934e4d9-3cff-4400-8411-0d6059ab9111.png)

![Bildschirmfoto 2022-09-12 um 20 40 11](https://user-images.githubusercontent.com/4378513/189732602-96877402-7d4b-4072-affa-fb380faccc85.png)

### Environment general
**Operating system**:

**Backend (ownCloud Core or Infinite Scale)**:
ocis 2.0.0-beta.8

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Keycloak deployment example

### Keycloak config

Token Lifetime: 2 min
![1663007867008](https://user-images.githubusercontent.com/4378513/189731952-d13f3f3b-ea83-4196-8889-5a6114852dd7.png)

Session Idle: 3 min.
![1663007888809](https://user-images.githubusercontent.com/4378513/189731981-e0cb9db7-09f0-4892-a17d-b24d8d3f3deb.png)

### Environment ownCloud Infinite Scale
**Version:**
2.0.0-beta.8
**Updated from an older Infinite Scale or fresh install:**

**Where did you install Infinite Scale from:**

### Environment ownCloud Core
**Web server:**

**Database:**

**PHP version:**

**Version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and put the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well-sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to diligently
remove *all* hostnames, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by micbar** [comment]
@dschmidt @kulmann @fschade FYI

**Comment by fschade** [comment]
Thanks, pretty well documented 🤗

**Comment by kulmann** [comment]
Tried the same... When I was inactive in that browser window the `refresh_expires_in` gets reduced over time. When I'm active again it gets reset to 1800. Did you observe the same?

Read a little bit about how keycloaks `refresh_expires_in` is constructed and found this: https://stackoverflow.com/a/67624190
So it seems like `refresh_expires_in` is the smallest value among `SSO Session Idle`, `Client Session Idle`, `SSO Session Max`, and `Client Session Max`. Maybe the session idle time reduces during inactivity.

If that's the desired behaviour this doesn't seem like a bug at all. Just keycloak configuration complexity. 😋 Web actually does the token renewal according to the information it has. Can't see anything wrong here.

**Comment by kulmann** [comment]
Thanks for the explanation @fschade 

For enabling offline access we need to add `offline_access` to the requested scopes. Can be done via config.json or with the env var `WEB_OIDC_SCOPE` in ocis (if no dedicated config.json has been specified). Default scopes are `openid profile email`, you would have to add `offline_access` to that list.

**Comment by micbar** [comment]
@fschade In your example, did you run into the session time out window?

**Comment by fschade** [comment]
i updated the description

**Comment by micbar** [comment]
Before we implement something, let us think what we want to have as a desired behavior.

> SSO Session Idle: 2m
> SSO Session Max: 3m

According to your explanation, this is the time we can work in an application.

So if that is desired, we need to be redirected to the login page.

But the access token lifespan is something different and seems to be refreshed flawlessly.

**Comment by kulmann** [comment]
Yes, to my understanding `SSO Session Max: 3m` means that the session gets invalidated after 3 minutes, meaning you'll be logged out. I think it's reasonable that we show a page, informing the user that their session expired. Wording can be improved of course...

**Comment by fschade** [comment]
we increased the sso idle timeout, this fixes described behavior.
please reopen if needed.
