### ISSUE TITLE
Link to shares page with highlighting

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/web#7646]
It would be nice to have the ability to highlight a specific share in the shares list via link.

Use-case:

- Einstein shares something with Marie
- Marie receives an email containing a link pointing to her shares page (e.g. `https://ocis-host/files/shares/with-me?highlight-share-id=157070d2-c2b6-479d-a7bc-cec65ec309d1`)
- Share with the uuid `157070d2-c2b6-479d-a7bc-cec65ec309d1` is highlighted for better visibility

refs https://github.com/owncloud/ocis/pull/4564
refs https://github.com/owncloud/ocis/issues/4303

**Comment by kulmann** [comment]
I would like to utilize our `scrollTo` query parameter for this. Since the `Shared with me` page can have name clashes for pending shares we indeed need to use the share id.

**Comment by kulmann** [comment]
@lookacat can you have a look at this?

**Comment by JammingBen** [comment]
> I would like to utilize our `scrollTo` query parameter for this. Since the `Shared with me` page can have name clashes for pending shares we indeed need to use the share id.

This has been implemented meanwhile, hence I'm closing this issue. You can simply use the `scrollTo` query param followed by the share id.
