### ISSUE TITLE
Missing git command while running oc10 with docker-compose

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#7672]
Running oc10 with: `docker-compose up oc10`
exists with error:
```bash
...
web_oc10  | /usr/bin/entrypoint: line 20: git: command not found
web_oc10 exited with code 127
```

### Steps to reproduce
1. Remove old oC10 image: `docker rmi web-oc10` or `docker rmi owncloud/server`
2. Try to start oC10 using compose file: `docker compose up oc10`

**Comment by phil-davis** [comment]
`git-core` was removed in PR https://github.com/owncloud-docker/ubuntu/pull/116

Maybe this is the cause of the problem? The docker images are based on `owncloud-docker/ubuntu` ... I suppose that `git` has gone from all of them. CC: @xoxys FYI

Why does something need `git` in that docker image?

**Comment by xoxys** [comment]
Correct, removed from prod base image. That's only affecting the dev container. Feel free to add whatever is needed, as done in https://github.com/owncloud/web/pull/7673 I guess it's needed to fetch some dev stuff during startup.

**Comment by saw-jan** [comment]
> `git-core` was removed in PR [owncloud-docker/ubuntu#116](https://github.com/owncloud-docker/ubuntu/pull/116)
> 
> Maybe this is the cause of the problem? The docker images are based on `owncloud-docker/ubuntu` ... I suppose that `git` has gone from all of them. CC: @xoxys FYI
> 
> Why does something need `git` in that docker image?

Yeah, this problem came with the update image.

We use git only to set up testing and other core apps which is done in the entrypoint. And in docker-compose setup, we add necessary libs in the local docker file (e.g. oc10.Dockerfile)
