### ISSUE TITLE
Conflict selection "keep both" for folders overwrites content when using Firefox

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#7680]
### Steps to reproduce
1. start web with ocis (both current master)
2. create a folder `f1`
3. upload a folder with the same name
4. in conflict dialog select "keep both"

### Expected behaviour
the new folder should be named `f1 (2)`

### Actual behaviour
the folder is overwritten

### Environment general
**Operating system**:
Ubuntu 22
**Backend (ownCloud Core or Infinite Scale)**:
ocis

### Environment ownCloud Infinite Scale
**Version:**
commit ca66a9f7516734e7a3c64074d37f266dd90f702f
**Updated from an older Infinite Scale or fresh install:**
fresh
**Where did you install Infinite Scale from:**
git

### Client configuration
**Browser:**
FF 104.0.2 (64-bit)
Chrome works fine
**Operating system:**
Ubuntu 22

#### Browser log
```
MKCOLhttps://localhost:9200/remote.php/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$e256fd28-0fcc-4d4f-8f76-98c920c7dd44/f1/
[HTTP/1.1 405 Method Not Allowed 213ms]

Error: The resource you tried to create already exists
    r https://localhost:9200/js/chunks/vendor-b5f623a3.js:136
    buildHttpErrorFromDavResponse https://localhost:9200/js/chunks/vendor-b5f623a3.js:136
    createFolder https://localhost:9200/js/chunks/vendor-b5f623a3.js:136
    promise callback*createFolder https://localhost:9200/js/chunks/vendor-b5f623a3.js:136
    vt https://localhost:9200/js/web-app-files-06301145.js:1
    handleUppyFileUpload https://localhost:9200/js/web-app-files-06301145.js:1
    displayOverwriteDialog https://localhost:9200/js/web-app-files-06301145.js:1
    onFilesSelected https://localhost:9200/js/web-app-files-06301145.js:1
    publish https://localhost:9200/js/chunks/vendor-b5f623a3.js:12
    publish https://localhost:9200/js/chunks/vendor-b5f623a3.js:12
    publish https://localhost:9200/js/web-runtime-1e168de2.js:1
    addFiles https://localhost:9200/js/web-runtime-1e168de2.js:1
    handleDrop https://localhost:9200/js/chunks/vendor-b5f623a3.js:147
    getFile https://localhost:9200/js/chunks/vendor-b5f623a3.js:147
    getFile https://localhost:9200/js/chunks/vendor-b5f623a3.js:147
    p7 https://localhost:9200/js/chunks/vendor-b5f623a3.js:147
    p7 https://localhost:9200/js/chunks/vendor-b5f623a3.js:147
    f7 https://localhost:9200/js/chunks/vendor-b5f623a3.js:147
    f7 https://localhost:9200/js/chunks/vendor-b5f623a3.js:147
    f7 https://localhost:9200/js/chunks/vendor-b5f623a3.js:147
web-app-files-06301145.js:1:101034
```
![image](https://user-images.githubusercontent.com/2425577/191926643-b0a29751-6975-4d53-86f3-0e9f43ec71b9.png)

**Comment by JammingBen** [comment]
Note: It happens when uploading via the "Upload"-menu, but not via Drag&Drop.

This is due to the reason that the `relativePath` property has a leading slash when resources are dropped, but not when selected via menu. This "issue" originates from the browser (or Uppy, I'm not 100% sure).

**Comment by individual-it** [comment]
@JammingBen it happened for me also with Drag&Drop

**Comment by JammingBen** [comment]
> @JammingBen it happened for me also with Drag&Drop

Oh indeed. Chrome works with Drag&Drop, FF is broken either way. I assume the missing `relativePath` is still the issue, but that needs investigation.

@lookacat That's the issue I was talking about yesterday. However, as I already said, it needs to wait for the Drive-Alias-PR.
