### ISSUE TITLE
[oC10] Bottom Elements in OnlyOffice Documents missing

### ISSUE THREAD

**Issue by voroyam** [owncloud/web#7701]
Excel Documents "hide" the bottom elements. Scrolling is difficult bc you scroll in the cells, not the UI. Issue does not appear in the classic UI. Only in oC Web.

- oC Classic, notice the sheet selection at the bottom:

![sheet selection_1](https://user-images.githubusercontent.com/24212810/192759550-d9750628-fdee-4402-8794-2793dff8b657.png)

- New UI, same Window Size, same Document, no sheet selection, bottom elects are missing

![no-sheet-selection](https://user-images.githubusercontent.com/24212810/192759617-bd0f00e1-8348-45eb-8caa-ba54fc4ffab0.png)

**Comment by JammingBen** [comment]
Closing this as won't fix since we dropped oC10 support beginning with version 7.1.0.
