### ISSUE TITLE
Space viewer can see delete- and restore-actions in space trashbin

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#7702]
### Steps to reproduce
1. As space manager, invite user `test` to a space
2. As space manager, delete a file in the space so it appears in the space trashbin
3. As user `test`, navigate to the space trashbin
4. Select the deleted file

### Expected behaviour
The user should not see delete- and restore-actions.

### Actual behaviour
The user sees the delete- and restore-actions.

**Comment by JammingBen** [comment]
@tbsbdr Am I right about the expected behavior here? Or should the trashbin be hidden completely from the user? Also, what should a space editor be able to do in this case?

**Comment by tbsbdr** [comment]
your bug description is legit.

if you are a read only-member, you should not see the delete/restore options as those are write-actions (kind of..)
