### ISSUE TITLE
+1 Tag is misaligned

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7708]
Problem:
![thumb-Clipboard - September 23, 2022 2_27 PM](https://user-images.githubusercontent.com/26610733/192994495-e2971043-50c2-4b13-bad1-8122b7994904.png)

expected behaviour:
+1 tag should be in line with the other tags :-)

**Comment by matheusmuniz03** [comment]
Hey @tbsbdr, how to get to this page locally?

**Comment by pascalwengerter** [comment]
> Hey @matheusmuniz03  Tags are currently only available on the experimantal branch which you would need to build yourself from https://github.com/owncloud/ocis/tree/experimental 
> 
> If you don't want to build it yourself, tags should be available at the beginning of next year for ocis - stay tuned

Small correction - it needs the `experimental` branch in both the oCIS and web repo :) took me a bit to figure out why I don't see the tags on the UI
