### ISSUE TITLE
Translations for Contextual helpers are not getting applied

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7716]
Strings are translated but are not shown in the Web UI:

### Translated string in Traxisfex:
<img width="1503" alt="Screenshot 000694@2x" src="https://user-images.githubusercontent.com/26610733/193089233-b72da9aa-a0a9-42a5-aec0-96df004ee55b.png">

### UI is in German, but Contextual helpers are not translated:
<img width="530" alt="Screenshot 000693@2x" src="https://user-images.githubusercontent.com/26610733/193088813-50cf5c4a-f2b3-4ba9-9473-35d98a0af2f7.png">
<img width="510" alt="Screenshot 000692@2x" src="https://user-images.githubusercontent.com/26610733/193088820-33cd3c28-4cbc-4c38-acae-ae942c51c9c3.png">
<img width="517" alt="Screenshot 000691@2x" src="https://user-images.githubusercontent.com/26610733/193088827-a93539ae-de9a-41c5-9105-1ab7c4164915.png">

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/owncloud-design-system/pull/2334 - needs ODS update though to appear in Web.
