### ISSUE TITLE
Search bar sends to many requests

### ISSUE THREAD

**Issue by kobergj** [owncloud/web#7723]
### Steps to reproduce
1.Type something into the search bar

### Expected behaviour
A request is send when the user stops typing

### Actual behaviour
A request is send on every key stroke

### Environment general
Versions:
- web: ownCloud Web UI 5.7.0
- ocis: Infinite Scale 2.0.0-beta.8+0477273ff Community

### Explanation:
On every search request ocis will open the index file which needs a bit of memory allocation (depending on size of the index). When spamming the server with search requests the search service will be OOM killed by the os which results in `500` or `502` results.

We will implement a cache on server side to avoid ddos attacks, but less search request from the webui would improve user experience.

**Comment by kobergj** [comment]
Not sure about priority. @kulmann or @micbar can help?

**Comment by tbsbdr** [comment]
cc @JanAckermann

**Comment by JanAckermann** [comment]
We've implemented a debounce timeout of 100ms after any keystroke (NOT on any keystroke) we feel that this is giving the best user experience as it feels quite fluent. 

The expected behavior is quite controversial, how do we know that the user has actually stopped typing?

**Comment by kobergj** [comment]
I would define "the user has stopped typing" as "the user didn't hit a button for time X"

Of course X needs to be defined. I am not a 100% sure what the correct value for it is, but if I'm typing a word into the search bar without stopping, I expect only 1 request being send.

**Comment by kobergj** [comment]
As of now you can just hit random buttons on your keyboard as fast as you can and it will still bomb the server with requests

**Comment by JanAckermann** [comment]
>Of course X needs to be defined. I am not a 100% sure what the correct value for it is, but if I'm typing a word into the search bar without stopping, I expect only 1 request being send.

I am not quite sure if this is a good user experience as it feels laggy that way and not like a typeahead search

Checked with google drive, and they to the same:
![image](https://user-images.githubusercontent.com/26169327/193265443-1685a5bb-968a-4bb4-8f79-e2ee21c33c6c.png)

**Comment by kulmann** [comment]
@JanAckermann not sure if the debounce works as expected. It **should** hold back the requests until the user didn't provide any input for 100ms. But continuous fast typing still triggers requests.

**Comment by JanAckermann** [comment]
Will investigate, I also think we shouldn't do the debounce on every search provider, but on one place (so basically in the search bar component)
