### ISSUE TITLE
User has option to rename the mount point in the search results

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7726]
ownCloud Web UI 5.7.0 
 Infinite Scale 2.0.0-beta.8+befe44245 Community 

Steps:

- admin creates folder "new" and share to einstein (edit permissions)
- einstein accepts folder and tries to find vie search
- in search result einstein has option rename folder

Expected: no ability to rename the folder in the search results. Same behavior with "Shares" 

Actual: 
![Screenshot 2022-09-30 at 15 39 30](https://user-images.githubusercontent.com/84779829/193282310-a7e13bac-ad78-48be-9aed-da80132cde2b.png)

https://user-images.githubusercontent.com/84779829/193282092-ee8837d6-fd5c-4f89-9f9f-54bd0628248b.mov

**Comment by JammingBen** [comment]
We should continue to work on renaming shared resources: https://github.com/owncloud/web/pull/7390. It should "solve" this issue here as well.

**Comment by JammingBen** [comment]
We've decided to disable share renaming (for now). So this is not an issue anymore:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/50302941/232760715-5b92a0cc-d057-433f-9411-3d8a3dc63463.png">
