### ISSUE TITLE
Search result confuses the path

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7727]
ownCloud Web UI 5.7.0
Infinite Scale 2.0.0-beta.8+befe44245 Community

lets imagine: 
einstein is member-viewer of the space. 
if manager wants to give einstein ability to edit one folder- he shares folder to einstein as editor

Steps:
- admin creates space with folder "einsteinFol"
- admin adds einstein as member-viewer of the space
- admin shares folder "einsteinFol" to einstein(edit permissions)
- einstein accepts folder and types "ein" into the search

![Screenshot 2022-09-30 at 16 07 27](https://user-images.githubusercontent.com/84779829/193288186-10986c64-a399-4c67-b13f-9d912e17ef3d.png)

- press enter to get search result
![Screenshot 2022-09-30 at 16 11 40](https://user-images.githubusercontent.com/84779829/193288920-3e19a720-d076-48f1-a6a4-81b2ebfd0de0.png)

Actual: both results belong to space. But one should belong to "Shares". `Duplicate keys detected` error

https://user-images.githubusercontent.com/84779829/193291146-fe9e2e02-c7ff-4264-aa97-0af2b8b596a2.mov

**Comment by JammingBen** [comment]
I can't reproduce it with current master, could you please try again @ScharfViktor ? Me guess (or rather my hope) is that the work on URLs recently fixed this issue.

**Comment by ScharfViktor** [comment]
it still reproduces for me, maybe I'm doing something wrong?
- stop docker
- switch to master
- git pull
- rm -rf dist (if needed)
- pnpm install
- pnpm build:w
- start docker-compose with fresh latest ocis

**Comment by JammingBen** [comment]
Should be correct 🤔  Do you have the same behaviour after a page reload? Or only directly after accepting the share?

**Comment by ScharfViktor** [comment]
I get `Duplicate keys detected` after accepting folder and after reload page and searching. Url contains `fileId` or `shareId` if I am in `shared with me` tab

**Comment by ScharfViktor** [comment]
@JammingBen did you reproduce it? if you need help, ping me

**Comment by JammingBen** [comment]
Ahhh I got it! I shared another `einsteinFol` folder from my personal space with einstein - that works. But it has to be the same `einsteinFol` inside the space. Can reproduce it now, thanks 👍

**Comment by kulmann** [comment]
> I'm not sure about the expected behaviour here. As a user, I'd expect to file to only show up once in the search results, because it's basically one resource. But then, the permissions might be different, so there would be a reason to have access to both locations. @kulmann Options?

If we can fix the issue of the incorrect link, I'd prefer to show both entries for now. As you said, they have different permissions - if we have the chance we should make all of them available to the user.

**Comment by ScharfViktor** [comment]
re-tested on `8.0.0-alpha.11`
work correct, both result in the search result - 👍 

<img width="483" alt="image" src="https://github.com/owncloud/web/assets/84779829/18de7fc3-7df8-433b-b543-0417e5bfb374">

when clicking on both folders -> redirect to project space to folder `einsteinFol` (edit permission) - 👍 

There is only one error in the console as the page has 2 identical id's. I think we can ignore it and close issue

<img width="1723" alt="Screenshot 2023-12-06 at 16 53 47" src="https://github.com/owncloud/web/assets/84779829/343ea037-f5fb-4b2d-93c7-eb8badddda40">

**Comment by JammingBen** [comment]
Huh, not that I can remember. But a lot has happened over the last year, so we probably fixed it "by accident"? 😄

**Comment by JammingBen** [comment]
Yes that's a good idea 👍
