### ISSUE TITLE
Polishing: Selected item in dropdown is not visible (Edit Quota)

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7738]
### Problem

Active Item is not visible, textcolor is the same as background.

Reproduce:

1.  login as Space Admin
2.  Select "Edit Quota"

*   Affected: light and dark mode

![Screenshot 000703](https://user-images.githubusercontent.com/26610733/194001176-701a4c77-85c6-40f5-9383-3b6a0306034f.png)

![Screenshot 000700](https://user-images.githubusercontent.com/26610733/194001227-233dc037-db59-46a6-ae6e-b4283ec6ff6b.png)

### Expected

OK ex. in Usermanagement and settings

![Screenshot 000704](https://user-images.githubusercontent.com/26610733/194001480-54b75abf-557c-4df9-a68e-7db33e5008ff.png)

![Screenshot 000705](https://user-images.githubusercontent.com/26610733/194001705-211d9708-aba8-4b55-9b9d-d892ac29a834.png)

**Comment by pascalwengerter** [comment]
Needs a fix in the github.com/owncloud/owncloud-design-system, the modal style rules overwrite the (implicit) OcSelect that gets rendered into it
