### ISSUE TITLE
Wording: Make "Logout-Message" friendlier

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7744]
Problem: The current logout message leaves me with a slight feeling of failure which leads to an unpleasant ux

## Current
![Screenshot 000708](https://user-images.githubusercontent.com/26610733/194159911-86481596-7331-48af-8c20-3992063f402f.png)

## Expected
proposal for a friendlier message:

- Logged out because of inactivity
- You were automatically logged out after 30 minutes of inactivity for security reasons.
- Log in again

![image](https://user-images.githubusercontent.com/26610733/194249675-6f92e9aa-962d-43c1-a3a8-75ce0afeef95.png)
<details>
  <summary>Discarded solution</summary>

![image](https://user-images.githubusercontent.com/26610733/194163567-3e14d812-1d01-49ce-9782-b7133ef1e946.png)
</details>

**Comment by pascalwengerter** [comment]
Feel free to assign this to me 🙋‍♂️

**Comment by kulmann** [comment]
Not sure if we can print the "inactivity" in all relevant use cases. Also I'm pretty sure that there are other reasons for being logged out as well. If you don't have a refresh token and no internet connection at the time when the access token renewal is supposed to happen your access token just expires and we can't issue a new one without a roundtrip to the IdP.

Fully agree that the wording needs improvement though.

Awesome that you want to take care @pascalwengerter thank you! :heart:

**Comment by kulmann** [comment]
Yes, fine by me as well as a first iteration 👍 I guess that users will still be confused about that, but it's way better than before.
