### ISSUE TITLE
Its hard to tell if someone has access to a resource - Add member-filter

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7746]
### Steps to reproduce

Its hard to tell if someone has already access to a resource if the sharee/members list has several people already listed.
 ex. try to spot Jörn in the list:
![Screenshot 000720](https://user-images.githubusercontent.com/26610733/194359895-23ff80a6-3331-43f2-ae47-39dd6a11a872.png)

### Expected behaviour
- Add search-icon 
- click on search icon opens form and alters search icon to close-X
- form filters Members (and Shared with? - tbd - not sure about this)
![image](https://user-images.githubusercontent.com/26610733/194368384-b66c32f4-9f01-40e2-a5be-f0fec6c7e79f.png)

**Comment by JanAckermann** [comment]
@tbsbdr do we want to add the search filter to shared files ?

**Comment by tbsbdr** [comment]
Discussed pros and cons with Benedikt, outcome for now:

*   Filter should only filter Space members (no shares)
