### ISSUE TITLE
Add space between text and button

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7759]
### Steps to reproduce
1. open usermanagement
2. edit newly created user before first login

![grafik](https://user-images.githubusercontent.com/16665512/194848139-3814a0b0-d70d-4951-a8ce-94a588b6e149.png)

Text and button row look a bit compressed. Add space between

**Comment by JanAckermann** [comment]
Fixed via https://github.com/owncloud/web/pull/7820
