### ISSUE TITLE
User Management: Reload data after creating a new user

### ISSUE THREAD

**Issue by pmaier1** [owncloud/web#7761]
After creating a new user, the "Edit user" view in the sidebar stays empty until you reload the page.

**Expected behavior**
After creating a new user, I can click on "Edit user" to change their properties.

**Actual behavior**
After creating a new user, clicking on "Edit user" gives you an empty page in the side bar.

cc @tbsbdr @kulmann

**Comment by kulmann** [comment]
@JanAckermann could you look into this?
