### ISSUE TITLE
Spaces: Right Sidebar cut off on specific window widths

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7773]
### Steps to reproduce
1. Open right sidebar of a space
2. Change browser window width

### Expected behaviour
Elements including right sidebar adapt responsively

### Actual behaviour
Right sidebar width stays fixed, elements are cut off

<img width="1032" alt="grafik" src="https://user-images.githubusercontent.com/16665512/195292449-c8f422dd-4009-47fb-9543-807ec6fe9138.png">

Note: Seen in multiple contexts, not only spaces. Seems to be a general problem with the right sidebar.

**Comment by tbsbdr** [comment]
Discussed some possible solutions like:

1. show only left and right sidebar if there is not enough space (already happens for viewports < 960 px)
2. hide space image if right side bar opens and if there is not enough space.
3. collapse left sidebar if there is not enough space left
4. show scrollbars ;-)
5. make everything 100% responsive
6. place Space-TItle, description etc. below the space image if there is not enough space

We decided to go with "2) hide space image if right side bar opens" as it seems the most cost-effective solution.

Note:
we have a similar issue on other views if the breadcrumb does not behave reposinsive (gets too long). This is described here and won't be fixed before GA: https://github.com/owncloud/web/issues/6731
