### ISSUE TITLE
Replacing a file results in duplicate resource (only UI glitch)

### ISSUE THREAD

**Issue by lookacat** [owncloud/web#7774]
### Steps to reproduce
1. Make /a.txt and a folder b with a.txt
2. Copy /a.txt into folder b and choose 'replace'
3. UI shows the same resource twice 
4. (Reload fixes the issue)

### Expected behaviour
Only one entry should exist

### Actual behaviour
UI shows the same resource twice 

### Environment general
This is only on current master, demo.owncloud.com works fine so I guess there has something gone wrong while refactoring

**Comment by kulmann** [comment]
Found another issue: when choosing `Keep both` the new file names don't get created correctly anymore, see screenshot of copying `a.txt` multiple times
<img width="220" alt="Screenshot 2022-10-14 at 09 08 30" src="https://user-images.githubusercontent.com/3532843/195784533-7c198a3c-21cb-434c-85d5-933a9ac2756f.png">

This should show `a.txt`, `a (1).txt` and `a (2).txt`. Instead it shows `a.txt`, `a (1).txt` and `a (1)(1).txt`....

**Comment by kulmann** [comment]
This is fallout from introducing `fileIds`... after copying files we perform a `getFileInfo` on the copied resource. We use the `resource` objects for this, which contain the old file id, only the new path has been applied on them. Our `getFileInfo` / `listFiles` method now is smart enough to recognize that the fileId doesn't match the resource requested by the new path. So it performs a meta request to obtain the correct path for the file id. As a result it loads the original (copied) resource.

Solution is simple: only use thew new path for the `getFileInfo` request. Will also fix the name issues posted above...

**Comment by kulmann** [comment]
Will be fixed by https://github.com/owncloud/web/pull/7797
