### ISSUE TITLE
"Decline" and "Clear selection" icons are identical

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#7779]
When your screen is <1000px, batch actions for the current file selection will hide their labels and only show their respective icons. This is a bit confusing on the "Shared with others" page, as the icons for "Decline" and "Clear selection" are identical:

![image](https://user-images.githubusercontent.com/50302941/195541295-2c2ca111-7b21-4538-8d78-4e03147bb64b.png)

\cc @tbsbdr

**Comment by CaptWeiss** [comment]
@JammingBen any suggestions on what the Icons should be?
cc @tbsbdr

**Comment by tbsbdr** [comment]
I'd suggest this icon for decline:

![](https://user-images.githubusercontent.com/26610733/195879076-85df4b9c-d22b-4718-8f0c-d3e22bd0108f.png)

`spam-3-line` from https://remixicon.com/
