### ISSUE TITLE
Search result page is missing basic features

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7780]
-- not actionable yet --

### General
Collection of issues on the current SERP (Search Engine Result Page)
We'll proceed in 2 steps:
1. **Single Purpose** Search `only files`
2. **Multi Purpose** Search files `and all other apps` (depends on the extension system / the integration of different search providers)

----------

**The following issues only relate to step 1:**

### Steps to reproduce
1. create the file `test.txt` in Personal
2. Search for test.txt and hit <enter> 
3. compare the search result page with the view in personal

**Missing features**

1. resources are missing checkboxes
2. no batch actions available
3. filestable is not sortable https://github.com/owncloud/web/issues/7798
4. Context-menu is missing most options (@tbsbdr needs ticket)
5. Last modified shows "invalid DateTime" -> this seems to be a backend issue because the `REPORT` endpoint delivers another date format then a regular `PROPFIND` (see https://github.com/owncloud/ocis/issues/4712)
6. Owner is not shown -> might be a backend thing as well since the owner is missing in `REPORT` requests (also see https://github.com/owncloud/ocis/issues/4712)

- can't create links
- Sharing is not possible

![Screenshot 000808@2x](https://user-images.githubusercontent.com/26610733/195544314-9bf517b5-09a6-428c-92b7-f7f07495728e.png)

**Comment by JanAckermann** [comment]
IHMO most when not all described missing features are solved, please open new dedicated issues, if you thing something is still not implemented 

![image](https://github.com/owncloud/web/assets/26169327/754baa0a-0cb3-4086-a61e-94c0d2be8ace)
