### ISSUE TITLE
"Copy" and "Cut" actions don't work for the current folder

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#7784]
### Steps to reproduce

1.  Create a folder in your personal space
2.  Navigate into the folder
3.  Select an action for the current folder via the breadcrumb action menu: "Copy" or "Cut"

### Expected behaviour

The resource should either be copied/cut, ~or these actions should be hidden.~

### Actual behaviour

The actions can be clicked, but nothing is being copied/cut.

I am not sure about the expected behavior, what do you think @tbsbdr @kulmann ?

**Comment by tbsbdr** [comment]
the resource should be copied / cut.

updated initial post
