### ISSUE TITLE
Can't open office file from shared with me `Accepted shares` view

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#7812]
### Steps to reproduce
1. Click on a shared office document in the shared with me `Accepted shares` view (cloud.owncloud.com)

### Expected behaviour
As in ownCloud 10, opening a file directly from the shared with me view is possible

### Actual behaviour
<img width="875" alt="image" src="https://user-images.githubusercontent.com/33026403/196167994-ff996947-2e56-4474-b120-bb932cdde940.png">

Right click (Open in Collabora) and click on the file leads to 404

<img width="543" alt="image" src="https://user-images.githubusercontent.com/33026403/196168203-8ac763cb-068f-4b3a-8deb-42c431ee17f7.png">

### Environment general
**Backend (ownCloud Core or Infinite Scale)**:
ownCloud 10.11

**Frontend**:
ownCloud Web 5.7

**Comment by JammingBen** [comment]
Seems to be fixed meanwhile with 6.0. Feel free to re-open if the issue re-appears.
