### ISSUE TITLE
Insert here button has no visual feedback of Activity

### ISSUE THREAD

**Issue by dragotin** [owncloud/web#7815]
The "insert here" button does not properly indicate that an action is performed, @tbsbdr 

### Steps to reproduce
1. Copy or Cut a file or folder using the buttons on top of the filelist 
2. Navigate to a different folder
3. Use the Insert-Here button to insert the files to this directory.

### Expected behaviour
The UI indicates somehow that the action is "understood" and ongoing. Maybe add some moving symbol to show that something is going on.

### Actual behaviour
The button turns dark blue - which I assume that should indicate it. However, that is not moving at all. I ended up clicking twice a few times because I thought the first click was not understood.

**Comment by tbsbdr** [comment]
Yep, this is a problem we have all over the place in the Web UI. Is on the roadmap after GA.

More general ticket: #6183

**Comment by JammingBen** [comment]
This has been implemented meanwhile via https://github.com/owncloud/web/pull/8611 -> closing.
