### ISSUE TITLE
Can only upload single folder

### ISSUE THREAD

**Issue by B3nWalter** [owncloud/web#7831]
### Steps to reproduce
1. Click on upload button 
2. Try to select multiple folders 
3. Not possible with "strg" and clicking multiple folders

### Expected behaviour
Selecting multiple folder with "strg" + mouse click or with mouse cursor 

### Actual behaviour
Can only upload single folder

### Environment general
Windows

**Comment by kulmann** [comment]
The system file picker doesn't allow multi folder upload, that's a browser limitation unfortunately. You can use the drag&drop upload for multi folder upload.

**Comment by tbsbdr** [comment]
can't fix, browser limitation
