### ISSUE TITLE
Missing open in new tab feature

### ISSUE THREAD

**Issue by B3nWalter** [owncloud/web#7832]
### Steps to reproduce
1. Open web app
2. right click 
3. no open in new tab

### Expected behaviour
having  the possibility to open a file in a new tab to compare files quickly
presumably the behavior in most cloud solutions and file explorer 

### Actual behaviour
makes it complicated, tabs need to be duplicated

### Environment general
oc web

**Comment by AlexAndBear** [comment]
Fixed via https://github.com/owncloud/web/pull/11329
