### ISSUE TITLE
Space: Show context menu: changing position when scrolling

### ISSUE THREAD

**Issue by mmattel** [owncloud/web#7838]
### Steps to reproduce
See:
https://user-images.githubusercontent.com/26610733/196742558-d5dc5888-93df-4b9d-87c3-fb7683e96c5e.mp4

### Expected behaviour
The context menu should not relocate when scrolling

### Actual behaviour
The context menu relocates when scrolling

### Environment general
**Operating system**: macOS and W10

### Notes
Would be great to fix this before GA

@kulmann @tbsbdr fyi

**Comment by mmattel** [comment]
ping

**Comment by kulmann** [comment]
I can't reproduce this anymore, could you recheck please? And if not reproducible for you please close :-)

**Comment by mmattel** [comment]
do you have an instance I can access and test?

**Comment by kulmann** [comment]
any of the continuous `latest` deployments

**Comment by kulmann** [comment]
http://ocis.ocis-web.latest.owncloud.works

**Comment by mmattel** [comment]
Tested via latest, confirmed, fixed 👍

**Comment by kulmann** [comment]
> Tested via latest, confirmed, fixed 👍

Thanks for taking the time to confirm 🥳
