### ISSUE TITLE
Fresh `pnpm i` fails

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#7866]
### Steps to reproduce
1. Clone this repo and `cd` into it
2. Run `pnpm i`
3. See this
<img width="717" alt="Screenshot 2022-10-25 at 23 11 34" src="https://user-images.githubusercontent.com/16822008/197882275-bfee7e09-065a-4af3-ba6f-1db390d059c5.png">

### Expected behaviour
Things work

### Actual behaviour
Things don't work. Not sure if that's related to my local `pnpm` cache maybe? I was trying pretty hard getting a local ODS linked via `pnpm`

**Comment by dschmidt** [comment]
@saw-jan had the same issue

Do you remember, what solved the problem for you? I think it was missing the `.npmrc` file, but it started working, when I added it to the repo iirc.

```
11:27
yeah, I am trying to build web repo locally
I did pnpm upgrade to upgrade the packages
And now the install command works
but I don't think we need to do upgrade
```

Agreed, upgrade installs everything in the valid version ranges, which probably gives you too new versions of a bunch of our deps.
Maybe it also fails now because we pinned dependency versions via renovatebot?

**Comment by pascalwengerter** [comment]
The culprint seems to be `vue-jest` having been set to `v3.0.7` by renovate-bot, fixing it at `v3.0.0` seems to resolve it for now 🥳

**Comment by dschmidt** [comment]
I don't get that, if you look at  https://github.com/owncloud/web/pull/7842/files :

Before `^3.0.7` was pinned, now `3.0.7` is pinned - in both `package.json` and `pnpm-lock.yaml`. If at all the release should be older than before, but `3.0.7` is already the latest (stable?) release...

Maybe you can paste your diff or send a PR with your changes and the updated lock file?

**Comment by saw-jan** [comment]
I found out something.
I use `nvm` to install node versions and `npm` to install `pnpm` and works just fine.
1. :heavy_check_mark: Working
i. Install node 16: `nvm install 16`
ii. Install pnpm: `npm i -g pnpm` (path: `~/.nvm/versions/node/v16.18.0/bin/pnpm`)
iii. `pnpm i` works :heavy_check_mark: 

2. :x: `spawn node-gyp` Error
i. Install node 16: `nvm install 16`
ii. Install pnpm: `curl -fsSL https://get.pnpm.io/install.sh | sh -` (path: `~/.local/share/pnpm/pnpm`)
iii. `pnpm i` fails :x:

**Comment by dschmidt** [comment]
We might be good if we update vue-jest to a recent version: https://github.com/vuejs/vue-jest/issues/403

**Comment by JanAckermann** [comment]
Fixed via: https://github.com/owncloud/web/pull/7901
Anyways, we want to update vue-jest later

**Comment by saw-jan** [comment]
> I found out something. I use `nvm` to install node versions and `npm` to install `pnpm` and works just fine.
> 
> 1. heavy_check_mark Working
>    i. Install node 16: `nvm install 16`
>    ii. Install pnpm: `npm i -g pnpm` (path: `~/.nvm/versions/node/v16.18.0/bin/pnpm`)
>    iii. `pnpm i` works heavy_check_mark
> 2. x `spawn node-gyp` Error
>    i. Install node 16: `nvm install 16`
>    ii. Install pnpm: `curl -fsSL https://get.pnpm.io/install.sh | sh -` (path: `~/.local/share/pnpm/pnpm`)
>    iii. `pnpm i` fails x
> 
> `pnpm` installed using `install.sh` script is giving this error.
> 
> Can someone confirm this?
> 
> CC @pascalwengerter @dschmidt

Both approaches work now! :+1:
