### ISSUE TITLE
Present mode is not working in PDF viewer

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#7879]
### Steps to reproduce
1. Open a PDF file with PDF viewer
2. Click on `Present` in the three dots menu
<img width="410" alt="image" src="https://user-images.githubusercontent.com/33026403/198117711-d358f850-aec7-4dd6-b669-62f77939f8fe.png">

### Expected behaviour
PDF is shown in full screen mode

### Actual behaviour
Nothing happens

### Environment general
**Backend (ownCloud Core or Infinite Scale)**:
oCIS 2.0.0 Beta8

**Comment by pascalwengerter** [comment]
I couldn't find the `Present` button in Chrome, Safari or Firefox and will close the ticket. Feel free to reopen
