### ISSUE TITLE
e2e. upload.feature

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7885]
instead of deleted acceptance tests https://github.com/owncloud/web/issues/7264#issuecomment-1248932852 I suggest to create  upload.feature e2e tests:

- [ ] create upload folder step with options "Keep both" and "Merge"
- [x] change existing method upload file. add options: "Keep both" and "Replace"
- [x] change method `And "Alice" creates the following resources`. add option to create file in the folder
- [x] create new upload.feature

steps: 
- user creates folder `PARENT` 
- user create files: `parent.txt` and `example.txt` with content in the folder `PARENT`
- user uploads `PARENT` folder (we have it in `filesForUpload`) with `merge` option
Expect: `PARENT/parent.txt` get new version, `example.txt` is exist, another files of uploaded folder `PARENT` are exist

- user uploads `PARENT` (we have it in `filesForUpload`) with `keep both` option
Expect: we have `PARENT (1)` and `PARENT` folders

- same with file uploading

cc @individual-it  @SwikritiT

**Comment by amrita-shrestha** [comment]
@ScharfViktor Do you mean `Merge` in this sentences `change existing method upload file. add options: "Keep both" and "Replace"`

 I could not find any setting to set the `Replace` option.Could you help me in this 
![noreplace](https://user-images.githubusercontent.com/54478846/199649956-7e8bb57c-f25d-4b50-b837-d6ff28aced09.png)

**Comment by ScharfViktor** [comment]
> @ScharfViktor Do you mean `Merge` in this sentences `change existing method upload file. add options: "Keep both" and "Replace"`
> 
> I could not find any setting to set the `Replace` option.Could you help me in this ![noreplace](https://user-images.githubusercontent.com/54478846/199649956-7e8bb57c-f25d-4b50-b837-d6ff28aced09.png)

Yes, "replace" = "merge". I think the button has been renamed.

**Comment by saw-jan** [comment]
@amrita-shrestha something remaining to do on this?

**Comment by amrita-shrestha** [comment]
@saw-jan  currently upload folder feature is not available in playwright so some task is still not done.

**Comment by saw-jan** [comment]
Playwright cannot do folder upload as of now. See https://github.com/microsoft/playwright/issues/6854

**Comment by ScharfViktor** [comment]
closed as completed
