### ISSUE TITLE
[Web] Rename "Quicklink" to "link" 

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7891]
### Steps to reproduce
1. Rightclick on a resource
2. Select "Copy Quicklink"
3. I received feedback that "Quicklink" is an **unexpected wording** which makes users think. 

### Expected behaviour
- Wording that does not make users think (meet users expectations)
- Generally rename **Quicklink** to **link** --> `Copy link`

1. Context menu: Rename to "Copy link"
2. Tooltip: Rename to "Copy link"
3. Form label: Rename to "Link"
4. Action: Rename to "Add another link"
5. Seperator: Set color to `--oc-color-input-border` to increase visibility of the separator-line

![Screenshot 000924](https://user-images.githubusercontent.com/26610733/199553530-dd43c5dc-fa42-45a1-9767-264ab6789555.png)

### Actual behaviour
- wording makes users think

**Comment by tbsbdr** [comment]
@kulmann as seeing it now in the UI, I'd prefer to call it just "copy link" and "Link" in the sidebar. I suggest to push the link just as "The link" - everything else is "Advanced usecase" and should not disturb regular users-usecase.

Ok like this, @kulmann ?

CC @dragotin 

\--

Note: The multiple links should be more hidden in future, ex. via "Advanced view"-switch like you know it from your FritzBox and some other applications.

![](https://service.avm.de/support/media/en/223.png)

**Comment by kulmann** [comment]
I like the simple `Link` and `Copy link` as well.

Still thinking about the action below, which is currently labelled `Add link`. I think making it more clear that this is not the submit action for creating the link above would be helpful. What do you think about e.g. `Add more links`? Can you think of alternatives?

**Comment by dragotin** [comment]
I think @tbsbdr and me also considered the term `Standardlink`, as it makes it clear which link (out of the multiple) that is, but I like only `Link` as well.
I very much like to switch to `Add more links`.

**Comment by tbsbdr** [comment]
Regarding the "Add more link" issue:

I understand you say that the "Add link" action gives the impression to belog to the link above (which is wrong).

Correct @dragotin @kulmann ? 

![](https://user-images.githubusercontent.com/26610733/198971975-dd285b57-0c8f-40ea-8118-aa454b14e669.png)

**Comment by kulmann** [comment]
> Regarding the "Add more link" issue:
> 
> 
> 
> I understand you say that the "Add link" action gives the impression to belog to the link above (which is wrong).
> 
> 
> 
> Correct @dragotin @kulmann ? 
> 
> 
> 
> ![](https://user-images.githubusercontent.com/26610733/198971975-dd285b57-0c8f-40ea-8118-aa454b14e669.png)

Yep, that's the issue I see 👍🏻

**Comment by tbsbdr** [comment]
Classified as Prio2 as I again observed that the wording `Quicklink` leads to confusion. Potential to cause even internal failures due to misunderstandings.
