### ISSUE TITLE
Upload of big files is failing in CERNBox: Uppy error "Upload stalled for 30 seconds, aborting."

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#7900]
### Steps to reproduce
1. Upload a large file (6-7 GB)

### Expected behaviour
Upload works

### Actual behaviour
At the very end of the upload it always fails for any user, in console we get 
`[Uppy]  Failed to upload xxx. Upload stalled for 30 seconds, aborting.`

For smaller files (tested 2 and 3 GB) everything works.
With curl we are able to upload the same big files, so it must be the frontend issue.

We tried to set the timeout in uppyOptions to 1h and to 0 (deactivates check) but still get the same error.

For smaller files (tested 2 and 3 GB) everything works.

The nginx upload limit is 8GB.

**Comment by kulmann** [comment]
This is without TUS, right? So no chunking in place, only one big XHR upload, correct?

**Comment by elizavetaRa** [comment]
Xhr upload, yes

**Comment by JammingBen** [comment]
> We tried to set the timeout in uppyOptions to 1h and to 0 (deactivates check) but still get the same error.

@elizavetaRa Where exactly did you set the timeout? The proper place would be where the XHR plugin is being initialized: https://github.com/owncloud/web/blob/54e26b5010bb0ca99626808d5a67579466731da8/packages/web-runtime/src/services/uppyService.ts#L78

I did get the same error, however, after increasing the timeout in the XHR options, everything works.

**Comment by elizavetaRa** [comment]
@JammingBen I was setting in `packages/web-runtime/src/composables/upload/useUpload.ts`  in `uppyOptions`. Will try your way, thanks!

**Comment by elizavetaRa** [comment]
@JammingBen it worked by us as well, maybe you could add the fix to web

**Comment by JammingBen** [comment]
https://github.com/owncloud/web/pull/7912 increases the default timeout and also makes it configurable.
