### ISSUE TITLE
Enable autoplay on media files

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7908]
Clicking on a media file (mp3, mp4) should, analogously to clicking on other files (e.g. docx), cause the file to open, in the case of media files -> AutoPlay after opening the media viewer. Clicking on the respective file is the users` intent to open the file.
Currently the media player opens, the file must be started manually.

**Comment by kulmann** [comment]
@hurradieweltgehtunter what about using back/forward buttons in the preview app? Would you expect all videos / audio files to start playback automatically, or only for the one file that you opened from the files list?

Also, please note that Chromium browsers only allow **muted** autoplay, see: https://www.w3schools.com/tags/att_video_autoplay.asp

**Comment by JanAckermann** [comment]
>Would you expect all videos / audio files to start playback automatically

I would expect that

**Comment by JanAckermann** [comment]
>Also, please note that Chromium browsers only allow muted autoplay

Seems to play with sound on google chrome tough, good enough for me =)

**Comment by kulmann** [comment]
> > Would you expect all videos / audio files to start playback automatically
> 
> I would expect that

I wouldn't 😁 

@tbsbdr what are your thoughts on this?

**Comment by pascalwengerter** [comment]
Not sure how outdated it is by now (2016 is a while back, after all), but I vividly remember this and all the implications https://webkit.org/blog/6784/new-video-policies-for-ios/
