### ISSUE TITLE
Admin cannot see the group members 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7921]
Infinite Scale 2.0.0-beta.8+1f53ec525 Community
ownCloud Web UI 6.0.0-rc.4

Steps:
- run ocis with creating demo users
- admin opens `user management` -> `Groups `tab
- admin clicks on the group's details button

Expected: admin can see all members of the selected group

Actual: Api gives us possibility to see who are members of the group, but we can not see members on the web:

![Screenshot 2022-11-04 at 10 08 47](https://user-images.githubusercontent.com/84779829/199946972-14849a6c-7853-49bf-9174-ec4e6f911e59.png)

**Comment by JanAckermann** [comment]
@tbsbdr needs a little design concept <3
