### ISSUE TITLE
[oC10] PDFs can't be opened (local Docker setup)

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#7931]
Opening PDF files leads to a console error:

```
Refused to load plugin data from 'blob:http://host.docker.internal:8080/0116bc02-16f5-4653-8bd4-30ac6897b3f8' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'object-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by kulmann** [comment]
Are you sure @JammingBen ? 🤔 there is this issue: https://github.com/owncloud/web/issues/6772 I'm not convinced that it should be closed though... and that came from a production environment.

**Comment by egorzot** [comment]
@JammingBen how did you solve this issue? I'm stuck with it

**Comment by JammingBen** [comment]
@egorzot The issue should have been fixed via https://github.com/owncloud/web/pull/8498 in current master.
