### ISSUE TITLE
Improve contextual help text for public link role "Internal"

### ISSUE THREAD

**Issue by mmattel** [owncloud/web#7938]
As discussed with @kulmann and @micbar (see https://github.com/owncloud/ocis/issues/5000), the help text describing the role `Internal` needs improvement as users get confused when reading this.

**Current contextual help text:**
<img src="https://user-images.githubusercontent.com/3321281/200574130-f45e49f2-7e68-487b-8cde-b7f48f0ee5b1.png" width="300">

**Suggestion:**
_Account and existing access rights required_
The recipient of this link can access the shared content only if he has already an account with at least viewing permissions to that shared content. This role is beneficial to point an existing member to data directly he already has access to, therefore the name Internal is used.

**Current list box text:**
<img src="https://user-images.githubusercontent.com/3321281/200575971-dba31b10-8b5e-4c46-b6d9-290047907d79.png" width="300">

**Suggestion:**
_Internal_
Account and existing access rights required

**NOTE**
The texts are suggestions and can be used for further refinement.

**Comment by JanAckermann** [comment]
Texts were written by @tbsbdr, as he is the text-god, I'd like to hear his opinion

**Comment by mmattel** [comment]
> Texts were written by @tbsbdr, as he is the text-god, I'd like to hear his opinion

When gods meet 🤣

**Comment by tbsbdr** [comment]
as discussed:
- Main objective of the contextual helper is to tell the user where to find all information about sharing (--> in the docs)
- Please add a short sentence with the meaning like "Learn all about sharing [here](#)"

**Comment by mmattel** [comment]
Just for reference, this could be a possible target to the documentation regarding [Sharing](https://doc.owncloud.com/webui/next/owncloud_web/web_for_users.html#sharing).

**Comment by mmattel** [comment]
ping

**Comment by JanAckermann** [comment]
@mmattel what is that ping for ?

**Comment by kulmann** [comment]
We'll get rid of the internal link role.
