### ISSUE TITLE
Refactor drone file related to test failure comment

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#7943]
### Description
If  e2e tests fail in both oc10 and ocis then the trace-view for ocis overwrites the trace-view for oc10. Reference PR https://github.com/owncloud/web/pull/7929#issuecomment-1305152395
Refactor GitHub comments so that it comments all failures at once. 
- [ ] Check failure combination of acceptance, e2e-ocis, e2e-oc10
- [ ] Currently, trace view of the scenario passing in retry also commented. In my view it will be better if only failed-scenario trace view commented. 

### Current behavior 
In a single build if multiple pipelines fails then it comments on failure as shown below:
![Screenshot from 2022-12-07 09-54-07](https://user-images.githubusercontent.com/54478846/206086208-07374c8a-d238-4375-ae5e-2f77e509e95d.png)

@individual-it @SwikritiT @kiranparajuli589 @grgprarup @SagarGi  @saw-jan

**Comment by saw-jan** [comment]
with e2e tests, we can create two separate GH comments for oC10 and oCIS. This way, the logs from one will not overwrite another. Similar is done in client: https://github.com/owncloud/client/pull/10261/commits/79c6497f3616de414adf6fcf623170672f1984a0

For all acceptance tests, maybe create only one GH comment.

**Comment by saw-jan** [comment]
> Check failure combination of acceptance, e2e-ocis, e2e-oc10

GH comments are built within a pipeline, so it would be difficult to check the combination of those

**Comment by amrita-shrestha** [comment]
This debugging PR shows that different comment history is created for different UI test https://github.com/owncloud/web/pull/8070
.
