### ISSUE TITLE
Recipients disappear after re-sharing to the group

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7946]
ownCloud Web UI 6.0.0-rc.6
Infinite Scale 2.0.0-rc.1+736f513cf Community -local

Steps:

- admin creates file and shares to marie
- marie accepts file and re-shares it to the users and the group 

Actual: after re-sharing to the group again, all recipients or public links disappear, but still remain after reloading the page

https://user-images.githubusercontent.com/84779829/201134209-e8df26b8-2a62-4616-a90d-ac0aba9ae550.mov

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/8009.
