### ISSUE TITLE
Quota is not displayed after the creation of the project space and does not change after some operations

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7959]
ownCloud Web UI 6.0.0-rc.6
Infinite Scale 2.0.0-rc.1+736f513cf Community -local

### Steps:
- user creates project space
- go to space->details

### Actual: quota is not displayed - NOT OK

<img width="826" alt="Screenshot 2022-11-14 at 12 50 34" src="https://user-images.githubusercontent.com/84779829/201653378-6649b718-1844-4431-8a4b-4af75e3516fe.png">

reload page: quota is displayed - OK

<img width="825" alt="Screenshot 2022-11-14 at 12 51 08" src="https://user-images.githubusercontent.com/84779829/201653484-6faa11a9-7d37-4281-9831-be61315f55e3.png">

create new text file or change content of the existing file: quota did not increase - NOT OK

restoring old version of the file: quota does not change - NOT OK

upload file or folder: quota changed - OK

delete file or folder: quota changed - OK

**Comment by kulmann** [comment]
Web is currently not in shape for updating quota whenever a writing operation happens. We would need to create quota update requests in many different places for the current state of the code base. So we decided to keep it to a minimum, see https://github.com/owncloud/web/issues/6930#issuecomment-1196729639

Regarding the main part of your issue, that's a bug we should fix: space quota should be visible in space details immediately after creating a space and navigating into it. Page reload should not be needed. We will not fix the other two mentioned cases where quota is not refetched.
