### ISSUE TITLE
No "not enough quota" message when user creates a file

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7960]
ownCloud Web UI 6.0.0-rc.6
Infinite Scale 2.0.0-rc.1+736f513cf Community -local

Steps: 
- create project space with quota = 10 `curl -k -X POST 'https://localhost:9200/graph/v1.0/drives' -u admin:admin -d '{"name":"marketing", "quota": {"total": 10}}' -vk`
- upload file 5 Bytes
- create new txt file and type "123456" 
- try to save

Actual: no message to user on web

Expect: when you try upload file more than 5 Bytes you get message:
<img width="318" alt="Screenshot 2022-11-14 at 13 21 58" src="https://user-images.githubusercontent.com/84779829/201658984-d517ba04-7c3e-4fcb-866f-b1268c58113b.png">

**Comment by JammingBen** [comment]
Good catch, thx! Has been fixed via https://github.com/owncloud/web/pull/8001 (will be shipped to master soon as well).

**Comment by individual-it** [comment]
the error says nothing about quota, but that there was an error contacting the server
![image](https://user-images.githubusercontent.com/2425577/204461559-07da4d33-a3c8-4948-b491-3fd71a476c23.png)

**Comment by JammingBen** [comment]
> the error says nothing about quota, but that there was an error contacting the server

We can't bring new translations to the `stable-6.0` branch for technical reasons. Hence we needed to use an existing, generic error message. The current master has a more specific error message.
