### ISSUE TITLE
Overwriting file in not possible on web if there is enough quota

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7962]
ownCloud Web UI 6.0.0-rc.6
Infinite Scale 2.0.0-rc.1+736f513cf Community -local

Steps see this api test: 
- https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiSpaces/quota.feature#L56-L60
- create project space with quota = 10 `curl -k -X POST 'https://localhost:9200/graph/v1.0/drives' -u admin:admin -d '{"name":"marketing", "quota": {"total": 10}}' -vk`
- upload file 9 Bytes (if you created file- you need reload page #7959 )
- change this file on your PC to 5 bytes and upload it again

Actual: web checking
<img width="318" alt="Screenshot 2022-11-14 at 13 21 58" src="https://user-images.githubusercontent.com/84779829/201662516-ecfe5734-a780-403b-904b-6b4e7d9752ff.png">
but it is possible. 

Expect: The web check appears after clicking the "Keep Both" button. If we choose "merging" - it should be possible to overwrite

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/8015.
