### ISSUE TITLE
Slow network connection: Load timeout for modules

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#7964]
### Steps to reproduce
1. in Chrome: switch on "slow 3G" in developer tools --> Network conditions
2. Go to https://ocis.ocis-traefik.latest.owncloud.works/

### Expected behaviour
The page should work with a slow network as well

### Actual behaviour
The UI shows "Oops, something went wrong", console shows "Load timeout for modules"

![Screenshot from 2022-11-14 16-56-07](https://user-images.githubusercontent.com/7430156/201705826-584a95d1-bf7d-4ef7-8fc3-036657c1f3df.png)

Same repeated in cernbox with increased timeouts: There is a spinner that shows by loading of the app. By loading of the extensions the spinner disappears and on slow connection user only see the white screen. Here expected bahaviour would be to show the spinner by loading of the extensions

**Comment by elizavetaRa** [comment]
Background: this happens to some CERNBox users, especially those working from other countries

**Comment by JammingBen** [comment]
Both PRs https://github.com/owncloud/web/pull/10976 and https://github.com/owncloud/ocis/pull/9287 massively increased loading times, I think we can close here.

There are still some follow-up issues we're planning to tackle:

* https://github.com/owncloud/web/issues/10982
* https://github.com/owncloud/web/issues/10981
* https://github.com/owncloud/web/issues/10980
