### ISSUE TITLE
in nfs mount, upload gets restart if upload data makes storage of nfs server exhaustive

### ISSUE THREAD

**Issue by bishwasojha** [owncloud/web#7971]
## Describe the bug

In nfs mount, the uploading does not get completed if the uploaded data makes storage of nfs server exhaustive. During uploading, the data  is synced to the nfs server, and the server storage is occupied; however, once the server storage is exhausted, the progress bar of uploading restarts from the beginning, and the server storage that was previously occupied is no longer occupied. 

## Steps to reproduce

1. setup nfs client server https://owncloud.dev/ocis/storage-backends/dcfsnfs/
2. upload data exhausting the storage of the nfs server

## Expected behavior
- uploading terminates with some notification

## Actual behavior
- The progress bar during uploading goes to completion, but then the progress bar restarts from the beginning . 

## Setup

- setup nfs client and nfs server

<details>
<p>

```console
OCIS_VERSION=ocis:2.0.0-rc.1
```

</p>
</details>

## Additional context

[Screencast from 14-11-22 12:27:52 अपराह्न +0545.webm](https://user-images.githubusercontent.com/33860671/201593007-2d58753f-df0d-4d70-82e5-6a88578ae334.webm)

**Comment by JammingBen** [comment]
> I don't think the web ui should retry on a 507, should it?

If the upload in gone on the server side, we should avoid retrying, yes. It should be pretty easy, we just need to hook onto the `onShouldRetry` event and check for the status code `507` (https://uppy.io/docs/tus/#onShouldRetry-err-retryAttempt-options-next-gt-next-err).

@butonic Are there any more status codes where retrying should not happen?

**Comment by butonic** [comment]
Hm, InsufficientStorage 507, RFC 4918, 11.5 ... actually any 5xx?

**Comment by JammingBen** [comment]
https://github.com/owncloud/web/pull/7985 has been merged on the `stable-6.0` branch (coming to master soon as well) which addresses this.
