### ISSUE TITLE
preview app: respect sorting from file list

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#7978]
### Steps to reproduce
1. Sort a folder with photos by name
2. Open one of the photos in the preview app
3. Navigate back and forth

### Expected behaviour
The back/forward navigation in the preview app should respect the chosen sorting from the files app.

### Actual behaviour
The chosen sorting is not respected (it's not even "always sorted by name", which would've been okish).

**Comment by pascalwengerter** [comment]
@C0rby fyi we talked about this ;)
