### ISSUE TITLE
version of file cannot be restored by shared user

### ISSUE THREAD

**Issue by bishwasojha** [owncloud/web#7980]
### Descriptiop of bug
A file is shared to a user with editor role. The old version of file cannot be restored and download by a shared user.

### Steps to reproduce
1. create a file and write content
2. again add content to a file and make new version 
3. share file to a user with editor role
4. user accepts a file and check version of file
5. click on restore  
6. old version cannot be restored. 
7. click on download; it throws error 

**Note: This issue isnot reproducable if file is within a folder**

### Expected behaviour 
Old version of file can be restore

## Environment
- server : owncloud/ocis:2.0.0-rc.1

## Client configuration
- Browser: : Google Chrome Version 106.0.5249.61 (Official Build) (64-bit)
- Operating system: : Ubuntu 22.04 LTS

## Additional Information

[Screencast from 16-11-22 03:47:55 अपराह्न +0545.webm](https://user-images.githubusercontent.com/33860671/202164143-7925bb6e-0910-40f4-a448-4ec020d2a809.webm)

**Comment by kulmann** [comment]
@bishwasojha does it work with oc10 for single file shares? 🤔

**Comment by bishwasojha** [comment]
@kulmann it doesnot work in oc10 with new design. But it works fine with classic web of oc10. Seems like a problem with new design of web.

# in classic web

[Screencast from 17-11-22 10:01:42 पूर्वाह्न +0545.webm](https://user-images.githubusercontent.com/33860671/202354071-157bbbda-1dc8-4f22-8e9d-4b37efb2e67c.webm)

# in new web

[Screencast from 17-11-22 10:04:23 पूर्वाह्न +0545.webm](https://user-images.githubusercontent.com/33860671/202354448-9f57c3b9-a449-4992-ab9e-08e513339618.webm)

**Comment by JammingBen** [comment]
https://github.com/owncloud/web/pull/7989 fixes downloading and reverting versions on the "Shared with me"-page, which was the issue here. However, there are still issues with oCIS: https://github.com/owncloud/ocis/issues/3868. These seem to be on the sever side as far as I can see.

**Comment by JammingBen** [comment]
Closing as the issue has been solved in Web and oCIS 👍
