### ISSUE TITLE
Public link of folder with `Uploader`role, public is able to create `(file | folder)` in that folder

### ISSUE THREAD

**Issue by bishwasojha** [owncloud/web#8003]
### Description of bug
when the public link of folder with `Editor` role is changed to `Uploader` , public is able to create file | folder in that folder.

### Steps to reproduce
1. Create a Folder
2. Add Public Link with role `editor`
3. Open the Link in incognito 
4. Change the role `editor` to `Uploader`
5. Refresh the link

Then, in the shared folder, a new file | folder can be created. 

### Expected behaviour
with `Uploader` role , the UI mustnot have option to create file | folder.

### Actual behaviour
Public can create file|folder.
### Environment general
**Operating system**:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

**Backend (ownCloud Core or Infinite Scale)**:oCIS

### Environment ownCloud Infinite Scale
**Version:**  owncloud/ocis: 2.0.0-rc.1 

### Client configuration
**Browser:**  Google Chrome Version 106.0.5249.61 (Official Build) (64-bit)

**Operating system:** Ubuntu 22.04 LTS

### Additional Information
[Screencast from 21-11-22 09:52:17 पूर्वाह्न +0545.webm](https://user-images.githubusercontent.com/33860671/202963730-9a641d78-186a-495e-9352-042bb91b6576.webm)

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/8006.
