### ISSUE TITLE
Make web UI react to server-side events

### ISSUE THREAD

**Issue by gedw99** [owncloud/web#8005]
I am not sure if this is implemented yet or not.

When many users are using the gui to view the same folder , does the gui update in a reactive way such that files being created. Updated or deleted shows in all users gui ? 

If not then I have a few ideas about how both the file view and the file contents ( such as an image ) would be kept synced across gui.

**Comment by kulmann** [comment]
> > We don't have a way to push events from the backend to the Web UI until now. Though that may come in the future.
> 
> Because NATS is already used , we could use web sockets / quic webtransport / SSE to do that.
> 
> centrifugo is a very nice system that uses all the above protocols with NATS to do that in an extensible and secure way. It’s also very well supported imho.
> 
> With multi protocol support we can addd web notification later if we want.

Thank you for the recommendation, we'll definitely look into it 😍 What you describe is currently in the state "agreed, but not yet concepted". We'll work towards it in the next couple of months.

**Comment by pascalwengerter** [comment]
@kulmann or @gedw99 could you update the issue title with "Make web UI react to server-side events" or the likes? Currently sounds like it is a static UI 😅

**Comment by gedw99** [comment]
I am planning to start on this . 

I feel that SSE is a goood first candidate because http/2 and http/3 can use it. Also I tend to like to embrace the CQRS aspect ts with mutations being send in over http and events sent out ( to clients ) over SSE. 

Also it’s good for mobile battery 
There are good golang native libs for Desktop and Mobile. 

But the best aspect is that it built in a to the programmer appears stateless , even though under the hood it is a long poll ( as far as I know . 

My plan is to use NATS to hold the messages with a SSE proxy package worker above it. NATS consumer can do retention until all SSE subscribes have gotten the message . 

Security is jwt NATS . 

The NATS load balancer can be used in the clients to load balance out to the nearest NATS server in the cluster. 

I feel it’s not a good idea to use the NATS websocket. I feel it’s a good idea to not be too couples between client and server.

also zOCIS needs to SSE d specialised notifications to FCM . Apple, etc.

Please let’s me know if any thoughts .

**Comment by kulmann** [comment]
Hey @gedw99 - wow, just wow! Would love to see progress on this, I didn't expect that someone would dive into such a large topic. 🤩 
To be honest, I can't give an educated opinion, yet. What you describe and from what I know this sounds like a really good direction.

Regarding service workers, we're currently putting some effort into integrating `workbox` for some long running operations (like copy or batch-delete).

Please go ahead 🚀 💪 
And please reach out for disussions / help / ...

**Comment by JanAckermann** [comment]
We started to implement SSE for file locks already. More events will follow, will close this issue as completed, since we have more issues according to the respective events and the engine is already implemented
