### ISSUE TITLE
Deleted user still as member of the project space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#8010]
ownCloud Web UI 5.7.0-rc.10 
Infinite Scale 2.0.0-beta.7

Steps:

- admin creates space
- admin adds users "richard" and "einstein" as members
- admin creates public link to the space
- admin deletes user "richard"
- admin opens space

GET `https://localhost:9200/graph/v1.0/me/drives?%24top=0&%24skip=0&%24orderby=name+asc&%24filter=driveType+eq+project`

richard still as member:
![Screenshot 2022-08-24 at 16 57 29](https://user-images.githubusercontent.com/84779829/186452429-339c3958-d310-4d98-8f0f-2bc4ce135b66.png)

- admin opens members

web try to call deleted richard and get 502 GET `https://localhost:9200/graph/v1.0/users/932b4540-8d16-481e-8ef4-588e4b6b151c?%24select=&%24expand=drive`

we haven't on the web no link no user einstein and cannot add new user member: 
![Screenshot 2022-08-24 at 17 03 55](https://user-images.githubusercontent.com/84779829/186453956-46573555-ffd8-46e4-b406-1988adab251e.png)

related https://github.com/owncloud/ocis/issues/903

**Comment by kulmann** [comment]
Moved to web repo, as recommended by @dragonchaser

**Comment by ScharfViktor** [comment]
the same behavior when deleting a group (just to know when fixing bug)

**Comment by kulmann** [comment]
Has been fixed via https://github.com/owncloud/web/pull/8336 - we're omitting the deleted users and groups in the member list now.
