### ISSUE TITLE
[oc10] Trashbin is visible after disabling `Deleted Files` in oC10 backend

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#8017]
### Steps to reproduce
1. Disable the `Deleted Files` app

### Expected behaviour
Like in ownCloud 10 UI also Web should not show the `Deleted Files` menu entry anymore

<img width="256" alt="image" src="https://user-images.githubusercontent.com/33026403/203636603-ccb98584-b5e9-44a4-93e0-668410bf6544.png">

### Actual behaviour
In ownCloud Web the `Deleted Files` menu entry is still there. Deleting files works as expected - no files go into the trashbin.

<img width="244" alt="image" src="https://user-images.githubusercontent.com/33026403/203636885-ca57f2ed-95c7-44ce-b728-769e586c4d8a.png">

### Environment ownCloud Core
**Version:** (see ownCloud admin page)
10.11

**Comment by tbsbdr** [comment]
considering as p4 as its oc10 related and deviation from default setting (-> cornercase)
