### ISSUE TITLE
Empty sidebar when opening a space from search results

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#8034]
ownCloud Web UI 6.0.0-rc.8
Infinite Scale 2.0.0-rc.2 Community 

Step: 
- admin creates project space "new"
- admin goes to "personal" and tries to find project space by name "new"
- admin opens "new" space via search result
- admin tries to open `details` or `members`:

Expected: sidebar is not empty
Actual: message: sidebar is empty and message: "Select a file or folder to view details" 

https://user-images.githubusercontent.com/84779829/204304347-9a18c472-d962-45a0-9ddf-7271c20f204d.mov

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/8045.
