### ISSUE TITLE
Spaces: Enable sharing with groups

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#8035]
### Steps to reproduce
1. Login as user with the role "Space Manager"
2. Try to share a whole Space with a group
3. Sharing a Space with a group is not possible

### Expected behaviour

- Sharing with a group should be possible

### Actual behaviour

- Sharing a Space with a group is not possible

**Comment by kulmann** [comment]
current state: not possible backend side. I suppose allowing groups as members creates too much potential for conflicts in deduplication and auto-guessing the resulting membership role.

**Comment by tbsbdr** [comment]
CC @hodyroff 👆

**Comment by JammingBen** [comment]
This has been tackled via https://github.com/owncloud/web/pull/8161.
