### ISSUE TITLE
share receiver with permission "viewer" does not get any error message when trying to restore a version

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#8037]
### Steps to reproduce
1. As Alice upload a file called 'file.txt'
2. As Alice overwrite the file called 'file.txt' with different content
3. As Alice share the file to Brian with the permissions 'Viewer'
4. As Brian accept the file
5. As Brian try to restore the old version of the file

### Expected behaviour
Ether of:
1. Brian should not see the buttons to restore an old version
2. Brian should see a proper error message why the restoring did not work

### Actual behaviour
COPY operation fails with 403 but no error message is shown to the user

### Environment general
**Operating system**:
Ubuntu
**Backend (ownCloud Core or Infinite Scale)**:
ocis
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
### Environment ownCloud Infinite Scale
**Version:**
2.0.0-rc.2
**Updated from an older Infinite Scale or fresh install:**
fresh
**Where did you install Infinite Scale from:**
GitHub
#### Browser log
![image](https://user-images.githubusercontent.com/2425577/204464390-e8a371ed-e7c6-40ce-a4ed-5687ca5c0872.png)

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/8040.
