### ISSUE TITLE
 large size file can't be opened in text-editor

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#8038]
### Steps to reproduce
1. Upload a file `large.txt` of size greater than `10 GB`
2. After the file upload is complete, open the file in **text-editor** 

### Expected behaviour
**The file should be open in text-editor or some message like `large size file can't be opened` should be displayed**

### Actual behaviour
**Reload animation is displayed on the text-editor page** 

![reload](https://user-images.githubusercontent.com/54478846/204462590-a70fed3b-d821-436b-8d22-9f3a61abdeb8.jpeg)

### Environment general
**Operating system**: Ubuntu 22.04 LTS

**Backend (ownCloud Core or Infinite Scale)**: ocis

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:**  v2.0.0-rc.2

**Updated from an older Infinite Scale or fresh install:** fresh install

**Where did you install Infinite Scale from:**

### Client configuration
**Browser:** Version 107.0.5304.121 (Official Build) (64-bit)

**Operating system:** Ubuntu 22.04 LTS

**Comment by JanAckermann** [comment]
Hm, generally this is the same behavior as in most OSs, the system freezes :D
@kulmann something we should tackle anyways?

**Comment by kulmann** [comment]
Wouldn't treat this as a bug for the very reason @JanAckermann stated.

Idea for improvement: when the text editor is opened with a file size above a certain threshold (no idea, really... my IDE warns for files above 4 MB I think) we could show a modal, warning the user that the app might not be able to handle the file size, giving the options to proceed anyway or to exit the editor (same as the normal "close" action in the editor, going back to the location the user came from via `closeApp` from appNavigation composable).
