### ISSUE TITLE
Search result message "No results" keeps duplicating

### ISSUE THREAD

**Issue by lookacat** [owncloud/web#8054]
![bug](https://user-images.githubusercontent.com/786551/205061860-2b7de7f4-4a36-425c-bb6c-32f0409a5741.png)

### Steps to reproduce
1. Search `keine`
2. Wait a little bit
3. Search `keine ergebnisse`

### Expected behaviour
Only one message string displayed

### Actual behaviour
Message multiplies with each search

**Comment by kulmann** [comment]
Fun stuff. This only happens when the search term is part of the `No results / Keine Ergebnisse` string. 😆

**Comment by lookacat** [comment]
Lol, i will look into it tomorrow

**Comment by kulmann** [comment]
Has been solved via https://github.com/owncloud/web/pull/8062
