### ISSUE TITLE
Issue when running `web` with vite & local oCIS binary

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#8086]
Not sure whether it is expected to be running the `web` repo with dockerized backends for development, however I just noticed using things the way I was used to (`pnpm build:w` and `(env vars) ./bin/ocis start`) doesn't work anymore, since both `vite.config.ts` and `config/vite_ocis/config.json` use `host.docker.internal` URLs, and now the IDP/oidc is broken.

### Expected behaviour
"Web & local oCIS binary" work out of the box

### Actual behaviour
Not obvious how/if the "web & local oCIS binary" combination works

**Comment by pascalwengerter** [comment]
As requested by @dschmidt I start oCIS via `WEB_ASSET_PATH=../../web/dist WEB_UI_CONFIG=../../web/dev/docker/ocis.web.config.json OCIS_INSECURE=true IDM_CREATE_DEMO_USERS=true OCIS_URL=https://host.docker.internal:9200 ./bin/ocis server` (assuming both repos are located in the same parent dir)

**Comment by JammingBen** [comment]
You need to run oCIS with an additional `OCIS_CORS_ALLOW_ORIGINS=https://host.docker.internal:9201`. Furthermore the web IDP config is needed in oCIS: `cp ~/path_to_your_web/dev/docker/ocis.idp.config.yaml $HOME/.ocis/config/idp.yaml`.

Please re-open or send me a message if it's still not working properly 🙂
