### ISSUE TITLE
[e2e-test] sometimes the upload.feature crashes in the oc10

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#8087]
Sometimes test fails. https://drone.owncloud.com/owncloud/web/30533/11/17 

I could not reproduce it locally 

npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/30533/tracing/upload-resources-in-personal-space-alice-2022-12-8-10-26-09.zip

I see wrong behavior oc10 when we:
- create folder
- create file inside of the folder
- goto(startUrl) - !! here is bug 

![Screenshot 2022-12-08 at 18 41 50](https://user-images.githubusercontent.com/84779829/206525314-36e23010-79db-4680-a148-8f441a5403b7.png)

- Here we create the folder "PARENT" again.  but we get 405 because folder exist 
![image](https://user-images.githubusercontent.com/84779829/206525847-88f479b1-d72f-4291-82cd-ba0c3b813b48.png)

**Comment by grgprarup** [comment]
Failed on today's nightly https://drone.owncloud.com/owncloud/web/30765/9/16
