### ISSUE TITLE
Idea: Provide ownCloud-web specific type interfaces

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#8089]
When working on the ownCloud codebase(s), I've often looked into the fixtures/mocks (which may soon get deleted in #8088) to figure out what properties the commonly used files/resources/shares (receiving, pending, outgoing, ...)/users/spaces/... have. Wouldn't it be, esp. in the recent shift to mainly working in TypeScript, useful to add an ownCloud directory to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types which would make those tyoes importable via `@types/owncloud-web` (or similar)?

**Comment by dschmidt** [comment]
Our internally used types should get better, yes. 

Types especially useful for external devs are slowly moving to web-client and web-pkg, which we are going to publish as independent packages at some point (hopefully rather sooner than later). 

So not sure what we would be publishing at DefinitelyTyped

**Comment by pascalwengerter** [comment]
Up for discussion, feel free to close if you deem what exists in web-client/web-pkg is enough :) the nice thing about DefinitelyTyped is that publishing is being taken care of by them (plus it feels a bit more official I guess, but not necessary ofc)

**Comment by dschmidt** [comment]
To me that's usually just a crutch if packages don't come with their own types. Always possible that types lag behind etc

**Comment by pascalwengerter** [comment]
I've used some of the existing ones in a refactoring of #7991 now, closing this issue as not relevant (at least for now). Thanks!
