### ISSUE TITLE
 click on the 'All files' or 'Personal' dropdown menu doesn't open a drop down in iphone resolution

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#8092]
### Steps to reproduce
1. Login as a user 
2. set the resolution to `375x812`
3. click on `All files` drop down menu or `Personal` (on ocis)

### Expected behaviour
A drop-down menu should be revealed with the option to navigate to different pages 

### Actual behaviour
No menu is revealed

https://user-images.githubusercontent.com/41103328/206649094-82dee3a2-2215-460f-8e6c-8b4090755c05.mp4

### Environment
Web with oc10 started with docker compose 
THe behaviour is same with `ocis` backed as well

**Comment by ScharfViktor** [comment]
same existing issue: https://github.com/owncloud/web/issues/7253

**Comment by SwikritiT** [comment]
closing this in favour of https://github.com/owncloud/web/issues/7253
