### ISSUE TITLE
Even out acceptance test pipeline run durations

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#8115]
Checking https://drone.owncloud.com/owncloud/web/30730/15/19 I can spot one pipeline that is (also in more cases) running for ~25min, and a rough 5-7min longer than the next-longest (~18min) of the other 20 (oCIS) and 42 (oC10) pipelines.

Ideally, the tests can be more evenly distributed to reduce the acceptance test duration to <20min

**Comment by kulmann** [comment]
Would be greatly appreciated!

**Comment by amrita-shrestha** [comment]
After the copying test cases has been copied to ocis in this issue https://github.com/owncloud/ocis/issues/5094. We can continue with this issue

**Comment by phil-davis** [comment]
> After the copying test cases has been copied to ocis in this issue [owncloud/ocis#5094](https://github.com/owncloud/ocis/issues/5094). We can continue with this issue

@amrita-shrestha this issue is in web, so I think it can be done any time that someone is available - it can bt does not have to wait until after ocis API test restructuring.
