### ISSUE TITLE
[Bug] Name of deleted folder should be placed in quotation marks

### ISSUE THREAD

**Issue by d7oc** [owncloud/web#8122]
### Steps to reproduce
1. Switch language to German
2. Create a folder "Testordner nicht"
3. Delete the folder

### Expected behaviour
It should be clearly visible which folder name would be deleted

### Actual behaviour
<img width="518" alt="Screenshot 2022-12-15 at 17 43 09" src="https://user-images.githubusercontent.com/102977884/207928155-9f20a7f7-e673-4cb4-8679-1979fa1f3dfc.png">
You cannot differentiate the folder name. Would it be the "Testordner" which will not be deleted or the folder "Testordner nicht" which will be deleted? It would be beneficial to have quotation marks around the folder name

### Environment general
Everything was tested on  https://web.cloud.owncloud.com

**Comment by dschmidt** [comment]
If the translation needs to be changed anyway, I would argue the folder name should be put in the main text (in quotes of course) and possibly removed from the title


@tbsbdr thoughts?
