### ISSUE TITLE
[FR] Use Clipboard API instead of Document.execCommand for Clipboard Actions

### ISSUE THREAD

**Issue by d7oc** [owncloud/web#8134]
Currently the JavaScript Code uses the follow module: https://www.npmjs.com/package/copy-to-clipboard. This module uses https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand# under the hood which is not working properly on e.g. Safari as the user is just presented a popup to copy the link himself.

Meanwhile there is a Clipboard API which is also supported on Safari, see comparison in https://www.w3docs.com/snippets/javascript/how-to-copy-the-text-to-the-clipboard-with-javascript.html.

This feature request is to replace the module and use one with uses the Clipboard API under the hood to support all browser properly with working Clipboard interactions.

**Comment by pascalwengerter** [comment]
@JammingBen I guess you can close this as completed via #8173 ? :)
