### ISSUE TITLE
Fix acceptance tests with new v-calendar

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#8151]
In https://github.com/owncloud/web/pull/8128 we updated to a new major version of v-calendar and while it seems to work just fine when testing it manually, the acceptance tests are broken - so we skipped them for now.

It would be great if the QA Team could properly fix it.
Thanks in advance!

See commit "Skip expiration date picker acceptance test as it's broken with the n…" - currently it is https://github.com/owncloud/web/pull/8128/commits/932c4082fd723af2afb7b8997f44e7b75ef4af9d here but we are rebasing constantly, so possibly not for long.

**Comment by phil-davis** [comment]
@amrita-shrestha @SagarGi please get someone to sort this out.

**Comment by dschmidt** [comment]
We made the OcDatepicker component instance available on the DOM Element to be able to fix the `move` invocation, (as you can see in the referenced commit and the one before) but to be honest I would prefer if we could get rid of that and internal api usage all together. 

As it's used in one acceptance test only, it shouldn't be too much of a performance problem I hope. Moreover we fixed the infamous December issue recently, which should be included in the v calendar version used in the PR, so we can get rid of that extra code path as well

**Comment by dschmidt** [comment]
There's also an e2e Test which uses the same more or less internal api, up to you but it might be worth porting the acceptance test over and fixing it just once

**Comment by saw-jan** [comment]
The problem with the failing acceptance test `webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:11` is that whenever the test tries to click the year `2038`, it will click the year `2035` (just above it). This is due to the scrolling-back issue that we have raised earlier here https://github.com/owncloud/web/issues/7513

**Comment by saw-jan** [comment]
Changing the test code will only make the tests pass for a certain period of time.
The tests should work nicely with the new v-calendar if that scrolling issue is fixed soon. Should we close this issue here?
Or any thoughts? @dschmidt

**Comment by saw-jan** [comment]
I will post the current (master) and new (vue3-compat-ng) scrolling behavior of the calendar.
I see some difference

**Comment by dschmidt** [comment]
Ok, cool. 

If it's just a test issue I'd be happy if we could get a temporary fix which won't make the scope of the PR much bigger, as it's really hard to review already

**Comment by dschmidt** [comment]
Let's fix it properly in a follow up maybe?

**Comment by saw-jan** [comment]
> I will post the current (master) and new (vue3-compat-ng) scrolling behavior of the calendar.
I see some difference

I think the behavior is the same on both. The only difference is the calendar size due to which the test is passing on master but not in `vue3-compat-ng` branch.

Master:

https://user-images.githubusercontent.com/52366632/209666668-8020966a-5f3d-47ca-92ba-7db84d5eeab3.mp4

vue3-compat-ng:

https://user-images.githubusercontent.com/52366632/209666642-3d60f5c0-cc25-4764-ae81-c86891bfd145.mp4

> If it's just a test issue I'd be happy if we could get a temporary fix which won't make the scope of the PR much bigger, as it's really hard to review already

Maybe we can adjust the date as of now.

CC @dschmidt @phil-davis

**Comment by saw-jan** [comment]
> Maybe we can adjust the date as of now.

But we also want to be sure that the issue with auto-scroll is caught

**Comment by phil-davis** [comment]
> Maybe we can adjust the date as of now.

yes, adjust the future date to some closer date that does not cause this known date-picker problem. The test scenario is just testing that the expiration date of a public link share can be adjusted.

The dates currently chosen are after the date for the https://en.wikipedia.org/wiki/Year_2038_problem and so they are checking that the software does not have this future problem. But I don't think that we need to be doing that specifically in a test like this. We can easily add specific "year 2038" test scenarios as a separate thing some time in the future.

**Comment by saw-jan** [comment]
Can this be closed now?
CC @phil-davis @dschmidt

**Comment by phil-davis** [comment]
Yes - closing. The "year 2038" is a different thing, and we are some way off from rushing to test that everywhere just yet!
