### ISSUE TITLE
Extended support for localization languages

### ISSUE THREAD

**Issue by Pro100x3mal** [owncloud/web#8155]
Please expand support for different languages.  At least at the level of ownCloud classic.  Is it planned to add the Russian language?

**Comment by tbsbdr** [comment]
hey @Pro100x3mal currently russian transations are not in scope.
most translations are done by community especially when it comes to languages that are not spoken by the web team.
We have a coverage of 11% translated russian strings which is not enough to be enrolled in the language selection - but someone already started to translate to russian =)

translations are currently done via transifex, feel free to contribute👍

![screenshot_000153](https://user-images.githubusercontent.com/26610733/209825081-8bc1670b-6d55-4875-a917-9eedc1ff3a59.png)

**Comment by kulmann** [comment]
We check the translation coverage in transifex from time to time. Russian is at 54% at the moment. If you manage to reach 70% you can reopen here and ping me, then I'll happily add Russian to the bundle. :-)

**Comment by kulmann** [comment]
https://app.transifex.com/owncloud-org/owncloud-web/languages/
