### ISSUE TITLE
Search icon overlap in search bar

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#8158]
### Steps to reproduce
1. Open the web 

### Expected behaviour
search icon should not overlap text "Enter search term"

### Actual behaviour
![searchicon](https://user-images.githubusercontent.com/54478846/209764603-74535893-37d6-4faf-8724-e5dfc61de1f1.png)

### Environment general
**Operating system**: ubuntu

**Backend (ownCloud Core or Infinite Scale)**: both master branch

### Log
``` console
index.html#/oidc-callback? 
code=GS5Ke9OMXLsKLiJh0YHVfIeWTsdlsI9Zmv7SgVy0gTkt5PtFQ8EJox7L0cp50aQF&state=29781b5beff543558a7b39f9240517c2:1 Refused to apply style from 'http://host.docker.internal:8080/index.php/apps/web/index.html' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by kulmann** [comment]
Saw the same, with 'pnpm build' it is like in the screenshot, with 'pnpm vite' is displayed correct. Probabl some broken style import... didn't have the time, yet, to check it out myself.

**Comment by amrita-shrestha** [comment]
while we create a folder then a successful message popup in the down-left corner in `pnpm-vite` and at top in `pnpm build`. I think this is also related to the production build issue too.

**Comment by kulmann** [comment]
> while we create a folder then a successful message popup in the down-left corner in `pnpm-vite` and at top in `pnpm build`. I think this is also related to the production build issue too.

That's actually part of the dockerized dev setup. `pnpm vite` doesn't stick to that. `pnpm build` does, so that everything is displayed the same way as in CI (make e2e/acceptance test debugging easier).
