### ISSUE TITLE
[web] Explain what Spaces are

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#8163]
**Please track times**

## Current
- currently there is not hint what Spaces are and what this section differentiates from Personal:
<img width="1693" alt="screenshot_000161" src="https://user-images.githubusercontent.com/26610733/209829980-a78dac91-0851-444b-ae8d-3936e46cc7b3.png">

## Expected
Add a contextual helper to explain what Spaces are.
Helper text:

> **Learn about Spaces**
> 
> Spaces are special folders built for collaboration.

**Feedback welcome!**

- hide entirely if batch actions are visible / items are selected
- ~hide the label (only show the `?` icon) in mobile viewports~ Decided with stakeholders against it, as the lonley icon would look out of place 

![screenshot_000156](https://user-images.githubusercontent.com/26610733/209830161-81a65c57-b941-4842-9afb-5d40c4bd73a7.png)
![screenshot_000159](https://user-images.githubusercontent.com/26610733/209830163-8ac840d2-9d9f-4969-8031-79799b9f4b68.png)

**Comment by tbsbdr** [comment]
idea: 
- place only the "?" (without text "learn more about spaces") directly behind "Spaces" in Breadcrumb
`Spaces ?`
- "?" is only visible in Space root (if you navigate down, "?" disappears)

**Comment by hurradieweltgehtunter** [comment]
Proposal: Include a (?) Icon on each page (Personal, Shares, Spaces, Trashbin) on the top right corner (besides cog wheel and show/hide sidebar icon) to explain each page.

(?) on Personal -> show infos about the "personal" page
(?) on Shares -> Show infos about the "Shares" page 
etc.

Advantage:
- all pages are explained in-app
- consistent position for help icon

**Comment by tbsbdr** [comment]
updated initial comment with a shorter context-helper text.
