### ISSUE TITLE
Unwanted Share receivers list shows up

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#8167]
### Steps to reproduce
1. User 'Alice' create two folders `sharewithadmin` and `folder1`
2. `Alice` share folder `sharewithadmin` with user admin
3. `Alice` click the `sharewithadmin` checkbox and click `folder1` checkbox
4. `Alice` click `Add people` quick action collaborator
 
![Screenshot from 2022-12-29 13-58-05](https://user-images.githubusercontent.com/54478846/209923236-82e996c0-09c7-495e-8f19-0f53823e707d.png)

5. Alice searched `admin` user to share then suggestion doesn't contain admin user

**Note**:  first shared resources should be checked. If we change the order i.e first we click `folder1` and later `sharewithadmin` then it works fine
### Expected behaviour
Shared with admin  should not be displayed and `admin` user option should be available when searched

### Actual behaviour

![Screenshot from 2022-12-29 13-58-34](https://user-images.githubusercontent.com/54478846/209923444-d6016dbf-e7ec-4cbc-8466-890e78e35b6b.png)

![Screenshot from 2022-12-29 14-11-01](https://user-images.githubusercontent.com/54478846/209924836-5202db13-28d7-493b-81a9-aca153c3837e.png)

### Environment general
**Operating system**: ubuntu22

**Backend (ownCloud Core or Infinite Scale)**: both

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Core

**PHP version:** 7.4

**Version:** (see ownCloud admin page)  10.11.0.6

**Updated from an older ownCloud or fresh install:** fresh 

**Where did you install ownCloud from:** github

### Environment ownCloud Infinite Scale
**Version:** latest

**Updated from an older Infinite Scale or fresh install:** fresh

**Where did you install Infinite Scale from:** github

Note: pnpm build is used to build web

**Comment by JammingBen** [comment]
@amrita-shrestha Could you please re-test if you can still reproduce the error on current master? Because I can't, maybe it has been fixed via https://github.com/owncloud/web/pull/8349.

**Comment by amrita-shrestha** [comment]
issue has been resolved so closing this issue
