### ISSUE TITLE
[oC10] Sidebar remain open in oc10

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#8172]
### Steps to reproduce
1. User creates file `Photo/Portugal.jpg` 
2. User copies URL of file page `http://host.docker.internal:8080/index.php/apps/web/index.html#/files/spaces/personal/admin?sort-dir=desc&items-per-page=100&view-mode=resource-table&fileId=6`
![Screenshot from 2023-01-02 14-59-55](https://user-images.githubusercontent.com/54478846/210212578-8d95f712-653f-497b-813c-6e629cf3dbf4.png)

3. User open sidebar panel for file `Photo/Portugal.jpg` 
4. Then paste the URL `http://host.docker.internal:8080/index.php/apps/web/index.html#/files/spaces/personal/admin?sort-dir=desc&items-per-page=100&view-mode=resource-table&fileId=6`
![Screenshot from 2023-01-02 15-02-17](https://user-images.githubusercontent.com/54478846/210212693-dae70275-5e35-478f-b10a-dde0df41b9c0.png)

### Expected behaviour
sidebar panel should be closed

### Actual behaviour

![openedsidebar](https://user-images.githubusercontent.com/54478846/210212400-6a76bab0-a52c-411e-8852-1f8891d2793c.png)

### Environment general
**Operating system**: ubuntu

**Backend (ownCloud Core or Infinite Scale)**: oc10

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:** master

**Updated from an older Infinite Scale or fresh install:** fresh

**Where did you install Infinite Scale from:** github

### Environment ownCloud Core
**Web server:** web

**PHP version:** php7.4

**Version:** (see ownCloud admin page) master
 
**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** github

**Comment by JanAckermann** [comment]
Closing as OC10 Support has been discontinued with version 7.1.0
