### ISSUE TITLE
Display remaining time on link shares with expiration date

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8211]
It would be nice to have a little indicator showing how much time is left until a share expires.

![grafik](https://user-images.githubusercontent.com/16665512/211812548-8e1f2a5d-15b0-49ca-adfc-dc0a5e6e2c9a.png)

**Comment by kulmann** [comment]
Will be removed again in https://github.com/owncloud/web/pull/8965 as the role labels are much longer now and the space is insufficient to display such a hint. The calendar icon has a tooltip with the corresponding text. Sufficient for now.

**Comment by hurradieweltgehtunter** [comment]
IMO we need to have a concept rework of the whole sharing dialog in the right sidebar. Too many "fixes" which get reverted.

**Comment by tbsbdr** [comment]
> Too many "fixes" which get reverted.

which ones?

**Comment by kulmann** [comment]
> why is the private link not available anymore but for example iOS and desktop still uses them ...

That one is by design. Private link is not a good user facing concept. But it's a good thing for client-to-client handover. Nothing wrong with that.

**Comment by kulmann** [comment]
> > > why is the private link not available anymore but for example iOS and desktop still uses them ...
> > 
> > 
> > That one is by design. Private link is not a good user facing concept. But it's a good thing for client-to-client handover. Nothing wrong with that.
> 
> iOS lets me use the private link, too.

That's not intended and will be fixed at some point.
