### ISSUE TITLE
Copy and paste values to user dialog leads to error message

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#8225]
### Steps to reproduce
1. Create a new user
2. Paste a password to the password field

### Actual behaviour
<img width="497" alt="image" src="https://user-images.githubusercontent.com/33026403/212195088-c658766b-4685-4c38-9389-49c99c02eaec.png">

**Comment by ChrisEdS** [comment]
Another weird behaviour in that context:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/33026403/212195543-6c31bfd1-90d9-4ff0-935a-36ca666ed810.png">

**Comment by dschmidt** [comment]
Which version are you using?

**Comment by ChrisEdS** [comment]
I'm on `latest` ownCloud Web UI 7.0.0-rc.6
