### ISSUE TITLE
Return on keyboard should be seen as "ok"

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#8226]
### Steps to reproduce
1. Create a new folder
2. Give the folder a name
3. Hit enter

### Expected behaviour
The folder will be created 

### Actual behaviour
I have to manually hit the create button

Enter should be seen as ok in all scenarios, creating new users, delete files and so on. This would speed up the workflow when using the web client.

**Comment by kulmann** [comment]
Already on it. Broke with the vue3 (compat) update unfortunately. Thanks for reporting!

**Comment by kulmann** [comment]
It applies to all modals by the way. Not only to folder creation.

**Comment by ChrisEdS** [comment]
Yes, absolutely - I picked the folder creation as example. Thanks for taking care! <3

**Comment by JammingBen** [comment]
Seems to be fixed with the recent upgrade to Vue 3 and its related changes.
