### ISSUE TITLE
Space member editor/viewer has available buttons for editing the space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#8251]
Infinite Scale 2.0.0+eb33e9152 Community 
 ownCloud Web UI 7.0.0-rc.6 
docker 

Steps:

- admin creates space and shares space to einstein as viewer or editor
- einstein opens space and go to context menu
 
Expected result: for viewer or editor buttons `rename` `edit subtitle` `disable` `edit quota` aren't available

Actual: if user clicks buttons ->he get 403 (correct from backend side)
![Screenshot 2023-01-16 at 14 57 46](https://user-images.githubusercontent.com/84779829/212712868-9fcfe4d7-cc8a-40c8-bc2f-4c2a69b7032a.png)

cc @ChrisEdS

**Comment by ChrisEdS** [comment]
Thank you very much @ScharfViktor
