### ISSUE TITLE
Reusage of web components in extensions limited

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#8281]
Background: 
Developing feature rich extensions like backups extension that lists backup resources similar to web-app-files

Issue:
A lot of components from web-app-files are needed for the extension: ResourceTable, AppBar, breadcrumbs, useSort, useResourcesViewDefaults etc.
According to @dschmidt reusage of components from web can only be done from web-pkg and web-client. Moving all of these components would require also moving of their imported components, almost the whole web-app-files.

Keeping the extension inside of the web is long term also a bad solution as changes in imports would cause a lot of effort in maintainability

**Comment by dschmidt** [comment]
As responded later to you in chat (when you probably already called it a day) we need to hear more explicit use cases and what exactly you want to achieve. 


If you give us more details about what exactly you want to achieve, we can help laying out an architecture.

**Comment by pascalwengerter** [comment]
@kulmann from a cursory read it seemed like there has been basically a re-implementation of the ResourceTable for spaces in the admin-app recently, moving ResourceTable (and potentially ResourceTiles also 😇 ) to the `web-pkg` could both resolve that, force the project to move away from some mixins/`web-app-files`-internal APIs towards more open ones and address parts of this ticket?

**Comment by elizavetaRa** [comment]
@dschmidt We want to be able to reuse things from `web-app-files` in external extensions. The extensions should be able to import from a certain web version and don't break when there are modifications of reused components. 

Example: backups extension that has a logic, similar to `web-app-files`: reuses ResourceTable, breadcrumbs, actions, useResourcesViewDefaults [etc.](https://github.com/cernbox/web/blob/88fa97b0d327a3d0a392d60bf1a2f7b4f67d27c6/packages/web-app-backups/src/components/BackupsSection.vue#L104) but it's reachable from ApplicationSwitcher and has own endpoints and loadResourcesTasks.
![Screenshot from 2023-01-25 11-16-04](https://user-images.githubusercontent.com/7430156/214537492-53344ed7-367b-4d69-8e70-6a98d55ee03f.png)

As I understand, the only way would be to move needed components to `web-pkg`, but this is a large part of `web-app-files` as components have their own imports from `web-app-files`. For now, we keep the extension internally in our web fork, but on upstream rebases it breaks and needs fixes.

**Comment by kulmann** [comment]
@elizavetaRa @diocas can we close this issue as superseded by https://github.com/owncloud/web/issues/9267 ? 🤔 or do you have requirements for component reusability in other cases as well?

**Comment by diocas** [comment]
ping @elizavetaRa 
Please re-open if there are more requirements.
