### ISSUE TITLE
`Context menu` is not shown for declined share on `stable-6.0`

### ISSUE THREAD

**Issue by SagarGi** [owncloud/web#8286]
### Description
A user sends a multiple shares to another user, then the received user accepts all the shares. And when the user declines one of the share and then tries to open the `context menu` for the declined share then the UI does not shows the `context menu`

### Steps to Reproduce
1. create `user1` and `user2`
2. `user1` creates folder to share `folder1` and  `folder2`
3. `user1` shares both folders to `user2`.
4. `user2` accepts both shares
5. Then `user2` declines one of the share

Now , Try to accept the  declined share with context menu (actions)

### Expected Behaviour
***On master branch with ocis-master branch***

https://user-images.githubusercontent.com/46086950/213683251-8e3eca4f-0797-449b-a4d4-2cc931b63c80.mp4

### Actual Behaviour
***On stable-6.0 branch with ocis-stable-2.0 branch***

https://user-images.githubusercontent.com/46086950/213683379-b83cee49-810b-4a48-9069-81c4183998aa.mp4

**Comment by SagarGi** [comment]
https://drone.owncloud.com/owncloud/web/31908/12/12Failure is seen in drone

**Comment by SagarGi** [comment]
@kulmann @ScharfViktor this is seen on `stable-6.0` but not on `master` branch.

**Comment by JanAckermann** [comment]
not reproducible, closing
