### ISSUE TITLE
OCIS: Inactive navigation items in Settings menu invisible when in light mode

### ISSUE THREAD

**Issue by mdusher** [owncloud/web#8290]
### Steps to reproduce
1. Login to OCIS
2. Go to the user menu in the top right and select "Settings"
3. If in Dark mode, switch to Light mode
4. The inactive option in the left side navigation will have white text and be invisible.

### Expected behaviour
Inactive options should be visible to the user

### Actual behaviour
The inactive option has white text on a white background and appears invisible when in light mode
![image](https://user-images.githubusercontent.com/3529874/213944661-c8f2498f-30b4-4faf-8b70-77b055197ed0.png)

### Environment general
Tested using https://ocis.ocis-web.latest.owncloud.works/

**Comment by JammingBen** [comment]
Thanks for the report! We plan to move the language select to the account page and remove the settings app completely, as we don't use it anymore (https://github.com/owncloud/web/pull/8294).
