### ISSUE TITLE
[Vue 3 follow-up] Get ODS docs running again

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#8302]
The ODS docs are currently broken due to the Vue 3 upgrade.

* [ ] Check if upgrade of `vue-style-loader` is necessary
* [ ] Check if upgrade of `vue-styleguidist` is necessary
* [ ] Update all docs inside the components to work with Vue 3

**Comment by dschmidt** [comment]
... and with TypeScript

**Comment by JammingBen** [comment]
Closing in favour of https://github.com/owncloud/web/issues/10233.
