### ISSUE TITLE
[stable-6.0] Acceptance test not running on nightly

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#8312]
The acceptance tests are not running on `nightly` for `web stable-6.0`.
Latest Build: https://drone.owncloud.com/owncloud/web/32071
1-month previous Build: https://drone.owncloud.com/owncloud/web/30930

@ScharfViktor @micbar Is this intended or not?

**Comment by ScharfViktor** [comment]
I think Benedikt already tried to configure it https://github.com/owncloud/web/pull/8048
It seems that somewhere there is no trigger for the night start. if you know where to fix it please fix it

**Comment by phil-davis** [comment]
![Screenshot 2023-01-25 at 15-36-47 Settings - owncloud_web - Drone CI](https://user-images.githubusercontent.com/1535615/214532267-454ff2f3-008e-47cb-b314-1e825e5607d9.png)

There is a drone "cron" job. It does run: https://drone.owncloud.com/owncloud/web/32071

It only runs the e2e tests.

Do we want to also run the "old" nightwatch acceptance tests in nightly on stabale-6.0?

**Comment by ScharfViktor** [comment]
I think so. it won't be superfluous

**Comment by grgprarup** [comment]
Implemented here https://github.com/owncloud/web/pull/8315, so closing.
