### ISSUE TITLE
[oC10] Switching users with owncloud web enabled, log into previous session of other user (sessionOCPassPhrase issue?)

### ISSUE THREAD

**Issue by Radstake** [owncloud/web#8321]
### Steps to reproduce
1. Log in as user A with TOTP enabled
2. Logout
3. Login in as user B with TOTP enabled
4. redirected via Owncloud Web (trusted or not trusted enabled)
5. Ends up in old session of user A

**cookie: sessionOCPassPhrase seems the issue, when removed it works ok**

### Expected behaviour
Login as user B

### Actual behaviour
Hijacking wrong session

### Environment general
Debian 10

**Backend (ownCloud Core or Infinite Scale)**:
ownCloud Core

**Database:**
10.3.36-MariaDB-0+deb10u2 - Debian 10

**PHP version:**
7.4.33

**Version:** (see ownCloud admin page)
10.11.0.6

**Comment by Radstake** [comment]
This seems quite serious... hope there will be a follow up soon.....

**Comment by DeepDiver1975** [comment]
I assume you are referring to the cookie `oc_sessionPassphrase` ?

**Comment by DeepDiver1975** [comment]
Can you please double check if the cookie value changes after logout?

**Comment by Radstake** [comment]
Hi thats indeed the one. The cookies doesn't change after login, that we when signing in with another account, it still redirects and log in with the previous one. Only when removing the cookie, login with the new one is possible.

**Comment by DeepDiver1975** [comment]
> Hi thats indeed the one.

:+1: 



> The cookies doesn't change after login

we change the cookie after logout - please compare the values in your setup.
I am also wondering if there are any log messages during logout.

**Comment by Radstake** [comment]
> > Hi thats indeed the one.
> 
> 👍
> 
> > The cookies doesn't change after login
> 
> we change the cookie after logout - please compare the values in your setup. I am also wondering if there are any log messages during logout.

Sure thing, will do and come back on it.
