### ISSUE TITLE
Change the color of the header

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#8332]
### Actual behaviour
I try to change the color of the header, but I can't find a design token for doing this task.

Can you point me to the solution?

**Comment by pascalwengerter** [comment]
@ChrisEdS what I guess you're looking for (not sure what `header` is pointing at exactly) is https://github.com/owncloud/web/blob/62650af88a6815ba190239281717576981c472c1/packages/web-runtime/src/App.vue#L217, so `--oc-color-swatch-brand-default`?

**Comment by ChrisEdS** [comment]
That did the trick, thank you!

**Comment by kulmann** [comment]
> That did the trick, thank you!

That changes the color of other elements as well. Did you want to change the **top bar color only** or did you achieve what you wanted?

**Comment by ChrisEdS** [comment]
Yes, that changes other elements like the the header color of the modals, but I'm fine with that. But what I initially wanted was to change the color of the header and the color of the background. 

<img width="526" alt="image" src="https://user-images.githubusercontent.com/33026403/215598447-63b334ad-a5a8-4fb3-8bd4-ffe2ddbbff98.png">

**Comment by pascalwengerter** [comment]
> > That did the trick, thank you!
> 
> That changes the color of other elements as well. Did you want to change the **top bar color only** or did you achieve what you wanted?

But that's also the idea behind having the design system/some concept behind the theming instead of offering 2.623 different properties ;)

**Comment by pascalwengerter** [comment]
> Yes, that changes other elements like the the header color of the modals, but I'm fine with that. But what I initially wanted was to change the color of the header and the color of the background.
> 
> <img alt="image" width="526" src="https://user-images.githubusercontent.com/33026403/215598447-63b334ad-a5a8-4fb3-8bd4-ffe2ddbbff98.png">

Just make sure to check the contrasts, IIRC the swatch-brand-default is supposed to be quite dark and then works with bright text (so you'd need to update the text color for brighter colors to something darker)

**Comment by ChrisEdS** [comment]
Contrast looks fine to me

<img width="512" alt="image" src="https://user-images.githubusercontent.com/33026403/215599632-cd242d7d-ceca-4bb0-8814-7c5789d9673f.png">
