### ISSUE TITLE
Sharing Permission: "Read" can be deselected

### ISSUE THREAD

**Issue by dj4oC** [owncloud/web#8335]
<img width="432" alt="Screenshot 2023-01-30 at 14 57 04" src="https://user-images.githubusercontent.com/115982880/215498081-ed5527a7-7b03-4658-8c58-3c96645016dc.png">

### Steps to reproduce
1. Share a folder -> Invite -> Marie
2. Choose "Custom permission"
3. click "Cancel"
4. Again click "Custom permission"
5. Click "Apply"

### Expected behaviour
"Read" should not be deselectedable as long as there is no "Upload only" permission

### Actual behaviour
"Read is deselectedable" 

ownCloud Web UI 7.0.0-rc.10 
Infinite Scale 2.0.0+713e932c0 Community

**Comment by JammingBen** [comment]
"Cancel" somehow removes all selected custom permissions. Web then won't send any permissions to the server, resulting in a share with all available permissions as that seems to be the server default.

Nice catch, thx for reporting!
