### ISSUE TITLE
refactor e2e test so that the quick link copied is accessed from clipboard 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#8347]
We have a test step
```feature
And "Brian" copies quick link of the resource "shared_folder" from the context menu
```

Buth this step only clicks the quick link creation button and doesn't get the copied value from clipboard and store it in the `link store` 

Refactor this function so that the URL is stored as well.

- [x] PR to stable (https://github.com/owncloud/web/pull/8499)
- [x] Port to master (https://github.com/owncloud/web/pull/8530)

**Comment by SwikritiT** [comment]
we can get value from the clipboard  through the clipboard api provided by `playwright`

**Comment by SwikritiT** [comment]
Roshan will make a PR for this

**Comment by SwikritiT** [comment]
What if we need to access the link? I would expect that after copying the link we should be able to access the link as well. In the current scenario, we cannot access the link copied from the quick link if we use it in conjunction with this step
```
 When "Anonymous" opens the public link "QuickLink"
```

I would expect we should be able to use them together or is there another way we can access the quick link?

That's my opinion.
 cc @SagarGi @amrita-shrestha @saw-jan 

Others can also add theirs

**Comment by saw-jan** [comment]
As of now, we don't have tests related to quick-link so maybe implement it along with the test as well.
