### ISSUE TITLE
[Tiles view] Resize tiles

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#8368]
### Expected behaviour
Tiles can be resized using a slider component (HTML `range` input, potentially to be added to the ODS). 
Details for tile sizing have been sketched out in https://github.com/owncloud/web/issues/6126 and https://github.com/owncloud/web/pull/7991 . Independently of the current tile size on bigger viewports, https://github.com/owncloud/web/issues/8367 should be respected on mobile from my understanding

Open tasks:

- [x] Implement slider
- [x] Resize the default file icon with the tile size
- [x] Fix view when using bigger tile-sizes and having a small screen and/or opening the sidebar. Content may float out of the right screen currently.
- [x] Only show tile size slide when tile size is supported

**Bonus:** Use e.g. https://vueuse.org/core/useresizeobserver/#useresizeobserver to load & update currently viewed tiles with bigger thumbnails upon resizing on certain thresholds (only when enlarging tiles, keeping the bigger size of already loaded tiles when decreasing the size should be fine).

**Comment by ChrisEdS** [comment]
Great stuff! I know this is work in progress but, for the record, I saw the following on main branch:

1. Set the tiles view slider to the second position
2. Open a document in OnlyOffice
3. Switch back to files view inside the new tab

### Expected
The tiles view still has the size I set before

### Current
The slider has still the second position but the tiles view is set back to the not enlarged state

<img width="775" alt="image" src="https://user-images.githubusercontent.com/33026403/218250945-066c051b-74d3-4424-ba1a-1a63a4e5ff89.png">

**Comment by ChrisEdS** [comment]
I don't know if it's in scope but as a power user I would like to be able to select images (tick the boxes) with the keyboard.

**Comment by kulmann** [comment]
> I don't know if it's in scope but as a power user I would like to be able to select images (tick the boxes) with the keyboard.

Not really in scope at the moment, but wanted behaviour. I created an issue for it https://github.com/owncloud/web/issues/8429
