### ISSUE TITLE
Proper Icon for admin settings "General"

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#8403]
Suggestion to set a proper icon for the `General` Item in the admin settings:

## Icon: "information-fill"
![screenshot_000373](https://user-images.githubusercontent.com/26610733/217752547-7c159a67-c85b-4a4b-865c-57607f6574e3.png)

## Icon: "home-2-fill" (favourite)
favourite as the info icon is not quite correct because its not only informational as you will be able to set the logo here. (but I'd be also fine with the Info-icon)
![screenshot_000372](https://user-images.githubusercontent.com/26610733/217752614-dabb4eb7-6364-45ab-a2bf-2ac2aa966ebd.png)

@JanAckermann are you fine with the home icon?

**Comment by JanAckermann** [comment]
@tbsbdr idk what speaks against the icon we are using currently ?

**Comment by tbsbdr** [comment]
> what speaks against the icon we are using currently ?

sure, cogwheel is fine as well, but should be aligned with the one in the App switcher. Makes no sense to have different icons that depict the same thing (except outline / filled).

**Comment by JanAckermann** [comment]
adjusted in https://github.com/owncloud/web/pull/8375
