### ISSUE TITLE
Sorting does not work when `sortBy` and `sortDir` both change

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#8409]
### Steps to reproduce
1. Go to your personal space and make sure, you default sorting: `sortBy` = `name` and `sortDir` = `asc`
2. Click on the `size` table header to sort by size -> it won't sort by size, but by `name` `desc`

This happens because only one query param is being updated at the time.

**Comment by dschmidt** [comment]
Probably a regression introduced by the vue-router 4 update, which made all navigations async.
