### ISSUE TITLE
[ocis] Logo context menu option doesn't work

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#8416]
### Steps to reproduce
1. Login as `admin`
2. Navigate to `Administrator Setting`
3. Retry to change the logo using the `Upload image` option and reset the logo
4. Success upload/reset dialogue box pops up but the logo doesn't change 
[Screencast from 02-11-2023 07:48:54 PM.webm](https://user-images.githubusercontent.com/54478846/218262251-48f6555b-9071-4d0b-953b-411c75c55cf3.webm)

### Expected behaviour
-  Logo should be changed after successful upload message pop-up

### Actual behaviour
- logo doesn't change

### Environment general
**Operating system**: ubuntu 22.04

**Backend (ownCloud Core or Infinite Scale)**: ocis 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:** 

**Updated from an older Infinite Scale or fresh install:** master

**Where did you install Infinite Scale from:** github 

### Logs
- Not present

#### Browser log
- Not present

**Comment by kulmann** [comment]
The backend PR is not merged, yet. https://github.com/owncloud/ocis/pull/5559

**Comment by amrita-shrestha** [comment]
didn't work with the docker build. But work fine with binary build

**Comment by JanAckermann** [comment]
@amrita-shrestha could you check again? You might need to disable the cache unfortunately

**Comment by amrita-shrestha** [comment]
currently, it works fine so closing this issue
