### ISSUE TITLE
Editing or deleting the expiration date of group shares is not possible

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#8419]
<img width="217" alt="image" src="https://user-images.githubusercontent.com/84779829/218443939-ab471e6f-c7d4-47ea-a1c9-cebf79259a91.png">

steps:

- create space
- share space to group "philosophy haters" with expiration date
- try to edit or delete "expiration date"

Actual: no buttons `Edit expiration date` and `remove expiration date` for group sharing

<img width="379" alt="Screenshot 2023-02-13 at 11 39 38" src="https://user-images.githubusercontent.com/84779829/218436407-0285340b-ee9a-4409-a7ae-697b51fb9bca.png">

Expected: same as sharing with user
<img width="373" alt="Screenshot 2023-02-13 at 11 38 34" src="https://user-images.githubusercontent.com/84779829/218436375-2d072a9a-7113-450f-ae2d-3fb75682c231.png">

**Comment by JammingBen** [comment]
This seems to affect regular resources as well, not only spaces.

**Comment by ScharfViktor** [comment]
here is backend issue. I re-opened #https://github.com/owncloud/ocis/issues/5442

**Comment by JanAckermann** [comment]
Closing via https://github.com/owncloud/web/pull/9513
