### ISSUE TITLE
Shares View: Grouping of Shares

### ISSUE THREAD

**Issue by dragotin** [owncloud/web#8423]
## Summary
- **Now:** Add grouping (default: off, activate via config)
- **Later:** Replace grouping-feature by filters

## Problem description

For installations with may many shares, the current "Shares" page might be not clean and structured enough. 

## Proposed solution
@elizavetaRa from CERN has made a proposal with a grouped table which allows to structure the output of the shares tables based on attributes of the shares, ex. the owner, via a combo box.

This could make it's way into ownCloud  Web before it gets finally replaced or combined with a solution based on filtering as proposed by @tbsbdr 

- Grouping-feature should be configurable
- Grouping-feature should be disabled by default

![image](https://user-images.githubusercontent.com/26610733/218537913-a2d71ced-bb82-46a5-869a-417d04a8a93a.png)

## Alternative solutions you considered
- Multi Select Combobox with search option

**Reasoning:**

Mainly efforts:
- **Rewrite** Simple filtering is less expensive to implement (current code works and suits perfectly for cernbox users, but we'd need a rewrite of the code if we'd like to productize it) @kulmann please correct me if I'm wrong
- **Lower maintenance** costs on the long run as filters are a re-used component in Web we already need to maintain

![image](https://user-images.githubusercontent.com/26610733/218855732-647bb6a6-9be9-4f9c-8ffe-c58181f61379.png)

**Comment by tbsbdr** [comment]
(Updated initial comment of @dragotin to have all info in one place)

**Comment by JammingBen** [comment]
Has been implemented via https://github.com/owncloud/web/pull/9438.
