### ISSUE TITLE
tags can be create with only space as tag name

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#8426]
### Steps to reproduce
1. user creates a file `music`
2. navigate to `add or edit tag` 
3. Enter a space new tag suggestion available
4. Can `Save` such tag

![tag](https://user-images.githubusercontent.com/54478846/218510231-f2fc55af-3318-42bf-a8a7-1cf864dc22b8.png)
![tag2](https://user-images.githubusercontent.com/54478846/218510408-4ad7ce36-2dc1-4331-ba9d-69c93366e10b.png)

### Expected behaviour
tags name should not be spaces 

### Actual behaviour
double/triple space named tags can be created

### Question for developer
1. Is this actual behavior for tags? 

### Environment general
**Operating system**: ubuntu 20.04

**Backend (ownCloud Core or Infinite Scale)**: ocis

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:**

**Updated from an older Infinite Scale or fresh install:**  master

**Where did you install Infinite Scale from:** github

**Comment by kulmann** [comment]
... and a followup issue, if you click on the tag in the file list, the `search` route by the tag name shows an infinite loading spinner.

We should prevent this in the web ui and also add validation in the backend. Could you please also open a corresponding ocis issue? Thank you!
