### ISSUE TITLE
Only demo user `moss` shows email and password filled

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#8436]
### Steps to reproduce
1. login as demo user `moss`
2. navigate to user in administration setting
3. create new user
![Screenshot from 2023-02-15 14-43-05](https://user-images.githubusercontent.com/54478846/218980850-7bfb2f49-b5a1-4ffd-8097-46043d14a75f.png)

### Expected behaviour
Other user doesn't contain pre-existing value in email and password
![Screenshot from 2023-02-15 14-45-49](https://user-images.githubusercontent.com/54478846/218981488-b8b369a3-de42-4ffe-a6b8-d0ea60db67c2.png)

### Actual behaviour
email and password field contain some string

### Environment general
**Operating system**: ubuntu 22

**Backend (ownCloud Core or Infinite Scale)**: ocis

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:** latest

**Updated from an older Infinite Scale or fresh install:** fresh

**Where did you install Infinite Scale from:** github

**Comment by JanAckermann** [comment]
Has this something to do with user moss in general ? I think we should just disable the Autofill in all create modals in the admin settings app

**Comment by JammingBen** [comment]
Closing as duplicate of https://github.com/owncloud/web/issues/8065.
