### ISSUE TITLE
[cern] Display single (publicly) shared _file_ in dedicated view

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#8445]
### Expected behavior
When opening a public link that only refers to a single file, it should not be opened in a table or tiles view but in a dedicated view. CERN offered their implementation which lives on https://github.com/owncloud/web/pull/8440 and roughly looks like this:

<img width="1440" alt="Screenshot 2023-02-15 at 17 05 29" src="https://user-images.githubusercontent.com/16822008/219085734-d09764b3-2c37-495e-8df4-d0048bc8eeed.png">

**Comment by tbsbdr** [comment]
relates to https://github.com/owncloud/web/pull/9159/commits/44f5d2ca0ad63e854bbb80bf9670e4d1cd765afe

**Comment by tbsbdr** [comment]
question to @elizavetaRa 
does the current implementation suit your needs?
[Single file share view](https://github.com/owncloud/web/pull/9159/commits/44f5d2ca0ad63e854bbb80bf9670e4d1cd765afe)
