### ISSUE TITLE
[admin-settings] List of users not sortable in combination with search

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8467]
### Steps to reproduce
1. Open admin settings, panel "Users"
2. Enter something in searchfield (result should be > 1 users)
3. Sort table by clicking on column names

### Expected behaviour
List of search results gets sorted

### Actual behaviour
Sorting arrow in column name switches but list does not get sorted.

Tested in FF & Chrome

https://ocis.ocis-wopi.latest.owncloud.works

https://user-images.githubusercontent.com/16665512/219613582-41f104f6-42e0-487b-8653-c433a398ab8b.mov

**Comment by hurradieweltgehtunter** [comment]
Just came across the same behaviour in "Groups". But it seems like there is something re-ordered but I cannot figure out, how it gets sorted.

https://user-images.githubusercontent.com/16665512/219654956-76dc8f9e-2973-47b0-b542-1b04c2178fa6.mov

**Comment by kulmann** [comment]
@JanAckermann could you take a look here?

**Comment by JanAckermann** [comment]
Will be fixed via https://github.com/owncloud/web/pull/8433
