### ISSUE TITLE
[admin-settings] Reload of page after logo upload has no effect

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8468]
### Steps to reproduce
1. Open admin settings, tab “General”
2. Click on three dots menu next to “Logo”, select upload logo
3. Select SVG file
4. File gets uploaded, notification is positive, page gets reloaded.

### Expected behaviour
Logo is changed

### Actual behaviour
Logo stays the same after page reload. Need to hard reload manually (Win: “Ctrl + F5”, Mac: “Command + Shift + R”) to update the logo.

https://ocis.ocis-wopi.latest.owncloud.works

https://user-images.githubusercontent.com/16665512/219615203-f14c4feb-8e86-45fe-aa7c-4b10e15a643a.mov

**Comment by pascalwengerter** [comment]
Currently blocked by https://github.com/owncloud/ocis/issues/8579

**Comment by pascalwengerter** [comment]
Custom logo now gets displayed after (automated) page reload, please re-open if it appears again
