### ISSUE TITLE
[admin-settings] Users: Unexpected search result

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8493]
### Steps to reproduce
1. Add user 1:
Username: smuchatnov 
Name: "Sergej Muchatnov"
Email: test@sergej.de

2. Add user 2:
Username: sganser
Name: Susanne Ganser
Email: test@susanne.de

3. Search user list, type "serg"

### Expected behaviour
User "Sergej Muchatnov" is the only search result.

### Actual behaviour
Both users appear as search result. "Serg" is highlighted in row "Sergej Muchatnov", in row "Susanne Ganser" nothing is highlighted.

![grafik](https://user-images.githubusercontent.com/16665512/220883892-8eb607d0-d003-4cc5-91b7-969d271518c4.png)

**Comment by JammingBen** [comment]
This applies to all search fields across the platform (users, groups, spaces, space members, filters). I had a quick look into it, apparently we do this on purpose ("fuzzy search").

But I agree that the result is kinda misleading. @tbsbdr What do you think, remove the fuzziness?

**Comment by hurradieweltgehtunter** [comment]
Could you explain "fuzzyness"? Why is a user displayed who hasn't the search term in any entity?

**Comment by JammingBen** [comment]
> Could you explain "fuzzyness"? Why is a user displayed who hasn't the search term in any entity?

Sure, sorry for the technical slang 😄

A fuzzy search generally does not require a 100% match between your search term and the search result. That way, a search engine can deal with type errors. E.g. you want to search for `einstein`, but you misspell it:`einstien`. A fuzzy search will still show you `einstein` as a result. You already know this behaviour from big search engines like Google.

The more fuzzy a search engine is, the more inaccurate it gets. That can be blessing and curse at the same time.

In this specific case I'm afraid the fuzziness brings more confusion than benefit.

**Comment by hurradieweltgehtunter** [comment]
Thank you for the explanation. In this case, searching for users, fuzzyness maybe isn't appropriate and should be turned off?

**Comment by tbsbdr** [comment]
yes, please turn fuzzyness off for user search 👍
