### ISSUE TITLE
File versions list not styled

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8503]
### Steps to reproduce
1. Generate some versions of a file
2. Open sidebar -> versions

### Expected behaviour
List of version is styled in standardized layout

### Actual behaviour
- Actions look like other actions (like file actions) + hover effect
- Download icon differs from standard download icon (compare: context menu)
- paddings/margins missing
- horizontal grey line is used as separator between resource name and actions AND between actions
- actions are not labelled, instead action is described only in tooltip

![grafik](https://user-images.githubusercontent.com/16665512/221150720-67e9d620-3e55-487a-9f7c-7cfa512454bf.png)

**Comment by tbsbdr** [comment]
nitpick: for me the restore-arrow spins into the wrong direction (clockwise, i.e. forward).
I suggest a different icon for restore:
![screenshot_000489](https://user-images.githubusercontent.com/26610733/221158488-b5e38b5d-e584-4398-a249-0e0c3bad8ed4.png)

**Comment by hurradieweltgehtunter** [comment]
> nitpick: for me the restore-arrow spins into the wrong direction (clockwise, i.e. forward). I suggest a different icon `history` for restore: ![screenshot_000489](https://user-images.githubusercontent.com/26610733/221158488-b5e38b5d-e584-4398-a249-0e0c3bad8ed4.png)

good catch. done.
