### ISSUE TITLE
Make used search provider's configurable

### ISSUE THREAD

**Issue by fschade** [owncloud/web#8524]
Right now the default search provider (`files.sdk`) is enabled by default and there is no way of disabling it.

In (rare!?) cases where different file backends (ocis) are used, it is not guaranteed that the default search provider is a good fit or does work at all.

Because of that, web needs a configuration option to define which provider's are used and which not.

Since we provide a `out of the box` experience the `files.sdk` search provider must be enabled by default, but for more advanced cases, the user must be able to disable that provider and decide which to use and which not.

for reference, https://github.com/owncloud/web/pull/8441#issuecomment-1431523570

**Comment by JammingBen** [comment]
Implemented via https://github.com/owncloud/web/pull/9800. E.g. to disable the files app search provider, you simply pass `com.github.owncloud.web.files.search` to the `disabledExtensions` config.

\cc @diocas
