### ISSUE TITLE
Fix max quota validation

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#8536]
Followup for https://github.com/owncloud/web/issues/8490

There are some issues with max quota validation in the `admin-settings` app:
- [x] the `Edit` panel in the right sidebar of the `Users` view doesn't use the max quota capability. There is no validation before sending the request. The quota modal does this validation before sending the request and shows an error message in red.
- [x] The `Edit quota` batch action and context menu action do have the validation, but the max quota is not formatted properly. Should use our `formatFileSize` helper for a nice, standardized and localized filesize formatting.
- [x] `equal to or less than`, the `to` is missing after `equal`

Additional issue:
- [x] It is still possible to choose `unlimited`

<img width="506" alt="Screenshot 2023-03-03 at 15 55 58" src="https://user-images.githubusercontent.com/3532843/222756113-75b2423e-d2e7-4dc0-a352-2d6fe0955a42.png">

**Comment by JanAckermann** [comment]
@kulmann 
Fix landed in https://github.com/owncloud/web/pull/8571

Could you please move `The Edit quota batch action seems to have a copy&paste text issue`  to another issue, this has nothing to do with the quota validation in general :1st_place_medal:

**Comment by kulmann** [comment]
> @kulmann Fix landed in #8571
> 
> Could you please move `The Edit quota batch action seems to have a copy&paste text issue` to another issue, this has nothing to do with the quota validation in general 🥇

done 👍 thank you!
