### ISSUE TITLE
Fuse threshold seems wrong

### ISSUE THREAD

**Issue by lookacat** [owncloud/web#8539]
### Steps to reproduce
![Clipboard - March 6, 2023 11_34 AM](https://user-images.githubusercontent.com/786551/223089253-604d2566-5450-404b-b631-342739c09ed4.png)
![Clipboard - March 6, 2023 11_35 AM](https://user-images.githubusercontent.com/786551/223089274-1f8211f6-3423-4367-97f7-246ab6a6fb4e.png)

### Expected behaviour
Result should be found

**Comment by tbsbdr** [comment]
can't follow 😃
tried to reproduce on https://ocis.ocis-web.latest.owncloud.works/ but I don't get the problem. @lookacat what do I miss?

https://user-images.githubusercontent.com/26610733/223125530-0a853880-4b61-4ea4-b0fc-b3278c71301e.mp4

**Comment by pascalwengerter** [comment]
Also can't reproduce
