### ISSUE TITLE
Missing Translations (de)

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8573]
On-Going issue for missing translations

# Admin settings
| Area | reason | current string | proposed german string | status | checked, ok? |
| -----| ------- | -------------- | ------------------------ | ---------- | ---------|
| Left Sidebar | - | General | Allgemein | translated in TX |  ✅ |
| Allgemein | Translated in TX, ? | Appearance | Erscheinungsbild | translated in TX | ✅ |
| Users (user table, column name) | ? | Login | Anmeldung erlaubt | Translated in TX | ✅  |
| Users (user table, column "login") | seems to be missing in Transifex | Allowed / Not allowed (options for Login) | Ja / Nein | Translated in TX  | ✅  |
| Users, edit user (right sidebar) | Untranslated in TX | Login | Anmeldung erlaubt | Translated in TX | ✅  |
| Users, edit user (right sidebar) | Untranslated in TX | Allowed / Not allowed (selectable options for Login) | Ja / Nein | Translated in TX  | ✅  |
| Users, show user details (right sidebar) | Untranslated in TX | Login | Anmeldung erlaubt | Translated in TX  | ✅  |
| Users, show user details (right sidebar) | Untranslated in TX | Allowed / Not allowed (options for Login) | Ja / Nein | Translated in TX  | ✅  |
| Users, Roles Filter | ? | Roles | Rollen | Translated in TX | ✅ |
| Users, Groups Filter opened, input placeholder | - | Filter | Gruppen filtern | Translated in TX | ✅ |
| Users, Roles Filter opened, input placeholder | - | Filter | Rollen filtern | Translated in TX | ✅ |
| Users, batch actions | Seems to missing in transifex | Add to groups | Zu Gruppe(n) hinzufügen | Translated in Transifex | ✅  |
| Users, batch actions | Seems to missing in transifex | Add %{userCount} selected users to groups | %{userCount} markierte Benutzer/-innen zu Gruppen hinzufügen. | Translated in transifex | ✅  |
| Users, batch actions | Seems to missing in transifex | Users were added to groups successfully | Markierte Benutzer/-innen wurden erfolgreich zu den gewählten Gruppen hinzugefügt | Translated in Transifex | ✅  |
| Users, batch actions | Seems to missing in transifex | Remove from groups | Aus Gruppen entfernen | Translated in transifex |  ✅  |
| Users, batch actions | Untranslated in transifex | Remove %{userCount} selected users from groups  | Entferne %{userCount} ausgewählte Benutzer aus Gruppen. | Translated in TX | ✅  |
| Users, batch actions | Untranslated in transifex | Users were removed from groups successfully | Markierte Benutzer/-innen wurden erfolgreich aus den Gruppe(n) entfernt. | Translated in TX | ✅ |
| Users, batch actions "edit login" modal | New en string | Specify for the selected users whether they can log in. | Legen Sie für die markierten Benutzer fest, ob diese sich anmelden können. | Translated in TX | ✅ |
| Groups, delete group modal title | Wrong translation in TX | Delete group "%{groupName}? / Delete %{groupCount} groups? | Gruppe %{groupName} löschen? / %{groupCount} Gruppen löschen? | Not yet in TX | ✅ |
| Groups, delete group modal body | Wrong translation in TX | Soll diese Gruppe wirklich gelöscht werden soll? | Sind Sie sicher, dass Sie diese Gruppe löschen wollen? | Updated translation as suggestion in TX | ✅ |
| Spaces, change quota, enter value > max quota value | Untranslated in Transifex | Please enter a value equal or less than %{max value} | Bitte wählen Sie ein Quota kleiner als %{max value} | Translated in transifex | ✅  |
| Spaces, Details, quota usage in right sidebar | ? | 65 B von 1 GB benutzt (0% **used**) | 65 B von 1 GB benutzt (0% **genutzt**) | Proposal in Transifex | ✅  |
| Spaces, list members, list segmentation not consistent | ? | Manager/-innen - Bearbeitende Person - Betrachter/-in | Manager/-innen - Bearbeiter/-innen - Betrachter/-innen | Proposal in Transifex | ✅  |
| Enable space | english string not yet in TX | Space was enabled successfully (no translation available) | Space wurde erfolgreich aktiviert | Translated in TX | ✅ |

# Trashbin
| Area | reason | current string | proposed german string | status | checked, ok? |
| -----| ------- | -------------- | ------------------------ | ------ | ------------- |
| page title | TBD | Trash Overview | Papierkorb-Überblick | translated in TX | ✅ |
| subtitle below trash overview | TBD | %{count} trashes in total | %{count} Papierkörbe | translated in TX | ✅ |

# Notifications

| Trigger | reason | current string | proposed german string | status | checked, ok? |
| -----| ------- | -------------- | -------------------------- | ------ | ------------- |
| User added to space | - | %{username} added you to Space %{space name} | %{username} hat dich zum Space %{space name} hinzugefügt | translated in TX | ✅ |
| User removed from space | - | %{username} removed you from Space %{space name} | %{username} hat dich aus Space %{space name} entfernt | translated in TX | ✅ |
| File shared | - | %{username} shared %{filename} with you | %{username} hat %{filename} mit dir geteilt | translated in TX | ✅ |
| File un-shared | - | %{username} unshared %{filename} with you | %{username} hat die Freigabe %{filename} beendet (?) | translated in TX | ✅ |
| Notification box | - | Mark all as read | Alle als gelesen markieren | translated in TX  | ✅ |
| disable space | - | {username} disabled Space {spacename} | {username} hat den Space {spacename} deaktiviert | translated in TX | ✅ |

# Spaces

| Trigger | reason | current string | proposed german string | status | checked, ok? |
| --------| -------| -------------- | ------------------------ | ------ | ------------- |
| Notification (toast) when enabling space | - | Space was enabled successfully | Space wurde erfolgreich aktiviert. | Translated in TX | ✅ |
| Share space, set permission | permission declaration not consistent | Betrachter/-in, Bearbeitende Person, Manager/-in | Kann anzeigen - Kann keine Änderungen vornehmen // Kann bearbeiten - Kann Änderungen vornehmen // Kann verwalten - Kann administrieren | translated in TX | ✅ |

# Files
| Trigger | reason | current string | proposed german string | status | checked, ok? |
| --------| -------| -------------- | ------------------------ | ------ | ------------- |
| Share file/folder, Permission type declarations not consistent | - | Betrachter/-in, Bearbeitende Person, Benutzerdefinierte Rechte | Kann anzeigen - Kann keine Änderungen vornehmen // Kann bearbeiten - Kann Änderungen vornehmen // Benutzerdefinierte Rechte | - | ✅ |
| Context menu | ? | Create Space from selection | Neuen Space aus Auswahl erstellen ... | Translated in TX | ✅ |
| Create space from selection dialog | ? | Create Space with the content of "file.txt". The content will be copied. | Erstellt einen neuen Space. Die markierten Elemente werden in den neuen Space kopiert. | Translated in TX | ✅ |

# Account settings
| Area | reason | current string | proposed german string | status | checked, ok? |
| -----| ------- | -------------- | ------------------------ | ---------- | ---------|
| Account | net yet transferred | GDPR export | Export nach §20 DSGVO | Translated in TX |  ✅ |
| Account | Missing in TX | Request a new GDPR export | Neuen Export anfordern | Translated in TX |  ✅ |
| Account | Missing in TX | Download export | Export herunterladen | Transalted in TX |  ✅ |
| Account | - | GDPR export could not be requested. Please contact an administrator. | DSGVO-Export kann nicht angefordert werden. Bitte wenden Sie sich an Ihren Administrator. | Translated in TX | ✅ |
| Account | - | GDPR export has been requested | DSGVO Export wird erstellt ... | Translated in TX |  ✅ |

# Search
| Area | reason | current string | proposed german string | status | checked, ok? |
| -----| ------- | -------------- | ------------------------ | ---------- | ---------|
| Search result dropdown | string not translated | Files | Dateien | translated in TX |  ✅ |

to be continued

**Comment by kulmann** [comment]
huh, what do you mean by `missing translations`? Just missing in transifex? Then I'd propose to just go ahead and translate the strings in transifex. ;-) `General` is already translated as `Allgemein`. If you discover strings that don't appear in transifex at all, that would of course be worth an issue.

**Comment by hurradieweltgehtunter** [comment]
I'm just collecting translations here which appear to be missing or seem badly translated while going through the UI. Looking up the reason later.

**Comment by hurradieweltgehtunter** [comment]
@kulmann updated the status and translated missing ones.

**Comment by kobergj** [comment]
@hurradieweltgehtunter here is the link to transifex: https://www.transifex.com/owncloud-org/owncloud/ocis-userlog/

Strings look fine. We are using `Sie` instead of `dich` and also some wording is slightly different. But they look fine for me.

**Comment by hurradieweltgehtunter** [comment]
> @hurradieweltgehtunter here is the link to transifex: https://www.transifex.com/owncloud-org/owncloud/ocis-userlog/
> 
> Strings look fine. We are using `Sie` instead of `dich` and also some wording is slightly different. But they look fine for me.

Perfect, thank you. Notifications are translated.

**Comment by pascalwengerter** [comment]
@hurradieweltgehtunter what's the definition of done here, is this a backend or frontend issue after all? :)

**Comment by hurradieweltgehtunter** [comment]
> 



> @hurradieweltgehtunter what's the definition of done here, is this a backend or frontend issue after all? :)

Depends :) I'll close this issue when I checked all listed translations. So far it was Transifex mostly.

**Comment by hurradieweltgehtunter** [comment]
All translations fixed 🚀
