### ISSUE TITLE
Context menu hide the three dots when there is not enough space down below

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#8574]
### Steps to reproduce
1. Create a MD document
2. Create a TXT document
3. Open the menu on each file with the three dots menu or with right click

### Expected behaviour
The menu opens the same way no matter on which file extension

### Actual behaviour
https://user-images.githubusercontent.com/33026403/223869649-cfcd118c-7e31-46a8-b779-8706e9db8758.mov

### Environment ownCloud Infinite Scale
**Version:**
ownCloud Web UI 7.0.0-rc.18 
​Infinite Scale 3.0.0-alpha.1+633b4ba79 Community

**Comment by kulmann** [comment]
IMO works as designed. This was a recent improvement to avoid scroll bars in context menus as much as possible.

**Comment by ChrisEdS** [comment]
> IMO works as designed. This was a recent improvement to avoid scroll bars in context menus as much as possible.

No it does not, the menu has no spacing to the right anymore:

https://user-images.githubusercontent.com/33026403/223947662-2404fc7d-cea9-4ff9-896d-540bb04d83ac.mov

As you can see in the video the three dots are hidden ...

**Comment by JammingBen** [comment]
Ahh okay, so it's about the horizontal placement, got it 👍 Not that trivial to solve unfortunately, as always with the drop menu placement. I'll have a look when the time permits.

**Comment by kulmann** [comment]
> > The text file has more items (= bigger menu), hence this is happening.
> 
> 
> 
> Oh yes, seems unrelated to the file extension - I will change the title. Thanks

Ah, gotcha, thanks for clarifying!
