### ISSUE TITLE
Antivirus: Provide helpful error message

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#8580]
### Steps to reproduce
1. try to upload a virus ex from https://www.eicar.org/download-anti-malware-testfile/
2. Error message says only "unknown error"
![image](https://user-images.githubusercontent.com/26610733/224068142-f475432d-91d2-44a1-abf4-61d7591215d3.png)

### Expected behaviour
Error message should inform the user why the upload failed. in this case:
`Virus detected, upload was blocked for this file.`

### Actual behaviour
Error message says only "unknown error"

### Environment general
- reported by a customer afaik on "Schulungsumgebung"

**Comment by JanAckermann** [comment]
@micbar can you check if this has been already solved with our translated messages from backend ?

**Comment by JanAckermann** [comment]
Closing as I think this has been solved already. Please reopen if wrong.
