### ISSUE TITLE
[Notifications] Re-load spaces when user has been added to a space

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#8586]
Currently, when receiving a notification about a space invitation, you either need to re-load the page or head the to spaces overview for it to be clickable. It would be great to re-load the spaces in the store in such case.

**Comment by kulmann** [comment]
Why not fetch the single space if it‘s not yet present in the runtime? If useres have thousands of spaces in the future it would be great to not reload the full list. 😅

**Comment by JammingBen** [comment]
Sounds good, but we need to differentiate between the space notifications because we only want to do that when the user has been added to a space - that's not possible currently. And we also need to take action when being removed from a space or a space gets disabled/removed.

**Comment by JammingBen** [comment]
Closing in favour of https://github.com/owncloud/web/issues/10397.
