### ISSUE TITLE
Respect public link password enforcement capability

### ISSUE THREAD

**Issue by micbar** [owncloud/web#8587]
# Description

There is a capability which is used in oc10 and ocis to indicate that public links need a password to be sucessfully created/changed.

ownCloud Web seems to currently not respect that capability.

## ocis

```json
{
    "api_enabled": true,
    "resharing": true,
    "group_sharing": true,
    "sharing_roles": true,
    "deny_access": false,
    "auto_accept_share": true,
    "share_with_group_members_only": true,
    "share_with_membership_groups_only": true,
    "search_min_length": 3,
    "default_permissions": 22,
    "user_enumeration": {
        "enabled": true,
        "group_members_only": true
    },
    "federation": {
        "outgoing": false,
        "incoming": false
    },
    "public": {
        "enabled": true,
        "send_mail": true,
        "social_share": true,
        "upload": true,
        "multiple": true,
        "supports_upload_only": true,
        "password": {
            "enforced_for": {
                "read_only": false,
                "read_write": true,
                "upload_only": true
            },
            "enforced": false
        },
        "expire_date": {
            "enabled": false
        },
        "can_edit": true,
        "alias": true
    },
    "user": {
        "send_mail": true,
        "profile_picture": false,
        "settings": [
            {
                "enabled": true,
                "version": "1.0.0"
            }
        ],
        "expire_date": {
            "enabled": true
        }
    }
}
```

The capability tells the clients, on which public link type the password needs to be enforced:

```json
"password": {
            "enforced_for": {
                "read_only": false,
                "read_write": true,
                "upload_only": true
            },
            "enforced": false
        },
```

**Comment by micbar** [comment]
@tbsbdr @kulmann FYI

**Comment by JammingBen** [comment]
Web should already respect the capability when creating public links via the share panel or the quick action. But the check is missing when creating links via the context action "Copy quicklink".

Also, there are some conflicts with the `internal` role, because that one does not support password protection.

**Comment by micbar** [comment]
@JammingBen 

1. set `OCIS_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD: "true"`
2.  try to create link with "Editor" permission
3. "updating the share failed"

### Response

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>error</status><statuscode>996</statuscode><message>Error sending update request to public link provider: the public share needs to have a password</message></meta></ocs>
```

**Comment by kulmann** [comment]
Turns out, there are bugs backend side and frontend side:
- backend: the password enforced for capability `read_write_delete`, which represents the `Editor` role, is missing
- frontend: the `isPasswordEnforcedFor` check returns early with the first capability that was true. It doesn't check that it's in the context that is represented by the capability.

**Comment by micbar** [comment]
- Reva PR https://github.com/cs3org/reva/pull/3731
- oCIS PR
- Web PR

**Comment by JammingBen** [comment]
Creating links via the context menu still ignores the `read_only` capability 👀

**Comment by JammingBen** [comment]
This works as expected by now, hence closing here.
