### ISSUE TITLE
[admin-settings] Avatar initials do not update on username change

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8588]
### Steps to reproduce
1. Go to admin settings -> user -> edit user
2. Change username -> save

### Expected behaviour
Avatar in top right corner changes to first letter of new username

### Actual behaviour
Avatar does not change / Does change but page reload is required

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

**Comment by JanAckermann** [comment]
Avatar does not respect the username but first and last name, anyways can't reproduce, avatar changes for me
