### ISSUE TITLE
[admin-settings] Make group names editable

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8591]
### Steps to reproduce
1. Go to admin settings -> groups -> create new Group
2. Click on created group

### Expected behaviour
Group name can be edited

### Actual behaviour
Group name cannot be edited.
This can get it very cumbersome when trying to rename a group with many users in it:
1. Create new group
2. Move all users to new group
3. Delete old group
:(

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

**Comment by JammingBen** [comment]
This needs to be implemented via API first: https://github.com/owncloud/ocis/issues/5099
