### ISSUE TITLE
[admin-settings] Users: Improve batch actions add to / remove from group(s)

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8597]
Current implementation works but holds potential for improvement.

Proposal:

Instead of 2 buttons "add to groups" & "Remove from Groups" make one button "Edit groups" (Saves space and the group selection box in the opening modal should then behave like when editing a single user (right sidebar))

- Show all groups as buttons, of which at least one of the selected users is a member, removable with the "X"
- Show addable groups as selection (like it is now)

Especially removing groups in the current implementation could lead to confusion:
1. Select some users ("Student 1", "Student 2") which are definitely not part of a specific group ("Teachers", elevated permissions)
2. click on batch action "remove from groups"
3. Specific group ("Teachers") is displayed as option to remove from the selected users ("Student 1", "Student 2"). -> ”Why is this group displayed? Are those students wrongfully in the "Teachers" group? Ok better remove them. Repeat. Group "Teachers" is still displayed as option? Something must not be working!“ -> Panic.

**Comment by tbsbdr** [comment]
This is exactly how I'd love to see it, but unfortunately retrieving the `users` x `groups` information would slow down the system, right @kulmann @micbar ?

## Former Draft
This is a former draft where only **common groups** are shown.
(different: groups-form is places in the right sidebar, bot as batch-modal - but thats not the point here)
![Users - Window@2x](https://user-images.githubusercontent.com/26610733/224317558-7d407adc-47ea-46da-8dc4-f8dac489ed01.png)

**Comment by hurradieweltgehtunter** [comment]
yep, exactly. I can't assess the performance issues, but UX wise I'd really recommend it that way.

**Comment by micbar** [comment]
@hurradieweltgehtunter Unfortunately that is not possible.

We would risk a lot of blaming. There are some organisations which cannot call "listMembersOfGroup" on the backend.

This would make the UI completely unusable.

**Comment by hurradieweltgehtunter** [comment]
Too bad. but ok, I'm just reporting what jumps to my mind in my oc web journey :)
