### ISSUE TITLE
[spaces] Highlight spaces where user is space-admin

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8640]
While playing around with web I came across the problem, that can't remember, of which space I am a space admin when having many spaces. My proposal would be to add a little highlight to spaces, where I'm space manager of.

![grafik](https://user-images.githubusercontent.com/16665512/225873871-f7b81f08-aaf0-4f70-b992-a7e80b47a00d.png)

**Comment by hurradieweltgehtunter** [comment]
Same goes for admin-panel -> spaces. Some highlight of spaces, where I'm manager of would be nice. Otherwise, users might get confused why actions on spaces differ.

**Comment by tbsbdr** [comment]
To get the requirements clear: "can't remember, of which space I am a space admin" - why is it important for the manager to have this info upfront in the space overview?

**Comment by hurradieweltgehtunter** [comment]
I think most importantly because the available actions differ, and currently it is not clear, why they differ (got me confused at least).
Also, it might get in handy to see, in the overview, on which spaces the user can perform admin tasks at all.

**Comment by JanAckermann** [comment]
I think it's quite handy to have this information, as well displaying it with a small tag in the upper right front.

Is this actionable @tbsbdr @kulmann

**Comment by tbsbdr** [comment]
I'm not really convinced of the necessity of this feature, thus low prio from my side.
Imo it would be more important to have a function that users can access their most often needed spaces/files within a a few clicks. This could be
- "recent" or
- "favorites" or
- box.com-like collections
- other possibilities ...

Examples:

![screenshot_000775](https://user-images.githubusercontent.com/26610733/233921376-485033fd-245a-4529-8348-fffbf8da4e69.png)

![screenshot_000776](https://user-images.githubusercontent.com/26610733/233921910-ad4877ca-39c4-42c9-b17d-a17fcdefec61.png)

**Comment by JanAckermann** [comment]
Fine for me but a complete different story (: with a lot of planning involved

**Comment by hurradieweltgehtunter** [comment]
> Imo it would be more important to have a function that users can access their most often needed spaces/files within a a few clicks. 

Seems like a totally different feature? 
I opened an issue some while ago to that topic here: https://github.com/owncloud/web/issues/7563

**Comment by tbsbdr** [comment]
correct, different topic

**Comment by tbsbdr** [comment]
@JanAckermann you said this could be done with low effort like < 1h - if so, I don't want to stop you

**Comment by JanAckermann** [comment]
:+1:

**Comment by JanAckermann** [comment]
>Same goes for admin-panel -> spaces. Some highlight of spaces, where I'm manager of would be nice. Otherwise, users might get confused why actions on spaces differ.
@hurradieweltgehtunter some design proposal?

**Comment by JanAckermann** [comment]
But admin-panel -> spaces is a list, where do you want to have the badge?

**Comment by hurradieweltgehtunter** [comment]
> But admin-panel -> spaces is a list, where do you want to have the badge?

This list has a `Manager` column, which is sufficient imo.

**Comment by tbsbdr** [comment]
Im not convinced of this solution. It adds too much visual info upfront that always need to be processed vs. i assume the usecase to be quite rare.
