### ISSUE TITLE
[spaces] cannot select 1GB quota as quota on new space

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8641]
### Steps to reproduce
1. Create space
2. Edit quota
3. Select 1GB

### Expected behaviour
Quota can be confirmed and stored

### Actual behaviour
Button "Confirm" is disabled

When selecting an other quota, saving it, edit quota again -> 1GB can be selected.

Edit: Further digging: It seems, that the already stored quota value cannot be selected and stored again.
Edit quota -> Select "2GB" -> save -> edit quota again -> Select 2GB -> Button is disabled.
This is ok, if a quota is selected. But for new spaces without a quota setting it seems that the select field has the first option "1GB" pre-selected, although there is no 1GB quota. This results in disabling the "Confirm" button.

Proposal: Add an option "Select quota or enter value" as pre-selected option.

![grafik](https://user-images.githubusercontent.com/16665512/225880501-7f632b09-13bd-4686-90f7-c0ed5ce960de.png)

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

**Comment by JammingBen** [comment]
> But for new spaces without a quota setting it seems that the select field has the first option "1GB" pre-selected, although there is no 1GB quota.

No, 1 GB is pre-selected because it **is** the current value. A new space gets created with 1 GB default quota.

> Proposal: Add an option "Select quota or enter value" as pre-selected option.

This won't work, because again, 1 GB is the value the space actually has.

**Comment by ChrisEdS** [comment]
Maybe add a small `(current value)` text behind?

**Comment by hurradieweltgehtunter** [comment]
I'm not on laptop anymore but I think what confused me in the first place was that there was no note - neither in the space overview nor the modal-, that the quota was set to 1GB initially. 
But I need to verify that.

**Comment by hurradieweltgehtunter** [comment]
I checked again. What confused me in the first place was that I clicked on a disabled space. Disabled spaces show `-` as remaining space in the admin settings spaces overview. For me, it was not recognizable which quota settings were applied for this specific space, so I got confused even more when I could not select 1GB.
My idea would be to show the remaining space for disabled spaces, too. And, show the quota settings. For example:
Remaining space: 345MB / 1 GB

**Comment by JammingBen** [comment]
> My idea would be to show the remaining space for disabled spaces, too. And, show the quota settings. For example:
Remaining quota: 345MB / 1 GB

We would like to do that, but the server does not provide that data for disabled spaces :( Which raises the question for me: does it make sense to show the "Edit quota"-action for disabled spaces?

**Comment by hurradieweltgehtunter** [comment]
Now I'm confused. A lot. Are these columns in the space overview in admin settings new?

<img width="507" alt="grafik" src="https://user-images.githubusercontent.com/16665512/227362591-0626b5c9-f7bc-4e8f-855b-06e4097f56cc.png">

**Comment by kulmann** [comment]
> Now I'm confused. A lot. Are these columns in the space overview in admin settings new?
> 
> <img alt="grafik" width="463" src="https://user-images.githubusercontent.com/16665512/227363617-96c43761-4f13-49e2-adec-1e32bb846287.png">

Not new. They are hidden when your browser window is too smal.

**Comment by hurradieweltgehtunter** [comment]
🤦 wow … ok, then it's my fault, apparently.

What do you think about condensing the 3 columns to one?
Quota usage: `1.1MB / 2GB `
Maybe add: `(0.2% used)` 

Displaying "Used quota" and "Remaining quota" seems doubled, as one can derive one value from the other.
Would make more room for possible future columns and would make the quota information visible on smaller screens.
