### ISSUE TITLE
[spaces] Cannot change, add or remove members to disabled spaces, but GUI suggests being able to

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8642]
### Steps to reproduce
1. Create space
2. Disable space
3. Right click -> Members
4. Enter user/groupname
5. Select user/group
6. Click on "Add"

### Expected behaviour
User/group gets added as space member

OR

Invite GUI is disabled

### Actual behaviour
GUI let's me select users/groups but fails when clicking on "Add"

XHR Response:
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>failure</status><statuscode>404</statuscode><message>Wrong path, file/folder doesn&#39;t exist</message></meta></ocs>
```

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

**Comment by hurradieweltgehtunter** [comment]
This might get interesting: If it should not be possible to add members on disabled spaces, should it be possible to add new space admins? This could be a valid case. While preventing normal users from accessing a space, the space administration might change or wants to edit the space.
Example: Teacher 1 is space admin for space “class 1”. After the school year with the beginning of the holidays, the space gets disabled to prevent students from accessing it. In the meantime, Teacher 1 wants to add Teacher 2 as space admin, because Teacher 2 will be the new class teacher. To do so, he is forced to grant students access – which he might not want to.

**Comment by hurradieweltgehtunter** [comment]
FYI: This is not bound to adding new members only, but also for editing existing space members (remove, change permission, add expiration date, ...)

**Comment by hurradieweltgehtunter** [comment]
@tbsbdr i think this needs a concept decision at first. Should it be possible to edit disabled spaces (and it is even technically possible?) or not?

**Comment by JanAckermann** [comment]
This concept has been decided with the whole team. Maybe @butonic can give some insights.

**Comment by kulmann** [comment]
> @tbsbdr i think this needs a concept decision at first. Should it be possible to edit disabled spaces (and it is even technically possible?) or not?

Like @JanAckermann said, it was a conscious decision to **not** make a disabled space editable in any way. Let's make this consistent in the first place. I can see a requirement coming up in the future that managers want to edit disabled spaces anyway, but we should not invest all the valuable time to make that possible right now.

As a result, I see multiple things that need to be fixed for a consistent "disabled space" experience in the UI:
- "Members" panel in the right sidebar:
  - disable the invite input field for members
  - disable `Create link` for the quicklink
  - disable `Add link` for additional public links
  - disable context actions on already existing links
- right click context menu on a disabled space:
  - remove menu item "Edit image"
