### ISSUE TITLE
language code "zh_CN" does not work

### ISSUE THREAD

**Issue by Dirreke** [owncloud/web#8678]
In `config.json`, when I set the tag `"zh_CN": "文件"` to the `applications`, just like what the [document](https://github.com/owncloud/web/blob/5e95e12d9952e2d17aaced71c177e5c1c4091779/docs/deployments/oc10-app.md?plain=1#L89) say, it doesn't work.

![image](https://user-images.githubusercontent.com/51513111/226936761-e8712017-ffb3-464f-9e7f-c6a72af8b4c6.png)

I tried to modify "zh_CN" to "zh" like the following, and it works.

![image](https://user-images.githubusercontent.com/51513111/226937834-05bf2420-a676-42e3-a59f-91b62d0a98b1.png)

```json
"applications" : [
    {
      "title": {
        "en": "Classic Design",
        "de": "Klassisches Design",
        "fr": "Design classique",
        "zh": "文件"
      },
      "icon": "swap-box",
      "url": "http://sgool.zju.edu.cn:53030/index.php/apps/files"
    }
]
```
So maybe the different language codes are used at the different place.

And other text that is not in Chinese may also be the result of this issue.

![image](https://user-images.githubusercontent.com/51513111/226941852-3daf3083-9e0b-474b-85ac-1821150bf96c.png)

I will be sorry if it is my negligence, please let me know.

### Environment general
**Operating system**: Cent Os 7

**Backend**: ownCoud

### Environment ownCloud Core
**Web server:** Nginx

**Database:** SQL

**PHP version:** 7.3

**Version:** 10.11.0

**Updated from an older ownCloud or fresh install:**Updated from the older ownCloud

**Comment by JanAckermann** [comment]
Thank you for the issue, 
let me clarify: web is only using the language code for now, the territory code won't be used, therefore the docs are wrong and 
therefore I will change zh_CN to zh,

As you already noticed, translations are missing. We rely on the community here, so everybody can add translations to; 
https://app.transifex.com/owncloud-org/owncloud-web/language/zh/
