### ISSUE TITLE
Too long breadcrumb breaks sidebar

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#8685]
### Steps to reproduce
1. Go into a subfolder with a breadcrumb that is longer than the current web-app-files width
2. Open sidebar

### Expected behaviour
Breadcrumb becomes multiline (considered as bad usability). gdrive?

### Actual behaviour
Breadcrumb keeps the width for the web-app-files, the sidebar width breaks

![thumbnail_ragozina_cern](https://user-images.githubusercontent.com/7430156/227143572-695c043d-96ae-4e0d-a0cd-ce5384308330.png)

**Comment by elizavetaRa** [comment]
@kulmann several users by us are facing this problem as deep directory trees are common

**Comment by kulmann** [comment]
already tracked in https://github.com/owncloud/web/issues/6731 - could you add your info and screenshot here and close this issue as duplicate?
