### ISSUE TITLE
[guests] Label guest accounts as "Guest" instead of "User"

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8700]
### Steps to reproduce
1. Go to admin settings ⇾ users
2. Add user, role “guest”
3. go to files ⇾ share file ⇾ enter guest account name.

### Expected behavior
Proposals on user search differentiate between types:
— users
— groups
— guests

<img width="1032" alt="grafik" src="https://user-images.githubusercontent.com/16665512/227475991-e8729153-5d81-4381-b0bf-30eb63aa8b2c.png">

### Actual behavior
Guest accounts are labelled “User”

<img width="407" alt="grafik" src="https://user-images.githubusercontent.com/16665512/227475217-e8213d7d-1a19-4ecf-b28c-855020413ad2.png">

**Comment by JanAckermann** [comment]
Closing in favour of https://github.com/owncloud/ocis/issues/6058
