### ISSUE TITLE
Make sure `hasAvatar` is reactive in RecipientContainer

### ISSUE THREAD

**Issue by dschmidt** [owncloud/web#8734]
c.f. https://github.com/owncloud/web/pull/8682#discussion_r1151152659

... or at least clarify why it doesn't have to be

**Comment by JammingBen** [comment]
I checked the code, IMO there is no need for it to be reactive.

A `RecipientContainer` gets created when you select a recipient to share a resource with. On creation it will check if the recipient is a user and then loads their avatar. There is no scenario where the recipient changes while the container keeps existing. A new recipient would result in a new `RecipientContainer`.
