### ISSUE TITLE
[admin-settings] Users: Add "no group" to group filter

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8740]
### Steps to reproduce
1. Go to admin settings -> Users
2. Click on group filter

### Expected behaviour
It could come in hand to have an option "No group" to show all users who are not member of a group

![grafik](https://user-images.githubusercontent.com/16665512/228550269-ca5d21cc-243c-4c13-8b42-bff1acc5c6de.png)

### Actual behaviour
There is no such possibility

**Comment by JanAckermann** [comment]
Would like to have the wording: Not assigned and rather use a descriptive icon like the group icon but crossed out

**Comment by kulmann** [comment]
we'll do that, but I'll close this issue here in favour of the more recent and detailed https://github.com/owncloud/web/issues/10820
