### ISSUE TITLE
[share-dialog-redesign] Redesign of sharing dialog (right sidebar)

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8743]
Based on customer feedback, we might have to think about some rework of the share dialog in the right sidebar.

# Current layout

## Section share with people
![grafik](https://user-images.githubusercontent.com/16665512/228586709-0ec59fa0-dbcb-4098-8c9e-6c2828ae26e7.png)

Tracked here: https://github.com/owncloud/web/issues/8749

## Section "Share via link"
![grafik](https://user-images.githubusercontent.com/16665512/228587144-235fd2f2-c16d-4c8a-87f0-d4f83e78edf6.png)

Tracked in subtask here: https://github.com/owncloud/web/issues/8750

# Rename permissions

This is mostly due to the german translations and the attempt for gender-neutral wording. It is quite hard to find a gender-neutral term representing permissions:
- Bearbeiter/-in: looks clumsy
- Bearbeiter / Bearbeiterin: too long
- Bearbeitende Person: too long, not universally usable

Tracked in subtask here: https://github.com/owncloud/web/issues/8751
Discussion about permission "Internal" here: https://github.com/owncloud/web/issues/8752

**Comment by kulmann** [comment]
Share dialog redesign is not on the roadmap. What we currently have works for now. Thanks for the input, maybe later when we come back to this in the future.
