### ISSUE TITLE
[share-dialog-redesign] V: Access details

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8753]
![grafik](https://user-images.githubusercontent.com/16665512/228802366-a44b5429-d8c4-4db2-b25e-451c44a7091c.png)

Needs info on 
- What's the overall purpose?
- Which information can be displayed in each section?

TBD

**Comment by kulmann** [comment]
The purpose is to display all information about a share at a glance, while only keeping the most important information in the share row of the shares panel. Otherwise the shares list would be quite overwhelming for the user. 🤷

**Comment by hurradieweltgehtunter** [comment]
Ok got that. Thank you.
I do understand the motivation to add this panel, but I think - backed by customer feedback - that this can and should be improved.

My thoughts on that:

**Access details**
For the current content, I think this is not the correct title.

**Name** 
It is not clear to me which name is meant here. The title does not say “Details about invited person” so it's not clear that this is the invited persons` name. 
Also, this seems redundant as it is already displayed in the right sidebar.

**Additional info**
Why this label and not `email address`? 
Seems redundant as it is displayed in the tooltip when hovering over the avatar.

**Type**
Redundant, since we're using different icons in the list

**Access expires**
Redundant, since we're displaying the calendar icon + expiration date + remaining time for expiring access

**Shared on**
Valid information IMO

**Invited by**
Valid information IMO

Will add a concept for possible improvements.

**Comment by kulmann** [comment]
Share dialog redesign is not on the roadmap. What we currently have works for now. Thanks for the input, maybe later when we come back to this in the future.
