### ISSUE TITLE
[oC10] folder cannot be downloaded by no-login user with quick link

### ISSUE THREAD

**Issue by Dirreke** [owncloud/web#8761]
Sorry if the design is like this. 

I create a quicklink with permission 'Viewer'. And there are some folders and files in it.

Users who are not logged in can download files but not folders.

I'm not sure if it's a problem. If it's my mistake, please tell me. Thanks

**Comment by JammingBen** [comment]
Do you get an error when trying to download a folder, or does the option simply not show? This should have been fixed recently (see https://github.com/owncloud/web/issues/6423). What version of Web are you currently running?

**Comment by Dirreke** [comment]
yeah. I use web 6.0 with owncloud server 10. @kulmann 

I think it's a little different from #6423.

It has 2 issue actually.

 * First, when I download folder, it will jump to the login page and require user to log in. 

 * Second, even if I log in as the user who shared this link, I can not download it either. It returns that "File not found. The specified document has not been found on this server"

![mmexport1680259131938.png](https://user-images.githubusercontent.com/51513111/229098441-15954673-82f5-4785-9c59-e8d95d003e1f.png)

**Comment by Dirreke** [comment]
![image](https://github.com/owncloud/web/assets/51513111/e8b901b5-bc16-4f7b-a6dc-3fa57f980132)
And when I use web 7.0.2, I get the empty file by clicking "download"(for folder)

**Comment by Dirreke** [comment]
![image](https://github.com/owncloud/web/assets/51513111/e51cc534-0c87-4205-8133-e9075a35986c)
it's also happen when I download multiple files by clicking "download" on the top of web

**Comment by Dirreke** [comment]
I checked the Network, And  I fount it get a 302 Code.
![image](https://github.com/owncloud/web/assets/51513111/49b93ab4-5a8b-4e13-a29d-c486e53b17e5)
Maybe beacause that when I tried download a folder from shared link, I always get the param `dir=%2F`, it result that I cannot download folder.
