### ISSUE TITLE
[admin-settings] Make space disable and delete button available for user with admin role

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#8763]
### Steps to reproduce
1. create user `Samy` with user role `admin` and user `Amy` with `User` role
2. user 'Amy' create spaces `team A` and `developer team`
3. user `Samy` goes to the admin-setting page 
4. `Samy` user tries to disable the space  `team A` and `developer team`
5. disable button is not visible 
![Screenshot from 2023-03-31 14-28-24](https://user-images.githubusercontent.com/54478846/229071661-29ec545a-a46d-40ab-997b-c6cb6d8972e6.png)
6. admin role users can disable and delete their own space through webUI
7. a user with an admin role can disable and delete space created by the next user using the API 

### Expected behaviour
 users with admin roles should be able to disable, delete and restore spaces created by other users through webUI

### Actual behaviour
 users with admin roles can edit space quotes only through webUI

### Environment general
**Operating system**:  ubuntu 22.04

**Backend (ownCloud Core or Infinite Scale)**: ocis

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:**  7.0.0-rc.26

**Updated from an older Infinite Scale or fresh install:**  fresh

**Where did you install Infinite Scale from:** github

# Question
- Are we going to add feature `admin role user delete and disable space created by others` ❓

**Comment by JanAckermann** [comment]
I think we should close it then

**Comment by amrita-shrestha** [comment]
# QA-TODO
Space disable and delete button has been added on the web. Related issue in ocis  https://github.com/owncloud/ocis/issues/5872

- [ ] Maybe we could add webUI deletes for admin deleting other user spaces

@saw-jan @SwikritiT

**Comment by SagarGi** [comment]
Test has been added for it and seems to be working fine
