### ISSUE TITLE
Open in web from Desktop currently broken

### ISSUE THREAD

**Issue by micbar** [owncloud/web#8773]
### Steps to reproduce
1. Create Document.docx on the Desktop Client
2. In file browser, open Context action "owncloud->Open in Onlyoffice"
3. 

### Expected behaviour
OnlyOffice should open the app

### Actual behaviour
![1680645377861](https://user-images.githubusercontent.com/4378513/229931776-22f81b07-198b-440b-b002-7564fa53b4c0.png)

### Request (from mitmproxy)

POST https://0001.schule.owncloud.works/app/open-with-web 
With param `file_id: 0dd2c554-61ce-4c46-bceb-1962ce93fac3$ddc2004c-0977-11eb-9d3f-a793888cd0f8!84b3a190-f155-4b97-ada1-8834d45e72f4`
NOTE: appName is empty

Return value

```json
{ "uri": "https://0001.schule.owncloud.works/external?contextRouteName=files-spaces-personal&fileId=0dd2c554-61ce-4c46-bceb-1962ce93fac3%24ddc2004c-0977-11eb-9d3f-a793888cd0f8%2184b3a190-f155-4b97-ada1-8834d45e72f4"
   }
```

Web tries to open but cannot find an appName
![empty app name](https://user-images.githubusercontent.com/4378513/229932964-c924be7f-797d-4279-933e-148d1a5981f8.png)

## Spec

originally this was documented here https://owncloud.dev/services/app-registry/apps/#open-a-file-with-the-owncloud-web

An empty appName should open the default app.

## Questions

@TheOneRing Intended to send no appName?

@dschmidt @kulmann  Could that be fall out from the file action refactoring?

ownCloud | Infinite Scale
-- | --
Edition | Community
Version | 3.0.0-alpha.2+8c9c9fd2d
Web-Client-Version  | 7.0.0-rc.27

**Comment by JammingBen** [comment]
Re-opening because it still fails on `ocis.ocis-wopi`. Needs further investigation.

**Comment by dschmidt** [comment]
Same error?

**Comment by JuancaG05** [comment]
> Same error?

Yes, I'm working with this feature for the Android app and in `ocis-wopi.latest` I could reproduce this same error

**Comment by JammingBen** [comment]
So turns out the fix is not yet released and deployed... big facepalm moment 🤦
