### ISSUE TITLE
Feature Request: Password Exchange Extension

### ISSUE THREAD

**Issue by dj4oC** [owncloud/web#8817]
## Use Case:
I want to exchange a password with a user and I don't want to use unsecure email to do this. Currently I create a text file in ownCloud and share this md file with a user, but I have to generate a password using an external password generator and I have to delete the file after a certain time. I would love to have a user interface for this purpose.

### User A has a small form to enter username, generate or input password, write a little comment and set a validation. If form is filled, a quick link is generated and can be shared with external users.
![Screenshot 2023-04-14 at 16 34 01](https://user-images.githubusercontent.com/115982880/232074294-13f61518-8e52-4920-a4a5-1dc7c5184e40.png)

### User B opens the link and can access provided information.
![Screenshot 2023-04-14 at 16 33 17](https://user-images.githubusercontent.com/115982880/232074298-09da29fd-1081-4854-803c-199501e5684f.png)

Background:
There is an archived repro: https://github.com/MichaelThessel/pwx which seems to be the base of https://pwx.psmanaged.com/

**Comment by AlexAndBear** [comment]
This feature didn't get any attention yet. And I don't know if this fits in the owncloud file share ecosystem at all. 
Closing for now.
