### ISSUE TITLE
refactor user/group/link/spaces stores for e2e tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#8819]
We have two different types of "stores" in the e2e tests:
1. **dummy-data-store**: They are used to keep data for dummies (users & groups). Only users/users that are in that store can be created by the tests. While creating a user/group, the data from the store is used to add to the users-details given by the tests. E.g. the test does not need to mention the display name of a user, it is drawn from the user-store.
2. **created-items-store:** They are used to remember which items are created during a test run and then to check the results in later step or to delete those items in the afterScenario, see #8662. We cannot use the dummy-data-stores for the cleanup task, because not all items in that store have been actually created.

In the current code both type of stores are called the same. userStore and groupStore are "dummy-data-stores", linkStore, spacesStore, etc. are created-items-store. (userRoleStore is again used a bit different)
I find naming those things similar very confusing and so I suggest to separate those concepts.
1. name the stores that are used for creating items something like `dummyUserStore`
2. name the stores that are used to remember created item something like `createdUserStore`

CC @ScharfViktor @fschade 
I think that way it would be much easier to understand what is needed for what and will make the PRs for #8662 much cleaner.

**Comment by amrita-shrestha** [comment]
refactoring has been done for the group and user store. No need to refactor space and link the store
