### ISSUE TITLE
create simple e2e tests for GDPR export

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#8824]
1. login
2. go to personal users page
3. click GDPR export button
4. check that the API request is send
5. wait till report is generated, or alternatively create the export file by a WebDAV upload
- I wouldn't wait in the e2e 
- I check message
<img width="375" alt="image" src="https://user-images.githubusercontent.com/84779829/232455272-4c2f6224-bf21-421d-9601-7762f3bf6073.png">
- don't wait propfind response. create mock for response and check download button (waitForResponse HEAD)
<img width="289" alt="image" src="https://user-images.githubusercontent.com/84779829/232455514-6528cc3f-b21a-4d1b-936f-8b1d4cd1aa55.png">
- checking  new  export generation `Request new export`
7. check that link to the file is correct

CC @ScharfViktor

**Comment by ScharfViktor** [comment]
closed #8865
