### ISSUE TITLE
[files-app] context menu: use consistent spaces icon

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8836]
### Steps to reproduce
1. mark (multiple) files
2. right click

### Expected behaviour
"Create space from selection" uses the common spaces icon (filled)

### Actual behaviour
Context menu item uses inverted icon style.

<img width="626" alt="Bildschirmfoto 2023-04-17 um 16 32 30" src="https://user-images.githubusercontent.com/16665512/232518836-6baefe33-3b46-4aec-ba72-4a7128d9c050.png">

**Comment by JammingBen** [comment]
The same applies to the trash bin icon. IMO it's fine as it is because it's consistent in the environment itself: left sidebar uses "regular" icons, actions use outlined icons. If we change the space icon in the context menu, we need to change all icons.

@tbsbdr @kulmann opinions?

**Comment by hurradieweltgehtunter** [comment]
Hm ok, understood.
@JammingBen you are completely right, it also applies to the trashbin icon. But the spaces icon stood out to me because `Spaces` is this own entity, it feels like a brand with a fixed name (which is good IMO!) and therefore I expected the icon to be fixed as well.

Not sure how to tackle this and since it's not a big thing, keep it like it is.
