### ISSUE TITLE
Create space on selection: Re-Write dialog text

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8838]
### Steps to reproduce
1. Select (multiple) files
2. open context menu
3. click on "Create space from selection"

Dialog contains this text: `The content will be copied.`
Which should be re-written to `The marked elements will be copied.`
Since there is no space yet, there is no content to be copied. Marked files and folders will be copied.

**Comment by kulmann** [comment]
There's actually two different modes of the modal:
1. You select a folder. The **content** of the folder will be copied into the new space.
2. You select a file or multiple files/folders. The **selection** will be copied into the new space.

The fact that you opened this issue makes clear that this is too subtle. Needs to be improved...

**Comment by kulmann** [comment]
Ah, maybe ignore my comment above...

`The content will be copied.` is supposed to express that no metadata will be copied. I.e. if you have created shares, links, tags, etc on or inside the selected files those will NOT be copied to the space. Any idea how to improve wording in that regard?

**Comment by hurradieweltgehtunter** [comment]
Ok, thanks for the hint. I wasn't aware that the copy mechanism changes if a single folder or multiple elements are selected. IMO initiating the same action should always have the same output. But that's another topic.

IMO `The marked elements will be copied` provides sufficient information. If we need to, we could add sth. like `Shares, Links and Versions will not be copied`

What about file versions, though?

**Comment by JanAckermann** [comment]
>What about file versions, though?
File versions  and Tags won't be applied as well

**Comment by hurradieweltgehtunter** [comment]
So, after I organized my files with tag, copied them to a new space and search for a specific tag I'll find one file but not the copied one? Even it's the same file? ooff ... isn't that messy?

**Comment by kulmann** [comment]
> So, after I organized my files with tag, copied them to a new space and search for a specific tag I'll find one file but not the copied one? Even it's the same file? ooff ... isn't that messy?

For this first iteration of the feature, yes, that's what happens. No metadata of the files will be copied.

We could introduce an addition to the feature like a checkbox in the modal (might even be checked by default) `Recreate tags on copies`. For that to be done in an efficient way we need backend involvement. Therefore -> feature request.

**Comment by hurradieweltgehtunter** [comment]
ok let's not overcomplicate it. Back to topic: 
`The marked elements will be copied.` with an additional contextual helper text `Shares, Versions and Tags will not be copied` ok?

**Comment by JanAckermann** [comment]
Fine for me, will take care

**Comment by JanAckermann** [comment]
@kulmann not as easy as I tough as we use the createModal fnc here, can we add messageContextualHelperData to the oc-modal ?

**Comment by JanAckermann** [comment]
I think we can as we already has contextualHelper in the modal but this will be rendered quite under the message

**Comment by JanAckermann** [comment]
![image](https://user-images.githubusercontent.com/26169327/233247252-251c1d2d-44d6-4334-b96d-de439aafe606.png)
