### ISSUE TITLE
Modal background z-index wrong

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8843]
### Steps to reproduce
1. Initate some action to open a modal

### Expected behaviour
The modal background overlays all elements; further navigation is not possible as long as modal stays open.

### Actual behaviour
Top nav bar is not overlayed For example clicking on the avatar opens the account menu. 

<img width="1212" alt="grafik" src="https://user-images.githubusercontent.com/16665512/232713148-55f2661a-2c0d-4c6f-bf3e-d7fbf12e609e.png">

Furthermore it is possible to navigate away, resulting in this:

<img width="1171" alt="grafik" src="https://user-images.githubusercontent.com/16665512/232713425-b703bf63-7453-48f5-82c9-541066f123fa.png">

Fix by
```
.oc-modal-background {
  z-index: 5; // current value: 4
}
```

**Comment by kulmann** [comment]
Addition to your proposed solution: We have an `--oc-z-index-modal` variable (default: 9999). We should apply that instead of a hardcoded number. Wondering why we don't use it there... 🤔
