### ISSUE TITLE
To create a new GDPR report, the user needs to reload the page

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#8862]
Steps

- generate GDPR export: go to account page -> click by request new export button
- wait generation GDPR export
- click by `Request new export`
- wait for new export

Actual: new export appear only for reloading page

Expected: after generating a new file  `.personal_data_export.json`
![image](https://user-images.githubusercontent.com/84779829/233062273-2c08599f-2170-4dcd-a6f6-6201095d94d9.png)
`download export` updates

**Comment by JammingBen** [comment]
There is active polling every 30 seconds, so the user does not have to reload the page. Ideal solution here would be that the server notifies the client about a finished GDPR export, but that's not possible currently.

**Comment by ScharfViktor** [comment]
> There is active polling every 30 seconds, so the user does not have to reload the page. Ideal solution here would be that the server notifies the client about a finished GDPR export, but that's not possible currently.

Yes, we wait 30 sec in the case `HTTP/1.1 425 TOO EARLY` and send new PROPFIND response

but in my case I get PROPFIND `<d:status>HTTP/1.1 200 OK</d:status>` after POST `https://host.docker.internal:9200/graph/v1.0/users/uuid/exportPersonalData` and web does't send new PROPFIND request

https://user-images.githubusercontent.com/84779829/233076863-eb77a660-6b2f-4c26-87f5-4792378f2b64.mov
