### ISSUE TITLE
[space trashbin] opening the sidebar of disabled space results in failing request

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8881]
### Steps to reproduce
1. Create space
2. Disable space
3. Go to "Deleted files" -> select space trash bin
4. Click on sidebar toggle icon

### Expected behaviour
Tell us what should happen

### Actual behaviour
Loading spinner keeps spinning. Request fails:
<img width="978" alt="grafik" src="https://user-images.githubusercontent.com/16665512/233439413-76c61fa4-bae7-4c50-b0c2-f502585a0e51.png">

Opening sidebar of enabled space shows:
<img width="425" alt="grafik" src="https://user-images.githubusercontent.com/16665512/233440164-59fdd2ce-d824-44a4-bfbe-07f792ec63c9.png">

**Comment by JanAckermann** [comment]
Huh? Shoudn't be possible at all do navigate into the trashbin of a disabled space, let me check =)

**Comment by hurradieweltgehtunter** [comment]
interestingly, entering a trash bin of a disabled space won't show any deleted files.
But I can see, you are already on it :)
