### ISSUE TITLE
[files-app] share indicator icons wrong

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8894]
### Steps to reproduce
Make sure to have 2 folders or files existing, both not shared.

1. Select folder, open right sidebar
2. Share folder with person X, hit "Share"
3. Click on "Copy Quicklink" of another folder in file list

### Expected behaviour
Share indicator icons in file list:
- First folder should have the "Shared with people" icon
- Second folder should have the "Shared via link" icon

### Actual behaviour
First folder: ok ("Deutsch" in Screenshot)
Second folder magically got both icons ("Shared with people" and "shared via link") ("Mathematik" in screenshot)

![grafik](https://user-images.githubusercontent.com/16665512/233953274-a02abd6b-2db1-4710-a3b3-1918f04e57e2.png)

Reloading the page shows correct icons

**Comment by JanAckermann** [comment]
Hmm works fine on latest master 
![image](https://user-images.githubusercontent.com/26169327/234196770-fb08a0b7-55e3-4684-a6cc-1a514daa5589.png)

**Comment by hurradieweltgehtunter** [comment]
https://user-images.githubusercontent.com/16665512/234197614-ffe8dbd6-4217-4b12-8613-30b53b00cd94.mov

**Comment by JanAckermann** [comment]
Latest master:

https://user-images.githubusercontent.com/26169327/234199376-41f9e74a-253b-469c-b7a9-2b433e0c2a5d.mp4
