### ISSUE TITLE
[account settings] wrong language selected

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8895]
Make sure to have a non-english browser language set, in my example german

### Steps to reproduce
1. Login with new user (first login)
2. Go to account settings

### Expected behaviour
Language selection box should match the language in use

### Actual behaviour
UI is in german but language selector shows "english"

![grafik](https://user-images.githubusercontent.com/16665512/233955541-c4a44b09-4afb-4d6f-99ab-77ada2d97063.png)

**Comment by kulmann** [comment]
> As far as I know this happens because English is being set as default language in oCIS: https://github.com/owncloud/ocis/blob/master/services/settings/pkg/service/v0/settings.go#L161.
> 
> @kulmann What do you think, maybe we just ignore that setting in Web and display the current language if no language is set for the user?

The code you referenced defines basically the "recommended default option", but oCIS doesn't apply the recommended default. IMO fine to ignore the default. I see two options:
1. select the browser language if it is present in the list. con: what do you select if the browser language is not present in the list?
2. add a new option `browser language` which is selected if the backend doesn't have a value for the setting (= the default). con: users will expect that they can switch back to the undefined value / `browser language` option and to my knowledge that's not possible.

Pick any of the two as a short term solution. ;-)

My preferred option is 3: convert the single choice setting to a string setting in the settings service code base and just show the languages in a dropdown in web that we already have defined in the web runtime. That way we wouldn't need to define in the ocis code base which languages are supported by web (which is quite controversial at the moment) and could easily fall back to an empty string for using the browser language.

**Comment by tbsbdr** [comment]
Adding to @kulmann `s option 1)
> what do you select if the browser language is not present in the list?

How about showing then showing a "Select ..." as placeholder?
![screenshot_000846](https://user-images.githubusercontent.com/26610733/235076381-67b724ba-c370-41f3-bf34-29a2dbc10551.png)

**Comment by JanAckermann** [comment]
We could hack a little more, this applies if no lang is set in accounts settings service (bakend):

1. extract locale by navigator.language 
2. lookup if the language is existing in the lang settings (backend?
3. If yes, pre-select in select box, if now -> please choose

**Comment by JammingBen** [comment]
> extract locale by navigator.language

This is actually handled already when the translations are being loaded. Can't remember exactly how it's called, `currentLanguage` or so. But that needs to be the fallback IMO! So your 1. and 2. need to be switched, otherwise the browser language overwrites the setting, no?

**Comment by JanAckermann** [comment]
We do for sure talk about different things, I just talk about the selection in the accounts setting. 

Maybe its clearer to you if you have a look in to the pr 
https://github.com/owncloud/web/pull/8958

**Comment by JammingBen** [comment]
> We do for sure talk about different things, I just talk about the selection in the accounts setting.

Yes, exactly what I was talking about and also how you implemented it :) Besides `navigator.language` which I want to avoid - that was my point.

**Comment by JanAckermann** [comment]
Ok, you was talking about that variable, ya that's mostly the same but better to use the current language if its already there, not implemented was about the setting to currentLang if no setting exists. But this has also some downsides but those are a little bit edge-case like

**Comment by JanAckermann** [comment]
@JammingBen unfortunately default language is not exposed via useGettext and I don't think we can use language.current because this might fallback to en if its some locale we don't have in our translations so, navigator.language seems to be the way to go

**Comment by JanAckermann** [comment]
> Yes, exactly what I was talking about and also how you implemented it :) Besides navigator.language which I want to avoid - that was my point.

Would love to avoid that to, but I have valid points, why we cant avoid that

**Comment by JammingBen** [comment]
> because this might fallback to en if its some locale we don't have in our translations so

But isn't that exactly what we want? If my browser language is not supported, OC will be displayed English -> show English as currently selected option on the account page, no? Why would we show the browser language if the current language is actually English?

Anyway, it's late, maybe I'm thinking in the wrong direction here - you'll find a proper solution I'm sure 🙂

**Comment by JanAckermann** [comment]
checked that, if browser lang is zh language.current will also be zh, this means that we will show the "Please choose..."  placeholder. if we don't want to show the 'Please choose...' at all like @tbsbdr had proposed, we might fallback to the defaultValue which is English

@tbsbdr please decide. 

I am off now for some beers :beers:

**Comment by JanAckermann** [comment]
So I had a little finding: 

I've set my browser language to AR, this is a language we don't support in web, but in transifex are translations.
So web will render texts partly in Arabic. 

If we would set the language in the account page to the default language: English, it would be quite confusing to the user.
As they need to choose another language and then select English again to really get the full English version of web. 

So I suggest the following (basically what  @tbsbdr had proposed):

If the user doesn't have a selected language in the settings, check the browser language, if it's supported by web (server options) set it as the selected option, otherwise show "Please choose". 

My PR implement that.

(PS: speaking of web sounds so strange, I would love to have a code name for that,  I am not very imaginative  but Phoenix sounds quite nice :p )
