### ISSUE TITLE
[files-app] Quicklink not displayed after creation

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8896]
Make sure to have 2 files/folders existing, both not shared

### Steps to reproduce
1. Open right sidebar for file/folder 1, panel "Shares"
2. Click on Quicklink icon in file list for file/folder 2
3. Right sidebar switches, Notification toast pops up "Quicklink was copied"

### Expected behaviour
Quicklink is also displayed in the Quicklink input field

### Actual behaviour
Link is missing in Quicklink input

![grafik](https://user-images.githubusercontent.com/16665512/233956408-24718657-8787-4f0c-b7e7-a66d9686c738.png)

Reloading sidebar results in quicklink gets displayed, so should be a updating the sidebar issue.

**Comment by JanAckermann** [comment]
Huh, works for me ?

**Comment by hurradieweltgehtunter** [comment]
![grafik](https://user-images.githubusercontent.com/16665512/234196776-3fa7e631-636f-48b1-a2ac-4734e6631313.png)

https://user-images.githubusercontent.com/16665512/234196768-1039db44-89af-43c6-9758-3d3b631f30bf.mov

**Comment by JanAckermann** [comment]
Latest master:


https://user-images.githubusercontent.com/26169327/234198611-a17dd1ed-4f7c-4fc4-a1ed-141d5a7ffb1e.mp4

**Comment by hurradieweltgehtunter** [comment]
![grafik](https://user-images.githubusercontent.com/16665512/234199158-2c045dae-84b6-469d-9d4f-dec901242d54.png)

**Comment by JanAckermann** [comment]
works fine here:

![image](https://user-images.githubusercontent.com/26169327/234199863-4c65dd7a-02dc-4bf3-867c-d4612ed89005.png)

**Comment by hurradieweltgehtunter** [comment]
dang FF...

ok see the difference how you and I create the quicklink. You are using context menu -> quicklink. I use the quicklink icon in the file list.

**Comment by JanAckermann** [comment]
Oh ya you are right, but doesn't affect the result for me =) using the quick icon also creates a share link in the right sidebar

**Comment by hurradieweltgehtunter** [comment]
hm strange. For me there is a difference. as discussed, let's have a screenshare later
