### ISSUE TITLE
[Sharing] Cannot change sharing link permission to editor

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8900]
### Steps to reproduce
1. Create sharing link for resource
2. Set role to "Editor"
3. Enter password in modal, save

### Expected behaviour
Password gets saved, link role is changed

### Actual behaviour
Link change request fails, request returns 403

Tested with two separate users, both admins

**Comment by micbar** [comment]
This is working fine on ocis vanilla (3.0.0-rc.1)

We had a policy on the test deployment which was too greedy. Fixed.
