### ISSUE TITLE
No scrolling possible in admin views

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#8901]
### Steps to reproduce
1. Create a few users
2. Change the viewport
3. No scrolling possible

### Expected behaviour
Scrolling is possible in users, spaces and groups view

### Actual behaviour

https://user-images.githubusercontent.com/33026403/234130139-37c9e680-cb8a-4102-abad-72221ae9a0a4.mov

### Environment
3.0.0-alpha.2+72d5566fd
7.0.0-rc.32

**Comment by JanAckermann** [comment]
Already fixed

**Comment by kulmann** [comment]
> Already fixed

To add more detail:
- fixed in https://github.com/owncloud/web/pull/8893
- will most likely be deployed to demo instances today

**Comment by ChrisEdS** [comment]
Thanks @kulmann
