### ISSUE TITLE
Some items in files context menu cannot be reached

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#8917]
### Steps to reproduce
1. create a space (I could not reproduce the issue with the personal space)
2. upload multiple files to the space
3. check the context menu of every item

### Expected behaviour
all items of the context menu of every item should be reachable

### Actual behaviour
There is one particular file, where the bottom of the context menu is not reachable
![image](https://user-images.githubusercontent.com/2425577/234547844-26dbd2cd-efdb-4199-bd9c-775e97d4f376.png)

### Environment general
**Operating system**:
tried on Ubuntu

**Backend (ownCloud Core or Infinite Scale)**:
infinite scale

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Environment ownCloud Infinite Scale
**Version:**
3.0.0rc1

**Updated from an older Infinite Scale or fresh install:**
fresh

**Where did you install Infinite Scale from:**
https://download.owncloud.com

### Client configuration
**Browser:**
FF 112
 
**Operating system:**
tried on Ubuntu & Win 10

**Comment by kulmann** [comment]
Does the context menu not become scrollable?

**Comment by individual-it** [comment]
no, when I scroll, the whole file-list scrolls out of view, but the context menu stays where it is
![image](https://user-images.githubusercontent.com/2425577/234550911-0a97bff6-82d6-450a-bc3d-f5899ee1a087.png)
