### ISSUE TITLE
[web-app-search] No visible difference between folders and spaces in search results

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8925]
### Steps to reproduce
1. Make sure to have min 1 folder and a space created with the same name
2. Search this name in global search

### Expected behaviour
Saerch results are somehow differentiated based on their type (folder, space, ...)

### Actual behaviour
No difference visible

First search result in screenshot (top list and full view list) is a space, other are folders (see edit pen, rename possible for folders, not for spaces)

![grafik](https://user-images.githubusercontent.com/16665512/234604922-609efdb8-5dfa-477d-8a37-402a4a6f93c6.png)

Also, I expected that the dropdown result list would segment results based in their type (see top left "Files")

https://ocis.ocis-wopi.latest.owncloud.works

**Comment by hurradieweltgehtunter** [comment]
sth like this would be nice

![grafik](https://user-images.githubusercontent.com/16665512/234608520-a12ba340-c053-4755-b57a-0ef39d04bc7a.png)

**Comment by kulmann** [comment]
Doable by splitting the search provider in the files app into two different providers, one filtering out spaces from the result set, the other one filtering everything but spaces out. This would be reasonable effort for the search result preview. But we should consider the full picture here - hitting `Enter` the user lands on a search result page. That should take the same thoughts into account.

There are some more more or less related issues:
- https://github.com/owncloud/web/issues/5844
- https://github.com/owncloud/web/issues/7780

And there is also the idea that the search preview does even more segmentations:
- https://github.com/owncloud/web/issues/7099

Nice enhancement, but needs more concepting. :-)

**Comment by tbsbdr** [comment]
I'd stick to the scheme and show the following, if the result is Space:

1. display "Spaces" as Parent folder
2. show Space Image/Icon if 

![screenshot_000847](https://user-images.githubusercontent.com/26610733/235114278-d8e8063d-24ac-4b63-b097-22cba8cb74cb.png)

**Comment by JammingBen** [comment]
I stumbled upon this while fixing https://github.com/owncloud/web/issues/9022.

> Doable by splitting the search provider in the files app into two different providers, one filtering out spaces from the result set, the other one filtering everything but spaces out.

@kulmann Do we really need separate search providers for this? My current fix (https://github.com/owncloud/web/pull/9026) simply adjusts the existing search provider and returns the correct space resource if found.

**Comment by kulmann** [comment]
> I stumbled upon this while fixing #9022.
> 
> > Doable by splitting the search provider in the files app into two different providers, one filtering out spaces from the result set, the other one filtering everything but spaces out.
> 
> @kulmann Do we really need separate search providers for this? My current fix (#9026) simply adjusts the existing search provider and returns the correct space resource if found.

Your solution is good. 👍

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/web/pull/9026.
