### ISSUE TITLE
no scrollbar

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#8927]
### Steps to reproduce
1. go to the instance settings after creating some spaces / users
2. ensure your browser window is smallish

### Expected behaviour
you can scroll through spaces / users

### Actual behaviour
there is no scrollbar:

![image](https://user-images.githubusercontent.com/34452982/234625954-101c7eac-52c5-4ee2-a8e2-af3aec895459.png)

### Environment ownCloud Infinite Scale
**Version:** 3.0.0-rc.1

**Comment by kulmann** [comment]
Already fixed in https://github.com/owncloud/web/pull/8893 - will be included in ocis `v3.0.0-rc.2`.
