### ISSUE TITLE
Current-indicator for tile sorting has wrong color

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#8931]
The current-indicator in the sorting dropdown of the tiles view has a wrong color. It should be the same as in the share-role-select.

<img width="186" alt="image" src="https://user-images.githubusercontent.com/50302941/234775485-a3234324-1fbe-4ff0-97ab-5f8272c8c5f8.png">

**Comment by JanAckermann** [comment]
Looked also bad in dark mode
![image](https://user-images.githubusercontent.com/26169327/235105947-9ec3097b-a5b3-42c6-8520-43ca3b226ba7.png)
