### ISSUE TITLE
[Spaces] Context menu should not hide the three dots

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#8936]
### Steps to reproduce
1. Open the three dots menu
2. Change the browser window size
3. Open the three dots menu again

### Expected behaviour
The menu will open on the same position as before (right hand side to the three dots)

### Actual behaviour

https://user-images.githubusercontent.com/33026403/234812105-a42c11de-18fe-4b80-be0e-1999f8b94311.mov

### Environment general
Seen at https://ocis.ocis-web.latest.owncloud.works

**Comment by ChrisEdS** [comment]
In my opinion, the menu should always open 5 px to the right of the three dots if space allows.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/33026403/234812507-6067556e-b54c-4014-b626-9368a8b65787.png">

**Comment by JammingBen** [comment]
To clarify: You're talking about the horizontal position only, right? The vertical position needs to be changed because you don't have enough space to place the menu below when shrinking the browser window.

**Comment by ChrisEdS** [comment]
> To clarify: You're talking about the horizontal position only, right?

Yes

> The vertical position needs to be changed because you don't have enough space to place the menu below when shrinking the browser window.

I know :)

**Comment by ChrisEdS** [comment]
Seems only to be an issue on the first entries if the tile size is small. "Normally" the menu opens to the left. 

https://user-images.githubusercontent.com/33026403/234829515-d1acec6a-885a-4144-8b46-069ca69d9421.mov
