### ISSUE TITLE
Setting space description does not work after being deleted

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#8937]
### Steps to reproduce
1. create new Space "Player"
2. delete .space folder 
3. upload folder `.space/readme.md` with content "Football Player "
4. enable "set as space description" for readme.md file  
![Screenshot from 2023-04-26 16-38-59](https://user-images.githubusercontent.com/54478846/234554305-c2c00249-2b63-4abf-aa0e-f781f92dc50d.png)
5. success message "space description was set successful " displayed

### Expected behaviour
Content of readme.md file should be displayed
![Screenshot from 2023-04-26 16-43-24](https://user-images.githubusercontent.com/54478846/234555289-3a71e574-90d8-4eeb-a591-32efe181ac1e.png)

### Actual behaviour
![Screenshot from 2023-04-26 16-42-19](https://user-images.githubusercontent.com/54478846/234555091-53132c85-c52f-4f5a-b3b3-3c46f488e8bd.png)

### Environment general
**Operating system**: ubuntu 22.04

**Backend (ownCloud Core or Infinite Scale)**: ocis

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:** 3.0.0-rc.1+b5056958b

**Updated from an older Infinite Scale or fresh install:** fresh

**Where did you install Infinite Scale from:** github

**Comment by micbar** [comment]
@JammingBen You need to handle possible `425` status on the special items. Postprocessing is enabled, so the files are processed asnychronously. In the case of a full virusscan pipeline, it could take some time until the content of the special items is available for download.

**Comment by SwikritiT** [comment]
> # QA-TEAM TO-DO
> * [ ]  add tests coverage for this issue if possible

@ScharfViktor do we need to add e2e test coverage for this issue?

**Comment by ScharfViktor** [comment]
> So after uploading a file it needs to be explicitly "set as space image" or description via the Api.

IMHO I would cover this through api tests (if they don't already exist).

**Comment by amrita-shrestha** [comment]
already covered in the API test. SO closing this issue
