### ISSUE TITLE
User-Mangement: Emtpy PATCH request to graph/v1.0/users/<id> when updating role assignment

### ISSUE THREAD

**Issue by rhafer** [owncloud/web#8946]
When updating a user's role-assignment without changing any other user attribute the UI sends an uneeded empty PATCH request to `graph/v1.0/users/<id>` before sending the correct POST `graph/v1.0/users/<id>/appRoleAssignment`.
The unneeded PATCH request is a bit problematic when using a read-only LDAP backend for the users in graph, as we return a 403 when trying to update users in a read-only backend.

![image](https://user-images.githubusercontent.com/373399/234876974-e14ced53-dff7-4fa9-a160-7c51c8cc5e5e.png)

I can try to make the /user endpoint a bit smarter and ignore such no-op requests, but still we should not be sending it.

cc @JanAckermann

**Comment by JanAckermann** [comment]
Thx for report. There shouldn't be any additional req, let me fix that.

**Comment by JanAckermann** [comment]
@rhafer I am not able to reproduce it, is there anything you do differently than me?  

[approle.mp4.webm](https://user-images.githubusercontent.com/26169327/235069181-55e17476-2105-40cf-a7e8-51475397d79f.webm)

**Comment by rhafer** [comment]
> I am not able to reproduce it, is there anything you do differently than me?

No, was doing exactly the same. But it seems I used an outdated web in my test :facepalm: it's not longer happening after running `make -C services/web generate`
