### ISSUE TITLE
Antivirus: Upload overlay shows success, but file is not available

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#8953]
### Steps to reproduce
1. login to the 0001 schule instance
2. upload eicar test file `eicar_com.zip` (https://www.eicar.org/download-anti-malware-testfile/)
3. upload overlay says `eicar_com.zip` "item uploaded" + green ✅ but `eicar_com.zip` is not available in file list

![screenshot_000851](https://user-images.githubusercontent.com/26610733/235141360-a145cd80-0a84-45bd-8b1a-abf36a9d416a.png)

### Expected behaviour

- Don't communicate a success if the file is now available for the user; show error in upload overlay:
- `Virus found in eicar_com.zip. Upload not possible. Virus: [Win.Test.EICAR_HDB-1] `

![screenshot_000851](https://user-images.githubusercontent.com/26610733/235142741-9c89295d-89bc-4c68-a545-aaba4004676e.png)

### Actual behaviour
- Upload overlay says `eicar_com.zip` "item uploaded" + green ✅ but `eicar_com.zip` is not available in file list
- Notification shows correct error message

**Comment by kulmann** [comment]
Not an excuse for the UX, this is how it works at the moment. You're talking about two separate, asynchronous processes:
1. Upload = transferring the bytes to the server. That works.
2. Postprocessing (including anti virus check) = happens AFTER the upload. Causes a notification if a virus was found.

To streamline the UX into what you describe we need at least something like SSE. Or we would need to poll the file(s) after upload until the postprocessing is done. That would produce too much load.

Issue is not actionable. In the proposed state it's only an argument for moving on with SSE quicker....

**Comment by tbsbdr** [comment]
eh, yes. I remember... closing and I might reopen if we get SSE.
