### ISSUE TITLE
Datepicker: Can't distinguish selectable from unselectable dates

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#8955]
### Steps to reproduce
1. Wait until current date is not the first or last day of the month
2. open datepicker
3. selectable dates (in the future) are hard to distinguish from unselectable dates (in the past) because:
  - fontcolor and weight is almost the same for selectable and unselectable dates
  - unselectables show the same hover-effect and mouse-pointer on hover

![screenshot_000859](https://user-images.githubusercontent.com/26610733/235164667-516c4bd2-90a4-41fd-87f1-78ba2dfc1ac1.png)

### Expected behaviour
- unselectable on hover: dont show circle
- unselectable on hover: don't pretend to be selectable, ex via `cursor: not-allowed;`
- unselectable: set font weight to extra light (200)
- selctable: set font weight to bold (700)

### Actual behaviour
- Can't distinguish selectable from unselectable dates

**Comment by JanAckermann** [comment]
Good idea 😍
