### ISSUE TITLE
Current language is not highlighted in select field

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#8962]
"English" should be highlighted:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/50302941/235611620-512b0b34-01c9-4ee1-a8da-4dea2c6a6a50.png">

**Comment by JanAckermann** [comment]
not again :_;

**Comment by JammingBen** [comment]
Yeah :( I think our recent refactoring caused this.

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/8972.
