### ISSUE TITLE
link share icons inconsistent

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8963]
### Steps to reproduce
1. Share a resource via link
2. Check files view 
3. Check files view in Shares overview (Shared via link")

### Expected behaviour
Link share icons are consistent

### Actual behaviour
They are not

Files view "Personal":
![grafik](https://user-images.githubusercontent.com/16665512/235613405-59f85161-64ea-434a-8fcc-ccd2923fdc80.png)
Icons are styled via button style css classes

Overview "Shares" - "Shared via link"
![grafik](https://user-images.githubusercontent.com/16665512/235613503-f4c6a136-5a25-47e9-a311-65d90cad6df0.png)
Icons are styled via avatar-element css class

**Comment by JammingBen** [comment]
@tbsbdr I thought this was a desired behaviour. The "Shares" column in `Personal` includes share indicators, e.g. indicating that a resource has at least one link share. The "Shared with" column in `Shared via link` includes all available link shares, hence those are being shown as avatar. Showing multiple standard-blue indicators might be confusing as well, no? At least these indicators were not designed to represent single shares, but to indicate that a resource has been shared.

**Comment by pascalwengerter** [comment]
@tbsbdr I assigned you, please provide feedback and then I'm happy to act on it!

**Comment by tbsbdr** [comment]
thanks for the ping! I agree with what Benedikt said:

-  remove the Shared with column on the Shared via link page
