### ISSUE TITLE
[OCIS] Folder size diffrent on personal page.

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/web#8966]
### Description
Folder size is diffrent on personal page than the actual size.

### Steps to reproduce
1. upload a folder with more than 100 files.

### Expected behaviour
file size on personal page and inside the folder or actual size should be same.

### Actual behaviour
file size on personal page is diffrent than actual size.

[Screencast from 2-5-23 05:08:22 अपराह्न +0545.webm](https://user-images.githubusercontent.com/122071597/235653274-ae34e379-18d6-4650-9389-8c7e93081c69.webm)

### Environment general
**Operating system**: Ubuntu 22.04.2 LTS
**Backend (ownCloud Core or Infinite Scale)**: OCIS

### Environment ownCloud Infinite Scale
**Version:**: ocis-3.0.0-rc.1-linux-amd64

**Where did you install Infinite Scale from:**
https://download.owncloud.com/ocis/ocis/testing/3.0.0-rc.1/ocis-3.0.0-rc.1-linux-amd64

Web Version: web 7.0.0-rc.32

**Comment by JammingBen** [comment]
I'm closing here in favour of https://github.com/owncloud/ocis/issues/6215 as this looks to be a server issue. Thanks for noticing though, there is definitely something fishy.
