### ISSUE TITLE
Wording: Custom permission `Update` should be `Edit`

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#8999]
### Steps to reproduce
- set custom permissions for a share:
![screenshot_000898](https://user-images.githubusercontent.com/26610733/236800895-07afded4-4809-417c-b730-0a94a4537640.png)

### Expected behaviour
Please rename to "edit"
- for files
- for folders

### Actual behaviour
wording is `update`

**Comment by kulmann** [comment]
On `stable-7.0` branch or master?
