### ISSUE TITLE
The error message displayed when uploading an *.exe is not user-friendly

### ISSUE THREAD

**Issue by tschiebel** [owncloud/web#9002]
## Error description
The displayed error message when uploading a *.exe is not user-friendly.
![image](https://github.com/owncloud/ocis/assets/132444655/a4b8a899-3fb7-4b9c-a9cf-7befbb948ed2)

## Steps to reproduce
* upload exe file via drag and drop
* click on "Show Details" at the bottom right of the error message
*

## Expected behavior
Something like "The file of this file type could not be uploaded due to data security reasons. If you have any questions, please contact  support." should appear as an error message.

## Actual behavior
-

**Comment by micbar** [comment]
@kulmann @JammingBen Transferred from ocis

**Comment by kulmann** [comment]
Forbidden via file firewall, correct?

**Comment by micbar** [comment]
yes. We are sending a 403 response code without any body. We can easily change that.

**Comment by JammingBen** [comment]
> We are sending a 403 response code without any body. We can easily change that.

Voting for proper error messages provided by the server (Web already sends an `Accept-Language` header in these requests) or at least documented error codes that Web can handle.

**Comment by JanAckermann** [comment]
I strongly recommend that as well, if that's not possible because of any reason, we should work with error codes e.G errUploadSecurityIssueFileType
