### ISSUE TITLE
Margin in share-actions context menu is off

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9019]
Happens on master only, probably because of https://github.com/owncloud/web/pull/8983.

<img width="291" alt="image" src="https://github.com/owncloud/web/assets/50302941/16ac4ed2-d8ea-4b6a-82fa-e36c6ba6a7a4">

**Comment by JanAckermann** [comment]
![image](https://github.com/owncloud/web/assets/26169327/4df74522-7148-42d8-a565-0bb610dd744c)

not the case anymore
