### ISSUE TITLE
Share indicators missing after cut&paste (page reload needed)

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#9030]
With a `MOVE` request (in the ui: cut & paste) oCIS also moves the attached shares. ownCloud Web doesn't reflect that in the share indicators after successful `MOVE`.

### Steps to reproduce
1. Create a folder "test" and a folder "another test" (I did in a project space, but should be the same in a personal space)
2. Create a public link and a share on folder "test"
3. Select context action "Cut", navigate into "another test" and select "Paste"

### Expected behaviour
After successful `MOVE` the file list should reflect the share state in the share indicators because `MOVE` also moves the shares.

### Actual behaviour
You need a page reload to see the share indicators. The right sidebar sharing panel correctly shows the shares.

### Screenshots
<img width="1827" alt="Screenshot 2023-05-12 at 13 09 39" src="https://github.com/owncloud/web/assets/3532843/b396a5d5-7715-4abe-ba77-cfc6f5403aac">
<img width="1827" alt="Screenshot 2023-05-12 at 13 09 56" src="https://github.com/owncloud/web/assets/3532843/3b7d2c2e-77ac-4dd5-8949-3c4579475d62">

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/web/pull/9110.
