### ISSUE TITLE
File list footer info displays the info about hidden file even when the `show hidden file` option is disabled

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#9036]
### Steps to reproduce
1. Create a folder `newFolder`
2. Create a hidden file `.hidden.txt`
3. make sure that the `show hidden files` option is disabled

### Expected behaviour
The footer should only say that there's one folder as only one folder is actually visible. Something like `1 item in total (0 files, 1 folder)`

### Actual behaviour
The info about the `hidden file` is also displayed 

![Screenshot from 2023-05-15 14-41-31](https://github.com/owncloud/web/assets/41103328/d72816a0-a6c2-4f20-a2dc-ba7fce2cf771)

![Screenshot from 2023-05-15 14-42-46](https://github.com/owncloud/web/assets/41103328/73fc66c9-7344-45bc-b947-25848ff930ad)

### Environment general
**Operating system**: Ubuntu 22.04.2 LTS

**Backend (ownCloud Core or Infinite Scale)**: tested with OCIS but the bug exists in both

### Environment ownCloud Infinite Scale
**Version:** 3.0.0-rc.3+08797f705

**Comment by kulmann** [comment]
@tbsbdr do you agree with the expected behaviour? I do.

**Comment by JammingBen** [comment]
How do we handle the displayed folder size such case? Only show the size of the displayed items? While this would be doable when being inside a folder (because we calculate the folder size by accumulating all items inside), the size for a folder being returned from the server always includes hidden files. Hence we might get different folder sizes.

**Comment by SwikritiT** [comment]
I don't know if this will be of any help but the classic UI displays the information about hidden file like so

![Screenshot from 2023-06-12 09-30-36](https://github.com/owncloud/web/assets/41103328/9918f197-4856-40b3-b30c-545cd3fd5a27)
