### ISSUE TITLE
[FR] Implement single file upload on "paste" action in Web

### ISSUE THREAD

**Issue by hodyroff** [owncloud/web#9047]
When I have a file (picture) in the clipboard I like to go to the web frontend and use a "paste" action to upload.

Actual behaviour: Nothing happens
Expected behaviour: Upload happens as when I do drag & drop
Works in rocket.chat eg.

**Comment by lookacat** [comment]
It will only work for single files, multiple file selection pasting is not supported by browser for security reasons (just a hint to be clear what this feature will be able to do)
