### ISSUE TITLE
Browser hangs when selecting a lot of users in admin-settings

### ISSUE THREAD

**Issue by tschiebel** [owncloud/web#9048]
## Error description
Browser hangs.

## Steps to reproduce
* All 1239 users of a instance (0183) selected.
* Edit login as batch.
* Attempt to select "NO

## Expected behavior
All users can be deactivated by batch.

## Actual behavior
All users were selected after a long wait. However, the NO could not be clicked.

## Additional context
Epic says that the deployment is not yet complete, but the feature is available and also usable:
With smaller number (class with about 30 users) you could do the batch processing to deactivate and also to activate the login.

![image](https://github.com/owncloud/ocis/assets/132444655/ab01b945-7a3f-44fa-a2c7-21879f98287d)
![image](https://github.com/owncloud/ocis/assets/132444655/e88d6a4a-f4ee-4299-a05f-b9d7220ccbc4)
![image](https://github.com/owncloud/ocis/assets/132444655/35f6e1b6-3e29-42dc-88f0-bea9a78a1805)

## Comment
Browser crashes are annoying, but here the system was really challenged. However, I suspect that the instance 0183 itself (i.e. not only my browser frontend) was also damaged by this, because uploads of files failed afterwards (message for this is "unknown error"). The two screenshots with the filename Screenshot*.png in the attachment of this ticket could not be uploaded on 0183 anymore. The upload on instance 0146, on the other hand, worked.

**Comment by micbar** [comment]
@kulmann @JanAckermann we need to see what is feasible.

**Comment by JammingBen** [comment]
We re-fetch each user after the operation to ensure the data is up to date with the server. We could skip that, which would reduce the amount of outgoing requests by half. Instead we could simply re-load the users list. The only drawback I see here: the current selection gets lost. @kulmann What do you think?

**Comment by kulmann** [comment]
@JammingBen we also fetch each user individually (because we need to expand the drive data) upon selection. So things are going crazy even before any batch action is triggered.

Currently thinking about limiting the number of listed users to some amount (100? 200?) and enforce filtering with this. Maybe even show an empty list until filters have been applied.

**Comment by JammingBen** [comment]
True... although it makes me wonder why the dropdown-selection in the modal does not work after all users have been selected successfully 🤔  Either way, 1000+ rows per page without any pagination or lazy loading probably break under any circumstance.

**Comment by JanAckermann** [comment]
Exactly, we've talked a long while ago about server-side pagination, but not been implemented...

Client-side pagination is the way to go for now IHMO

**Comment by tbsbdr** [comment]
yes, lets try  a client side pagination / limit as temporary workaround with 200 max selected items.

**Comment by JanAckermann** [comment]
@tbsbdr talked with involved web team members -> 50 items per page seems to be quite reasonable

**Comment by JammingBen** [comment]
Not technically fixed, but mitigated by https://github.com/owncloud/web/pull/9119, so I'm closing here.
