### ISSUE TITLE
Images with the extension bmp: clicking triggers the download instead of the preview 

### ISSUE THREAD

**Issue by tschiebel** [owncloud/web#9050]
## Error description
For images with the extension bmp, a thumbnail is displayed, but clicking triggers the download instead of the preview. Instance pre production

## Steps to reproduce
* Click image.bmp
*
*

## Expected behavior
As with other images (e.g. jpg), a preview of the image is offered in a Drive image viewer.

## Actual behavior
Click on image.bmp triggers download instead of preview.

## Additional context
We have observed this only now on the VP. On the temporary training environment, the preview works.

**Comment by micbar** [comment]
@kulmann @JammingBen Config or code?

**Comment by kulmann** [comment]
Not sure. I can reproduce it in a vanilla ocis with an image of mime type `image/x-ms-bmp`. However, the `preview` app is configured in a way that this mime type should be supported.

Let's treat it as a web regression for now. Maybe the additional mime types config for the preview app is not working properly.

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9092.
