### ISSUE TITLE
User deactivated by the Drive admin will only get a screen after logging into the ByCS-IDM, which should not take them any further

### ISSUE THREAD

**Issue by tschiebel** [owncloud/web#9051]
## Error description
A user deactivated by the Drive admin will only get a screen after logging into the cloud-IDM, which should not take them any further.

## Steps to reproduce
* Drive-Admin sets "Login allowed"=No for a user in the administration portal of the drive.
* User logs in to the cloud-IDM and is redirected to their drive.
*

## Expected behavior
Error message such as "Your Drive access has been blocked" appears.

## Actual behavior
See message in screenshot.

## Additional context
Context to understand the problem

![2023-05-09 14_59_20-Window](https://github.com/owncloud/web/assets/26610733/a379f0e2-0b4d-47bb-a8bf-4030988a31d8)

**Comment by micbar** [comment]
@tbsbdr @kulmann IMO this works "as designed".  What could we do?

**Comment by kulmann** [comment]
For now this indeed works as designed. Web handles any user that can't login like this. If we want to have a dedicated screen for that it's an enhancement. Won't fix for ocis 3.0.0.

**Comment by tbsbdr** [comment]
possible reasons (to be tested):
- wrong school / user unknown to school
- user deactivated
- loged out after timeout


Error message propsal:

## Not loged in
Possible reasons could be: Logout for security reasons or account not active. Please try again in a few minutes or contact your Administrator.

**Comment by lookacat** [comment]
@tbsbdr what help page are you referring to, or should the "more" link to an url set in the config? Is there a default url?

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9263.
