### ISSUE TITLE
Long links in notifications are cut off

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#9053]
### Steps to reproduce
1. Open up the web ui with oC 10 as backend and log in as admin
2. See a notification with a lengthy url inside (see screenshot)

### Expected behaviour
Long url gets truncated or breaks into the next line or something similar

### Actual behaviour
url looks cut off

### Screenshot
<img width="395" alt="Screenshot 2023-05-16 at 12 52 32" src="https://github.com/owncloud/web/assets/3532843/9d7870c5-09dc-4e7b-8eaf-e3b7529e126d">

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9144.
