### ISSUE TITLE
Uploading 58G folder crash google chrome browser

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#9068]
### Steps to reproduce
1. quota has been set to no restriction
2. Upload a folder of size 58G 
[Screencast from 19-5-23 09:56:37 पूर्वाह्न +0545.webm](https://github.com/owncloud/web/assets/54478846/0fce3fac-21dd-45b9-9dfc-7fe23bb014f8)

### Expected behaviour
Google Chrome should not crash

### Actual behaviour
During the uploading process chrome report crash 

### Environment general
**Operating system**: ubuntu 22.04

**Backend (ownCloud Core or Infinite Scale)**: ocis

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:** master

**Updated from an older Infinite Scale or fresh install:** fresh

**Where did you install Infinite Scale from:** github

![Screenshot from 2023-05-19 09-48-58](https://github.com/owncloud/web/assets/54478846/5e9f2d03-cdf3-4df3-8a1b-ecda470e35fb)

**Comment by kulmann** [comment]
Closing as `wont fix`, this use case is not in scope for web. For such big uploads users should use the desktop client.
