### ISSUE TITLE
Resume upload after upload cancelled works but the upload information dialog is not correct

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#9080]
### Steps to reproduce
1. upload a large file `1-5gb`
2. Pause the upload
3. Cancel the upload
4. Re-upload the same file (upload resumes :heavy_check_mark: ) - but icon says `Resume upload` :x:
5. Click Resume icon
6. Let the upload finish - incorrect upload information :x:

![Screenshot from 2023-05-23 12-21-06](https://github.com/owncloud/web/assets/52366632/28d9a1f8-cdd2-4829-82d8-629ea15a012a)

### Expected behaviour
- Correct icon after file re-upload in the upload information dialog
- Correct information after the upload is finished

### Actual behaviour
[Screencast from 05-23-2023 12:05:22 PM.webm](https://github.com/owncloud/web/assets/52366632/b380aff0-15b0-41de-987a-44c0be649ddf)

## Web version
- `ownCloud Web UI 7.0.0-rc.37`
- built from `stable-7.0` branch

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9141.

**Comment by saw-jan** [comment]
The weird message is gone but there are still some issues:
- :exclamation: re-upload icon state is not the correct one
- :exclamation: upload successful but the file doesn't appear

https://github.com/owncloud/web/assets/52366632/81926359-7f1c-4f49-a79b-cf22c6f85fbb

CC @JammingBen

**Comment by saw-jan** [comment]
My web version is still rc39. Maybe my web build didn't work. I will re-test again

**Comment by saw-jan** [comment]
Ahh! My build was not correct. the fix works :+1:

**Comment by saw-jan** [comment]
- [ ] Enable e2e tests from `uploadResumable.ocis.feature`
https://github.com/owncloud/web/blob/e9d26bd413e9d85a07f1a0d8718f41ac5f2be88a/tests/e2e/cucumber/features/smoke/uploadResumable.ocis.feature#L18-L28

**Comment by SagarGi** [comment]
This issue has been fixed in `master` and `stable-7.0`. So moving to done.
