### ISSUE TITLE
QA: multiple pipelines for ocis e2e tests

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#9107]
We are in the good situation now, that we already have so many e2e tests for ocis that they run for approximately 20 minutes in CI (oc10 e2e tests run approximately 6 minutes).

Wish: could we split up the e2e tests in a reasonable way so that they run in multiple pipelines with runtime below 10 minutes? For the moment that would mean something like 3-5 pipelines (depending on which grouping of tests into one pipeline makes sense).

Edit: apparently it's only 15 minutes on a successful CI run for e2e tests ocis. But still, would be nice to always be below 10 minutes.

**Comment by saw-jan** [comment]
Done in https://github.com/owncloud/web/pull/9149
