### ISSUE TITLE
Mobile breadcrumbs for tablet-viewports in portrait mode

### ISSUE THREAD

**Issue by lookacat** [owncloud/web#9137]
### Steps to reproduce
1. Resize the browser to portrait tablet mode viewport
2. Desktop breadcrumb is too small to provide value

### Expected behaviour
Switch to mobile breadcrumb

**Comment by pascalwengerter** [comment]
@lookacat what's the definition of done here? Sounds like the existing mobile breadcrumbs just need to be displayed earlier?

**Comment by kulmann** [comment]
Definition of done is "find a good breakpoint for when to switch to mobile breadcrumbs/ back to desktop breadcrumbs"

**Comment by JammingBen** [comment]
Tested together with @tbsbdr , looks fine they way it is. Hence closing here.
