### ISSUE TITLE
Double items after moving a file with the same name

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#9152]
Version  3.0.0-rc.4+80b4e8574
7.0.0-rc.39

https://ocis.ocis-web.latest.owncloud.works/

Steps: 
- create `f1/test.txt`
- create `test.txt`
- move `test.txt` to `f1` with replacing

Actual: two items on page. need reload

https://github.com/owncloud/web/assets/84779829/11e816ee-f1b4-45e4-bfbc-b6c2d70bbe73

Expected: one file on page

**Comment by kulmann** [comment]
some details: the fileIds of the cut out file and the replaced file don't match, but web only upserts the file into its state by id.

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/web/pull/9510.
