### ISSUE TITLE
URI/access-denied

### ISSUE THREAD

**Issue by tschiebel** [owncloud/web#9179]
## Error description
URI/access-denied

## Steps to reproduce
Waiting for logout.

## Expected behavior
Using the custom css for the access-denied page.

## Actual behavior
Vanila CSS for the access-denied page

**Comment by kulmann** [comment]
@tschiebel @dj4oC I don't have the slightest idea what this issue is about. Please provide detailed input.

**Comment by JammingBen** [comment]
Closing here because of missing info. Feel free to re-open at any time.
