### ISSUE TITLE
Space creation does not block recurring event

### ISSUE THREAD

**Issue by dj4oC** [owncloud/web#9189]
### Steps to reproduce
1. click on "new space"
2. instead of clicking "create" press "RETURN" key as fast as you can

### Expected behaviour
only one space is created

### Actual behaviour
many spaces with the same name are created

### Environment general
ownCloud Web UI 7.0.0-rc.37 
Infinite Scale 3.0.0-rc.4 Enterprise

**Comment by dj4oC** [comment]
screencast:
https://github.com/owncloud/web/assets/115982880/4187cb85-c6c5-43ae-82ef-a907728583e4

**Comment by kulmann** [comment]
Thanks for your bug report @dj4oC - screen recording is not necessary, the steps to reproduce are perfectly self explanatory and the behaviour easy to reproduce. 👍 

This is kind of related to https://github.com/owncloud/web/issues/9183 - in general it seems like all our forms assume that your internet is fast. ;-) needs improvement quite soon in my opinion.

**Comment by kulmann** [comment]
Setting `p2-high`, not for this single example but for the problem in general.
