### ISSUE TITLE
e2e tests for app provider / `external` app

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#9191]
## Description
The app provider and with it our integration with office editors like `Collabora Online` or `OnlyOffice` is a fundamental part of the ocis product for collaborative work. As such it is important to have at least some minimal test coverage in the e2e test suite. We don't want to vendor test the applications, so let's keep the scenarios minimal. But such scenarios should always run in CI.

## Acceptance criteria
- add app provider with collabora and onlyoffice in the root level `docker-compose` stack for developers (so that running the e2e tests is possible locally... also beneficial for feature development)
- add app provider with collabora and onlyoffice to .drone.star so that the e2e tests can also run in CI :trollface: 
- add a basic test scenario in the `smoke` category for collabora and onlyoffice, each. steps should involve creating a document or spreadsheet (not both! decide for one! if one works the others work as well), add some content, close the editor again, create a public link, open the public link as anonymous user, open the document and check the content.

**Comment by kulmann** [comment]
cc @individual-it it would help me a lot and would give us quite the "release certainty increase" if your team could take over this task :heart: 
cc @ScharfViktor you probably want to be involved here as well 😇

**Comment by saw-jan** [comment]
Local setup and CI are done in https://github.com/owncloud/web/pull/9265 and https://github.com/owncloud/web/pull/9373 respectively.
Closing here.
