### ISSUE TITLE
cannot upload files to a folder that has a space at the end of the name

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#9207]
### Steps to reproduce
1. create a folder with a space at the end of the name (this is not possible with web, but can be done with the android client or simple curl command)
2. try to upload some file to that folder

### Expected behaviour
ether ocis should not allow to have spaces at the end of folder names - then this is an ocis bug - and not client should be able to do it
or web should be able to upload files to such folders

### Actual behaviour
web trims the last space of the folder name and sends the request to an non-existing folder. The upload fails with `Parent folder does not exist`

### Environment general
**Operating system**:
Ubuntu 22.04 / Android
**Backend (ownCloud Core or Infinite Scale)**:
ocis

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Environment ownCloud Infinite Scale
**Version:**
3.0.0 web 7.0.0

**Updated from an older Infinite Scale or fresh install:**
fresh

**Where did you install Infinite Scale from:**
docker

**Comment by individual-it** [comment]
DELETE operations are done on the correct name

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9282.
