### ISSUE TITLE
Update CERN links

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9210]
needs to be made possible via extension system

![screenshot_001219](https://github.com/owncloud/web/assets/26610733/d2a0153c-b35c-4bf9-9b44-b4d7bd766ab9)

fixed by: https://github.com/owncloud/web/pull/8473/files
relates to: https://github.com/owncloud/web/pull/9159/commits/88a2efa1c16835f406050ef8de4875c1e74b6ef2

**Comment by kulmann** [comment]
TODO: document in a central place how to enable the feature

**Comment by pascalwengerter** [comment]
@kulmann `isRunningOnEos` (which I supose is what enables this) is documented within https://owncloud.dev/clients/web/getting-started/#options

**Comment by dschmidt** [comment]
in fact: it's implemented in an app now: https://github.com/cernbox/web-extensions/blob/18a735e406e06828f741283ede5a00866aca470d/cernbox-integration/src/index.ts#L15

**Comment by dschmidt** [comment]
.. so it needs no config, the app just needs to be loaded

**Comment by pascalwengerter** [comment]
In fact "something like this needs to be documented", so I'd include it in #9892 and close here?
