### ISSUE TITLE
[QA] comma should not be allowed in tags

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#9223]
## Describe the bug

Tags are stored in an mpk file with the key `user.ocis.md.tags` as one comma separated value.
Thus the user interface should not allow commas.

## Steps to reproduce

* Start ocis 3.0.0 daily
* log in as admin, create a file, click open the three dots menu of the file
* start adding tags
![grafik](https://github.com/owncloud/ocis/assets/1108546/eefb4a6d-1c95-43ad-a824-e5d371580f29)
----

Tags entered with comma, fall apart. No warning or error appears (this time), that 'hello' is duplicate.
Note that we now have ` world` and `world` (with and without leading whitespace), but this is not distinguishable in the UI:
![grafik](https://github.com/owncloud/ocis/assets/1108546/79729d95-70c9-435b-b65b-0f00bc238ddb)

----
Enter the tag `hello,world` again.
![grafik](https://github.com/owncloud/ocis/assets/1108546/d5c840b2-2cd4-4d5f-a2aa-8baf18bd7353)

----

Click Save. This time it cannot be saved. An error occurs.
![grafik](https://github.com/owncloud/ocis/assets/1108546/1b87d3a4-9dbe-474f-9b88-00db92bf11dc)
----

## Expected behavior
Commas should be disallowed.
Not sure of leading and trailing whitespace should be accepted. Currently the backend accepts them - if so, the UI should somehow mark that.

## Setup

hetzner-deploy/deploy_ocis_bare_metal.sh

<details>
<p>

```console
OCIS_URL=https://ocis-claim-20230601.jw-qa.owncloud.works
ocis_fqdn=ocis-claim-20230601.jw-qa.owncloud.works
OCIS_VERSION_STRING=Version: 3.0.0-rc.4+7a4bc71e6
PROXY_HTTP_ADDR=0.0.0.0:9200
PROXY_TLS=false
OCIS_INSECURE=false

# OCIS_LOG_LEVEL=warn
OCIS_LOG_LEVEL=debug

## To go back to 3.0.0-rc3 behavior: https://github.com/owncloud/ocis/issues/6403#issuecomment-1567924356
PROXY_USER_OIDC_CLAIM=preferred_username 
PROXY_USER_CS3_CLAIM=username

OCIS_CONFIG_DIR=/etc/ocis
OCIS_BASE_DATA_PATH=/var/lib/ocis
```

</p>
</details>

**Comment by tbsbdr** [comment]
closing in favour of more actionable ticket: https://github.com/owncloud/web/issues/9224
