### ISSUE TITLE
Show separate tags if comma was entered

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9224]
### Steps to reproduce
1. enter "hello, world" as new tag
2. (formfield shows "hello, world" as single tag)
3. press "Save"
4. filelist shows "hello, world" as single tag ❌
5. refresh
6. fielist shows "hello" and "world" as separate tags ✅

( **Step 4: filelist shows "hello, world" as single tag ❌** )
![image](https://github.com/owncloud/web/assets/26610733/38751b75-b9f8-41fc-809b-55dce54cbab9)

### Expected behaviour

immediately reflect the user, that 2 tags will be created:
![image](https://github.com/owncloud/web/assets/26610733/b8baf5c3-6aab-4c87-980f-0ffdcc039b97)
![image](https://github.com/owncloud/web/assets/26610733/83ece209-8f56-4547-8cda-480734e5a801)

-  if a comma gets entered, show separate tags
- show tag 🏷️ icon instead of circle in form field and autosuggest

### Actual behaviour
- separate tags are only shown upon refresh

superseeds https://github.com/owncloud/web/issues/9223

**Comment by tbsbdr** [comment]
@lookacat 👆for you?

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/web/pull/9348.
