### ISSUE TITLE
sharing a folder with a group that the sharer is member of reduces the permissions on the folder

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#9225]
## Describe the bug

If a user shares a folder to himself by a group that he is member of, he cannot set all permissions when sharing that folder again

## Steps to reproduce

1. login as "einstein" to https://ocis.ocis-web.latest.owncloud.works
2. create a new folder
3. share that folder with "can view" permissions to "physic-lovers"
4. go to "Shares" and accept the share
5. view the details of the folder

## Expected behavior
as einstein is the owner of the folder, he should still be able to share it with all permissions
or maybe einstein should not be able to accept a share that he has shared out himself

## Actual behavior
after accepting his own share einstein can only share out the folder with "can view" permissions
![image](https://github.com/owncloud/ocis/assets/2425577/7ca553fd-3674-4394-96fa-6f80d31e4664)
![image](https://github.com/owncloud/ocis/assets/2425577/d4e6b01d-f201-4b3a-9f23-53634977b4b7)

## Setup

https://ocis.ocis-web.latest.owncloud.works

**Comment by kobergj** [comment]
Moved because web mixes up permissions. Please ping me if server also does something weird
