### ISSUE TITLE
Create EOS Projects on request

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9228]
# Description
relates to https://github.com/owncloud/web/pull/9159/commits/6b774f2dfad7f8097b80539db30cfa27a355d299

## User Stories

* > As CERN I want that Projects can only be created asynchronously upon request so that we can keep track of projects.

## Acceptance Criteria
- hide the space creation form for all users at all times (could already be fulfilled, because reva master doesn't provide permissions...)
- provide an option to put a custom button on the spaces overview:
  - needs custom label (technical detail for implementation: require translations for the label in config already, or do we use the additional translations feature?)
  - links to an external page (project creation request form)
  - button is available for all regular users (Button is not available for lightweight accounts)
- add documentation for how to provide custom translations (if we go that way for the button label translation)

Note: User gets notified about approved (created) Project via E-Mail Ticket

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

**Comment by kulmann** [comment]
@diocas @elizavetaRa is the project creation available for lightweight accounts?

**Comment by dschmidt** [comment]
> @dschmidt possible requirement for the extension system: custom button in the spaces overview

That's easy, more interesting is how to hide the default button 🤔

**Comment by kulmann** [comment]
> > @dschmidt possible requirement for the extension system: custom button in the spaces overview
> 
> That's easy, more interesting is how to hide the default button 🤔

It's automatically hidden if the user doesn't have the permission to create spaces. So we should probably make the default user permissions configurable.

**Comment by diocas** [comment]
> @diocas @elizavetaRa is the project creation available for lightweight accounts?

No

**Comment by JammingBen** [comment]
We currently don't see a good extension entry point here. https://github.com/owncloud/web/pull/9816 adds a custom component for CERN where the custom URL, label and potential permission checks can be handled.

This checks all the acceptance criteria of this issue, is that correct? @diocas

**Comment by tbsbdr** [comment]
we'll go with the hardcoded solution for now https://github.com/owncloud/web/pull/9816 
any other more generic solution would be useful for the product but must happen in the future;
