### ISSUE TITLE
Show EOS Projects as Spaces

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9229]
# Description

relates to: https://github.com/owncloud/web/pull/9159/commits/6b774f2dfad7f8097b80539db30cfa27a355d299

## User Stories

* > As CERN  we want to show existing EOS Projects as Spaces so that adaption costs are kept low.

## Acceptance Criteria
- Rename "Spaces" to "Projects" in the UI
- Show EOS Projects instead of Spaces  
- tbd

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

**Comment by tbsbdr** [comment]
@JammingBen can you confirm that the API is `graph/v.1.0/me/drives/?%24filter=driveType+eq+project` for listing projects only?

**Comment by diocas** [comment]
For now I think listing is enough (we don't have other features available to users at the moment). We would be interested in having the other Spaces goodies (like readme and image).
The admins as of now can share, nothing else. The user management is done in another platform outside of CERNBox.

**Comment by tbsbdr** [comment]
@diocas is there any todo for us on this ticket?

**Comment by tbsbdr** [comment]
Rename of Spaces can be done eg. via translations overrides , see https://github.com/owncloud/web/pull/8790
