### ISSUE TITLE
[ocis] search in file content button is cleared

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#9242]
The button `search in file content` gets cleared when a file from the search result is opened and closed.

### Steps to reproduce
1. Create a user
2. Create a file `textfile.txt` with the content `hello`
3. Enable the `search in file content` button
4. Search for the term `hello` from the global search bar
5. Open the file `textfile.txt` from a search result
6. Close the text file editor
7. Check the `search in file content` button

### Expected behaviour
Might be similar to this, the user can see the search result with `textfile.txt`
![Screenshot from 2023-06-15 14-17-07](https://github.com/owncloud/web/assets/8559121/474a84dd-143c-4290-bc91-6c8fbdd58b63)

### Actual behaviour
The button `search in file content` is cleared
![Screenshot from 2023-06-15 14-17-45](https://github.com/owncloud/web/assets/8559121/0bd2b28d-386d-4795-8ef7-46bf383a065d)

[Screencast from 15-6-23 12:23:57 अपराह्न +0545.webm](https://github.com/owncloud/web/assets/8559121/13541c83-485d-4cc4-9deb-8341e9793e40)

### Environment general
**Operating system**: Ubuntu 22.04

**Backend (ownCloud Core or Infinite Scale)**: OCIS

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:** Ocis: Infinite Scale 3.0.0+45a46ec25 Community
Web: ownCloud Web UI 7.0.0 

Services needed for full-text search:
`tika`: apache/tika:latest

Extra environment for OCIS
```
SEARCH_EXTRACTOR_TYPE: "tika"
SEARCH_EXTRACTOR_TIKA_TIKA_URL: "http://host.docker.internal:9998"
```
```
FRONTEND_FULL_TEXT_SEARCH_ENABLED: "true"
```

**Comment by ScharfViktor** [comment]
I cannot reproduce it on latest web (use https://ocis.ocis-web.latest.owncloud.works/)
I could not find the `search in file contents' button from `step 3' 

<img width="1101" alt="image" src="https://github.com/owncloud/web/assets/84779829/d54b53f8-2c82-4980-a049-c5c47156eae6">

**Comment by kulmann** [comment]
> I cannot reproduce it on latest web (use https://ocis.ocis-web.latest.owncloud.works/) I could not find the `search in file contents' button from `step 3'
> 
> <img alt="image" width="1101" src="https://user-images.githubusercontent.com/84779829/247045160-d54b53f8-2c82-4980-a049-c5c47156eae6.png">

https://ocis.ocis-web.latest.owncloud.works/ doesn't have a fulltext search (no tika in the deployment)
