### ISSUE TITLE
Provide alternative to store user language setting

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9243]
# Description

## User Stories

* > As a developer I need a way to store the user-language without the ocis settings api so that I'm not fixed to store the user-language via the the ocis settings-service. 

## Acceptance Criteria
- user language needs to be available in get request to /me in the graph api
- user language can be updated via patch request to /users/{id} in the graph api
- web needs to use these 2 requests for the user language (dont use the settings api any more)
- check if the query for `values-list` can be removed if only used for getting the current language
- web needs to provide a hard-coded list of all available languages. Currently:
<img width="380" alt="image" src="https://github.com/owncloud/web/assets/50302941/c0763eca-442f-4245-a04a-067ff82eb40a">

Note:  settings api should only be available internal via grpc
Note: needs backend change (for both ocis and reva master)

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

refers to: https://github.com/owncloud/web/pull/9159/commits/89949c33aaa53778735529deb296e6248f4d13e4

**Comment by butonic** [comment]
we should add the `preferredLanguage` property to the [libre graph user resouce](https://github.com/owncloud/libre-graph-api/blob/36bd0fafda7723996e9479de9331f527ac47a9ae/api/openapi-spec/v1.0.yaml#L2406-L2464) as it exists [in ms graph](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties):


Property | Type | Description
-- | -- | --
preferredLanguage | String | The preferred language for the user. The  preferred language format is based on RFC 4646. The name is a  combination of an ISO 639 two-letter lowercase culture code associated  with the language, and an ISO 3166 two-letter uppercase subculture code  associated with the country or region. Example: "en-US", or "es-ES". Returned by default. Supports `$filter` (`eq`, `ne`, `not`, `ge`, `le`, `in`, `startsWith`, and `eq` on `null` values)

**Comment by micbar** [comment]
Fine for me.

**Comment by tbsbdr** [comment]
relates to / blocked by: [Make `language` setting available via graph user (read & write) · Issue #5455 · owncloud/ocis](https://github.com/owncloud/ocis/issues/5455)

**Comment by 2403905** [comment]
1. @tbsbdr @micbar Are we keep the two-letter format 'en'  or move to the "en-US" ?

@butonic  
2. Could the available languages look like https://learn.microsoft.com/en-us/graph/api/outlookuser-supportedlanguages?view=graph-rest-1.0&tabs=http

**Comment by JanAckermann** [comment]
> 1. @tbsbdr @micbar Are we keep the two-letter format 'en'  or move to the "en-US" ?
> 
> @butonic 2. Could the available languages look like https://learn.microsoft.com/en-us/graph/api/outlookuser-supportedlanguages?view=graph-rest-1.0&tabs=http

we keep the two-letter format, but the API will accept and expose ISO lang codes as well

**Comment by JanAckermann** [comment]
Note: I updated the story points to 8 because its a little bit more complex than we thought first
