### ISSUE TITLE
Notification Settings

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9248]
# Description

## User Stories

* > As a user I want to be in control which notifications I receive so that I don't get spammed.

## Acceptance Criteria
- Resources can be marked as "watch" for each users, see https://github.com/owncloud/web/issues/9249
- User can disable/enable to receive events for watched items:
  - Shared: An item has been shared with you or you have been added to a Space
  - New: An item has been created or uploaded
  - Changed: An item has been changed
  - Deleted: An item has been deleted
  - Download: An item has been downloaded via a link for everyone
  - Upload: An item has been uploaded via a link for everyone
- Users can select, if they want to receive events via mail and/or In-App
- Users can select if they receive mails instantly, as a summary or never. Summary options are
  - Daily
  - Weekly

## Scribble:
![screenshot_002944](https://github.com/user-attachments/assets/c8c8d138-bcc6-4559-b377-699ee37303a6)

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

relates to https://github.com/owncloud/web/pull/9159/commits/9ffff2de54266f231e43e1e7e96e8110ae0ea7a5 also see: https://cernbox.docs.cern.ch/web/notifications/#activating-notifications

**Comment by LukasHirt** [comment]
Does this replace the notifications toggle that's already in place or should basically that toggle enable this new section?

![image](https://github.com/user-attachments/assets/c5fb75d2-c81d-4203-bde9-27f62c4fc4bb)

**Comment by LukasHirt** [comment]
> Users can select if they receive mails instantly, as a summary or never.

If the "never" option is selected, should it be still possible to toggle specific email notifications or should all of them be disabled?
