### ISSUE TITLE
O365: Open Non "Personal" Documents in View Mode per Default

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9255]
# Description

## User Stories

* > As a user who clicks on a presentation, document or spreadsheet outside my Personal folder, I want that the file gets opened in view-only-mode in O365 so that I don't apply changes accidentally.

## Value
- error prevention
- improve collaboration

## Acceptance Criteria
- applies only to documents that are stored outside the users Home Folder (= "Personal"), eg. Shares & Spaces
- click on presentation, document or spreadsheet opens O365 in view mode per default
- if the user wants to edit the file, he/she needs an extra click on "Edit" to switch to editing Mode 

**In view mode, switch to edit mode:**
![screenshot_001232](https://github.com/owncloud/web/assets/26610733/dcf3e0c4-f92f-4032-885c-2f4485b7afa8)

**In edit mode, switch to other modes:**
![246333658-7cfec590-de88-4904-a71b-1299e819d59c](https://github.com/owncloud/web/assets/26610733/d0f8f9d7-53bb-4c9e-a3ed-2cbb51d4adf5)

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

relates to https://github.com/owncloud/web/pull/9159/commits/2894f0cbe9a2c3515be87eb9fb4ed679f52e400a

**Comment by tbsbdr** [comment]
@kulmann makes sense for the product I'd say, do you agree?

**Comment by kulmann** [comment]
> @kulmann makes sense for the product I'd say, do you agree?

For Shares, including public links, I agree. But for Spaces I'm not fully convinced. At least it's more complex than that. I believe the wish for exceptions like "immediate edit mode if I'm the file owner" or "immediate edit mode if I'm the space manager" would arise quickly...

**Comment by JammingBen** [comment]
Implemented via https://github.com/owncloud/web/pull/9879. The new config option `editor.openAsPreview` needs to be set to enable this feature. It can either be `true` to enable it for all apps, or an array of apps, e.g. `['Office356']`.
