### ISSUE TITLE
[Web] Search on current folder

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9264]
# Description
relates: https://github.com/owncloud/web/commit/f22428c83d36b966654a78cf51d16dcf3401f37f

## User Stories

* > As CERN I only want to provide a filter for the current folder so that system load is kept low.

## Value
- if no backend side search is available, at least let users filter the current folder.
- prepare to register other search providers like elastic search

## Acceptance Criteria
- search providers can be registered as an extension  
- Add devdocs how to get started with extension registration for search

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

**Comment by kulmann** [comment]
@diocas @elizavetaRa please confirm our assumption that the preview (= drop down under the search input field) is sufficient and you don't need a search result page... or provide corrected acceptance criteria.

**Comment by diocas** [comment]
That is correct and corresponds to our current implementation.

**Comment by tbsbdr** [comment]
- Search can currently have different providers via a extensions
- in theory it should be possible that cern can register its own search (~ search only the current folder)
- needs testing if adding a different search provider works as described above

**Comment by JammingBen** [comment]
Closing here since it has been implemented (see https://github.com/cernbox/web-extensions/pull/22).
