### ISSUE TITLE
OCM App

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9268]
- relates to https://github.com/owncloud/web/pull/9159/commits/369a99fd65f415a68e3b76c840a334bcc7938c5b
- enable to run the app as extension
- provide an option to reuse components
- how to remove the patches regarding federated shares?
- Demo Video: https://www.youtube.com/watch?v=sXuMailUE9Y&t=35s
- In action on https://sm1.cernbox.cern.ch/ <-- cc @dschmidt

**Comment by tbsbdr** [comment]
should be committed here: https://github.com/cernbox/web-extensions

**Comment by tbsbdr** [comment]
daily
- @dschmidt can not currently test the app locally with data, so for now please ping @elizavetaRa so she can test new commits

**Comment by tbsbdr** [comment]
### Current: Account Type
![screenshot_001842](https://github.com/owncloud/web/assets/26610733/7cbc3661-b7a3-429d-a769-ec4f16bb8c79)

### OC10: Federated Account
![screenshot_001844](https://github.com/owncloud/web/assets/26610733/c44a1748-3fd7-4813-9391-1dd810b9bd05)

**Comment by kulmann** [comment]
@elizavetaRa and @diocas will discuss with the backend people if it's feasible to search through all account types at the same time. Might be that the request times will be too long to come up with an oc10-style invite.

**Comment by kulmann** [comment]
@elizavetaRa and @diocas stated in a meeting today that we can proceed with migrating their existing OCM app to the web monorepo.
Thank you :heart:
