### ISSUE TITLE
Advanced Search Features not available in web 7.0.1+ version

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#9270]
### Steps to reproduce
1. Create some files `testfile.txt`, `newfile.txt`, `testfile2.txt`, and add tag `tag 1` for `testfile2.txt` file
2. Type the `test` keyword and press enter in the global search bar

### Expected behaviour
Might need to be similar or the features are removed.
@ScharfViktor @kulmann

### Actual behaviour
The filter options are not showing on UI. Also for full-text search enabled the button `search in file content` is not showing up. The search option with the tag is not available.

`Web UI 7.0.0`
![Screenshot from 2023-06-19 12-19-17](https://github.com/owncloud/web/assets/8559121/fd4521eb-c001-40f3-ab4c-ed589f593858)

`Web UI 7.0.2`
![Screenshot from 2023-06-19 12-13-27](https://github.com/owncloud/web/assets/8559121/f2a22184-77bf-4bbf-b206-68c6609fde0d)

### Environment general

**Operating system**: Ubuntu 22.04

**Backend (ownCloud Core or Infinite Scale)**: OCIS

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:** Infinite Scale 3.0.0

**Comment by kulmann** [comment]
@grgprarup the search features are only available on web `master`, not on `stable`. The version info `7.0.0` in `master` is unfortunately misleading in that regard.
