### ISSUE TITLE
Tag selection dropdown remains open after selection

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#9281]
### Steps to reproduce
1. Create user `user`
2. Create or upload a file `textfile.txt`
3. Add a tag `tag 1`, `tag 2`, and `tag 3` to the file `textfile.txt` from the sidebar panel
4. Goto the search result page, from the global search bar
5. Select tag `tag 1` from the tag filter

### Expected behaviour
The dropdown must be closed when any `tag` is selected.

### Actual behaviour
The dropdown won't close when `tag` is selected
![Screenshot from 2023-06-22 10-12-21](https://github.com/owncloud/web/assets/8559121/f2fd4bab-59a6-4373-af13-3c47bcfe5d42)

[Screencast from 22-6-23 10:11:50 पूर्वाह्न +0545.webm](https://github.com/owncloud/web/assets/8559121/82f8068b-c557-405a-8bc3-226c7d04b8c2)

### Environment general
**Operating system**: Ubuntu 22.04

**Backend (ownCloud Core or Infinite Scale)**: OCIS-3.0.0

** Web **: Latest `master`

**Comment by saw-jan** [comment]
Maybe multiple tags can be selected and that's why the behavior is.

CC @ScharfViktor

**Comment by ScharfViktor** [comment]
> Maybe multiple tags can be selected and that's why the behavior is.

Probably yes, otherwise if you want to choose several tags you have to open dropdown again. which is less convenient

**Comment by JammingBen** [comment]
This is a single select, hence the expected behaviour to close the menu after selection is valid 👍

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/web/pull/9575.
