### ISSUE TITLE
Authenticated public links break uploads

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9298]
### Steps to reproduce
1. Create a folder with 2 resources
2. Create a public link for that folder
3. Open the public link in an authenticated context (or login on the public link page)
4. Navigate to your personal table
5. Upload a file -> it breaks because the request uses the public link token as auth token

**Comment by dschmidt** [comment]
c.f. https://github.com/owncloud/web/pull/9159/commits/a5b171726f9a0e123bb05aad175e3b493aebba68
