### ISSUE TITLE
Clean urls and spaces mock

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9308]
# Description

@elizavetaRa @diocas 
lets please clarify in this ticket whats happening in  [Clean urls and spaces mock](https://github.com/owncloud/web/pull/9159/commits/6b774f2dfad7f8097b80539db30cfa27a355d299) 

(Create Project reuqirement is described here: [Create EOS Projects on request](https://github.com/owncloud/web/issues/9228))

## User Stories

* > As a student searching for a good file sync solution

## Acceptance Criteria
- [ ] click on 3-dots of a project > trashbin navigates to Deleted files > Projects > [Projects]
- [ ]  Rename `Spaces` to `Projects`
- [x] #9865
- [ ]  Click on a Project navigates to CERNBox > eos > Project > a > [Project]
- [ ]  Project-overview: Project title is  `basename(this.$route.params.driveAliasAndItem)`
- [ ]  Route for trashbin is `/trash/eos`

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

**Comment by tbsbdr** [comment]
`show show FUSE/Windows/Direct Paths on Project-Details` will be implemented

waiting for cern backend:

- click on 3-dots of a project > trashbin navigates to Deleted files > Projects > [Projects]
- Rename Spaces to Projects
- Click on a Project navigates to CERNBox > eos > Project > a > [Project]
- Project-overview: Project title is basename(this.$route.params.driveAliasAndItem)
- Route for trashbin is /trash/eos

**Comment by kulmann** [comment]
Status on 26th of October: waiting for graph api implementation to be able to proceed here.

**Comment by dschmidt** [comment]
Basically the same requirements as here: https://github.com/owncloud/web/issues/9379#issuecomment-1783387828

Project title obviously also needs to be provided as drive name.

**Comment by JammingBen** [comment]
Closing here since this is finished on our side. @elizavetaRa @diocas please feel free to create a new issue if you run into any trouble.
