### ISSUE TITLE
Prevent tokeninfo request

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9310]
Issue for: https://github.com/owncloud/web/pull/9159/commits/7d70c676cddc746ce3917b0bf168ff348fa2eaa7

"_Our Reva backend doesn't implement it yet_"

**Comment by tbsbdr** [comment]
@d7oc asked why don't override the method so that cern would not need to implement it backendwise - would that be a possible solution @pascalwengerter @dschmidt ?

**Comment by JammingBen** [comment]
> @micbar we where wondering what the tokeninfo endpoint does - could you please tell what it does / is good for?

The endpoint gives information which is necessary for resolving the link in certain cases:

* It provides file ids which are necessary for https://github.com/owncloud/web/pull/9299
* It provides info if the public link is an `alias_link` which is needed for resolving internal links
* It provides info if the link is password protected

**Comment by tbsbdr** [comment]
hm okay, thx @JammingBen 
@dschmidt could you please outline what the endpoint should basically do / return in the case of cernbox? (return an empty object if none of the 3 functionalities above are used or alike? ) cc @labkode

**Comment by dschmidt** [comment]
In doubt `{}` is good for starters, I'm leaving the details of a more meaningful response to a backend person

**Comment by micbar** [comment]
# Examples

Usage:

curling the `unprotected` endpoint returns standard information
```
curl --insecure -X GET https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/tokeninfo/unprotected/jqDCLhaiyIvXZTp

<TokenInfo>
  <token>jqDCLhaiyIvXZTp</token>
  <linkurl>/s/jqDCLhaiyIvXZTp</linkurl>
  <passwordprotected>false</passwordprotected>
  <storageid>f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c</storageid>
  <opaqueid>c6378f93-0e2d-4f77-812b-a1b2b3ee04ae</opaqueid>
  <path/>
  <spacePath/>
  <spaceAlias/>
  <spaceURL/>
</TokenInfo>
```

curling a password protected link only returns minimal information
```
curl --insecure -X GET https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/tokeninfo/unprotected/jqDCLhaiyIvXZTp

<TokenInfo>
  <token>jqDCLhaiyIvXZTp</token>
  <linkurl>/s/jqDCLhaiyIvXZTp</linkurl>
  <passwordprotected>true</passwordprotected>
  <storageid/>
  <opaqueid/>
  <path/>
  <spacePath/>
  <spaceAlias/>
  <spaceURL/>
</TokenInfo>
```

curling the `protected` endpoint returns full information if user has native access
```
curl --insecure -X GET https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/tokeninfo/protected/jqDCLhaiyIvXZTp -u marie:radioactivity

<TokenInfo>
  <token>jqDCLhaiyIvXZTp</token>
  <linkurl>/s/jqDCLhaiyIvXZTp</linkurl>
  <passwordprotected>false</passwordprotected>
  <storageid>f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c</storageid>
  <opaqueid>c6378f93-0e2d-4f77-812b-a1b2b3ee04ae</opaqueid>
  <path/>
  <spacePath>/users/f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c</spacePath>
  <spaceAlias>personal/marie</spaceAlias>
  <spaceURL>personal/marie/c6378f93-0e2d-4f77-812b-a1b2b3ee04ae</spaceURL>
</TokenInfo>
```

curling the `protected` endpoint returns same information as `unprotected` endpoint if user does not have native access
```
curl --insecure -X GET https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/tokeninfo/protected/jqDCLhaiyIvXZTp -u einstein:relativity

<TokenInfo>
  <token>jqDCLhaiyIvXZTp</token>
  <linkurl>/s/jqDCLhaiyIvXZTp</linkurl>
  <passwordprotected>false</passwordprotected>
  <storageid>f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c</storageid>
  <opaqueid>c6378f93-0e2d-4f77-812b-a1b2b3ee04ae</opaqueid>
  <path/>
  <spacePath/>
  <spaceAlias/>
  <spaceURL/>
</TokenInfo>
```


curling the `protected` endpoint without authentication returns `401 Unauthorized`
```
curl --insecure -X GET https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/tokeninfo/protected/jqDCLhaiyIvXZTp

HTTP/1.1 401 Unauthorized
```

**Comment by micbar** [comment]
@dschmidt @tbsbdr @diocas I clarified the backend behavior.
