### ISSUE TITLE
“Preview” listed twice in Action menu

### ISSUE THREAD

**Issue by koebel** [owncloud/web#9317]
### Steps to reproduce
1. Click on any resource of a file type that can be displayed in preview app (jpg, png, etc.)
2. Option “Preview” appears twice in Action menu

### Expected behaviour
Preview option is displayed once

### Actual behaviour
Preview option is displayed twice

### Environment ownCloud Infinite Scale
**Version:** 7.0.2

![Screenshot_Actionmenu_Preview_Option_2times](https://github.com/owncloud/web/assets/8348693/46c0a23f-2a63-4de7-aa30-564a0837a84e)

**Comment by JammingBen** [comment]
Hmm this looks like a config issue to me. How exactly does your setup look like, are you running Web with our docker dev setup?

Web makes a request to `https://host.docker.internal:9201/config.json` to fetch the config from the server. If you check the server's response and look into `apps` and `external_apps`, there should only be one occurrence of `preview` (probably in `external_apps`):

```
{
    ....
    "apps": [
        "files",
        "text-editor",
        "pdf-viewer",
        "search",
        "external",
        "admin-settings",
        "webfinger"
    ],
    "external_apps": [
        {
            "id": "preview",
            "path": "web-app-preview",
            "config": {
                "mimeTypes": [
                    "image/tiff",
                    "image/bmp",
                    "image/x-ms-bmp"
                ]
            }
        },
       ...
    ],
    ...
```
