### ISSUE TITLE
Preview details in detail view of photo not fully displayed on mobile devices

### ISSUE THREAD

**Issue by koebel** [owncloud/web#9318]
### Steps to reproduce
1. Open any resource of a file type that can be displayed in preview app on a mobile device
2. preview details at the bottom are cut off on the right side because the div is not fully centered and thus some actions are cut off

### Expected behaviour
preview detail bar is centered and all actions are visible even on smaller devices

### Actual behaviour
on mobile devices rotate icon is cut off and thus this action is not accessible to the user

![Screenshot_Previewdetails_Detailview](https://github.com/owncloud/web/assets/8348693/9ef66510-ca22-4430-aff6-65b77f382f6a)

**Comment by koebel** [comment]
@grimmoc I think the issue are the 30px margin of .oc-position-medium
If you subtract that amount from .oc-position-bottom-center on the left, it seems to be ok

![Screen Shot 2023-07-05 at 16 16 32](https://github.com/owncloud/web/assets/8348693/1305691c-3241-4242-a1fa-5548e33e0015)

**Comment by grimmoc** [comment]
@koebel yes, I know. I am working on it. it also caused the bar to be off-center in desktop view
