### ISSUE TITLE
Notifications of outages

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9319]
Issue for commit
[Notifications of outages](https://github.com/owncloud/web/pull/9159/commits/a1f92acdb8131eb2219c07e2b0b2f4973fd12409)

@elizavetaRa you assess that this commit could be implemented as an extension - @pascalwengerter would you agree?

**Comment by elizavetaRa** [comment]
Yes, we have it here: https://github.com/cernbox/web-extensions/commit/cc7ed68d353ce02410a8e8738d043b371cd525aa

@pascalwengerter A question about quality of code of such extensions: is it better to live the empty <main></main> (only using "showMessage" on mounted)  or is there some other way to deal with it? And it there a recommended port to mount? I mounted on one that has "multiple" property.

**Comment by tbsbdr** [comment]
closing as not part of web merge project (rejected bucket)
