### ISSUE TITLE
tik-icon in permission tippy is cut off on small devices

### ISSUE THREAD

**Issue by koebel** [owncloud/web#9321]
### Steps to reproduce
1. share a resource with someone using the web interface on a mobile device or device with small screen with
2. click on permission level setting (can view, can edit, ...)

### Expected behaviour
full "tippy" box is displayed including tik icon on the right side of the blue box

### Actual behaviour
"tippy" box is cut off on the right side, tik icon is not visible

issue in "Personal":

![Screenshot_Cutoff_Permissions_Tik_Small_Devices](https://github.com/owncloud/web/assets/8348693/c388b218-8ecb-49ed-b81c-4d354d94be4c)

the same issue also applies with editing permissions in "Spaces" where on certain devices even text gets cut off:

![Screenshot_Permission_Settings_Spaces](https://github.com/owncloud/web/assets/8348693/300a93cb-98b7-494f-9005-a02da68f694c)

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9520.
