### ISSUE TITLE
Spaces overview: Thumbnail image is zoomed in

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9328]
### Steps to reproduce
1. Create a Space and set [this](https://cloud.owncloud.com/s/60x95j0FH680suW) image as Space Image
2. Space overview: Thumbnail image is zoomed in

Note: Happens only if you upload a big image with 3000px width, does not happen if you use a image with 500px width

![screenshot_001309](https://github.com/owncloud/web/assets/26610733/8494140e-37cf-43da-a59e-a8fcb09ef47f)

### Expected behaviour

- Thumbnail Image should be zoomed in (see correct behaviour on single Space Frontpage)

![screenshot_001310](https://github.com/owncloud/web/assets/26610733/b883bebe-f330-4191-97eb-580cf7247521)

**Correct behaviour on single Space Frontpage**
![screenshot_001311](https://github.com/owncloud/web/assets/26610733/c336e935-8c2c-4ca8-9ee3-af4f07ee6c9a)

### Actual behaviour
Space overview: Thumbnail image is zoomed in

**Comment by dschmidt** [comment]
I assume this depends on https://github.com/owncloud/ocis/issues/5179
