### ISSUE TITLE
To set an individual quota, the user needs to have logged in once.

### ISSUE THREAD

**Issue by shishouyuan** [owncloud/web#9330]
### Steps to reproduce
1. Create a new user.
2. Edit its quota.

### Expected behaviour
A default value can be set by the admin system-wide, and the quota can be set for a new user when creating the account.

### Actual behaviour
To set an individual quota, the user needs to have logged in once. It's impossible for an admin with a large group of users to handle this.

### Environment general
I think it's independent of environment.
**Backend**: Infinite Scale 3.1.0-next.2+038520778
**Web Client**: 7.1.0-alpha.1

**Comment by JammingBen** [comment]
@micbar This is a limitation by the server, right?

**Comment by micbar** [comment]
yes. The quota is a property of the personal space. The personal space will only be created during the first login of the user.

**Comment by JammingBen** [comment]
Okay thanks! @shishouyuan You can assign a default quota per user role, maybe this helps: https://owncloud.dev/services/proxy/#automatic-quota-assignments. I'm closing here as the Web client can't do anything other, sorry!

**Comment by shishouyuan** [comment]
@JammingBen Thank you.
