### ISSUE TITLE
Batch actions are too obtrusive

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9340]
### Steps to reproduce
1. Select 2 files
2. Batch actions are shown
3. Batch actions are too obtrusive (whole line changes, 5 outlined buttons appear)
Note: Not showing ex. the new/upload buttons sets the whole interface into a modal state, as you need to clear the selection to get back to the initial state with the new/upload buttons.

### Expected behaviour
- Primary Actions stay where they are (New / Upload / New User etc.)
- Batch actions are displayed in raw-button style
- Batch actions are also shown for single selected resources (we once removed this until we find a better solution which should be delivered with this issue)
- clear-section X is not shown (info is still available in info-panel)
- padding-x: 8px
- gap-size="small"

![screenshot_001320](https://github.com/owncloud/web/assets/26610733/10bd6c0e-2bd3-41be-adaf-049dedca7f58)
![screenshot_001324](https://github.com/owncloud/web/assets/26610733/ae90b52d-5011-40d6-8ef9-a7a1ef79f6e0)

### Actual behaviour
- Batch actions are too obtrusive
- batch actions put interface in modal state

**Comment by JanAckermann** [comment]
😍
