### ISSUE TITLE
Always display requestID when something fails

### ISSUE THREAD

**Issue by micbar** [owncloud/web#9342]
# Make Infinite Scale support easier

We are dealing with a highly distributed system. That means it is harder to debug errors in the backend.

Fur that purpose, we always log and trace the requestID.

## Proposal

Every time when an error occurs, we should display a copy&paste able Request ID to the end user.

This enables the end user to give the admin an entrypoint into the Logging and Tracing stack.

## Value

- Provide a good user experiance
- Provide the admin team a way to really address the issue

## Visual

@tbsbdr I was imaginating a "Details" dropdown link in every error message popup. That should contain the RequestID and a short explanation how to use that.

@d7oc @JRundfeldt @hodyroff @dragotin   FYI

**Comment by micbar** [comment]
Nice Idea.

From my POV this is a P1

**Comment by tbsbdr** [comment]
## Infos needed:
- X-Request-ID
- IDP Session ID
- time
- response code
- response body
- Web UI version
- Backend version

**Comment by d7oc** [comment]
Do we need all this information from the user? I would say one UUID as kind of anchor to find the logs should be sufficient the other information should be just in the logs. Don't know where this UUID could be so if e.g. the `X-Request-ID` can be used to determine a single failing call or if it might be reused. I just would like to limit the amount of information we need to get from the user. As we just need "something" to find the corresponding part in the log and take it from there.

**Comment by JanAckermann** [comment]
@tbsbdr could you please provide an mock-up that fits to the web?

I was thinking about showing this in the showMessage Toast

**Comment by tbsbdr** [comment]
@cdamken from your view: would it be sufficient to only provide the x-request ID or would you want "as much as possible infos" ?

**Comment by JammingBen** [comment]
Closing as this has been implemented meanwhile.
