### ISSUE TITLE
Search Preview Shows Folder Icon Instead of Space Icon

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9347]
### Steps to reproduce
1. create a space "New Space" that contains the folder "New Folder"
2. Search for "New"
3. Search Preview Shows Folder Icon Instead of Space Icon

![screenshot_001327](https://github.com/owncloud/web/assets/26610733/dc96f233-3f45-47b9-b9d1-915593d6b344)

### Expected behaviour
- "Spaces" and "New Space" should show Space-Icon

<img width="565" alt="screenshot_001328" src="https://github.com/owncloud/web/assets/26610733/f843782b-207c-4872-8bd3-c3c16620d4e5">

### Actual behaviour
Search Preview Shows Folder Icon Instead of Space Icon

**Comment by JanAckermann** [comment]
Good point, fixed in https://github.com/owncloud/web/pull/9349
