### ISSUE TITLE
Batch Actions: Raw Button Has No Hover-State

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9352]
### Steps to reproduce
1. Hover on Batch Actions
2. Raw Button Has No Hover-State
![screenshot_001341](https://github.com/owncloud/web/assets/26610733/83cbeb21-546b-4944-879f-fb2310480ca6)

### Expected behaviour
- Raw button should have hover (same as on view-options Icon: `--oc-color-background-hover`)
- `--oc-color-background-hover` should have the color of `--oc-color-background-highlight`

![screenshot_001349](https://github.com/owncloud/web/assets/26610733/353399dd-7a58-4bd4-89eb-0af8326eb35a)

### Actual behaviour

- Raw Button Has No Hover-State

**Comment by JanAckermann** [comment]
@tbsbdr sorry, if as you tagged that as good-first-issue, i feel this is mandatory for https://github.com/owncloud/web/pull/9346

**Comment by tbsbdr** [comment]
yes, well spotted 👍

**Comment by JammingBen** [comment]
@tbsbdr Maybe we should use `--oc-color-background-hover` as hover color to be consistent with other hovers? E.g.:

![image](https://github.com/owncloud/web/assets/50302941/77b5754e-ca4f-48b1-ba22-ec353f250668)

**Comment by tbsbdr** [comment]
I would like that the hover effect is bluish (rather than grey) so that it looks good within the outlined buttons as well. So this would mean to change the `--oc-color-background-hover` to a bluish color like the value of `--oc-color-background-highlight`

**Comment by JanAckermann** [comment]
@tbsbdr you mean like overall the whole ui?

**Comment by tbsbdr** [comment]
jup

**Comment by JanAckermann** [comment]
that's exceeding a little the title and the description of this pr ...

**Comment by JammingBen** [comment]
Also it would have a few side effects. E.g. there would be no visible difference between a selected and a hovered row like currently:

<img width="275" alt="image" src="https://github.com/owncloud/web/assets/50302941/e77293cc-f7b7-4302-94b7-9957cbbcc499">

**Comment by JanAckermann** [comment]
Anyways, this is far ahead of the issue's context, please open a new issue for that (good-first-topic is fine) and maybe we should keep track of the side effects and how to handle them
