### ISSUE TITLE
[oC10] Quota inconsistent with classic UI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/web#9375]
### Steps to reproduce
1. `admin:admin@demo.owncloud.com` sets `--data 'username=test&quota=1+GB'`
2. user `test` sees `You are using 0 B of 1 GB (0 %)` in classic UI
3. user `test` sees `0 B of 1.07 GB used` in new web UI

### Expected behaviour
Quota should be same in both frontends.

### Actual behaviour
Quota is different in both frontends.

### Environment general

```
% curl -s "https://demo.owncloud.com/status.php" | jq
{
  "installed": true,
  "maintenance": false,
  "needsDbUpgrade": false,
  "version": "10.12.2.1",
  "versionstring": "10.12.2",
  "edition": "Enterprise",
  "productname": "ownCloud",
  "product": "ownCloud"
}
```

```
[Log]  ownCloud Web UI 6.0.0  (web-runtime-f0fd7d61.js, line 1)
[Log]  ownCloud 10.12.2 Enterprise  (web-runtime-f0fd7d61.js, line 1)
```

![CleanShot 2023-07-10 at 18 33 49](https://github.com/owncloud/web/assets/214010/e5b69af4-3fa8-484c-b409-c7d3642d40ba)

![CleanShot 2023-07-10 at 18 34 06](https://github.com/owncloud/web/assets/214010/c826721b-c360-437c-aabb-20fdd33edb92) | ![CleanShot 2023-07-10 at 18 34 15](https://github.com/owncloud/web/assets/214010/0d67bae9-cd70-4f45-bb1a-0735a40d4669)
-- | --

**Comment by pascalwengerter** [comment]
Interesting 🤔 we pass the total quota announced from the backend through a `filesize` lib in https://github.com/owncloud/web/blob/1f09b73e435bfce8e05e0e0b47ee0a784263c850/packages/web-runtime/src/components/Topbar/UserMenu.vue#L197, if someone wants to take a closer look - great first issue

**Comment by michaelstingl** [comment]
Yes, decision here:
- https://github.com/owncloud/web/issues/5879

`Filesize.js` switched to `IEC 80000-13:2008` in 8.0.0, see their changelog:

https://github.com/avoidwork/filesize.js/blob/master/CHANGELOG.md#800

**Comment by michaelstingl** [comment]
New web UI reads quota in bytes, but classic UI for oC10 user management sets `quota=1+GB`
