### ISSUE TITLE
Sharing UI improvements

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9376]
relates to: https://github.com/owncloud/web/issues/9376

> New shared with me view with show/hide instead of accept/reject
> Improvements to sidebar sharing:
> * Renames "Public links" to "Share publicly"
> * Adds icon to role selected for better understanding
> * Adds direct link for internal shares
> 
> The change to accept/reject has been discussed and approved by oC

## to be defined / discussed
- ocis with auto-accept enabled behaves like oc10 auto-accept enabled

**Comment by tbsbdr** [comment]
@JammingBen you are already working on that, correct?

**Comment by JammingBen** [comment]
Yes I'm on it!

**Comment by JammingBen** [comment]
We've implemented a `portal-target` which will be filled via an extension: https://github.com/cernbox/web-extensions/pull/25. This means this is done on our side.
