### ISSUE TITLE
Shared with me/others/links views

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9379]
relates to https://github.com/owncloud/web/pull/9159/commits/49e125f81c023e1c71d772d72b346a1cc0ac3f35

> Shares will always appear as a space, which breaks opening single files shares with apps. It breaks because web was supposed to redirect to the universal url (all files), instead of a "share" url. I consider this to be broken in upstream, as this redirection was supposed to be supported.

**Comment by tbsbdr** [comment]
@elizavetaRa @diocas am I right that this should be fixed via https://github.com/owncloud/web/pull/9721 ?

**Comment by tbsbdr** [comment]
Pending on cern backend

**Comment by dschmidt** [comment]
> Pending on cern backend

to be more specific: this depends on loading drives via the Graph API. 

We at least need personal spaces, shares/mountpoints and projects. 

Mountpoints need their original space as remoteItem, including the driveId and root file id and currently also the path in the original space. 
We also need permissions (i.e. users and groups that are members of the drives) to determine if parent resources are accessible in breadcrumbs and when determining parent folders. If CERN can't provide these, they need to come up with an alternative approach to determine access rights (and members need to be loaded on demand for showing them in the sidebar)

driveAliases need to be provided in a way that correct urls can be resolved through the router. 
If the url for a project space root should look like `/files/spaces/eos/projects/c/cernbox/`, the driveAlias needs to be `eos/projects/c/cernbox`. likewise for personal spaces obviously
