### ISSUE TITLE
Automatically open single file share app

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9380]
~~relates to https://github.com/owncloud/web/pull/9159/commits/b29df6470ef943dd99807793412e188a80f1b973~~

> When opening the single file view, it automatically opens the default app.
> It was discussed that this would not come upstream, but apparently it's already there...

## Acceptance Criteria:

- auto-open should be enabled/disabled via config file

**Comment by tbsbdr** [comment]
question to @diocas @elizavetaRa 
- auto-open should be enabled/disabled via config file, right?

**Comment by elizavetaRa** [comment]
I'd say yes

**Comment by tbsbdr** [comment]
Daily
- Default for CERN would also be auto-open

**Comment by pascalwengerter** [comment]
> Daily
> 
>     * Default for CERN would also be auto-open

So is there a to-do left here? I noticed some ambiguity in the commit message the other day and wasn't sure whether CERN's needs are met already or not

**Comment by tbsbdr** [comment]
yes, added AC to initial post

> auto-open should be enabled/disabled via config file

Although auto open already fulfills CERNs use case, I would like to be able to have this configurable for the product. this could also be a good candidate for regular sprint story; do you agree @JammingBen?

**Comment by JammingBen** [comment]
Configuration is always nice on paper, but I feel like we shouldn't overdo it with configurable UI behaviour.  Especially since we already have the single-file-view itself configurable. So if auto-open is default for the product as well as for Cern, I'd prefer not having this configurable. Ultimately you decide though 🙂

**Comment by tbsbdr** [comment]
@elizavetaRa is making the auto-open behaviour configurable a mandatory for the CERN Web Merge Project?
If not I'd be fine having it not configurable until we receive crucial feedback / i.e. focus now on getting more important things done.

**Comment by elizavetaRa** [comment]
For us not mandatory, answered yes initially as I thought you want to disable auto-open on default

**Comment by pascalwengerter** [comment]
@tbsbdr shall we remove it from the CERN bucket list (or "check the box with a note"), then? The issue can be left open I suppose for future reference/implementation down the road

**Comment by tbsbdr** [comment]
clarified & checked ✅ linked the PR that solved the intend in the [bucket list](https://github.com/owncloud/web/issues/9278)

**Comment by tbsbdr** [comment]
Feature is configurable already via `WEB_OPTION_OPEN_LINKS_WITH_DEFAULT_APP`
