### ISSUE TITLE
Enable router-history-mode

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9382]
relates to d08394206a1a025be772d17892cea87b9874e317

> Enable router-history-mode

provide via buildtime html header partial

**Comment by dschmidt** [comment]
See discussion in #9278

**Comment by tbsbdr** [comment]
Daily
- web will be build by CERN so that the build flag can be set

**Comment by dschmidt** [comment]
will be added via vite.`cern.config.ts`
