### ISSUE TITLE
Batch actions on spaces list are missing margin

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9384]
### Steps to reproduce
1. Login as user
2. Go to "Spaces" in the left navigation
3. Create a new space
4. Select the space via the checkbox on the left -> the "download"-action is missing some margin to the left. It should be the same as in the "Personal" view

<img width="512" alt="image" src="https://github.com/owncloud/web/assets/50302941/d9ad9dfb-ed97-4d9c-b25e-5eff901eba74">

**Comment by tbsbdr** [comment]
Assessing as P3 because its very likely that this issue is quite visible and gives the impression of a slighlty "broken" app;
