### ISSUE TITLE
Provide nicer-to-read names for themes

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9403]
### Steps to reproduce
1. check out [Theme switcher for more themes by elizavetaRa · Pull Request #9396 · owncloud/web](https://github.com/owncloud/web/pull/9396)
2. select a theme
3. theme name is technical
![image](https://github.com/owncloud/web/assets/26610733/278e78d0-40c3-4f56-af47-507e1da35494)

### Expected behaviour
- Theme name should be non-technical
- Theme name should be translatable "High Contrast"

### Actual behaviour
theme name is technical

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9698.
