### ISSUE TITLE
User does not know that Tags are globally visible

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9416]
### Steps to reproduce
1. Create a tag
2. User does not know that Tags are globally visible (if 
![screenshot_001413](https://github.com/owncloud/web/assets/26610733/5f5004af-6dff-479d-8c93-5dcc1c546de4)

### Expected behaviour
User should know who can see Tags:
- Add Contextual Helper next to "Add or edit Tags"
  - Title: "Who can view Tags?"
  - Body: "Everyone who can view the file can view it's Tags. Everyone who can edit the file can edit it's Tags."

![screenshot_001413](https://github.com/owncloud/web/assets/26610733/73d98876-f21f-4349-896d-306d5ad14a5f)

### Actual behaviour
User does not know that Tags are globally visible

**Comment by tbsbdr** [comment]
@JammingBen please remove "good first issue" if this is not the case =D

**Comment by phil-davis** [comment]
And even if a user does not have access to any resource that has that tag, I think that the tag "string/name" can be seen by the user. For example:
- Alice tags a file in space "Special-Projects" with "Project-Three-Letter-Agency"
- and "Three-Letter-Agency" is not supposed to be known about in the wider organisation
- Brian has access to space "Special-Projects" and can see the tag - no problem
- Carol does not have access to space "Special-Projects"
- Carol starts to tag a files in one of her spaces. She types "Project-T" and "Project-Three-Letter-Agency" is displayed as a suggestion.
- the information in the tag name has been "leaked" more widely

So users need to be aware that they should not embed "private"/"confidential" information in a tag name.
