### ISSUE TITLE
Search location filter is modified after opening a file in the text editor

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#9428]
steps: 

Precondition: user has files with the same "content" in different places  (personal, project, shares jail)

Steps: 
- user searches files using fullTextSearch and `all files` filter
- open file from personal space in the text editor
- close text editor

Expected: `all files` filter in the search result. 

Actual: `current folder` filter in the search result. 

https://github.com/owncloud/web/assets/84779829/0a735e01-be71-42e6-94f7-f317f2247fbc

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/web/pull/9432.
