### ISSUE TITLE
[cloud import] Dark theme does not apply to uppy dashboard

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9452]
The dark theme does not apply to the uppy dashboard which is used for the cloud import. We should use our color tokens here.

<img width="472" alt="image" src="https://github.com/owncloud/web/assets/50302941/09b66917-f79a-4c7e-acc2-4e6d6e4c4e6e">

**Comment by dschmidt** [comment]
Especially the WebDav Formulars look pretty bad, we need to check whether we need to handle that in our upstream PR as well - somehow...

**Comment by dschmidt** [comment]
... oh and uppy has a dark mode as well, maybe we can just use that. We would need to tie it to our own dark mode switch then
