### ISSUE TITLE
[Search] Translation missing

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#9455]
### Steps to reproduce
1. Set language to any non-english language
2. Open location picker in global search bar

### Expected behaviour
Options are translated

### Actual behaviour
Options are not translated

![grafik](https://github.com/owncloud/web/assets/16665512/92774b03-46fc-49b2-aee7-cce4164bfd1e)

https://ocis.ocis-wopi.latest.owncloud.works

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9443, it's just not yet deployed.
