### ISSUE TITLE
Upload: It's unclear if upload is in progress

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9458]
### Steps to reproduce
1. login in on https://ocis.ocis-web.latest.owncloud.works/
2. download this testfolder `include` (~50 MB, 5.000 Files): https://cloud.owncloud.com/s/94r3BR3dttLPG9G
3. drag and drop `include` into the webinterface for upload
4. browser shows drop-area for ~15 sec
5. It's Unclear if upload is in progress

browser shows drop-area for ~15 sec
![screenshot_001433](https://github.com/owncloud/web/assets/26610733/9cb0296e-1f5f-44aa-a052-2748174d7cd8)

### Expected behaviour
Show top loading bar if the system is working (so that the user does not start to click around / knows the system is working etc.)

### Actual behaviour
browser shows drop-area for ~15 sec

**Comment by tbsbdr** [comment]
Marking as error, as this leads to erroneous results (although performed by the user)

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9552.
