### ISSUE TITLE
Drop on secret file drop pages is broken

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9464]
### Steps to reproduce
1. Create a secret file drop for a folder
2. Open it in an unauthenticated context
3. Try to drop a file -> it won't work. No errors whatsoever.

**Comment by ChrisEdS** [comment]
There is a PR for the feature, good opportunity to work from there? https://github.com/owncloud/web/pull/8511

**Comment by JammingBen** [comment]
We want to get the fix done quickly so it lands in the upcoming release. Iterating over the design changes would take more time. We still have that on our roadmap of course though 🙂

**Comment by jacob-nv** [comment]
@JammingBen No luck trying to recreate this issue. Could you send quick video? Thanks

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9489.
