### ISSUE TITLE
Cloud importer. uploading files message in the cloud list selection 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#9469]
test on https://0001.schule.owncloud.works/

web 3.1.0-beta.1+16f54d9bb
backend 7.1.0-rc.1

Steps:

- upload a few files (that doesn't fit security policies or a big files) 
- close uploading message and try to upload using import

Actual: uploading windows opens. Why? is that how it's designed? 
![image](https://github.com/owncloud/web/assets/84779829/eea7beca-bea5-466f-a465-52cadf2deb11)

https://github.com/owncloud/web/assets/84779829/9de86cad-6770-4458-aba5-17e4444237fb

Expect: no uploading window

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9471.
