### ISSUE TITLE
[cloud importer] Retrying denied file clears the import dialog and upload-info dialog stays in loading state

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#9473]
Server: https://0001.schule.owncloud.works/
```
ownCloud Web UI 7.1.0-rc.1
Infinite Scale 3.1.0-beta.1+16f54d9bb Enterprise 
```
### Steps to reproduce
1. Try to import file that is not allowed by policy. e.g. `.treasure`
2. Error messages :heavy_check_mark: 

![Screenshot from 2023-07-24 18-13-07](https://github.com/owncloud/web/assets/52366632/322e693b-6d3d-42d6-8eeb-7bf7897f6adf) | ![Screenshot from 2023-07-24 18-14-32](https://github.com/owncloud/web/assets/52366632/1aa7e697-44aa-4f2d-a6ae-840c0a7a9a1a)
--|--

3. Open the import dialog again and click `Retry`
4. Import list is empty and upload-info dialog stays in loading state :x:

![Screenshot from 2023-07-24 18-14-09](https://github.com/owncloud/web/assets/52366632/accb7b13-653f-4f76-84b5-9636224b8bdb) | ![Screenshot from 2023-07-24 18-14-01](https://github.com/owncloud/web/assets/52366632/5ad7e9fe-2ab0-4d32-b3a9-c2ead9aaed29) 
--|--

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9471.

**Comment by saw-jan** [comment]
The previous bug is no more but there are some flows that may not be expected
1. Try to import file that is not allowed by policy. e.g. `.treasure` :heavy_check_mark: 

![Screenshot from 2023-07-25 14-27-57](https://github.com/owncloud/web/assets/52366632/8e2857cd-0889-4f73-b440-2cea7233c76b) | ![Screenshot from 2023-07-25 14-28-29](https://github.com/owncloud/web/assets/52366632/ab602845-74e8-4683-91bd-c2b3433c208d)
--|--

2. Open the import dialog again (:question: no retry option like before)

![Screenshot from 2023-07-25 14-28-35](https://github.com/owncloud/web/assets/52366632/556016b2-4886-44fa-a7b1-fafbe3b7d143) | .
--|--
3. Try to import same file (:question: list is blank and upload-info dialog has no error)

![Screenshot from 2023-07-25 14-28-52](https://github.com/owncloud/web/assets/52366632/e1e50950-1fe8-4f8f-a00a-302cbd2b2683) | ![Screenshot from 2023-07-25 14-28-56](https://github.com/owncloud/web/assets/52366632/b79ef44f-10e7-4b0f-bb63-7f4818ad6e82)
--|--

**Comment by JammingBen** [comment]
Good catch! This is probably because of https://github.com/owncloud/web/issues/9472

**Comment by saw-jan** [comment]
So then, it will be fixed with that issue?

**Comment by JammingBen** [comment]
I assume so, yes.

**Comment by saw-jan** [comment]
Great!

**Comment by saw-jan** [comment]
Issue followup in https://github.com/owncloud/web-extensions/issues/167
