### ISSUE TITLE
PDFs can't be opened with Safari

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9483]
### Steps to reproduce
1. Upload a PDF file
2. With Safari, open the PDF file by clicking it -> endless loading spinner. Console reports nothing. Re-loading the page correctly loads the PDF file.

**Comment by lookacat** [comment]
couldn't debug it because it freezes and after googling for a similar issue i didn't find anything.
My approach would be to try to build a MVP pdf viewer as we have it (just quick hacking) and see if and where the problem begins to occur since the pdf viewer in safari generally should probably work

**Comment by dschmidt** [comment]
Maybe worth testing with #8857 as that changes loading and app initialization quite a bit (and this does not happen on page reload, so it might be an initialization issue after all)

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9565.
