### ISSUE TITLE
[oc10][QA] Büro (from richdocuments) cannot be opened with web

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#9488]
Seen with core 10.12.2 and web 7.0.2 and richdocuments 4.0.0-rc.3

* hook richdocuments into web, according to 
https://doc.owncloud.com/webui/next/owncloud_web/web_with_oc_server.html#collabora-online-integration
* test the [NEW] button, all the office file types are there, creating and editing with richdocuments works.
* click open the 9 dots menue
![grafik](https://github.com/owncloud/web/assets/1108546/d6b70f7f-9bc7-4fd2-bc4e-014192ba6c78)
----
* There is a 'Büro' entry there. Click this.
![grafik](https://github.com/owncloud/web/assets/1108546/226ea2d2-3222-46da-8133-ccdb950da600)
---
* The page does not load. A javascript error occurs. BAD

**Comment by jnweiger** [comment]
Expected behaviour:
* verified on a different machine, where web is not installed:
![grafik](https://github.com/owncloud/web/assets/1108546/bbf67bb3-d791-44ba-967b-4064b78fe75a)

**Comment by JanAckermann** [comment]
Closing as we discontinued the support for oc10 in web. If you feel this is super important and we need a bugfix for an older major version please reopen.
