### ISSUE TITLE
Move "Set expiration date" action to 3-dots-menu

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9493]
The "Set expiration date" action when adding shares should be moved to a 3-dots-menu next to the "Share" button. See this mock up:

<img width="401" alt="image" src="https://github.com/owncloud/web/assets/50302941/3a21a812-773c-415b-9a87-1358744169c5">

**Comment by tbsbdr** [comment]
Note: `Deny Access` toggle will move to this menu also later. (does currently not exist on this level)
