### ISSUE TITLE
[Spaces] Broken view if you access a disabled space

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#9497]
### Steps to reproduce
1. Share a space via public link
2. Disable the space
3. Try to access it via the created link

### Expected behaviour
A useful message will be shown

### Actual behaviour
![image](https://github.com/owncloud/web/assets/33026403/5a738122-66b0-4d3a-9bcf-3e83f59ce7c0)

### Environment ownCloud Infinite Scale
**Version:**
Infinite Scale 3.0.0

**Comment by JanAckermann** [comment]
Also happens on deleted file shares
