### ISSUE TITLE
public links in authenticated context. Don't open file in the text editor 

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#9578]
web: 7.1.0-rc.3
ocis: 3.1.0-rc.1

Steps: 

- admin creates `f1/fileInPersonal.txt`
- admin shares `f1` folder to einstein
- admin creates link to file `fileInPersonal.txt`
- einstein accepts `f1` folder and opens link

Actual: file fileInPersonal.txt opens direct in the text editor

Expected: einstein jumps to shared folder `f1` and `fileInPersonal.txt` file is selected
<img width="711" alt="Screenshot 2023-08-15 at 23 16 39" src="https://github.com/owncloud/web/assets/84779829/4c6f2f47-47dd-44fa-876f-be640be8a308">

cc @JammingBen

**Comment by JammingBen** [comment]
Has been fixed via https://github.com/owncloud/web/pull/9587.
