### ISSUE TITLE
Redirection to personal space after closing file in the shared folder

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#9579]
web: 7.1.0-rc.3
ocis: 3.1.0-rc.1

use https://ocis.ocis-web.latest.owncloud.works/

Steps:

- admin shares folder `f1` to einstein (editor role)
- einstein accepts `f1` folder and creates new `file.txt` inside of the folder
- einstein closes the text editor

Expected: Einstein stays in the f1 shared folder.

Actual: redirect to personal space

https://github.com/owncloud/web/assets/84779829/7e1b1aa4-666c-4799-acda-c3a6c40eab7b

**Comment by JammingBen** [comment]
Closing here as this has been fixed meanwhile.
