### ISSUE TITLE
Retain User Preferences for Left and Right Side Bars

### ISSUE THREAD

**Issue by dj4oC** [owncloud/web#9613]
**As** a heavy user of ownCloud Infinite Web,
**I want** the application to remember my side bar preferences,
**So that** I don't have to manually adjust them every time I log in or browse through Spaces.

**Acceptance Criteria:**

1. **Left Side Bar Memory:** 
   - When I minimize the left side bar, the application should remember this choice.
   - Upon my next login or when I navigate through different sections of the platform, the left side bar should remain minimized unless I choose to expand it.
   https://github.com/owncloud/web/pull/10611

2. **Right Side Bar Persistence:** 
   - I want the right side bar to be always visible, regardless of where I navigate within the web ui (i.e. also across apps)
   - The platform should remember this preference, ensuring the right side bar remains visible during all my life until I decide otherwise.
   - Upon navigation, the right sidebar switches back to the respective root panel for the current view (added by @kulmann )
   - Make the look and feel of the right sidebar and text-editor equal (added by @AlexAndBear)
   - Add default panels for files-trash and admin-settings -> general (added by @AlexAndBear)
https://github.com/owncloud/web/pull/10612

**Comment by pascalwengerter** [comment]
@dj4oC would client-side retaining of preference be sufficient, or should it be saved within the user's settings on the server?

**Comment by dschmidt** [comment]
How would we retaining it client side when sessions timeout and all storage is in sessionStorage (by default)?

**Comment by dj4oC** [comment]
Imho it should be stored in the browser since I do have different displays with different sizes and resolutions. 

Secondly with k8s we cannot store extra parameters after deployment.

**Comment by dj4oC** [comment]
> How would retaining it client side work when sessions timeout and all storage is in sessionStorage (by default)?

Cannot we use both storage? Depending on the necessity of the specific story?

**Comment by pascalwengerter** [comment]
@dschmidt my suggestion would have been to store it in the localStorage (like the theme choice also) so at least it survives page reloads and (re-)login?

**Comment by kulmann** [comment]
> How would retaining it client side work when sessions timeout and all storage is in sessionStorage (by default)?

Our other viewOptions are always persisted into the `localStorage` for the very reasons that @dj4oC mentioned. We want those options to live longer than the browser session, so the option mentioned in the issue description would also belong in the `localStorage` in my opinion.

**Comment by kulmann** [comment]
There was a feedback survey submission today, stating `Sidebar/view details panel doesnt stay open (would be desirable as a persistent setting)`. So basically a +1 on this issue.
