### ISSUE TITLE
PDF are loaded twice

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#9617]
### Steps to reproduce
1. upload a PDF file
2. view the PDF file in ocis/web

### Expected behaviour
the file is requested once from the server and send to the browser

### Actual behaviour
the file is loaded twice from the server
![grafik](https://github.com/owncloud/web/assets/2425577/22d7a964-288c-4b7b-85c8-694a31650192)

### Environment general
**Operating system**:
Ubuntu 22-04

**Backend (ownCloud Core or Infinite Scale)**:
ocis

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Environment ownCloud Infinite Scale
**Version:**
ocis 4.0.0
Web-Client-Version | 7.1.0

**Updated from an older Infinite Scale or fresh install:**
updated from 3.1 dev

**Where did you install Infinite Scale from:**
docker

### Client configuration
**Browser:**
Firefox

**Operating system:**
Ubuntu

**Comment by dschmidt** [comment]
https://github.com/owncloud/web/pull/9485

Should fix this

**Comment by jacob-nv** [comment]
The issue has been resolved on the current master
