### ISSUE TITLE
Icon on details page, when no file is selected, suggests a drag and drop interaction

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/web#9642]
![image](https://github.com/owncloud/web/assets/200626/4911df0a-a970-444d-a92b-f013648cfcb6)

Suggestions:
![image](https://github.com/owncloud/web/assets/200626/2352fd51-2a8e-48d0-93e4-6ec14ded8a4d)
![image](https://github.com/owncloud/web/assets/200626/413d1d3d-e69e-4e07-a3e6-30eb5752ac99)

See: https://talk.owncloud.com/channel/web?msg=wxGYbmmyrEqzzqSAo

@tbsbdr @JanAckermann

**Comment by tbsbdr** [comment]
closing in favour of: https://github.com/owncloud/web/issues/9643
