### ISSUE TITLE
"Select a file or folder to view details" Icon is missleading

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9643]
### Steps to reproduce
1. open right sidebar in web ui (no resource selected)
2. Icon is missleading

![screenshot_001623](https://github.com/owncloud/web/assets/26610733/b6d723ef-5b13-4af2-beb4-d251f7237cb8)

### Expected behaviour
- show the info-icon instead

![image](https://github.com/owncloud/web/assets/26610733/6cee9912-3a37-4e6e-92bc-7343356fb5ee)

### Actual behaviour
- Icon is missleading

**Comment by JanAckermann** [comment]
This has been solved elsewhere
