### ISSUE TITLE
[QA] web-7.0.3 at oc10 always has new -> drawio button

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#9656]
Seen with 10.13.1-rc.1 and enabled web 7.0.3 and disabled drawio  1.0.1

* fresh installlation, drawio app never enabled.
* switch to the classic UI, no drawio icon is shown. OK
* with the classic UI, the [ + New ] menu has no drawio entry. OK
* switch to the new web UI, the [ + New ] menu button has an entry `Draw.io-Datei` - BAD. 
* with the new web UI, upload a *.drawio file -> the orange drawio icon appears with the file. It better should not be recognized when drawio is diabled. OKish
![grafik](https://github.com/owncloud/web/assets/1108546/665b9c5e-9d24-4702-917c-2c4f4513128b)

**Comment by jnweiger** [comment]
While drawio app is disabled in oc10, clicking new -> 'Draw.io-Datei` (either runs into #6988 or when the index.php issue does not occur)
this error is to be expected:
![grafik](https://github.com/owncloud/web/assets/1108546/1de0cd42-f69f-42c8-80a1-70a366ca7a39)

**Comment by JammingBen** [comment]
How does your Web `config.json` file look like? I assume `draw-io` is included in `apps`...?

**Comment by jnweiger** [comment]
Ah, you are right, of course. I always forget that all this is a static config only.
