### ISSUE TITLE
Pagination Footer: Current Page is Highlighted Twice

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9665]
### Steps to reproduce
1. Upload ex. 500 files, set pagination size to 20
2. click on "1" then "2" then "3" ... "5"
3. Current page is highlighted twice: "5" and "6" are highlighted

![screenshot_001635](https://github.com/owncloud/web/assets/26610733/83634198-cee3-4926-b887-fee8e253da0e)

### Expected behaviour
Only "5" should be highlighted as current page

### Actual behaviour
- Current Page is Highlighted Twice

**Comment by lookacat** [comment]
it seems like an issue with :active or sth, if i want to inspect the wrongly highlighted page the highlighting is gone
