### ISSUE TITLE
[Web] Password Generator for Links

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9666]
# Description

## User Stories

* > As a user who needs to enter a password I want the UI to generate a compliant password so that I don't need to figure out a password by myself.

## Value
- improve security

## Acceptance Criteria
- Always show the "generate" icon within a password-field (icon: `sparkling-2-fill`)
- Click on the icon generates a new password (if a password exists already, it gets overwritten)
- If the password needs to comply with a policy, the generated password complies with the policy;
- If no policy is required, the generated password contains latin letters and has an entropy of >80 bits (try: https://www.omnicalculator.com/other/password-entropy)
- Toopltip: "Generate a password"

![image](https://github.com/owncloud/web/assets/26610733/3431c6bf-d3c3-49dc-a46a-860322fdc655)

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

**Comment by JanAckermann** [comment]
I want to take over as soon as this is actionable.

I would suggest using this lib, https://www.npmjs.com/package/generate-password

it will work well with out password policies
