### ISSUE TITLE
Direct share indicator gets overwritten

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9712]
### Steps to reproduce
1. Create a folder and upload some files to it
2. Open the folder and share one of the files with another user -> it will get a user sharing indicator in the table (good!)
3. While being inside of the folder, share the folder itself via a link (via the breadcrumb context actions) -> all resources get a link sharing indicator in the table (good!), the user sharing indicator for that one resources goes missing (bad!)

**Comment by jacob-nv** [comment]
This seems to work. Am I doing something wrong?


https://github.com/owncloud/web/assets/138569835/aa5a2a17-d6f4-46ca-b519-3e96d69dcc7a

**Comment by JammingBen** [comment]
Can't reproduce either anymore -> closing.
