### ISSUE TITLE
Sidebar preview gets confused for folders

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9713]
### Steps to reproduce
1. Upload an image to your personal space
2. Create a folder in your personal space
3. Open the details panels for the image
4. Select the folder resource while keeping the sidebar open -> the folder will wrongfully show the image preview

**Note:** Fix needs to target `stable-7.1`.

**Comment by jacob-nv** [comment]
@JammingBen Could you please record short video reproducing the bug? Somehow I'm not able to reproduce it. Sorry for inconvenience

**Comment by JammingBen** [comment]
Sure, here it is: 

https://github.com/owncloud/web/assets/50302941/c124e0b0-65ac-42d5-b1ba-4af242c7f659

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/web/pull/9732.
