### ISSUE TITLE
[web] Show WebDAV Paths in web UI

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9714]
# Description

## User Stories

* > As a user who wants to access ocis via a webdav client software, I want an option to copy the webdav path for any resource so that I don't have to knit together the path manually.

## Acceptance Criteria
- show webdav path for every folder in the resource details, including space roots
  - Path is truncated
  - path can be copied via click on the copy icon
- option is disabled by default
- option can be activated via account page 
  - New Account page section "**Preferences**"
  - [checkbox] `Show WebDAV path`
  - move `Language` to section "**Preferences**"
  - move `Notification setting` to section "**Preferences**"
- It's okay if the option `Show WebDAV path` is stored in the localstorage rather than on the backend; should be stored in the backend in the future, but this is not part of this story.

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

## Visuals
![image](https://github.com/owncloud/web/assets/26610733/bb50eaf6-2ae4-48a4-bf15-26b247a09c9f)
![screenshot_001973](https://github.com/owncloud/web/assets/26610733/de25ab62-5c61-4fc7-b0e4-193ad58b3e21)

**Comment by michaelstingl** [comment]
> > As an admin I want to copy webdav paths so that I can use them eg. in my cli.
> 
> note: other than in oc10, in ocis we have multiple path (one per space)

Not only admins needs this. Every user that wants to use 3rd party WebDAV clients or CLI tools needs to know the WebDAV URL. Add it to the details?

![CleanShot 2023-11-02 at 14 08 45](https://github.com/owncloud/web/assets/214010/e2ab28bd-bb1f-41ed-b510-da22105dface)

**Comment by tbsbdr** [comment]
updated initial comment

**Comment by michaelstingl** [comment]
> * I want an option to copy the webdav path for any resource

Folders and Spaces I'd say. Not relevant for files from my POV.

**Comment by JanAckermann** [comment]
> > * I want an option to copy the webdav path for any resource
> 
> 
> 
> Folders and Spaces I'd say. Not relevant for files from my POV.

I'd rather keep it consistent everywhere
