### ISSUE TITLE
Web can only receive one `sse` event

### ISSUE THREAD

**Issue by kobergj** [owncloud/web#9742]
Something seems fishy with webs `sse` connection. Only one event is received, then the connection is stale and needs a reconnect to get more events.

Steps to reproduce:
- run any ocis version that has `sse`s enabled (e.g. current master but is reproducible with all versions > 4.0)
- make sure to have `OCIS_SERVICE_ACCOUNT_ID` and `OCIS_SERVICE_ACCOUNT_SECRET` set (or run ocis init)
- login with marie and einstein in two seperate windows
- as marie share a file with einstein
      -> einstein will receive a notification
- as marie remove the share with einstein
     -> einstein will NOT receive a notification
- as einstein reload the page
- as marie share the file again with einstein
    -> einstein will receive two notifications (the missing file_unshared and the new file_shared)

Remark:
The web shows no additional logs and the sse connection seems to be ok (if you ask to the network tab). 
Note that this could be very well be bug on server side, but I cannot reproduce the issue using `curl` or `postman` connected to the `sse` endpoint (they will receive all events immediately).

We need to find out why the web `sse` connection is different from the one opened through postman.

**Comment by JammingBen** [comment]
I see that the structure of the data the server sends has changed (I assume via https://github.com/owncloud/ocis/pull/7325). Web checks for `notification_id`, which is now inside `data` - hence it doesn't work.

Strange though that the first notification still works for you 🤔 For me it's not working at all.

**Comment by kobergj** [comment]
Mmmh. Strange but ok. I'll wait for web implementation and retest again!
