### ISSUE TITLE
Copy action breaks file list for public links

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9765]
### Steps to reproduce
1. Create a public link with edit permissions for a folder including a file and another folder
2. Open the public link
3. Copy the file from the file list
4. Navigate into the folder -> the file list breaks

<img width="546" alt="image" src="https://github.com/owncloud/web/assets/50302941/98612ebd-da1a-4e69-b533-e17dfa43acc7">

**Comment by jacob-nv** [comment]
@JammingBen Could you record video of this? Trying to reproduce steps, but could not get error
