### ISSUE TITLE
[QA] Deleted tests listed in expected-failure list are not reported by run.sh

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#9778]
Some tests like `webUISharingExternal/federationSharing.feature` was deleted in PR https://github.com/owncloud/web/pull/9751. They are also listed in the expected failure list but after the deletion of those test suites, run.sh should report those tests as passing but CI stays silent.

Fix run.sh so that not existing tests are listed as unexpected passing and we don't forget to remove deleted tests from the list

**Comment by phil-davis** [comment]
Note: each pipeline runs a suite (or suites) and therefore has only run the scenarios for those suite(s). So `run.sh` can check that every scenario from those suites that is expected to fail, did fail.

If there are scenarios in expected-to-fail from a suite that does not exist any more, then there will not be any pipeline that runs that suite.

So it will be tricky to fix this problem. I suppose that `run.sh` can parse the whole expected-failures file and report any expected-failure lines that refer to a suite/feature file that does not exist at all. That can happen early (before running any tests), and will cause all acceptance test pipelines to fail quickly.

**Comment by saw-jan** [comment]
Closing as completed
