### ISSUE TITLE
[web] Open shares without having to accept it

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9784]
# Description

## User Stories

* > As a user I don't want to accept shares so that I can just klick on a share to access it.

## Acceptance Criteria
- klick on a share shows the resource
- no "accept" aka "sync" needed

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

**Comment by tbsbdr** [comment]
depend on  Sharing NG and #9709

**Comment by tbsbdr** [comment]
depends on sharing NG

**Comment by tbsbdr** [comment]
@JammingBen could you list what would be needed to move this issue forward?

**Comment by JammingBen** [comment]
> @JammingBen could you list what would be needed to move this issue forward?

@dschmidt Do you know from the top of your head? 🤔 I need to dig into this topic again...

**Comment by JammingBen** [comment]
Okay so I digged into it, looks like we have all the necessary information from the server now. So all that's necessary is to get started in Web.
