### ISSUE TITLE
Password policy e2e test

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#9795]
![Screenshot 2023-10-11 at 16 36 22](https://github.com/owncloud/web/assets/84779829/8bdcb08c-321b-442b-a9ba-5b012c978ff4)

we implemented feature banned password list and `docker-compose.yml` contains this env 
`FRONTEND_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: '/etc/ocis/password-policy-banned-passwords.txt'`

- [x] implement test for entering password for public link
in the test we can use existing password in banned-paswword-list like: `password` or `12345678` https://github.com/owncloud/web/pull/9798

![image](https://github.com/owncloud/web/assets/84779829/9cfd1b18-db0b-490c-bebf-8be661181320)
 
- [x] implement steps for new buttons: hide/show password, copy to buffer, generate password and use this step in existing tests https://github.com/owncloud/web/pull/9820

cc @individual-it @saw-jan  @grgprarup

**Comment by saw-jan** [comment]
Done in https://github.com/owncloud/web/pull/9798 and https://github.com/owncloud/web/pull/9820
