### ISSUE TITLE
[web] Create Shortcuts: webpage

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9796]
# Description

## User Stories

* > As a user I want to create shortcuts so that I don't need to remember the location of a resource or webpage.

## Acceptance Criteria
- Add new option `+ New` > `Shortcut`
- Click on `Shortcut` opens a dialog "Create a Shortcut"
- Initial dialog shows a form "Shortcut to a webpage"
- 1. Scenario "**Webpage**"
  - Form "Shortcut to webpage or file" is used as href eg. "owncloud.com" 
  - Form "File name" is prefilled with "owncloud.com" but can be edited by the user
  - Button `Create` creates owncloud.com.url
  - click on owncloud.com.url in the filestable opens new tab

  - Button `Create` creates `ideas.url`
  - click on `ideas.url` in the filestable opens the url in the same tab
 - check if any security measurements are necessary when opening links (maybe simple URL decoding is sufficient?)

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

### Scenario "**Webpage**"

1. **Initial** ![image](https://github.com/owncloud/web/assets/26610733/17ddd6a6-d47f-4da4-8f7a-773ae438d2e9)
2. **Webpage with searchresults** ![image](https://github.com/owncloud/web/assets/26610733/08cda5f2-324a-4050-9957-7b4423b5975d)
3. **External URL no more searchresults** ![image](https://github.com/owncloud/web/assets/26610733/44d61663-cbd1-4e3f-af6d-03f884a8fe9a)

### Scenario "**Resource**"

1. **Initial** ![image](https://github.com/owncloud/web/assets/26610733/d810d31e-3cf1-4da0-8dae-3e793e9005bd)
2. **Internal URL with searchresults** ![image](https://github.com/owncloud/web/assets/26610733/8e40bb5b-54fd-4fb5-9abe-41f6fa9aa205)
3. **Internal URL focused** ![image](https://github.com/owncloud/web/assets/26610733/edcf1cef-18f7-4f86-b2fb-d6eb89cee3c3)
4. **Internal URL selected** ![image](https://github.com/owncloud/web/assets/26610733/c4e5c678-aeed-472d-9df7-0d59582f9e66)

**Comment by michaelstingl** [comment]
`*.url` files should work across clients. Ping me when implemented, the clients teams can do a quick round of QA…
