### ISSUE TITLE
Integrate file editors in application menu

### ISSUE THREAD

**Issue by lookacat** [owncloud/web#9807]
### Description
Goal: Integrate apps like onlyoffice/collabora and other editors into the application menu. Faster access to the app without having to manually create a file first.
MVP: Texteditor in the application menu, create empty file in current folder, open with default app.

**Comment by JanAckermann** [comment]
Notes:

Ordner wo ich Schreibzugriff habe, soll die Datei dort abgelegt werden 
Ordner wo ich nicht schreiben kann personal root 
Wie reflektieren wir den Speicherort ? Location ähnlich suche 
Leere Dateien abspeichern
