### ISSUE TITLE
[oC10] Logout action while using ownCloud 10 backend doesn't work

### ISSUE THREAD

**Issue by xoxys** [owncloud/web#9812]
### Steps to reproduce
1. Run ownCloud 10 with ownCloud Web (We run both as container service instead of using the oc10 app)
2. Click "Logout" in Web 

### Expected behaviour
Successful logout.

### Actual behaviour
![image](https://github.com/owncloud/web/assets/3391958/7af0a3b4-3499-4301-b55c-1fc4ee8ab19a)

### Environment general
**Operating system**:

**Backend (ownCloud Core or Infinite Scale)**: owncCloud Core

### Environment ownCloud Core
**Version:** v10.13.1

**Comment by JammingBen** [comment]
Closing here since Web dropped support for oC10 with version 7.1.0. Workaround for this specific issue: logout from the old UI.
