### ISSUE TITLE
[Preview app] image preloading broken

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#9838]
### Steps to reproduce
1. Upload some images
2. Open one of the in the preview app
3. Observe the network requests, images get preloaded

### Expected behaviour
Navigating from the current image to the next or previous doesn't fetch the image and doesn't show a loading spinner

### Actual behaviour
Navigating from the current image to the next or previous fetches ~~the image~~ something (again?!) and shows a loading spinner

**Comment by jacob-nv** [comment]
@kulmann @jacob-nv 

Images are not getting fetched again. Those images comes form URL so if you have disabled cached, you will download it again.
Request coming from switching between images are PROPFIND requests.
Why the spinner is still displaying comes down to 2 things.
1. Somewhat of a fake timeout
![fake_timeout](https://github.com/owncloud/web/assets/138569835/e58571fc-fe52-4ec1-8d1d-fd799b18cdd0)
2. Setting image as active
![set_image](https://github.com/owncloud/web/assets/138569835/2cf13a6e-478d-455d-a972-f7d66ec864ca)

Both of these states contribute to spinner displaying
![spinner-condition](https://github.com/owncloud/web/assets/138569835/84eaf54d-d856-49a1-8ed3-8374f72256c7)

The timeout could be removed if activeMediaFileCached exists
