### ISSUE TITLE
[web][preview app] reset image position in image container

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#9840]
## User story
> As a user who works a lot with photos / images, after panning the image in the image container I would like to reset the image position to the center of the image container, so that e.g. rotation doesn't look weird. 

## Steps
1. Upload an image
2. Use the super smooth new mouse panning in the image container to move the image to another position on the screen
3. Try to reset the image position to the center of the image container

## Acceptance criteria
- having a button to reset zoom and position
- unit test

**Comment by JanAckermann** [comment]
Do we need to have 2 separate buttons or can we use the existing reset zoom one ?

**Comment by JanAckermann** [comment]
![image](https://github.com/owncloud/web/assets/26169327/25962db5-55b2-417b-80ba-999007cf2979)
@tbsbdr added the new button all to the right, could you please provide a better text and icon?

Button will reset rotation, position and zoom
