### ISSUE TITLE
[web] Provide dedicated, vendor-neutral icons

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9847]
# Description

## User Stories

* > As a user I want different Icons for different file extensions so that I can easily differentiate between eg. docx and ods.

## Value
- improve usabiliy
- position ocis as vendor neutral platform

## Acceptance Criteria

Provide new icons for
- Document (docx & odt)
- Spreadsheet (xlsx & ods)
- Presentation (pptx & odp)
- Forms (docf & oform)
- Markdown (md & markdown)

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

**Comment by tbsbdr** [comment]
yes, I need to create / find fitting ones.

**Comment by lookacat** [comment]
ping me if you have something, would exchange them

**Comment by tbsbdr** [comment]
[Neutral Icons plus Forms plus Markdown.zip](https://github.com/owncloud/web/files/13244332/Neutral.Icons.plus.Forms.plus.Markdown.zip)


Screenshot:
![screenshot_001874](https://github.com/owncloud/web/assets/26610733/82b631bb-ecfb-4f37-be02-ccbf6856b1b1)
