### ISSUE TITLE
[web] Share with federated users

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9852]
see @JammingBen comment

**Comment by JammingBen** [comment]
The basic feature has already been implemented via https://github.com/owncloud/web/pull/9896. However, the whole thing is not yet productized and is missing a few things for that to be possible:

* [ ] finish server implementation on our side (there are still some bugs)
* [ ] add dev docs on the app and how to run the setup
* [ ] Add `ocs.openRemotely` config to oCIS
* [ ] Add `ocs.openRemotely` config to our dev docs
* [ ] Redesign the ocm web app @tbsbdr 
* [ ] Add tests (unit and e2e)

**Comment by tbsbdr** [comment]
obsolete in meantime
