### ISSUE TITLE
show FUSE/Windows/Direct Paths on Project-Details

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9865]
subtask of: https://github.com/owncloud/web/issues/9308
Add extension-point 
![screenshot_001841](https://github.com/owncloud/web/assets/26610733/4a3491a5-00fd-498b-b237-5e416c0da0a9)

**Comment by JammingBen** [comment]
We've implemented a `portal-target` which will be filled via an extension: https://github.com/cernbox/web-extensions/pull/25. This means this is done on our side.
