### ISSUE TITLE
Dev docs for extension framework

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9892]
The Web extension framework needs proper dev documentation, talking about the following (at least):

* [x] Which entry points for extensions do we have, meaning what can be extended https://github.com/owncloud/web/pull/10400
* [x] Provide example for each available extension type (https://github.com/owncloud/web/pull/10906)
* [x] How can portals be used by extensions,  see https://github.com/owncloud/web/pull/10400#pullrequestreview-1841034066

**Comment by kulmann** [comment]
Related: https://github.com/owncloud/web/issues/2423

**Comment by tbsbdr** [comment]
Adding examples would be great :)
