### ISSUE TITLE
e2e tests for url stability

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#9897]
## Description
Clients rely on URLs being correctly resolved in ownCloud Web for some features. We had some regressions recently (see links below), so I'd like to make sure with some new e2e tests that URLs in ownCloud Web resolve reliably.

### Recent regressions
1. https://github.com/owncloud/web/issues/9868
2. https://github.com/owncloud/web/issues/9867
3. https://github.com/owncloud/web/issues/9804

## New e2e tests

I'd like to see a new URL journey in web with at least the following features. Open for suggestions for additional features.

### File details panels (regression no. 1)
The right sidebar within the files app holds a few details panels like `details`, `sharing` or `versions`. Clients can open the web ui in the file list with the `versions` panel opened in the right sidebar by appending `?details=versions` to the private link. Same for the sharing panel by appending `?details=sharing` to the private link. This behaviour must remain stable.

### Resolving all plain private links (regression no. 2)
Clients have a feature for showing a file or folder in the web browser. This opens the private link (without additional url params) in the web browser. Currently the default behaviour of ownCloud Web is, that it shows the file in the file list if there is no editor for the file. And it opens the default viewer/editor for the file if there is one. This is fine like it is. A new e2e test should check that private links open in the web ui for cases: a) a file without viewer/editor, b) a file with viewer/editor, c) a folder, d) the root of a space, e) the (hardcoded!) share jail id. The last one (share jail) is an edge case which is currently broken. It can't resolve in web, because there is no file listing which shows the share jail itself as a child element. So this needs to redirect to the shared with me page (currently broken).

### open-with-web endpoint (regression no. 3)
Clients can make a request to the `open-with-web` ocis endpoint to obtain the browser URL for opening the respective file in an app from the app provider, e.g. opening a file in OnlyOffice. Was recently broken, this is a very important product feature and must remain stable.

**Comment by kulmann** [comment]
@ScharfViktor do you have additional URL related features in mind that should be represented in this journey?

**Comment by kulmann** [comment]
@tbsbdr Fine to add this to one of the next sprints? I'd like to give this into the hands of @ScharfViktor

**Comment by kulmann** [comment]
@michaelstingl cc

**Comment by SwikritiT** [comment]
Hi @kulmann for the 3rd regression
I tried getting the URL using the for collabora with following curl request

```
 curl -XPOST "https://host.docker.internal:9200/app/open-with-web" -d"file_id=<file-id>&app_name=Collabora" -vk -uadmin:admin
```
Which gives me following response
```
{"uri":"https://host.docker.internal:9200/external?app=Collabora\u0026contextRouteName=files-spaces-personal\u0026fileId=<file-id>"}
```

As you can see the `&` is not sanitized it's still sent as the unicode number, is this the expected response , is it converted to `&` on client side or should this be a server issue?

**Comment by SwikritiT** [comment]
for the e2e test for this case `a file without viewer/editor` how can the editor is enabled in CI and locally is there any command that I can use to disable the editor for tests? Or does it require writing the new config file entirely?

cc @kulmann @ScharfViktor

**Comment by ScharfViktor** [comment]
> for the `Resolving all plain private links (regression no. 2)` to write e2e test for this case `a file without viewer/editor`, the editor is enabled in CI, and locally. Is there any command that I can use to disable the editor for tests? Or does it require writing the new config file entirely?

together with @SwikritiT we decided to use a file for this case for which type there is no editor

**Comment by ScharfViktor** [comment]
close, as in completed
