### ISSUE TITLE
Run e2e tests against ocis with keycloak as idp

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#9904]
Follow up of https://github.com/owncloud/web/pull/9518

**Reasons:**
- during the release process we run e2e tests on different instances, except only keycloak.
- the idea of running e2e on a k8s cluster, where we have an instance as similar to production as possible, where we track metrics and where k6 tests are already running

what e2e test should have (using keycloak admin console api):
- ~[ ] add users to group~ (https://github.com/owncloud/ocis/issues/5538)
- ~[ ] delete users from group~ (https://github.com/owncloud/ocis/issues/5538)
- [x] change user role (https://github.com/owncloud/web/pull/10119)
- skip features: https://github.com/owncloud/web/tree/master/tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature https://github.com/owncloud/web/tree/master/tests/e2e/cucumber/features/smoke/admin-settings/groups.ocis.feature

**Comment by PrajwolAmatya** [comment]
- [ ] implement assigning role to user through keycloak https://github.com/owncloud/web/pull/10119

**Comment by PrajwolAmatya** [comment]
The groups created in oCIS are not accessed in the keycloak and vice versa. So, the addition of user to group and deletion of users from the group is not possible.
cc @ScharfViktor @saw-jan

**Comment by ScharfViktor** [comment]
addition of user to group is possible on keycloak admin panel
 
<img width="1454" alt="image" src="https://github.com/owncloud/web/assets/84779829/f86d47d8-51c7-4f1c-8442-765116a8fda3">

hmm but sharing to group (created in keycloak is not possible). maybe it's bug

**Comment by PrajwolAmatya** [comment]
> addition of user to group is possible on keycloak admin panel
> 
> <img alt="image" width="1454" src="https://private-user-images.githubusercontent.com/84779829/290465506-f86d47d8-51c7-4f1c-8442-765116a8fda3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDUxMjcsIm5iZiI6MTcwMjU0NDgyNywicGF0aCI6Ii84NDc3OTgyOS8yOTA0NjU1MDYtZjg2ZDQ3ZDgtNTFjNy00ZjFjLTg0NDItNzY1MTE2YThmZGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA5MDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNDM1ZWVhZDQ2NDliMmFjMWExODRmYTdlYjFjNDRlMTRhZDg5NDUwZTllYWI5MWMzZjM5NGM2MGZhZjYxYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hJiZ4Dukw-1oG8pbIJ9zeyvQb3oPSGpDhfLsKusCx9s">
> hmm but sharing to group (created in keycloak is not possible). maybe it's bug

yes, the create a user and add a user to the group but this created group information is not available in oCIS. The same thing other way around, we create a group in oCIS and this created group is not available in keycloak side.

**Comment by PrajwolAmatya** [comment]
I have created an issue for it https://github.com/owncloud/web/issues/10171

**Comment by saw-jan** [comment]
^
CC @wkloucek

**Comment by ScharfViktor** [comment]
I talked to @rhafer. It's not bug, it is feature request. Thanks for creating report

**Comment by rhafer** [comment]
Here's the existing feature request https://github.com/owncloud/ocis/issues/5538

**Comment by saw-jan** [comment]
Since group provisioning via Keycloak is not available yet we can work on e2e regarding groups after the feature has been implement.
For now, we will mark this ticket as done.
