### ISSUE TITLE
[web] Disable browser translations on content

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#9910]
# Description

## User Stories

* > As someone who uses the auto translate feature in a browser, I want content to not be translated, so that I don't see invalid data in my ownCloud.

## Value

- Auto translation doesn't mess with user generated content.
- Prevent errors caused via autotranslations 

## Acceptance Criteria
files app:
- file and folder names don't get auto translated
- space titles don't get auto translated
- space descriptions don't get auto translated
- user and group names (e.g. in sharing) don't get auto translated
- tags
- search results

user settings app:
- user, group and space names don't get auto translated

[probably more to be added] @tbsbdr 

## References
This issue has been around for quite some time in the oc10 classic ui and was fixed recently, see https://github.com/owncloud/core/issues/39946
The solution that was chosen was to forbid auto translation on the entire html document. For web this is not a good solution, as we don't have a good translation coverage, yet, and we will probably never have the same language support that auto translation offers. I'd be in favour of a solution where only the content gets protected, i.e. file names.

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by dschmidt** [comment]
As mentioned in the core ticket, there is https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate

**Comment by tbsbdr** [comment]
👍 updated to your initial comment

**Comment by kulmann** [comment]
Lessons learned:
- doing this "right" (i.e. only disable browser translations on user generated content) requires quite the amount of code changes for little value and would need to be strictly followed by any developer (core and community), which is very unlikely to happen.
- at the same time, doing this "right" (as described above) does not go well with the interpolation feature on our translations (i.e. defining translation templates and inject content at runtime, which is a mix of translatable and non-translatable content)

Then there is the choice of setting translate="no" on the entire html document or allowing browser translations also on user generated content. Forbidding browser translations leads to people not being able to use our software at all, as compared to being able to use it with flaws on user generated content.

We decided to allow all browser translations and effectively doing nothing (= closing the open pull request without merging).
