### ISSUE TITLE
[web+ocis] Make default link permission configurable

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9919]
# Description

## User Stories

* > As an Admin I want to set the default link permission so that it fits to the policy of my organisation.
* > As an Admin I want that ownCloud provides privacy by default so that I don't need to take care of privacy focused settings.

## Value
- provide privacy by default

## Acceptance Criteria
- provide an ocis config option + capability for the default link permission
- Options correlate to:
  - `Only for invited people`
  - `Anyone with the link can view`
  - (tbd: should we provide the other roles as well? I can hardly imagine usecases where `Anyone with the link can edit` should be the default)
  - **Default** correlates to `anyone with the link can view`, i.e. permission `1`
- Investigate: does a default link permission of `0` conflict with a default password policy? permission 0 links must always be created without password.

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by tbsbdr** [comment]
CC @michaelstingl

**Comment by kulmann** [comment]
I'm kind of confused by this story... the password story ( https://github.com/owncloud/ocis/issues/7682 ) is a good idea, but locking everything down in the first place seems to me like it will prevent successful/easy collaboration.

**Comment by tbsbdr** [comment]
@hodyroff what is your take on that?

**Comment by hodyroff** [comment]
I think as an admin I like to decide if the the default for my users shall be "invited people" or "link". Later the decision should be delegateable to Spaces and/or to Users (advanced settings). Default should be "invited users".
If its sysadmin as a first step, thats ok.

**Comment by tbsbdr** [comment]
Update: revised the initial comment; applied agile story-format;
