### ISSUE TITLE
Enabling the password requirement for the link breaks the "invite people via link" feature

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#9922]
related https://github.com/owncloud/ocis/issues/7682

## Steps: 
- run ocis with `OCIS_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD=true` (in my case It was as default)
- create folder and click by `copy link` button and set the required password for the link (by default we create link with viewer permission). That means user with role `user` cannot create link with 
- share folder to einstein 
- change link permission to `invited people`

## Expected
- `invited people` is on the list of roles for the link
-  If the link role gets downgraded from "anyone can..." to "Only Invited ...", password and exp. date gets removed from the link

## Current behaviour
no `invited people` in the list. You can only get this permission if you delete password for link (admin feature)
Note: using api we can create public link with permission `0` (invite people) without password: - is correct
![image](https://github.com/owncloud/web/assets/84779829/72b167dc-a0a5-4a3e-b255-90f5f7b1f087)

https://github.com/owncloud/web/assets/84779829/923f6974-5ec4-42eb-a1e8-6850fdcd95c7

**Comment by kulmann** [comment]
@ScharfViktor is it possible for a non-admin to update the link to `permission: 0` and removing the password on an API level? Then we could solve it web-only.

**Comment by tbsbdr** [comment]
update: added more details to expected behaviour in initial post of yours, @ScharfViktor

**Comment by ScharfViktor** [comment]
> @ScharfViktor is it possible for a non-admin to update the link to `permission: 0` and removing the password on an API level? Then we could solve it web-only.

yes, non-admin can update link 
![Screenshot 2023-11-09 at 11 45 43](https://github.com/owncloud/web/assets/84779829/60bf73dc-7909-47f0-9813-b94793cce5ab)

**Comment by kulmann** [comment]
@jacob-nv is this something you could take over?

**Comment by jacob-nv** [comment]
> @jacob-nv is this something you could take over?

For sure
