### ISSUE TITLE
Checking ocis cache script fails

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#9930]
When requesting to download ocis cache returned `403` status code. Doubt that we need to add authentication in curl 
command.

Informative sites:
- https://czak.pl/2015/09/15/s3-rest-api-with-curl.html
- https://www.burgundywall.com/post/upload-minio-curl
- https://gist.github.com/JustinTimperio/ae695eef5fda1f1590a685a017bbb5ec

Another way - use minio find command

**Comment by saw-jan** [comment]
Check if you can use minio image and do listing with mc and then search the desired cache in the list returned
