### ISSUE TITLE
Search field overlapped by current file info in top bar

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#9935]
## Describe the bug
On certain screen sizes the current file info in the top bar overlaps the search field, see Screenshot.

<img width="1056" alt="Screenshot 2023-11-14 at 08 21 42" src="https://github.com/owncloud/web/assets/3532843/12578cb8-8724-4d55-9e7c-38c163cf321e">

## Steps to reproduce
1. Open a .txt file in the text editor
2. Change browser viewport to e.g. 1050px width

## Expected behavior
No overlap of top bar elements at any time.

## Actual behavior
Current file info and search bar have an overlap.

## Possible solution
On mobile viewport sizes we collapse the search bar into an icon which then expands into the whole top bar width on click. We probably need to apply this behaviour to tablet sizes whenever the current file info in the top bar is visible...

**Comment by jacob-nv** [comment]
@kulmann Could you maybe send me video? I'm not really able to display current file info in text editor and search at the same time

**Comment by kulmann** [comment]
Seems to be a bug within my branch where I stumbled over the bug... sorry for the noise :-(
