### ISSUE TITLE
Shortcut: Add `Enter` to follow happy path

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9963]
## Steps to reproduce
1. Click on New --> Shortcut
2. enter owncloud.com
3. hit enter, nothing happens (needs 2 x tab or arrow down to move forward which is fine, but enter would be finer)

![screenshot_001940](https://github.com/owncloud/web/assets/26610733/a6b20cfc-9329-41e0-b17a-455fd3d4ce39)

## Expected behavior
- hit enter, https://owncloud.com should be committed as  URL

## Actual behavior
- hit enter, nothing happens

**Comment by dschmidt** [comment]
This report is valid, but I have a feeling we could also not handle this specifically here but have a generic solution for forms (in modals)
