### ISSUE TITLE
Clicking a .url file in the file list opens in external app

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#9968]
## Describe the bug
Clicking on a `.url` file in the file list should just follow the link inside the .url file, but opens the `external` app (i.e. OnlyOffice / Collabora / ...) instead.

## Steps to reproduce
0. Have an ocis instance running with OnlyOffice or Collabora via app provider
1. Create a Shortcut file, e.g. to `owncloud.com`, save it as `owncloud.com.url`
2. Right-click on the newly created shortcut file and select `Open shortcut` -> all good
3. Left-click on the shortcut file -> 💥 

## Expected behavior
`Open shortcut` should be the default action happening on left click in the file list.

## Actual behavior
The `external` app opens (and shows an error that the file can't be viewed or edited)

**Comment by JanAckermann** [comment]
Fixed via https://github.com/cs3org/reva/pull/4344

**Comment by kulmann** [comment]
Thank you! 🙏🏻
